-- LDR ecosystem additive foundations: stages 9-14
-- Mirrors migrations already applied to Supabase. No Stripe/payment execution changes.

create table public.ldr_work_preferences (
 user_id uuid primary key references auth.users(id) on delete cascade,
 active boolean not null default false, opportunity_types text[] not null default '{}',
 modalities text[] not null default '{}', country_codes text[] not null default '{}',
 competency_keys text[] not null default '{}', minimum_compensation_cents integer check (minimum_compensation_cents is null or minimum_compensation_cents >= 0),
 currency text check (currency is null or currency ~ '^[A-Z]{3}$'), updated_at timestamptz not null default now(), created_at timestamptz not null default now()
);
create table public.ldr_squads (id uuid primary key default gen_random_uuid(), owner_user_id uuid not null references auth.users(id) on delete cascade, project_id uuid references public.ldr_experience_projects(id) on delete set null, name text not null check(char_length(name) between 1 and 120), description text, status text not null default 'forming' check(status in ('forming','active','completed','archived')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.ldr_squad_members (id uuid primary key default gen_random_uuid(), squad_id uuid not null references public.ldr_squads(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, role_label text, status text not null default 'invited' check(status in ('invited','active','completed','left','removed')), joined_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(squad_id,user_id));
create table public.ldr_career_goals (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, target_title text not null check(char_length(target_title) between 1 and 160), target_country text, target_work_mode text, target_competency_keys text[] not null default '{}', status text not null default 'active' check(status in ('active','achieved','paused','archived')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.ldr_opportunity_recommendations (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, opportunity_type text not null check(opportunity_type in ('job','project','service','course','challenge')), source_reference uuid, title text not null check(char_length(title) between 1 and 180), rationale jsonb not null default '{}'::jsonb, status text not null default 'suggested' check(status in ('suggested','viewed','saved','dismissed','acted')), generated_at timestamptz not null default now(), expires_at timestamptz, created_at timestamptz not null default now());
create table public.ldr_ecosystem_links (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, source_type text not null check(source_type in ('proof','career_goal','job','project','service','course','squad')), source_reference uuid not null, target_type text not null check(target_type in ('proof','career_goal','job','project','service','course','squad')), target_reference uuid not null, relation_type text not null check(relation_type in ('supports','requires','produces','prepares_for','related_to','participates_in')), metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique(user_id,source_type,source_reference,target_type,target_reference,relation_type));
create table public.ldr_copilot_actions (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, context_type text not null check(context_type in ('career','learning','work','project','marketplace','portfolio')), context_reference uuid, action_type text not null check(action_type in ('learn','practice','prove','apply','offer_service','join_project','build_portfolio')), title text not null check(char_length(title) between 1 and 180), rationale jsonb not null default '{}'::jsonb, status text not null default 'suggested' check(status in ('suggested','accepted','dismissed','completed')), generated_at timestamptz not null default now(), expires_at timestamptz, created_at timestamptz not null default now());
create table public.ldr_market_radar_signals (id uuid primary key default gen_random_uuid(), signal_type text not null check(signal_type in ('skill_demand','job_demand','project_demand','course_gap','service_demand')), market_scope text not null, competency_key text, title text not null check(char_length(title) between 1 and 180), evidence jsonb not null default '{}'::jsonb, observed_at timestamptz not null, expires_at timestamptz, active boolean not null default true, created_at timestamptz not null default now());

alter table public.ldr_work_preferences enable row level security; alter table public.ldr_squads enable row level security; alter table public.ldr_squad_members enable row level security; alter table public.ldr_career_goals enable row level security; alter table public.ldr_opportunity_recommendations enable row level security; alter table public.ldr_ecosystem_links enable row level security; alter table public.ldr_copilot_actions enable row level security; alter table public.ldr_market_radar_signals enable row level security;
revoke all on public.ldr_work_preferences,public.ldr_squads,public.ldr_squad_members,public.ldr_career_goals,public.ldr_opportunity_recommendations,public.ldr_ecosystem_links,public.ldr_copilot_actions,public.ldr_market_radar_signals from anon;
grant all on public.ldr_work_preferences,public.ldr_squads,public.ldr_squad_members,public.ldr_career_goals,public.ldr_opportunity_recommendations,public.ldr_ecosystem_links,public.ldr_copilot_actions,public.ldr_market_radar_signals to service_role;
grant select,insert,update,delete on public.ldr_work_preferences,public.ldr_squads,public.ldr_squad_members,public.ldr_career_goals,public.ldr_ecosystem_links to authenticated;
grant select,update,delete on public.ldr_opportunity_recommendations,public.ldr_copilot_actions to authenticated;
grant select on public.ldr_market_radar_signals to authenticated;

create policy "work_preferences_own" on public.ldr_work_preferences for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy "squads_owner_all" on public.ldr_squads for all to authenticated using(owner_user_id=(select auth.uid())) with check(owner_user_id=(select auth.uid()));
create policy "squads_member_read" on public.ldr_squads for select to authenticated using(exists(select 1 from public.ldr_squad_members m where m.squad_id=id and m.user_id=(select auth.uid())));
create policy "squad_members_owner_manage" on public.ldr_squad_members for all to authenticated using(exists(select 1 from public.ldr_squads s where s.id=squad_id and s.owner_user_id=(select auth.uid()))) with check(exists(select 1 from public.ldr_squads s where s.id=squad_id and s.owner_user_id=(select auth.uid())));
create policy "squad_members_self_read" on public.ldr_squad_members for select to authenticated using(user_id=(select auth.uid()));
create policy "career_goals_own" on public.ldr_career_goals for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy "opportunity_recommendations_own_read" on public.ldr_opportunity_recommendations for select to authenticated using(user_id=(select auth.uid()));
create policy "opportunity_recommendations_own_update" on public.ldr_opportunity_recommendations for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy "opportunity_recommendations_own_delete" on public.ldr_opportunity_recommendations for delete to authenticated using(user_id=(select auth.uid()));
create policy "ecosystem_links_own" on public.ldr_ecosystem_links for all to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy "copilot_actions_own_read" on public.ldr_copilot_actions for select to authenticated using(user_id=(select auth.uid()));
create policy "copilot_actions_own_update" on public.ldr_copilot_actions for update to authenticated using(user_id=(select auth.uid())) with check(user_id=(select auth.uid()));
create policy "copilot_actions_own_delete" on public.ldr_copilot_actions for delete to authenticated using(user_id=(select auth.uid()));
create policy "market_radar_authenticated_read" on public.ldr_market_radar_signals for select to authenticated using(active=true and (expires_at is null or expires_at>now()));