import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";

function emailOf(claims:Record<string,unknown>){const v=claims["email"];return typeof v==="string"?v:null}
const auth=[requireSupabaseAuth] as const;

export const academicNetworkSnapshot=createServerFn({method:"GET"}).middleware(auth).inputValidator((data?:{communityId?:string|null;search?:string|null;savedOnly?:boolean;offset?:number})=>data??{}).handler(async({context,data})=>{const m=await import("@/lib/academic-network.server");return m.getAcademicNetwork(context.userId,emailOf(context.claims),data)});
export const academicFeedMore=createServerFn({method:"GET"}).middleware(auth).inputValidator((data:{offset:number;communityId?:string|null;search?:string|null;savedOnly?:boolean})=>data).handler(async({context,data})=>{const m=await import("@/lib/academic-network.server");return m.getAcademicNetwork(context.userId,emailOf(context.claims),data)});
export const academicSaveDiary=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{id?:string;body:string;prompt?:string|null})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).saveDiaryEntry(context.userId,data));
export const academicDeleteDiary=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{id:string})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).deleteDiaryEntry(context.userId,data.id));
export const academicCreatePost=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{body:string;postType:"reflection"|"question"|"debate"|"study"|"recommendation"|"photo";anonymous:boolean;communityId?:string|null;locationLabel?:string;locationCity?:string;locationCountry?:string;topics?:string[];hasAttachment?:boolean;attachment?:{path:string;fileName?:string;altText?:string}})=>data).handler(async({context,data})=>{const normalized=data.hasAttachment&&!data.body.trim()?{...data,postType:"photo" as const}:data;return (await import("@/lib/academic-network.server")).createAcademicPost(context.userId,normalized)});
export const academicRepostPost=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{postId:string;comment?:string})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).repostAcademicPost(context.userId,data));
export const academicUpdatePost=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{id:string;body:string})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).updateAcademicPost(context.userId,data));
export const academicDeletePost=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{id:string})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).deleteAcademicPost(context.userId,data.id));
export const academicCreateComment=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{postId:string;body:string;anonymous:boolean;parentCommentId?:string|null})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).createAcademicComment(context.userId,data));
export const academicUpdateComment=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{id:string;body:string})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).updateAcademicComment(context.userId,data));
export const academicDeleteComment=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{id:string})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).deleteAcademicComment(context.userId,data.id));
export const academicToggleSave=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{postId:string})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).toggleAcademicSave(context.userId,data.postId));
export const academicToggleSupport=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{postId:string})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).toggleAcademicSupport(context.userId,data.postId));
export const academicSharePost=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{postId:string;targetProfileId:string})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).shareAcademicPost(context.userId,data));
export const academicToggleMembership=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{communityId:string})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).toggleAcademicMembership(context.userId,data.communityId));
export const academicUpdateProfile=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{bio?:string;profession?:string;country?:string;city?:string;interests?:string[];showName?:boolean;showLocation?:boolean})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).updateAcademicProfile(context.userId,data));
export const academicRequestConnection=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{targetProfileId:string})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).requestAcademicConnection(context.userId,data.targetProfileId));
export const academicRespondConnection=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{id:string;status:"accepted"|"declined"})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).respondAcademicConnection(context.userId,data.id,data.status));
export const academicReport=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{postId?:string;commentId?:string;reason:string;details?:string})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).reportAcademicContent(context.userId,data));
export const academicAdminSnapshot=createServerFn({method:"GET"}).middleware(auth).handler(async({context})=>(await import("@/lib/academic-network.server")).getAcademicAdmin(context.userId));
export const academicModerate=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{kind:"post"|"comment"|"report";id:string;action:"hide"|"restore"|"pin"|"unpin"|"resolve"|"dismiss"})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).moderateAcademic(context.userId,data));
export const academicSetProfileRole=createServerFn({method:"POST"}).middleware(auth).inputValidator((data:{profileId:string;role:"member"|"student"|"professor"|"mentor"})=>data).handler(async({context,data})=>(await import("@/lib/academic-network.server")).setAcademicProfileRole(context.userId,data));
