import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { resolveAccess } from "@/lib/access.server";
const db=supabaseAdmin as any;
function fail(m:string):never{throw new Error(m)}
function clean(v:unknown,n:number){return String(v??"").trim().slice(0,n)}
function slug(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"").slice(0,80)}
async function admin(uid:string){try{const x=await resolveAccess(db,uid);return Boolean(x.authorized&&x.role==="superadmin")}catch{return false}}
async function realProfile(uid:string){const {data}=await db.from("academic_profiles").select("id,user_id,username,display_role").eq("user_id",uid).maybeSingle();if(!data)fail("Crie seu perfil acadêmico antes de publicar um desafio.");return data}
export async function listChallenges(userId:string){
  const {data}=await db.from("academic_challenges").select("id,slug,title,theme,description,rules,starts_at,ends_at,status,category,image_path,eligible_roles,community_weight,jury_weight,created_by").in("status",["published","closed"]).order("starts_at",{ascending:false});
  const rows=data??[];if(!rows.length)return [];
  const ids=rows.map((x:any)=>x.id),authors=[...new Set(rows.map((x:any)=>x.created_by).filter(Boolean))];
  const [{data:entries},{data:profiles},{data:counts}]=await Promise.all([db.from("academic_challenge_entries").select("id,challenge_id,entry_type,post_id,article_id,status,badge,final_score").eq("user_id",userId).in("challenge_id",ids),authors.length?db.from("academic_profiles").select("user_id,username,avatar_path").in("user_id",authors):Promise.resolve({data:[]}),db.from("academic_challenge_entries").select("challenge_id").in("challenge_id",ids)]);
  const own=new Map((entries??[]).map((x:any)=>[x.challenge_id,x])),profileMap=new Map((profiles??[]).map((x:any)=>[x.user_id,x])),countMap=new Map<string,number>();for(const x of counts??[])countMap.set(x.challenge_id,(countMap.get(x.challenge_id)||0)+1);
  return rows.map((x:any)=>({...x,myEntry:own.get(x.id)??null,ownChallenge:x.created_by===userId,author:profileMap.get(x.created_by)??null,participantCount:countMap.get(x.id)||0}));
}
export async function enterChallenge(userId:string,input:{challengeId:string;entryType:"post"|"article";postId?:string;articleId?:string}){
  const {data:c}=await db.from("academic_challenges").select("id,status,starts_at,ends_at,eligible_roles").eq("id",input.challengeId).eq("status","published").maybeSingle();if(!c)fail("Desafio indisponível.");const now=Date.now();if(now<new Date(c.starts_at).getTime()||now>new Date(c.ends_at).getTime())fail("O desafio não está no período de participação.");
  const {data:p}=await db.from("academic_profiles").select("display_role").eq("user_id",userId).maybeSingle();if(Array.isArray(c.eligible_roles)&&!c.eligible_roles.includes(p?.display_role||"member"))fail("Seu papel acadêmico não está habilitado para este desafio.");
  if(input.entryType==="post"){const {data:own}=await db.from("academic_posts").select("id").eq("id",input.postId||"").eq("user_id",userId).eq("status","active").maybeSingle();if(!own)fail("Publicação inválida.")}
  else{const {data:own}=await db.from("academic_articles").select("id").eq("id",input.articleId||"").eq("user_id",userId).eq("status","active").maybeSingle();if(!own)fail("Artigo inválido.")}
  const row={challenge_id:c.id,user_id:userId,entry_type:input.entryType,post_id:input.entryType==="post"?input.postId:null,article_id:input.entryType==="article"?input.articleId:null,status:"submitted"};const {data,error}=await db.from("academic_challenge_entries").insert(row).select("id,status").single();if(error)fail("Esta participação não pôde ser registrada.");return data;
}
export async function adminChallengeSnapshot(userId:string){if(!(await admin(userId)))fail("Acesso negado.");const [{data:challenges},{data:entries},{data:scores}]=await Promise.all([db.from("academic_challenges").select("*").order("created_at",{ascending:false}),db.from("academic_challenge_entries").select("*").order("created_at",{ascending:false}),db.from("academic_challenge_jury_scores").select("*").order("updated_at",{ascending:false})]);return {challenges:challenges??[],entries:entries??[],scores:scores??[]}}
export async function saveChallenge(userId:string,input:{id?:string;title:string;theme:string;description?:string;rules?:string;startsAt:string;endsAt:string;status:"draft"|"published"|"closed"|"cancelled";category?:string;communityWeight:number;juryWeight:number}){await realProfile(userId);const isAdmin=await admin(userId);const cw=Number(input.communityWeight),jw=Number(input.juryWeight);if(!Number.isFinite(cw)||!Number.isFinite(jw)||Math.abs(cw+jw-100)>0.001)fail("Os pesos precisam somar 100%.");const starts=new Date(input.startsAt),ends=new Date(input.endsAt);if(!Number.isFinite(starts.getTime())||!Number.isFinite(ends.getTime())||ends<=starts)fail("Datas inválidas.");const status=input.status==="cancelled"?"closed":input.status;const base={title:clean(input.title,180),theme:clean(input.theme,240),description:clean(input.description,8000),rules:clean(input.rules,12000),starts_at:starts.toISOString(),ends_at:ends.toISOString(),status,category:clean(input.category,100),community_weight:cw,jury_weight:jw,updated_at:new Date().toISOString()};if(!base.title||!base.theme)fail("Título e tema são obrigatórios.");if(input.id){let q=db.from("academic_challenges").update(base).eq("id",input.id);if(!isAdmin)q=q.eq("created_by",userId);const {data,error}=await q.select("id").maybeSingle();if(error||!data)fail("Você só pode editar seus próprios desafios.");return data}const {data,error}=await db.from("academic_challenges").insert({...base,slug:`${slug(base.title)||"desafio"}-${Date.now().toString(36)}`,created_by:userId}).select("id").single();if(error)fail("Não foi possível criar o desafio.");return data}
export async function scoreChallengeEntry(userId:string,input:{entryId:string;score:number;notes?:string}){if(!(await admin(userId)))fail("Acesso negado.");const score=Math.max(0,Math.min(100,Number(input.score)));if(!Number.isFinite(score))fail("Nota inválida.");const {data:entry}=await db.from("academic_challenge_entries").select("id,challenge_id,entry_type,post_id,article_id").eq("id",input.entryId).maybeSingle();if(!entry)fail("Participação não encontrada.");if(entry.entry_type==="post"){const {count}=await db.from("academic_reactions").select("post_id",{count:"exact",head:true}).eq("post_id",entry.post_id).eq("reaction_type","support");await scoreEntry(entry,userId,score,input.notes,Number(count??0))}else{const {count}=await db.from("academic_article_reactions").select("article_id",{count:"exact",head:true}).eq("article_id",entry.article_id).eq("reaction_type","support");await scoreEntry(entry,userId,score,input.notes,Number(count??0))}return {ok:true}}
async function scoreEntry(entry:any,userId:string,score:number,notes:string|undefined,communityRaw:number){await db.from("academic_challenge_jury_scores").upsert({challenge_entry_id:entry.id,juror_user_id:userId,score,notes:clean(notes,3000),updated_at:new Date().toISOString()},{onConflict:"challenge_entry_id,juror_user_id"});const [{data:c},{data:all}]=await Promise.all([db.from("academic_challenges").select("community_weight,jury_weight").eq("id",entry.challenge_id).single(),db.from("academic_challenge_jury_scores").select("score").eq("challenge_entry_id",entry.id)]);const jury=(all??[]).reduce((a:number,x:any)=>a+Number(x.score||0),0)/Math.max(1,(all??[]).length),community=Math.min(100,communityRaw),final=community*(Number(c.community_weight)/100)+jury*(Number(c.jury_weight)/100);await db.from("academic_challenge_entries").update({status:"eligible",community_score:community,jury_score:jury,final_score:final,updated_at:new Date().toISOString()}).eq("id",entry.id)}
export async function setChallengeEntryResult(userId:string,input:{entryId:string;status:"eligible"|"ineligible"|"winner"|"highlighted";badge?:"article_highlight"|"community_choice"|"ldr_academic_highlight"|null}){if(!(await admin(userId)))fail("Acesso negado.");const {data,error}=await db.from("academic_challenge_entries").update({status:input.status,badge:input.badge??null,updated_at:new Date().toISOString()}).eq("id",input.entryId).select("id").maybeSingle();if(error||!data)fail("Participação não encontrada.");return data}
