import { supabaseAdmin } from "@/integrations/supabase/client.server";
const db=supabaseAdmin as any;
function fail(m:string):never{throw new Error(m)}
function clean(v:unknown,n:number){return String(v??"").trim().slice(0,n)}
function slugify(v:string){return v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"").slice(0,80)}
function html(v:string){const e=v.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");return e.split(/\n{2,}/).map(p=>`<p>${p.replace(/\n/g,"<br>")}</p>`).join("")}
async function nameOf(uid:string){const {data}=await db.from("profiles").select("full_name").eq("id",uid).maybeSingle();return data?.full_name||"Membro LDR"}
export async function createArticle(userId:string,input:{title:string;summary?:string;body:string;category?:string;communityId?:string|null;keywords?:string[];references?:string;locationLabel?:string;locationCity?:string;locationCountry?:string}){const title=clean(input.title,180),body=clean(input.body,100000);if(title.length<3||!body)fail("Título e texto são obrigatórios.");const slug=`${slugify(title)||"artigo"}-${Date.now().toString(36)}`;const {data,error}=await db.from("academic_articles").insert({user_id:userId,community_id:input.communityId||null,slug,title,summary:clean(input.summary,800),body_html:html(body),category:clean(input.category,100),keywords:(input.keywords??[]).map(x=>clean(x,60)).filter(Boolean).slice(0,20),references_text:clean(input.references,12000),location_label:clean(input.locationLabel,160)||null,location_city:clean(input.locationCity,80)||null,location_country:clean(input.locationCountry,80)||null,status:"active"}).select("id,slug").single();if(error)fail("Não foi possível publicar o artigo.");return data}
export async function articleBySlug(userId:string,slug:string){const {data:a}=await db.from("academic_articles").select("id,user_id,slug,title,summary,body_html,category,keywords,references_text,location_label,location_city,location_country,created_at,updated_at").eq("slug",clean(slug,120)).eq("status","active").maybeSingle();if(!a)fail("Artigo não encontrado.");const [{data:p},{count:supports},{data:mine},{data:saved}]=await Promise.all([db.from("academic_profiles").select("id,username,display_role,show_name").eq("user_id",a.user_id).maybeSingle(),db.from("academic_article_reactions").select("article_id",{count:"exact",head:true}).eq("article_id",a.id).eq("reaction_type","support"),db.from("academic_article_reactions").select("article_id").eq("article_id",a.id).eq("user_id",userId).eq("reaction_type","support").maybeSingle(),db.from("academic_saved_articles").select("article_id").eq("article_id",a.id).eq("user_id",userId).maybeSingle()]);return {...a,user_id:undefined,own:a.user_id===userId,author:{profileId:p?.id??null,username:p?.username??null,name:p?.show_name===false?"Membro LDR":await nameOf(a.user_id),role:p?.display_role??"member"},supportCount:supports??0,supported:Boolean(mine),saved:Boolean(saved)}}
export async function toggleSupport(userId:string,articleId:string){const {data}=await db.from("academic_article_reactions").select("article_id").eq("user_id",userId).eq("article_id",articleId).eq("reaction_type","support").maybeSingle();if(data){await db.from("academic_article_reactions").delete().eq("user_id",userId).eq("article_id",articleId).eq("reaction_type","support");return {supported:false}}await db.from("academic_article_reactions").insert({user_id:userId,article_id:articleId,reaction_type:"support"});return {supported:true}}
export async function toggleSave(userId:string,articleId:string){const {data}=await db.from("academic_saved_articles").select("article_id").eq("user_id",userId).eq("article_id",articleId).maybeSingle();if(data){await db.from("academic_saved_articles").delete().eq("user_id",userId).eq("article_id",articleId);return {saved:false}}await db.from("academic_saved_articles").insert({user_id:userId,article_id:articleId});return {saved:true}}
