import { getRequest } from "@tanstack/react-start/server";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { resolveClient } from "@/lib/client-portal.server";
import { hasOwnerDigitalAccess } from "@/lib/owner-digital-access.server";
import { AI_PROJECTS } from "@/content/ai-business-career-curriculum";
const db=supabaseAdmin as any;
const PRODUCT_KEY="formacao_ia_negocios_carreira",SLUG="formacao-ia-negocios-carreira",TITLE="Formação em Inteligência Artificial Aplicada aos Negócios e à Carreira";
const PRICE_BRL=29999,PRICE_EUR=4990;
type Market="BR"|"INTL";
function fail(m:string):never{throw new Error(m)}
async function customerFor(userId:string,email:string|null){const x=await resolveClient(userId,email);if(x.status!=="ok")fail("Acesso do cliente não disponível.");return x.customer;}
function match(o:any){const m=o?.metadata??{};return o?.catalog_key===PRODUCT_KEY||m.product_key===PRODUCT_KEY||m.product_key===SLUG;}
async function paidOrder(customerId:string){const {data}=await db.from("orders").select("id,catalog_key,payment_status,metadata,created_at").eq("customer_id",customerId).eq("payment_status","pago").order("created_at",{ascending:false});return (data??[]).find(match)??null;}
async function ensureProgram(){let {data}=await db.from("training_programs").select("id,slug,title,status,projects_included").eq("slug",SLUG).maybeSingle();if(data?.id){await db.from("training_programs").update({status:"published",projects_included:6,lifetime_access:true,live_sessions_included:0,minimum_days:0}).eq("id",data.id);return {...data,status:"published",projects_included:6};}const r=await db.from("training_programs").insert({slug:SLUG,title:TITLE,description:"Formação 100% online: 600 horas, 15 módulos, 225 aulas, 5 projetos avaliativos e 1 projeto final.",status:"published",minimum_days:0,live_sessions_included:0,projects_included:6,lifetime_access:true}).select("id,slug,title,status,projects_included").single();if(r.error||!r.data)throw r.error??new Error("Falha ao preparar a formação.");return r.data;}
async function ensureEnrollment(customerId:string,trainingId:string,entitled:boolean){if(!entitled)return null;let {data}=await db.from("training_enrollments").select("id,enrolled_at,progress_percent,completed_at").eq("training_id",trainingId).eq("customer_id",customerId).eq("active",true).maybeSingle();if(data)return data;const r=await db.from("training_enrollments").insert({training_id:trainingId,customer_id:customerId,active:true,product_key:PRODUCT_KEY}).select("id,enrolled_at,progress_percent,completed_at").single();return r.data??null;}
function origin(){const r=getRequest();return process.env.CLIENT_PANEL_URL?.replace(/\/$/,"")||(r?new URL(r.url).origin:"https://painel.ldrrhestrategia.com");}
export async function getAIFormationOffer(userId:string,email:string|null){const c=await customerFor(userId,email);const order=await paidOrder(c.id);const entitled=Boolean(order)||hasOwnerDigitalAccess(email,userId);const training=await ensureProgram();await ensureEnrollment(c.id,training.id,entitled);return {productKey:PRODUCT_KEY,slug:SLUG,title:TITLE,priceBrlCents:PRICE_BRL,priceEurCents:PRICE_EUR,entitled,lifetimeAccess:true,totalModules:15,totalLessons:225,totalHours:600,liveSessionsIncluded:0,projectReviewsIncluded:6};}
export async function createAIFormationCheckout(userId:string,email:string|null,market:Market){const c=await customerFor(userId,email);const offer=await getAIFormationOffer(userId,email);if(offer.entitled)fail("Esta formação já está disponível para sua conta.");const amount=market==="BR"?PRICE_BRL:PRICE_EUR,currency=market==="BR"?"BRL":"EUR";const meta={product_key:PRODUCT_KEY,training_slug:SLUG,market,auth_user_id:userId};const {data:o,error}=await db.from("orders").insert({order_number:"",customer_id:c.id,contact_email:c.email,contact_phone:c.phone,service_type:"produto_digital",title:TITLE,description:"Pagamento único · acesso vitalício · 225 aulas · 6 avaliações de projeto",quantity:1,amount_cents:amount,currency,payment_status:"pendente",status:"novo",priority:"media",catalog_key:PRODUCT_KEY,metadata:meta}).select("id").single();if(error||!o)fail("Não foi possível iniciar o pedido.");const secret=process.env.STRIPE_SECRET_KEY;if(!secret)fail("Pagamento temporariamente indisponível.");const p=new URLSearchParams();p.set("mode","payment");p.set("line_items[0][price_data][currency]",currency.toLowerCase());p.set("line_items[0][price_data][unit_amount]",String(amount));p.set("line_items[0][price_data][product_data][name]",TITLE);p.set("line_items[0][quantity]","1");p.set("success_url",`${origin()}/cliente/biblioteca?payment=success&product=ai-formation&session_id={CHECKOUT_SESSION_ID}`);p.set("cancel_url",`${origin()}/cliente/biblioteca?payment=cancel&product=ai-formation`);p.set("metadata[order_id]",o.id);p.set("metadata[product_key]",PRODUCT_KEY);p.set("metadata[training_slug]",SLUG);p.set("payment_intent_data[metadata][order_id]",o.id);p.set("payment_intent_data[metadata][product_key]",PRODUCT_KEY);if(c.email)p.set("customer_email",c.email);const response=await fetch("https://api.stripe.com/v1/checkout/sessions",{method:"POST",headers:{Authorization:`Bearer ${secret}`,"Content-Type":"application/x-www-form-urlencoded"},body:p});const session=await response.json() as any;if(!response.ok||!session.url)fail("Não foi possível abrir o checkout.");await db.from("orders").update({stripe_checkout_session_id:session.id}).eq("id",o.id);return {url:session.url};}
export async function getAIFormationExperience(userId:string,email:string|null){const c=await customerFor(userId,email),offer=await getAIFormationOffer(userId,email);if(!offer.entitled)fail("Compre a formação ou ative a assinatura da Biblioteca para acessar.");const training=await ensureProgram(),enr=await ensureEnrollment(c.id,training.id,true);const [{data:cloud},{data:subs}]=await Promise.all([db.from("training_state").select("state,progress_percent").eq("training_id",training.id).eq("customer_id",c.id).maybeSingle(),db.from("training_project_submissions").select("id,submission_number,title,project_url,status,submitted_at,reviewed_at,feedback").eq("training_id",training.id).eq("customer_id",c.id).order("submission_number",{ascending:true})]);const state=(cloud?.state&&typeof cloud.state==="object"?cloud.state:{}) as any,completed=Array.isArray(state.completedLessons)?state.completedLessons:[];return {...offer,trainingId:training.id,enrollmentId:enr?.id??null,state,completedLessons:completed,progressPercent:Math.round(Math.min(100,completed.length/225*100)),projectSubmissions:subs??[],projects:AI_PROJECTS,studentName:c.fullName??c.full_name??c.email??"Aluno"};}
export async function saveAIFormationState(userId:string,email:string|null,state:Record<string,unknown>){const c=await customerFor(userId,email),offer=await getAIFormationOffer(userId,email);if(!offer.entitled)fail("Acesso não disponível.");const training=await ensureProgram(),completed=Array.isArray((state as any).completedLessons)?(state as any).completedLessons:[],progress=Math.round(Math.min(100,completed.length/225*100));const {error}=await db.from("training_state").upsert({training_id:training.id,customer_id:c.id,state,progress_percent:progress,updated_at:new Date().toISOString()},{onConflict:"training_id,customer_id"});if(error)fail("Não foi possível salvar o progresso.");await db.from("training_enrollments").update({progress_percent:progress,...(progress>=100?{completed_at:new Date().toISOString()}:{} )}).eq("training_id",training.id).eq("customer_id",c.id);return {ok:true as const,progressPercent:progress};}
export async function submitAIProject(userId:string,email:string|null,input:{projectNumber:number;title:string;projectUrl?:string|null;projectText?:string|null}){const c=await customerFor(userId,email),exp=await getAIFormationExperience(userId,email);const project=AI_PROJECTS.find(p=>p.number===input.projectNumber);if(!project)fail("Projeto inválido.");const required=project.afterModule*15;if(exp.completedLessons.length<required)fail(`Conclua os módulos exigidos antes desta entrega (${required} aulas).`);const title=input.title.trim(),projectUrl=input.projectUrl?.trim()||null,projectText=input.projectText?.trim()||null;if(!title||(!projectUrl&&!projectText))fail("Informe o projeto e sua documentação.");const previous=(exp.projectSubmissions??[]).find((s:any)=>s.submission_number===project.number);if(previous&&(previous.status==="submitted"||previous.status==="in_review"))fail("Este projeto já está em avaliação.");if(previous){if(previous.status!=="changes_requested")fail("Esta avaliação já foi concluída.");const r=await db.from("training_project_submissions").update({title,project_url:projectUrl,project_text:projectText,status:"submitted",submitted_at:new Date().toISOString(),reviewed_at:null}).eq("id",previous.id).select("id,submission_number,status").single();if(r.error)fail("Não foi possível reenviar o projeto.");return {ok:true as const,submission:r.data};}const r=await db.from("training_project_submissions").insert({training_id:exp.trainingId,enrollment_id:exp.enrollmentId,customer_id:c.id,submission_number:project.number,title,project_url:projectUrl,project_text:projectText,status:"submitted"}).select("id,submission_number,status").single();if(r.error||!r.data)fail("Não foi possível enviar o projeto.");return {ok:true as const,submission:r.data};}
