import { getRequest } from "@tanstack/react-start/server";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { resolveClient } from "@/lib/client-portal.server";
import { hasOwnerDigitalAccess } from "@/lib/owner-digital-access.server";
const db=supabaseAdmin as any;
const PRODUCT_KEY="formacao_negocio_24_horas";
const SLUG="formacao-negocio-em-24-horas";
const TITLE="Formação Negócio em 24 Horas";
const PRICE_BRL=29999, PRICE_EUR=4990;
type Market="BR"|"INTL";
function fail(m:string):never{throw new Error(m)}
async function customerFor(userId:string,email:string|null){const x=await resolveClient(userId,email);if(x.status!=="ok")fail("Acesso do cliente não disponível.");return x.customer;}
function match(o:any){const m=o?.metadata??{};return o?.catalog_key===PRODUCT_KEY||m.product_key===PRODUCT_KEY||m.product_key===SLUG;}
async function paidOrder(customerId:string){const {data,error}=await db.from("orders").select("id,catalog_key,payment_status,metadata,created_at").eq("customer_id",customerId).eq("payment_status","pago").order("created_at",{ascending:false});if(error)return null;return (data??[]).find(match)??null;}
async function ensureProgram(){let {data}=await db.from("training_programs").select("id,slug,title,status").eq("slug",SLUG).maybeSingle();if(data?.id){if(data.status!=="published")await db.from("training_programs").update({status:"published"}).eq("id",data.id);return {...data,status:"published"};}const r=await db.from("training_programs").insert({slug:SLUG,title:TITLE,description:"Formação prática 100% online com 9 módulos, 90 aulas, 360 horas, sem encontros ao vivo e projeto final avaliado.",status:"published",minimum_days:0,live_sessions_included:0,projects_included:1,lifetime_access:true}).select("id,slug,title,status").single();if(r.error||!r.data)throw r.error??new Error("Falha ao preparar a formação.");return r.data;}
async function ensureEnrollment(customerId:string,trainingId:string,entitled:boolean){if(!entitled)return null;let {data}=await db.from("training_enrollments").select("id,enrolled_at,progress_percent,completed_at,certificate_available_at").eq("training_id",trainingId).eq("customer_id",customerId).eq("active",true).maybeSingle();if(data)return data;const r=await db.from("training_enrollments").insert({training_id:trainingId,customer_id:customerId,active:true,product_key:PRODUCT_KEY}).select("id,enrolled_at,progress_percent,completed_at,certificate_available_at").single();return r.data??null;}
function appOrigin(){const r=getRequest();return process.env.CLIENT_PANEL_URL?.replace(/\/$/,"")||(r?new URL(r.url).origin:"https://painel.ldrrhestrategia.com");}
export async function getBusiness24Offer(userId:string,email:string|null){const c=await customerFor(userId,email);const order=await paidOrder(c.id);const owner=hasOwnerDigitalAccess(email,userId);const entitled=Boolean(order)||owner;const training=await ensureProgram();await ensureEnrollment(c.id,training.id,entitled);return {productKey:PRODUCT_KEY,slug:SLUG,title:TITLE,priceBrlCents:PRICE_BRL,priceEurCents:PRICE_EUR,entitled,lifetimeAccess:true,totalModules:9,totalLessons:90,totalHours:360,liveSessionsIncluded:0,projectReviewIncluded:true};}
export async function createBusiness24Checkout(userId:string,email:string|null,market:Market){const c=await customerFor(userId,email);const offer=await getBusiness24Offer(userId,email);if(offer.entitled)fail("Esta formação já está disponível para sua conta.");const amount=market==="BR"?PRICE_BRL:PRICE_EUR,currency=market==="BR"?"BRL":"EUR";const meta={product_key:PRODUCT_KEY,training_slug:SLUG,market,auth_user_id:userId};const {data:o,error}=await db.from("orders").insert({order_number:"",customer_id:c.id,contact_email:c.email,contact_phone:c.phone,service_type:"produto_digital",title:TITLE,description:"Pagamento único · acesso vitalício · 90 aulas · projeto final avaliado",quantity:1,amount_cents:amount,currency,payment_status:"pendente",status:"novo",priority:"media",catalog_key:PRODUCT_KEY,metadata:meta}).select("id").single();if(error||!o)fail("Não foi possível iniciar o pedido.");const secret=process.env.STRIPE_SECRET_KEY;if(!secret){await db.from("orders").delete().eq("id",o.id);fail("Pagamento temporariamente indisponível.");}const p=new URLSearchParams();p.set("mode","payment");p.set("line_items[0][price_data][currency]",currency.toLowerCase());p.set("line_items[0][price_data][unit_amount]",String(amount));p.set("line_items[0][price_data][product_data][name]",TITLE);p.set("line_items[0][quantity]","1");p.set("success_url",`${appOrigin()}/cliente/biblioteca?payment=success&product=business24&session_id={CHECKOUT_SESSION_ID}`);p.set("cancel_url",`${appOrigin()}/cliente/biblioteca?payment=cancel&product=business24`);p.set("client_reference_id",userId);p.set("metadata[order_id]",o.id);p.set("metadata[product_key]",PRODUCT_KEY);p.set("metadata[training_slug]",SLUG);p.set("metadata[user_id]",userId);p.set("payment_intent_data[metadata][order_id]",o.id);p.set("payment_intent_data[metadata][product_key]",PRODUCT_KEY);if(c.email)p.set("customer_email",c.email);let response:Response;try{response=await fetch("https://api.stripe.com/v1/checkout/sessions",{method:"POST",headers:{Authorization:`Bearer ${secret}`,"Content-Type":"application/x-www-form-urlencoded"},body:p});}catch{await db.from("orders").delete().eq("id",o.id);fail("Não foi possível abrir o checkout.");}const session=await response.json() as any;if(!response.ok||!session.id||!session.url){await db.from("orders").delete().eq("id",o.id);fail("Não foi possível abrir o checkout.");}await db.from("orders").update({stripe_checkout_session_id:session.id}).eq("id",o.id);return {url:session.url};}
export async function getBusiness24Experience(userId:string,email:string|null){const c=await customerFor(userId,email);const offer=await getBusiness24Offer(userId,email);if(!offer.entitled)fail("Compre a formação ou ative a assinatura da Biblioteca para acessar.");const training=await ensureProgram();const enr=await ensureEnrollment(c.id,training.id,true);const [{data:cloud},{data:subs},{data:credits}]=await Promise.all([db.from("training_state").select("state,progress_percent").eq("training_id",training.id).eq("customer_id",c.id).maybeSingle(),db.from("training_project_submissions").select("id,submission_number,title,project_url,status,submitted_at,reviewed_at,feedback").eq("training_id",training.id).eq("customer_id",c.id).order("submission_number",{ascending:true}),db.from("training_project_review_credits").select("id,status,source").eq("training_id",training.id).eq("customer_id",c.id).eq("source","included")]);if(!(credits??[]).length&&enr?.id)await db.from("training_project_review_credits").insert({training_id:training.id,enrollment_id:enr.id,customer_id:c.id,source:"included",status:"available"});const state=(cloud?.state&&typeof cloud.state==="object"?cloud.state:{}) as Record<string,unknown>;const completed=Array.isArray((state as any).completedLessons)?(state as any).completedLessons:[];return {...offer,trainingId:training.id,enrollmentId:enr?.id??null,state,completedLessons:completed,progressPercent:Math.round(Math.min(100,completed.length/90*100)),projectEligible:completed.length>=90,projectSubmissions:subs??[],studentName:c.fullName??c.full_name??c.email??"Aluno"};}
export async function saveBusiness24State(userId:string,email:string|null,state:Record<string,unknown>){const c=await customerFor(userId,email);const offer=await getBusiness24Offer(userId,email);if(!offer.entitled)fail("Acesso não disponível.");const training=await ensureProgram();const completed=Array.isArray((state as any).completedLessons)?(state as any).completedLessons:[];const progress=Math.round(Math.min(100,completed.length/90*100));const patch={training_id:training.id,customer_id:c.id,state,progress_percent:progress,updated_at:new Date().toISOString()};const {error}=await db.from("training_state").upsert(patch,{onConflict:"training_id,customer_id"});if(error)fail("Não foi possível salvar o progresso.");await db.from("training_enrollments").update({progress_percent:progress,...(progress>=100?{completed_at:new Date().toISOString()}:{} )}).eq("training_id",training.id).eq("customer_id",c.id);return {ok:true as const,progressPercent:progress};}
export async function submitBusiness24Project(userId:string,email:string|null,input:{title:string;projectUrl?:string|null;projectText?:string|null}){const c=await customerFor(userId,email);const exp=await getBusiness24Experience(userId,email);if(!exp.projectEligible)fail("Conclua as 90 aulas antes de enviar o projeto final.");const title=input.title.trim(),projectUrl=input.projectUrl?.trim()||null,projectText=input.projectText?.trim()||null;if(!title)fail("Informe o nome do projeto.");if(!projectUrl&&!projectText)fail("Descreva o projeto ou informe um link.");const list=exp.projectSubmissions??[],last=list.length?list[list.length-1]:null;if(last&&(last.status==="submitted"||last.status==="in_review"))fail("Seu projeto já está em avaliação.");if(last?.status==="changes_requested"){const r=await db.from("training_project_submissions").update({title,project_url:projectUrl,project_text:projectText,status:"submitted",submitted_at:new Date().toISOString(),reviewed_at:null}).eq("id",last.id).select("id,submission_number,status,submitted_at").single();if(r.error||!r.data)fail("Não foi possível reenviar o projeto.");return {ok:true as const,submission:r.data};}const {data:credit}=await db.from("training_project_review_credits").select("id").eq("training_id",exp.trainingId).eq("customer_id",c.id).eq("source","included").eq("status","available").limit(1).maybeSingle();if(!credit?.id)fail("A avaliação incluída já foi utilizada.");const r=await db.from("training_project_submissions").insert({training_id:exp.trainingId,enrollment_id:exp.enrollmentId,customer_id:c.id,review_credit_id:credit.id,submission_number:1,title,project_url:projectUrl,project_text:projectText,status:"submitted"}).select("id,submission_number,status,submitted_at").single();if(r.error||!r.data)fail("Não foi possível enviar o projeto.");await db.from("training_project_review_credits").update({status:"used",used_at:new Date().toISOString()}).eq("id",credit.id);return {ok:true as const,submission:r.data};}
