import { getRequest } from "@tanstack/react-start/server";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { resolveClient } from "@/lib/client-portal.server";

const db=supabaseAdmin as any;
export type EditorialProduct="jornal_ldr"|"revista_ldr";
type Market="BR"|"INTL";
const PRICE_BRL=90, PRICE_EUR=90;
const NAMES:Record<EditorialProduct,string>={jornal_ldr:"Jornal LDR — Assinatura Semanal",revista_ldr:"Revista LDR — Assinatura Semanal"};
const PATHS:Record<EditorialProduct,string>={jornal_ldr:"/cliente/biblioteca/jornal-ldr",revista_ldr:"/cliente/biblioteca/revista-ldr"};

function fail(m:string):never{throw new Error(m)}
function appOrigin(){const r=getRequest();return process.env.CLIENT_PANEL_URL?.replace(/\/$/,"")||(r?new URL(r.url).origin:"https://painel.ldrrhestrategia.com")}
function stripeId(v:any){return typeof v==="string"?v:v?.id??null}
function iso(v?:number|null){return v&&Number.isFinite(v)?new Date(v*1000).toISOString():null}
function active(status?:string|null){return status==="active"||status==="trialing"}
async function customerFor(userId:string,email:string|null){const c=await resolveClient(userId,email);if(c.status!=="ok")fail("Acesso do cliente não disponível.");return c.customer}
async function stripeGet(path:string){const secret=process.env.STRIPE_SECRET_KEY;if(!secret)return null;try{const r=await fetch(`https://api.stripe.com/v1/${path}`,{headers:{Authorization:`Bearer ${secret}`}});return r.ok?await r.json():null}catch{return null}}
async function currentRow(customerId:string,productKey:EditorialProduct){const {data,error}=await db.from("editorial_subscriptions").select("*").eq("customer_id",customerId).eq("product_key",productKey).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)fail("Não foi possível carregar a assinatura editorial.");return data??null}
async function sync(row:any){let sid=row.stripe_subscription_id??null,cid=row.stripe_customer_id??null;if(!sid&&row.stripe_checkout_session_id){const s=await stripeGet(`checkout/sessions/${encodeURIComponent(row.stripe_checkout_session_id)}`);sid=stripeId(s?.subscription)??sid;cid=stripeId(s?.customer)??cid}if(!sid)return row;const sub=await stripeGet(`subscriptions/${encodeURIComponent(sid)}`);if(!sub)return row;const patch={stripe_subscription_id:sid,stripe_customer_id:stripeId(sub.customer)??cid,status:String(sub.status??row.status??"incomplete"),current_period_start:iso(sub.current_period_start),current_period_end:iso(sub.current_period_end),cancel_at_period_end:Boolean(sub.cancel_at_period_end),updated_at:new Date().toISOString()};await db.from("editorial_subscriptions").update(patch).eq("id",row.id);return {...row,...patch}}

export async function getEditorialSubscriptionContext(userId:string,email:string|null,productKey:EditorialProduct){const customer=await customerFor(userId,email);const row=await currentRow(customer.id,productKey);const subscription=row?await sync(row):null;return {customer,productKey,subscription,active:active(subscription?.status),priceBrlCents:PRICE_BRL,priceEurCents:PRICE_EUR};}

export async function createEditorialCheckout(userId:string,email:string|null,productKey:EditorialProduct,market:Market){const customer=await customerFor(userId,email);const existing=await currentRow(customer.id,productKey);if(existing){const s=await sync(existing);if(active(s?.status)||["past_due","unpaid","paused","incomplete"].includes(String(s?.status)))fail(`Você já possui uma assinatura de ${NAMES[productKey].replace(" — Assinatura Semanal","")}.`)}const currency=market==="BR"?"BRL":"EUR",amount=market==="BR"?PRICE_BRL:PRICE_EUR;const {data:row,error}=await db.from("editorial_subscriptions").insert({customer_id:customer.id,product_key:productKey,market,currency,monthly_amount_cents:amount,status:"pending"}).select("id").single();if(error||!row)fail("Não foi possível preparar a assinatura editorial.");const secret=process.env.STRIPE_SECRET_KEY;if(!secret){await db.from("editorial_subscriptions").delete().eq("id",row.id);fail("Pagamento temporariamente indisponível.")}
const p=new URLSearchParams();p.set("mode","subscription");p.append("payment_method_types[]","card");p.set("line_items[0][price_data][currency]",currency.toLowerCase());p.set("line_items[0][price_data][unit_amount]",String(amount));p.set("line_items[0][price_data][recurring][interval]","week");p.set("line_items[0][price_data][product_data][name]",NAMES[productKey]);p.set("line_items[0][quantity]","1");p.set("success_url",`${appOrigin()}${PATHS[productKey]}?subscription=success&session_id={CHECKOUT_SESSION_ID}`);p.set("cancel_url",`${appOrigin()}${PATHS[productKey]}?subscription=cancel`);p.set("client_reference_id",userId);p.set("billing_address_collection","auto");for(const [k,v] of Object.entries({checkout_kind:"editorial_subscription",editorial_subscription_id:row.id,editorial_product_key:productKey,customer_id:customer.id,market})){p.set(`metadata[${k}]`,v);p.set(`subscription_data[metadata][${k}]`,v)}if(customer.email)p.set("customer_email",customer.email);
let r:Response;try{r=await fetch("https://api.stripe.com/v1/checkout/sessions",{method:"POST",headers:{Authorization:`Bearer ${secret}`,"Content-Type":"application/x-www-form-urlencoded"},body:p})}catch{await db.from("editorial_subscriptions").delete().eq("id",row.id);fail("Não foi possível abrir o checkout.")}const s=await r.json() as any;if(!r.ok||!s.id||!s.url){await db.from("editorial_subscriptions").delete().eq("id",row.id);fail(s?.error?.message||"Não foi possível abrir o checkout.")}await db.from("editorial_subscriptions").update({stripe_checkout_session_id:s.id,updated_at:new Date().toISOString()}).eq("id",row.id);return {url:s.url};}

export async function setEditorialCancellation(userId:string,email:string|null,productKey:EditorialProduct,cancelAtPeriodEnd:boolean){const customer=await customerFor(userId,email);const row=await currentRow(customer.id,productKey);if(!row?.stripe_subscription_id)fail("Assinatura ativa não encontrada.");const secret=process.env.STRIPE_SECRET_KEY;if(!secret)fail("Gestão da assinatura indisponível.");const p=new URLSearchParams();p.set("cancel_at_period_end",cancelAtPeriodEnd?"true":"false");const r=await fetch(`https://api.stripe.com/v1/subscriptions/${encodeURIComponent(row.stripe_subscription_id)}`,{method:"POST",headers:{Authorization:`Bearer ${secret}`,"Content-Type":"application/x-www-form-urlencoded"},body:p});const sub=await r.json() as any;if(!r.ok)fail(sub?.error?.message||"Não foi possível atualizar a assinatura.");const patch={status:String(sub.status??row.status),current_period_start:iso(sub.current_period_start),current_period_end:iso(sub.current_period_end),cancel_at_period_end:Boolean(sub.cancel_at_period_end),updated_at:new Date().toISOString()};await db.from("editorial_subscriptions").update(patch).eq("id",row.id);return {ok:true,subscription:{...row,...patch}};}

export async function handleEditorialStripeEvent(metadata:Record<string,string>,object:any,eventType:string){const rowId=metadata["editorial_subscription_id"];const productKey=metadata["editorial_product_key"] as EditorialProduct|undefined;const sid=eventType.startsWith("customer.subscription")?object.id??null:stripeId(object.subscription)??stripeId(object.parent?.subscription_details?.subscription);if(!rowId&&!sid)return false;let raw=String(object.status??"pending");if(eventType==="checkout.session.completed")raw=object.payment_status==="paid"||object.payment_status==="no_payment_required"?"active":"pending";if(eventType==="invoice.payment_succeeded")raw="active";if(eventType==="checkout.session.expired"||eventType==="customer.subscription.deleted")raw="canceled";if(eventType==="invoice.payment_failed")raw="past_due";const allowed=new Set(["pending","active","trialing","past_due","canceled","unpaid","paused","incomplete"]);const patch:any={status:allowed.has(raw)?raw:"incomplete",updated_at:new Date().toISOString()};if(eventType==="checkout.session.completed"||eventType==="checkout.session.expired")patch.stripe_checkout_session_id=object.id??null;if(sid)patch.stripe_subscription_id=sid;const cid=stripeId(object.customer);if(cid)patch.stripe_customer_id=cid;const ps=iso(object.current_period_start),pe=iso(object.current_period_end);if(ps)patch.current_period_start=ps;if(pe)patch.current_period_end=pe;if(typeof object.cancel_at_period_end==="boolean")patch.cancel_at_period_end=object.cancel_at_period_end;let q=db.from("editorial_subscriptions").update(patch);if(rowId)q=q.eq("id",rowId);else if(sid)q=q.eq("stripe_subscription_id",sid);if(productKey)q=q.eq("product_key",productKey);const {error}=await q;if(error)throw error;return true;}
