export type EditorialKind="jornal"|"revista";
export type EditorialProduct=
  |"jornal_ldr"|"revista_ldr"
  |"jornal_negocios_economia"|"jornal_politica_economia"|"jornal_europa"|"jornal_migracao_mobilidade"
  |"revista_fofoca"|"revista_robotica_ia"|"revista_gastronomia"|"revista_negocios"|"revista_saude_mental"|"revista_saude_bem_estar"|"revista_estetica"|"revista_rural"|"revista_viagem"|"revista_migracao_exterior"|"revista_carreira_trabalho_internacional"|"revista_vida_luciano";

export type EditorialEntry={
  productKey:EditorialProduct;slug:string;kind:EditorialKind;icon:string;title:string;subtitle:string;description:string;topics:string[];priceBrlCents:number;priceEurCents:number;color:string;notice?:string;
};

const standard=(x:Omit<EditorialEntry,"priceBrlCents"|"priceEurCents">):EditorialEntry=>({...x,priceBrlCents:90,priceEurCents:90});

export const EDITORIAL_CATALOG:EditorialEntry[]=[
  standard({productKey:"jornal_negocios_economia",slug:"jornal-negocios-economia",kind:"jornal",icon:"📈",title:"Jornal LDR — Negócios & Economia",subtitle:"Mercado, empresas e decisões que movem a economia",description:"Leitura semanal sobre economia, empresas, empreendedorismo, emprego, tecnologia aplicada aos negócios e movimentos de mercado.",topics:["Economia","Empresas","Mercado","Empreendedorismo","Emprego","Tecnologia"],color:"#0b2341"}),
  standard({productKey:"jornal_politica_economia",slug:"jornal-politica-economia",kind:"jornal",icon:"🏛️",title:"Jornal LDR — Política & Economia",subtitle:"Política econômica com contexto e fontes",description:"Decisões governamentais, inflação, emprego, impostos e economia internacional, separando notícia, análise e opinião.",topics:["Política econômica","Inflação","Emprego","Impostos","Economia internacional"],color:"#24364b",notice:"Conteúdo editorial com neutralidade: notícia, análise e opinião são identificadas separadamente."}),
  standard({productKey:"jornal_europa",slug:"jornal-europa",kind:"jornal",icon:"🇪🇺",title:"Jornal LDR — Europa",subtitle:"Europa em foco toda semana",description:"União Europeia, Bélgica, Portugal, França, Espanha, economia europeia, trabalho, legislação relevante e acontecimentos que afetam quem vive ou faz negócios na Europa.",topics:["União Europeia","Bélgica","Portugal","França","Espanha","Economia europeia"],color:"#173f6b",notice:"Regras legais e governamentais devem indicar país, data e fonte oficial."}),
  standard({productKey:"jornal_migracao_mobilidade",slug:"jornal-migracao-mobilidade",kind:"jornal",icon:"🌍",title:"Jornal LDR — Migração & Mobilidade",subtitle:"Política migratória e vida internacional",description:"Vistos, residência, trabalho internacional, mudanças regulatórias, integração e mobilidade dentro da Europa.",topics:["Migração","Vistos","Residência","Trabalho internacional","Integração"],color:"#285c63",notice:"Informação migratória é informativa e deve citar fontes oficiais; não substitui assessoria jurídica."}),
  standard({productKey:"revista_fofoca",slug:"revista-fofoca",kind:"revista",icon:"💬",title:"Revista Fofoca & Celebridades",subtitle:"Entretenimento, famosos e cultura pop",description:"Famosos, redes sociais, cultura pop, tendências e bastidores públicos, com rumor claramente separado de informação confirmada.",topics:["Celebridades","Entretenimento","Redes sociais","Cultura pop","Tendências"],color:"#7a1740",notice:"Rumores nunca são apresentados como fatos confirmados."}),
  standard({productKey:"revista_robotica_ia",slug:"revista-robotica-ia",kind:"revista",icon:"🤖",title:"Revista Robótica & Inteligência Artificial",subtitle:"Tecnologia, automação e futuro",description:"Robótica, inteligência artificial, automação, inovação, novos equipamentos, pesquisas e aplicações práticas.",topics:["Robótica","IA","Automação","Inovação","Pesquisa"],color:"#254a7a"}),
  standard({productKey:"revista_gastronomia",slug:"revista-gastronomia-culinaria",kind:"revista",icon:"🍳",title:"Revista Gastronomia & Culinária",subtitle:"Receitas, técnicas e negócios gastronômicos",description:"Receitas, gastronomia internacional, culinária brasileira e europeia, técnicas culinárias e pequenos negócios de alimentação.",topics:["Receitas","Gastronomia","Brasil","Europa","Negócios gastronômicos"],color:"#8b4b23"}),
  standard({productKey:"revista_negocios",slug:"revista-negocios",kind:"revista",icon:"💼",title:"Revista Negócios",subtitle:"Empreendedorismo, vendas e expansão",description:"Empreendedorismo, vendas, marketing, liderança, gestão, oportunidades e internacionalização de negócios.",topics:["Empreendedorismo","Vendas","Marketing","Liderança","Gestão","Internacionalização"],color:"#183d63"}),
  standard({productKey:"revista_saude_mental",slug:"revista-saude-mental",kind:"revista",icon:"🧠",title:"Revista Saúde Mental",subtitle:"Comportamento, bem-estar e estudos",description:"Saúde mental, comportamento, bem-estar, psicanálise, estudos recentes e prevenção com linguagem responsável.",topics:["Saúde mental","Comportamento","Bem-estar","Psicanálise","Pesquisa"],color:"#514275",notice:"Conteúdo informativo; não substitui avaliação médica, psicológica ou psiquiátrica."}),
  standard({productKey:"revista_saude_bem_estar",slug:"revista-saude-bem-estar",kind:"revista",icon:"❤️",title:"Revista Saúde & Bem-Estar",subtitle:"Informação confiável para qualidade de vida",description:"Saúde, prevenção, hábitos, qualidade de vida e ciência sem promessas de cura.",topics:["Saúde","Prevenção","Hábitos","Qualidade de vida","Ciência"],color:"#9b3d4a",notice:"Conteúdo informativo e educativo, sem diagnóstico ou promessa de cura."}),
  standard({productKey:"revista_estetica",slug:"revista-estetica",kind:"revista",icon:"✨",title:"Revista Estética",subtitle:"Beleza, procedimentos e mercado",description:"Estética, beleza, procedimentos, tendências, cuidados e mercado profissional, distinguindo conteúdo informativo de orientação médica.",topics:["Estética","Beleza","Procedimentos","Tendências","Mercado"],color:"#8d5b76",notice:"Conteúdo informativo; procedimentos de saúde exigem avaliação profissional adequada."}),
  standard({productKey:"revista_rural",slug:"revista-rural",kind:"revista",icon:"🌱",title:"Revista Rural",subtitle:"Campo, tecnologia e oportunidades",description:"Agricultura, agronegócio, pequenos produtores, tecnologia rural, sustentabilidade e oportunidades no campo.",topics:["Agricultura","Agronegócio","Produtor rural","Tecnologia rural","Sustentabilidade"],color:"#3f6d42"}),
  standard({productKey:"revista_viagem",slug:"revista-viagem",kind:"revista",icon:"✈️",title:"Revista Viagem",subtitle:"Destinos, cultura e experiências",description:"Destinos no Brasil e na Europa, turismo, cultura, roteiros, gastronomia e dicas para viajantes.",topics:["Destinos","Europa","Brasil","Turismo","Cultura","Gastronomia"],color:"#2d6680"}),
  standard({productKey:"revista_migracao_exterior",slug:"revista-migracao-vida-exterior",kind:"revista",icon:"🌍",title:"Revista Migração & Vida no Exterior",subtitle:"Viver, trabalhar e se adaptar fora do país",description:"Documentação, trabalho, adaptação, cultura, integração e oportunidades internacionais.",topics:["Vida no exterior","Documentação","Trabalho","Adaptação","Integração"],color:"#3d5f73",notice:"Conteúdo informativo e baseado em fontes oficiais quando tratar de regras migratórias."}),
  standard({productKey:"revista_carreira_trabalho_internacional",slug:"revista-carreira-trabalho-internacional",kind:"revista",icon:"🌐",title:"Revista Carreira & Trabalho Internacional",subtitle:"Carreira global, recrutamento e oportunidades",description:"Carreira internacional, currículo, entrevistas, mercado de trabalho, recrutamento, competências e adaptação profissional em diferentes países.",topics:["Carreira internacional","Currículo","Entrevistas","Recrutamento","Mercado de trabalho","Competências"],color:"#164a72"}),
  {productKey:"revista_vida_luciano",slug:"a-vida-de-luciano",kind:"revista",icon:"📖",title:"A Vida de Luciano",subtitle:"Uma história real em novos capítulos toda semana",description:"Revista semanal em capítulos sobre trajetória, mudanças, empreendedorismo, psicanálise, negócios, aprendizados e bastidores dos projetos.",topics:["Trajetória","Empreendedorismo","Psicanálise","Negócios","Bastidores","Aprendizados"],priceBrlCents:2990,priceEurCents:500,color:"#5b0824"},
];

export function findEditorialBySlug(slug:string){return EDITORIAL_CATALOG.find(x=>x.slug===slug)??null;}
export function findEditorialByProductKey(productKey:string){return EDITORIAL_CATALOG.find(x=>x.productKey===productKey)??null;}
export function editorialPath(productKey:EditorialProduct){if(productKey==="jornal_ldr")return "/cliente/biblioteca/jornal-ldr";if(productKey==="revista_ldr")return "/cliente/biblioteca/revista-ldr";const item=findEditorialByProductKey(productKey);return item?`/cliente/biblioteca/publicacoes/${item.slug}`:"/cliente/biblioteca/publicacoes";}
export function editorialTitle(productKey:EditorialProduct){if(productKey==="jornal_ldr")return "Jornal LDR";if(productKey==="revista_ldr")return "Revista LDR";return findEditorialByProductKey(productKey)?.title??"Publicação LDR";}
export function editorialPrices(productKey:EditorialProduct){if(productKey==="revista_vida_luciano")return {priceBrlCents:2990,priceEurCents:500};return {priceBrlCents:90,priceEurCents:90};}
