export type MestreObrasModule={number:number;title:string;hours:number;objectives:string[];topics:string[];practice:string;assessment:string;references:string[]};

export const MESTRE_DE_OBRAS_600H={
 slug:"mestre-de-obras-gestao-execucao-controle-600h",
 productKey:"formacao_mestre_de_obras_600h",
 category:"construcao-civil",
 track:"Construção Civil",
 hours:600,
 certificate:true,
 subscriptionOnly:true,
 title:"Mestre de Obras — Gestão, Execução e Controle de Obras",
 description:"Formação livre avançada de 600 horas para desenvolver competências de leitura de projeto, planejamento, organização de canteiro, acompanhamento de serviços, qualidade, produtividade, comunicação e controle da execução. Não substitui habilitação profissional, licença, certificação obrigatória ou responsabilidade técnica legalmente exigida.",
 completionPolicy:"Carga acadêmica estimada de 600 horas, sem bloqueio artificial por tempo conectado. A conclusão depende do percurso acadêmico e das avaliações configuradas.",
 modules:[
 {number:1,title:"Papel do mestre de obras e organização da produção",hours:30,objectives:["Delimitar responsabilidades operacionais e interfaces técnicas","Organizar frentes de serviço e comunicação de campo"],topics:["estrutura organizacional da obra","responsabilidade e limites de atuação","ordens de serviço","diário de obra","coordenação de equipes","ética e comunicação"],practice:"Construir o mapa de responsabilidades e fluxo de informação de uma obra simulada.",assessment:"Estudo de caso sobre tomada de decisão e escalonamento técnico.",references:["Mattos, Aldo Dórea. Planejamento e Controle de Obras. Oficina de Textos.","Souza, Ubiraci E. Lemes de. Como Aumentar a Eficiência da Mão de Obra. PINI."]},
 {number:2,title:"Leitura e compatibilização de projetos",hours:30,objectives:["Interpretar plantas, cortes, fachadas e detalhes","Identificar interferências antes da execução"],topics:["escalas e cotas","projeto arquitetônico","estrutural","instalações","detalhamento","compatibilização","RFI e registro de dúvidas"],practice:"Analisar um conjunto didático de plantas e produzir lista de interferências.",assessment:"Exercício de interpretação e compatibilização.",references:["ABNT NBR 6492 — Documentação técnica para projetos arquitetônicos e urbanísticos — Requisitos.","Ching, Francis D. K. Representação Gráfica em Arquitetura. Bookman."]},
 {number:3,title:"Planejamento executivo e sequenciamento",hours:30,objectives:["Transformar escopo em sequência executável","Controlar restrições e curto prazo"],topics:["EAP","precedências","cronograma","linha de balanço","planejamento semanal","restrições","percentual de planos concluídos"],practice:"Elaborar planejamento de seis semanas para uma obra didática.",assessment:"Defesa do sequenciamento e análise de desvios.",references:["Mattos, Aldo Dórea. Planejamento e Controle de Obras. Oficina de Textos.","Ballard, Glenn. The Last Planner System of Production Control. University of Birmingham."]},
 {number:4,title:"Canteiro, logística e fluxos",hours:30,objectives:["Planejar fluxos seguros e produtivos","Reduzir movimentações e perdas"],topics:["layout de canteiro","acessos","armazenamento","movimentação","equipamentos","sinalização","resíduos","logística interna"],practice:"Projetar layout funcional de canteiro para cenário fornecido.",assessment:"Auditoria simulada de logística e riscos.",references:["Souza, Ubiraci E. Lemes de. Projeto e Implantação do Canteiro. O Nome da Rosa.","NR 18 — Segurança e Saúde no Trabalho na Indústria da Construção."]},
 {number:5,title:"Materiais de construção e recebimento",hours:30,objectives:["Reconhecer propriedades relevantes dos materiais","Estruturar inspeção de recebimento e armazenamento"],topics:["cimento","agregados","aço","blocos","argamassas","madeira","gesso","revestimentos","rastreabilidade"],practice:"Criar fichas de recebimento e critérios de aceitação.",assessment:"Análise de não conformidades de materiais.",references:["Bauer, L. A. Falcão. Materiais de Construção. LTC.","Neville, A. M.; Brooks, J. J. Tecnologia do Concreto. Bookman."]},
 {number:6,title:"Locação, níveis e controle geométrico",hours:30,objectives:["Compreender referências, eixos, níveis e prumo","Planejar verificações geométricas"],topics:["gabarito","eixos","cotas","nível","prumo","esquadro","instrumentos","tolerâncias","registros"],practice:"Elaborar plano de conferência geométrica por etapa.",assessment:"Resolução de situações de locação e conferência.",references:["Borges, Alberto de Campos. Topografia Aplicada à Engenharia Civil. Blucher.","McCormac, Jack. Topografia. LTC."]},
 {number:7,title:"Terraplenagem, fundações e contenções",hours:30,objectives:["Reconhecer etapas e controles executivos","Identificar situações que exigem decisão técnica especializada"],topics:["movimento de terra","compactação","escavação","fundações rasas","fundações profundas","contenções","drenagem","registros de execução"],practice:"Preparar checklist executivo e pontos de parada para inspeção.",assessment:"Estudo de caso de anomalia durante fundação.",references:["Velloso, Dirceu A.; Lopes, Francisco R. Fundações. Oficina de Textos.","ABNT NBR 6122 — Projeto e execução de fundações."]},
 {number:8,title:"Formas, armaduras e concreto",hours:30,objectives:["Coordenar controles prévios à concretagem","Reconhecer falhas executivas recorrentes"],topics:["formas","escoramento","armaduras","cobrimento","embutidos","recebimento do concreto","adensamento","cura","desforma","rastreabilidade"],practice:"Executar inspeção documental simulada pré-concretagem.",assessment:"Plano de concretagem e tratamento de não conformidades.",references:["ABNT NBR 14931 — Execução de estruturas de concreto — Procedimento.","Neville, A. M.; Brooks, J. J. Tecnologia do Concreto. Bookman."]},
 {number:9,title:"Alvenarias e vedações",hours:30,objectives:["Planejar execução racionalizada de vedações","Controlar geometria e interfaces"],topics:["marcação","elevação","amarração","vergas","contravergas","encunhamento","interfaces com instalações","controle dimensional"],practice:"Criar procedimento de inspeção de alvenaria.",assessment:"Diagnóstico de falhas em painel didático.",references:["Thomaz, Ercio et al. Código de Práticas nº 1: Alvenaria de Vedação em Blocos Cerâmicos. IPT/SindusCon-SP.","ABNT NBR 16868 — Alvenaria estrutural."]},
 {number:10,title:"Instalações hidráulicas e sanitárias — interfaces de obra",hours:30,objectives:["Coordenar interfaces civis das instalações","Identificar verificações antes do fechamento"],topics:["shafts","passagens","água fria","água quente","esgoto","ventilação","águas pluviais","testes","registros"],practice:"Montar checklist de liberação para fechamento de shafts.",assessment:"Compatibilização de instalações em ambiente didático.",references:["ABNT NBR 5626 — Sistemas prediais de água fria e água quente — Projeto, execução, operação e manutenção.","ABNT NBR 8160 — Sistemas prediais de esgoto sanitário — Projeto e execução."]},
 {number:11,title:"Instalações elétricas — interfaces de obra",hours:30,objectives:["Compreender interfaces entre construção e instalação elétrica","Controlar passagens e condições antes dos acabamentos"],topics:["eletrodutos","caixas","quadros","infraestrutura","aterramento","compatibilização","inspeção visual","limites de atuação"],practice:"Produzir mapa de interfaces elétricas/civis.",assessment:"Estudo de caso de interferências e retrabalho.",references:["ABNT NBR 5410 — Instalações elétricas de baixa tensão.","Cotrim, Ademaro A. M. B. Instalações Elétricas. Pearson."]},
 {number:12,title:"Impermeabilização e estanqueidade",hours:30,objectives:["Reconhecer sistemas e pontos críticos","Organizar controle antes da proteção e acabamento"],topics:["substrato","caimentos","mantas","membranas","rodapés","ralos","juntas","teste de estanqueidade","proteção mecânica"],practice:"Criar plano de inspeção de área molhada.",assessment:"Diagnóstico de infiltração em estudo de caso.",references:["ABNT NBR 9575 — Impermeabilização — Seleção e projeto.","ABNT NBR 9574 — Execução de impermeabilização."]},
 {number:13,title:"Revestimentos, pisos e acabamentos",hours:30,objectives:["Planejar sequência e condições de aplicação","Controlar qualidade visual e funcional"],topics:["chapisco","emboço","reboco","gesso","cerâmica","pedras","pisos","juntas","planeza","aderência","proteção"],practice:"Montar plano de liberação de ambientes para acabamento.",assessment:"Inspeção simulada com classificação de defeitos.",references:["ABNT NBR 13749 — Revestimento de paredes e tetos de argamassas inorgânicas — Especificação.","ABNT NBR 13753 — Revestimento de piso interno ou externo com placas cerâmicas e com utilização de argamassa colante — Procedimento."]},
 {number:14,title:"Pintura, fachadas e proteção superficial",hours:30,objectives:["Avaliar preparação de base e condições de aplicação","Estruturar inspeção e aceitação"],topics:["substratos","umidade","preparação","seladores","massas","tintas","demãos","fachadas","falhas de pintura","manutenção"],practice:"Criar procedimento de mock-up e inspeção de pintura.",assessment:"Análise causal de manifestações em acabamento pintado.",references:["ABNT NBR 13245 — Tintas para construção civil — Execução de pinturas em edificações não industriais — Preparação de superfície.","Fazenda, Jorge M. R. Tintas: Ciência e Tecnologia. Blucher."]},
 {number:15,title:"Coberturas, esquadrias e envoltória",hours:30,objectives:["Coordenar interfaces de estanqueidade da envoltória","Planejar inspeções antes da entrega"],topics:["telhados","rufos","calhas","esquadrias","selantes","fachadas","drenagem","estanqueidade","interfaces"],practice:"Elaborar mapa de pontos críticos da envoltória.",assessment:"Plano de prevenção de infiltrações.",references:["ABNT NBR 10821 — Esquadrias para edificações.","ABNT NBR 15575 — Edificações habitacionais — Desempenho."]},
 {number:16,title:"Qualidade, inspeções e não conformidades",hours:30,objectives:["Estruturar inspeção baseada em critérios","Tratar desvios com rastreabilidade"],topics:["plano de inspeção","fichas de verificação","evidências","não conformidade","causa","ação corretiva","liberação de serviço","rastreabilidade"],practice:"Construir sistema simples de inspeção para cinco serviços.",assessment:"Tratamento completo de uma não conformidade simulada.",references:["ISO 9001:2015 — Quality management systems — Requirements.","ABNT NBR 15575 — Edificações habitacionais — Desempenho."]},
 {number:17,title:"Produtividade, medições e controle de custos",hours:30,objectives:["Relacionar produção, recursos e custo","Acompanhar avanço físico com evidências"],topics:["apropriação","produtividade","consumo","perdas","medição","avanço físico","orçamento","desvios","indicadores"],practice:"Montar boletim semanal de produção e consumo.",assessment:"Análise de produtividade e proposta de melhoria.",references:["TCPO — Tabelas de Composições de Preços para Orçamentos. PINI.","Mattos, Aldo Dórea. Como Preparar Orçamentos de Obras. Oficina de Textos."]},
 {number:18,title:"Segurança, saúde e organização preventiva",hours:30,objectives:["Integrar prevenção ao planejamento operacional","Reconhecer riscos e interromper condições inseguras conforme procedimentos aplicáveis"],topics:["gestão de riscos","proteções coletivas","EPI","trabalho em altura","escavações","máquinas","ordem e limpeza","DDS","emergência"],practice:"Realizar análise didática de riscos de uma frente de trabalho.",assessment:"Plano preventivo para etapa crítica simulada.",references:["NR 18 — Segurança e Saúde no Trabalho na Indústria da Construção.","NR 35 — Trabalho em Altura."]},
 {number:19,title:"Patologias, diagnóstico inicial e prevenção",hours:30,objectives:["Reconhecer manifestações patológicas comuns","Registrar evidências sem extrapolar responsabilidade técnica"],topics:["fissuras","umidade","descolamentos","corrosão","deformações","causas prováveis","registro","prevenção","encaminhamento técnico"],practice:"Produzir relatório fotográfico didático de manifestação patológica.",assessment:"Estudo de caso com hipóteses, evidências e encaminhamento.",references:["Helene, Paulo R. L. Manual para Reparo, Reforço e Proteção de Estruturas de Concreto. PINI.","Thomaz, Ercio. Trincas em Edifícios: Causas, Prevenção e Recuperação. Oficina de Textos."]},
 {number:20,title:"Entrega da obra, liderança e projeto integrador",hours:30,objectives:["Integrar planejamento, qualidade, produção e comunicação","Preparar entrega e transição para operação"],topics:["liderança situacional","reuniões de produção","punch list","as built","manual e registros","entrega","lições aprendidas","projeto integrador"],practice:"Desenvolver plano executivo completo para uma obra didática, do canteiro à entrega.",assessment:"Projeto integrador final com cronograma, logística, inspeções, riscos, indicadores e plano de entrega.",references:["Mattos, Aldo Dórea. Planejamento e Controle de Obras. Oficina de Textos.","PMI. A Guide to the Project Management Body of Knowledge (PMBOK Guide). Project Management Institute."]}
 ] as MestreObrasModule[],
 media:{audioRequired:true,imageRequired:true,altTextRequired:true},
 quality:{noPlaceholder:true,noRepeatedModules:true,referencesMustBeVerifiedBeforeProduction:true},
 disclaimer:"Formação livre. O conteúdo educacional não confere atribuição técnica, registro profissional ou autorização para executar atividades reservadas a profissionais legalmente habilitados. Normas e requisitos devem ser conferidos em sua versão vigente e na jurisdição da obra."
} as const;
