import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { resolveClient } from "@/lib/client-portal.server";
import { hasOwnerDigitalAccess } from "@/lib/owner-digital-access.server";

const PRODUCT_KEY="curso_gratuito_organizar_carreira";
const PRODUCT_SLUG="curso-gratuito-organizar-carreira";
const TITLE="Como Organizar sua Carreira e Dar o Próximo Passo Profissional";
const TOTAL_DAYS=7;
const db=supabaseAdmin as any;
function fail(message:string):never{throw new Error(message)}
async function customerFor(userId:string,email:string|null){const ctx=await resolveClient(userId,email);if(ctx.status!=="ok")fail("Acesso do cliente não disponível.");return ctx.customer;}
function daysSince(value:string|null|undefined){if(!value)return 0;const time=Date.parse(value);if(!Number.isFinite(time))return 0;return Math.max(0,Math.floor((Date.now()-time)/86_400_000));}
async function ensureProgram(){const description="Curso gratuito de 7 dias, 100% em formato de leitura, sem aulas ao vivo, com atividades práticas e acesso sem expiração.";const {data:existing}=await db.from("training_programs").select("id,slug,title,status").eq("slug",PRODUCT_SLUG).maybeSingle();if(existing){if(existing.status!=="published")await db.from("training_programs").update({status:"published",description}).eq("id",existing.id);return {...existing,status:"published"};}const {data,error}=await db.from("training_programs").insert({slug:PRODUCT_SLUG,title:TITLE,description,status:"published"}).select("id,slug,title,status").single();if(error||!data)throw error??new Error("Falha ao preparar o curso gratuito.");return data;}
async function enrollment(customerId:string){try{const training=await ensureProgram();const {data}=await db.from("training_enrollments").select("id,enrolled_at,progress_percent,completed_at,certificate_available_at").eq("training_id",training.id).eq("customer_id",customerId).eq("active",true).maybeSingle();return {training,data:data??null};}catch(error){console.warn("free career enrollment lookup skipped",error);return {training:null,data:null};}}
async function savedProgress(customerId:string){const {data}=await db.from("library_progress").select("progress_percent,current_location,updated_at").eq("customer_id",customerId).eq("product_key",PRODUCT_KEY).maybeSingle();return data??null;}
export async function getFreeCareerCourse(userId:string,email:string|null){const customer=await customerFor(userId,email);const current=await enrollment(customer.id);const owner=hasOwnerDigitalAccess(email,userId);const enrolled=Boolean(current.data)||owner;const enrolledAt=(current.data?.enrolled_at??(owner?new Date(0).toISOString():null)) as string|null;const elapsedDays=owner?TOTAL_DAYS:daysSince(enrolledAt);const progress=await savedProgress(customer.id);return {productKey:PRODUCT_KEY,slug:PRODUCT_SLUG,title:TITLE,free:true,readingOnly:true,liveClasses:false,totalLessons:7,totalDays:TOTAL_DAYS,readingMinutes:"15–20",entitled:enrolled,accessNeverExpires:true,enrolledAt,elapsedDays,progressPercent:Number(progress?.progress_percent??current.data?.progress_percent??0)};}
export async function enrollFreeCareerCourse(userId:string,email:string|null){const customer=await customerFor(userId,email);const current=await enrollment(customer.id);if(current.data)return getFreeCareerCourse(userId,email);if(!current.training)fail("Não foi possível preparar o curso gratuito.");const {error}=await db.from("training_enrollments").insert({training_id:current.training.id,customer_id:customer.id,active:true});if(error)fail("Não foi possível iniciar o curso gratuito.");return getFreeCareerCourse(userId,email);}
