import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { resolveClient } from "@/lib/client-portal.server";
import { hasOwnerDigitalAccess } from "@/lib/owner-digital-access.server";
const PRODUCT_KEY="formacao_gratuita_gestao_pessoas_rh",SLUG="formacao-gratuita-gestao-pessoas-rh",TITLE="Formação em Gestão de Pessoas e Recursos Humanos",HOURS=600;const db=supabaseAdmin as any;
function fail(m:string):never{throw new Error(m)}
async function customerFor(uid:string,email:string|null){const c=await resolveClient(uid,email);if(c.status!=="ok")fail("Acesso do cliente não disponível.");return c.customer;}
async function ensureProgram(){const description="Formação livre e profissional gratuita em Gestão de Pessoas e Recursos Humanos, 600 horas, 100% online, por leitura e atividades, sem aulas ao vivo obrigatórias.";const {data:e}=await db.from("training_programs").select("id,slug,status").eq("slug",SLUG).maybeSingle();if(e){if(e.status!=="published")await db.from("training_programs").update({status:"published",description}).eq("id",e.id);return e;}const {data,error}=await db.from("training_programs").insert({slug:SLUG,title:TITLE,description,status:"published"}).select("id,slug,status").single();if(error||!data)throw error??new Error("Falha ao preparar formação de RH.");return data;}
async function enrollment(cid:string){try{const training=await ensureProgram();const {data}=await db.from("training_enrollments").select("id,enrolled_at,progress_percent,completed_at").eq("training_id",training.id).eq("customer_id",cid).eq("active",true).maybeSingle();return{training,data:data??null};}catch(e){console.warn("HR formation enrollment lookup skipped",e);return{training:null,data:null};}}
export async function getFreeHrFormation(uid:string,email:string|null){const c=await customerFor(uid,email),x=await enrollment(c.id),owner=hasOwnerDigitalAccess(email,uid);return{productKey:PRODUCT_KEY,slug:SLUG,title:TITLE,free:true,readingOnly:true,liveClasses:false,hours:HOURS,totalModules:12,totalUnits:65,entitled:owner||!!x.data,accessNeverExpires:true,enrolledAt:x.data?.enrolled_at??null,progressPercent:x.data?.progress_percent??0,completedAt:x.data?.completed_at??null};}
export async function enrollFreeHrFormation(uid:string,email:string|null){const c=await customerFor(uid,email),x=await enrollment(c.id);if(x.data)return getFreeHrFormation(uid,email);if(!x.training)fail("Não foi possível preparar a formação de RH.");const {error}=await db.from("training_enrollments").insert({training_id:x.training.id,customer_id:c.id,active:true});if(error)fail("Não foi possível iniciar a formação de RH.");return getFreeHrFormation(uid,email);}
