import { getRequest } from "@tanstack/react-start/server";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { resolveClient } from "@/lib/client-portal.server";
import { hasOwnerDigitalAccess } from "@/lib/owner-digital-access.server";
import { hasActiveLibrarySubscription } from "@/lib/library-subscription.server";

const PRODUCT_KEY="formacao_gestao_pessoas_rh";
const SLUG="formacao-gratuita-gestao-pessoas-rh";
const TITLE="Formação em Gestão de Pessoas e Recursos Humanos";
const HOURS=600;
const PRICE_BRL=29_999;
const PRICE_EUR=4_990;
type Market="BR"|"INTL";
const db=supabaseAdmin as any;

function fail(m:string):never{throw new Error(m)}
async function customerFor(uid:string,email:string|null){const c=await resolveClient(uid,email);if(c.status!=="ok")fail("Acesso do cliente não disponível.");return c.customer;}
function matches(order:any){const metadata=(order?.metadata??{}) as Record<string,unknown>;const key=typeof metadata.product_key==="string"?metadata.product_key:"";return order?.catalog_key===PRODUCT_KEY||key===PRODUCT_KEY||key===SLUG;}
async function paidOrder(cid:string){const {data,error}=await db.from("orders").select("id,catalog_key,payment_status,metadata,created_at").eq("customer_id",cid).eq("payment_status","pago").order("created_at",{ascending:false});if(error)fail("Não foi possível verificar a compra da formação.");return(data??[]).find(matches)??null;}
function appOrigin(){const request=getRequest();return process.env.CLIENT_PANEL_URL?.replace(/\/$/,"")||(request?new URL(request.url).origin:"https://painel.ldrrhestrategia.com");}
async function ensureProgram(){const description="Formação livre de caráter profissional em Gestão de Pessoas e Recursos Humanos, 600 horas e 100% online, disponível por compra individual ou pela assinatura ativa da Biblioteca LDR.";const {data:e}=await db.from("training_programs").select("id,slug,status").eq("slug",SLUG).maybeSingle();if(e){await db.from("training_programs").update({status:"published",description,title:TITLE}).eq("id",e.id);return{...e,status:"published"};}const {data,error}=await db.from("training_programs").insert({slug:SLUG,title:TITLE,description,status:"published"}).select("id,slug,status").single();if(error||!data)throw error??new Error("Falha ao preparar formação de RH.");return data;}
async function enrollment(cid:string){try{const training=await ensureProgram();const {data}=await db.from("training_enrollments").select("id,enrolled_at,progress_percent,completed_at,product_key,active").eq("training_id",training.id).eq("customer_id",cid).eq("active",true).order("enrolled_at",{ascending:false}).limit(1).maybeSingle();return{training,data:data??null};}catch(e){console.warn("HR formation enrollment lookup skipped",e);return{training:null,data:null};}}
async function ensureEnrollment(cid:string,entitled:boolean){if(!entitled)return null;const x=await enrollment(cid);if(x.data)return x.data;if(!x.training)return null;const {data,error}=await db.from("training_enrollments").insert({training_id:x.training.id,customer_id:cid,active:true,product_key:PRODUCT_KEY}).select("id,enrolled_at,progress_percent,completed_at,product_key,active").single();if(error){console.warn("HR formation enrollment provisioning skipped",error);return null;}return data;}

export async function getFreeHrFormation(uid:string,email:string|null){const c=await customerFor(uid,email),x=await enrollment(c.id),owner=hasOwnerDigitalAccess(email,uid),order=await paidOrder(c.id);const legacy=!!x.data&&!x.data.product_key;const subscription=!legacy&&!owner&&!order?await hasActiveLibrarySubscription(c.id):false;const entitled=owner||legacy||!!order||subscription;const e=await ensureEnrollment(c.id,entitled);return{productKey:PRODUCT_KEY,slug:SLUG,title:TITLE,free:false,priceBrlCents:PRICE_BRL,priceEurCents:PRICE_EUR,readingOnly:true,hours:HOURS,totalModules:12,totalUnits:65,entitled,lifetimeAccess:owner||legacy||!!order,subscriptionAccess:subscription,grandfathered:legacy,enrolledAt:e?.enrolled_at??x.data?.enrolled_at??null,progressPercent:e?.progress_percent??x.data?.progress_percent??0,completedAt:e?.completed_at??x.data?.completed_at??null};}

export async function createHrFormationCheckout(uid:string,email:string|null,market:Market){const c=await customerFor(uid,email),offer=await getFreeHrFormation(uid,email);if(offer.entitled)fail("Esta formação já está disponível para sua conta.");const amount=market==="BR"?PRICE_BRL:PRICE_EUR,currency=market==="BR"?"BRL":"EUR",metadata={product_key:PRODUCT_KEY,training_slug:SLUG,market,auth_user_id:uid};const {data:order,error}=await db.from("orders").insert({order_number:"",customer_id:c.id,contact_email:c.email,contact_phone:c.phone,service_type:"produto_digital",title:TITLE,description:"Formação em Gestão de Pessoas e Recursos Humanos · 600 horas · 100% online · pagamento único · acesso vitalício",quantity:1,amount_cents:amount,currency,payment_status:"pendente",status:"novo",priority:"media",catalog_key:PRODUCT_KEY,metadata}).select("id").single();if(error||!order)fail("Não foi possível iniciar o pedido da formação.");const secret=process.env.STRIPE_SECRET_KEY;if(!secret){await db.from("orders").delete().eq("id",order.id);fail("Pagamento temporariamente indisponível.");}const params=new URLSearchParams();params.set("mode","payment");params.set("line_items[0][price_data][currency]",currency.toLowerCase());params.set("line_items[0][price_data][unit_amount]",String(amount));params.set("line_items[0][price_data][product_data][name]",TITLE);params.set("line_items[0][quantity]","1");params.set("success_url",`${appOrigin()}/cliente/formacoes/gestao-pessoas-rh?payment=success&session_id={CHECKOUT_SESSION_ID}`);params.set("cancel_url",`${appOrigin()}/cliente/formacoes/gestao-pessoas-rh?payment=cancel`);params.set("client_reference_id",uid);params.set("metadata[order_id]",order.id);params.set("metadata[product_key]",PRODUCT_KEY);params.set("metadata[training_slug]",SLUG);params.set("metadata[user_id]",uid);params.set("metadata[market]",market);params.set("payment_intent_data[metadata][order_id]",order.id);params.set("payment_intent_data[metadata][product_key]",PRODUCT_KEY);if(c.email)params.set("customer_email",c.email);let response:Response;try{response=await fetch("https://api.stripe.com/v1/checkout/sessions",{method:"POST",headers:{Authorization:`Bearer ${secret}`,"Content-Type":"application/x-www-form-urlencoded"},body:params});}catch{await db.from("orders").delete().eq("id",order.id);fail("Não foi possível abrir o checkout.");}const session=await response.json() as {id?:string;url?:string;error?:{message?:string}};if(!response.ok||!session.id||!session.url){await db.from("orders").delete().eq("id",order.id);fail(session.error?.message||"Não foi possível abrir o checkout.");}await db.from("orders").update({stripe_checkout_session_id:session.id,metadata}).eq("id",order.id);return{url:session.url};}
