import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { resolveClient } from "@/lib/client-portal.server";
import { hasOwnerDigitalAccess } from "@/lib/owner-digital-access.server";
const PRODUCT_KEY="curso_gratuito_primeiros_socorros",SLUG="curso-gratuito-primeiros-socorros",TITLE="Primeiros Socorros — Noções Básicas",DAYS=30;const db=supabaseAdmin as any;
function fail(m:string):never{throw new Error(m)}async function customerFor(uid:string,email:string|null){const c=await resolveClient(uid,email);if(c.status!=="ok")fail("Acesso do cliente não disponível.");return c.customer;}function daysSince(v:string|null|undefined){if(!v)return 0;const t=Date.parse(v);return Number.isFinite(t)?Math.max(0,Math.floor((Date.now()-t)/86400000)):0;}
async function ensureProgram(){const description="Curso gratuito e introdutório de Primeiros Socorros — Noções Básicas: 30 aulas, 10 horas, 100% leitura, sem aulas ao vivo, sem habilitação profissional e com acesso sem expiração.";const {data:e}=await db.from("training_programs").select("id,slug,status").eq("slug",SLUG).maybeSingle();if(e){if(e.status!=="published")await db.from("training_programs").update({status:"published",description}).eq("id",e.id);return e;}const {data,error}=await db.from("training_programs").insert({slug:SLUG,title:TITLE,description,status:"published"}).select("id,slug,status").single();if(error||!data)throw error??new Error("Falha ao preparar Primeiros Socorros.");return data;}
async function enrollment(cid:string){try{const training=await ensureProgram();const {data}=await db.from("training_enrollments").select("id,enrolled_at,progress_percent,completed_at").eq("training_id",training.id).eq("customer_id",cid).eq("active",true).maybeSingle();return{training,data:data??null};}catch(e){console.warn("First aid enrollment lookup skipped",e);return{training:null,data:null};}}
export async function getFreeFirstAid(uid:string,email:string|null){const c=await customerFor(uid,email),x=await enrollment(c.id),owner=hasOwnerDigitalAccess(email,uid),entitled=owner||!!x.data,enrolledAt=(x.data?.enrolled_at??(owner?new Date(0).toISOString():null)) as string|null;return{productKey:PRODUCT_KEY,slug:SLUG,title:TITLE,free:true,readingOnly:true,liveClasses:false,totalLessons:30,totalDays:DAYS,hours:10,professionalCertification:false,entitled,accessNeverExpires:true,enrolledAt,elapsedDays:owner?DAYS:daysSince(enrolledAt)};}
export async function enrollFreeFirstAid(uid:string,email:string|null){const c=await customerFor(uid,email),x=await enrollment(c.id);if(x.data)return getFreeFirstAid(uid,email);if(!x.training)fail("Não foi possível preparar Primeiros Socorros.");const {error}=await db.from("training_enrollments").insert({training_id:x.training.id,customer_id:c.id,active:true});if(error)fail("Não foi possível iniciar Primeiros Socorros.");return getFreeFirstAid(uid,email);}
