import { getRequest } from "@tanstack/react-start/server";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { resolveClient } from "@/lib/client-portal.server";
const db=supabaseAdmin as any;
export type LdrPassPlan="pass"|"pro"|"business"; export type LdrPassMarket="BR"|"EU"; export type LdrPassBilling="monthly"|"annual";
const PRICES={pass:{BR:{monthly:["price_1UHqKWKlx2LyNGeB5VwHHNZk",4990],annual:["price_1UHqKZKlx2LyNGeBSbnEW7HZ",49900]},EU:{monthly:["price_1UHqKcKlx2LyNGeB5bMFTwr4",990],annual:["price_1UHqKeKlx2LyNGeBH7r4vwc4",9900]}},pro:{BR:{monthly:["price_1UHqKgKlx2LyNGeB9T6rrMTA",14990],annual:["price_1UHqKjKlx2LyNGeBAggVSrCe",149900]},EU:{monthly:["price_1UHqKlKlx2LyNGeBsZXQLh21",2990],annual:["price_1UHqKpKlx2LyNGeBHBvSqNIH",29900]}},business:{BR:{monthly:["price_1UHqKrKlx2LyNGeBkhYcufVw",49900],annual:["price_1UHqKtKlx2LyNGeBKtFk2oYW",499000]},EU:{monthly:["price_1UHqKvKlx2LyNGeBnjpoACBl",9900],annual:["price_1UHqKyKlx2LyNGeBEWAt0AAH",99000]}}} as const;
function fail(m:string):never{throw new Error(m)} function origin(){const r=getRequest();return process.env.CLIENT_PANEL_URL?.replace(/\/$/,"")||(r?new URL(r.url).origin:"https://ldracademy.online")} async function customerFor(u:string,e:string|null){const c=await resolveClient(u,e);if(c.status!=="ok")fail("Acesso do cliente não disponível.");return c.customer}
export function ldrPassPrice(plan:LdrPassPlan,market:LdrPassMarket,billing:LdrPassBilling){const [priceId,amount]=PRICES[plan][market][billing];return {priceId,amount,currency:market==="BR"?"BRL":"EUR"}}
export async function getLdrPassContext(u:string,e:string|null){const customer=await customerFor(u,e);const {data,error}=await db.from("ldr_pass_subscriptions").select("*").eq("customer_id",customer.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(error)fail("Não foi possível carregar o LDR PASS.");return {customer,subscription:data??null,active:data?.status==="active"||data?.status==="trialing"}}
export async function createLdrPassCheckout(u:string,e:string|null,plan:LdrPassPlan,market:LdrPassMarket,billing:LdrPassBilling,source:string){const customer=await customerFor(u,e);const {data:existing}=await db.from("ldr_pass_subscriptions").select("id,status").eq("customer_id",customer.id).in("status",["active","trialing","past_due","unpaid","paused","incomplete"]).limit(1).maybeSingle();if(existing)fail("Você já possui um LDR PASS em andamento.");const p=ldrPassPrice(plan,market,billing),safeSource=["academy","ldrrhestrategia","ecossistema"].includes(source)?source:"academy";const {data:row,error}=await db.from("ldr_pass_subscriptions").insert({customer_id:customer.id,plan,market,currency:p.currency,billing_cycle:billing,amount_cents:p.amount,status:"pending",source:safeSource}).select("id").single();if(error||!row)fail("Não foi possível preparar o LDR PASS.");const secret=process.env.STRIPE_SECRET_KEY;if(!secret){await db.from("ldr_pass_subscriptions").delete().eq("id",row.id);fail("Pagamento temporariamente indisponível.");}const q=new URLSearchParams();q.set("mode","subscription");q.set("line_items[0][price]",p.priceId);q.set("line_items[0][quantity]","1");q.set("success_url",`${origin()}/cliente/ldr-pass?subscription=success&session_id={CHECKOUT_SESSION_ID}`);q.set("cancel_url",`${origin()}/ldr-pass?subscription=cancel`);q.set("client_reference_id",u);q.set("billing_address_collection","auto");for(const [k,v] of Object.entries({checkout_kind:"ldr_pass_subscription",ldr_pass_subscription_id:row.id,customer_id:customer.id,plan,market,billing_cycle:billing,source:safeSource})){q.set(`metadata[${k}]`,v);q.set(`subscription_data[metadata][${k}]`,v)}if(customer.email)q.set("customer_email",customer.email);const response=await fetch("https://api.stripe.com/v1/checkout/sessions",{method:"POST",headers:{Authorization:`Bearer ${secret}`,"Content-Type":"application/x-www-form-urlencoded"},body:q});const session=await response.json() as any;if(!response.ok||!session.id||!session.url){await db.from("ldr_pass_subscriptions").delete().eq("id",row.id);fail(session?.error?.message||"Não foi possível abrir o checkout.");}await db.from("ldr_pass_subscriptions").update({stripe_checkout_session_id:session.id,updated_at:new Date().toISOString()}).eq("id",row.id);return {url:session.url}}
