import { getRequest } from "@tanstack/react-start/server";
import { paidCourseProjectApproved } from "@/lib/paid-course-project-policy.server";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { resolveClient } from "@/lib/client-portal.server";
import { hasOwnerDigitalAccess } from "@/lib/owner-digital-access.server";
const PRODUCT_KEY="formacao_massoterapia",PRODUCT_SLUG="formacao-completa-massoterapia",TITLE="Formação Completa em Massoterapia";
const PRICE_BRL=29_999,PRICE_EUR=4_990,TOTAL_LESSONS=300,TOTAL_HOURS=1200,MINIMUM_DAYS=150;
type Market="BR"|"INTL";const db=supabaseAdmin as any;
function fail(message:string):never{throw new Error(message)}
async function customerFor(userId:string,email:string|null){const ctx=await resolveClient(userId,email);if(ctx.status!=="ok")fail("Acesso do cliente não disponível.");return ctx.customer;}
function appOrigin(){const request=getRequest();return process.env.CLIENT_PANEL_URL?.replace(/\/$/,"")||(request?new URL(request.url).origin:"https://painel.ldrrhestrategia.com");}
function daysSince(v:string|null|undefined){if(!v)return 0;const t=Date.parse(v);return Number.isFinite(t)?Math.max(0,Math.floor((Date.now()-t)/86400000)):0;}
function matches(o:any){const m=(o?.metadata??{}) as Record<string,unknown>;const k=typeof m.product_key==="string"?m.product_key:"";return o?.catalog_key===PRODUCT_KEY||k===PRODUCT_KEY||k===PRODUCT_SLUG;}
async function paidOrder(customerId:string){const {data,error}=await db.from("orders").select("id,catalog_key,payment_status,metadata,created_at").eq("customer_id",customerId).eq("payment_status","pago").order("created_at",{ascending:false});if(error)fail("Não foi possível verificar o acesso.");return(data??[]).find(matches)??null;}
async function ensureProgram(){const {data:e}=await db.from("training_programs").select("id,slug,status").eq("slug",PRODUCT_SLUG).maybeSingle();if(e){if(e.status!=="published")await db.from("training_programs").update({status:"published"}).eq("id",e.id);return e;}const {data,error}=await db.from("training_programs").insert({slug:PRODUCT_SLUG,title:TITLE,description:"Formação profissional livre em Massoterapia: 15 módulos, 300 aulas, 1.200 horas, 100% online, percurso recomendado de 6 a 12 meses e sem encontros ao vivo nesta etapa.",status:"published"}).select("id").single();if(error||!data)throw error??new Error("Falha ao preparar a formação.");return data;}
async function ensureEnrollment(customerId:string,entitled:boolean){if(!entitled)return null;try{const training=await ensureProgram();let {data:e}=await db.from("training_enrollments").select("id,enrolled_at,progress_percent,certificate_available_at").eq("training_id",training.id).eq("customer_id",customerId).eq("active",true).maybeSingle();if(!e){const r=await db.from("training_enrollments").insert({training_id:training.id,customer_id:customerId,active:true,product_key:PRODUCT_KEY}).select("id,enrolled_at,progress_percent,certificate_available_at").single();e=r.data;}return e;}catch(error){console.warn("massotherapy enrollment skipped",error);return null;}}
async function savedProgress(customerId:string){const {data}=await db.from("library_progress").select("progress_percent,current_location,updated_at").eq("customer_id",customerId).eq("product_key",PRODUCT_KEY).maybeSingle();return data??null;}
export async function getMassotherapyOffer(userId:string,email:string|null){const customer=await customerFor(userId,email);const owner=hasOwnerDigitalAccess(email??customer.email,userId);
  const order=owner?null:await paidOrder(customer.id);const entitled=Boolean(order)||owner;const enrollment=await ensureEnrollment(customer.id,entitled);const progress=await savedProgress(customer.id);const enrolledAt=(enrollment?.enrolled_at??order?.created_at??null) as string|null;const elapsedDays=owner?MINIMUM_DAYS:daysSince(enrolledAt);const maxUnlockedLesson=owner?TOTAL_LESSONS:Math.min(TOTAL_LESSONS,(elapsedDays+1)*2);const progressPercent=Number(progress?.progress_percent??enrollment?.progress_percent??0);
  const projectApproved=await paidCourseProjectApproved(customer.id,"formacao-completa-massoterapia");const certificateEligible=entitled&&elapsedDays>=MINIMUM_DAYS&&progressPercent>=100&&projectApproved;return{productKey:PRODUCT_KEY,slug:PRODUCT_SLUG,title:TITLE,priceBrlCents:PRICE_BRL,priceEurCents:PRICE_EUR,entitled,lifetimeAccess:true,minimumMonths:6,maximumMonths:12,minimumDays:MINIMUM_DAYS,liveSessionsIncluded:0,totalModules:15,totalLessons:TOTAL_LESSONS,totalHours:TOTAL_HOURS,enrolledAt,elapsedDays,maxUnlockedLesson,progressPercent,certificateEligible};}
export async function createMassotherapyCheckout(userId:string,email:string|null,market:Market){const customer=await customerFor(userId,email);const offer=await getMassotherapyOffer(userId,email);if(offer.entitled)fail("Esta formação já está disponível para sua conta.");const amountCents=market==="BR"?PRICE_BRL:PRICE_EUR,currency=market==="BR"?"BRL":"EUR";const metadata={product_key:PRODUCT_KEY,training_slug:PRODUCT_SLUG,market,auth_user_id:userId};const {data:order,error}=await db.from("orders").insert({order_number:"",customer_id:customer.id,contact_email:customer.email,contact_phone:customer.phone,service_type:"produto_digital",title:TITLE,description:"Formação Completa em Massoterapia · pagamento único · acesso vitalício",quantity:1,amount_cents:amountCents,currency,payment_status:"pendente",status:"novo",priority:"media",catalog_key:PRODUCT_KEY,metadata}).select("id").single();if(error||!order)fail("Não foi possível iniciar o pedido.");const secret=process.env.STRIPE_SECRET_KEY;if(!secret){await db.from("orders").delete().eq("id",order.id);fail("Pagamento temporariamente indisponível.");}const p=new URLSearchParams();p.set("mode","payment");p.set("line_items[0][price_data][currency]",currency.toLowerCase());p.set("line_items[0][price_data][unit_amount]",String(amountCents));p.set("line_items[0][price_data][product_data][name]",TITLE);p.set("line_items[0][quantity]","1");p.set("success_url",`${appOrigin()}/cliente/biblioteca?payment=success&product=massoterapia&session_id={CHECKOUT_SESSION_ID}`);p.set("cancel_url",`${appOrigin()}/cliente/biblioteca?payment=cancel&product=massoterapia`);p.set("client_reference_id",userId);p.set("metadata[order_id]",order.id);p.set("metadata[product_key]",PRODUCT_KEY);p.set("metadata[training_slug]",PRODUCT_SLUG);p.set("metadata[user_id]",userId);p.set("metadata[market]",market);p.set("payment_intent_data[metadata][order_id]",order.id);p.set("payment_intent_data[metadata][product_key]",PRODUCT_KEY);if(customer.email)p.set("customer_email",customer.email);let response:Response;try{response=await fetch("https://api.stripe.com/v1/checkout/sessions",{method:"POST",headers:{Authorization:`Bearer ${secret}`,"Content-Type":"application/x-www-form-urlencoded"},body:p});}catch{await db.from("orders").delete().eq("id",order.id);fail("Não foi possível abrir o checkout.");}const session=(await response.json()) as {id?:string;url?:string};if(!response.ok||!session.id||!session.url){await db.from("orders").delete().eq("id",order.id);fail("Não foi possível abrir o checkout.");}await db.from("orders").update({stripe_checkout_session_id:session.id,metadata}).eq("id",order.id);return{url:session.url};}
