import type { PF } from "@/lib/professional-formations.catalog";

const base={priceBrlCents:29999,priceEurCents:4990,hours:600,lessons:144,modulesCount:12,minimumDays:75,includedInSubscription:true};

export const NEW_PROFESSIONAL_FORMATIONS = [
{
 slug:"aba-autismo",productKey:"formacao_aba_autismo_600h",publicPath:"/formacao/aba-autismo",learnerPath:"/cliente/treinamentos/formacao-profissional/aba-autismo",icon:"🧠",theme:"purple",...base,
 i18n:{
  pt:{name:"Formação em ABA Aplicada ao Autismo",short:"ABA Aplicada ao Autismo",category:"Autismo & Comportamento",description:"Formação livre profissional avançada em Análise do Comportamento Aplicada, autismo, avaliação, comunicação, autonomia, ética, neurodiversidade e suportes individualizados.",project:"Plano Integrado de Avaliação e Apoio Comportamental Individualizado no Autismo",disclaimer:"Formação livre profissional. Não concede certificações BACB (BCBA, BCaBA ou RBT), licença clínica ou habilitação automática para atos reservados a profissões regulamentadas.",modules:["Fundamentos Filosóficos e Científicos da Análise do Comportamento","Autismo, Neurodesenvolvimento e Necessidades de Suporte","Avaliação Comportamental e Análise de Dados","Aprendizagem e Mudança Comportamental","Modelos Compreensivos e Intervenções Naturalísticas","Família, Cuidadores e Generalização","Ética, Direitos, Assentimento e Neurodiversidade","Supervisão, Equipes e Qualidade de Implementação","Suportes Individualizados nos Níveis 1, 2 e 3","Pesquisa e Prática Baseada em Evidências","Tópicos Avançados: CAA, Tecnologia e Ciclo de Vida","Laboratório de Casos e Prática Aplicada Simulada"]},
  en:{name:"Applied Behavior Analysis (ABA) for Autism Training",short:"ABA for Autism",category:"Autism & Behavior",description:"Advanced professional non-degree training in Applied Behavior Analysis, autism, assessment, communication, autonomy, ethics, neurodiversity and individualized support.",project:"Integrated Individualized Behavioral Assessment and Support Plan for Autism",disclaimer:"Professional non-degree training. It does not grant BACB certifications (BCBA, BCaBA or RBT), clinical licensure, or automatic qualification for regulated professional acts.",modules:["Philosophical and Scientific Foundations of Behavior Analysis","Autism, Neurodevelopment and Support Needs","Behavioral Assessment and Data Analysis","Learning and Behavior Change","Comprehensive Models and Naturalistic Interventions","Families, Caregivers and Generalization","Ethics, Rights, Assent and Neurodiversity","Supervision, Teams and Implementation Quality","Individualized Support Across Levels 1, 2 and 3","Research and Evidence-Based Practice","Advanced Topics: AAC, Technology and Lifespan","Case Laboratory and Simulated Applied Practice"]},
  fr:{name:"Formation en ABA Appliquée à l’Autisme",short:"ABA et Autisme",category:"Autisme & Comportement",description:"Formation professionnelle libre avancée en analyse appliquée du comportement, autisme, évaluation, communication, autonomie, éthique, neurodiversité et soutiens individualisés.",project:"Plan Intégré d’Évaluation et de Soutien Comportemental Individualisé dans l’Autisme",disclaimer:"Formation professionnelle libre. Elle n’accorde pas les certifications BACB (BCBA, BCaBA ou RBT), ni licence clinique ni habilitation automatique à des actes réglementés.",modules:["Fondements Philosophiques et Scientifiques de l’Analyse du Comportement","Autisme, Neurodéveloppement et Besoins de Soutien","Évaluation Comportementale et Analyse des Données","Apprentissage et Changement Comportemental","Modèles Globaux et Interventions Naturalistes","Familles, Aidants et Généralisation","Éthique, Droits, Assentiment et Neurodiversité","Supervision, Équipes et Qualité de Mise en Œuvre","Soutiens Individualisés aux Niveaux 1, 2 et 3","Recherche et Pratique Fondée sur les Preuves","Thèmes Avancés : CAA, Technologie et Parcours de Vie","Laboratoire de Cas et Pratique Appliquée Simulée"]},
  es:{name:"Formación en ABA Aplicada al Autismo",short:"ABA y Autismo",category:"Autismo & Comportamiento",description:"Formación profesional libre avanzada en Análisis Aplicado de la Conducta, autismo, evaluación, comunicación, autonomía, ética, neurodiversidad y apoyos individualizados.",project:"Plan Integrado de Evaluación y Apoyo Conductual Individualizado en Autismo",disclaimer:"Formación profesional libre. No concede certificaciones BACB (BCBA, BCaBA o RBT), licencia clínica ni habilitación automática para actos regulados.",modules:["Fundamentos Filosóficos y Científicos del Análisis de Conducta","Autismo, Neurodesarrollo y Necesidades de Apoyo","Evaluación Conductual y Análisis de Datos","Aprendizaje y Cambio de Conducta","Modelos Integrales e Intervenciones Naturalistas","Familias, Cuidadores y Generalización","Ética, Derechos, Asentimiento y Neurodiversidad","Supervisión, Equipos y Calidad de Implementación","Apoyos Individualizados en los Niveles 1, 2 y 3","Investigación y Práctica Basada en Evidencias","Temas Avanzados: CAA, Tecnología y Ciclo Vital","Laboratorio de Casos y Práctica Aplicada Simulada"]}
 }
},
{
 slug:"saude-mental-praticas-clinicas",productKey:"formacao_saude_mental_praticas_clinicas_600h",publicPath:"/formacao/saude-mental-praticas-clinicas",learnerPath:"/cliente/treinamentos/formacao-profissional/saude-mental-praticas-clinicas",icon:"🧩",theme:"petrol",...base,
 i18n:{
  pt:{name:"Saúde Mental e Práticas Clínicas Baseadas em Evidências",short:"Saúde Mental e Evidências",category:"Saúde Mental",description:"Formação livre avançada em saúde mental, escuta, modelos clínicos, formulação de casos, ética, investigação e prática baseada em evidências.",project:"Formulação Clínica Integrativa e Plano de Intervenção Baseado em Evidências",disclaimer:"Esta formação não substitui graduação, registro profissional ou habilitação legal exigidos para o exercício de profissões regulamentadas.",modules:["Fundamentos da Saúde Mental","Escuta, Entrevista e Relação Clínica","Modelos Psicodinâmicos","Abordagens Humanistas e Existenciais","Abordagens Cognitivo-Comportamentais","Terapias Contextuais e Processuais","Modelos Sistêmicos e Relacionais","Psicopatologia e Formulação de Casos","Avaliação e Tomada de Decisão","Prática Baseada em Evidências","Ética, Diversidade e Limites Profissionais","Laboratório de Formulação e Estudos de Caso"]},
  en:{name:"Mental Health and Evidence-Based Clinical Practices",short:"Mental Health & Evidence",category:"Mental Health",description:"Advanced professional non-degree training in mental health, listening, clinical models, case formulation, ethics, research and evidence-based practice.",project:"Integrative Clinical Formulation and Evidence-Based Intervention Plan",disclaimer:"This training does not replace a degree, professional registration, licensure or other legal requirements for regulated professions.",modules:["Foundations of Mental Health","Listening, Interviewing and Clinical Relationship","Psychodynamic Models","Humanistic and Existential Approaches","Cognitive Behavioral Approaches","Contextual and Process-Based Therapies","Systemic and Relational Models","Psychopathology and Case Formulation","Assessment and Decision-Making","Evidence-Based Practice","Ethics, Diversity and Professional Boundaries","Case Formulation Laboratory"]},
  fr:{name:"Santé Mentale et Pratiques Cliniques Fondées sur les Preuves",short:"Santé Mentale & Preuves",category:"Santé Mentale",description:"Formation professionnelle libre avancée en santé mentale, écoute, modèles cliniques, formulation de cas, éthique, recherche et pratique fondée sur les preuves.",project:"Formulation Clinique Intégrative et Plan d’Intervention Fondé sur les Preuves",disclaimer:"Cette formation ne remplace pas un diplôme, une inscription professionnelle, une autorisation d’exercice ou les exigences légales des professions réglementées.",modules:["Fondements de la Santé Mentale","Écoute, Entretien et Relation Clinique","Modèles Psychodynamiques","Approches Humanistes et Existentielles","Approches Cognitivo-Comportementales","Thérapies Contextuelles et Processuelles","Modèles Systémiques et Relationnels","Psychopathologie et Formulation de Cas","Évaluation et Prise de Décision","Pratique Fondée sur les Preuves","Éthique, Diversité et Limites Professionnelles","Laboratoire de Formulation et Études de Cas"]},
  es:{name:"Salud Mental y Prácticas Clínicas Basadas en Evidencias",short:"Salud Mental y Evidencias",category:"Salud Mental",description:"Formación profesional libre avanzada en salud mental, escucha, modelos clínicos, formulación de casos, ética, investigación y práctica basada en evidencias.",project:"Formulación Clínica Integrativa y Plan de Intervención Basado en Evidencias",disclaimer:"Esta formación no sustituye un grado, registro profesional, licencia ni otros requisitos legales de las profesiones reguladas.",modules:["Fundamentos de la Salud Mental","Escucha, Entrevista y Relación Clínica","Modelos Psicodinámicos","Enfoques Humanistas y Existenciales","Enfoques Cognitivo-Conductuales","Terapias Contextuales y Basadas en Procesos","Modelos Sistémicos y Relacionales","Psicopatología y Formulación de Casos","Evaluación y Toma de Decisiones","Práctica Basada en Evidencias","Ética, Diversidad y Límites Profesionales","Laboratorio de Formulación y Casos"]}
 }
},
{
 slug:"sociologia",productKey:"formacao_sociologia_600h",publicPath:"/formacao/sociologia",learnerPath:"/cliente/treinamentos/formacao-profissional/sociologia",icon:"🌍",theme:"terracotta",...base,
 i18n:{
  pt:{name:"Sociologia — Teorias, Métodos e Desigualdades Contemporâneas",short:"Sociologia",category:"Ciências Sociais",description:"Formação livre avançada em teoria sociológica clássica e contemporânea, métodos de investigação, análise de dados, desigualdades, instituições e transformações sociais.",project:"Diagnóstico Sociológico de um Fenômeno Social Contemporâneo",disclaimer:"Formação livre profissional e acadêmica. Não equivale a graduação em Sociologia ou Ciências Sociais.",modules:["Fundamentos da Sociologia e Imaginação Sociológica","Marx, Durkheim, Weber e Simmel","Indivíduo, Cultura, Identidade e Socialização","Bourdieu, Giddens, Foucault e Habermas","Métodos Quantitativos de Investigação","Métodos Qualitativos de Investigação","Análise e Interpretação de Dados Sociais","Classe, Gênero, Raça, Etnia e Desigualdades","Educação, Trabalho, Organizações e Profissões","Cidade, Território, Demografia e Globalização","Família, Sexualidade, Envelhecimento, Lazer e Turismo","Sociologia Aplicada, Tecnologia e Pesquisa Contemporânea"]},
  en:{name:"Sociology — Theories, Methods and Contemporary Inequalities",short:"Sociology",category:"Social Sciences",description:"Advanced non-degree training in classical and contemporary sociological theory, research methods, data analysis, inequalities, institutions and social change.",project:"Sociological Diagnosis of a Contemporary Social Phenomenon",disclaimer:"Professional and academic non-degree training. It is not a university degree in Sociology or Social Sciences.",modules:["Foundations of Sociology and Sociological Imagination","Marx, Durkheim, Weber and Simmel","Individual, Culture, Identity and Socialization","Bourdieu, Giddens, Foucault and Habermas","Quantitative Research Methods","Qualitative Research Methods","Social Data Analysis and Interpretation","Class, Gender, Race, Ethnicity and Inequalities","Education, Work, Organizations and Professions","City, Territory, Demography and Globalization","Family, Sexuality, Aging, Leisure and Tourism","Applied Sociology, Technology and Contemporary Research"]},
  fr:{name:"Sociologie — Théories, Méthodes et Inégalités Contemporaines",short:"Sociologie",category:"Sciences Sociales",description:"Formation libre avancée en théorie sociologique classique et contemporaine, méthodes de recherche, analyse de données, inégalités, institutions et transformations sociales.",project:"Diagnostic Sociologique d’un Phénomène Social Contemporain",disclaimer:"Formation professionnelle et académique libre. Elle ne constitue pas un diplôme universitaire de sociologie ou de sciences sociales.",modules:["Fondements de la Sociologie et Imagination Sociologique","Marx, Durkheim, Weber et Simmel","Individu, Culture, Identité et Socialisation","Bourdieu, Giddens, Foucault et Habermas","Méthodes Quantitatives de Recherche","Méthodes Qualitatives de Recherche","Analyse et Interprétation des Données Sociales","Classe, Genre, Race, Ethnicité et Inégalités","Éducation, Travail, Organisations et Professions","Ville, Territoire, Démographie et Mondialisation","Famille, Sexualité, Vieillissement, Loisirs et Tourisme","Sociologie Appliquée, Technologie et Recherche Contemporaine"]},
  es:{name:"Sociología — Teorías, Métodos y Desigualdades Contemporáneas",short:"Sociología",category:"Ciencias Sociales",description:"Formación libre avanzada en teoría sociológica clásica y contemporánea, métodos de investigación, análisis de datos, desigualdades, instituciones y transformaciones sociales.",project:"Diagnóstico Sociológico de un Fenómeno Social Contemporáneo",disclaimer:"Formación profesional y académica libre. No equivale a un grado universitario en Sociología o Ciencias Sociales.",modules:["Fundamentos de Sociología e Imaginación Sociológica","Marx, Durkheim, Weber y Simmel","Individuo, Cultura, Identidad y Socialización","Bourdieu, Giddens, Foucault y Habermas","Métodos Cuantitativos de Investigación","Métodos Cualitativos de Investigación","Análisis e Interpretación de Datos Sociales","Clase, Género, Raza, Etnia y Desigualdades","Educación, Trabajo, Organizaciones y Profesiones","Ciudad, Territorio, Demografía y Globalización","Familia, Sexualidad, Envejecimiento, Ocio y Turismo","Sociología Aplicada, Tecnología e Investigación Contemporánea"]}
 }
},
{
 slug:"filosofia-clinica",productKey:"formacao_filosofia_clinica_600h",publicPath:"/formacao/filosofia-clinica",learnerPath:"/cliente/treinamentos/formacao-profissional/filosofia-clinica",icon:"🏛️",theme:"wine",...base,
 i18n:{
  pt:{name:"Filosofia Clínica — Método, Escuta e Filosofia Aplicada",short:"Filosofia Clínica",category:"Filosofia Aplicada",description:"Formação livre avançada em filosofia aplicada, historicidade, fenomenologia, hermenêutica, existencialismo, linguagem, escuta, ética e análise de narrativas.",project:"Análise Filosófica de Caso e Projeto de Escuta Aplicada",disclaimer:"Formação livre em filosofia aplicada. Não substitui habilitação legal exigida para profissões clínicas regulamentadas e não concede licença clínica.",modules:["Fundamentos da Filosofia Aplicada","História da Filosofia e Cuidado de Si","Historicidade, Biografia e Narrativa","Fenomenologia e Experiência Vivida","Hermenêutica e Interpretação","Existencialismo, Liberdade e Responsabilidade","Filosofia da Linguagem e Comunicação","Estrutura de Pensamento, Categorias e Perspectivas","Emoções, Valores, Subjetividade e Pré-Juízos","Escuta Filosófica e Construção de Hipóteses","Ética, Limites e Aplicações Organizacionais e Educacionais","Laboratório de Casos Filosóficos e Projeto Final"]},
  en:{name:"Clinical Philosophy — Method, Listening and Applied Philosophy",short:"Clinical Philosophy",category:"Applied Philosophy",description:"Advanced non-degree training in applied philosophy, historicity, phenomenology, hermeneutics, existentialism, language, listening, ethics and narrative analysis.",project:"Philosophical Case Analysis and Applied Listening Project",disclaimer:"Non-degree training in applied philosophy. It does not replace legal qualifications for regulated clinical professions and does not grant clinical licensure.",modules:["Foundations of Applied Philosophy","History of Philosophy and Care of the Self","Historicity, Biography and Narrative","Phenomenology and Lived Experience","Hermeneutics and Interpretation","Existentialism, Freedom and Responsibility","Philosophy of Language and Communication","Structure of Thought, Categories and Perspectives","Emotions, Values, Subjectivity and Prejudgments","Philosophical Listening and Hypothesis Building","Ethics, Boundaries and Organizational and Educational Applications","Philosophical Case Laboratory and Final Project"]},
  fr:{name:"Philosophie Clinique — Méthode, Écoute et Philosophie Appliquée",short:"Philosophie Clinique",category:"Philosophie Appliquée",description:"Formation libre avancée en philosophie appliquée, historicité, phénoménologie, herméneutique, existentialisme, langage, écoute, éthique et analyse narrative.",project:"Analyse Philosophique de Cas et Projet d’Écoute Appliquée",disclaimer:"Formation libre en philosophie appliquée. Elle ne remplace pas les qualifications légales des professions cliniques réglementées et n’accorde pas de licence clinique.",modules:["Fondements de la Philosophie Appliquée","Histoire de la Philosophie et Souci de Soi","Historicité, Biographie et Récit","Phénoménologie et Expérience Vécue","Herméneutique et Interprétation","Existentialisme, Liberté et Responsabilité","Philosophie du Langage et Communication","Structure de Pensée, Catégories et Perspectives","Émotions, Valeurs, Subjectivité et Préjugements","Écoute Philosophique et Construction d’Hypothèses","Éthique, Limites et Applications Organisationnelles et Éducatives","Laboratoire de Cas Philosophiques et Projet Final"]},
  es:{name:"Filosofía Clínica — Método, Escucha y Filosofía Aplicada",short:"Filosofía Clínica",category:"Filosofía Aplicada",description:"Formación libre avanzada en filosofía aplicada, historicidad, fenomenología, hermenéutica, existencialismo, lenguaje, escucha, ética y análisis de narrativas.",project:"Análisis Filosófico de Caso y Proyecto de Escucha Aplicada",disclaimer:"Formación libre en filosofía aplicada. No sustituye habilitaciones legales de profesiones clínicas reguladas ni concede licencia clínica.",modules:["Fundamentos de Filosofía Aplicada","Historia de la Filosofía y Cuidado de Sí","Historicidad, Biografía y Narrativa","Fenomenología y Experiencia Vivida","Hermenéutica e Interpretación","Existencialismo, Libertad y Responsabilidad","Filosofía del Lenguaje y Comunicación","Estructura de Pensamiento, Categorías y Perspectivas","Emociones, Valores, Subjetividad y Prejuicios","Escucha Filosófica y Construcción de Hipótesis","Ética, Límites y Aplicaciones Organizacionales y Educativas","Laboratorio de Casos Filosóficos y Proyecto Final"]}
 }
},
{
 slug:"ciencia-politica",productKey:"formacao_ciencia_politica_600h",publicPath:"/formacao/ciencia-politica",learnerPath:"/cliente/treinamentos/formacao-profissional/ciencia-politica",icon:"🏛️",theme:"navy",...base,
 i18n:{
  pt:{name:"Ciência Política — Teoria, Instituições e Democracia",short:"Ciência Política",category:"Ciências Sociais",description:"Formação livre avançada em teoria política, Estado, instituições, democracia, participação, políticas públicas, economia política, comunicação e política comparada.",project:"Análise Institucional e Política Comparada de um Problema Contemporâneo",disclaimer:"Formação acadêmica livre, apartidária e orientada à análise crítica. Não equivale a graduação em Ciência Política.",modules:["Fundamentos da Ciência Política","Poder, Estado, Soberania e Legitimidade","Teoria Política Clássica","Teoria Política Contemporânea","Instituições e Sistemas Políticos","Partidos, Eleições e Representação","Federalismo, Governança e Relações Intergovernamentais","Democracia, Participação e Sociedade Civil","Movimentos Sociais, Feminismos e Ação Coletiva","Economia Política, Relações Internacionais e Globalização","Comunicação Política, Opinião Pública, Populismo e Desinformação","Política Comparada, Métodos e Ciência de Dados"]},
  en:{name:"Political Science — Theory, Institutions and Democracy",short:"Political Science",category:"Social Sciences",description:"Advanced non-degree training in political theory, the state, institutions, democracy, participation, public policy, political economy, communication and comparative politics.",project:"Institutional and Comparative Political Analysis of a Contemporary Problem",disclaimer:"Non-degree academic training, non-partisan and focused on critical analysis. It is not a university degree in Political Science.",modules:["Foundations of Political Science","Power, State, Sovereignty and Legitimacy","Classical Political Theory","Contemporary Political Theory","Political Institutions and Systems","Parties, Elections and Representation","Federalism, Governance and Intergovernmental Relations","Democracy, Participation and Civil Society","Social Movements, Feminisms and Collective Action","Political Economy, International Relations and Globalization","Political Communication, Public Opinion, Populism and Disinformation","Comparative Politics, Methods and Data Science"]},
  fr:{name:"Science Politique — Théorie, Institutions et Démocratie",short:"Science Politique",category:"Sciences Sociales",description:"Formation libre avancée en théorie politique, État, institutions, démocratie, participation, politiques publiques, économie politique, communication et politique comparée.",project:"Analyse Institutionnelle et Politique Comparée d’un Problème Contemporain",disclaimer:"Formation académique libre, non partisane et orientée vers l’analyse critique. Elle ne constitue pas un diplôme universitaire en science politique.",modules:["Fondements de la Science Politique","Pouvoir, État, Souveraineté et Légitimité","Théorie Politique Classique","Théorie Politique Contemporaine","Institutions et Systèmes Politiques","Partis, Élections et Représentation","Fédéralisme, Gouvernance et Relations Intergouvernementales","Démocratie, Participation et Société Civile","Mouvements Sociaux, Féminismes et Action Collective","Économie Politique, Relations Internationales et Mondialisation","Communication Politique, Opinion Publique, Populisme et Désinformation","Politique Comparée, Méthodes et Science des Données"]},
  es:{name:"Ciencia Política — Teoría, Instituciones y Democracia",short:"Ciencia Política",category:"Ciencias Sociales",description:"Formación libre avanzada en teoría política, Estado, instituciones, democracia, participación, políticas públicas, economía política, comunicación y política comparada.",project:"Análisis Institucional y Política Comparada de un Problema Contemporáneo",disclaimer:"Formación académica libre, apartidista y orientada al análisis crítico. No equivale a un grado universitario en Ciencia Política.",modules:["Fundamentos de Ciencia Política","Poder, Estado, Soberanía y Legitimidad","Teoría Política Clásica","Teoría Política Contemporánea","Instituciones y Sistemas Políticos","Partidos, Elecciones y Representación","Federalismo, Gobernanza y Relaciones Intergubernamentales","Democracia, Participación y Sociedad Civil","Movimientos Sociales, Feminismos y Acción Colectiva","Economía Política, Relaciones Internacionales y Globalización","Comunicación Política, Opinión Pública, Populismo y Desinformación","Política Comparada, Métodos y Ciencia de Datos"]}
 }
},
{
 slug:"ciencias-felicidade",productKey:"formacao_ciencias_felicidade_600h",publicPath:"/formacao/ciencias-felicidade",learnerPath:"/cliente/treinamentos/formacao-profissional/ciencias-felicidade",icon:"☀️",theme:"gold",...base,
 i18n:{
  pt:{name:"Ciências da Felicidade e Bem-Estar — Da Neurociência à Prática",short:"Ciências da Felicidade",category:"Bem-Estar & Comportamento",description:"Formação livre avançada sobre felicidade e bem-estar, integrando filosofia, psicologia positiva, neurociência, relações, propósito, trabalho, cultura e intervenções baseadas em evidências.",project:"Programa de Promoção do Bem-Estar Baseado em Evidências",disclaimer:"Conteúdo educacional. Não promete felicidade, cura ou tratamento de condições de saúde mental e não substitui acompanhamento profissional quando necessário.",modules:["Filosofia da Felicidade e História das Ideias","Hedonismo, Eudaimonia e Bem-Estar Subjetivo","Psicologia Positiva, Forças e Florescimento","Neurociência do Bem-Estar e seus Limites","Emoções, Autorregulação e Inteligência Emocional","Hábitos, Adaptação Hedônica e Mudança Comportamental","Relações, Vínculos e Conexão Social","Propósito, Sentido, Valores e Autodeterminação","Sono, Atividade Física, Estresse e Bem-Estar","Felicidade no Trabalho, Educação e Organizações","Cultura, Renda, Desigualdade e Políticas Públicas","Intervenções Baseadas em Evidências e Projeto Final"]},
  en:{name:"Science of Happiness and Well-Being — From Neuroscience to Practice",short:"Science of Happiness",category:"Well-Being & Behavior",description:"Advanced non-degree training on happiness and well-being integrating philosophy, positive psychology, neuroscience, relationships, purpose, work, culture and evidence-based interventions.",project:"Evidence-Based Well-Being Promotion Program",disclaimer:"Educational content. It does not promise happiness, cure or treatment of mental health conditions and does not replace professional care when needed.",modules:["Philosophy of Happiness and History of Ideas","Hedonism, Eudaimonia and Subjective Well-Being","Positive Psychology, Strengths and Flourishing","Neuroscience of Well-Being and Its Limits","Emotions, Self-Regulation and Emotional Intelligence","Habits, Hedonic Adaptation and Behavior Change","Relationships, Bonds and Social Connection","Purpose, Meaning, Values and Self-Determination","Sleep, Physical Activity, Stress and Well-Being","Happiness at Work, Education and Organizations","Culture, Income, Inequality and Public Policy","Evidence-Based Interventions and Final Project"]},
  fr:{name:"Sciences du Bonheur et du Bien-Être — Des Neurosciences à la Pratique",short:"Sciences du Bonheur",category:"Bien-Être & Comportement",description:"Formation libre avancée sur le bonheur et le bien-être intégrant philosophie, psychologie positive, neurosciences, relations, sens, travail, culture et interventions fondées sur les preuves.",project:"Programme de Promotion du Bien-Être Fondé sur les Preuves",disclaimer:"Contenu éducatif. Il ne promet ni bonheur, ni guérison, ni traitement de troubles de santé mentale et ne remplace pas un accompagnement professionnel lorsque nécessaire.",modules:["Philosophie du Bonheur et Histoire des Idées","Hédonisme, Eudémonisme et Bien-Être Subjectif","Psychologie Positive, Forces et Épanouissement","Neurosciences du Bien-Être et Leurs Limites","Émotions, Autorégulation et Intelligence Émotionnelle","Habitudes, Adaptation Hédonique et Changement Comportemental","Relations, Liens et Connexion Sociale","But, Sens, Valeurs et Autodétermination","Sommeil, Activité Physique, Stress et Bien-Être","Bonheur au Travail, Éducation et Organisations","Culture, Revenu, Inégalités et Politiques Publiques","Interventions Fondées sur les Preuves et Projet Final"]},
  es:{name:"Ciencias de la Felicidad y Bienestar — De la Neurociencia a la Práctica",short:"Ciencias de la Felicidad",category:"Bienestar & Comportamiento",description:"Formación libre avanzada sobre felicidad y bienestar integrando filosofía, psicología positiva, neurociencia, relaciones, propósito, trabajo, cultura e intervenciones basadas en evidencias.",project:"Programa de Promoción del Bienestar Basado en Evidencias",disclaimer:"Contenido educativo. No promete felicidad, cura ni tratamiento de condiciones de salud mental y no sustituye atención profesional cuando sea necesaria.",modules:["Filosofía de la Felicidad e Historia de las Ideas","Hedonismo, Eudaimonía y Bienestar Subjetivo","Psicología Positiva, Fortalezas y Florecimiento","Neurociencia del Bienestar y sus Límites","Emociones, Autorregulación e Inteligencia Emocional","Hábitos, Adaptación Hedónica y Cambio Conductual","Relaciones, Vínculos y Conexión Social","Propósito, Sentido, Valores y Autodeterminación","Sueño, Actividad Física, Estrés y Bienestar","Felicidad en el Trabajo, Educación y Organizaciones","Cultura, Ingresos, Desigualdad y Políticas Públicas","Intervenciones Basadas en Evidencias y Proyecto Final"]}
 }
}
] as unknown as PF[];
