import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { resolveAccess, writeAudit } from "@/lib/access.server";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/integrations/supabase/types";

type Client=SupabaseClient<Database>;
const db=supabaseAdmin as unknown as {from:(table:string)=>any};
function fail(m:string):never{throw new Error(m)}
async function requireSuperadmin(supabase:Client,userId:string){const a=await resolveAccess(supabase,userId);if(!a.authorized||a.role!=="superadmin")fail("Acesso negado.");return a}
function list(value:string|undefined){return (value||"").split("\n").map(x=>x.trim()).filter(Boolean)}

export async function getProfessionalComplianceAdmin(supabase:Client,userId:string){await requireSuperadmin(supabase,userId);const [{data:categories},{data:rules}]=await Promise.all([
 db.from("professional_categories").select("id,slug,name_pt,name_en,name_fr,name_es,regulated_by_default,requires_admin_review,active,sort_order").order("sort_order"),
 db.from("professional_country_rules").select("*").order("country_code"),
]);return {categories:categories??[],rules:rules??[]}}

export async function saveProfessionalCountryRule(supabase:Client,userId:string,input:{id?:string|null;countryCode:string;categoryId:string;titleLabel?:string|null;requiresRegistration:boolean;requiresManualReview:boolean;registrationLabel?:string|null;requiredDocuments?:string;publicDisclosures?:string;allowedOnline:boolean;allowedInPerson:boolean;advertisingRestrictions?:string;fiscalRequirements?:string;emergencyNotice?:string|null;legalNotice?:string|null;active:boolean}){const actor=await requireSuperadmin(supabase,userId);const country=input.countryCode.trim().toUpperCase();if(!["BR","PT","BE"].includes(country))fail("País inválido.");const {data:category}=await db.from("professional_categories").select("id").eq("id",input.categoryId).maybeSingle();if(!category)fail("Categoria inválida.");const payload={country_code:country,category_id:input.categoryId,title_label:input.titleLabel?.trim()||null,requires_registration:Boolean(input.requiresRegistration),requires_manual_review:Boolean(input.requiresManualReview),registration_label:input.registrationLabel?.trim()||null,required_documents:list(input.requiredDocuments),public_disclosures:list(input.publicDisclosures),allowed_modalities:[...(input.allowedOnline?["online"]:[]),...(input.allowedInPerson?["in_person"]:[])],advertising_restrictions:list(input.advertisingRestrictions),fiscal_requirements:list(input.fiscalRequirements),emergency_notice:input.emergencyNotice?.trim()||null,legal_notice:input.legalNotice?.trim()||null,active:Boolean(input.active),reviewed_at:new Date().toISOString(),reviewed_by:userId,updated_at:new Date().toISOString()};if(!payload.allowed_modalities.length)fail("Selecione ao menos uma modalidade permitida.");let id=input.id||null;if(id){const {data,error}=await db.from("professional_country_rules").update(payload).eq("id",id).select("id").maybeSingle();if(error||!data)fail("Não foi possível atualizar a regra.")}else{const {data,error}=await db.from("professional_country_rules").upsert(payload,{onConflict:"country_code,category_id"}).select("id").single();if(error||!data)throw error??new Error("Não foi possível criar a regra.");id=data.id}await writeAudit({actorId:userId,actorEmail:actor.email,action:"professional_network.compliance_rule_saved",target:id,details:{countryCode:country,categoryId:input.categoryId}});return {ok:true as const,id}}

export async function updateProfessionalCategory(supabase:Client,userId:string,input:{categoryId:string;active:boolean;regulatedByDefault:boolean;requiresAdminReview:boolean}){const actor=await requireSuperadmin(supabase,userId);const {data,error}=await db.from("professional_categories").update({active:Boolean(input.active),regulated_by_default:Boolean(input.regulatedByDefault),requires_admin_review:Boolean(input.requiresAdminReview),updated_at:new Date().toISOString()}).eq("id",input.categoryId).select("id").maybeSingle();if(error||!data)fail("Categoria não encontrada.");await writeAudit({actorId:userId,actorEmail:actor.email,action:"professional_network.category_updated",target:input.categoryId,details:input});return {ok:true as const}}
