import { supabaseAdmin } from "@/integrations/supabase/client.server";
const db=supabaseAdmin as unknown as {from:(table:string)=>any};
function fail(m:string):never{throw new Error(m)}
const FORBIDDEN=[/cura\s+garantida/i,/resultado\s+garantido/i,/100\s*%\s*(?:de\s*)?(?:efic[aá]cia|resultado)/i,/elimina\s+(?:a\s+)?ansiedade/i,/cura\s+(?:a\s+)?depress[aã]o/i,/cura\s+(?:o\s+)?trauma/i,/resultado\s+em\s+\d+\s+sesso/i,/melhor\s+profissional/i,/n[uú]mero\s*1/i,/clientes\s+garantidos/i,/faturamento\s+garantido/i,/renda\s+garantida/i];
function validateClaims(...texts:(string|null|undefined)[]){const value=texts.filter(Boolean).join(" ");if(FORBIDDEN.some(r=>r.test(value)))fail("O texto contém promessa absoluta, sensacionalista ou incompatível com as diretrizes da Rede LDR.")}
async function context(userId:string){const {data:a}=await db.from("professional_accounts").select("id,status").eq("auth_user_id",userId).maybeSingle();if(!a)fail("Área profissional não encontrada.");const {data:p}=await db.from("professional_profiles").select("id,compliance_status,profile_status,is_public,country_code,category_id").eq("professional_account_id",a.id).maybeSingle();if(!p)fail("Complete seu perfil primeiro.");return {account:a,profile:p}}
export async function saveProfessionalService(userId:string,input:{id?:string|null;name:string;description?:string|null;modality:"online"|"in_person"|"both";durationMinutes:number;currency:"EUR"|"BRL";priceCents:number;city?:string|null;publicLocation?:string|null;bookingEnabled?:boolean}){const {profile}=await context(userId);const name=input.name.trim(),desc=input.description?.trim()||null;validateClaims(name,desc);if(name.length<3)fail("Informe o nome do serviço.");const duration=Math.round(Number(input.durationMinutes));if(duration<5||duration>480)fail("Duração inválida.");const price=Math.round(Number(input.priceCents));if(price<0)fail("Preço inválido.");if(input.modality==="in_person"&&!input.publicLocation?.trim())fail("Para atendimento presencial, informe cidade/região ou local público de atendimento.");const approved=profile.compliance_status==="approved"&&profile.profile_status==="active"&&profile.is_public;const bookingEnabled=Boolean(input.bookingEnabled)&&approved&&price>0;const payload={name,description:desc,modality:input.modality,duration_minutes:duration,currency:input.currency,price_cents:price,city:input.city?.trim()||null,public_location:input.publicLocation?.trim()||null,booking_enabled:bookingEnabled,active:true,updated_at:new Date().toISOString()};if(input.id){const {error}=await db.from("professional_services").update(payload).eq("id",input.id).eq("professional_profile_id",profile.id);if(error)throw error;return {ok:true as const,id:input.id,bookingEnabled}}
 const {data,error}=await db.from("professional_services").insert({professional_profile_id:profile.id,...payload,sort_order:100}).select("id").single();if(error||!data)fail("Não foi possível criar o serviço.");return {ok:true as const,id:data.id,bookingEnabled}}
export async function setProfessionalServiceActive(userId:string,input:{id:string;active:boolean}){const {profile}=await context(userId);const {error}=await db.from("professional_services").update({active:Boolean(input.active),booking_enabled:input.active?undefined:false,updated_at:new Date().toISOString()}).eq("id",input.id).eq("professional_profile_id",profile.id);if(error)throw error;return {ok:true as const}}
