export type PFLocale="pt"|"en"|"fr"|"es";
export type PFSlug="vendas-negociacao"|"marketing-digital"|"recrutamento-selecao"|"gestao-administrativa-financeira"|"comunicacao-oratoria";
type T={name:string;short:string;description:string;project:string;modules:string[]};
export type PF={slug:PFSlug;productKey:string;publicPath:string;learnerPath:string;icon:string;theme:string;priceBrlCents:number;priceEurCents:number;hours:number;lessons:number;modulesCount:number;minimumDays:number;i18n:Record<PFLocale,T>};
const common={priceBrlCents:29999,priceEurCents:4990,hours:600,lessons:150,modulesCount:10,minimumDays:75};
export const PROFESSIONAL_FORMATIONS:PF[]=[
{slug:"vendas-negociacao",productKey:"formacao_vendas_negociacao_atendimento",publicPath:"/formacao-vendas-negociacao",learnerPath:"/cliente/treinamentos/formacao-profissional/vendas-negociacao",icon:"🤝",theme:"navy",...common,i18n:{
pt:{name:"Formação em Vendas, Negociação e Atendimento ao Cliente",short:"Vendas e Negociação",description:"Formação prática para estruturar prospecção, atendimento, negociação, fechamento, CRM e pós-venda.",project:"Plano Comercial e Processo Completo de Vendas",modules:["Fundamentos de Vendas","Prospecção Profissional","Atendimento ao Cliente","Vendas Consultivas","Negociação","Objeções e Fechamento","Vendas Digitais","Pós-venda e Fidelização","Gestão Comercial","Vendas Internacionais e Projeto Final"]},
en:{name:"Sales, Negotiation and Customer Service Training",short:"Sales & Negotiation",description:"Practical training in prospecting, service, negotiation, closing, CRM and after-sales.",project:"Sales Plan and Complete Sales Process",modules:["Sales Foundations","Professional Prospecting","Customer Service","Consultative Selling","Negotiation","Objections and Closing","Digital Sales","After-sales and Loyalty","Sales Management","International Sales and Final Project"]},
fr:{name:"Formation en Vente, Négociation et Service Client",short:"Vente & Négociation",description:"Formation pratique en prospection, service client, négociation, conclusion, CRM et après-vente.",project:"Plan Commercial et Processus Complet de Vente",modules:["Fondamentaux de la Vente","Prospection Professionnelle","Service Client","Vente Consultative","Négociation","Objections et Conclusion","Vente Digitale","Après-vente et Fidélisation","Gestion Commerciale","Vente Internationale et Projet Final"]},
es:{name:"Formación en Ventas, Negociación y Atención al Cliente",short:"Ventas y Negociación",description:"Formación práctica en prospección, atención, negociación, cierre, CRM y posventa.",project:"Plan Comercial y Proceso Completo de Ventas",modules:["Fundamentos de Ventas","Prospección Profesional","Atención al Cliente","Venta Consultiva","Negociación","Objeciones y Cierre","Ventas Digitales","Posventa y Fidelización","Gestión Comercial","Ventas Internacionales y Proyecto Final"]}}},
{slug:"marketing-digital",productKey:"formacao_marketing_digital_redes_sociais",publicPath:"/formacao-marketing-digital",learnerPath:"/cliente/treinamentos/formacao-profissional/marketing-digital",icon:"📣",theme:"wine",...common,i18n:{
pt:{name:"Formação em Marketing Digital e Redes Sociais para Negócios",short:"Marketing Digital",description:"Marketing, posicionamento, conteúdo, funil, tráfego pago, métricas e IA aplicada aos negócios.",project:"Plano Completo de Marketing Digital",modules:["Fundamentos de Marketing","Posicionamento e Marca","Público, Persona e Proposta de Valor","Redes Sociais para Negócios","Conteúdo, Copywriting e Storytelling","Funil, Leads e Landing Pages","E-mail, WhatsApp e Automação","Tráfego Pago: Meta e Google Ads","Métricas, IA e Otimização","Estratégia Internacional e Projeto Final"]},
en:{name:"Digital Marketing and Social Media for Business Training",short:"Digital Marketing",description:"Marketing, positioning, content, funnels, paid media, metrics and AI for business.",project:"Complete Digital Marketing Plan",modules:["Marketing Foundations","Positioning and Brand","Audience, Persona and Value Proposition","Social Media for Business","Content, Copywriting and Storytelling","Funnels, Leads and Landing Pages","Email, WhatsApp and Automation","Paid Media: Meta and Google Ads","Metrics, AI and Optimization","International Strategy and Final Project"]},
fr:{name:"Formation en Marketing Digital et Réseaux Sociaux pour Entreprises",short:"Marketing Digital",description:"Marketing, positionnement, contenu, tunnel, publicité, métriques et IA appliquée aux entreprises.",project:"Plan Complet de Marketing Digital",modules:["Fondamentaux du Marketing","Positionnement et Marque","Public, Persona et Proposition de Valeur","Réseaux Sociaux pour Entreprises","Contenu, Copywriting et Storytelling","Tunnel, Leads et Landing Pages","E-mail, WhatsApp et Automatisation","Publicité: Meta et Google Ads","Métriques, IA et Optimisation","Stratégie Internationale et Projet Final"]},
es:{name:"Formación en Marketing Digital y Redes Sociales para Negocios",short:"Marketing Digital",description:"Marketing, posicionamiento, contenido, embudos, publicidad, métricas e IA aplicada a negocios.",project:"Plan Completo de Marketing Digital",modules:["Fundamentos de Marketing","Posicionamiento y Marca","Público, Persona y Propuesta de Valor","Redes Sociales para Negocios","Contenido, Copywriting y Storytelling","Embudo, Leads y Landing Pages","Email, WhatsApp y Automatización","Publicidad: Meta y Google Ads","Métricas, IA y Optimización","Estrategia Internacional y Proyecto Final"]}}},
{slug:"recrutamento-selecao",productKey:"formacao_recrutamento_selecao_profissional",publicPath:"/formacao-recrutamento-selecao",learnerPath:"/cliente/treinamentos/formacao-profissional/recrutamento-selecao",icon:"🧑‍💼",theme:"green",...common,i18n:{
pt:{name:"Formação em Recrutamento e Seleção Profissional",short:"Recrutamento e Seleção",description:"Do planejamento da vaga ao onboarding, com sourcing, triagem, entrevistas, indicadores e recrutamento internacional.",project:"Processo Completo de Recrutamento e Seleção",modules:["Fundamentos de RH e Contratação","Descrição de Cargos e Competências","Divulgação, Employer Branding e Sourcing","Triagem de Currículos","Entrevistas e Seleção por Competências","Ferramentas de Apoio e Experiência do Candidato","Diversidade, Inclusão e Proteção de Dados","Recrutamento Operacional, Comercial e Técnico","Indicadores, Feedback, Proposta e Onboarding","Recrutamento Internacional e Projeto Final"]},
en:{name:"Professional Recruitment and Selection Training",short:"Recruitment & Selection",description:"From job planning to onboarding, including sourcing, screening, interviews, metrics and international recruitment.",project:"Complete Recruitment and Selection Process",modules:["HR and Hiring Foundations","Job Descriptions and Competencies","Job Promotion, Employer Branding and Sourcing","CV Screening","Competency Interviews and Selection","Support Tools and Candidate Experience","Diversity, Inclusion and Data Protection","Operational, Sales and Technical Recruitment","Metrics, Feedback, Offer and Onboarding","International Recruitment and Final Project"]},
fr:{name:"Formation en Recrutement et Sélection Professionnelle",short:"Recrutement & Sélection",description:"De la planification du poste à l'onboarding: sourcing, tri, entretiens, indicateurs et recrutement international.",project:"Processus Complet de Recrutement et Sélection",modules:["Fondamentaux RH et Recrutement","Descriptions de Poste et Compétences","Diffusion, Marque Employeur et Sourcing","Tri des CV","Entretiens et Sélection par Compétences","Outils et Expérience Candidat","Diversité, Inclusion et Protection des Données","Recrutement Opérationnel, Commercial et Technique","Indicateurs, Feedback, Offre et Onboarding","Recrutement International et Projet Final"]},
es:{name:"Formación en Reclutamiento y Selección Profesional",short:"Reclutamiento y Selección",description:"Desde la planificación de la vacante hasta onboarding, con sourcing, criba, entrevistas, indicadores y reclutamiento internacional.",project:"Proceso Completo de Reclutamiento y Selección",modules:["Fundamentos de RR. HH. y Contratación","Descripción de Puestos y Competencias","Difusión, Employer Branding y Sourcing","Criba de Currículums","Entrevistas y Selección por Competencias","Herramientas y Experiencia del Candidato","Diversidad, Inclusión y Protección de Datos","Reclutamiento Operativo, Comercial y Técnico","Indicadores, Feedback, Oferta y Onboarding","Reclutamiento Internacional y Proyecto Final"]}}},
{slug:"gestao-administrativa-financeira",productKey:"formacao_gestao_administrativa_financeira",publicPath:"/formacao-gestao-administrativa-financeira",learnerPath:"/cliente/treinamentos/formacao-profissional/gestao-administrativa-financeira",icon:"📊",theme:"petrol",...common,i18n:{
pt:{name:"Formação em Gestão Administrativa e Financeira para Pequenos Negócios",short:"Gestão Administrativa e Financeira",description:"Administração prática, fluxo de caixa, custos, preços, indicadores e planejamento para pequenos negócios.",project:"Plano Administrativo e Financeiro de um Pequeno Negócio",modules:["Fundamentos de Administração","Planejamento e Organização Empresarial","Processos e Produtividade","Receitas, Custos e Despesas","Fluxo de Caixa e Capital de Giro","Precificação, Margem e Ponto de Equilíbrio","Orçamento, Contas e Estoque","Fornecedores, Compras e Indicadores","Riscos, Documentação e Noções Tributárias","Crescimento Sustentável e Projeto Final"]},
en:{name:"Administrative and Financial Management for Small Business Training",short:"Administrative & Financial Management",description:"Practical administration, cash flow, costs, pricing, metrics and planning for small businesses.",project:"Administrative and Financial Plan for a Small Business",modules:["Administration Foundations","Business Planning and Organization","Processes and Productivity","Revenue, Costs and Expenses","Cash Flow and Working Capital","Pricing, Margin and Break-even","Budgeting, Accounts and Inventory","Suppliers, Purchasing and Metrics","Risks, Documentation and Tax Basics","Sustainable Growth and Final Project"]},
fr:{name:"Formation en Gestion Administrative et Financière pour Petites Entreprises",short:"Gestion Administrative & Financière",description:"Administration pratique, trésorerie, coûts, prix, indicateurs et planification pour petites entreprises.",project:"Plan Administratif et Financier d'une Petite Entreprise",modules:["Fondamentaux de l'Administration","Planification et Organisation","Processus et Productivité","Revenus, Coûts et Dépenses","Trésorerie et Fonds de Roulement","Prix, Marge et Seuil de Rentabilité","Budget, Comptes et Stock","Fournisseurs, Achats et Indicateurs","Risques, Documents et Notions Fiscales","Croissance Durable et Projet Final"]},
es:{name:"Formación en Gestión Administrativa y Financiera para Pequeños Negocios",short:"Gestión Administrativa y Financiera",description:"Administración práctica, flujo de caja, costes, precios, indicadores y planificación para pequeños negocios.",project:"Plan Administrativo y Financiero de un Pequeño Negocio",modules:["Fundamentos de Administración","Planificación y Organización Empresarial","Procesos y Productividad","Ingresos, Costes y Gastos","Flujo de Caja y Capital de Trabajo","Precios, Margen y Punto de Equilibrio","Presupuesto, Cuentas e Inventario","Proveedores, Compras e Indicadores","Riesgos, Documentación y Nociones Fiscales","Crecimiento Sostenible y Proyecto Final"]}}},
{slug:"comunicacao-oratoria",productKey:"formacao_comunicacao_oratoria_inteligencia_emocional",publicPath:"/formacao-comunicacao-oratoria",learnerPath:"/cliente/treinamentos/formacao-profissional/comunicacao-oratoria",icon:"🎤",theme:"purple",...common,i18n:{
pt:{name:"Formação em Comunicação, Oratória e Inteligência Emocional no Trabalho",short:"Comunicação e Oratória",description:"Comunicação assertiva, oratória, apresentações, feedback, conflitos, liderança e habilidades emocionais no trabalho.",project:"Plano de Comunicação Profissional com Apresentação Aplicada",modules:["Fundamentos da Comunicação","Comunicação Verbal e Não Verbal","Escuta Ativa e Comunicação Assertiva","Oratória e Falar em Público","Storytelling e Apresentações","Comunicação Digital, Vídeo e Entrevistas","Persuasão Ética, Negociação e Feedback","Conflitos, Equipes e Liderança","Autoconsciência, Autorregulação e Empatia","Posicionamento Profissional e Projeto Final"]},
en:{name:"Communication, Public Speaking and Emotional Intelligence at Work Training",short:"Communication & Public Speaking",description:"Assertive communication, public speaking, presentations, feedback, conflict, leadership and emotional skills at work.",project:"Professional Communication Plan with Applied Presentation",modules:["Communication Foundations","Verbal and Non-verbal Communication","Active Listening and Assertive Communication","Public Speaking","Storytelling and Presentations","Digital Communication, Video and Interviews","Ethical Persuasion, Negotiation and Feedback","Conflict, Teams and Leadership","Self-awareness, Self-regulation and Empathy","Professional Positioning and Final Project"]},
fr:{name:"Formation en Communication, Prise de Parole et Intelligence Émotionnelle au Travail",short:"Communication & Prise de Parole",description:"Communication assertive, prise de parole, présentations, feedback, conflits, leadership et compétences émotionnelles au travail.",project:"Plan de Communication Professionnelle avec Présentation Appliquée",modules:["Fondamentaux de la Communication","Communication Verbale et Non Verbale","Écoute Active et Communication Assertive","Prise de Parole en Public","Storytelling et Présentations","Communication Digitale, Vidéo et Entretiens","Persuasion Éthique, Négociation et Feedback","Conflits, Équipes et Leadership","Conscience de Soi, Autorégulation et Empathie","Positionnement Professionnel et Projet Final"]},
es:{name:"Formación en Comunicación, Oratoria e Inteligencia Emocional en el Trabajo",short:"Comunicación y Oratoria",description:"Comunicación asertiva, oratoria, presentaciones, feedback, conflictos, liderazgo y habilidades emocionales en el trabajo.",project:"Plan de Comunicación Profesional con Presentación Aplicada",modules:["Fundamentos de Comunicación","Comunicación Verbal y No Verbal","Escucha Activa y Comunicación Asertiva","Oratoria y Hablar en Público","Storytelling y Presentaciones","Comunicación Digital, Vídeo y Entrevistas","Persuasión Ética, Negociación y Feedback","Conflictos, Equipos y Liderazgo","Autoconciencia, Autorregulación y Empatía","Posicionamiento Profesional y Proyecto Final"]}}}
];
export function getProfessionalFormation(slug:string){return PROFESSIONAL_FORMATIONS.find(x=>x.slug===slug)??null;}
export function pfText(f:PF,locale:PFLocale){return f.i18n[locale]??f.i18n.pt;}
export function buildLessons(f:PF,locale:PFLocale){const t=pfText(f,locale);const labels={pt:{lesson:"Aula",objective:"Objetivo",intro:"Nesta aula você vai compreender",apply:"Aplicação prática",exercise:"Exercício",summary:"Resumo",next:"Próximo passo"},en:{lesson:"Lesson",objective:"Objective",intro:"In this lesson you will understand",apply:"Practical application",exercise:"Exercise",summary:"Summary",next:"Next step"},fr:{lesson:"Leçon",objective:"Objectif",intro:"Dans cette leçon, vous allez comprendre",apply:"Application pratique",exercise:"Exercice",summary:"Résumé",next:"Étape suivante"},es:{lesson:"Clase",objective:"Objetivo",intro:"En esta clase comprenderás",apply:"Aplicación práctica",exercise:"Ejercicio",summary:"Resumen",next:"Siguiente paso"}}[locale];return t.modules.map((moduleTitle,mi)=>({id:mi+1,title:moduleTitle,lessons:Array.from({length:15},(_,li)=>{const n=mi*15+li+1;const phase=["fundamentos","diagnóstico","planejamento","execução","comunicação","ferramentas","análise","prática","decisão","melhoria","caso aplicado","erros comuns","boas práticas","atividade","síntese"][li];return{id:`${f.slug}-m${mi+1}-l${li+1}`,title:`${labels.lesson} ${n} · ${moduleTitle} — ${phase}`,summary:`${labels.objective}: desenvolver competência prática em ${moduleTitle.toLowerCase()}.`,content:[`${labels.intro} ${moduleTitle.toLowerCase()} de forma aplicada ao contexto profissional.`,`${labels.apply}: identifique uma situação real ou fictícia e registre como os conceitos desta unidade podem ser utilizados.`,`${labels.exercise}: descreva uma decisão concreta, os critérios usados e o resultado esperado.`,`${labels.summary}: conecte esta unidade às anteriores e mantenha evidências para o projeto final.`,`${labels.next}: avance somente após compreender como aplicar o conteúdo com ética, clareza e responsabilidade.`]};})}));}
