import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { resolveAccess, writeAudit } from "@/lib/access.server";
import type { SupabaseClient } from "@supabase/supabase-js";
import type { Database } from "@/integrations/supabase/types";
type Client=SupabaseClient<Database>;
const db=supabaseAdmin as unknown as {from:(table:string)=>any};
function fail(m:string):never{throw new Error(m)}
async function requireSuper(supabase:Client,userId:string){const a=await resolveAccess(supabase,userId);if(!a.authorized||a.role!=="superadmin")fail("Acesso negado.");return a}
export async function getPendingCatalogServices(supabase:Client,userId:string){await requireSuper(supabase,userId);const {data}=await db.from("professional_services").select("id,professional_profile_id,catalog_key,name,modality,duration_minutes,currency,price_cents,public_location,approval_status,requires_admin_review,active,created_at,professional_profiles(display_name,professional_title,country_code,compliance_status,profile_status,is_public,professional_account_id)").eq("source_type","ldr_catalog").order("created_at",{ascending:false}).limit(300);return {services:data??[]}}
export async function reviewCatalogService(supabase:Client,userId:string,input:{serviceId:string;action:"approve"|"reject"}){const actor=await requireSuper(supabase,userId);const {data:s}=await db.from("professional_services").select("id,professional_profile_id,price_cents,professional_profiles(professional_account_id,compliance_status,profile_status,is_public)").eq("id",input.serviceId).eq("source_type","ldr_catalog").maybeSingle();if(!s)fail("Serviço não encontrado.");if(input.action==="reject"){await db.from("professional_services").update({approval_status:"rejected",booking_enabled:false,active:false,updated_at:new Date().toISOString()}).eq("id",s.id)}else{const p=Array.isArray(s.professional_profiles)?s.professional_profiles[0]:s.professional_profiles;const {data:sub}=await db.from("professional_subscriptions").select("id,current_period_end").eq("professional_account_id",p?.professional_account_id).eq("status","active").order("created_at",{ascending:false}).limit(1).maybeSingle();const cycleActive=Boolean(sub)&&(!sub?.current_period_end||new Date(sub.current_period_end).getTime()>Date.now());const profileReady=p?.compliance_status==="approved"&&p?.profile_status==="active"&&Boolean(p?.is_public);await db.from("professional_services").update({approval_status:"approved",requires_admin_review:false,active:true,booking_enabled:Boolean(cycleActive&&profileReady&&Number(s.price_cents)>0),updated_at:new Date().toISOString()}).eq("id",s.id)}await writeAudit({actorId:userId,actorEmail:actor.email,action:`professional_network.catalog_service_${input.action}`,target:s.id});return {ok:true as const}}
