export type PsychoNews={category:string;title:string;summary:string;analysis?:string;source:string;sourceTitle:string;sourceDate:string;url:string;readTime:string;badge?:string};

export const PSYCHO_EDITION={
  number:"01",date:"12 de setembro de 2026",kicker:"Saúde mental, Psicanálise, ciência e sociedade em perspectiva global.",
  stories:[
    {category:"MUNDO & SAÚDE MENTAL",title:"Prevenção do suicídio continua no centro da agenda mundial de saúde mental",summary:"A OMS estima mais de 720 mil mortes por suicídio por ano. Em 2026, a campanha mundial mantém o tema ‘Changing the Narrative on Suicide’, com foco em reduzir estigma, ampliar conversas responsáveis e fortalecer políticas e estratégias de prevenção.",analysis:"Olhar da Psicanálise: falar sobre sofrimento psíquico com responsabilidade pode abrir espaço para escuta, vínculo e busca de ajuda. A prevenção exige respostas sociais e de saúde baseadas em evidências.",source:"Organização Mundial da Saúde (OMS)",sourceTitle:"World Suicide Prevention Day 2026",sourceDate:"10 set. 2026",url:"https://www.who.int/campaigns/world-suicide-prevention-day/2026",readTime:"4 min"},
    {category:"TECNOLOGIA & SAÚDE MENTAL",title:"Ferramentas digitais ampliam possibilidades de apoio em saúde mental",summary:"A OMS destacou em 2026 o Step-by-Step, intervenção digital de autoajuda para depressão e ansiedade com orientação leve de apoiadores treinados. A proposta busca ampliar acesso, especialmente em contextos com poucos recursos e crises humanitárias.",analysis:"Tecnologia pode ampliar acesso, mas ferramentas digitais não devem ser apresentadas como substitutas automáticas de avaliação e acompanhamento profissional quando estes são necessários.",source:"Organização Mundial da Saúde (OMS)",sourceTitle:"WHO Step-by-Step programme recognized as a promising innovation for mental health in humanitarian settings",sourceDate:"17 jun. 2026",url:"https://www.who.int/news/item/17-06-2026-who-step-by-step-programme-recognized-as-a-promising-innovation-for-mental-health-in-humanitarian-settings",readTime:"4 min"},
    {category:"ENVELHECIMENTO & SAÚDE MENTAL",title:"Saúde cognitiva e prevenção ganham espaço nas políticas internacionais",summary:"Novas orientações da OMS publicadas em julho de 2026 destacam fatores modificáveis ao longo da vida e indicam que até 45% do risco de demência pode ser prevenido ou adiado, reforçando a importância de políticas de saúde cerebral ao longo do ciclo de vida.",analysis:"Prevenção não significa garantia individual. O dado deve ser compreendido como estimativa populacional de risco potencialmente modificável, sem promessas de impedir doenças em casos específicos.",source:"Organização Mundial da Saúde (OMS)",sourceTitle:"New WHO guidelines: up to 45% of dementia risk could be prevented or delayed",sourceDate:"15 jul. 2026",url:"https://www.who.int/teams/mental-health-and-substance-use",readTime:"4 min"},
    {category:"BRASIL · REGULAMENTAÇÃO & PSICANÁLISE",title:"Brasil debate regulamentação da psicoterapia e possível exclusividade profissional",summary:"O Conselho Federal de Psicologia defende a regulamentação da psicoterapia e apoiou a SUG 01/2024, que propõe exclusividade para profissionais da Psicologia e médicos psiquiatras. Em maio de 2026, o Sistema Conselhos voltou a discutir estratégias para regulamentar por lei a psicoterapia como prática privativa da Psicologia.",analysis:"DEBATE EM ANDAMENTO: a própria documentação do CFP registra que a psicoterapia ainda não é prática privativa nem profissão regulamentada e que uma regulamentação desse alcance depende de lei aprovada no Congresso Nacional. A pauta é especialmente relevante para a Psicanálise e para o debate sobre autonomia de diferentes tradições clínicas.",source:"Conselho Federal de Psicologia (CFP)",sourceTitle:"Primeira APAF de 2026 delibera sobre importantes questões para o exercício profissional da Psicologia",sourceDate:"26 mai. 2026",url:"https://site.cfp.org.br/primeira-apaf-de-2026-delibera-sobre-importantes-questoes-para-o-exercicio-profissional-da-psicologia/",readTime:"6 min",badge:"DEBATE EM ANDAMENTO"},
    {category:"BRASIL · CONTEXTO JURÍDICO",title:"Psicoterapia ainda não é prática privativa no Brasil",summary:"Em material institucional sobre a regulamentação, o CFP afirma que a psicoterapia ainda não é prática privativa e que atos infralegais de conselhos profissionais, isoladamente, não regulamentam a prática para toda a sociedade.",analysis:"A revista diferencia posição institucional, proposta legislativa e direito vigente para evitar apresentar um debate político-profissional como uma proibição já aprovada.",source:"Conselho Federal de Psicologia (CFP)",sourceTitle:"Psicoterapia: no caminho da regulamentação",sourceDate:"27 fev. 2025",url:"https://site.cfp.org.br/psicoterapia-no-caminho-da-regulamentacao/",readTime:"5 min",badge:"CONTEXTO"}
  ] as PsychoNews[]
};
