export const PSYCHOANALYSIS_EBOOKS = [
  {
    key:"ebook_pratica_clinica_psicanalise", slug:"pratica-clinica-psicanalise", publicPath:"/ebooks/pratica-clinica-psicanalise", readerPath:"/cliente/biblioteca/ebook_pratica_clinica_psicanalise", color:"#314E52",
    title:"A Prática Clínica da Psicanálise", subtitle:"Estrutura, Manejo e o Início da Clínica", short:"A Prática Clínica da Psicanálise",
    description:"Um guia teórico-clínico para estruturar a prática psicanalítica com atenção ao enquadre, manejo, ética, formação permanente e sustentabilidade da clínica.",
    audience:"Psicanalistas recém-formados, estudantes em final de formação e profissionais que desejam estruturar a prática clínica com solidez teórica e ética.",
    priceBrlCents:1990, priceEurCents:490,
    chapters:["A Análise Pessoal — O Analista em Análise","A Supervisão — O Terceiro na Cena Analítica","A Formação Teórica Continuada","O Início do Percurso","A Estruturação da Clínica","O Manejo Clínico","Como Atingir Pacientes","A Entrevista Inicial","Formulação Psicanalítica","Transferência","Contratransferência","O Silêncio e o Tempo da Intervenção","Interpretação e Timing","Construção do Caso Clínico","Sigilo e Proteção de Dados","Psicanálise Online","Consultório e Hospitalidade Clínica","Gestão Financeira","Cuidado com o Analista","Identidade do Analista"]
  },
  {
    key:"ebook_psicanalise_no_mundo", slug:"psicanalise-no-mundo", publicPath:"/ebooks/psicanalise-no-mundo", readerPath:"/cliente/biblioteca/ebook_psicanalise_no_mundo", color:"#1F4E79",
    title:"A Psicanálise no Mundo", subtitle:"Regulamentação, Panorama Global e Atuação Internacional", short:"A Psicanálise no Mundo",
    description:"Uma leitura comparativa sobre presença institucional, formação, regras profissionais, circulação internacional e desafios contemporâneos da psicanálise em diferentes países.",
    audience:"Psicanalistas com interesse em atuação internacional, pesquisadores e profissionais que desejam compreender diferenças legais, culturais e institucionais entre países.",
    priceBrlCents:1990, priceEurCents:490,
    chapters:["A Força da Psicanálise no Brasil","Bélgica","Portugal","Espanha","O Déficit de Profissionais na Europa","Como Atuar Internacionalmente","Argentina","França","Alemanha","Reino Unido","Itália","Estados Unidos","Canadá","Austrália","África Lusófona","Ásia","IPA, EPF e FEPAL","Psicanálise Online Internacional","Psicanálise, Universidade e Pesquisa","O Futuro Internacional da Psicanálise"]
  },
  {
    key:"ebook_estudos_caso_psicanalise", slug:"estudos-caso-psicanalise", publicPath:"/ebooks/estudos-caso-psicanalise", readerPath:"/cliente/biblioteca/ebook_estudos_caso_psicanalise", color:"#7C3A5D",
    title:"Estudos de Caso", subtitle:"Da escuta à formulação: pensar o caso para além do sintoma", short:"Estudos de Caso",
    description:"eBook Premium de estudo avançado da construção de casos em Psicanálise: fundamentos clínicos, casos clássicos, formulação contemporânea, manejo, supervisão, ética e metodologia.",
    audience:"Psicanalistas, profissionais em formação e leitores com base teórica que desejam aprofundar construção de caso, transferência, contratransferência, manejo e escrita clínica.",
    premium:true, regularPriceBrlCents:9990, regularPriceEurCents:1990, priceBrlCents:7990, priceEurCents:1490,
    chapters:["Pensar um caso psicanaliticamente","Do relato à construção do caso","Método psicanalítico","Escuta e associação livre","Sintoma e conflito","Repetição","Transferência","Contratransferência","Resistência","Interpretação","Enquadre e manejo","Supervisão","Dora","Pequeno Hans","Homem dos Ratos","Schreber","Homem dos Lobos","Caso A.","Angústia e dependência","Impasse transferencial","Leituras clínicas","Da formulação ao manejo","Estudo de caso e pesquisa","Ética da escrita clínica"]
  },
  {
    key:"ebook_psicanalise_autismo", slug:"psicanalise-autismo", publicPath:"/ebooks/psicanalise-autismo", readerPath:"/cliente/biblioteca/ebook_psicanalise_autismo", color:"#6B6F2A",
    title:"Psicanálise e Autismo", subtitle:"Escuta, Manejo Clínico e o Debate com a ABA", short:"Psicanálise e Autismo",
    description:"Uma obra crítica sobre história, escuta, manejo, neurodiversidade, trabalho multiprofissional e o debate entre perspectivas psicanalíticas e ABA, sem promessa de cura ou reducionismos.",
    audience:"Psicanalistas, psicólogos, estudantes, profissionais e familiares interessados em uma abordagem ética, crítica e respeitosa da singularidade de pessoas autistas.",
    priceBrlCents:1990, priceEurCents:490,
    chapters:["Funcionamento Autístico","Direção do Tratamento","ABA","Neurodiversidade","Evidências e Controvérsias","Enquadre","Transferência","O Olhar da Clínica","História do Autismo","Melanie Klein","Winnicott","Frances Tustin","Bettelheim","Lacan","DSM-5-TR e ICD-11","Intervenção Precoce","Família e Escola","Brincar e Comunicação","Adolescência e Vida Adulta","Capacitismo e Direitos"]
  },
  {
    key:'ebook_psicologia_psicanalise_terapias', slug:'psicologia-psicanalise-terapias-integrativas', publicPath:'/ebooks/psicologia-psicanalise-terapias-integrativas', readerPath:'/cliente/biblioteca/ebook_psicologia_psicanalise_terapias', color:'#4C5B7A',
    title:'Psicologia, Psicanálise e Terapias Integrativas', subtitle:'Diálogos, Diferenças e Possibilidades', short:'Psicologia, Psicanálise e Terapias Integrativas',
    description:'Obra da Coleção Estudos Contemporâneos com 20 capítulos sobre psicologia, psicanálise e terapias integrativas, escrita para estudo aprofundado, aplicação responsável e reflexão crítica.',
    audience:'Leitores, estudantes e profissionais interessados em aprofundamento contemporâneo e aplicação responsável.', priceBrlCents:4990, priceEurCents:990,
    chapters:['O nascimento das abordagens','O que é Psicologia','Abordagens da Psicologia','O nascimento da Psicanálise','Freud e o inconsciente','A Psicanálise depois de Freud','Terapias Integrativas','Corpo, mente e subjetividade','Sintoma e sofrimento','Escuta e vínculo','Emoções e comportamento','História individual','Ansiedade e sofrimento','Complementaridade e limites','Promessas de cura','Ética','Limites de atuação','Trabalho interdisciplinar','Situações práticas','O futuro do cuidado humano']
  },
  { key:'ebook_jornalismo_era_digital', slug:'jornalismo-era-digital', publicPath:'/ebooks/jornalismo-era-digital', readerPath:'/cliente/biblioteca/ebook_jornalismo_era_digital', color:'#315D68', title:'Jornalismo na Era Digital', subtitle:'Informação, Sociedade e Novas Tecnologias', short:'Jornalismo na Era Digital', description:'Obra da Coleção Estudos Contemporâneos com 20 capítulos sobre jornalismo na era digital, escrita para estudo aprofundado, aplicação responsável e reflexão crítica.', audience:'Leitores, estudantes e profissionais interessados em aprofundamento contemporâneo e aplicação responsável.', priceBrlCents:1990, priceEurCents:490, chapters:['Por que o jornalismo existe','História do jornalismo','Notícia e interesse público','Pauta','Apuração','Fontes','Entrevista','Escrita jornalística','Reportagem','Investigativo','Jornalismo digital','Redes sociais','Dados','Fake news','Fact-checking','Ética','IA nas redações','Algoritmos','Modelos de negócio','O jornalista do futuro'] },
  { key:'ebook_corpo_trabalho_escuta', slug:'corpo-trabalho-escuta', publicPath:'/ebooks/corpo-trabalho-escuta', readerPath:'/cliente/biblioteca/ebook_corpo_trabalho_escuta', color:'#6A4E3B', title:'Corpo, Trabalho e Escuta', subtitle:'Massagem e Psicanálise no Bem-Estar do Trabalhador', short:'Corpo, Trabalho e Escuta', description:'Obra sobre corpo, trabalho, massagem de bem-estar e Psicanálise como práticas distintas, com limites profissionais explícitos e sem atendimento híbrido.', audience:'Leitores, estudantes e profissionais interessados em aprofundamento contemporâneo e aplicação responsável.', priceBrlCents:4990, priceEurCents:990, chapters:['O trabalhador e seu corpo','Trabalho e sociedade','Corpo e rotina','Tensão e sobrecarga','Estresse no trabalho','Práticas de massagem','Massagem de bem-estar','Massagem laboral','Ambiente de cuidado','Psicanálise e trabalho','Inconsciente e vida profissional','Identidade e reconhecimento','Sofrimento no trabalho','Corpo e subjetividade','Duas práticas distintas','Limites definidos','Conflito de interesse','Transferência e contato','Ética e encaminhamento','Políticas responsáveis'] },
  { key:'ebook_comportamento_humano', slug:'comportamento-humano', publicPath:'/ebooks/comportamento-humano', readerPath:'/cliente/biblioteca/ebook_comportamento_humano', color:'#5B4A73', title:'Como Mudar o Comportamento Humano', subtitle:'Hábitos, Ambiente e Processos de Mudança', short:'Como Mudar o Comportamento Humano', description:'Obra da Coleção Estudos Contemporâneos com 20 capítulos sobre comportamento humano, hábitos, ambiente e processos de mudança responsável.', audience:'Leitores, estudantes e profissionais interessados em aprofundamento contemporâneo e aplicação responsável.', priceBrlCents:1990, priceEurCents:490, chapters:['Comportamento','Natureza e ambiente','Hábitos','Recompensa','Motivação','Emoções','Pensamento e ação','Ambiente','Relações sociais','Identidade','Tomada de decisão','Autocontrole','Procrastinação','Resistência à mudança','Repetição de padrões','Novos hábitos','Mudanças no ambiente','Mudança sustentável','Por que mudanças fracassam','Projeto pessoal de mudança'] },
  { key:'ebook_estetica_bem_estar', slug:'estetica-bem-estar', publicPath:'/ebooks/estetica-bem-estar', readerPath:'/cliente/biblioteca/ebook_estetica_bem_estar', color:'#8A5965', title:'Estética Aplicada ao Bem-Estar', subtitle:'Práticas, Experiência e Cuidado', short:'Estética Aplicada ao Bem-Estar', description:'Obra da Coleção Estudos Contemporâneos sobre estética aplicada ao bem-estar, experiência do cliente, ética e responsabilidade profissional.', audience:'Leitores, estudantes e profissionais interessados em aprofundamento contemporâneo e aplicação responsável.', priceBrlCents:1990, priceEurCents:490, chapters:['História da estética','Estética contemporânea','Beleza e cultura','Imagem corporal','Autoimagem','Experiência de cuidado','Acolhimento','Ambiente','Comunicação profissional','Experiência sensorial','Rotinas de atendimento','Biossegurança','Limites profissionais','Expectativas','Promessas e resultados','Ética','Experiência premium','Fidelização responsável','Gestão de serviços','Futuro da estética'] },
  { key:'ebook_tricologia_cuidado', slug:'tricologia-cuidado', publicPath:'/ebooks/tricologia-cuidado', readerPath:'/cliente/biblioteca/ebook_tricologia_cuidado', color:'#48665A', title:'Tricologia Capilar Aplicada ao Cuidado', subtitle:'Prática, Acompanhamento e Resultados', short:'Tricologia Capilar Aplicada ao Cuidado', description:'Obra da Coleção Estudos Contemporâneos sobre tricologia capilar aplicada ao cuidado, acompanhamento e prática responsável.', audience:'Leitores, estudantes e profissionais interessados em aprofundamento contemporâneo e aplicação responsável.', priceBrlCents:1990, priceEurCents:490, chapters:['Introdução à tricologia','Anatomia do cabelo','Estrutura do fio','Couro cabeludo','Ciclo capilar','Avaliação inicial','Anamnese','Alterações do couro cabeludo','Alterações dos fios','Rotinas de cuidado','Cosméticos capilares','Procedimentos e limites','Registro fotográfico','Protocolos','Evolução','Interpretação de resultados','Expectativa versus resultado','Encaminhamento','Ética','Prática profissional'] },
  { key:'ebook_ia_novos_milionarios', slug:'ia-novos-milionarios', publicPath:'/ebooks/ia-novos-milionarios', readerPath:'/cliente/biblioteca/ebook_ia_novos_milionarios', color:'#273F66', title:'Como a Inteligência Artificial Pode Criar Novos Milionários', subtitle:'Oportunidades, Negócios e Profissões na Nova Economia da IA', short:'Como a Inteligência Artificial Pode Criar Novos Milionários', description:'Análise crítica das oportunidades econômicas abertas pela IA, sem promessa de enriquecimento ou resultado financeiro garantido.', audience:'Leitores, estudantes e profissionais interessados em aprofundamento contemporâneo e aplicação responsável.', priceBrlCents:4990, priceEurCents:990, chapters:['Nova revolução tecnológica','IA generativa','O que a IA faz','Automação do trabalho','Novas profissões','Profissões em transformação','Empreendedor aumentado por IA','Empresas menores','Produtos digitais','Serviços com IA','Agentes de IA','Automação empresarial','IA em vendas','IA em marketing','IA na educação','Modelos de monetização','Oportunidades','Riscos e bolhas','Negócio baseado em IA','Quem captura valor'] },
  { key:'ebook_imigracao_efeitos_psicologicos', slug:'imigracao-efeitos-psicologicos', publicPath:'/ebooks/imigracao-efeitos-psicologicos', readerPath:'/cliente/biblioteca/ebook_imigracao_efeitos_psicologicos', color:'#6A586B', title:'Entre Dois Mundos', subtitle:'Imigração e os Efeitos Psicológicos da Experiência Migratória', short:'Entre Dois Mundos', description:'Obra da Coleção Estudos Contemporâneos sobre imigração, pertencimento, saudade, adaptação e os efeitos psicológicos da experiência migratória.', audience:'Leitores, estudantes, imigrantes e profissionais interessados em aprofundamento contemporâneo e aplicação responsável.', priceBrlCents:4990, priceEurCents:990, chapters:['Por que partimos','A decisão de deixar o país','Antes da partida','A chegada','Choque cultural','Língua e identidade','Saudade','Solidão','Família à distância','Relacionamentos','Trabalho e sobrevivência','Qualificação e recomeço','Preconceito','Pertencimento','Duas culturas','Novas redes','Adaptação','Voltar também é difícil','Quando procurar apoio','Pertencimento sem apagar origens'] },
  { key:'ebook_psicanalise_vs_psiquiatria', slug:'psicanalise-vs-psiquiatria', publicPath:'/ebooks/psicanalise-vs-psiquiatria', readerPath:'/cliente/biblioteca/ebook_psicanalise_vs_psiquiatria', color:'#39485F', title:'Psicanálise vs. Psiquiatria', subtitle:'Do diagnóstico à escuta: como duas tradições compreendem o sofrimento psíquico e podem dialogar na clínica', short:'Psicanálise vs. Psiquiatria', description:'Uma análise crítica das diferenças, limites e possibilidades de diálogo entre Psicanálise e Psiquiatria, do diagnóstico e da psicofarmacologia à escuta e subjetividade.', audience:'Leitores, estudantes e profissionais interessados em Psicanálise, Psiquiatria, saúde mental e cuidado interdisciplinar.', priceBrlCents:1990, priceEurCents:490, chapters:['Duas histórias da saúde mental','O que é Psiquiatria?','O que é Psicanálise?','Freud médico','Sintoma','Diagnóstico psiquiátrico','Construção do caso','Inconsciente no consultório','Psiquiatras psicanalistas','Psiquiatria psicodinâmica','Medicamento e palavra','Limites do medicamento','Escuta psiquiátrica','Transferência','Ansiedade','Depressão','Quando exige Psiquiatria','Encaminhamento','Um paciente, dois profissionais','Século XXI'] },
  {
    key:'ebook_falar_com_quem_feriu', slug:'falar-com-quem-feriu', publicPath:'/ebooks/falar-com-quem-feriu', readerPath:'/cliente/biblioteca/ebook_falar_com_quem_feriu', color:'#B65A7A',
    title:'Falar com Quem Feriu', subtitle:'Quando a Palavra Encontra a Dor', short:'Falar com Quem Feriu',
    description:'Uma obra sensível sobre o impacto emocional de falar, depois de muitos anos, com alguém ligado a uma experiência de dor, abuso ou ruptura. Não romantiza a violência, não impõe reconciliação e trata a palavra como possibilidade de elaboração, não como obrigação.',
    audience:'Leitores que desejam refletir com cuidado sobre dor silenciada, lembrança, corpo, palavra, limites, reconstrução subjetiva e a diferença entre perdoar, esquecer e elaborar.',
    priceBrlCents:4990, priceEurCents:990,
    chapters:['Quando a dor fica sem palavra','O corpo diante da lembrança','A necessidade extrema de falar','Falar não é reconciliar','Perdoar, esquecer e elaborar','O silêncio como defesa','O trauma e a memória','A palavra como tentativa de elaboração','Quando o passado responde','O cuidado antes do contato','O cuidado depois do contato','O direito de não romantizar a dor','A repetição e seus sinais','A escuta de si','Limites e proteção emocional','O que a psicanálise ajuda a pensar','A dor que muda a cabeça da pessoa','Reconstrução subjetiva','Quando procurar apoio profissional','Depois da palavra, a vida']
  },
  {
    key:'ebook_da_pobreza_ao_primeiro_contrato', slug:'da-pobreza-ao-primeiro-contrato', publicPath:'/ebooks/da-pobreza-ao-primeiro-contrato', readerPath:'/cliente/biblioteca/ebook_da_pobreza_ao_primeiro_contrato', color:'#8A5A24',
    title:'Da Pobreza ao Primeiro Contrato', subtitle:'Escassez, Produto, Proposta e Coragem Prática', short:'Da Pobreza ao Primeiro Contrato',
    description:'Uma obra prática e emocional sobre sair da escassez, criar uma oferta real, divulgar com dignidade, enfrentar recusas, fazer reuniões e buscar o primeiro contrato sem prometer enriquecimento, fórmula pronta ou resultado garantido.',
    audience:'Pessoas que estão começando um projeto, serviço ou produto digital e precisam transformar urgência em movimento, com método, proposta, prospecção ética e resistência emocional diante do silêncio e da rejeição.',
    priceBrlCents:4990, priceEurCents:990,
    chapters:['O começo sem estrutura','Escassez sem romantização','Uma necessidade real vira produto','O que você já sabe fazer','Da ideia à oferta','Criar sem esperar perfeição','Como organizar a primeira proposta','Divulgar sem ser conhecido','Primeiros contatos com ética','O silêncio das respostas','Rejeição e ajuste de rota','A reunião que exige coragem','Como apresentar valor','O preço e a dignidade','Follow-up sem desespero','Quando a oferta precisa mudar','O primeiro sim','O contrato como marco','Depois do primeiro contrato','Continuar sem se perder']
  },
] as const;

export type PsychoanalysisEbookKey = typeof PSYCHOANALYSIS_EBOOKS[number]["key"];
export function psychoanalysisEbookByKey(key:string){return PSYCHOANALYSIS_EBOOKS.find((e)=>e.key===key)??null;}
