export const PSYCHOANALYSIS_EBOOKS = [
  {
    key:"ebook_pratica_clinica_psicanalise", slug:"pratica-clinica-psicanalise", publicPath:"/ebooks/pratica-clinica-psicanalise", readerPath:"/cliente/biblioteca/ebook_pratica_clinica_psicanalise", color:"#314E52",
    title:"A Prática Clínica da Psicanálise", subtitle:"Estrutura, Manejo e o Início da Clínica", short:"A Prática Clínica da Psicanálise",
    description:"Um guia teórico-clínico para estruturar a prática psicanalítica com atenção ao enquadre, manejo, ética, formação permanente e sustentabilidade da clínica.",
    audience:"Psicanalistas recém-formados, estudantes em final de formação e profissionais que desejam estruturar a prática clínica com solidez teórica e ética.",
    priceBrlCents:2000, priceEurCents:399,
    chapters:["A Análise Pessoal — O Analista em Análise","A Supervisão — O Terceiro na Cena Analítica","A Formação Teórica Continuada — A Caixa de Ferramentas em Constante Renovação","O Início do Percurso — O Período de Atendimentos Gratuitos ou de Baixo Custo","A Estruturação da Clínica — Enquadre, Setting e Honorários","O Manejo Clínico no Dia a Dia","Como Atingir Pacientes — Estratégias Éticas para o Analista Iniciante","A Entrevista Inicial e a Construção da Demanda","Formulação Psicanalítica e Hipóteses de Funcionamento","Transferência: Repetição, Atualização e Novidade","Contratransferência e Uso Clínico dos Afetos do Analista","O Silêncio e o Tempo da Intervenção","Interpretação, Construção e Timing","Construção do Caso Clínico e Escrita de Processo","Sigilo, Documentação e Proteção de Dados","Psicanálise Online: Presença, Corpo e Mediação Tecnológica","Consultório Físico, Ambiente e Hospitalidade Clínica","Gestão Financeira da Clínica e Sustentabilidade","Cuidado com o Analista, Limites de Agenda e Prevenção do Esgotamento","Identidade do Analista, Instituições e Escrita Pública"]
  },
  {
    key:"ebook_psicanalise_no_mundo", slug:"psicanalise-no-mundo", publicPath:"/ebooks/psicanalise-no-mundo", readerPath:"/cliente/biblioteca/ebook_psicanalise_no_mundo", color:"#1F4E79",
    title:"A Psicanálise no Mundo", subtitle:"Regulamentação, Panorama Global e Atuação Internacional", short:"A Psicanálise no Mundo",
    description:"Uma leitura comparativa sobre presença institucional, formação, regras profissionais, circulação internacional e desafios contemporâneos da psicanálise em diferentes países.",
    audience:"Psicanalistas com interesse em atuação internacional, pesquisadores e profissionais que desejam compreender diferenças legais, culturais e institucionais entre países.",
    priceBrlCents:2000, priceEurCents:399,
    chapters:["A Força da Psicanálise no Brasil","Bélgica — Entre a Falta de Regulação e a Busca por Reconhecimento","Portugal — A Regulação pela Via Associativa e da IPA","Espanha — A Ausência de Norma e a Luta contra o Intrusismo","O Déficit de Profissionais e a Crise da Formação na Europa","Como Atuar Internacionalmente — Caminhos e Credenciais","Argentina: Tradição Psicanalítica e Cultura Urbana","França: Herança Freudiana, Lacaniana e Instituições Plurais","Alemanha: Formação, Saúde e Tradição Institucional","Reino Unido: Psicanálise, Psicoterapia e Autorregulação","Itália: Tradições Clínicas e Fronteiras Profissionais","Estados Unidos: Licenças Estaduais e Formação Psicanalítica","Canadá: Províncias, Idiomas e Regulação Diferenciada","Austrália: Saúde Mental, Registros e Formação Psicanalítica","África Lusófona: Contexto, Formação e Cooperação","Ásia: Tradução Cultural e Diversidade de Ecossistemas","IPA, EPF e FEPAL: Organismos, Redes e Limites de Autoridade","Psicanálise Online Internacional, Dados e Emergências","Psicanálise, Universidade e Pesquisa","O Futuro Internacional da Psicanálise"]
  },
  {
    key:"ebook_estudos_caso_psicanalise", slug:"estudos-caso-psicanalise", publicPath:"/ebooks/estudos-caso-psicanalise", readerPath:"/cliente/biblioteca/ebook_estudos_caso_psicanalise", color:"#7C3A5D",
    title:"Estudos de Caso", subtitle:"A Psicanálise e os Impasses da Vida Contemporânea", short:"Estudos de Caso",
    description:"Vinte estudos e construções clínicas sobre vínculos, repetição, inibição, carreira, desejo e sofrimento contemporâneo, apresentados com finalidade didática e proteção integral de confidencialidade.",
    audience:"Estudantes de psicologia e psicanálise, psicanalistas em formação e profissionais que desejam aprofundar a leitura de impasses clínicos contemporâneos.",
    priceBrlCents:2000, priceEurCents:399,
    chapters:["O medo da intrusão e o desejo de contato — Um caso de paciente esquizoide","O amor e a separação insuportável — Dois casos à luz de Freud e Lacan","Da oposição à possibilidade de amar — A evolução de uma paciente","A inibição intelectual e o bloqueio no trabalho — Uma análise de caso","A escrita inibida — O manuscrito que não se completa","A não realização do desejo profissional e o conflito com o ideal","Vínculo e Autossabotagem Amorosa: Quando a Proximidade Aciona a Fuga","O Medo de Compromisso e a Fantasia de Perder a Liberdade","Repetições Amorosas Destrutivas e a Compulsão à Repetição","Bloqueio Criativo e o Medo de Produzir Algo Próprio","Projetos que Nunca Terminam: Perfeccionismo e Suspensão do Julgamento","Síndrome do Impostor: Reconhecimento sem Apropriação","Evitar Promoções: Sucesso, Visibilidade e Culpa","Conflitos com Autoridade: Entre Submissão, Desafio e Transferência","Não Conseguir Pedir Demissão: Dependência, Medo e Fantasia de Catástrofe","Não Conseguir Empreender: Desejo de Autonomia e Medo de Exposição","Procrastinação Crônica: Tempo, Angústia e Evitação","Conflito entre Desejo e Dever: Carreira como Mandato","Luto Profissional e Transição de Carreira","Aposentadoria, Trabalho e Busca de Sentido"]
  },
  {
    key:"ebook_psicanalise_autismo", slug:"psicanalise-autismo", publicPath:"/ebooks/psicanalise-autismo", readerPath:"/cliente/biblioteca/ebook_psicanalise_autismo", color:"#6B6F2A",
    title:"Psicanálise e Autismo", subtitle:"Escuta, Manejo Clínico e o Debate com a ABA", short:"Psicanálise e Autismo",
    description:"Uma obra crítica sobre história, escuta, manejo, neurodiversidade, trabalho multiprofissional e o debate entre perspectivas psicanalíticas e ABA, sem promessa de cura ou reducionismos.",
    audience:"Psicanalistas, psicólogos, estudantes, profissionais e familiares interessados em uma abordagem ética, crítica e respeitosa da singularidade de pessoas autistas.",
    priceBrlCents:2000, priceEurCents:399,
    chapters:["O Funcionamento Autístico e a Borda Autística","A Direção do Tratamento — Apostar no Sujeito e em suas Invenções","A Análise do Comportamento Aplicada (ABA) — Fundamentos e Controvérsias","A Perspectiva da Neurodiversidade e as Críticas ao Modelo Médico","Evidências, Interesses e o Observatório da Eurofederação de Psicanálise","O Enquadre na Clínica do Autismo — Flexibilidade e Invenção","A Transferência e a Contratransferência na Clínica com Sujeitos Autistas","A Direção do Olhar — O que a Clínica com Autistas Ensina à Psicanálise","História do Autismo: Kanner, Asperger e Mudanças de Conceito","Melanie Klein e os Primeiros Debates Psicanalíticos sobre Crianças Autistas","Winnicott, Ambiente e a Clínica da Presença","Frances Tustin, Objetos Autísticos e Sensorialidade","Bruno Bettelheim e a Necessidade de uma Leitura Histórica Crítica","Lacan, Linguagem e Leituras Contemporâneas do Autismo","DSM-5-TR, ICD-11 e Diagnóstico Contemporâneo","Diagnóstico e Intervenção Precoce: O Valor do Tempo sem Determinismo","Família, Escola e Trabalho Multiprofissional","Brincar, Ecolalia, Estereotipias e Comunicação","Adolescência, Vida Adulta, Sexualidade e Trabalho","Capacitismo, Direitos e o Futuro da Clínica do Autismo"]
  }
] as const;

export type PsychoanalysisEbookKey = typeof PSYCHOANALYSIS_EBOOKS[number]["key"];
export function psychoanalysisEbookByKey(key:string){return PSYCHOANALYSIS_EBOOKS.find((e)=>e.key===key)??null;}
