export const PSYCHOANALYSIS_EBOOKS = [
  {
    key:"ebook_pratica_clinica_psicanalise", slug:"pratica-clinica-psicanalise", publicPath:"/ebooks/pratica-clinica-psicanalise", readerPath:"/cliente/biblioteca/ebook_pratica_clinica_psicanalise", color:"#314E52",
    title:"A Prática Clínica da Psicanálise", subtitle:"Estrutura, Manejo e o Início da Clínica", short:"A Prática Clínica da Psicanálise",
    description:"Um guia teórico-clínico para estruturar a prática psicanalítica com atenção ao enquadre, manejo, ética, formação permanente e sustentabilidade da clínica.",
    audience:"Psicanalistas recém-formados, estudantes em final de formação e profissionais que desejam estruturar a prática clínica com solidez teórica e ética.",
    priceBrlCents:2000, priceEurCents:399,
    chapters:["A Análise Pessoal — O Analista em Análise","A Supervisão — O Terceiro na Cena Analítica","A Formação Teórica Continuada — A Caixa de Ferramentas em Constante Renovação","O Início do Percurso — O Período de Atendimentos Gratuitos ou de Baixo Custo","A Estruturação da Clínica — Enquadre, Setting e Honorários","O Manejo Clínico no Dia a Dia","Como Atingir Pacientes — Estratégias Éticas para o Analista Iniciante","A Entrevista Inicial e a Construção da Demanda","Formulação Psicanalítica e Hipóteses de Funcionamento","Transferência: Repetição, Atualização e Novidade","Contratransferência e Uso Clínico dos Afetos do Analista","O Silêncio e o Tempo da Intervenção","Interpretação, Construção e Timing","Construção do Caso Clínico e Escrita de Processo","Sigilo, Documentação e Proteção de Dados","Psicanálise Online: Presença, Corpo e Mediação Tecnológica","Consultório Físico, Ambiente e Hospitalidade Clínica","Gestão Financeira da Clínica e Sustentabilidade","Cuidado com o Analista, Limites de Agenda e Prevenção do Esgotamento","Identidade do Analista, Instituições e Escrita Pública"]
  },
  {
    key:"ebook_psicanalise_no_mundo", slug:"psicanalise-no-mundo", publicPath:"/ebooks/psicanalise-no-mundo", readerPath:"/cliente/biblioteca/ebook_psicanalise_no_mundo", color:"#1F4E79",
    title:"A Psicanálise no Mundo", subtitle:"Regulamentação, Panorama Global e Atuação Internacional", short:"A Psicanálise no Mundo",
    description:"Uma leitura comparativa sobre presença institucional, formação, regras profissionais, circulação internacional e desafios contemporâneos da psicanálise em diferentes países.",
    audience:"Psicanalistas com interesse em atuação internacional, pesquisadores e profissionais que desejam compreender diferenças legais, culturais e institucionais entre países.",
    priceBrlCents:2000, priceEurCents:399,
    chapters:["A Força da Psicanálise no Brasil","Bélgica — Entre a Falta de Regulação e a Busca por Reconhecimento","Portugal — A Regulação pela Via Associativa e da IPA","Espanha — A Ausência de Norma e a Luta contra o Intrusismo","O Déficit de Profissionais e a Crise da Formação na Europa","Como Atuar Internacionalmente — Caminhos e Credenciais","Argentina: Tradição Psicanalítica e Cultura Urbana","França: Herança Freudiana, Lacaniana e Instituições Plurais","Alemanha: Formação, Saúde e Tradição Institucional","Reino Unido: Psicanálise, Psicoterapia e Autorregulação","Itália: Tradições Clínicas e Fronteiras Profissionais","Estados Unidos: Licenças Estaduais e Formação Psicanalítica","Canadá: Províncias, Idiomas e Regulação Diferenciada","Austrália: Saúde Mental, Registros e Formação Psicanalítica","África Lusófona: Contexto, Formação e Cooperação","Ásia: Tradução Cultural e Diversidade de Ecossistemas","IPA, EPF e FEPAL: Organismos, Redes e Limites de Autoridade","Psicanálise Online Internacional, Dados e Emergências","Psicanálise, Universidade e Pesquisa","O Futuro Internacional da Psicanálise"]
  },
  {
    key:"ebook_estudos_caso_psicanalise", slug:"estudos-caso-psicanalise", publicPath:"/ebooks/estudos-caso-psicanalise", readerPath:"/cliente/biblioteca/ebook_estudos_caso_psicanalise", color:"#7C3A5D",
    title:"Estudos de Caso", subtitle:"Da escuta à formulação: pensar o caso para além do sintoma", short:"Estudos de Caso",
    description:"eBook Premium de estudo avançado da construção de casos em Psicanálise: fundamentos clínicos, casos clássicos de Freud, formulação contemporânea, diferentes escolas, manejo, supervisão, ética e metodologia do estudo de caso.",
    audience:"Psicanalistas, profissionais em formação e leitores com base teórica que desejam aprofundar construção de caso, formulação, transferência, contratransferência, manejo e leitura crítica da literatura psicanalítica.",
    premium:true, regularPriceBrlCents:9990, regularPriceEurCents:1990, priceBrlCents:7990, priceEurCents:1490,
    chapters:["O que significa pensar um caso psicanaliticamente","Do relato clínico à construção do caso","O método psicanalítico","Escuta, associação livre e atenção flutuante","Sintoma, conflito e formação de compromisso","Repetição e compulsão à repetição","Transferência","Contratransferência","Resistência e mecanismos de defesa","Interpretação e construção","Enquadre, manejo e posição do analista","Supervisão e os limites da formulação clínica","Dora — desejo, sintoma, transferência e interrupção","Pequeno Hans — fobia, angústia e construção","Homem dos Ratos — obsessão, ambivalência e culpa","Schreber — paranoia, linguagem e reconstrução","Homem dos Lobos — infância, construção e limites da reconstrução analítica","Apresentação e construção do Caso A.","Angústia, perda, dependência e demanda de garantia","Transferência, repetição e impasses","Um mesmo caso, diferentes leituras: Freud, Klein, Winnicott, Bion e Lacan","Da formulação ao manejo","O estatuto epistemológico do estudo de caso e a pesquisa em Psicanálise","Ética da escrita clínica, confidencialidade e publicação"]
  },
  {
    key:"ebook_psicanalise_autismo", slug:"psicanalise-autismo", publicPath:"/ebooks/psicanalise-autismo", readerPath:"/cliente/biblioteca/ebook_psicanalise_autismo", color:"#6B6F2A",
    title:"Psicanálise e Autismo", subtitle:"Escuta, Manejo Clínico e o Debate com a ABA", short:"Psicanálise e Autismo",
    description:"Uma obra crítica sobre história, escuta, manejo, neurodiversidade, trabalho multiprofissional e o debate entre perspectivas psicanalíticas e ABA, sem promessa de cura ou reducionismos.",
    audience:"Psicanalistas, psicólogos, estudantes, profissionais e familiares interessados em uma abordagem ética, crítica e respeitosa da singularidade de pessoas autistas.",
    priceBrlCents:2000, priceEurCents:399,
    chapters:["O Funcionamento Autístico e a Borda Autística","A Direção do Tratamento — Apostar no Sujeito e em suas Invenções","A Análise do Comportamento Aplicada (ABA) — Fundamentos e Controvérsias","A Perspectiva da Neurodiversidade e as Críticas ao Modelo Médico","Evidências, Interesses e o Observatório da Eurofederação de Psicanálise","O Enquadre na Clínica do Autismo — Flexibilidade e Invenção","A Transferência e a Contratransferência na Clínica com Sujeitos Autistas","A Direção do Olhar — O que a Clínica com Autistas Ensina à Psicanálise","História do Autismo: Kanner, Asperger e Mudanças de Conceito","Melanie Klein e os Primeiros Debates Psicanalíticos sobre Crianças Autistas","Winnicott, Ambiente e a Clínica da Presença","Frances Tustin, Objetos Autísticos e Sensorialidade","Bruno Bettelheim e a Necessidade de uma Leitura Histórica Crítica","Lacan, Linguagem e Leituras Contemporâneas do Autismo","DSM-5-TR, ICD-11 e Diagnóstico Contemporâneo","Diagnóstico e Intervenção Precoce: O Valor do Tempo sem Determinismo","Família, Escola e Trabalho Multiprofissional","Brincar, Ecolalia, Estereotipias e Comunicação","Adolescência, Vida Adulta, Sexualidade e Trabalho","Capacitismo, Direitos e o Futuro da Clínica do Autismo"]
  }
] as const;

export type PsychoanalysisEbookKey = typeof PSYCHOANALYSIS_EBOOKS[number]["key"];
export function psychoanalysisEbookByKey(key:string){return PSYCHOANALYSIS_EBOOKS.find((e)=>e.key===key)??null;}
