import { getRequest } from "@tanstack/react-start/server";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { resolveClient } from "@/lib/client-portal.server";
import { hasOwnerDigitalAccess } from "@/lib/owner-digital-access.server";
import { PSYCHOANALYST_PROGRAMS,PSYCHOANALYST_TRILOGY,type PsychoanalystProgramKey } from "@/content/psychoanalyst-performance.catalog";
const db=supabaseAdmin as any;
type Market="BR"|"INTL";export type PerformanceProductKey=PsychoanalystProgramKey|"trilogia";
const bundleKey="psicanalista_alta_performance_trilogia",bundleSlug="psicanalista-alta-performance-trilogia";
function fail(m:string):never{throw new Error(m)}
function origin(){const r=getRequest();return process.env.CLIENT_PANEL_URL?.replace(/\/$/,"")||(r?new URL(r.url).origin:"https://ldracademy.online");}
async function customer(userId:string,email:string|null){const x=await resolveClient(userId,email);if(x.status!=="ok")fail("Acesso do cliente não disponível.");return x.customer;}
function program(key:string){const p=PSYCHOANALYST_PROGRAMS.find(x=>x.key===key);if(!p)fail("Curso não encontrado.");return p;}
function pk(key:PsychoanalystProgramKey){return `psicanalista_alta_performance_${key.replaceAll("-","_")}`;}
function slug(key:PsychoanalystProgramKey){return `psicanalista-alta-performance-${key}`;}
function projectTitle(key:PsychoanalystProgramKey){return key==="marketing-psicanalistas"?"Plano de Aquisição Ética de Pacientes — 90 Dias":key==="agenda-clinica"?"Plano de Organização e Sustentabilidade da Agenda Clínica — 12 Meses":"Plano Estratégico da Prática Profissional — 12 Meses";}
async function orders(cid:string){const {data}=await db.from("orders").select("catalog_key,metadata,payment_status").eq("customer_id",cid).eq("payment_status","pago");return data??[];}
function matches(o:any,key:string){return o.catalog_key===key||(o.metadata??{}).product_key===key;}
async function training(s:string,title:string){let {data}=await db.from("training_programs").select("id,slug,status,title").eq("slug",s).maybeSingle();if(!data){const r=await db.from("training_programs").insert({slug:s,title,description:"Curso pago · projeto final obrigatório.",status:"published"}).select("id,slug,status,title").single();data=r.data;}else if(data.status!=="published")await db.from("training_programs").update({status:"published",title}).eq("id",data.id);if(!data)fail("Não foi possível preparar o curso.");return data;}
async function enroll(cid:string,tid:string,key:string,entitled:boolean){if(!entitled)return null;let {data}=await db.from("training_enrollments").select("id,progress_percent,enrolled_at").eq("training_id",tid).eq("customer_id",cid).eq("active",true).maybeSingle();if(!data){const r=await db.from("training_enrollments").insert({training_id:tid,customer_id:cid,active:true,product_key:key}).select("id,progress_percent,enrolled_at").single();data=r.data;}return data;}
async function progress(cid:string,key:string){const {data}=await db.from("library_progress").select("progress_percent,current_location").eq("customer_id",cid).eq("product_key",key).maybeSingle();return data??null;}
async function latestProject(cid:string,tid:string){const {data}=await db.from("training_project_submissions").select("id,title,project_text,project_url,status,submitted_at,reviewed_at,feedback").eq("training_id",tid).eq("customer_id",cid).order("submission_number",{ascending:true});return(data??[]).at(-1)??null;}
async function ctx(userId:string,email:string|null){const c=await customer(userId,email),owner=hasOwnerDigitalAccess(email??c.email,userId),os=owner?[]:await orders(c.id),bundle=owner||os.some((o:any)=>matches(o,bundleKey));return{c,owner,os,bundle};}
export async function getPsychoanalystPerformanceOverview(userId:string,email:string|null){const x=await ctx(userId,email),courses=[] as any[];for(const p of PSYCHOANALYST_PROGRAMS){const key=pk(p.key),entitled=x.owner||x.bundle||x.os.some((o:any)=>matches(o,key)),t=await training(slug(p.key),p.title),e=await enroll(x.c.id,t.id,key,entitled),pr=entitled?await progress(x.c.id,key):null,project=entitled?await latestProject(x.c.id,t.id):null,pct=Math.max(Number(pr?.progress_percent??0),Number(e?.progress_percent??0));courses.push({...p,productKey:key,trainingSlug:t.slug,entitled,progressPercent:pct,project,projectTitle:projectTitle(p.key),projectRequired:true,certificateEligible:entitled&&pct>=100&&project?.status==="approved",learnerPath:`/cliente/psicanalista-alta-performance/${p.key}`});}const bt=await training(bundleSlug,PSYCHOANALYST_TRILOGY.title),be=await enroll(x.c.id,bt.id,bundleKey,x.bundle),bp=x.bundle?await latestProject(x.c.id,bt.id):null,all=courses.every(c=>c.progressPercent>=100&&c.project?.status==="approved");return{owner:x.owner,customer:{id:x.c.id,email:x.c.email},courses,trilogy:{...PSYCHOANALYST_TRILOGY,productKey:bundleKey,trainingSlug:bundleSlug,entitled:x.bundle,enrollment:be,project:bp,projectRequired:true,projectTitle:"Plano Estratégico Completo da Prática Psicanalítica",allCoursesComplete:all,certificateEligible:x.bundle&&all&&bp?.status==="approved"}};}
export async function getPsychoanalystPerformanceCourse(userId:string,email:string|null,key:PsychoanalystProgramKey){const o=await getPsychoanalystPerformanceOverview(userId,email),c=o.courses.find(x=>x.key===key);if(!c)fail("Curso não encontrado.");return c;}
export async function setPsychoanalystPerformanceProgress(userId:string,email:string|null,key:PsychoanalystProgramKey,progressPercent:number,currentLocation?:string|null){const o=await getPsychoanalystPerformanceCourse(userId,email,key);if(!o.entitled)fail("Acesso não liberado.");const c=await customer(userId,email),pct=Math.max(0,Math.min(100,Math.round(progressPercent))),payload={customer_id:c.id,product_key:o.productKey,progress_percent:pct,current_location:currentLocation??null,updated_at:new Date().toISOString()};const {error}=await db.from("library_progress").upsert(payload,{onConflict:"customer_id,product_key"});if(error)fail("Não foi possível salvar o progresso.");await db.from("training_enrollments").update({progress_percent:pct,completed_at:pct>=100?new Date().toISOString():null}).eq("customer_id",c.id).eq("product_key",o.productKey).eq("active",true);return{progressPercent:pct};}
async function saveProject(cid:string,tid:string,title:string,text:string|null,url:string|null){const p=await latestProject(cid,tid);if(p?.status==="submitted"||p?.status==="in_review")fail("Projeto em avaliação.");if(p?.status==="approved")fail("Projeto já aprovado.");if(p?.id){const {data,error}=await db.from("training_project_submissions").update({title,project_text:text,project_url:url,status:"submitted",submitted_at:new Date().toISOString(),reviewed_at:null,reviewed_by:null,feedback:null}).eq("id",p.id).select("id,status").single();if(error)fail("Não foi possível reenviar o projeto.");return data;}const {data,error}=await db.from("training_project_submissions").insert({training_id:tid,customer_id:cid,submission_number:1,title,project_text:text,project_url:url,status:"submitted",submitted_at:new Date().toISOString()}).select("id,status").single();if(error)fail("Não foi possível enviar o projeto.");return data;}
export async function submitPsychoanalystPerformanceProject(userId:string,email:string|null,input:{key:PsychoanalystProgramKey;title:string;projectText?:string|null;projectUrl?:string|null}){const o=await getPsychoanalystPerformanceCourse(userId,email,input.key);if(!o.entitled)fail("Acesso não liberado.");const x=await ctx(userId,email);if(!x.owner&&o.progressPercent<100)fail("Conclua 100% do curso antes de enviar o projeto.");const text=input.projectText?.trim()||null,url=input.projectUrl?.trim()||null;if(!text&&!url)fail("Descreva o projeto ou envie um link.");const t=await training(o.trainingSlug,o.title);return saveProject(x.c.id,t.id,input.title.trim()||o.projectTitle,text,url);}
export async function submitPsychoanalystTrilogyProject(userId:string,email:string|null,input:{title:string;projectText?:string|null;projectUrl?:string|null}){const o=await getPsychoanalystPerformanceOverview(userId,email);if(!o.trilogy.entitled)fail("Trilogia não liberada.");if(!o.owner&&!o.trilogy.allCoursesComplete)fail("Conclua os três cursos e tenha os projetos aprovados.");const text=input.projectText?.trim()||null,url=input.projectUrl?.trim()||null;if(!text&&!url)fail("Descreva o projeto ou envie um link.");const t=await training(bundleSlug,o.trilogy.title);return saveProject(o.customer.id,t.id,input.title.trim()||o.trilogy.projectTitle,text,url);}
export async function createPsychoanalystPerformanceCheckout(userId:string,email:string|null,key:PerformanceProductKey,market:Market){const x=await ctx(userId,email),isBundle=key==="trilogia",p=isBundle?null:program(key),catalog=isBundle?bundleKey:pk(key as PsychoanalystProgramKey),already=x.owner||(isBundle?x.bundle:x.bundle||x.os.some((o:any)=>matches(o,catalog)));if(already)fail("Conteúdo já disponível.");const title=isBundle?PSYCHOANALYST_TRILOGY.title:p!.title,amount=100*(market==="BR"?(isBundle?PSYCHOANALYST_TRILOGY.priceBRL:p!.priceBRL):(isBundle?PSYCHOANALYST_TRILOGY.priceEUR:p!.priceEUR)),currency=market==="BR"?"BRL":"EUR",trainingSlug=isBundle?bundleSlug:slug(key as PsychoanalystProgramKey),metadata={product_key:catalog,training_slug:trainingSlug,market,auth_user_id:userId,access_kind:"one_time_only"};const {data:order,error}=await db.from("orders").insert({order_number:"",customer_id:x.c.id,contact_email:x.c.email,contact_phone:x.c.phone,service_type:"produto_digital",title,description:"Pagamento único · acesso vitalício aos conteúdos digitais · projeto final obrigatório",quantity:1,amount_cents:amount,currency,payment_status:"pendente",status:"novo",priority:"media",catalog_key:catalog,metadata}).select("id").single();if(error||!order)fail("Não foi possível iniciar o pedido.");const secret=process.env.STRIPE_SECRET_KEY;if(!secret)fail("Pagamento indisponível.");const q=new URLSearchParams();q.set("mode","payment");q.set("line_items[0][price_data][currency]",currency.toLowerCase());q.set("line_items[0][price_data][unit_amount]",String(amount));q.set("line_items[0][price_data][product_data][name]",title);q.set("line_items[0][quantity]","1");q.set("success_url",`${origin()}/cliente/psicanalista-alta-performance?payment=success`);q.set("cancel_url",`${origin()}/cliente/psicanalista-alta-performance?payment=cancel`);q.set("client_reference_id",userId);q.set("metadata[order_id]",order.id);q.set("metadata[product_key]",catalog);q.set("metadata[training_slug]",trainingSlug);if(x.c.email)q.set("customer_email",x.c.email);const r=await fetch("https://api.stripe.com/v1/checkout/sessions",{method:"POST",headers:{Authorization:`Bearer ${secret}`,"Content-Type":"application/x-www-form-urlencoded"},body:q});const session=await r.json() as any;if(!r.ok||!session?.url){await db.from("orders").delete().eq("id",order.id);fail("Não foi possível abrir o checkout.");}await db.from("orders").update({stripe_checkout_session_id:session.id}).eq("id",order.id);return{url:session.url};}
