import { getRequest } from "@tanstack/react-start/server";
import { paidCourseProjectApproved } from "@/lib/paid-course-project-policy.server";
import { supabaseAdmin } from "@/integrations/supabase/client.server";
import { resolveClient } from "@/lib/client-portal.server";
import { hasOwnerDigitalAccess } from "@/lib/owner-digital-access.server";

const PRODUCT_KEY="formacao_psicanalise";const PRODUCT_SLUG="formacao-psicanalise";const TITLE="Formação em Psicanálise · Autismo + Atuação Internacional";const PRICE_BRL=29_999;const PRICE_EUR=4_990;const TOTAL_LESSONS=240;const TOTAL_HOURS=1200;const MAXIMUM_MONTHS=12;const COHORT_CAPACITY=50;type Market="BR"|"INTL";const db=supabaseAdmin as any;function fail(message:string):never{throw new Error(message)}
async function customerFor(userId:string,email:string|null){const ctx=await resolveClient(userId,email);if(ctx.status!=="ok")fail("Acesso do cliente não disponível.");return ctx.customer;}function matches(order:any){const metadata=(order?.metadata??{}) as Record<string,unknown>;const key=typeof metadata.product_key==="string"?metadata.product_key:"";return order?.catalog_key===PRODUCT_KEY||key===PRODUCT_KEY||key===PRODUCT_SLUG;}async function paidOrder(customerId:string){const {data,error}=await db.from("orders").select("id,catalog_key,payment_status,amount_cents,currency,stripe_checkout_session_id,metadata,created_at").eq("customer_id",customerId).eq("payment_status","pago").order("created_at",{ascending:false});if(error)fail("Não foi possível verificar a compra da formação.");return(data??[]).find(matches)??null;}function appOrigin(){const request=getRequest();const requestUrl=request?new URL(request.url):null;return process.env.CLIENT_PANEL_URL?.replace(/\/$/,"")||requestUrl?.origin||"https://ldracademy.online";}
async function ensureProgram(){const description="Formação livre em Psicanálise com 15 módulos, 240 unidades de aprendizagem, carga horária formativa total de 1.200 horas, 100% online e sob demanda, projetos e avaliações, com autismo, neurodiversidade e atuação internacional.";const {data:existing}=await db.from("training_programs").select("id,slug,title,status").eq("slug",PRODUCT_SLUG).maybeSingle();if(existing){if(existing.status!=="published"){const {data:published}=await db.from("training_programs").update({status:"published",description}).eq("id",existing.id).select("id,slug,title,status").single();return published??{...existing,status:"published"};}return existing;}const {data,error}=await db.from("training_programs").insert({slug:PRODUCT_SLUG,title:TITLE,description,status:"published"}).select("id,slug,title,status").single();if(error||!data)throw error??new Error("Falha ao preparar a formação.");return data;}
async function assignCohortBestEffort(trainingId:string,enrollmentId:string){try{const {data:cohorts}=await db.from("training_cohorts").select("id,cohort_number,capacity,status").eq("training_id",trainingId).order("cohort_number",{ascending:true});let chosen:any=null;for(const cohort of cohorts??[]){if(cohort.status!=="open")continue;const {data:members}=await db.from("training_enrollments").select("id").eq("cohort_id",cohort.id).eq("active",true);if((members??[]).length<Number(cohort.capacity??COHORT_CAPACITY)){chosen=cohort;break;}}if(!chosen){const next=Math.max(0,...((cohorts??[]).map((x:any)=>Number(x.cohort_number??0))))+1;const {data:newCohort}=await db.from("training_cohorts").insert({training_id:trainingId,cohort_number:next,capacity:COHORT_CAPACITY,status:"open",starts_at:new Date().toISOString()}).select("id,cohort_number,capacity,status").single();chosen=newCohort??null;}if(chosen?.id)await db.from("training_enrollments").update({cohort_id:chosen.id}).eq("id",enrollmentId);}catch(error){console.warn("psychoanalysis cohort assignment skipped",error);}}
async function ensureEnrollment(customerId:string,entitled:boolean){if(!entitled)return null;try{const training=await ensureProgram();let {data:enrollment}=await db.from("training_enrollments").select("id,enrolled_at,cohort_id,progress_percent,completed_at,certificate_available_at,training_cohorts(cohort_number,capacity,status)").eq("training_id",training.id).eq("customer_id",customerId).eq("active",true).maybeSingle();if(!enrollment){const created=await db.from("training_enrollments").insert({training_id:training.id,customer_id:customerId,active:true}).select("id,enrolled_at,cohort_id,progress_percent,completed_at,certificate_available_at").single();if(created.error||!created.data)throw created.error??new Error("Falha ao criar matrícula.");enrollment=created.data;await assignCohortBestEffort(training.id,enrollment.id);const refreshed=await db.from("training_enrollments").select("id,enrolled_at,cohort_id,progress_percent,completed_at,certificate_available_at,training_cohorts(cohort_number,capacity,status)").eq("id",enrollment.id).maybeSingle();enrollment=refreshed.data??enrollment;}return enrollment;}catch(error){console.warn("psychoanalysis enrollment provisioning skipped",error);return null;}}
async function savedProgress(customerId:string){const {data}=await db.from("library_progress").select("progress_percent,current_location,updated_at").eq("customer_id",customerId).eq("product_key",PRODUCT_KEY).maybeSingle();return data??null;}
export async function getPsychoanalysisOffer(userId:string,email:string|null){const customer=await customerFor(userId,email);const owner=hasOwnerDigitalAccess(email??customer.email,userId);const order=owner?null:await paidOrder(customer.id);const entitled=Boolean(order)||owner;const enrollment=await ensureEnrollment(customer.id,entitled);const progress=await savedProgress(customer.id);const enrolledAt=(enrollment?.enrolled_at??order?.created_at??null) as string|null;const maxUnlockedLesson=entitled?TOTAL_LESSONS:0;const progressPercent=Number(progress?.progress_percent??enrollment?.progress_percent??0);const projectApproved=await paidCourseProjectApproved(customer.id,"formacao-psicanalise");const certificateEligible=entitled&&progressPercent>=100&&projectApproved;return{productKey:PRODUCT_KEY,slug:PRODUCT_SLUG,title:TITLE,priceBrlCents:PRICE_BRL,priceEurCents:PRICE_EUR,regularPriceBrlCents:PRICE_BRL,regularPriceEurCents:PRICE_EUR,launchPromotionActive:false,launchMonths:0,launchStart:null,launchEnd:null,entitled,lifetimeAccess:true,minimumMonths:0,maximumMonths:MAXIMUM_MONTHS,minimumDays:0,liveSessionsIncluded:6,totalModules:15,totalLessons:TOTAL_LESSONS,totalHours:TOTAL_HOURS,enrolledAt,elapsedDays:0,maxUnlockedLesson,progressPercent,cohortNumber:enrollment?.training_cohorts?.cohort_number??null,cohortCapacity:enrollment?.training_cohorts?.capacity??COHORT_CAPACITY,certificateEligible,certificateAvailableAt:certificateEligible?new Date().toISOString():enrollment?.certificate_available_at??null,customerName:customer.fullName??customer.full_name??customer.email??"Aluno"};}
export async function createPsychoanalysisCheckout(userId:string,email:string|null,market:Market){fail("Novas compras individuais desta formação foram encerradas. O acesso está incluído no LDR ONE.");const customer=await customerFor(userId,email);const offer=await getPsychoanalysisOffer(userId,email);if(offer.entitled)fail("Esta formação já está disponível para sua conta.");return{url:""};}
