import { createServerFn } from "@tanstack/react-start";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
function emailOf(claims:Record<string,unknown>):string|null{const value=claims["email"];return typeof value==="string"?value:null;}

export const clientWrittenOrientationOffer=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const m=await import("@/lib/written-orientation.server");return m.getWrittenOrientationOffer(context.userId,emailOf(context.claims));});
export const clientCreateWrittenOrientationCheckout=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((data:{market:"BR"|"INTL";packageMinutes:10|30|60})=>data).handler(async({context,data})=>{const m=await import("@/lib/written-orientation.server");return m.createWrittenOrientationCheckout(context.userId,emailOf(context.claims),data.market,data.packageMinutes);});
export const clientActivateWrittenOrientationCheckout=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((data:{checkoutSessionId:string})=>data).handler(async({context,data})=>{const m=await import("@/lib/written-orientation.server");return m.activateWrittenOrientationCheckout(context.userId,emailOf(context.claims),data.checkoutSessionId);});
export const clientWrittenOrientationSession=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).inputValidator((data:{sessionId:string})=>data).handler(async({context,data})=>{const m=await import("@/lib/written-orientation.server");return m.getWrittenOrientationSession(context.userId,emailOf(context.claims),data.sessionId);});
export const clientSendWrittenOrientationMessage=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((data:{sessionId:string;message:string;consent:boolean})=>data).handler(async({context,data})=>{const m=await import("@/lib/written-orientation.server");return m.sendWrittenOrientationClientMessage(context.userId,emailOf(context.claims),data.sessionId,data.message,data.consent);});
export const adminWrittenOrientationList=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).handler(async({context})=>{const m=await import("@/lib/written-orientation.server");return m.getWrittenOrientationAdmin(context.supabase,context.userId);});
export const adminWrittenOrientationSession=createServerFn({method:"GET"}).middleware([requireSupabaseAuth]).inputValidator((data:{sessionId:string})=>data).handler(async({context,data})=>{const m=await import("@/lib/written-orientation.server");return m.getWrittenOrientationAdminSession(context.supabase,context.userId,data.sessionId);});
export const adminSendWrittenOrientationMessage=createServerFn({method:"POST"}).middleware([requireSupabaseAuth]).inputValidator((data:{sessionId:string;message:string})=>data).handler(async({context,data})=>{const m=await import("@/lib/written-orientation.server");return m.sendWrittenOrientationProfessionalMessage(context.supabase,context.userId,data.sessionId,data.message);});
