(function () {
  "use strict";

  const SUPPORTED = ["pt", "fr", "en", "es"];
  const STORAGE_KEY = "luciano.public.locale.v2";
  const LABELS = { pt: "PT", fr: "FR", en: "EN", es: "ES" };
  const HTML_LANG = { pt: "pt-BR", fr: "fr", en: "en", es: "es" };

  const en = {
    "Sobre": "About", "Temas": "Topics", "Lançamentos": "Releases", "Plataforma": "Platform", "Inscrever-se": "Register",
    "Palestra gratuita": "Free lecture", "Empreendedorismo": "Entrepreneurship", "e Saúde Mental": "and Mental Health", "sem Fronteiras": "without Borders",
    "da Ideia à Oportunidade com Equilíbrio": "from Idea to Opportunity with Balance",
    "Uma jornada real de coragem, recomeços e visão global — que une o empreendedorismo além das barreiras geográficas com o cuidado essencial com a mente. Inspirada no ebook": "A real journey of courage, new beginnings and global vision — combining entrepreneurship beyond geographical barriers with essential mental well-being. Inspired by the e-book",
    ", esta palestra é apresentada por Luciano Rodrigues Almeida e contará com": ", this lecture is presented by Luciano Rodrigues Almeida and will feature",
    "para mostrar que o sucesso sustentável nasce do equilíbrio entre negócios e bem-estar.": "to show that sustainable success grows from balance between business and well-being.",
    "convidados especiais": "special guests", "🌍 Sem Fronteiras": "🌍 Without Borders", "🧠 Saúde Mental": "🧠 Mental Health", "🎓 3h + Certificado": "🎓 3h + Certificate",
    "Apresentado por": "Presented by", "Psicanalista | Mentor | Gestor de Projetos | CEO do Grupo LdR Essence": "Psychoanalyst | Mentor | Project Manager | CEO of Grupo LdR Essence",
    "Começou vendendo mamão nas feiras da Bahia e construiu uma trajetória que atravessou São Paulo, Londres, Portugal e Bélgica. Hoje lidera o Grupo LdR Essence, que integra Luciano (palestras e mentoria), Essence Bem-estar, LdR RH Estratégia e uma linha de produtos em lançamento. Como psicanalista, une a visão empreendedora ao cuidado com a mente, mostrando que o sucesso sustentável nasce do equilíbrio.": "He began selling papayas at markets in Bahia and built a journey through São Paulo, London, Portugal and Belgium. Today he leads Grupo LdR Essence, which brings together Luciano (lectures and mentoring), Essence Well-being, LdR RH Estratégia and a growing product line. As a psychoanalyst, he connects entrepreneurial vision with mental well-being, showing that sustainable success comes from balance.",
    "🌍 Empreendedor sem Fronteiras": "🌍 Entrepreneur without Borders", "📚 Autor": "📚 Author", "Quero participar": "I want to join", "Ver temas": "View topics",
    "Psicanalista · Mentor · Gestor de Projetos": "Psychoanalyst · Mentor · Project Manager", "O segredo não está no dinheiro — está no movimento.": "The secret is not in the money — it is in taking action.",
    "INSPIRADO NO EBOOK · O MENINO QUE VENDIA MAMÃO": "INSPIRED BY THE E-BOOK · THE BOY WHO SOLD PAPAYAS",
    "A história por trás da palestra": "The story behind the lecture", "Das feiras da Bahia": "From the markets of Bahia", "ao mundo sem fronteiras": "to a world without borders",
    "Conheça a trajetória de Luciano — do menino que vendia mamão ao empreendedor que hoje conecta negócios entre Portugal, Bélgica, Brasil e o mundo, com a saúde mental como pilar fundamental para uma jornada sustentável.": "Discover Luciano's journey — from the boy who sold papayas to the entrepreneur who now connects businesses across Portugal, Belgium, Brazil and the world, with mental health as a fundamental pillar of a sustainable journey.",
    "Origens": "Origins", "Menino que vendia mamão na feira aprendeu cedo que empreender é sobre oferecer valor, persistir e construir relações — sem barreiras.": "The boy who sold papayas at the market learned early that entrepreneurship is about offering value, persisting and building relationships — without barriers.",
    "Jornada sem Fronteiras": "Journey without Borders", "Passou por São Paulo, Londres, Portugal e Bélgica — cada mudança foi um recomeço que expandiu sua visão de mundo e seus negócios.": "He lived through São Paulo, London, Portugal and Belgium — each move was a new beginning that broadened his view of the world and business.",
    "O ebook": "The e-book", "reúne episódios reais, mostrando que o movimento e o autocuidado são os verdadeiros segredos para empreender sem fronteiras.": "brings together real episodes, showing that action and self-care are the true secrets to entrepreneurship without borders.",
    "Uma história real": "A real story", "Experiência que virou conhecimento para compartilhar.": "Experience transformed into knowledge to share.",
    "Da Bahia à Europa, cada mudança trouxe desafios, escolhas e aprendizados. A palestra transforma essa trajetória em uma conversa prática sobre coragem, visão global, empreendedorismo e saúde mental.": "From Bahia to Europe, every move brought challenges, choices and lessons. The lecture turns this journey into a practical conversation about courage, global vision, entrepreneurship and mental health.",
    "Durante a palestra, Luciano receberá especialistas em": "During the lecture, Luciano will welcome experts in", "para enriquecer ainda mais a conversa sobre equilíbrio, resiliência e bem-estar no empreendedorismo internacional.": "to enrich the conversation about balance, resilience and well-being in international entrepreneurship.",
    "🧡 Convidados especiais!": "🧡 Special guests!", "Saúde Mental": "Mental Health", "🚀 Empreendedorismo": "🚀 Entrepreneurship", "🌍 Visão Global": "🌍 Global Vision",
    "O que você vai aprender": "What you will learn", "Temas da": "Lecture", "palestra": "topics", "Conteúdo prático e inspirador que une empreendedorismo internacional, saúde mental e visão global.": "Practical and inspiring content combining international entrepreneurship, mental health and global vision.",
    "🌍 Empreendedorismo sem Fronteiras": "🌍 Entrepreneurship without Borders", "Como identificar oportunidades além do mercado local, adaptar-se a diferentes culturas e construir negócios com alcance internacional.": "How to identify opportunities beyond the local market, adapt to different cultures and build internationally oriented businesses.",
    "🧠 Saúde Mental do Empreendedor Global": "🧠 Mental Health for Global Entrepreneurs", "Burnout, ansiedade, resiliência e equilíbrio entre vida pessoal e profissional em contextos multiculturais.": "Burnout, anxiety, resilience and work-life balance in multicultural contexts.",
    "💡 Transformar conhecimento em oportunidade": "💡 Turn knowledge into opportunity", "Como usar suas experiências e habilidades para criar negócios reais, sem abrir mão do bem-estar.": "How to use your experience and skills to create real businesses without sacrificing well-being.",
    "🎯 Empreendedorismo para jovens": "🎯 Entrepreneurship for young people", "Como começar ainda na universidade, com visão internacional e saúde mental em dia.": "How to start while still at university, with an international outlook and healthy mind.",
    "🌟 Marca pessoal e networking global": "🌟 Personal brand and global networking", "Construa uma reputação autêntica e uma rede de contatos que abre portas em qualquer país.": "Build an authentic reputation and a network that opens doors in any country.",
    "🚀 Da ideia à execução internacional": "🚀 From idea to international execution", "Passo a passo para tirar um projeto do papel com planejamento, ação e autocuidado.": "A step-by-step path to turn a project into reality through planning, action and self-care.",
    "\"Empreender sem fronteiras exige coragem, mas também cuidado. Cada recomeço me ensinou que a verdadeira expansão vem de dentro para fora.\"": "\"Entrepreneurship without borders takes courage, but also care. Every new beginning taught me that true expansion comes from the inside out.\"",
    "Presença e propósito": "Presence and purpose", "Empreender também é saber sustentar a própria jornada.": "Entrepreneurship also means knowing how to sustain your own journey.",
    "A proposta da palestra é aproximar estratégia, experiência real e equilíbrio emocional — para quem quer começar, crescer ou atravessar novas fronteiras com mais consciência.": "The lecture brings strategy, real experience and emotional balance together — for anyone who wants to start, grow or cross new borders with greater awareness.",
    "AMOSTRA GRÁTIS · EBOOK": "FREE SAMPLE · E-BOOK", "A Coragem de Começar": "The Courage to Start", "Leia gratuitamente o primeiro capítulo": "Read the first chapter for free", "Conheça o início da história antes de acessar o conteúdo completo na sua Biblioteca.": "Discover the beginning of the story before accessing the full content in your Library.",
    "Amostra gratuita · Capítulo 1": "Free sample · Chapter 1", "CAPÍTULO 1": "CHAPTER 1", "O Começo de Tudo": "The Beginning of Everything",
    "Tudo começou com uma fruta. Não uma fruta qualquer, mas um mamão. Eu o carregava nas mãos, oferecendo a quem passava, sem saber que aquele gesto simples era o primeiro passo de uma longa jornada. A feira era o meu mundo, e cada cliente, um professor. As pessoas compravam o mamão, mas eu vendia algo mais: uma história, um sorriso, uma promessa de que aquele dia seria melhor. Aprendi que o valor de uma coisa não está no que ela custa, mas no que ela representa para quem a recebe. Naquela época, eu não sabia o que era empreendedorismo.": "It all began with a fruit. Not just any fruit, but a papaya. I carried it in my hands, offering it to passers-by, unaware that this simple act was the first step in a long journey. The market was my world, and every customer was a teacher. People bought the papaya, but I was selling something more: a story, a smile, a promise that the day could be better. I learned that the value of something is not what it costs, but what it represents to the person receiving it. At the time, I did not know what entrepreneurship was.",
    "Para mim, era apenas sobreviver, ajudar minha família e entender como o mundo funcionava. Mas, olhando para trás, vejo que cada venda era uma lição de persistência e de fé. O mamão era doce, mas a vida, nem sempre. Havia dias em que ninguém comprava, em que o sol queimava e a chuva molhava a mercadoria. Ainda assim, eu voltava no dia seguinte, porque desistir nunca foi uma opção. A feira me ensinou a ler as pessoas. Eu sabia quem compraria apenas pelo olhar, quem estava com pressa e quem queria uma conversa.": "For me, it was simply about surviving, helping my family and understanding how the world worked. Looking back, I see that every sale was a lesson in persistence and faith. The papaya was sweet, but life was not always so. Some days no one bought anything, the sun burned and the rain soaked the produce. Even so, I returned the next day, because giving up was never an option. The market taught me to read people. I could tell who would buy just by their look, who was in a hurry and who wanted a conversation.",
    "Essa habilidade, mais tarde, se tornaria a base de tudo o que eu construiria. Cada porta que se abria era uma oportunidade; cada porta que se fechava, um aprendizado. O menino que vendia mamão não sabia, mas estava sendo forjado para enfrentar o mundo, com todas as suas dificuldades e belezas. Lembro do cheiro da terra molhada, das risadas das feirantes, do barulho das caixas sendo empilhadas. A feira era caótica, mas tinha uma alma. E aquela alma, de alguma forma, entrou em mim. Quando alguém me perguntava o que eu queria ser quando crescesse, eu não sabia responder.": "That skill would later become the foundation of everything I built. Every door that opened was an opportunity; every door that closed was a lesson. The boy who sold papayas did not know it, but he was being shaped to face the world, with all its difficulties and beauty. I remember the smell of wet earth, the laughter of the market sellers and the sound of boxes being stacked. The market was chaotic, but it had a soul. Somehow, that soul became part of me. When someone asked what I wanted to be when I grew up, I did not know how to answer.",
    "Mas, no fundo, eu já sabia: queria ser alguém que fizesse a diferença, nem que fosse vendendo um mamão com um sorriso. Os anos passaram, a feira ficou para trás, mas as lições permaneceram. A coragem de oferecer, a resiliência de continuar e a certeza de que cada pequeno gesto importa. Essa é a essência da minha história. E assim, com um mamão na mão e um sonho no coração, dei o primeiro passo de uma jornada que mudaria minha vida para sempre. Este livro é o início dessa jornada, cheia de altos e baixos, mas sempre movida pela esperança.": "Deep down, however, I already knew: I wanted to be someone who made a difference, even if it was by selling a papaya with a smile. The years passed and the market was left behind, but the lessons remained. The courage to offer, the resilience to continue and the certainty that every small gesture matters. This is the essence of my story. And so, with a papaya in my hand and a dream in my heart, I took the first step on a journey that would change my life forever. This book is the beginning of that journey, full of ups and downs, but always driven by hope.",
    "← Anterior": "← Previous", "Próxima →": "Next →", "Página 1 de 4": "Page 1 of 4", "Fim da amostra gratuita · Os próximos capítulos continuam protegidos.": "End of free sample · The following chapters remain protected.", "Entrar na Área do Cliente": "Enter Client Area",
    "LIVRO · JÁ DISPONÍVEL": "BOOK · AVAILABLE NOW", "O Menino que Vendia Mamão": "The Boy Who Sold Papayas", "Conheça a história que está na origem de": "Discover the story behind", ": uma trajetória de empreendedorismo, coragem, escolhas, resiliência e recomeços.": ": a journey of entrepreneurship, courage, choices, resilience and new beginnings.",
    "O livro possui identidade editorial própria e continua disponível exclusivamente dentro da": "The book has its own editorial identity and remains available exclusively in the", "Área do Cliente / Minha Biblioteca": "Client Area / My Library", "Acessar Minha Biblioteca": "Access My Library",
    "Fique por dentro": "Stay informed", "Próximos": "Upcoming", "lançamentos": "releases", "O ecossistema LdR Essence está em expansão — sempre com o olhar no mundo e na saúde mental. Confira:": "The LdR Essence ecosystem is expanding — always with a global outlook and attention to mental health. See what is coming:",
    "Ebook \"A Coragem de Começar\"": "E-book \"The Courage to Start\"", "A história completa do menino que vendia mamão, com lições práticas de empreendedorismo sem fronteiras, resiliência e visão de futuro.": "The complete story of the boy who sold papayas, with practical lessons in entrepreneurship without borders, resilience and future vision.", "✅ Já disponível — acessar plataforma": "✅ Available now — access platform",
    "Livro Digital \"O Menino que Vendia Mamão\"": "Digital Book \"The Boy Who Sold Papayas\"", "A história que inspirou o ebook, agora também em formato de livro digital. Uma narrativa emocionante sobre coragem, superação e empreendedorismo real.": "The story that inspired the e-book, now also as a digital book. A moving account of courage, overcoming adversity and real entrepreneurship.", "📚 Já disponivel": "📚 Available now",
    "Treinamento de Empreendedorismo": "Entrepreneurship Training", "Treinamento prático com módulos sobre mentalidade global, gestão, marketing, finanças, internacionalização e saúde mental.": "Practical training with modules on global mindset, management, marketing, finance, internationalisation and mental health.", "🚀 Em produção": "🚀 In production",
    "Filme \"O Menino que Vendia Mamão\"": "Film \"The Boy Who Sold Papayas\"", "Adaptação cinematográfica da trajetória real de Luciano, mostrando bastidores, desafios, conquistas e a importância da saúde mental na jornada sem fronteiras.": "A film adaptation of Luciano's real journey, showing the background, challenges, achievements and the importance of mental health on a journey without borders.", "🎥 Em pré-produção": "🎥 In pre-production",
    "Todos esses lançamentos fazem parte do": "All these releases are part of", "Inscreva-se na palestra e garanta acesso exclusivo às novidades em primeira mão.": "Register for the lecture and receive exclusive early access to the latest news.", "📢 Fique atento!": "📢 Stay tuned!",
    "Inscreva-se": "Register", "agora": "now", "Preencha o formulário abaixo. Após o envio, você será": "Complete the form below. After submitting it, you will be", "para o grupo do WhatsApp.": "to the WhatsApp group.", "redirecionado automaticamente": "automatically redirected",
    "📝 Abrir formulário de inscrição": "📝 Open registration form", "📱 Entrar no grupo do WhatsApp": "📱 Join the WhatsApp group", "Assim que você enviar o formulário, será levado diretamente para o grupo do WhatsApp.": "As soon as you submit the form, you will be taken directly to the WhatsApp group.", "⚡ Redirecionamento automático:": "⚡ Automatic redirect:", "(Caso não ocorra, clique no botão verde acima.)": "(If it does not happen, click the green button above.)", "🔒 Seus dados estão seguros. Esta página é apenas para divulgação do evento.": "🔒 Your data is safe. This page is only for promoting the event.",
    "© 2026 Luciano Rodrigues Almeida · Todos os direitos reservados.": "© 2026 Luciano Rodrigues Almeida · All rights reserved.", "📞 Dúvidas: +32492923605": "📞 Questions: +32492923605"
  };

  const fr = {
    "Sobre":"À propos","Temas":"Thèmes","Lançamentos":"Nouveautés","Plataforma":"Plateforme","Inscrever-se":"S'inscrire","Palestra gratuita":"Conférence gratuite","Empreendedorismo":"Entrepreneuriat","e Saúde Mental":"et Santé mentale","sem Fronteiras":"sans Frontières","da Ideia à Oportunidade com Equilíbrio":"de l'idée à l'opportunité avec équilibre",
    "Uma jornada real de coragem, recomeços e visão global — que une o empreendedorismo além das barreiras geográficas com o cuidado essencial com a mente. Inspirada no ebook":"Un véritable parcours de courage, de nouveaux départs et de vision mondiale — alliant l'entrepreneuriat au-delà des frontières géographiques au soin essentiel de la santé mentale. Inspirée de l'e-book",", esta palestra é apresentada por Luciano Rodrigues Almeida e contará com":", cette conférence est présentée par Luciano Rodrigues Almeida et accueillera des","para mostrar que o sucesso sustentável nasce do equilíbrio entre negócios e bem-estar.":"pour montrer que la réussite durable naît de l'équilibre entre activité professionnelle et bien-être.","convidados especiais":"invités spéciaux","🌍 Sem Fronteiras":"🌍 Sans Frontières","🧠 Saúde Mental":"🧠 Santé mentale","🎓 3h + Certificado":"🎓 3 h + Certificat","Apresentado por":"Présenté par",
    "Psicanalista | Mentor | Gestor de Projetos | CEO do Grupo LdR Essence":"Psychanalyste | Mentor | Chef de projet | CEO de Grupo LdR Essence","Começou vendendo mamão nas feiras da Bahia e construiu uma trajetória que atravessou São Paulo, Londres, Portugal e Bélgica. Hoje lidera o Grupo LdR Essence, que integra Luciano (palestras e mentoria), Essence Bem-estar, LdR RH Estratégia e uma linha de produtos em lançamento. Como psicanalista, une a visão empreendedora ao cuidado com a mente, mostrando que o sucesso sustentável nasce do equilíbrio.":"Il a commencé par vendre des papayes sur les marchés de Bahia et a construit un parcours passant par São Paulo, Londres, le Portugal et la Belgique. Aujourd'hui, il dirige Grupo LdR Essence, qui réunit Luciano (conférences et mentorat), Essence Bien-être, LdR RH Estratégia et une gamme de produits en développement. Psychanalyste, il associe vision entrepreneuriale et santé mentale, montrant que la réussite durable naît de l'équilibre.",
    "🌍 Empreendedor sem Fronteiras":"🌍 Entrepreneur sans Frontières","📚 Autor":"📚 Auteur","Quero participar":"Je veux participer","Ver temas":"Voir les thèmes","Psicanalista · Mentor · Gestor de Projetos":"Psychanalyste · Mentor · Chef de projet","O segredo não está no dinheiro — está no movimento.":"Le secret n'est pas dans l'argent — il est dans l'action.","INSPIRADO NO EBOOK · O MENINO QUE VENDIA MAMÃO":"INSPIRÉ DE L'E-BOOK · LE GARÇON QUI VENDAIT DES PAPAYES",
    "A história por trás da palestra":"L'histoire derrière la conférence","Das feiras da Bahia":"Des marchés de Bahia","ao mundo sem fronteiras":"au monde sans frontières","Conheça a trajetória de Luciano — do menino que vendia mamão ao empreendedor que hoje conecta negócios entre Portugal, Bélgica, Brasil e o mundo, com a saúde mental como pilar fundamental para uma jornada sustentável.":"Découvrez le parcours de Luciano — du garçon qui vendait des papayes à l'entrepreneur qui relie aujourd'hui des activités entre le Portugal, la Belgique, le Brésil et le monde, avec la santé mentale comme pilier d'un parcours durable.",
    "Origens":"Origines","Menino que vendia mamão na feira aprendeu cedo que empreender é sobre oferecer valor, persistir e construir relações — sem barreiras.":"Le garçon qui vendait des papayes au marché a appris très tôt qu'entreprendre, c'est offrir de la valeur, persévérer et créer des relations — sans barrières.","Jornada sem Fronteiras":"Parcours sans Frontières","Passou por São Paulo, Londres, Portugal e Bélgica — cada mudança foi um recomeço que expandiu sua visão de mundo e seus negócios.":"Il est passé par São Paulo, Londres, le Portugal et la Belgique — chaque changement fut un nouveau départ qui a élargi sa vision du monde et des affaires.","O ebook":"L'e-book","reúne episódios reais, mostrando que o movimento e o autocuidado são os verdadeiros segredos para empreender sem fronteiras.":"réunit des épisodes réels, montrant que l'action et le soin de soi sont les véritables secrets pour entreprendre sans frontières.",
    "Uma história real":"Une histoire vraie","Experiência que virou conhecimento para compartilhar.":"Une expérience devenue un savoir à partager.","Da Bahia à Europa, cada mudança trouxe desafios, escolhas e aprendizados. A palestra transforma essa trajetória em uma conversa prática sobre coragem, visão global, empreendedorismo e saúde mental.":"De Bahia à l'Europe, chaque changement a apporté défis, choix et apprentissages. La conférence transforme ce parcours en échange concret sur le courage, la vision mondiale, l'entrepreneuriat et la santé mentale.","Durante a palestra, Luciano receberá especialistas em":"Pendant la conférence, Luciano accueillera des spécialistes en","para enriquecer ainda mais a conversa sobre equilíbrio, resiliência e bem-estar no empreendedorismo internacional.":"afin d'enrichir l'échange sur l'équilibre, la résilience et le bien-être dans l'entrepreneuriat international.","🧡 Convidados especiais!":"🧡 Invités spéciaux !","Saúde Mental":"Santé mentale","🚀 Empreendedorismo":"🚀 Entrepreneuriat","🌍 Visão Global":"🌍 Vision mondiale",
    "O que você vai aprender":"Ce que vous allez apprendre","Temas da":"Thèmes de la","palestra":"conférence","Conteúdo prático e inspirador que une empreendedorismo internacional, saúde mental e visão global.":"Un contenu pratique et inspirant qui unit entrepreneuriat international, santé mentale et vision mondiale.","🌍 Empreendedorismo sem Fronteiras":"🌍 Entrepreneuriat sans Frontières","Como identificar oportunidades além do mercado local, adaptar-se a diferentes culturas e construir negócios com alcance internacional.":"Comment identifier des opportunités au-delà du marché local, s'adapter à différentes cultures et créer des activités à portée internationale.","🧠 Saúde Mental do Empreendedor Global":"🧠 Santé mentale de l'entrepreneur mondial","Burnout, ansiedade, resiliência e equilíbrio entre vida pessoal e profissional em contextos multiculturais.":"Épuisement professionnel, anxiété, résilience et équilibre entre vie privée et professionnelle dans des contextes multiculturels.","💡 Transformar conhecimento em oportunidade":"💡 Transformer le savoir en opportunité","Como usar suas experiências e habilidades para criar negócios reais, sem abrir mão do bem-estar.":"Comment utiliser vos expériences et compétences pour créer de vraies activités sans renoncer au bien-être.","🎯 Empreendedorismo para jovens":"🎯 Entrepreneuriat pour les jeunes","Como começar ainda na universidade, com visão internacional e saúde mental em dia.":"Comment commencer dès l'université, avec une vision internationale et une bonne santé mentale.","🌟 Marca pessoal e networking global":"🌟 Marque personnelle et réseau mondial","Construa uma reputação autêntica e uma rede de contatos que abre portas em qualquer país.":"Construisez une réputation authentique et un réseau qui ouvre des portes dans tous les pays.","🚀 Da ideia à execução internacional":"🚀 De l'idée à l'exécution internationale","Passo a passo para tirar um projeto do papel com planejamento, ação e autocuidado.":"Les étapes pour concrétiser un projet avec planification, action et soin de soi.",
    "\"Empreender sem fronteiras exige coragem, mas também cuidado. Cada recomeço me ensinou que a verdadeira expansão vem de dentro para fora.\"":"\"Entreprendre sans frontières exige du courage, mais aussi de l'attention à soi. Chaque nouveau départ m'a appris que la véritable expansion vient de l'intérieur.\"","Presença e propósito":"Présence et raison d'être","Empreender também é saber sustentar a própria jornada.":"Entreprendre, c'est aussi savoir soutenir son propre parcours.","A proposta da palestra é aproximar estratégia, experiência real e equilíbrio emocional — para quem quer começar, crescer ou atravessar novas fronteiras com mais consciência.":"La conférence rapproche stratégie, expérience réelle et équilibre émotionnel — pour celles et ceux qui souhaitent commencer, grandir ou franchir de nouvelles frontières avec plus de conscience.",
    "AMOSTRA GRÁTIS · EBOOK":"EXTRAIT GRATUIT · E-BOOK","A Coragem de Começar":"Le Courage de Commencer","Leia gratuitamente o primeiro capítulo":"Lisez gratuitement le premier chapitre","Conheça o início da história antes de acessar o conteúdo completo na sua Biblioteca.":"Découvrez le début de l'histoire avant d'accéder au contenu complet dans votre Bibliothèque.","Amostra gratuita · Capítulo 1":"Extrait gratuit · Chapitre 1","CAPÍTULO 1":"CHAPITRE 1","O Começo de Tudo":"Le commencement de tout",
    "Tudo começou com uma fruta. Não uma fruta qualquer, mas um mamão. Eu o carregava nas mãos, oferecendo a quem passava, sem saber que aquele gesto simples era o primeiro passo de uma longa jornada. A feira era o meu mundo, e cada cliente, um professor. As pessoas compravam o mamão, mas eu vendia algo mais: uma história, um sorriso, uma promessa de que aquele dia seria melhor. Aprendi que o valor de uma coisa não está no que ela custa, mas no que ela representa para quem a recebe. Naquela época, eu não sabia o que era empreendedorismo.":"Tout a commencé avec un fruit. Pas n'importe lequel : une papaye. Je la portais dans mes mains et la proposais aux passants, sans savoir que ce geste simple était le premier pas d'un long parcours. Le marché était mon monde, et chaque client, un professeur. Les gens achetaient la papaye, mais je vendais davantage : une histoire, un sourire, la promesse que la journée serait meilleure. J'ai appris que la valeur d'une chose ne réside pas dans son prix, mais dans ce qu'elle représente pour celui qui la reçoit. À l'époque, je ne savais pas ce qu'était l'entrepreneuriat.",
    "Para mim, era apenas sobreviver, ajudar minha família e entender como o mundo funcionava. Mas, olhando para trás, vejo que cada venda era uma lição de persistência e de fé. O mamão era doce, mas a vida, nem sempre. Havia dias em que ninguém comprava, em que o sol queimava e a chuva molhava a mercadoria. Ainda assim, eu voltava no dia seguinte, porque desistir nunca foi uma opção. A feira me ensinou a ler as pessoas. Eu sabia quem compraria apenas pelo olhar, quem estava com pressa e quem queria uma conversa.":"Pour moi, il s'agissait simplement de survivre, d'aider ma famille et de comprendre le monde. Avec le recul, je vois que chaque vente était une leçon de persévérance et de foi. La papaye était douce, mais la vie ne l'était pas toujours. Certains jours, personne n'achetait, le soleil brûlait et la pluie mouillait la marchandise. Pourtant, je revenais le lendemain, car abandonner n'a jamais été une option. Le marché m'a appris à lire les gens. Je savais, à leur regard, qui achèterait, qui était pressé et qui souhaitait parler.",
    "Essa habilidade, mais tarde, se tornaria a base de tudo o que eu construiria. Cada porta que se abria era uma oportunidade; cada porta que se fechava, um aprendizado. O menino que vendia mamão não sabia, mas estava sendo forjado para enfrentar o mundo, com todas as suas dificuldades e belezas. Lembro do cheiro da terra molhada, das risadas das feirantes, do barulho das caixas sendo empilhadas. A feira era caótica, mas tinha uma alma. E aquela alma, de alguma forma, entrou em mim. Quando alguém me perguntava o que eu queria ser quando crescesse, eu não sabia responder.":"Cette capacité allait plus tard devenir la base de tout ce que je construirais. Chaque porte ouverte était une opportunité ; chaque porte fermée, un apprentissage. Le garçon qui vendait des papayes ne le savait pas, mais il se préparait à affronter le monde, avec toutes ses difficultés et ses beautés. Je me souviens de l'odeur de la terre mouillée, du rire des vendeuses et du bruit des caisses empilées. Le marché était chaotique, mais il avait une âme. Et cette âme, d'une certaine manière, est entrée en moi. Quand on me demandait ce que je voulais devenir, je ne savais pas répondre.",
    "Mas, no fundo, eu já sabia: queria ser alguém que fizesse a diferença, nem que fosse vendendo um mamão com um sorriso. Os anos passaram, a feira ficou para trás, mas as lições permaneceram. A coragem de oferecer, a resiliência de continuar e a certeza de que cada pequeno gesto importa. Essa é a essência da minha história. E assim, com um mamão na mão e um sonho no coração, dei o primeiro passo de uma jornada que mudaria minha vida para sempre. Este livro é o início dessa jornada, cheia de altos e baixos, mas sempre movida pela esperança.":"Mais au fond, je le savais déjà : je voulais être quelqu'un qui ferait la différence, même en vendant une papaye avec le sourire. Les années ont passé et le marché est resté derrière moi, mais les leçons sont demeurées. Le courage de proposer, la résilience de continuer et la certitude que chaque petit geste compte. Voilà l'essence de mon histoire. Ainsi, une papaye à la main et un rêve dans le cœur, j'ai fait le premier pas d'un parcours qui allait changer ma vie pour toujours. Ce livre est le début de ce voyage, fait de hauts et de bas, mais toujours porté par l'espoir.",
    "← Anterior":"← Précédent","Próxima →":"Suivant →","Página 1 de 4":"Page 1 sur 4","Fim da amostra gratuita · Os próximos capítulos continuam protegidos.":"Fin de l'extrait gratuit · Les chapitres suivants restent protégés.","Entrar na Área do Cliente":"Accéder à l'Espace Client","LIVRO · JÁ DISPONÍVEL":"LIVRE · DISPONIBLE","O Menino que Vendia Mamão":"Le Garçon qui Vendait des Papayes","Conheça a história que está na origem de":"Découvrez l'histoire à l'origine de",
    ": uma trajetória de empreendedorismo, coragem, escolhas, resiliência e recomeços.":" : un parcours d'entrepreneuriat, de courage, de choix, de résilience et de nouveaux départs.","O livro possui identidade editorial própria e continua disponível exclusivamente dentro da":"Le livre possède sa propre identité éditoriale et reste disponible exclusivement dans","Área do Cliente / Minha Biblioteca":"l'Espace Client / Ma Bibliothèque","Acessar Minha Biblioteca":"Accéder à Ma Bibliothèque","Fique por dentro":"Restez informé","Próximos":"Prochaines","lançamentos":"nouveautés","O ecossistema LdR Essence está em expansão — sempre com o olhar no mundo e na saúde mental. Confira:":"L'écosystème LdR Essence se développe — toujours avec une vision mondiale et une attention à la santé mentale. Découvrez la suite :",
    "Ebook \"A Coragem de Começar\"":"E-book \"Le Courage de Commencer\"","A história completa do menino que vendia mamão, com lições práticas de empreendedorismo sem fronteiras, resiliência e visão de futuro.":"L'histoire complète du garçon qui vendait des papayes, avec des leçons pratiques d'entrepreneuriat sans frontières, de résilience et de vision d'avenir.","✅ Já disponível — acessar plataforma":"✅ Disponible — accéder à la plateforme","Livro Digital \"O Menino que Vendia Mamão\"":"Livre numérique \"Le Garçon qui Vendait des Papayes\"","A história que inspirou o ebook, agora também em formato de livro digital. Uma narrativa emocionante sobre coragem, superação e empreendedorismo real.":"L'histoire qui a inspiré l'e-book, désormais aussi en livre numérique. Un récit émouvant sur le courage, le dépassement et l'entrepreneuriat réel.","📚 Já disponivel":"📚 Disponible","Treinamento de Empreendedorismo":"Formation à l'entrepreneuriat","Treinamento prático com módulos sobre mentalidade global, gestão, marketing, finanças, internacionalização e saúde mental.":"Formation pratique avec des modules sur l'état d'esprit mondial, la gestion, le marketing, la finance, l'internationalisation et la santé mentale.","🚀 Em produção":"🚀 En production","Filme \"O Menino que Vendia Mamão\"":"Film \"Le Garçon qui Vendait des Papayes\"","Adaptação cinematográfica da trajetória real de Luciano, mostrando bastidores, desafios, conquistas e a importância da saúde mental na jornada sem fronteiras.":"Adaptation cinématographique du parcours réel de Luciano, montrant les coulisses, les défis, les réussites et l'importance de la santé mentale dans un parcours sans frontières.","🎥 Em pré-produção":"🎥 En préproduction","Todos esses lançamentos fazem parte do":"Toutes ces nouveautés font partie de","Inscreva-se na palestra e garanta acesso exclusivo às novidades em primeira mão.":"Inscrivez-vous à la conférence et bénéficiez d'un accès exclusif aux nouveautés.","📢 Fique atento!":"📢 Restez attentif !",
    "Inscreva-se":"Inscrivez-vous","agora":"maintenant","Preencha o formulário abaixo. Após o envio, você será":"Remplissez le formulaire ci-dessous. Après l'envoi, vous serez","para o grupo do WhatsApp.":"vers le groupe WhatsApp.","redirecionado automaticamente":"automatiquement redirigé","📝 Abrir formulário de inscrição":"📝 Ouvrir le formulaire d'inscription","📱 Entrar no grupo do WhatsApp":"📱 Rejoindre le groupe WhatsApp","Assim que você enviar o formulário, será levado diretamente para o grupo do WhatsApp.":"Dès l'envoi du formulaire, vous serez dirigé vers le groupe WhatsApp.","⚡ Redirecionamento automático:":"⚡ Redirection automatique :","(Caso não ocorra, clique no botão verde acima.)":"(Si cela ne se produit pas, cliquez sur le bouton vert ci-dessus.)","🔒 Seus dados estão seguros. Esta página é apenas para divulgação do evento.":"🔒 Vos données sont protégées. Cette page sert uniquement à présenter l'événement.","© 2026 Luciano Rodrigues Almeida · Todos os direitos reservados.":"© 2026 Luciano Rodrigues Almeida · Tous droits réservés.","📞 Dúvidas: +32492923605":"📞 Questions : +32492923605"
  };

  const es = {
    "Sobre":"Acerca de","Temas":"Temas","Lançamentos":"Lanzamientos","Plataforma":"Plataforma","Inscrever-se":"Inscribirse","Palestra gratuita":"Conferencia gratuita","Empreendedorismo":"Emprendimiento","e Saúde Mental":"y Salud Mental","sem Fronteiras":"sin Fronteras","da Ideia à Oportunidade com Equilíbrio":"de la idea a la oportunidad con equilibrio",
    "Uma jornada real de coragem, recomeços e visão global — que une o empreendedorismo além das barreiras geográficas com o cuidado essencial com a mente. Inspirada no ebook":"Un viaje real de valentía, nuevos comienzos y visión global, que une el emprendimiento más allá de las barreras geográficas con el cuidado esencial de la salud mental. Inspirada en el e-book",", esta palestra é apresentada por Luciano Rodrigues Almeida e contará com":", esta conferencia está presentada por Luciano Rodrigues Almeida y contará con","para mostrar que o sucesso sustentável nasce do equilíbrio entre negócios e bem-estar.":"para mostrar que el éxito sostenible nace del equilibrio entre los negocios y el bienestar.","convidados especiais":"invitados especiales","🌍 Sem Fronteiras":"🌍 Sin Fronteras","🧠 Saúde Mental":"🧠 Salud Mental","🎓 3h + Certificado":"🎓 3 h + Certificado","Apresentado por":"Presentado por","Psicanalista | Mentor | Gestor de Projetos | CEO do Grupo LdR Essence":"Psicoanalista | Mentor | Gestor de Proyectos | CEO de Grupo LdR Essence",
    "Começou vendendo mamão nas feiras da Bahia e construiu uma trajetória que atravessou São Paulo, Londres, Portugal e Bélgica. Hoje lidera o Grupo LdR Essence, que integra Luciano (palestras e mentoria), Essence Bem-estar, LdR RH Estratégia e uma linha de produtos em lançamento. Como psicanalista, une a visão empreendedora ao cuidado com a mente, mostrando que o sucesso sustentável nasce do equilíbrio.":"Comenzó vendiendo papayas en los mercados de Bahía y construyó una trayectoria que pasó por São Paulo, Londres, Portugal y Bélgica. Hoy dirige Grupo LdR Essence, que integra Luciano (conferencias y mentoría), Essence Bienestar, LdR RH Estratégia y una línea de productos en desarrollo. Como psicoanalista, une la visión emprendedora al cuidado de la mente y demuestra que el éxito sostenible nace del equilibrio.","🌍 Empreendedor sem Fronteiras":"🌍 Emprendedor sin Fronteras","📚 Autor":"📚 Autor","Quero participar":"Quiero participar","Ver temas":"Ver temas","Psicanalista · Mentor · Gestor de Projetos":"Psicoanalista · Mentor · Gestor de Proyectos","O segredo não está no dinheiro — está no movimento.":"El secreto no está en el dinero, sino en el movimiento.","INSPIRADO NO EBOOK · O MENINO QUE VENDIA MAMÃO":"INSPIRADO EN EL E-BOOK · EL NIÑO QUE VENDÍA PAPAYAS",
    "A história por trás da palestra":"La historia detrás de la conferencia","Das feiras da Bahia":"De los mercados de Bahía","ao mundo sem fronteiras":"al mundo sin fronteras","Conheça a trajetória de Luciano — do menino que vendia mamão ao empreendedor que hoje conecta negócios entre Portugal, Bélgica, Brasil e o mundo, com a saúde mental como pilar fundamental para uma jornada sustentável.":"Conoce la trayectoria de Luciano: del niño que vendía papayas al emprendedor que hoy conecta negocios entre Portugal, Bélgica, Brasil y el mundo, con la salud mental como pilar fundamental de un camino sostenible.","Origens":"Orígenes","Menino que vendia mamão na feira aprendeu cedo que empreender é sobre oferecer valor, persistir e construir relações — sem barreiras.":"El niño que vendía papayas en el mercado aprendió pronto que emprender significa ofrecer valor, persistir y construir relaciones, sin barreras.","Jornada sem Fronteiras":"Trayectoria sin Fronteras","Passou por São Paulo, Londres, Portugal e Bélgica — cada mudança foi um recomeço que expandiu sua visão de mundo e seus negócios.":"Pasó por São Paulo, Londres, Portugal y Bélgica; cada cambio fue un nuevo comienzo que amplió su visión del mundo y de los negocios.","O ebook":"El e-book","reúne episódios reais, mostrando que o movimento e o autocuidado são os verdadeiros segredos para empreender sem fronteiras.":"reúne episodios reales y demuestra que el movimiento y el autocuidado son los verdaderos secretos para emprender sin fronteras.",
    "Uma história real":"Una historia real","Experiência que virou conhecimento para compartilhar.":"Experiencia convertida en conocimiento para compartir.","Da Bahia à Europa, cada mudança trouxe desafios, escolhas e aprendizados. A palestra transforma essa trajetória em uma conversa prática sobre coragem, visão global, empreendedorismo e saúde mental.":"De Bahía a Europa, cada cambio trajo desafíos, decisiones y aprendizajes. La conferencia transforma esta trayectoria en una conversación práctica sobre valentía, visión global, emprendimiento y salud mental.","Durante a palestra, Luciano receberá especialistas em":"Durante la conferencia, Luciano recibirá a especialistas en","para enriquecer ainda mais a conversa sobre equilíbrio, resiliência e bem-estar no empreendedorismo internacional.":"para enriquecer la conversación sobre equilibrio, resiliencia y bienestar en el emprendimiento internacional.","🧡 Convidados especiais!":"🧡 ¡Invitados especiales!","Saúde Mental":"Salud Mental","🚀 Empreendedorismo":"🚀 Emprendimiento","🌍 Visão Global":"🌍 Visión Global","O que você vai aprender":"Lo que aprenderás","Temas da":"Temas de la","palestra":"conferencia","Conteúdo prático e inspirador que une empreendedorismo internacional, saúde mental e visão global.":"Contenido práctico e inspirador que une emprendimiento internacional, salud mental y visión global.",
    "🌍 Empreendedorismo sem Fronteiras":"🌍 Emprendimiento sin Fronteras","Como identificar oportunidades além do mercado local, adaptar-se a diferentes culturas e construir negócios com alcance internacional.":"Cómo identificar oportunidades más allá del mercado local, adaptarse a distintas culturas y construir negocios de alcance internacional.","🧠 Saúde Mental do Empreendedor Global":"🧠 Salud Mental del Emprendedor Global","Burnout, ansiedade, resiliência e equilíbrio entre vida pessoal e profissional em contextos multiculturais.":"Agotamiento, ansiedad, resiliencia y equilibrio entre vida personal y profesional en contextos multiculturales.","💡 Transformar conhecimento em oportunidade":"💡 Transformar conocimiento en oportunidad","Como usar suas experiências e habilidades para criar negócios reais, sem abrir mão do bem-estar.":"Cómo utilizar tus experiencias y habilidades para crear negocios reales sin renunciar al bienestar.","🎯 Empreendedorismo para jovens":"🎯 Emprendimiento para jóvenes","Como começar ainda na universidade, com visão internacional e saúde mental em dia.":"Cómo empezar desde la universidad, con visión internacional y una buena salud mental.","🌟 Marca pessoal e networking global":"🌟 Marca personal y red global","Construa uma reputação autêntica e uma rede de contatos que abre portas em qualquer país.":"Construye una reputación auténtica y una red de contactos que abra puertas en cualquier país.","🚀 Da ideia à execução internacional":"🚀 De la idea a la ejecución internacional","Passo a passo para tirar um projeto do papel com planejamento, ação e autocuidado.":"Paso a paso para convertir un proyecto en realidad mediante planificación, acción y autocuidado.",
    "\"Empreender sem fronteiras exige coragem, mas também cuidado. Cada recomeço me ensinou que a verdadeira expansão vem de dentro para fora.\"":"\"Emprender sin fronteras exige valentía, pero también cuidado. Cada nuevo comienzo me enseñó que la verdadera expansión nace de dentro hacia fuera.\"","Presença e propósito":"Presencia y propósito","Empreender também é saber sustentar a própria jornada.":"Emprender también es saber sostener el propio camino.","A proposta da palestra é aproximar estratégia, experiência real e equilíbrio emocional — para quem quer começar, crescer ou atravessar novas fronteiras com mais consciência.":"La conferencia acerca estrategia, experiencia real y equilibrio emocional a quienes quieren empezar, crecer o cruzar nuevas fronteras con mayor conciencia.",
    "AMOSTRA GRÁTIS · EBOOK":"MUESTRA GRATIS · E-BOOK","A Coragem de Começar":"El Coraje de Empezar","Leia gratuitamente o primeiro capítulo":"Lee gratis el primer capítulo","Conheça o início da história antes de acessar o conteúdo completo na sua Biblioteca.":"Conoce el comienzo de la historia antes de acceder al contenido completo en tu Biblioteca.","Amostra gratuita · Capítulo 1":"Muestra gratuita · Capítulo 1","CAPÍTULO 1":"CAPÍTULO 1","O Começo de Tudo":"El comienzo de todo",
    "Tudo começou com uma fruta. Não uma fruta qualquer, mas um mamão. Eu o carregava nas mãos, oferecendo a quem passava, sem saber que aquele gesto simples era o primeiro passo de uma longa jornada. A feira era o meu mundo, e cada cliente, um professor. As pessoas compravam o mamão, mas eu vendia algo mais: uma história, um sorriso, uma promessa de que aquele dia seria melhor. Aprendi que o valor de uma coisa não está no que ela custa, mas no que ela representa para quem a recebe. Naquela época, eu não sabia o que era empreendedorismo.":"Todo comenzó con una fruta. No cualquier fruta, sino una papaya. La llevaba en las manos y se la ofrecía a quienes pasaban, sin saber que aquel sencillo gesto era el primer paso de un largo viaje. El mercado era mi mundo y cada cliente, un maestro. La gente compraba la papaya, pero yo vendía algo más: una historia, una sonrisa, la promesa de que aquel día sería mejor. Aprendí que el valor de algo no está en lo que cuesta, sino en lo que representa para quien lo recibe. En aquella época, no sabía qué era el emprendimiento.",
    "Para mim, era apenas sobreviver, ajudar minha família e entender como o mundo funcionava. Mas, olhando para trás, vejo que cada venda era uma lição de persistência e de fé. O mamão era doce, mas a vida, nem sempre. Havia dias em que ninguém comprava, em que o sol queimava e a chuva molhava a mercadoria. Ainda assim, eu voltava no dia seguinte, porque desistir nunca foi uma opção. A feira me ensinou a ler as pessoas. Eu sabia quem compraria apenas pelo olhar, quem estava com pressa e quem queria uma conversa.":"Para mí, solo se trataba de sobrevivir, ayudar a mi familia y entender cómo funcionaba el mundo. Mirando atrás, veo que cada venta era una lección de persistencia y fe. La papaya era dulce, pero la vida no siempre lo era. Había días en que nadie compraba, el sol quemaba y la lluvia mojaba la mercancía. Aun así, volvía al día siguiente, porque rendirse nunca fue una opción. El mercado me enseñó a leer a las personas. Sabía quién compraría con solo mirarlo, quién tenía prisa y quién quería conversar.",
    "Essa habilidade, mais tarde, se tornaria a base de tudo o que eu construiria. Cada porta que se abria era uma oportunidade; cada porta que se fechava, um aprendizado. O menino que vendia mamão não sabia, mas estava sendo forjado para enfrentar o mundo, com todas as suas dificuldades e belezas. Lembro do cheiro da terra molhada, das risadas das feirantes, do barulho das caixas sendo empilhadas. A feira era caótica, mas tinha uma alma. E aquela alma, de alguma forma, entrou em mim. Quando alguém me perguntava o que eu queria ser quando crescesse, eu não sabia responder.":"Esa habilidad se convertiría más tarde en la base de todo lo que construiría. Cada puerta que se abría era una oportunidad; cada puerta que se cerraba, un aprendizaje. El niño que vendía papayas no lo sabía, pero se estaba preparando para enfrentarse al mundo, con todas sus dificultades y su belleza. Recuerdo el olor de la tierra mojada, las risas de las vendedoras y el ruido de las cajas apiladas. El mercado era caótico, pero tenía alma. Y esa alma, de algún modo, entró en mí. Cuando alguien me preguntaba qué quería ser de mayor, no sabía qué responder.",
    "Mas, no fundo, eu já sabia: queria ser alguém que fizesse a diferença, nem que fosse vendendo um mamão com um sorriso. Os anos passaram, a feira ficou para trás, mas as lições permaneceram. A coragem de oferecer, a resiliência de continuar e a certeza de que cada pequeno gesto importa. Essa é a essência da minha história. E assim, com um mamão na mão e um sonho no coração, dei o primeiro passo de uma jornada que mudaria minha vida para sempre. Este livro é o início dessa jornada, cheia de altos e baixos, mas sempre movida pela esperança.":"Pero, en el fondo, ya lo sabía: quería ser alguien que marcara la diferencia, aunque fuera vendiendo una papaya con una sonrisa. Pasaron los años y el mercado quedó atrás, pero las lecciones permanecieron. El valor de ofrecer, la resiliencia para continuar y la certeza de que cada pequeño gesto importa. Esa es la esencia de mi historia. Así, con una papaya en la mano y un sueño en el corazón, di el primer paso de un viaje que cambiaría mi vida para siempre. Este libro es el comienzo de ese viaje, lleno de altibajos, pero siempre impulsado por la esperanza.",
    "← Anterior":"← Anterior","Próxima →":"Siguiente →","Página 1 de 4":"Página 1 de 4","Fim da amostra gratuita · Os próximos capítulos continuam protegidos.":"Fin de la muestra gratuita · Los siguientes capítulos permanecen protegidos.","Entrar na Área do Cliente":"Entrar al Área del Cliente","LIVRO · JÁ DISPONÍVEL":"LIBRO · YA DISPONIBLE","O Menino que Vendia Mamão":"El Niño que Vendía Papayas","Conheça a história que está na origem de":"Conoce la historia que está en el origen de",
    ": uma trajetória de empreendedorismo, coragem, escolhas, resiliência e recomeços.":": una trayectoria de emprendimiento, valentía, decisiones, resiliencia y nuevos comienzos.","O livro possui identidade editorial própria e continua disponível exclusivamente dentro da":"El libro tiene una identidad editorial propia y sigue disponible exclusivamente en el","Área do Cliente / Minha Biblioteca":"Área del Cliente / Mi Biblioteca","Acessar Minha Biblioteca":"Acceder a Mi Biblioteca","Fique por dentro":"Mantente informado","Próximos":"Próximos","lançamentos":"lanzamientos","O ecossistema LdR Essence está em expansão — sempre com o olhar no mundo e na saúde mental. Confira:":"El ecosistema LdR Essence está creciendo, siempre con una mirada global y atención a la salud mental. Descubre lo próximo:",
    "Ebook \"A Coragem de Começar\"":"E-book \"El Coraje de Empezar\"","A história completa do menino que vendia mamão, com lições práticas de empreendedorismo sem fronteiras, resiliência e visão de futuro.":"La historia completa del niño que vendía papayas, con lecciones prácticas de emprendimiento sin fronteras, resiliencia y visión de futuro.","✅ Já disponível — acessar plataforma":"✅ Ya disponible — acceder a la plataforma","Livro Digital \"O Menino que Vendia Mamão\"":"Libro Digital \"El Niño que Vendía Papayas\"","A história que inspirou o ebook, agora também em formato de livro digital. Uma narrativa emocionante sobre coragem, superação e empreendedorismo real.":"La historia que inspiró el e-book, ahora también en formato de libro digital. Una narrativa emocionante sobre valentía, superación y emprendimiento real.","📚 Já disponivel":"📚 Ya disponible","Treinamento de Empreendedorismo":"Formación en Emprendimiento","Treinamento prático com módulos sobre mentalidade global, gestão, marketing, finanças, internacionalização e saúde mental.":"Formación práctica con módulos sobre mentalidad global, gestión, marketing, finanzas, internacionalización y salud mental.","🚀 Em produção":"🚀 En producción","Filme \"O Menino que Vendia Mamão\"":"Película \"El Niño que Vendía Papayas\"","Adaptação cinematográfica da trajetória real de Luciano, mostrando bastidores, desafios, conquistas e a importância da saúde mental na jornada sem fronteiras.":"Adaptación cinematográfica de la trayectoria real de Luciano, mostrando el detrás de escena, los desafíos, los logros y la importancia de la salud mental en un camino sin fronteras.","🎥 Em pré-produção":"🎥 En preproducción","Todos esses lançamentos fazem parte do":"Todos estos lanzamientos forman parte de","Inscreva-se na palestra e garanta acesso exclusivo às novidades em primeira mão.":"Inscríbete en la conferencia y obtén acceso exclusivo a las novedades.","📢 Fique atento!":"📢 ¡Mantente atento!",
    "Inscreva-se":"Inscríbete","agora":"ahora","Preencha o formulário abaixo. Após o envio, você será":"Completa el formulario a continuación. Después de enviarlo, serás","para o grupo do WhatsApp.":"al grupo de WhatsApp.","redirecionado automaticamente":"redirigido automáticamente","📝 Abrir formulário de inscrição":"📝 Abrir formulario de inscripción","📱 Entrar no grupo do WhatsApp":"📱 Entrar al grupo de WhatsApp","Assim que você enviar o formulário, será levado diretamente para o grupo do WhatsApp.":"En cuanto envíes el formulario, accederás directamente al grupo de WhatsApp.","⚡ Redirecionamento automático:":"⚡ Redirección automática:","(Caso não ocorra, clique no botão verde acima.)":"(Si no sucede, haz clic en el botón verde de arriba.)","🔒 Seus dados estão seguros. Esta página é apenas para divulgação do evento.":"🔒 Tus datos están seguros. Esta página solo sirve para promocionar el evento.","© 2026 Luciano Rodrigues Almeida · Todos os direitos reservados.":"© 2026 Luciano Rodrigues Almeida · Todos los derechos reservados.","📞 Dúvidas: +32492923605":"📞 Preguntas: +32492923605"
  };

  const dicts = { pt: {}, fr, en, es };
  const titles = {
    pt: ["Palestra e Plataforma — Luciano Rodrigues Almeida", "Palestra Empreendedorismo sem Fronteiras e Saúde Mental e Plataforma A Coragem de Começar, em um único site."],
    fr: ["Conférence et Plateforme — Luciano Rodrigues Almeida", "Conférence Entrepreneuriat sans Frontières et Santé mentale, avec la plateforme Le Courage de Commencer."],
    en: ["Lecture and Platform — Luciano Rodrigues Almeida", "Entrepreneurship without Borders and Mental Health lecture, with The Courage to Start platform."],
    es: ["Conferencia y Plataforma — Luciano Rodrigues Almeida", "Conferencia Emprendimiento sin Fronteras y Salud Mental, con la plataforma El Coraje de Empezar."]
  };

  const reverse = {};
  [fr, en, es].forEach((dict) => Object.entries(dict).forEach(([pt, translated]) => { reverse[translated] = pt; }));
  let translating = false;
  let current = "pt";

  function requestedLocale() {
    const query = new URLSearchParams(location.search).get("lang");
    if (SUPPORTED.includes(query)) return query;
    const saved = localStorage.getItem(STORAGE_KEY);
    if (SUPPORTED.includes(saved)) return saved;
    const detected = (navigator.language || "pt").slice(0, 2).toLowerCase();
    return SUPPORTED.includes(detected) ? detected : "pt";
  }

  function translateTextNode(node, lang) {
    const raw = node.nodeValue || "";
    const normalized = raw.replace(/\s+/g, " ").trim();
    if (!normalized) return;
    const canonical = reverse[normalized] || normalized;
    const translated = lang === "pt" ? canonical : (dicts[lang][canonical] || canonical);
    if (translated === normalized) return;
    const leading = raw.match(/^\s*/)[0];
    const trailing = raw.match(/\s*$/)[0];
    node.nodeValue = leading + translated + trailing;
  }

  function translateElement(root, lang) {
    if (!root || root.nodeType !== 1) return;
    [root, ...root.querySelectorAll("*")].forEach((element) => {
      if (["SCRIPT", "STYLE", "NOSCRIPT"].includes(element.tagName)) return;
      Array.from(element.childNodes || []).forEach((node) => {
        if (node.nodeType === 3) translateTextNode(node, lang);
      });
    });
  }

  function translateRoot(lang) {
    const root = document.getElementById("palestraView");
    if (!root) return;
    translating = true;
    translateElement(root, lang);
    translating = false;
  }

  function updatePageCounter(lang, scope) {
    const root = scope || document.getElementById("palestraView");
    if (!root) return;
    const elements = root.nodeType === 1 ? [root, ...root.querySelectorAll("span,div,p")] : [];
    elements.forEach((el) => {
      if (el.children.length || !el.textContent) return;
      const value = el.textContent.trim();
      const match = value.match(/^(?:Página|Page)\s+(\d+)\s+(?:de|of|sur)\s+(\d+)$/i);
      if (!match) return;
      const labels = { pt: `Página ${match[1]} de ${match[2]}`, fr: `Page ${match[1]} sur ${match[2]}`, en: `Page ${match[1]} of ${match[2]}`, es: `Página ${match[1]} de ${match[2]}` };
      el.textContent = labels[lang];
    });
  }

  function applyLocale(lang, updateUrl) {
    if (!SUPPORTED.includes(lang)) lang = "pt";
    current = lang;
    localStorage.setItem(STORAGE_KEY, lang);
    document.documentElement.lang = HTML_LANG[lang];
    translateRoot(lang);
    updatePageCounter(lang);
    document.title = titles[lang][0];
    const meta = document.querySelector('meta[name="description"]');
    if (meta) meta.setAttribute("content", titles[lang][1]);
    document.querySelectorAll(".ldr-public-lang-button").forEach((button) => {
      const active = button.dataset.lang === lang;
      button.classList.toggle("active", active);
      button.setAttribute("aria-pressed", String(active));
    });
    if (updateUrl) {
      const url = new URL(location.href);
      url.searchParams.set("lang", lang);
      history.replaceState({}, "", url.pathname + url.search + url.hash);
    }
    window.dispatchEvent(new CustomEvent("luciano:languagechange", { detail: { lang } }));
  }

  function addSwitcher() {
    const nav = document.querySelector("#palestraView header nav");
    if (!nav || nav.querySelector(".ldr-public-language-switcher")) return;
    const style = document.createElement("style");
    style.textContent = ".ldr-public-language-switcher{display:flex;gap:4px;align-items:center;flex-wrap:nowrap}.ldr-public-lang-button{border:1px solid rgba(247,239,227,.45);background:transparent;color:inherit;border-radius:999px;padding:5px 8px;font:700 11px/1 Montserrat,Arial,sans-serif;cursor:pointer}.ldr-public-lang-button:hover,.ldr-public-lang-button:focus-visible,.ldr-public-lang-button.active{background:var(--ouro);border-color:var(--ouro);color:var(--vinho2)}@media(max-width:760px){.ldr-public-language-switcher{order:-1;width:100%;justify-content:center;margin:4px 0}.ldr-public-lang-button{padding:7px 10px}}";
    document.head.appendChild(style);
    const wrap = document.createElement("div");
    wrap.className = "ldr-public-language-switcher";
    wrap.setAttribute("role", "group");
    wrap.setAttribute("aria-label", "Idioma / Language / Langue");
    SUPPORTED.forEach((lang) => {
      const button = document.createElement("button");
      button.type = "button";
      button.className = "ldr-public-lang-button";
      button.dataset.lang = lang;
      button.textContent = LABELS[lang];
      button.addEventListener("click", () => applyLocale(lang, true));
      wrap.appendChild(button);
    });
    const signup = nav.querySelector(".btn");
    nav.insertBefore(wrap, signup || null);
  }

  function init() {
    if (!document.getElementById("palestraView")) return;
    addSwitcher();
    applyLocale(requestedLocale(), false);
    const observer = new MutationObserver((mutations) => {
      if (translating) return;
      translating = true;
      mutations.forEach((mutation) => {
        if (mutation.type === "characterData") {
          translateTextNode(mutation.target, current);
          updatePageCounter(current, mutation.target.parentElement);
          return;
        }
        mutation.addedNodes.forEach((node) => {
          if (node.nodeType === 3) translateTextNode(node, current);
          if (node.nodeType === 1) {
            translateElement(node, current);
            updatePageCounter(current, node);
          }
        });
      });
      translating = false;
    });
    observer.observe(document.getElementById("palestraView"), { childList: true, subtree: true, characterData: true });
  }

  if (document.readyState === "loading") document.addEventListener("DOMContentLoaded", init, { once: true });
  else init();
})();
