import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Eye, EyeOff, Flag, Pin, PinOff, ShieldCheck, UserCog } from "lucide-react";
import { academicAdminSnapshot, academicModerate, academicSetProfileRole } from "@/lib/academic-network.functions";
import { useAccess } from "@/lib/central-data";

export const Route=createFileRoute("/_authenticated/admin/rede-academica")({component:AcademicNetworkAdmin});

function AcademicNetworkAdmin(){
  const access=useAccess(); const qc=useQueryClient(); const snapshot=useServerFn(academicAdminSnapshot), moderateFn=useServerFn(academicModerate), setRoleFn=useServerFn(academicSetProfileRole);
  const {data,isLoading}=useQuery({queryKey:["academic-network-admin"],queryFn:()=>snapshot({}),enabled:access.data?.authorized===true&&access.data.role==="superadmin"});
  const moderate=useMutation({mutationFn:(x:{kind:"post"|"comment"|"report";id:string;action:"hide"|"restore"|"pin"|"unpin"|"resolve"|"dismiss"})=>moderateFn({data:x}),onSuccess:()=>qc.invalidateQueries({queryKey:["academic-network-admin"]})});
  const setRole=useMutation({mutationFn:(x:{profileId:string;role:"member"|"student"|"professor"|"mentor"})=>setRoleFn({data:x}),onSuccess:()=>qc.invalidateQueries({queryKey:["academic-network-admin"]})});
  if(access.isLoading)return <div className="s8-card mx-auto max-w-md text-center">Carregando…</div>;
  if(!access.data?.authorized||access.data.role!=="superadmin")return <div className="s8-card mx-auto max-w-md text-center">Acesso restrito ao Master.</div>;
  if(isLoading||!data)return <div className="s8-card mx-auto max-w-md text-center">Carregando Rede Acadêmica…</div>;
  const activeReports=(data.reports??[]).filter((r:any)=>r.status==="new"||r.status==="reviewing");
  return <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6"><header><p className="text-xs font-black tracking-[.18em] text-muted-foreground">PAINEL MASTER</p><h1 className="mt-1 text-3xl font-bold">Rede Acadêmica</h1><p className="mt-2 text-sm text-muted-foreground">Moderação de publicações, comentários e denúncias. O conteúdo do Diário privado não é exibido aqui.</p></header>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat title="Publicações" value={data.posts?.length??0}/><Stat title="Comentários" value={data.comments?.length??0}/><Stat title="Denúncias abertas" value={activeReports.length}/><Stat title="Perfis acadêmicos" value={data.profiles?.length??0}/></section>
    <section className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><Flag className="h-5 w-5"/><h2 className="text-lg font-bold">Denúncias</h2></div><div className="mt-4 space-y-3">{activeReports.length?activeReports.map((r:any)=><div key={r.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><b className="text-sm">{r.reason}</b><p className="mt-1 text-xs text-muted-foreground">{new Date(r.created_at).toLocaleString()}</p>{r.details&&<p className="mt-2 text-sm">{r.details}</p>}</div><div className="flex gap-2"><button onClick={()=>moderate.mutate({kind:"report",id:r.id,action:"resolve"})} className="rounded-lg bg-[#071426] px-3 py-2 text-xs font-black text-white">RESOLVER</button><button onClick={()=>moderate.mutate({kind:"report",id:r.id,action:"dismiss"})} className="rounded-lg border px-3 py-2 text-xs font-black">DESCARTAR</button></div></div></div>):<p className="text-sm text-muted-foreground">Nenhuma denúncia aberta.</p>}</div></section>

    <section className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5"/><h2 className="text-lg font-bold">Comentários recentes</h2></div><div className="mt-4 space-y-3">{data.comments?.length?data.comments.slice(0,80).map((c:any)=><div key={c.id} className="rounded-xl border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2 text-[10px] font-black"><span className="rounded-full bg-muted px-2 py-1">{c.status}</span>{c.anonymous&&<span className="rounded-full bg-muted px-2 py-1">ANÔNIMO</span>}</div><p className="mt-2 whitespace-pre-wrap break-words text-sm">{c.body}</p><p className="mt-2 text-[10px] text-muted-foreground">{new Date(c.created_at).toLocaleString()}</p></div><div className="flex flex-wrap gap-2">{c.status==="active"?<button title="Ocultar comentário" onClick={()=>moderate.mutate({kind:"comment",id:c.id,action:"hide"})} className="rounded-lg border p-2"><EyeOff className="h-4 w-4"/></button>:<button title="Restaurar comentário" onClick={()=>moderate.mutate({kind:"comment",id:c.id,action:"restore"})} className="rounded-lg border p-2"><Eye className="h-4 w-4"/></button>}</div></div></div>):<p className="text-sm text-muted-foreground">Nenhum comentário publicado.</p>}</div></section>

    <section className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><UserCog className="h-5 w-5"/><h2 className="text-lg font-bold">Perfis e funções acadêmicas</h2></div><p className="mt-1 text-xs text-muted-foreground">Defina quem aparece como Membro, Aluno, Professor ou Mentor. Esta função é visual dentro da Rede e não altera permissões administrativas do sistema.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{data.profiles?.length?data.profiles.map((p:any)=><div key={p.id} className="rounded-xl border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><b className="block truncate text-sm">{p.name}</b><p className="mt-1 truncate text-xs text-muted-foreground">{p.profession||"Profissão não informada"}</p></div><select value={p.display_role} disabled={setRole.isPending} onChange={e=>setRole.mutate({profileId:p.id,role:e.target.value as "member"|"student"|"professor"|"mentor"})} className="w-full rounded-lg border bg-background px-3 py-2 text-xs font-bold sm:w-auto"><option value="member">MEMBRO</option><option value="student">ALUNO</option><option value="professor">PROFESSOR</option><option value="mentor">MENTOR</option></select></div></div>):<p className="text-sm text-muted-foreground">Nenhum perfil acadêmico criado ainda.</p>}</div></section>
    <section className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5"/><h2 className="text-lg font-bold">Publicações recentes</h2></div><div className="mt-4 space-y-3">{data.posts?.map((p:any)=><div key={p.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2 text-[10px] font-black"><span className="rounded-full bg-muted px-2 py-1">{p.post_type}</span><span className="rounded-full bg-muted px-2 py-1">{p.status}</span>{p.anonymous&&<span className="rounded-full bg-muted px-2 py-1">ANÔNIMO</span>}{p.is_pinned&&<span className="rounded-full bg-[#071426] px-2 py-1 text-white">FIXADO</span>}</div><p className="mt-2 line-clamp-4 whitespace-pre-wrap text-sm">{p.body}</p><p className="mt-2 text-[10px] text-muted-foreground">{new Date(p.created_at).toLocaleString()}</p></div><div className="flex flex-wrap gap-2">{p.status==="active"?<button title="Ocultar" onClick={()=>moderate.mutate({kind:"post",id:p.id,action:"hide"})} className="rounded-lg border p-2"><EyeOff className="h-4 w-4"/></button>:<button title="Restaurar" onClick={()=>moderate.mutate({kind:"post",id:p.id,action:"restore"})} className="rounded-lg border p-2"><Eye className="h-4 w-4"/></button>}{p.is_pinned?<button title="Desafixar" onClick={()=>moderate.mutate({kind:"post",id:p.id,action:"unpin"})} className="rounded-lg border p-2"><PinOff className="h-4 w-4"/></button>:<button title="Fixar" onClick={()=>moderate.mutate({kind:"post",id:p.id,action:"pin"})} className="rounded-lg border p-2"><Pin className="h-4 w-4"/></button>}</div></div></div>)}</div></section>
  </div>
}
function Stat({title,value}:{title:string;value:number}){return <div className="rounded-2xl border bg-card p-5"><p className="text-xs font-bold text-muted-foreground">{title}</p><p className="mt-2 text-3xl font-black">{value}</p></div>}
