import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { sellerAdminDashboard, sellerAdminMarkPayout, sellerAdminReviewApplication, sellerAdminSetSaleStatus } from "@/lib/seller.functions";

export const Route=createFileRoute("/_authenticated/admin/vendedores")({component:SellerAdmin});
function money(c:number,cur:string){return new Intl.NumberFormat(cur==="BRL"?"pt-BR":"pt-PT",{style:"currency",currency:cur}).format((c||0)/100)}
function SellerAdmin(){
 const load=useServerFn(sellerAdminDashboard),review=useServerFn(sellerAdminReviewApplication),setStatus=useServerFn(sellerAdminSetSaleStatus),pay=useServerFn(sellerAdminMarkPayout); const [data,setData]=useState<any>(null);
 async function refresh(){try{setData(await load({}))}catch(e:any){toast.error(e?.message||"Acesso negado")}}
 useEffect(()=>{refresh()},[]);
 async function reviewApp(id:string,action:"approve"|"reject"){try{const r:any=await review({data:{applicationId:id,action}});toast.success(action==="approve"?`Aprovado. Código ${r.referralCode||"criado"}.`:"Candidatura recusada.");await refresh()}catch(e:any){toast.error(e?.message||"Erro")}}
 async function sale(id:string,status:any){try{await setStatus({data:{saleId:id,status}});toast.success("Venda atualizada.");await refresh()}catch(e:any){toast.error(e?.message||"Erro")}}
 async function payout(seller:any,currency:"EUR"|"BRL"){const ref=window.prompt("Informe a referência da transferência/comprovante:");if(!ref)return;try{const r:any=await pay({data:{sellerUserId:seller.user_id,currency,paymentReference:ref}});toast.success(`Repasse registrado: ${money(r.amountCents,currency)}`);await refresh()}catch(e:any){toast.error(e?.message||"Erro")}}
 if(!data)return <main className="mx-auto max-w-6xl p-6"><div className="s8-card">Carregando Rede Comercial...</div></main>;
 return <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><p className="text-xs font-black uppercase tracking-[.16em] text-primary">Administração LDR</p><h1 className="mt-1 font-serif text-3xl">Rede Comercial — Vendedores</h1>
 <section className="mt-7 s8-card"><h2 className="font-serif text-2xl">Candidaturas</h2><div className="mt-4 space-y-3">{data.applications.filter((a:any)=>a.status==="pending").length===0?<p className="text-sm text-muted-foreground">Nenhuma candidatura pendente.</p>:data.applications.filter((a:any)=>a.status==="pending").map((a:any)=><div key={a.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-4"><div><strong>{a.full_name}</strong><p className="text-sm">{a.email} · {a.phone||"sem telefone"}</p><p className="text-sm text-muted-foreground">{a.country} · prefere {a.preferred_currency}</p></div><div className="flex gap-2"><button onClick={()=>reviewApp(a.id,"approve")} className="rounded-lg bg-primary px-4 py-2 text-sm font-bold text-primary-foreground">Aprovar</button><button onClick={()=>reviewApp(a.id,"reject")} className="rounded-lg border px-4 py-2 text-sm font-bold">Recusar</button></div></div></div>)}</div></section>
 <section className="mt-7 s8-card"><h2 className="font-serif text-2xl">Vendedores ativos</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{data.sellers.map((s:any)=><div key={s.user_id} className="rounded-xl border p-4"><strong>{s.full_name}</strong><p className="text-sm text-muted-foreground">{s.email} · {s.referral_code}</p><div className="mt-3 flex gap-2"><button onClick={()=>payout(s,"EUR")} className="rounded-lg border px-3 py-2 text-xs font-bold">Registrar repasse EUR</button><button onClick={()=>payout(s,"BRL")} className="rounded-lg border px-3 py-2 text-xs font-bold">Registrar repasse BRL</button></div></div>)}</div></section>
 <section className="mt-7 s8-card"><h2 className="font-serif text-2xl">Vendas recentes</h2><div className="mt-4 space-y-3">{data.sales.map((s:any)=><div key={s.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-4"><div><strong>{s.product_name}</strong><p className="text-sm">Cliente: {s.customer_name}</p><p className="text-xs uppercase text-muted-foreground">{s.status}</p></div><div className="text-right"><strong>{money(s.amount_cents,s.currency)}</strong><p className="text-sm text-primary">Comissão {money(s.commission_cents,s.currency)}</p></div></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>sale(s.id,"confirmed")} className="rounded-lg border px-3 py-2 text-xs font-bold">Confirmar pagamento</button><button onClick={()=>sale(s.id,"available")} className="rounded-lg bg-primary px-3 py-2 text-xs font-bold text-primary-foreground">Liberar comissão</button><button onClick={()=>sale(s.id,"rejected")} className="rounded-lg border px-3 py-2 text-xs font-bold">Recusar</button><button onClick={()=>sale(s.id,"refunded")} className="rounded-lg border px-3 py-2 text-xs font-bold">Reembolso</button></div></div>)}</div></section>
 </main>
}
