import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Eye, EyeOff, FileText, Flag, ImageIcon, Pin, PinOff, ShieldCheck, UserCog } from "lucide-react";
import { academicAdminSnapshot, academicModerate, academicSetProfileRole } from "@/lib/academic-network.functions";
import { academicAdminV2Snapshot, academicModerateV2 } from "@/lib/academic-admin-v2.functions";
import { useAccess } from "@/lib/central-data";
import { AcademicChallengesAdmin } from "@/components/academic-challenges-admin";
import { AcademicEditorialAdminV3 } from "@/components/academic-editorial-admin-v3";

export const Route=createFileRoute("/_authenticated/admin/rede-academica")({component:AcademicNetworkAdmin});

function AcademicNetworkAdmin(){
  const access=useAccess(); const qc=useQueryClient();
  const snapshot=useServerFn(academicAdminSnapshot), moderateFn=useServerFn(academicModerate), setRoleFn=useServerFn(academicSetProfileRole), v2Fn=useServerFn(academicAdminV2Snapshot), moderateV2Fn=useServerFn(academicModerateV2);
  const enabled=access.data?.authorized===true&&access.data.role==="superadmin";
  const {data,isLoading}=useQuery({queryKey:["academic-network-admin"],queryFn:()=>snapshot({}),enabled});
  const {data:v2,isLoading:isV2Loading}=useQuery({queryKey:["academic-network-admin-v2"],queryFn:()=>v2Fn(),enabled});
  const moderate=useMutation({mutationFn:(x:{kind:"post"|"comment"|"report";id:string;action:"hide"|"restore"|"pin"|"unpin"|"resolve"|"dismiss"})=>moderateFn({data:x}),onSuccess:()=>{qc.invalidateQueries({queryKey:["academic-network-admin"]});qc.invalidateQueries({queryKey:["academic-network-admin-v2"]})}});
  const moderateV2=useMutation({mutationFn:(x:{kind:"article"|"mediaPost";id:string;action:"hide"|"restore"})=>moderateV2Fn({data:x}),onSuccess:()=>{qc.invalidateQueries({queryKey:["academic-network-admin"]});qc.invalidateQueries({queryKey:["academic-network-admin-v2"]})}});
  const setRole=useMutation({mutationFn:(x:{profileId:string;role:"member"|"student"|"professor"|"mentor"})=>setRoleFn({data:x}),onSuccess:()=>qc.invalidateQueries({queryKey:["academic-network-admin"]})});
  if(access.isLoading)return <div className="s8-card mx-auto max-w-md text-center">Carregando…</div>;
  if(!enabled)return <div className="s8-card mx-auto max-w-md text-center">Acesso restrito ao Master.</div>;
  if(isLoading||!data||isV2Loading)return <div className="s8-card mx-auto max-w-md text-center">Carregando Rede Acadêmica…</div>;
  const activeReports=(data.reports??[]).filter((r:any)=>r.status==="new"||r.status==="reviewing");
  const articleReports=(v2?.reports??[]).filter((r:any)=>r.article_id&&(r.status==="new"||r.status==="reviewing"));
  return <div className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6"><header><p className="text-xs font-black tracking-[.18em] text-muted-foreground">PAINEL MASTER</p><h1 className="mt-1 text-3xl font-bold">Rede Acadêmica</h1><p className="mt-2 text-sm text-muted-foreground">Moderação de publicações, comentários, artigos, fotos, perfis e denúncias. O conteúdo do Diário privado não é exibido aqui.</p></header>
    <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6"><Stat title="Publicações" value={data.posts?.length??0}/><Stat title="Comentários" value={data.comments?.length??0}/><Stat title="Artigos" value={v2?.articles?.length??0}/><Stat title="Fotos" value={v2?.media?.length??0}/><Stat title="Denúncias abertas" value={activeReports.length+articleReports.length}/><Stat title="Perfis acadêmicos" value={data.profiles?.length??0}/></section>
    <section className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><Flag className="h-5 w-5"/><h2 className="text-lg font-bold">Denúncias</h2></div><div className="mt-4 space-y-3">{[...activeReports,...articleReports].length?[...activeReports,...articleReports].map((r:any)=><div key={r.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex gap-2"><b className="text-sm">{r.reason}</b>{r.article_id&&<span className="rounded-full bg-muted px-2 py-0.5 text-[10px] font-black">ARTIGO</span>}</div><p className="mt-1 text-xs text-muted-foreground">{new Date(r.created_at).toLocaleString()}</p>{r.details&&<p className="mt-2 text-sm">{r.details}</p>}</div><div className="flex gap-2"><button onClick={()=>moderate.mutate({kind:"report",id:r.id,action:"resolve"})} className="min-h-10 rounded-lg bg-[#071426] px-3 py-2 text-xs font-black text-white">RESOLVER</button><button onClick={()=>moderate.mutate({kind:"report",id:r.id,action:"dismiss"})} className="min-h-10 rounded-lg border px-3 py-2 text-xs font-black">DESCARTAR</button></div></div></div>):<p className="text-sm text-muted-foreground">Nenhuma denúncia aberta.</p>}</div></section>
    <section className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><FileText className="h-5 w-5"/><h2 className="text-lg font-bold">Artigos</h2></div><div className="mt-4 space-y-3">{v2?.articles?.length?v2.articles.map((a:any)=><div key={a.id} className="rounded-xl border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2 text-[10px] font-black"><span className="rounded-full bg-muted px-2 py-1">{a.status}</span>{a.category&&<span className="rounded-full bg-muted px-2 py-1">{a.category}</span>}</div><b className="mt-2 block text-sm">{a.title}</b><p className="mt-1 line-clamp-2 text-xs text-muted-foreground">{a.summary}</p><p className="mt-2 text-[10px] text-muted-foreground">{a.authorName} · {new Date(a.created_at).toLocaleString()}</p></div>{a.status==="active"?<button title="Ocultar artigo" onClick={()=>moderateV2.mutate({kind:"article",id:a.id,action:"hide"})} className="min-h-10 min-w-10 rounded-lg border p-2"><EyeOff className="h-4 w-4"/></button>:a.status==="hidden"?<button title="Restaurar artigo" onClick={()=>moderateV2.mutate({kind:"article",id:a.id,action:"restore"})} className="min-h-10 min-w-10 rounded-lg border p-2"><Eye className="h-4 w-4"/></button>:null}</div></div>):<p className="text-sm text-muted-foreground">Nenhum artigo publicado.</p>}</div></section>
    <section className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><ImageIcon className="h-5 w-5"/><h2 className="text-lg font-bold">Fotos publicadas</h2></div><p className="mt-1 text-xs text-muted-foreground">A moderação preserva o arquivo e oculta/restaura a publicação vinculada.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{v2?.media?.length?v2.media.map((m:any)=><div key={m.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex gap-2 text-[10px] font-black"><span className="rounded-full bg-muted px-2 py-1">{m.mime_type}</span><span className="rounded-full bg-muted px-2 py-1">{m.post?.status||"—"}</span></div><p className="mt-2 line-clamp-2 text-sm">{m.alt_text||m.post?.body||"Imagem da Rede Acadêmica"}</p><p className="mt-2 text-[10px] text-muted-foreground">{new Date(m.created_at).toLocaleString()}</p></div>{m.post?.status==="active"?<button title="Ocultar publicação da foto" onClick={()=>moderateV2.mutate({kind:"mediaPost",id:m.id,action:"hide"})} className="min-h-10 min-w-10 rounded-lg border p-2"><EyeOff className="h-4 w-4"/></button>:m.post?.status==="hidden"?<button title="Restaurar publicação da foto" onClick={()=>moderateV2.mutate({kind:"mediaPost",id:m.id,action:"restore"})} className="min-h-10 min-w-10 rounded-lg border p-2"><Eye className="h-4 w-4"/></button>:null}</div></div>):<p className="text-sm text-muted-foreground">Nenhuma foto publicada.</p>}</div></section>
    <section className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5"/><h2 className="text-lg font-bold">Comentários recentes</h2></div><div className="mt-4 space-y-3">{data.comments?.length?data.comments.slice(0,80).map((c:any)=><div key={c.id} className="rounded-xl border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2 text-[10px] font-black"><span className="rounded-full bg-muted px-2 py-1">{c.status}</span>{c.anonymous&&<span className="rounded-full bg-muted px-2 py-1">ANÔNIMO</span>}</div><p className="mt-2 whitespace-pre-wrap break-words text-sm">{c.body}</p><p className="mt-2 text-[10px] text-muted-foreground">{new Date(c.created_at).toLocaleString()}</p></div>{c.status==="active"?<button title="Ocultar comentário" onClick={()=>moderate.mutate({kind:"comment",id:c.id,action:"hide"})} className="min-h-10 min-w-10 rounded-lg border p-2"><EyeOff className="h-4 w-4"/></button>:<button title="Restaurar comentário" onClick={()=>moderate.mutate({kind:"comment",id:c.id,action:"restore"})} className="min-h-10 min-w-10 rounded-lg border p-2"><Eye className="h-4 w-4"/></button>}</div></div>):<p className="text-sm text-muted-foreground">Nenhum comentário publicado.</p>}</div></section>
    <section className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><UserCog className="h-5 w-5"/><h2 className="text-lg font-bold">Perfis e funções acadêmicas</h2></div><p className="mt-1 text-xs text-muted-foreground">Revisão de perfil e função visual. Isso não altera permissões administrativas.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{data.profiles?.length?data.profiles.map((p:any)=><div key={p.id} className="rounded-xl border p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><b className="block truncate text-sm">{p.name}</b><p className="mt-1 truncate text-xs text-muted-foreground">{p.profession||"Profissão não informada"}</p></div><select aria-label={`Função acadêmica de ${p.name}`} value={p.display_role} disabled={setRole.isPending} onChange={e=>setRole.mutate({profileId:p.id,role:e.target.value as "member"|"student"|"professor"|"mentor"})} className="min-h-10 w-full rounded-lg border bg-background px-3 py-2 text-xs font-bold sm:w-auto"><option value="member">MEMBRO</option><option value="student">ALUNO</option><option value="professor">PROFESSOR</option><option value="mentor">MENTOR</option></select></div></div>):<p className="text-sm text-muted-foreground">Nenhum perfil acadêmico criado ainda.</p>}</div></section>
    <AcademicEditorialAdminV3/>
    <AcademicChallengesAdmin/>
    <section className="rounded-2xl border bg-card p-5"><div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5"/><h2 className="text-lg font-bold">Publicações recentes</h2></div><div className="mt-4 space-y-3">{data.posts?.map((p:any)=><div key={p.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><div className="flex flex-wrap gap-2 text-[10px] font-black"><span className="rounded-full bg-muted px-2 py-1">{p.post_type}</span><span className="rounded-full bg-muted px-2 py-1">{p.status}</span>{p.anonymous&&<span className="rounded-full bg-muted px-2 py-1">ANÔNIMO</span>}{p.is_pinned&&<span className="rounded-full bg-[#071426] px-2 py-1 text-white">FIXADO</span>}</div><p className="mt-2 line-clamp-4 whitespace-pre-wrap text-sm">{p.body}</p><p className="mt-2 text-[10px] text-muted-foreground">{new Date(p.created_at).toLocaleString()}</p></div><div className="flex flex-wrap gap-2">{p.status==="active"?<button title="Ocultar" onClick={()=>moderate.mutate({kind:"post",id:p.id,action:"hide"})} className="min-h-10 min-w-10 rounded-lg border p-2"><EyeOff className="h-4 w-4"/></button>:<button title="Restaurar" onClick={()=>moderate.mutate({kind:"post",id:p.id,action:"restore"})} className="min-h-10 min-w-10 rounded-lg border p-2"><Eye className="h-4 w-4"/></button>}{p.is_pinned?<button title="Desafixar" onClick={()=>moderate.mutate({kind:"post",id:p.id,action:"unpin"})} className="min-h-10 min-w-10 rounded-lg border p-2"><PinOff className="h-4 w-4"/></button>:<button title="Fixar" onClick={()=>moderate.mutate({kind:"post",id:p.id,action:"pin"})} className="min-h-10 min-w-10 rounded-lg border p-2"><Pin className="h-4 w-4"/></button>}</div></div></div>)}</div></section>
  </div>
}
function Stat({title,value}:{title:string;value:number}){return <div className="rounded-2xl border bg-card p-5"><p className="text-xs font-bold text-muted-foreground">{title}</p><p className="mt-2 text-3xl font-black">{value}</p></div>}
