import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { listEcosystemContacts, updateEcosystemContact } from "@/lib/ecosystem-support.functions";

export const Route=createFileRoute("/_authenticated/admin/contatos")({component:ContactsAdmin});
function dueLabel(value:string){const ms=new Date(value).getTime()-Date.now(),d=Math.ceil(ms/86400000);if(d<0)return "Prazo ultrapassado";if(d===0)return "Vence hoje";return `${d} dia${d===1?"":"s"} restante${d===1?"":"s"}`;}
function ContactsAdmin(){
 const qc=useQueryClient(),list=useServerFn(listEcosystemContacts),update=useServerFn(updateEcosystemContact);
 const q=useQuery({queryKey:["ecosystem-contacts"],queryFn:()=>list({}),refetchInterval:60000});
 const m=useMutation({mutationFn:(x:{id:string;status:string;priority:string})=>update({data:x}),onSuccess:()=>qc.invalidateQueries({queryKey:["ecosystem-contacts"]})});
 return <div className="space-y-5"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#C7A33B]">Ecossistema LDR</p><h1 className="font-serif text-3xl text-[#0B1F3A]">Contatos e solicitações</h1><p className="mt-2 text-sm text-slate-600">Central privada de solicitações recebidas pelo Ecossistema.</p></div>
 {q.isLoading?<p>Carregando…</p>:q.isError?<p role="alert">Não foi possível carregar os contatos.</p>:
 <div className="grid gap-4">{(q.data??[]).map((c:any)=><article key={c.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black text-[#C7A33B]">{c.protocol}</p><h2 className="mt-1 font-serif text-xl text-[#0B1F3A]">{c.subject}</h2>{c.wants_luciano&&<span className="mt-2 inline-block rounded-full bg-amber-100 px-3 py-1 text-xs font-bold">Destino solicitado: Luciano</span>}</div><strong className={new Date(c.response_due_at).getTime()<Date.now()?"text-red-700":"text-[#0B1F3A]"}>{dueLabel(c.response_due_at)}</strong></div>
 <div className="mt-4 grid gap-2 text-sm"><p><strong>{c.name}</strong> · {c.email}{c.phone?` · ${c.phone}`:""}</p><p className="whitespace-pre-wrap rounded-xl bg-slate-50 p-4">{c.message}</p><p className="text-xs text-slate-500">Origem: {c.source_project} · {new Date(c.created_at).toLocaleString("pt-BR")}</p></div>
 <div className="mt-4 flex flex-wrap gap-2"><select value={c.status} onChange={e=>m.mutate({id:c.id,status:e.target.value,priority:c.priority})} className="rounded-lg border px-3 py-2"><option value="novo">Novo</option><option value="em_atendimento">Em atendimento</option><option value="aguardando_cliente">Aguardando cliente</option><option value="respondido">Respondido</option><option value="resolvido">Resolvido</option></select><select value={c.priority} onChange={e=>m.mutate({id:c.id,status:c.status,priority:e.target.value})} className="rounded-lg border px-3 py-2"><option value="normal">Prioridade normal</option><option value="alta">Prioridade alta</option></select><a href={`mailto:${encodeURIComponent(c.email)}?subject=${encodeURIComponent(`Re: ${c.subject} — ${c.protocol}`)}`} className="rounded-lg bg-[#0B1F3A] px-4 py-2 font-bold text-white">Responder por e-mail</a></div></article>)}</div>}</div>;
}