import { Link, createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { professionalCatalogAdmin, professionalCatalogAdminReview } from "@/lib/professional-catalog-admin.functions";

export const Route=createFileRoute("/_authenticated/painel-profissional/rede-servicos")({component:ServiceReview});
type Row=Record<string,any>;
function money(c:number,currency:string){return new Intl.NumberFormat(currency==="BRL"?"pt-BR":"pt-PT",{style:"currency",currency}).format((c||0)/100)}
function ServiceReview(){const load=useServerFn(professionalCatalogAdmin);const review=useServerFn(professionalCatalogAdminReview);const [data,setData]=useState<any>(null);const [busy,setBusy]=useState<string|null>(null);const refresh=async()=>setData(await load());useEffect(()=>{void refresh()},[]);if(!data)return <p className="text-sm text-muted-foreground">Carregando serviços da Rede…</p>;const rows=(data.services??[]) as Row[];return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-primary">Rede de Profissionais LDR</p><h1 className="mt-1 font-serif text-4xl">Revisão de serviços</h1><p className="mt-2 text-sm text-muted-foreground">Aprove ou rejeite serviços do catálogo LDR que exigem validação antes do checkout.</p></div><Link to="/painel-profissional/rede-profissionais" className="rounded-xl border px-4 py-2 text-sm font-bold">Voltar à Rede</Link></div><section className="rounded-3xl border bg-card p-6"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr className="border-b"><th className="py-2">Profissional</th><th>Serviço</th><th>País</th><th>Modalidade</th><th>Valor</th><th>Status</th><th>Ações</th></tr></thead><tbody>{rows.map((s:Row)=>{const p=Array.isArray(s.professional_profiles)?s.professional_profiles[0]:s.professional_profiles;return <tr key={s.id} className="border-b last:border-0"><td className="py-3"><strong>{p?.display_name||"—"}</strong><p className="text-xs text-muted-foreground">{p?.professional_title||""}</p></td><td>{s.name}</td><td>{p?.country_code||"—"}</td><td>{s.modality}</td><td>{money(s.price_cents,s.currency)}</td><td><span className="rounded-full bg-muted px-2 py-1 text-xs font-bold">{s.approval_status}</span></td><td><div className="flex gap-2"><button disabled={busy===s.id} onClick={async()=>{setBusy(s.id);try{await review({data:{serviceId:s.id,action:"approve"}});toast.success("Serviço aprovado.");await refresh()}catch(e){toast.error(e instanceof Error?e.message:"Erro")}finally{setBusy(null)}}} className="rounded-lg bg-primary px-3 py-2 text-xs font-black text-primary-foreground">APROVAR</button><button disabled={busy===s.id} onClick={async()=>{setBusy(s.id);try{await review({data:{serviceId:s.id,action:"reject"}});toast.success("Serviço rejeitado.");await refresh()}catch(e){toast.error(e instanceof Error?e.message:"Erro")}finally{setBusy(null)}}} className="rounded-lg border px-3 py-2 text-xs font-bold">REJEITAR</button></div></td></tr>})}</tbody></table></div>{rows.length===0?<p className="mt-4 text-sm text-muted-foreground">Nenhum serviço do catálogo selecionado ainda.</p>:null}</section></div>}
