import { Link, createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { professionalPayoutAdmin, professionalPayoutDocumentUrl, professionalPayoutMarkPaid, professionalPayoutReviewDocument, professionalPayoutSetProcessing } from "@/lib/professional-payout-admin.functions";

export const Route = createFileRoute("/_authenticated/painel-profissional/rede-profissionais-repasses")({ component: PayoutAdmin });
type Row = Record<string, any>;
function money(c:number,currency:string){return new Intl.NumberFormat(currency==="BRL"?"pt-BR":"pt-PT",{style:"currency",currency}).format((Number(c)||0)/100)}
const STATUS:Record<string,string>={awaiting_documentation:"AGUARDANDO DOCUMENTAÇÃO",documentation_received:"DOCUMENTAÇÃO RECEBIDA",in_review:"EM ANÁLISE",approved_for_payout:"APROVADO PARA REPASSE",processing:"PROCESSANDO",paid:"PAGO",adjustment_required:"AJUSTE NECESSÁRIO"};
function PayoutAdmin(){
 const load=useServerFn(professionalPayoutAdmin);const review=useServerFn(professionalPayoutReviewDocument);const docUrl=useServerFn(professionalPayoutDocumentUrl);const processing=useServerFn(professionalPayoutSetProcessing);const markPaid=useServerFn(professionalPayoutMarkPaid);
 const [data,setData]=useState<any>(null);const [busy,setBusy]=useState(false);const [reference,setReference]=useState<Record<string,string>>({});const [method,setMethod]=useState<Record<string,string>>({});
 const refresh=async()=>setData(await load());useEffect(()=>{void refresh()},[]);
 const docsByPayout=useMemo(()=>{const m=new Map<string,Row[]>();for(const d of data?.documents??[]){const a=m.get(d.payout_id)||[];a.push(d);m.set(d.payout_id,a)}return m},[data]);
 async function openDoc(id:string){try{const r=await docUrl({data:{documentId:id}});window.open(r.url,"_blank","noopener,noreferrer")}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível abrir o documento.")}}
 async function decide(id:string,decision:"approve"|"reject"){let rejectionReason:string|undefined;if(decision==="reject"){rejectionReason=window.prompt("Motivo da rejeição:")||undefined;if(!rejectionReason)return}setBusy(true);try{await review({data:{documentId:id,decision,rejectionReason}});toast.success(decision==="approve"?"Documento aprovado.":"Documento rejeitado.");await refresh()}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível revisar.")}finally{setBusy(false)}}
 async function startProcessing(id:string){setBusy(true);try{await processing({data:{payoutId:id}});toast.success("Repasse enviado pelo Stripe Connect e registrado no painel.");await refresh()}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível processar o repasse.")}finally{setBusy(false)}}
 async function finish(p:Row){const ref=(reference[p.id]||"").trim();if(!ref){toast.error("Informe a referência do pagamento.");return}setBusy(true);try{await markPaid({data:{payoutId:p.id,paymentReference:ref,paymentMethod:(method[p.id]||"manual")}});toast.success("Repasse concluído e saldo baixado.");await refresh()}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível concluir o repasse.")}finally{setBusy(false)}}
 if(!data)return <p className="text-sm text-muted-foreground">Carregando repasses…</p>;
 return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-primary">Rede de Profissionais LDR</p><h1 className="mt-1 font-serif text-4xl">Repasses e documentos fiscais</h1><p className="mt-2 text-sm text-muted-foreground">Revisão documental, aprovação e envio seguro do repasse mensal via Stripe Connect. A LDR mantém a comissão configurada e transfere o valor líquido ao profissional.</p></div><Link to="/painel-profissional/rede-profissionais" className="rounded-xl border px-4 py-2 text-sm font-bold">Voltar à Rede</Link></div>
 <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat label="AGUARDANDO DOCUMENTAÇÃO" value={(data.payouts??[]).filter((x:Row)=>x.status==="awaiting_documentation").length}/><Stat label="EM ANÁLISE" value={(data.payouts??[]).filter((x:Row)=>["documentation_received","in_review"].includes(x.status)).length}/><Stat label="APROVADOS/PROCESSANDO" value={(data.payouts??[]).filter((x:Row)=>["approved_for_payout","processing"].includes(x.status)).length}/><Stat label="PAGOS" value={(data.payouts??[]).filter((x:Row)=>x.status==="paid").length}/></div>
 <div className="space-y-4">{(data.payouts??[]).map((p:Row)=>{const docs=docsByPayout.get(p.id)||[];const bal=(data.balances??[]).find((b:Row)=>b.professional_account_id===p.professional_account_id&&b.currency===p.currency);return <section key={p.id} className="rounded-3xl border bg-card p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div className="min-w-0"><h2 className="break-words font-serif text-2xl">{p.professional?.display_name||"Profissional"}</h2><p className="mt-1 text-sm text-muted-foreground">{p.period_start} a {p.period_end} · {p.currency}</p></div><span className="rounded-full bg-primary/10 px-3 py-1.5 text-xs font-black text-primary">{STATUS[p.status]||p.status}</span></div>
 <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat label="VALOR BRUTO" value={money(p.gross_cents,p.currency)}/><Stat label="COMISSÃO LDR" value={`-${money(p.platform_fee_cents,p.currency)}`}/><Stat label="LÍQUIDO DO REPASSE" value={money(p.net_cents,p.currency)}/><Stat label="SALDO DISPONÍVEL" value={money(bal?.available_cents||0,p.currency)}/></div>
 <div className="mt-5"><h3 className="font-bold">Documentação fiscal</h3>{docs.length===0?<p className="mt-2 rounded-xl bg-muted/50 p-3 text-sm text-muted-foreground">Nenhum documento enviado ainda.</p>:<div className="mt-3 space-y-2">{docs.map(d=><div key={d.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border p-3"><div className="min-w-0"><p className="break-words font-bold">{d.original_filename||d.document_type}</p><p className="text-xs text-muted-foreground">{d.document_type} · enviado em {new Date(d.uploaded_at).toLocaleString()} · {d.status}</p>{d.rejection_reason&&<p className="mt-1 text-xs text-destructive">{d.rejection_reason}</p>}</div><div className="flex flex-wrap gap-2"><button onClick={()=>openDoc(d.id)} className="rounded-lg border px-3 py-2 text-xs font-bold">ABRIR</button>{d.status!=="approved"&&<button disabled={busy} onClick={()=>decide(d.id,"approve")} className="rounded-lg bg-primary px-3 py-2 text-xs font-black text-primary-foreground">APROVAR</button>}{d.status!=="rejected"&&<button disabled={busy} onClick={()=>decide(d.id,"reject")} className="rounded-lg border px-3 py-2 text-xs font-bold">REJEITAR</button>}</div></div>)}</div>}</div>
 <div className="mt-5 border-t pt-5">{p.status==="approved_for_payout"&&<button disabled={busy} onClick={()=>startProcessing(p.id)} className="rounded-xl bg-primary px-4 py-3 text-sm font-black text-primary-foreground">ENVIAR VIA STRIPE CONNECT</button>}{p.status==="processing"&&<div className="space-y-3"><p className="rounded-xl bg-muted/50 p-3 text-sm text-muted-foreground">Se uma transferência Stripe já tiver sido criada, tente novamente o processamento antes de usar a baixa manual. A baixa manual abaixo fica disponível apenas para conciliação excepcional.</p><div className="grid gap-3 sm:grid-cols-[1fr_180px_auto]"><input value={reference[p.id]||""} onChange={e=>setReference({...reference,[p.id]:e.target.value})} placeholder="Referência/comprovante do pagamento" className="rounded-xl border bg-background px-3 py-3 text-sm"/><select value={method[p.id]||"manual"} onChange={e=>setMethod({...method,[p.id]:e.target.value})} className="rounded-xl border bg-background px-3 py-3 text-sm"><option value="manual">Transferência manual</option><option value="bank_transfer">Transferência bancária</option><option value="pix">PIX</option><option value="sepa">SEPA</option><option value="other">Outro</option></select><button disabled={busy} onClick={()=>finish(p)} className="rounded-xl bg-primary px-4 py-3 text-sm font-black text-primary-foreground">MARCAR COMO PAGO</button></div></div>}{p.status==="paid"&&<div className="rounded-xl bg-muted/50 p-4 text-sm"><strong>Pago:</strong> {p.paid_at?new Date(p.paid_at).toLocaleString():"—"} · {p.payment_method||"—"} · referência {p.payment_reference||"—"}</div>}</div></section>})}</div></div>;
}
function Stat({label,value}:{label:string;value:any}){return <div className="min-w-0 rounded-2xl border bg-card p-4"><p className="break-words text-xs font-black uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-2 break-words text-xl font-black text-primary">{value}</p></div>}
