import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { BookOpen, CalendarDays, GraduationCap, Megaphone, Plus } from "lucide-react";
import { useState } from "react";
import { professionalAddTrainingItem, professionalCreateTraining, professionalLearningHub } from "@/lib/learning.functions";

export const Route = createFileRoute("/_authenticated/painel-profissional/treinamentos")({ component: TrainingManager });

type Kind = "module" | "material" | "live" | "announcement";

function TrainingManager() {
  const load = useServerFn(professionalLearningHub);
  const createTraining = useServerFn(professionalCreateTraining);
  const addItem = useServerFn(professionalAddTrainingItem);
  const qc = useQueryClient();
  const { data, isLoading } = useQuery({ queryKey: ["professional-learning-hub"], queryFn: () => load({}) });
  const [title, setTitle] = useState(""); const [slug, setSlug] = useState(""); const [description, setDescription] = useState("");
  const [trainingId, setTrainingId] = useState(""); const [kind, setKind] = useState<Kind>("module"); const [itemTitle, setItemTitle] = useState(""); const [itemDescription, setItemDescription] = useState(""); const [url, setUrl] = useState(""); const [startsAt, setStartsAt] = useState(""); const [meetingUrl, setMeetingUrl] = useState("");

  const refresh = () => qc.invalidateQueries({ queryKey: ["professional-learning-hub"] });
  const create = useMutation({ mutationFn: () => createTraining({ data: { title, slug, description } }), onSuccess: async () => { setTitle(""); setSlug(""); setDescription(""); await refresh(); } });
  const publish = useMutation({ mutationFn: () => addItem({ data: { kind, trainingId, title: itemTitle, description: itemDescription, url: url || null, body: kind === "announcement" ? itemDescription : null, startsAt: kind === "live" && startsAt ? new Date(startsAt).toISOString() : null, meetingUrl: meetingUrl || null } }), onSuccess: async () => { setItemTitle(""); setItemDescription(""); setUrl(""); setStartsAt(""); setMeetingUrl(""); await refresh(); } });

  if (isLoading) return <p className="text-sm text-muted-foreground">Carregando treinamentos…</p>;
  const trainings = data?.trainings ?? [];
  const selected = trainings.find((t:any)=>t.id===trainingId);

  return <div className="space-y-6"><section className="s8-card"><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">Conteúdo educacional</p><h1 className="mt-1 flex items-center gap-2 font-serif text-3xl"><GraduationCap className="h-7 w-7"/> Treinamentos / Conteúdos</h1><p className="mt-2 text-sm text-muted-foreground">Estrutura pronta para criar treinamentos, módulos, materiais, avisos e encontros ao vivo que aparecem automaticamente para clientes autorizados.</p></section>

  <section className="grid gap-5 lg:grid-cols-2"><div className="s8-card"><h2 className="font-serif text-xl">Novo treinamento</h2><div className="mt-4 grid gap-3"><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Nome do treinamento" className="rounded-lg border border-border bg-background p-3 text-sm"/><input value={slug} onChange={e=>setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]+/g,"-"))} placeholder="identificador-do-treinamento" className="rounded-lg border border-border bg-background p-3 text-sm"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Descrição" className="min-h-24 rounded-lg border border-border bg-background p-3 text-sm"/><button disabled={!title.trim()||!slug.trim()||create.isPending} onClick={()=>create.mutate()} className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-3 text-sm font-bold text-primary-foreground disabled:opacity-50"><Plus className="h-4 w-4"/> Criar treinamento</button></div></div>

  <div className="s8-card"><h2 className="font-serif text-xl">Publicar conteúdo</h2><div className="mt-4 grid gap-3"><select value={trainingId} onChange={e=>setTrainingId(e.target.value)} className="rounded-lg border border-border bg-background p-3 text-sm"><option value="">Selecione o treinamento</option>{trainings.map((t:any)=><option key={t.id} value={t.id}>{t.title}</option>)}</select><select value={kind} onChange={e=>setKind(e.target.value as Kind)} className="rounded-lg border border-border bg-background p-3 text-sm"><option value="module">Módulo / matéria</option><option value="material">Material / link</option><option value="live">Encontro ao vivo</option><option value="announcement">Aviso</option></select><input value={itemTitle} onChange={e=>setItemTitle(e.target.value)} placeholder="Título" className="rounded-lg border border-border bg-background p-3 text-sm"/><textarea value={itemDescription} onChange={e=>setItemDescription(e.target.value)} placeholder={kind === "announcement" ? "Texto do aviso" : "Descrição"} className="min-h-20 rounded-lg border border-border bg-background p-3 text-sm"/>{kind === "material" ? <input value={url} onChange={e=>setUrl(e.target.value)} placeholder="Link do material" className="rounded-lg border border-border bg-background p-3 text-sm"/> : null}{kind === "live" ? <><input type="datetime-local" value={startsAt} onChange={e=>setStartsAt(e.target.value)} className="rounded-lg border border-border bg-background p-3 text-sm"/><input value={meetingUrl} onChange={e=>setMeetingUrl(e.target.value)} placeholder="Link do encontro" className="rounded-lg border border-border bg-background p-3 text-sm"/></> : null}<button disabled={!trainingId||!itemTitle.trim()||publish.isPending} onClick={()=>publish.mutate()} className="rounded-lg bg-primary px-4 py-3 text-sm font-bold text-primary-foreground disabled:opacity-50">Publicar</button></div></div></section>

  <section><h2 className="mb-3 font-serif text-2xl">Treinamentos cadastrados</h2>{trainings.length ? <div className="grid gap-4 lg:grid-cols-2">{trainings.map((t:any)=>{const modules=data?.modules.filter((x:any)=>x.training_id===t.id)??[];const materials=data?.materials.filter((x:any)=>x.training_id===t.id)??[];const sessions=data?.sessions.filter((x:any)=>x.training_id===t.id)??[];const announcements=data?.announcements.filter((x:any)=>x.training_id===t.id)??[];return <article key={t.id} className="s8-card"><div className="flex items-start justify-between gap-3"><div><h3 className="font-serif text-xl text-primary">{t.title}</h3><p className="mt-1 text-sm text-muted-foreground">{t.description || "Sem descrição"}</p></div><span className="rounded-full bg-accent px-3 py-1 text-xs font-bold">{t.status}</span></div><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><div className="rounded-lg bg-accent/50 p-3"><BookOpen className="mb-1 h-4 w-4"/> {modules.length} módulos · {materials.length} materiais</div><div className="rounded-lg bg-accent/50 p-3"><CalendarDays className="mb-1 h-4 w-4"/> {sessions.length} encontros</div><div className="rounded-lg bg-accent/50 p-3"><Megaphone className="mb-1 h-4 w-4"/> {announcements.length} avisos</div><div className="rounded-lg bg-accent/50 p-3">{(data?.enrollments.filter((x:any)=>x.training_id===t.id&&x.active)??[]).length} participantes</div></div></article>})}</div> : <div className="s8-card text-sm text-muted-foreground">Nenhum treinamento criado ainda. A estrutura já está pronta.</div>}</section>
  </div>;
}
