import { createFileRoute, Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { sellerDashboard, sellerRegisterSale } from "@/lib/seller.functions";

export const Route = createFileRoute("/_authenticated/vendedor")({ component: SellerDashboardPage });

const CATS=[
  ["digital","Produto digital"],["training","Treinamento"],["mentoring","Mentoria"],["career","Carreira"],["wellbeing","Bem-estar"],["marketing","Marketing / Site"],["recruitment","Recrutamento"],["business","Contrato empresarial"],["service","Outro serviço"]
] as const;

function money(cents:number,currency:string){return new Intl.NumberFormat(currency==="BRL"?"pt-BR":"pt-PT",{style:"currency",currency}).format((cents||0)/100)}

function SellerDashboardPage(){
  const load=useServerFn(sellerDashboard); const save=useServerFn(sellerRegisterSale);
  const [data,setData]=useState<any>(null); const [busy,setBusy]=useState(false);
  const [form,setForm]=useState({customerName:"",customerEmail:"",customerPhone:"",productName:"",productCategory:"service",amount:0,currency:"EUR",paymentReference:"",notes:""});
  async function refresh(){try{setData(await load({}));}catch(e:any){toast.error(e?.message||"Acesso de vendedor não encontrado.")}}
  useEffect(()=>{refresh()},[]);
  const totals=useMemo(()=>data?.totals||{},[data]);
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);try{await save({data:{...form,amount:Number(form.amount)}});toast.success("Venda registrada. Aguardando confirmação.");setForm({...form,customerName:"",customerEmail:"",customerPhone:"",productName:"",amount:0,paymentReference:"",notes:""});await refresh();}catch(e:any){toast.error(e?.message||"Não foi possível registrar a venda.")}finally{setBusy(false)}}
  if(!data)return <div className="mx-auto max-w-3xl p-6"><div className="s8-card">Carregando painel comercial...</div></div>;
  return <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.16em] text-primary">Rede Comercial LDR</p><h1 className="mt-1 font-serif text-3xl">Olá, {data.account.full_name}</h1><p className="mt-2 text-sm text-muted-foreground">Código: <strong>{data.account.referral_code}</strong></p></div><Link to="/para-vendedores" className="rounded-lg border px-4 py-2 text-sm font-bold">Ver página de vendas</Link></div>
  <section className="mt-7 grid gap-4 md:grid-cols-3">{["EUR","BRL"].map(cur=>totals[cur]?<div key={cur} className="s8-card"><p className="text-xs font-bold uppercase text-muted-foreground">{cur}</p><p className="mt-2 text-sm">Vendas: <strong>{money(totals[cur].sales,cur)}</strong></p><p className="text-sm">Comissão pendente: <strong>{money(totals[cur].pending,cur)}</strong></p><p className="text-sm">Disponível: <strong className="text-primary">{money(totals[cur].available,cur)}</strong></p><p className="text-sm">Já recebida: <strong>{money(totals[cur].paid,cur)}</strong></p></div>:null)}</section>
  <section className="mt-7 grid gap-6 lg:grid-cols-[1fr_1.2fr]"><div className="s8-card"><h2 className="font-serif text-2xl">Registrar nova venda</h2><p className="mt-2 text-xs leading-5 text-muted-foreground">A comissão fica pendente até a LDR confirmar o pagamento do cliente.</p><form onSubmit={submit} className="mt-5 space-y-3"><div><label className="s8-label">Cliente</label><input required className="s8-field" value={form.customerName} onChange={e=>setForm({...form,customerName:e.target.value})}/></div><div><label className="s8-label">E-mail do cliente</label><input type="email" className="s8-field" value={form.customerEmail} onChange={e=>setForm({...form,customerEmail:e.target.value})}/></div><div><label className="s8-label">Produto/serviço</label><input required className="s8-field" value={form.productName} onChange={e=>setForm({...form,productName:e.target.value})}/></div><div className="grid grid-cols-2 gap-3"><div><label className="s8-label">Categoria</label><select className="s8-field" value={form.productCategory} onChange={e=>setForm({...form,productCategory:e.target.value})}>{CATS.map(([v,l])=><option value={v} key={v}>{l} — {data.rates[v]}%</option>)}</select></div><div><label className="s8-label">Moeda</label><select className="s8-field" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}><option>EUR</option><option>BRL</option></select></div></div><div><label className="s8-label">Valor da venda</label><input required min="0.01" step="0.01" type="number" className="s8-field" value={form.amount||""} onChange={e=>setForm({...form,amount:Number(e.target.value)})}/></div><div><label className="s8-label">Referência do pagamento</label><input className="s8-field" placeholder="Ex.: Stripe, Pix, pedido ou comprovante" value={form.paymentReference} onChange={e=>setForm({...form,paymentReference:e.target.value})}/></div><button disabled={busy} className="w-full rounded-xl bg-primary px-5 py-3 font-bold text-primary-foreground disabled:opacity-60">{busy?"Registrando...":"Registrar venda"}</button></form></div>
  <div className="s8-card min-w-0"><h2 className="font-serif text-2xl">Minhas vendas</h2><div className="mt-4 space-y-3">{data.sales.length===0?<p className="text-sm text-muted-foreground">Nenhuma venda registrada ainda.</p>:data.sales.map((s:any)=><div key={s.id} className="rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-3"><div><strong>{s.product_name}</strong><p className="text-sm text-muted-foreground">{s.customer_name}</p></div><div className="text-right"><strong>{money(s.amount_cents,s.currency)}</strong><p className="text-sm text-primary">Comissão {s.commission_rate}%: {money(s.commission_cents,s.currency)}</p></div></div><p className="mt-2 text-xs uppercase tracking-wide text-muted-foreground">Status: {s.status}</p></div>)}</div></div></section>
  <section className="mt-7 s8-card"><h2 className="font-serif text-2xl">Pagamentos recebidos</h2><div className="mt-4 space-y-2">{data.payouts.length===0?<p className="text-sm text-muted-foreground">Nenhum repasse registrado ainda.</p>:data.payouts.map((p:any)=><div key={p.id} className="flex flex-wrap justify-between gap-3 border-b py-3 text-sm"><span>{p.period_start} a {p.period_end} · {p.payment_method||"transferência"}</span><strong>{money(p.amount_cents,p.currency)}</strong></div>)}</div></section>
  </main>
}
