import { BookOpen, GraduationCap, Library, Newspaper, Search, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { useI18n } from "@/lib/i18n";
import { PROFESSIONAL_FORMATIONS, pfText, type PFLocale } from "@/lib/professional-formations.catalog";

type L="pt"|"en"|"fr"|"es";
type Kind="all"|"psicanalise"|"negocios"|"carreira"|"rh"|"ia";
type Course={id:string;title:string;desc:string;meta:string;price:string;href:string;kind:Exclude<Kind,"all">;icon:string;accent:string};

const UI={
 pt:{brand:"LDR Academy",eyebrow:"BIBLIOTECA ACADÊMICA DIGITAL",hero:"Conhecimento organizado para o seu próximo passo.",sub:"Cursos, formações, livros e publicações em uma experiência inspirada em uma biblioteca universitária.",explore:"EXPLORAR A ACADEMY",library:"ENTRAR NA MINHA BIBLIOTECA",search:"Buscar curso ou formação…",all:"Todos",psy:"Psicanálise",business:"Negócios",career:"Carreira",rh:"RH",ai:"Inteligência Artificial",courses:"Cursos e Formações",coursesSub:"Escolha seu próximo aprendizado. Todos os principais cursos em uma única estante.",know:"CONHECER",free:"Comece gratuitamente",freeSub:"Conteúdos de entrada para começar agora.",start:"COMEÇAR GRÁTIS",editorial:"Banca Acadêmica",editorialSub:"Jornais, revistas e publicações especiais.",books:"Livraria LDR",booksSub:"Livros e eBooks para leitura no seu ritmo.",subscription:"Quer explorar vários conteúdos?",subscriptionText:"A assinatura mensal mantém acesso aos conteúdos digitais incluídos enquanto estiver ativa.",subscribe:"VER OPÇÕES DE ACESSO"},
 en:{brand:"LDR Academy",eyebrow:"DIGITAL ACADEMIC LIBRARY",hero:"Organized knowledge for your next step.",sub:"Courses, training, books and publications in a university-library inspired experience.",explore:"EXPLORE THE ACADEMY",library:"OPEN MY LIBRARY",search:"Search courses or training…",all:"All",psy:"Psychoanalysis",business:"Business",career:"Career",rh:"HR",ai:"Artificial Intelligence",courses:"Courses & Training",coursesSub:"Choose your next learning path. All main programs on one shelf.",know:"LEARN MORE",free:"Start for free",freeSub:"Entry-level content to begin now.",start:"START FREE",editorial:"Academic Newsstand",editorialSub:"Newspapers, magazines and special publications.",books:"LDR Bookstore",booksSub:"Books and eBooks to read at your own pace.",subscription:"Want to explore several contents?",subscriptionText:"The monthly subscription keeps access to included digital content while active.",subscribe:"VIEW ACCESS OPTIONS"},
 fr:{brand:"LDR Academy",eyebrow:"BIBLIOTHÈQUE ACADÉMIQUE NUMÉRIQUE",hero:"Des connaissances organisées pour votre prochaine étape.",sub:"Cours, formations, livres et publications dans une expérience inspirée d’une bibliothèque universitaire.",explore:"EXPLORER L’ACADEMY",library:"OUVRIR MA BIBLIOTHÈQUE",search:"Rechercher un cours ou une formation…",all:"Tout",psy:"Psychanalyse",business:"Business",career:"Carrière",rh:"RH",ai:"Intelligence Artificielle",courses:"Cours et Formations",coursesSub:"Choisissez votre prochain apprentissage. Tous les programmes principaux sur une seule étagère.",know:"DÉCOUVRIR",free:"Commencer gratuitement",freeSub:"Des contenus d’entrée pour commencer maintenant.",start:"COMMENCER GRATUITEMENT",editorial:"Kiosque Académique",editorialSub:"Journaux, magazines et publications spéciales.",books:"Librairie LDR",booksSub:"Livres et eBooks à lire à votre rythme.",subscription:"Vous voulez explorer plusieurs contenus ?",subscriptionText:"L’abonnement mensuel donne accès aux contenus numériques inclus tant qu’il reste actif.",subscribe:"VOIR LES OPTIONS D’ACCÈS"},
 es:{brand:"LDR Academy",eyebrow:"BIBLIOTECA ACADÉMICA DIGITAL",hero:"Conocimiento organizado para tu próximo paso.",sub:"Cursos, formaciones, libros y publicaciones en una experiencia inspirada en una biblioteca universitaria.",explore:"EXPLORAR LA ACADEMY",library:"ABRIR MI BIBLIOTECA",search:"Buscar curso o formación…",all:"Todos",psy:"Psicoanálisis",business:"Negocios",career:"Carrera",rh:"RR. HH.",ai:"Inteligencia Artificial",courses:"Cursos y Formaciones",coursesSub:"Elige tu próximo aprendizaje. Todos los programas principales en una sola estantería.",know:"CONOCER",free:"Empieza gratis",freeSub:"Contenidos de entrada para comenzar ahora.",start:"EMPEZAR GRATIS",editorial:"Quiosco Académico",editorialSub:"Periódicos, revistas y publicaciones especiales.",books:"Librería LDR",booksSub:"Libros y eBooks para leer a tu ritmo.",subscription:"¿Quieres explorar varios contenidos?",subscriptionText:"La suscripción mensual mantiene acceso a los contenidos digitales incluidos mientras esté activa.",subscribe:"VER OPCIONES DE ACCESO"}
} as const;

const CORE:Course[]=[
 {id:"psy",title:"Formação Online em Psicanálise",desc:"Teoria, prática clínica, leituras orientadas e encontros ao vivo.",meta:"1.200h · 220 aulas",price:"R$ 299,99 · € 49,90",href:"/formacao-psicanalise",kind:"psicanalise",icon:"🧠",accent:"#5b2b86"},
 {id:"psy-intl",title:"Psicanálise Internacional, Neurodiversidade e Autismo",desc:"Curso avançado com atuação internacional, neurodiversidade e autismo.",meta:"21 módulos · 105 aulas",price:"R$ 497 · € 89",href:"/formacao-psicanalise-internacional",kind:"psicanalise",icon:"🌍",accent:"#24476f"},
 {id:"brief",title:"Formação em Terapia Breve Psicanalítica",desc:"Formação estruturada para aprofundamento teórico e aplicação clínica.",meta:"1.200h · 300 aulas",price:"R$ 299,99 · € 49,90",href:"/formacao-terapia-breve-psicanalitica",kind:"psicanalise",icon:"🪑",accent:"#6b2145"},
 {id:"performance",title:"Psicanalista de Alta Performance",desc:"Marketing, agenda, gestão e crescimento profissional em uma trilogia avançada.",meta:"Programa avançado · 660h",price:"Trilogia R$ 797 · € 149",href:"/cliente/psicanalista-alta-performance",kind:"psicanalise",icon:"📈",accent:"#8a6a2d"},
 {id:"ai",title:"Formação em Inteligência Artificial Aplicada aos Negócios e à Carreira",desc:"IA para conteúdo, automação, produtos digitais, programação e soluções reais.",meta:"600h · 15 módulos · 225 aulas",price:"R$ 299,99 · € 49,90",href:"/cliente/treinamentos/ia-negocios-carreira",kind:"ia",icon:"🤖",accent:"#143d59"},
 {id:"rh",title:"Formação em Gestão de Pessoas e Recursos Humanos",desc:"Formação profissional em RH, gestão de pessoas e desenvolvimento organizacional.",meta:"600h · 100% online",price:"R$ 299,99 · € 49,90",href:"/cliente/formacoes/gestao-pessoas-rh",kind:"rh",icon:"👥",accent:"#047857"},
 {id:"mentor",title:"Formação em Mentoria Profissional e de Carreira",desc:"Estruturação de processos de mentoria, carreira e desenvolvimento profissional.",meta:"9 módulos",price:"R$ 299,99 · € 49,90",href:"/cliente/biblioteca",kind:"carreira",icon:"🧭",accent:"#0b5cab"},
 {id:"lead",title:"Formação em Liderança e Gestão de Pessoas",desc:"Liderança, gestão, equipes, comunicação e desenvolvimento de pessoas.",meta:"9 módulos · 90 aulas",price:"R$ 299,99 · € 49,90",href:"/cliente/biblioteca",kind:"rh",icon:"🏛️",accent:"#7c3aed"},
 {id:"massage",title:"Formação Completa em Massoterapia",desc:"Formação profissional completa com conteúdo teórico e aplicação prática.",meta:"1.200h · 300 aulas",price:"R$ 299,99 · € 49,90",href:"/formacao-massoterapia",kind:"carreira",icon:"💆",accent:"#b85c2e"},
 {id:"business24",title:"Formação Negócio em 24 Horas",desc:"Da ideia a uma primeira oferta pronta para vender, com projeto final aplicado.",meta:"360h · 9 módulos · 90 aulas",price:"R$ 299,99 · € 49,90",href:"/formacao-negocio-em-24-horas",kind:"negocios",icon:"🚀",accent:"#c85a24"},
];

const FREE=[
 {title:"Organizar minha Carreira",desc:"Planejamento e próximos passos profissionais.",href:"/cliente/cursos/organizar-carreira",icon:"💼"},
 {title:"Francês para Negócios A1",desc:"Francês básico aplicado a situações profissionais.",href:"/cliente/cursos/frances-negocios-a1",icon:"🇫🇷"},
 {title:"Primeiros Socorros",desc:"Noções essenciais para situações de emergência.",href:"/cliente/cursos/primeiros-socorros",icon:"⛑️"},
];

const EDITORIAL=[
 ["Jornal LDR","/cliente/biblioteca/jornal-ldr","📰"],["Revista LDR","/cliente/biblioteca/revista-ldr","📖"],["LDR Ciência","/cliente/biblioteca/ldr-ciencia","🔬"],["Revista Negócios","/cliente/biblioteca/publicacoes/revista-negocios","💼"],["Jornal Europa","/cliente/biblioteca/publicacoes/jornal-europa","🇪🇺"],["Revista Psicanálise no Mundo","/cliente/biblioteca/publicacoes/revista-psicanalise-no-mundo","🧠"]
] as const;

function CourseCard({c,cta}:{c:Course;cta:string}){return <a href={c.href} className="group flex min-h-[300px] flex-col overflow-hidden rounded-[22px] border border-slate-200 bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className="h-2" style={{background:c.accent}}/><div className="flex flex-1 flex-col p-5"><div className="flex items-start justify-between gap-3"><span className="text-3xl">{c.icon}</span><span className="rounded-full bg-[#f5f0e6] px-2.5 py-1 text-[9px] font-black uppercase tracking-[.08em] text-[#7a5a22]">{c.meta}</span></div><h3 className="mt-4 font-serif text-xl leading-tight text-[#071426]">{c.title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{c.desc}</p><div className="mt-auto pt-5"><p className="text-sm font-black text-[#071426]">{c.price}</p><span className="mt-3 inline-flex w-full justify-center rounded-xl bg-[#071426] px-4 py-3 text-xs font-black text-white">{cta} →</span></div></div></a>}

export function AcademyUniversityHome(){
 const {locale:raw}=useI18n();
 const locale=(raw==="en"||raw==="fr"||raw==="es"?raw:"pt") as L;
 const t=UI[locale];
 const [kind,setKind]=useState<Kind>("all");
 const [q,setQ]=useState("");
 const pfLocale=locale as PFLocale;
 const professional:Course[]=PROFESSIONAL_FORMATIONS.map((f,i)=>{const tx=pfText(f,pfLocale);const kinds:Exclude<Kind,"all">[]=["negocios","negocios","rh","negocios","carreira"];return {id:f.slug,title:tx.name,desc:tx.description,meta:`${f.hours}h · ${f.modulesCount} ${locale==="en"?"modules":locale==="fr"?"modules":locale==="es"?"módulos":"módulos"}`,price:"R$ 299,99 · € 49,90",href:f.publicPath,kind:kinds[i]??"carreira",icon:f.icon,accent:["#0b3764","#7a1835","#047857","#0f766e","#6d28d9"][i]};});
 const courses=[...CORE,...professional];
 const filtered=useMemo(()=>courses.filter(c=>(kind==="all"||c.kind===kind)&&(`${c.title} ${c.desc}`).toLowerCase().includes(q.trim().toLowerCase())),[courses,kind,q]);
 const chips:[[Kind,string],...[Kind,string][]]=[["all",t.all],["psicanalise",t.psy],["negocios",t.business],["carreira",t.career],["rh",t.rh],["ia",t.ai]];
 return <main className="bg-[#fbfaf6] text-[#071426]">
  <section className="border-b border-[#d6ad63]/25 bg-gradient-to-br from-[#071426] via-[#0d2d4d] to-[#173f6b] text-white"><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6 sm:py-12"><p className="text-[10px] font-black uppercase tracking-[.24em] text-[#d6ad63]">{t.eyebrow}</p><div className="mt-3 grid gap-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><h1 className="font-serif text-4xl leading-tight !text-white sm:text-5xl">{t.brand}</h1><h2 className="mt-3 max-w-3xl text-2xl font-black leading-tight !text-white sm:text-3xl">{t.hero}</h2><p className="mt-3 max-w-3xl text-sm leading-7 !text-white/75 sm:text-base">{t.sub}</p></div><div className="grid gap-2 sm:grid-cols-2 lg:w-[390px]"><a href="#cursos" className="rounded-xl bg-[#d6ad63] px-4 py-3 text-center text-xs font-black text-[#281605]">{t.explore}</a><a href="/cliente/biblioteca" className="rounded-xl border border-white/20 bg-white/10 px-4 py-3 text-center text-xs font-black !text-white">{t.library}</a></div></div></div></section>

  <section className="sticky top-0 z-20 border-b border-slate-200 bg-[#fbfaf6]/95 backdrop-blur"><div className="mx-auto max-w-7xl px-4 py-3 sm:px-6"><div className="flex gap-2 overflow-x-auto [scrollbar-width:none]">{chips.map(([k,l])=><button key={k} onClick={()=>{setKind(k);document.getElementById('cursos')?.scrollIntoView({behavior:'smooth',block:'start'})}} className={`shrink-0 rounded-full px-4 py-2 text-xs font-black ${kind===k?"bg-[#071426] text-white":"border border-slate-200 bg-white text-[#071426]"}`}>{l}</button>)}<a href="#gratuitos" className="shrink-0 rounded-full border border-slate-200 bg-white px-4 py-2 text-xs font-black text-[#071426]">{t.free}</a><a href="#editorial" className="shrink-0 rounded-full border border-slate-200 bg-white px-4 py-2 text-xs font-black text-[#071426]">{t.editorial}</a><a href="#livros" className="shrink-0 rounded-full border border-slate-200 bg-white px-4 py-2 text-xs font-black text-[#071426]">{t.books}</a></div></div></section>

  <section id="cursos" className="scroll-mt-20"><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex items-center gap-3"><GraduationCap className="h-7 w-7 text-[#b1842c]"/><h2 className="font-serif text-3xl sm:text-4xl">{t.courses}</h2></div><p className="mt-2 text-sm text-slate-600">{t.coursesSub}</p></div><label className="relative block lg:w-[360px]"><Search className="absolute left-4 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search} className="w-full rounded-2xl border border-slate-200 bg-white py-3.5 pl-12 pr-4 text-sm outline-none focus:border-[#d6ad63] focus:ring-2 focus:ring-[#d6ad63]/20"/></label></div><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{filtered.map(c=><CourseCard key={c.id} c={c} cta={t.know}/>)}</div></div></section>

  <section id="gratuitos" className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-4 py-9 sm:px-6"><div className="flex items-center gap-3"><Sparkles className="h-7 w-7 text-[#b1842c]"/><div><h2 className="font-serif text-3xl">{t.free}</h2><p className="mt-1 text-sm text-slate-600">{t.freeSub}</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-3">{FREE.map(x=><a key={x.title} href={x.href} className="rounded-[20px] border border-slate-200 bg-[#fbfaf6] p-5 transition hover:-translate-y-0.5 hover:shadow-md"><span className="text-2xl">{x.icon}</span><h3 className="mt-3 font-serif text-xl">{x.title}</h3><p className="mt-2 text-sm text-slate-600">{x.desc}</p><span className="mt-4 inline-flex text-xs font-black text-[#0b5cab]">{t.start} →</span></a>)}</div></div></section>

  <section id="editorial"><div className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><div className="flex items-center gap-3"><Newspaper className="h-7 w-7 text-[#b1842c]"/><div><h2 className="font-serif text-3xl">{t.editorial}</h2><p className="mt-1 text-sm text-slate-600">{t.editorialSub}</p></div></div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{EDITORIAL.map(([name,href,icon])=><a key={name} href={href} className="rounded-[18px] border border-slate-200 bg-white p-4 shadow-sm transition hover:-translate-y-0.5"><span className="text-2xl">{icon}</span><h3 className="mt-3 font-serif text-base leading-tight">{name}</h3></a>)}</div></div></section>

  <section id="livros" className="border-y border-slate-200 bg-[#f4efe3]"><div className="mx-auto max-w-7xl px-4 py-9 sm:px-6"><div className="flex items-center gap-3"><BookOpen className="h-7 w-7 text-[#8a6727]"/><div><h2 className="font-serif text-3xl">{t.books}</h2><p className="mt-1 text-sm text-slate-600">{t.booksSub}</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2"><a href="/acoragemdecomecar" className="rounded-[22px] border border-[#d6ad63]/35 bg-white p-5"><p className="text-xs font-black uppercase tracking-[.14em] text-[#a06f1c]">eBook</p><h3 className="mt-2 font-serif text-2xl">A Coragem de Começar</h3><p className="mt-3 font-black">R$ 9,90 · € 4,90</p></a><a href="/livros" className="rounded-[22px] border border-[#d6ad63]/35 bg-white p-5"><p className="text-xs font-black uppercase tracking-[.14em] text-[#a06f1c]">LDR</p><h3 className="mt-2 font-serif text-2xl">{t.books}</h3><p className="mt-3 text-sm text-slate-600">{t.booksSub}</p></a></div></div></section>

  <section className="bg-[#071426] text-white"><div className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="grid gap-5 lg:grid-cols-[1fr_auto] lg:items-center"><div className="flex gap-4"><Library className="mt-1 h-8 w-8 shrink-0 text-[#d6ad63]"/><div><h2 className="font-serif text-2xl !text-white">{t.subscription}</h2><p className="mt-1 max-w-2xl text-sm leading-6 !text-white/70">{t.subscriptionText}</p></div></div><a href="/cliente/biblioteca" className="rounded-xl bg-[#d6ad63] px-5 py-3 text-center text-xs font-black text-[#281605]">{t.subscribe}</a></div></div></section>
 </main>;
}
