import { Gift, Instagram } from "lucide-react";
import { useI18n } from "@/lib/i18n";

type L="pt"|"en"|"fr"|"es";
const INSTAGRAM="https://www.instagram.com/ldracademy.online?stkn=MWhjOHI5N2syMDZ5aA%3D%3D&utm_source=qr";

const COPY={
  pt:{badge:"SORTEIO ESPECIAL",title:"GANHE 1 ANO",sub:"DE LDR ESSENCE ACADEMY COMPLETA",desc:"12 meses de acesso aos cursos, formações e conteúdos digitais incluídos na assinatura da plataforma.",winner:"1 VENCEDOR",date:"15/10/2026",time:"20H — BRASÍLIA",live:"AO VIVO NO INSTAGRAM",cta:"PARTICIPAR NO INSTAGRAM",rules:"VER REGULAMENTO",free:"Participação gratuita.",how:"Como participar",steps:["Seguir @ldracademy.online","Curtir a publicação oficial da campanha","Marcar 2 pessoas nos comentários","Compartilhar a publicação nos Stories e marcar @ldracademy.online"],reg:"Regulamento resumido",body:"Promoção LDR Essence Academy. 1 contemplado receberá 12 meses de acesso completo aos conteúdos digitais incluídos na modalidade premiada. O prêmio é pessoal, intransferível e não poderá ser convertido em dinheiro. Participações com contas falsas, bots, automações ou fraude poderão ser desclassificadas. O resultado está previsto para 15/10/2026 às 20h, horário de Brasília, com divulgação ao vivo no Instagram oficial. A participação é gratuita. Dados eventualmente solicitados serão usados para validação e entrega do prêmio. O Instagram não patrocina, administra ou está associado à campanha. A ação permanece sujeita às regras e requisitos legais aplicáveis."},
  en:{badge:"SPECIAL GIVEAWAY",title:"WIN 1 YEAR",sub:"OF FULL LDR ESSENCE ACADEMY ACCESS",desc:"12 months of access to courses, training and digital content included in the platform subscription.",winner:"1 WINNER",date:"15/10/2026",time:"20:00 — BRASÍLIA",live:"LIVE ON INSTAGRAM",cta:"ENTER ON INSTAGRAM",rules:"VIEW RULES",free:"Free entry.",how:"How to enter",steps:["Follow @ldracademy.online","Like the official giveaway post","Tag 2 people in the comments","Share the post to Stories and tag @ldracademy.online"],reg:"Summary rules",body:"LDR Essence Academy promotional campaign. One winner will receive 12 months of full access to the digital content included in the awarded subscription. The prize is personal, non-transferable and cannot be exchanged for cash. Fake accounts, bots, automation or fraud may lead to disqualification. Result scheduled for 15/10/2026 at 20:00 Brasília time, announced live on the official Instagram. Entry is free. Data requested may be used for validation and prize delivery. Instagram does not sponsor, administer or endorse this campaign. Applicable legal requirements remain in force."},
  fr:{badge:"TIRAGE SPÉCIAL",title:"GAGNEZ 1 AN",sub:"D’ACCÈS COMPLET À LDR ESSENCE ACADEMY",desc:"12 mois d’accès aux cours, formations et contenus numériques inclus dans l’abonnement de la plateforme.",winner:"1 GAGNANT",date:"15/10/2026",time:"20H — BRASÍLIA",live:"EN DIRECT SUR INSTAGRAM",cta:"PARTICIPER SUR INSTAGRAM",rules:"VOIR LE RÈGLEMENT",free:"Participation gratuite.",how:"Comment participer",steps:["Suivre @ldracademy.online","Aimer la publication officielle","Identifier 2 personnes en commentaire","Partager en Story et identifier @ldracademy.online"],reg:"Règlement résumé",body:"Campagne promotionnelle LDR Essence Academy. Un gagnant recevra 12 mois d’accès complet aux contenus numériques inclus dans la formule récompensée. Le prix est personnel, non transférable et non convertible en espèces. Les faux comptes, bots, automatisations ou fraudes peuvent entraîner une disqualification. Résultat prévu le 15/10/2026 à 20h, heure de Brasília, en direct sur Instagram. Participation gratuite. Les données éventuellement demandées serviront à la validation et à la remise du prix. Instagram ne sponsorise ni n’administre cette campagne. Les exigences légales applicables restent en vigueur."},
  es:{badge:"SORTEO ESPECIAL",title:"GANA 1 AÑO",sub:"DE LDR ESSENCE ACADEMY COMPLETA",desc:"12 meses de acceso a cursos, formaciones y contenidos digitales incluidos en la suscripción de la plataforma.",winner:"1 GANADOR",date:"15/10/2026",time:"20H — BRASILIA",live:"EN VIVO POR INSTAGRAM",cta:"PARTICIPAR EN INSTAGRAM",rules:"VER REGLAMENTO",free:"Participación gratuita.",how:"Cómo participar",steps:["Seguir @ldracademy.online","Dar me gusta a la publicación oficial","Etiquetar a 2 personas en los comentarios","Compartir en Stories y etiquetar @ldracademy.online"],reg:"Reglamento resumido",body:"Campaña promocional LDR Essence Academy. Una persona ganadora recibirá 12 meses de acceso completo a los contenidos digitales incluidos en la modalidad premiada. El premio es personal, intransferible y no se puede convertir en dinero. Cuentas falsas, bots, automatizaciones o fraude podrán ser descalificados. Resultado previsto para el 15/10/2026 a las 20h, hora de Brasilia, en vivo por Instagram. Participación gratuita. Los datos eventualmente solicitados se usarán para validación y entrega del premio. Instagram no patrocina ni administra esta campaña. Se mantienen vigentes los requisitos legales aplicables."}
} as const;

export function AcademyGiveawayBanner({compact=false}:{compact?:boolean}){
  const {locale:raw}=useI18n();
  const locale=(raw==="en"||raw==="fr"||raw==="es"?raw:"pt") as L;
  const t=COPY[locale];
  return <section aria-label={t.badge} className={`${compact?"mb-6":"border-b border-[#d6ad63]/20"} bg-[#071426] text-white`}>
    <div className={`${compact?"rounded-[24px] border border-[#d6ad63]/35 p-5 sm:p-6":"mx-auto max-w-7xl px-4 py-8 sm:px-6 sm:py-10"}`}>
      <div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr] lg:items-center">
        <div>
          <div className="inline-flex items-center gap-2 rounded-full border border-[#d6ad63]/45 px-3 py-1.5 text-[10px] font-black uppercase tracking-[.2em] text-[#e6c27b]"><Gift className="h-3.5 w-3.5"/>{t.badge}</div>
          <h2 className="mt-4 font-serif text-4xl leading-none text-[#fff7e7] sm:text-5xl">{t.title}</h2>
          <p className="mt-2 text-sm font-black uppercase tracking-[.12em] text-[#e6c27b] sm:text-base">{t.sub}</p>
          <p className="mt-4 max-w-2xl text-sm leading-6 text-white/75">{t.desc}</p>
          <div className="mt-5 flex flex-wrap gap-2 text-[11px] font-black uppercase tracking-[.08em]"><span className="rounded-full bg-white/10 px-3 py-2">{t.winner}</span><span className="rounded-full bg-white/10 px-3 py-2">{t.date}</span><span className="rounded-full bg-white/10 px-3 py-2">{t.time}</span><span className="rounded-full bg-white/10 px-3 py-2">{t.live}</span></div>
          <div className="mt-6 flex flex-col gap-3 sm:flex-row"><a href={INSTAGRAM} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-[#d6ad63] px-5 py-3 text-sm font-black text-[#281605]"><Instagram className="h-4 w-4"/>{t.cta}</a><details className="group rounded-xl border border-white/20 bg-white/5"><summary className="flex min-h-12 cursor-pointer list-none items-center justify-center px-5 py-3 text-sm font-black">{t.rules}</summary><div className="max-w-2xl border-t border-white/10 p-4 text-sm leading-6 text-white/75"><p className="font-black text-white">{t.how}</p><ol className="mt-2 list-decimal space-y-1 pl-5">{t.steps.map(s=><li key={s}>{s}</li>)}</ol><p className="mt-4 font-black text-white">{t.reg}</p><p className="mt-2">{t.body}</p></div></details></div>
          <p className="mt-3 text-xs text-white/55">{t.free}</p>
        </div>
        {!compact?<div className="hidden lg:block"><div className="ml-auto flex min-h-[205px] w-[320px] flex-col justify-center rounded-[28px] border border-[#d6ad63]/30 bg-white/[.06] p-8 text-center"><p className="text-xs font-black uppercase tracking-[.22em] text-[#d6ad63]">LDR ESSENCE ACADEMY</p><p className="mt-4 font-serif text-6xl text-[#fff7e7]">1 ANO</p><p className="mt-2 text-xs font-black uppercase tracking-[.16em] text-white/70">12 MESES DE ACESSO COMPLETO</p></div></div>:null}
      </div>
    </div>
  </section>;
}
