import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Check, Sparkles } from "lucide-react";
import { useState } from "react";
import { academicOnboardingState, academicSaveOnboarding } from "@/lib/academic-onboarding-v3.functions";

const COPY={
 pt:{title:"Quais temas você quer acompanhar?",sub:"Escolha de 3 a 8 temas. Isso ajuda a organizar sugestões de pessoas, comunidades e conteúdos. Nada será seguido automaticamente.",save:"PERSONALIZAR MINHA REDE",pick:"Selecione pelo menos 3 temas"},
 en:{title:"What topics do you want to follow?",sub:"Choose 3 to 8 topics. This helps organise suggestions for people, communities and content. Nothing will be followed automatically.",save:"PERSONALISE MY NETWORK",pick:"Select at least 3 topics"},
 fr:{title:"Quels thèmes souhaitez-vous suivre ?",sub:"Choisissez de 3 à 8 thèmes. Cela aide à organiser les suggestions de personnes, communautés et contenus. Aucun abonnement ne sera automatique.",save:"PERSONNALISER MON RÉSEAU",pick:"Sélectionnez au moins 3 thèmes"},
 es:{title:"¿Qué temas quieres seguir?",sub:"Elige entre 3 y 8 temas. Esto ayuda a organizar sugerencias de personas, comunidades y contenidos. No se seguirá a nadie automáticamente.",save:"PERSONALIZAR MI RED",pick:"Selecciona al menos 3 temas"}
} as const;
export function AcademicOnboardingV3({locale="pt"}:{locale?:string}){
 const l=(locale==="en"||locale==="fr"||locale==="es"?locale:"pt") as keyof typeof COPY,t=COPY[l];const qc=useQueryClient(),stateFn=useServerFn(academicOnboardingState),saveFn=useServerFn(academicSaveOnboarding);const {data,isLoading}=useQuery({queryKey:["academic-onboarding-v3"],queryFn:()=>stateFn()});const [selected,setSelected]=useState<string[]>([]);const chosen=selected.length?selected:(data?.interests??[]);const save=useMutation({mutationFn:()=>saveFn({data:{interests:chosen}}),onSuccess:()=>qc.invalidateQueries({queryKey:["academic-onboarding-v3"]})});if(isLoading||data?.completed)return null;const toggle=(x:string)=>setSelected(cur=>{const base=cur.length?cur:(data?.interests??[]);return base.includes(x)?base.filter((y:string)=>y!==x):base.length<8?[...base,x]:base});return <section className="rounded-[22px] border border-[#d6ad63]/55 bg-gradient-to-br from-[#071426] to-[#123d68] p-5 text-white shadow-lg"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-white/10 text-[#efc56d]"><Sparkles className="h-5 w-5"/></span><div><h2 className="font-serif text-xl">{t.title}</h2><p className="mt-1 text-xs leading-5 text-white/75">{t.sub}</p></div></div><div className="mt-4 flex flex-wrap gap-2">{(data?.allowed??[]).map((x:string)=>{const active=chosen.includes(x);return <button key={x} type="button" onClick={()=>toggle(x)} className={`min-h-10 rounded-full border px-3 text-[10px] font-black transition ${active?"border-[#efc56d] bg-[#efc56d] text-[#071426]":"border-white/20 bg-white/5 text-white"}`}>{active&&<Check className="mr-1 inline h-3.5 w-3.5"/>}{x}</button>})}</div><button disabled={chosen.length<3||save.isPending} onClick={()=>save.mutate()} className="mt-4 min-h-11 rounded-xl bg-[#efc56d] px-4 text-xs font-black text-[#071426] disabled:opacity-50">{chosen.length<3?t.pick:t.save}</button></section>}
