import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Award, CalendarDays, Plus, Save, Trophy } from "lucide-react";
import { useState } from "react";
import { academicAdminChallengeSnapshot, academicSaveChallenge, academicScoreChallengeEntry, academicSetChallengeEntryResult } from "@/lib/academic-challenges-v2.functions";

type Status="draft"|"published"|"closed"|"cancelled";
const EMPTY={title:"",theme:"",description:"",rules:"",startsAt:"",endsAt:"",status:"draft" as Status,category:"",communityWeight:40,juryWeight:60};
export function AcademicChallengesAdmin(){
  const qc=useQueryClient();const snapshot=useServerFn(academicAdminChallengeSnapshot),saveFn=useServerFn(academicSaveChallenge),scoreFn=useServerFn(academicScoreChallengeEntry),resultFn=useServerFn(academicSetChallengeEntryResult);const [form,setForm]=useState(EMPTY);const [editingId,setEditingId]=useState<string|undefined>();
  const {data,isLoading}=useQuery({queryKey:["academic-challenges-admin"],queryFn:()=>snapshot()});
  const refresh=()=>qc.invalidateQueries({queryKey:["academic-challenges-admin"]});
  const save=useMutation({mutationFn:()=>saveFn({data:{...form,id:editingId}}),onSuccess:()=>{setForm(EMPTY);setEditingId(undefined);refresh()}});
  const score=useMutation({mutationFn:(x:{entryId:string;score:number})=>scoreFn({data:x}),onSuccess:refresh});
  const result=useMutation({mutationFn:(x:{entryId:string;status:"winner"|"highlighted"|"eligible"|"ineligible";badge?:"article_highlight"|"community_choice"|"ldr_academic_highlight"|null})=>resultFn({data:x}),onSuccess:refresh});
  const edit=(c:any)=>{setEditingId(c.id);setForm({title:c.title,theme:c.theme,description:c.description??"",rules:c.rules??"",startsAt:String(c.starts_at).slice(0,16),endsAt:String(c.ends_at).slice(0,16),status:c.status,category:c.category??"",communityWeight:Number(c.community_weight??40),juryWeight:Number(c.jury_weight??60)})};
  if(isLoading)return <section className="rounded-2xl border bg-card p-5">Carregando desafios acadêmicos…</section>;
  return <section className="rounded-2xl border bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-2"><Trophy className="h-5 w-5"/><div><h2 className="text-lg font-bold">Desafios Acadêmicos</h2><p className="text-xs text-muted-foreground">40% comunidade + 60% júri por padrão, com pesos configuráveis.</p></div></div><button onClick={()=>{setEditingId(undefined);setForm(EMPTY)}} className="min-h-11 rounded-xl border px-3 text-xs font-black"><Plus className="mr-1 inline h-4 w-4"/>NOVO</button></div>
    <div className="mt-5 grid gap-4 xl:grid-cols-[1fr_.9fr]"><div className="space-y-3">{data?.challenges?.length?data.challenges.map((c:any)=><article key={c.id} className="rounded-xl border p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex gap-2 text-[10px] font-black"><span className="rounded-full bg-muted px-2 py-1">{c.status}</span><span className="rounded-full bg-[#f6efde] px-2 py-1 text-[#7b5a1d]">{c.community_weight}% COMUNIDADE · {c.jury_weight}% JÚRI</span></div><h3 className="mt-2 font-serif text-xl">{c.title}</h3><p className="mt-1 text-sm text-muted-foreground">{c.theme}</p><p className="mt-2 flex items-center gap-1 text-[10px] text-muted-foreground"><CalendarDays className="h-3 w-3"/>{new Date(c.starts_at).toLocaleDateString()} — {new Date(c.ends_at).toLocaleDateString()}</p></div><button onClick={()=>edit(c)} className="min-h-10 rounded-lg border px-3 text-xs font-black">EDITAR</button></div><div className="mt-3 border-t pt-3"><b className="text-xs">Participações</b><div className="mt-2 space-y-2">{(data.entries??[]).filter((e:any)=>e.challenge_id===c.id).map((e:any)=><div key={e.id} className="rounded-lg bg-muted/40 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><span className="text-[10px] font-bold">{e.entry_type.toUpperCase()} · {e.status} · {e.final_score==null?"SEM NOTA":`FINAL ${Number(e.final_score).toFixed(1)}`}</span><div className="flex flex-wrap gap-1"><button onClick={()=>{const raw=window.prompt("Nota do júri (0–100)",String(e.jury_score??80));if(raw!==null)score.mutate({entryId:e.id,score:Number(raw)})}} className="min-h-9 rounded-lg border bg-background px-2 text-[10px] font-black">AVALIAR</button><button onClick={()=>result.mutate({entryId:e.id,status:"highlighted",badge:"ldr_academic_highlight"})} className="min-h-9 rounded-lg border bg-background px-2 text-[10px] font-black">DESTACAR</button><button onClick={()=>result.mutate({entryId:e.id,status:"winner",badge:e.entry_type==="article"?"article_highlight":"community_choice"})} className="min-h-9 rounded-lg bg-[#071426] px-2 text-[10px] font-black text-white"><Award className="mr-1 inline h-3 w-3"/>VENCEDOR</button></div></div></div>)}</div></div></article>):<p className="rounded-xl border border-dashed p-5 text-sm text-muted-foreground">Nenhum desafio criado.</p>}</div>
      <div className="rounded-2xl border p-4"><h3 className="font-bold">{editingId?"Editar desafio":"Criar desafio"}</h3><div className="mt-4 grid gap-3"><F label="Título" value={form.title} set={v=>setForm({...form,title:v})}/><F label="Tema" value={form.theme} set={v=>setForm({...form,theme:v})}/><F label="Categoria" value={form.category} set={v=>setForm({...form,category:v})}/><label className="text-xs font-bold">Descrição<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})} rows={4} className="mt-1 w-full rounded-xl border bg-background p-3 text-sm"/></label><label className="text-xs font-bold">Regras<textarea value={form.rules} onChange={e=>setForm({...form,rules:e.target.value})} rows={4} className="mt-1 w-full rounded-xl border bg-background p-3 text-sm"/></label><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-bold">Início<input type="datetime-local" value={form.startsAt} onChange={e=>setForm({...form,startsAt:e.target.value})} className="mt-1 min-h-11 w-full rounded-xl border bg-background px-3"/></label><label className="text-xs font-bold">Fim<input type="datetime-local" value={form.endsAt} onChange={e=>setForm({...form,endsAt:e.target.value})} className="mt-1 min-h-11 w-full rounded-xl border bg-background px-3"/></label></div><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs font-bold">Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value as Status})} className="mt-1 min-h-11 w-full rounded-xl border bg-background px-3"><option value="draft">RASCUNHO</option><option value="published">PUBLICADO</option><option value="closed">ENCERRADO</option><option value="cancelled">CANCELADO</option></select></label><label className="text-xs font-bold">Comunidade %<input type="number" min="0" max="100" value={form.communityWeight} onChange={e=>setForm({...form,communityWeight:Number(e.target.value),juryWeight:100-Number(e.target.value)})} className="mt-1 min-h-11 w-full rounded-xl border bg-background px-3"/></label><label className="text-xs font-bold">Júri %<input type="number" min="0" max="100" value={form.juryWeight} onChange={e=>setForm({...form,juryWeight:Number(e.target.value),communityWeight:100-Number(e.target.value)})} className="mt-1 min-h-11 w-full rounded-xl border bg-background px-3"/></label></div></div>{save.error&&<p className="mt-3 text-xs text-destructive">{String((save.error as Error).message)}</p>}<button disabled={save.isPending} onClick={()=>save.mutate()} className="mt-4 min-h-11 w-full rounded-xl bg-[#071426] px-4 text-xs font-black text-white"><Save className="mr-2 inline h-4 w-4"/>SALVAR DESAFIO</button></div></div>
  </section>
}
function F({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="text-xs font-bold">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 min-h-11 w-full rounded-xl border bg-background px-3 text-sm"/></label>}
