import { Link } from "@tanstack/react-router";
import { BookOpen, CheckCircle2, Clock3, GraduationCap, MessageCircle, ShieldCheck, UsersRound, Video } from "lucide-react";
import { LanguageSelect } from "@/lib/i18n";
import { briefTherapyModules } from "@/content/brief-therapy-curriculum";
const WHATSAPP="https://wa.me/32492923605?text=Ol%C3%A1%2C%20quero%20saber%20mais%20sobre%20a%20Forma%C3%A7%C3%A3o%20em%20Terapia%20Breve%20Psicanal%C3%ADtica.";
export function BriefTherapyTrainingPage(){return <div className="min-h-screen bg-[#f4faf7] text-[#0b2e2c]"><header className="sticky top-0 z-40 border-b border-[#d6ad63]/40 bg-[#103d3a]/95 text-white backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-3 sm:px-6"><Link to="/" className="font-serif text-lg font-bold">Grupo LDR Essence</Link><div className="flex items-center gap-2"><a href={WHATSAPP} target="_blank" rel="noopener noreferrer" className="hidden min-h-10 items-center gap-2 rounded-full border border-white/20 px-3 text-xs font-bold sm:inline-flex"><MessageCircle className="h-4 w-4"/>Dúvidas</a><LanguageSelect/></div></div></header><main className="mx-auto max-w-6xl space-y-12 px-4 py-8 sm:px-6">
<section className="overflow-hidden rounded-[2rem] border border-[#d6ad63] bg-gradient-to-br from-[#0b2e2c] via-[#17645e] to-[#103d3a] p-6 text-white shadow-2xl sm:p-10"><span className="inline-flex rounded-full bg-[#d6ad63] px-3 py-1.5 text-[11px] font-black uppercase tracking-[.14em] text-[#103d3a]">Formação livre · 100% online</span><h1 className="mt-5 max-w-4xl font-serif text-4xl font-bold leading-tight sm:text-6xl">Formação em Terapia Breve Psicanalítica</h1><p className="mt-4 max-w-3xl text-lg text-white/80">Do foco à alta: fundamentos, técnica e prática clínica em um percurso estruturado de 15 módulos, 300 aulas, 1.200 horas e 6 encontros ao vivo.</p><div className="mt-6 flex flex-wrap gap-2 text-xs font-bold">{["15 módulos","300 aulas","1.200 horas","6 encontros ao vivo","Acesso vitalício na compra individual"].map(x=><span key={x} className="rounded-full bg-white/10 px-3 py-2">{x}</span>)}</div><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:max-w-2xl"><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-white/60">Brasil</p><p className="text-3xl font-black">R$ 299,99</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-white/60">Europa</p><p className="text-3xl font-black">€ 49,90</p></div></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><Link to="/cliente/biblioteca" className="rounded-xl bg-[#d6ad63] px-5 py-3 text-center text-sm font-black text-[#103d3a]">COMEÇAR MINHA FORMAÇÃO</Link><Link to="/cliente/biblioteca" className="rounded-xl border border-white/25 bg-white/10 px-5 py-3 text-center text-sm font-black">ACESSAR PELA ASSINATURA</Link></div></section>
<section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[GraduationCap,"15 módulos","Do fundamento histórico à supervisão e prática avançada."],[BookOpen,"300 aulas","Leitura estruturada, reflexão, exercícios e sínteses."],[Clock3,"1.200 horas","Carga horária formativa total do percurso."],[Video,"6 encontros ao vivo","Integração, dúvidas, casos e supervisão orientada."]].map(([I,t,d]:any)=><article key={t} className="rounded-3xl border border-[#c8ddd8] bg-white p-5 shadow-sm"><I className="h-7 w-7 text-[#17645e]"/><h2 className="mt-3 font-serif text-2xl font-bold">{t}</h2><p className="mt-2 text-sm leading-6 text-[#5f716c]">{d}</p></article>)}</section>
<section><p className="text-xs font-black uppercase tracking-[.18em] text-[#17645e]">Conteúdo completo</p><h2 className="mt-2 font-serif text-4xl font-bold">Do foco à alta, módulo por módulo.</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{briefTherapyModules.map((m,i)=><article key={m.id} className="rounded-3xl border border-[#c8ddd8] bg-white p-5"><span className="text-[10px] font-black uppercase tracking-[.14em] text-[#17645e]">Módulo {String(i+1).padStart(2,"0")} · 20 aulas</span><h3 className="mt-2 font-serif text-2xl font-bold">{m.title}</h3><p className="mt-2 text-sm leading-6 text-[#5f716c]">{m.focus}</p></article>)}</div></section>
<section className="rounded-[2rem] border border-[#d6ad63]/45 bg-[#fffaf0] p-6 sm:p-8"><div className="flex items-start gap-3"><ShieldCheck className="mt-1 h-7 w-7 shrink-0 text-[#17645e]"/><div><h2 className="font-serif text-3xl font-bold">Formação responsável e com limites claros</h2><p className="mt-3 text-sm leading-7 text-[#5f716c]">Formação livre de caráter educacional e profissional. Não equivale a graduação, especialização reconhecida pelo MEC ou licença profissional regulamentada. Conteúdos sobre risco, urgência, violência, medicação e quadros graves orientam encaminhamento para profissionais e serviços competentes.</p></div></div></section>
<section className="rounded-[2rem] bg-[#103d3a] p-7 text-white sm:p-10"><h2 className="font-serif text-4xl font-bold">Escolha como acessar</h2><div className="mt-6 grid gap-4 md:grid-cols-2"><article className="rounded-2xl bg-white/10 p-5"><h3 className="font-serif text-2xl font-bold">Compra individual</h3><p className="mt-2 text-sm text-white/70">Pagamento único e acesso vitalício aos conteúdos digitais.</p><p className="mt-4 text-2xl font-black">R$ 299,99 · € 49,90</p></article><article className="rounded-2xl border border-[#d6ad63]/60 bg-white/10 p-5"><h3 className="font-serif text-2xl font-bold">Assinatura Biblioteca LDR</h3><p className="mt-2 text-sm text-white/70">Acesso integral enquanto a assinatura estiver ativa, conforme as regras atuais da Biblioteca.</p></article></div><Link to="/cliente/biblioteca" className="mt-6 block rounded-xl bg-[#d6ad63] px-5 py-3 text-center text-sm font-black text-[#103d3a]">QUERO COMEÇAR</Link></section>
</main></div>}
