import { Link } from "@tanstack/react-router";
import { BookOpen, BriefcaseBusiness, Check, ChevronRight, GraduationCap, Languages, Library, Sparkles } from "lucide-react";
import { LanguageSelect, useI18n } from "@/lib/i18n";
import { librarySalesCardCatalog } from "@/lib/library-sales-card-i18n";

const PROMO_END_AT = new Date("2026-09-30T23:59:59+02:00").getTime();

type Locale = "pt" | "en" | "fr" | "es";

const COPY = {
  pt: {
    brand:"Biblioteca LDR", login:"Entrar", eyebrow:"CURSOS · FORMAÇÕES · CONHECIMENTO",
    title:"Conhecimento para sua carreira, seus negócios e sua vida profissional.",
    sub:"Cursos, formações profissionais, treinamentos, livros e conteúdos digitais reunidos em uma única plataforma.",
    see:"VER CURSOS E FORMAÇÕES", subscribe:"ASSINAR A BIBLIOTECA",
    helper:"Aprenda no seu ritmo · Acesse de qualquer lugar · Escolha entre conteúdos gratuitos, compra individual ou assinatura mensal.",
    choose:"O que você quer aprender?", chooseSub:"Encontre mais rápido o conteúdo ideal para seu momento.",
    formations:"Formações", free:"Gratuitos", business:"Negócios", books:"Livros", languages:"Idiomas",
    promo:"PROMOÇÃO DO MÊS", promoTitle:"50% OFF NO PRIMEIRO MÊS", promoText:"Uma assinatura para acessar os conteúdos digitais pagos da Biblioteca LDR enquanto estiver ativa.",
    firstMonth:"Primeiro mês", fromSecond:"A partir do 2º mês", promoCta:"ASSINAR COM 50% OFF",
    formationTitle:"Escolha sua formação", formationSub:"Formações profissionais para desenvolver conhecimentos aplicáveis à carreira, aos negócios e à atuação profissional.",
    freeBadge:"100% GRATUITA", know:"CONHECER FORMAÇÃO", startFree:"COMEÇAR GRATUITAMENTE",
    entrepreneurship:"TRANSFORME CONHECIMENTO EM NEGÓCIO", entrepreneurshipTitle:"Do Mamão ao Negócio", entrepreneurshipText:"90 aulas, 6 encontros ao vivo, acesso vitalício e aplicação prática em posicionamento, vendas e construção de negócio.",
    freeTitle:"Comece gratuitamente", freeText:"Entre na plataforma sem pagar e experimente a experiência de aprendizagem da Biblioteca LDR.",
    compare:"Escolha como acessar", oneTime:"Comprar individualmente", monthly:"Assinar a Biblioteca", oneTimeText:"Pagamento único e acesso vitalício ao conteúdo comprado.", monthlyText:"Acesso aos conteúdos digitais pagos enquanto a assinatura estiver ativa.",
    reading:"Leitura que também faz parte da sua formação", how:"Como funciona", step1:"1. Escolha", step1t:"Selecione seu curso, formação ou assinatura.", step2:"2. Acesse", step2t:"Entre na Biblioteca LDR pelo computador ou celular.", step3:"3. Aprenda", step3t:"Estude no seu ritmo e acompanhe seu progresso.",
    story:"Conhecimento construído na prática.", storyText:"Da Bahia à Europa, experiências em pessoas, negócios, carreira e empreendedorismo foram transformadas em conteúdos e formações voltados à prática.",
    faq:"Perguntas frequentes", final:"Seu próximo passo pode começar aqui.", finalSub:"Escolha uma formação, comece gratuitamente ou tenha acesso à Biblioteca LDR.",
  },
  en: {
    brand:"LDR Library", login:"Sign in", eyebrow:"COURSES · TRAINING · KNOWLEDGE", title:"Knowledge for your career, business and professional life.", sub:"Courses, professional training, entrepreneurship programs, books and digital content in one platform.", see:"VIEW COURSES & TRAINING", subscribe:"SUBSCRIBE", helper:"Learn at your pace · Access from anywhere · Choose free content, one-time purchase or monthly subscription.", choose:"What do you want to learn?", chooseSub:"Find the right content for your current goals.", formations:"Training", free:"Free", business:"Business", books:"Books", languages:"Languages", promo:"MONTHLY PROMO", promoTitle:"50% OFF THE FIRST MONTH", promoText:"One subscription for paid digital content while active.", firstMonth:"First month", fromSecond:"From month 2", promoCta:"SUBSCRIBE WITH 50% OFF", formationTitle:"Choose your training", formationSub:"Professional programs focused on practical career and business development.", freeBadge:"100% FREE", know:"LEARN MORE", startFree:"START FOR FREE", entrepreneurship:"TURN KNOWLEDGE INTO BUSINESS", entrepreneurshipTitle:"From Papaya to Business", entrepreneurshipText:"90 lessons, 6 live sessions, lifetime access and practical work on positioning, sales and business building.", freeTitle:"Start for free", freeText:"Enter the platform at no cost and experience the LDR Library learning environment.", compare:"Choose how to access", oneTime:"Buy individually", monthly:"Subscribe to the Library", oneTimeText:"One-time payment and lifetime access to the purchased content.", monthlyText:"Access paid digital content while your subscription is active.", reading:"Reading is part of learning too", how:"How it works", step1:"1. Choose", step1t:"Select a course, training or subscription.", step2:"2. Access", step2t:"Use the LDR Library on desktop or mobile.", step3:"3. Learn", step3t:"Study at your pace and track your progress.", story:"Knowledge built in practice.", storyText:"From Bahia to Europe, experiences in people, business, career and entrepreneurship became practical learning content.", faq:"Frequently asked questions", final:"Your next step can start here.", finalSub:"Choose a program, start free or access the LDR Library."},
  fr: {
    brand:"Bibliothèque LDR", login:"Entrer", eyebrow:"COURS · FORMATIONS · CONNAISSANCE", title:"Des connaissances pour votre carrière, vos affaires et votre vie professionnelle.", sub:"Cours, formations professionnelles, programmes, livres et contenus numériques sur une seule plateforme.", see:"VOIR LES COURS ET FORMATIONS", subscribe:"S’ABONNER", helper:"Apprenez à votre rythme · Accédez de partout · Choisissez du gratuit, un achat unique ou un abonnement.", choose:"Que voulez-vous apprendre ?", chooseSub:"Trouvez rapidement le contenu adapté à votre objectif.", formations:"Formations", free:"Gratuits", business:"Affaires", books:"Livres", languages:"Langues", promo:"PROMO DU MOIS", promoTitle:"-50% LE PREMIER MOIS", promoText:"Un abonnement pour accéder aux contenus numériques payants tant qu’il reste actif.", firstMonth:"Premier mois", fromSecond:"À partir du 2e mois", promoCta:"S’ABONNER À -50%", formationTitle:"Choisissez votre formation", formationSub:"Des formations professionnelles tournées vers la pratique, la carrière et l’entreprise.", freeBadge:"100% GRATUIT", know:"DÉCOUVRIR", startFree:"COMMENCER GRATUITEMENT", entrepreneurship:"TRANSFORMEZ VOS CONNAISSANCES EN ACTIVITÉ", entrepreneurshipTitle:"De la Papaye à l’Entreprise", entrepreneurshipText:"90 leçons, 6 rencontres en direct, accès à vie et pratique du positionnement, de la vente et de la construction d’activité.", freeTitle:"Commencez gratuitement", freeText:"Entrez sans payer et découvrez l’expérience d’apprentissage de la Bibliothèque LDR.", compare:"Choisissez votre accès", oneTime:"Acheter individuellement", monthly:"S’abonner à la Bibliothèque", oneTimeText:"Paiement unique et accès à vie au contenu acheté.", monthlyText:"Accès aux contenus numériques payants tant que l’abonnement est actif.", reading:"La lecture fait aussi partie de votre formation", how:"Comment ça marche", step1:"1. Choisissez", step1t:"Sélectionnez un cours, une formation ou un abonnement.", step2:"2. Accédez", step2t:"Utilisez la Bibliothèque LDR sur ordinateur ou mobile.", step3:"3. Apprenez", step3t:"Étudiez à votre rythme et suivez votre progression.", story:"Un savoir construit dans la pratique.", storyText:"De Bahia à l’Europe, des expériences en RH, carrière, affaires et entrepreneuriat sont devenues des contenus pratiques.", faq:"Questions fréquentes", final:"Votre prochaine étape peut commencer ici.", finalSub:"Choisissez une formation, commencez gratuitement ou accédez à la Bibliothèque LDR."},
  es: {
    brand:"Biblioteca LDR", login:"Entrar", eyebrow:"CURSOS · FORMACIONES · CONOCIMIENTO", title:"Conocimiento para tu carrera, tus negocios y tu vida profesional.", sub:"Cursos, formaciones profesionales, entrenamientos, libros y contenidos digitales en una sola plataforma.", see:"VER CURSOS Y FORMACIONES", subscribe:"SUSCRIBIRME", helper:"Aprende a tu ritmo · Accede desde cualquier lugar · Elige contenido gratuito, compra individual o suscripción.", choose:"¿Qué quieres aprender?", chooseSub:"Encuentra rápidamente el contenido ideal para tu momento.", formations:"Formaciones", free:"Gratis", business:"Negocios", books:"Libros", languages:"Idiomas", promo:"PROMO DU MOIS", promoTitle:"50% EN EL PRIMER MES", promoText:"Una suscripción para acceder a los contenidos digitales de pago mientras esté activa.", firstMonth:"Primer mes", fromSecond:"Desde el 2º mes", promoCta:"SUSCRIBIRME CON 50%", formationTitle:"Elige tu formación", formationSub:"Formaciones profesionales orientadas a la práctica, la carrera y los negocios.", freeBadge:"100% GRATIS", know:"CONOCER FORMACIÓN", startFree:"EMPEZAR GRATIS", entrepreneurship:"TRANSFORMA CONOCIMIENTO EN NEGOCIO", entrepreneurshipTitle:"Del Mamón al Negocio", entrepreneurshipText:"90 clases, 6 encuentros en vivo, acceso vitalicio y práctica en posicionamiento, ventas y construcción de negocio.", freeTitle:"Empieza gratis", freeText:"Entra sin pagar y conoce la experiencia de aprendizaje de la Biblioteca LDR.", compare:"Elige cómo acceder", oneTime:"Comprar individualmente", monthly:"Suscribirse a la Biblioteca", oneTimeText:"Pago único y acceso vitalicio al contenido comprado.", monthlyText:"Acceso a los contenidos digitales de pago mientras la suscripción esté activa.", reading:"La lectura también forma parte del aprendizaje", how:"Cómo funciona", step1:"1. Elige", step1t:"Selecciona tu curso, formación o suscripción.", step2:"2. Accede", step2t:"Usa la Biblioteca LDR desde ordenador o móvil.", step3:"3. Aprende", step3t:"Estudia a tu ritmo y sigue tu progreso.", story:"Conocimiento construido en la práctica.", storyText:"De Bahía a Europa, experiencias en personas, negocios, carrera y emprendimiento se transformaron en contenido práctico.", faq:"Preguntas frecuentes", final:"Tu próximo paso puede empezar aquí.", finalSub:"Elige una formación, empieza gratis o accede a la Biblioteca LDR."}
} as const;

const formations = [
  {tag:"RH · 600H",title:"Formação em Gestão de Pessoas e Recursos Humanos",desc:"600 horas · 100% online · leitura e atividades",free:true,href:"/cliente/formacoes/gestao-pessoas-rh",tone:"emerald"},
  {tag:"PSICANÁLISE",title:"Formação Online em Psicanálise",desc:"12 módulos · 1.200 horas · 180 unidades · 6 encontros ao vivo",price:"R$ 299,99 · € 49,90",href:"/formacao-psicanalise",tone:"violet"},
  {tag:"TERAPIA BREVE · 1.200H",title:"Formação em Terapia Breve Psicanalítica",desc:"15 módulos · 300 aulas · 1.200 horas · 6 encontros ao vivo",price:"R$ 299,99 · € 49,90",href:"/formacao-terapia-breve-psicanalitica",tone:"petrol"},
  {tag:"NEGÓCIO EM 24H",title:"Formação Negócio em 24 Horas",desc:"9 módulos · 90 aulas · 360 horas · 100% online · projeto final avaliado",price:"R$ 299,99 · € 49,90",href:"/formacao-negocio-em-24-horas",tone:"gold"},
  {tag:"MENTORIA E CARREIRA",title:"Formação em Mentoria Profissional e de Carreira",desc:"3 meses · percurso estruturado · acesso digital",price:"R$ 299,99 · € 49,90",href:"/cliente/biblioteca",tone:"blue"},
  {tag:"LIDERANÇA",title:"Formação em Liderança e Gestão de Pessoas",desc:"3 meses · percurso estruturado · acesso digital",price:"R$ 299,99 · € 49,90",href:"/cliente/biblioteca",tone:"green"},
] as const;
const freeCourses=[
  ["Gestão de Pessoas e RH","600h · formação livre profissional","/cliente/formacoes/gestao-pessoas-rh"],
  ["Organize sua Carreira","7 aulas · leitura · sem expiração","/cliente/cursos/organizar-carreira"],
  ["Francês Básico para Negócios — A1","30 aulas · 10 horas","/cliente/cursos/frances-negocios-a1"],
  ["Primeiros Socorros — Noções Básicas","30 aulas · 10 horas","/cliente/cursos/primeiros-socorros"],
] as const;

export function LibrarySalesHome(){
  const {locale:raw}=useI18n(); const locale=(raw==="pt"||raw==="en"||raw==="fr"||raw==="es"?raw:"pt") as Locale; const t=COPY[locale]; const {formations,freeCourses}=librarySalesCardCatalog(locale); const promo=Date.now()<PROMO_END_AT;
  const faq = locale==="pt" ? [
    ["Preciso pagar para entrar na Biblioteca?","Não. Há conteúdos gratuitos. Os conteúdos pagos podem ser comprados individualmente ou acessados pela assinatura enquanto ela estiver ativa."],
    ["Posso comprar uma formação sem assinar?","Sim. A compra individual é independente da assinatura e mantém acesso vitalício ao conteúdo comprado."],
    ["O que acontece se eu cancelar a assinatura?","O acesso derivado da assinatura termina conforme o período contratado. Compras vitalícias continuam disponíveis."],
    ["A formação de RH de 600h é graduação?","Não. É uma formação livre de caráter profissional e não corresponde a graduação ou diploma de nível superior reconhecido pelo MEC."],
  ] : [];
  return <main className="min-h-screen bg-[#f7f3e9] text-[#071426]">
    <header className="sticky top-0 z-50 border-b border-[#d6ad63]/25 bg-[#071426]/95 text-white backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6"><a href="#top" className="font-serif text-xl text-[#fff7e7]">{t.brand}</a><div className="flex items-center gap-2"><LanguageSelect/><Link to="/cliente/login" className="rounded-lg border border-white/15 px-3 py-2 text-xs font-black">{t.login}</Link></div></div></header>

    <section id="top" className="bg-gradient-to-br from-[#071426] via-[#0b2341] to-[#12365c] text-white"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 lg:grid-cols-[1.2fr_.8fr] lg:py-24"><div><p className="text-xs font-black uppercase tracking-[.24em] text-[#d6ad63]">{t.eyebrow}</p><h1 className="mt-5 max-w-4xl font-serif text-4xl leading-tight text-[#fff7e7] sm:text-6xl">{t.title}</h1><p className="mt-5 max-w-2xl text-base leading-7 text-white/75 sm:text-lg">{t.sub}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#formacoes" className="rounded-xl bg-[#d6ad63] px-5 py-3 text-center text-sm font-black text-[#281605]">{t.see}</a><Link to="/cliente/biblioteca" className="rounded-xl border border-white/20 bg-white/10 px-5 py-3 text-center text-sm font-black">{t.subscribe}</Link></div><p className="mt-4 text-xs leading-5 text-white/55">{t.helper}</p></div><div className="rounded-[28px] border border-white/10 bg-white/5 p-6 shadow-2xl"><div className="flex items-center gap-3"><Library className="h-8 w-8 text-[#d6ad63]"/><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#d6ad63]">Biblioteca LDR</p><p className="text-sm text-white/70">Cursos e formações em um só lugar</p></div></div><div className="mt-6 grid grid-cols-2 gap-3 text-sm">{[["600h","Formação gratuita RH"],["5","Formações profissionais"],["3+","Cursos gratuitos"],["PT/EN/FR/ES","Plataforma multilíngue"]].map(([a,b])=><div key={b} className="rounded-2xl bg-white/10 p-4"><p className="text-2xl font-black text-[#f2cf83]">{a}</p><p className="mt-1 text-xs text-white/65">{b}</p></div>)}</div></div></div></section>

    <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><div className="text-center"><h2 className="font-serif text-3xl">{locale==="pt"?"O que você quer fazer hoje?":locale==="fr"?"Que voulez-vous faire aujourd’hui ?":locale==="es"?"¿Qué quieres hacer hoy?":"What do you want to do today?"}</h2><p className="mt-2 text-sm text-slate-600">{locale==="pt"?"Escolha seu objetivo e encontre o conteúdo certo para você.":locale==="fr"?"Choisissez votre objectif et trouvez le contenu qui vous convient.":locale==="es"?"Elige tu objetivo y encuentra el contenido adecuado para ti.":"Choose your goal and find the right content for you."}</p></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[[locale==="pt"?"Aprender uma profissão":locale==="fr"?"Apprendre un métier":locale==="es"?"Aprender una profesión":"Learn a profession","#formacoes",GraduationCap],[locale==="pt"?"Melhorar meu negócio":locale==="fr"?"Développer mon activité":locale==="es"?"Mejorar mi negocio":"Grow my business","#negocios",BriefcaseBusiness],[locale==="pt"?"Desenvolver minha carreira":locale==="fr"?"Développer ma carrière":locale==="es"?"Desarrollar mi carrera":"Develop my career","#formacoes",Sparkles],[locale==="pt"?"Ler e me atualizar":locale==="fr"?"Lire et m’informer":locale==="es"?"Leer y actualizarme":"Read and stay informed","#editorial-ldr",BookOpen],[locale==="pt"?"Começar gratuitamente":locale==="fr"?"Commencer gratuitement":locale==="es"?"Empezar gratis":"Start for free","#gratuitos",Languages]].map(([label,href,Icon]:any)=><a key={label} href={href} className="group flex items-center justify-between rounded-2xl border border-[#d9cfba] bg-white p-4 shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><span className="flex items-center gap-3 font-black"><Icon className="h-5 w-5 text-[#a77b2e]"/>{label}</span><ChevronRight className="h-4 w-4 text-slate-400"/></a>)}</div></section>

    {promo?<section className="mx-auto max-w-7xl px-4 pb-10 sm:px-6"><div className="rounded-[30px] bg-[#071426] p-6 text-white shadow-xl sm:p-8"><div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><span className="rounded-full bg-[#ffd84d] px-3 py-1 text-[10px] font-black uppercase tracking-[.15em] text-[#2d2100]">{t.promo}</span><h2 className="mt-4 font-serif text-3xl text-[#fff7e7]">{t.promoTitle}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-white/70">{t.promoText}</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-white/60">{t.firstMonth}</p><p className="mt-1 text-2xl font-black text-[#ffd84d]">R$ 19,95 · € 4,95</p></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-white/60">{t.fromSecond}</p><p className="mt-1 text-2xl font-black">R$ 39,90 · € 9,90</p></div><Link to="/cliente/biblioteca" className="sm:col-span-2 rounded-xl bg-[#d6ad63] px-5 py-3 text-center text-sm font-black text-[#281605]">{t.promoCta}</Link></div></div></div></section>:null}

    <section id="formacoes" className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><div className="max-w-3xl"><p className="text-xs font-black uppercase tracking-[.2em] text-[#a77b2e]">FORMAÇÕES PROFISSIONAIS</p><h2 className="mt-2 font-serif text-4xl">{t.formationTitle}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{t.formationSub}</p></div><div className="mt-8 grid gap-5 md:grid-cols-2 xl:grid-cols-5">{formations.map(f=><article key={f.title} className="flex flex-col rounded-[26px] border border-[#d9cfba] bg-white p-5 shadow-sm"><span className="w-fit rounded-full bg-[#071426] px-3 py-1 text-[10px] font-black uppercase tracking-[.12em] text-white">{f.free?t.freeBadge:f.tag}</span><h3 className="mt-4 font-serif text-2xl leading-tight">{f.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{f.desc}</p>{f.free?<p className="mt-4 text-xl font-black text-emerald-700">GRÁTIS</p>:<p className="mt-4 text-lg font-black text-[#0b2341]">{f.price}</p>}<a href={f.href} className="mt-auto pt-6"><span className={`block rounded-xl px-4 py-3 text-center text-sm font-black text-white ${f.free?"bg-emerald-700":"bg-[#0b2341]"}`}>{f.free?t.startFree:t.know}</span></a></article>)}</div></section>

    <section id="negocios" className="bg-[#0b2341] text-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-14 sm:px-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#d6ad63]">{t.entrepreneurship}</p><h2 className="mt-3 font-serif text-4xl text-[#fff7e7]">{t.entrepreneurshipTitle}</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-white/70">{t.entrepreneurshipText}</p><div className="mt-5 flex flex-wrap gap-2">{["90 aulas","6 encontros ao vivo","Acesso vitalício","Posicionamento","Vendas"].map(x=><span key={x} className="rounded-full bg-white/10 px-3 py-1.5 text-xs">✓ {x}</span>)}</div></div><div className="rounded-2xl bg-white p-5 text-[#071426]"><p className="text-2xl font-black">R$ 299,99</p><p className="text-lg font-black">€ 49,90</p><a href="/treinamento" className="mt-4 block rounded-xl bg-[#d6ad63] px-5 py-3 text-center text-sm font-black text-[#281605]">{t.know}</a></div></div></section>

    <section id="gratuitos" className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><h2 className="font-serif text-4xl">{t.freeTitle}</h2><p className="mt-2 text-sm text-slate-600">{t.freeText}</p><div className="mt-7 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{freeCourses.map(([name,desc,href])=><article key={name} className="rounded-2xl border border-[#b8d8c8] bg-[#f6fbf8] p-5"><span className="text-[10px] font-black uppercase tracking-[.12em] text-emerald-700">{t.freeBadge}</span><h3 className="mt-3 font-serif text-xl">{name}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{desc}</p><a href={href} className="mt-5 block rounded-xl bg-emerald-700 px-4 py-3 text-center text-sm font-black text-white">{t.startFree}</a></article>)}</div></section>

    <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><h2 className="text-center font-serif text-4xl">{t.compare}</h2><div className="mx-auto mt-7 grid max-w-4xl gap-5 md:grid-cols-2"><article className="rounded-[26px] border bg-white p-6"><h3 className="font-serif text-2xl">{t.oneTime}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{t.oneTimeText}</p><div className="mt-4 space-y-2 text-sm"><p>✓ Pagamento único</p><p>✓ Acesso vitalício ao conteúdo comprado</p><p>✓ Ideal para uma formação específica</p></div></article><article className="rounded-[26px] bg-[#071426] p-6 text-white"><h3 className="font-serif text-2xl text-[#fff7e7]">{t.monthly}</h3><p className="mt-3 text-sm leading-6 text-white/70">{t.monthlyText}</p><div className="mt-4 space-y-2 text-sm"><p>✓ Conteúdos digitais pagos incluídos</p><p>✓ Acesso enquanto ativa</p><p>✓ Cancele conforme as regras atuais</p></div><Link to="/cliente/biblioteca" className="mt-5 block rounded-xl bg-[#d6ad63] px-4 py-3 text-center text-sm font-black text-[#281605]">{t.subscribe}</Link></article></div></section>

    <section id="livros" className="bg-white"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><h2 className="font-serif text-4xl">{t.reading}</h2><div className="mt-7 grid gap-4 md:grid-cols-2"><article className="rounded-2xl border p-6"><p className="text-xs font-black uppercase text-[#a77b2e]">eBook</p><h3 className="mt-2 font-serif text-2xl">A Coragem de Começar</h3><Link to="/cliente/biblioteca" className="mt-5 inline-block rounded-xl bg-[#0b2341] px-4 py-3 text-sm font-black text-white">VER EBOOK</Link></article><article className="rounded-2xl border p-6"><p className="text-xs font-black uppercase text-[#a77b2e]">Livro</p><h3 className="mt-2 font-serif text-2xl">O Menino que Vendia Mamão</h3><Link to="/cliente/biblioteca" className="mt-5 inline-block rounded-xl bg-[#0b2341] px-4 py-3 text-sm font-black text-white">VER LIVRO</Link></article></div></div></section>

    <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><h2 className="text-center font-serif text-4xl">{t.how}</h2><div className="mt-8 grid gap-4 md:grid-cols-3">{[[t.step1,t.step1t],[t.step2,t.step2t],[t.step3,t.step3t]].map(([a,b])=><article key={a} className="rounded-2xl border bg-white p-6"><h3 className="font-serif text-2xl">{a}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{b}</p></article>)}</div></section>

    <section className="bg-[#efe7d6]"><div className="mx-auto max-w-5xl px-4 py-14 text-center sm:px-6"><p className="text-xs font-black uppercase tracking-[.2em] text-[#a77b2e]">GRUPO LDR ESSENCE</p><h2 className="mt-3 font-serif text-4xl">{t.story}</h2><p className="mx-auto mt-4 max-w-3xl text-sm leading-7 text-slate-700">{t.storyText}</p></div></section>

    {locale==="pt"?<section className="mx-auto max-w-5xl px-4 py-14 sm:px-6"><h2 className="font-serif text-4xl">{t.faq}</h2><div className="mt-6 space-y-3">{faq.map(([q,a])=><details key={q} className="rounded-2xl border bg-white p-5"><summary className="cursor-pointer font-black">{q}</summary><p className="mt-3 text-sm leading-6 text-slate-600">{a}</p></details>)}</div></section>:null}

    <section className="bg-[#071426] text-white"><div className="mx-auto max-w-5xl px-4 py-16 text-center sm:px-6"><h2 className="font-serif text-4xl text-[#fff7e7]">{t.final}</h2><p className="mx-auto mt-3 max-w-2xl text-sm text-white/70">{t.finalSub}</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><a href="#formacoes" className="rounded-xl bg-[#d6ad63] px-5 py-3 text-sm font-black text-[#281605]">{t.see}</a><Link to="/cliente/biblioteca" className="rounded-xl border border-white/20 bg-white/10 px-5 py-3 text-sm font-black">{t.subscribe}</Link></div></div></section>
  

    <section id="editorial-ldr" className="mx-auto max-w-7xl px-4 py-10 sm:px-6 sm:py-14">
      <div className="mb-6 max-w-3xl">
        <p className="text-xs font-black uppercase tracking-[.22em] text-[#a77b2e]">JORNAL & REVISTA LDR</p>
        <h2 className="mt-2 font-serif text-3xl text-[#071426] sm:text-4xl">Informação e inspiração, toda semana.</h2>
        <p className="mt-3 text-sm leading-6 text-slate-600">Assinaturas editoriais independentes da Biblioteca LDR. Assine o Jornal ou a Revista separadamente.</p>
      </div>
      <div className="grid gap-5 md:grid-cols-2">
        <a href="/cliente/biblioteca/jornal-ldr" className="group rounded-[28px] bg-gradient-to-br from-[#071426] via-[#0b2341] to-[#163b67] p-6 text-white shadow-lg transition hover:-translate-y-1 hover:shadow-xl sm:p-8">
          <p className="text-xs font-black uppercase tracking-[.2em] text-[#d6ad63]">📰 JORNAL LDR</p>
          <h3 className="mt-3 font-serif text-3xl text-[#fff7e7]">O mundo em movimento</h3>
          <p className="mt-3 text-sm leading-6 text-white/75">Negócios, ciência, tecnologia, mundo e entretenimento em uma edição digital.</p>
          <div className="mt-6 flex flex-wrap items-end justify-between gap-4">
            <div><p className="text-2xl font-black">R$ 0,90 <span className="text-sm font-semibold text-white/60">/ semana</span></p><p className="mt-1 text-sm font-bold text-[#d6ad63]">€ 0,90 / semana</p></div>
            <span className="rounded-xl bg-[#d6ad63] px-4 py-3 text-xs font-black text-[#281605]">ASSINAR JORNAL →</span>
          </div>
        </a>
        <a href="/cliente/biblioteca/revista-ldr" className="group rounded-[28px] bg-gradient-to-br from-[#4c071d] via-[#6b0d2b] to-[#2a0a15] p-6 text-white shadow-lg transition hover:-translate-y-1 hover:shadow-xl sm:p-8">
          <p className="text-xs font-black uppercase tracking-[.2em] text-[#f0c775]">📖 REVISTA LDR</p>
          <h3 className="mt-3 font-serif text-3xl text-[#fff7e7]">Ideias que movem pessoas e negócios</h3>
          <p className="mt-3 text-sm leading-6 text-white/75">Carreira, empreendedorismo, comportamento, inovação e histórias que inspiram.</p>
          <div className="mt-6 flex flex-wrap items-end justify-between gap-4">
            <div><p className="text-2xl font-black">R$ 0,90 <span className="text-sm font-semibold text-white/60">/ semana</span></p><p className="mt-1 text-sm font-bold text-[#f0c775]">€ 0,90 / semana</p></div>
            <span className="rounded-xl bg-[#f0c775] px-4 py-3 text-xs font-black text-[#35101e]">ASSINAR REVISTA →</span>
          </div>
        </a>
      </div>
      <p className="mt-4 text-xs text-slate-500">Jornal LDR, Revista LDR e Biblioteca LDR possuem assinaturas separadas. A contratação de uma não libera automaticamente as outras.</p>
    </section>
</main>;
}
