import { Link } from "@tanstack/react-router";
import { BookOpen, Check, GraduationCap, Library, Sparkles } from "lucide-react";
import { LanguageSelect, useI18n } from "@/lib/i18n";

const PROMO_END_AT = new Date("2026-09-12T16:46:00.000Z").getTime();
type Locale = "pt" | "en" | "fr" | "es";

const copy = {
  pt: {
    brand:"Biblioteca LDR", login:"Entrar", eyebrow:"CURSOS · FORMAÇÕES · CONHECIMENTO",
    title:"Escolha o que quer aprender — e como quer acessar.",
    sub:"Na Biblioteca LDR, você pode comprar uma formação individualmente e ter acesso vitalício ao conteúdo comprado, ou assinar mensalmente e acessar os conteúdos digitais pagos enquanto a assinatura estiver ativa.",
    see:"VER CURSOS E FORMAÇÕES", subscribe:"ASSINAR A BIBLIOTECA",
    choose:"Escolha sua forma de acesso", lifetime:"PAGAMENTO ÚNICO · ACESSO VITALÍCIO", lifetimeText:"Ideal para quem quer uma formação específica. Você paga uma única vez e mantém acesso vitalício ao conteúdo comprado.",
    monthly:"ASSINATURA MENSAL · ESTILO NETFLIX", monthlyText:"Ideal para quem quer explorar vários conteúdos. Enquanto a assinatura estiver ativa, você acessa os conteúdos digitais pagos incluídos na Biblioteca. Cancele quando quiser.",
    promo:"⚡ PROMOÇÃO DE 24 HORAS · 50% NO PRIMEIRO MÊS", first:"🇧🇷 R$ 19,95  ·  🇪🇺 € 4,95", after:"A partir do segundo mês: R$ 39,90/mês ou € 9,90/mês. Cancele quando quiser.",
    formations:"Formações em destaque", psycho:"Formação Online em Psicanálise", psychoMeta:"12 módulos · 1.200 horas · 180 unidades · 6 encontros ao vivo", psychoFocus:"DESTAQUE ESPECIAL", psychoAutism:"Autismo na Clínica Psicanalítica: Teoria, Manejo e Casos Clínicos", psychoText:"A formação inclui um módulo específico dedicado ao estudo do autismo na clínica psicanalítica, articulando fundamentos teóricos, manejo clínico e discussão de casos clínicos.",
    onePrice:"Compra individual: R$ 299,99 · € 49,90 · acesso vitalício", orSub:"Ou acesse pela assinatura mensal enquanto ela estiver ativa.", know:"CONHECER A FORMAÇÃO",
    rh:"Formação em Gestão de Pessoas e Recursos Humanos", rhMeta:"600 horas · 100% online · formação livre profissional", free:"100% GRATUITA", start:"COMEÇAR GRATUITAMENTE",
    mentorship:"Formação em Mentoria Profissional e de Carreira", leadership:"Formação em Liderança e Gestão de Pessoas", price:"R$ 299,99 · € 49,90 · pagamento único · acesso vitalício",
    entrepreneurship:"Do Mamão ao Negócio", entrepreneurshipText:"90 aulas · 6 encontros ao vivo · aplicação prática em posicionamento, vendas e construção do negócio.",
    howTitle:"Qual opção combina mais com você?", buyTitle:"Quero apenas uma formação", buyText:"Escolha a compra individual. Pagamento único e acesso vitalício ao conteúdo comprado.", subTitle:"Quero acessar vários conteúdos", subText:"Escolha a assinatura mensal. Você acessa os conteúdos digitais pagos incluídos enquanto a assinatura estiver ativa.",
    final:"Comece do seu jeito.", finalText:"Você decide: acesso vitalício a uma formação específica ou assinatura mensal para explorar a Biblioteca LDR.",
  },
  en: { brand:"LDR Library", login:"Sign in", eyebrow:"COURSES · TRAINING · KNOWLEDGE", title:"Choose what you want to learn — and how you want to access it.", sub:"Buy a program once for lifetime access to what you purchased, or subscribe monthly to access included paid digital content while your subscription is active.", see:"VIEW COURSES & TRAINING", subscribe:"SUBSCRIBE", choose:"Choose your access", lifetime:"ONE-TIME PAYMENT · LIFETIME ACCESS", lifetimeText:"Best if you want one specific program. Pay once and keep lifetime access to what you purchased.", monthly:"MONTHLY SUBSCRIPTION", monthlyText:"Best if you want multiple contents. Access included paid digital content while active. Cancel anytime.", promo:"⚡ 24-HOUR PROMO · 50% OFF FIRST MONTH", first:"🇧🇷 R$ 19.95  ·  🇪🇺 €4.95", after:"From month two: R$39.90/month or €9.90/month. Cancel anytime.", formations:"Featured programs", psycho:"Online Psychoanalysis Program", psychoMeta:"12 modules · 1,200 hours · 180 units · 6 live meetings", psychoFocus:"SPECIAL HIGHLIGHT", psychoAutism:"Autism in Psychoanalytic Clinic: Theory, Clinical Management and Cases", psychoText:"The program includes a specific module on autism in psychoanalytic clinical practice, combining theory, clinical management and case discussion.", onePrice:"Individual purchase: R$299.99 · €49.90 · lifetime access", orSub:"Or access through the monthly subscription while active.", know:"LEARN MORE", rh:"People Management and Human Resources", rhMeta:"600 hours · 100% online · professional free course", free:"100% FREE", start:"START FREE", mentorship:"Professional & Career Mentoring", leadership:"Leadership & People Management", price:"R$299.99 · €49.90 · one-time · lifetime access", entrepreneurship:"From Papaya to Business", entrepreneurshipText:"90 lessons · 6 live meetings · practical positioning, sales and business building.", howTitle:"Which option fits you?", buyTitle:"I want one program", buyText:"Choose individual purchase. One-time payment and lifetime access to what you buy.", subTitle:"I want several contents", subText:"Choose monthly subscription. Access included paid digital content while active.", final:"Start your way.", finalText:"You choose: lifetime access to a specific program or monthly access to explore the LDR Library." },
  fr: { brand:"Bibliothèque LDR", login:"Entrer", eyebrow:"COURS · FORMATIONS · CONNAISSANCE", title:"Choisissez ce que vous voulez apprendre — et comment y accéder.", sub:"Achetez une formation une seule fois avec accès à vie, ou abonnez-vous mensuellement pour accéder aux contenus numériques payants inclus tant que l’abonnement est actif.", see:"VOIR LES COURS", subscribe:"S’ABONNER", choose:"Choisissez votre accès", lifetime:"PAIEMENT UNIQUE · ACCÈS À VIE", lifetimeText:"Idéal pour une formation précise. Un seul paiement et accès à vie au contenu acheté.", monthly:"ABONNEMENT MENSUEL", monthlyText:"Idéal pour plusieurs contenus. Accès aux contenus payants inclus tant que l’abonnement est actif. Annulez quand vous voulez.", promo:"⚡ PROMO 24H · -50% LE PREMIER MOIS", first:"🇧🇷 R$ 19,95  ·  🇪🇺 € 4,95", after:"Dès le 2e mois : R$ 39,90/mois ou € 9,90/mois. Annulez quand vous voulez.", formations:"Formations à la une", psycho:"Formation en Psychanalyse", psychoMeta:"12 modules · 1 200 heures · 180 unités · 6 rencontres en direct", psychoFocus:"MISE EN AVANT", psychoAutism:"Autisme en clinique psychanalytique : théorie, maniement clinique et cas cliniques", psychoText:"La formation comprend un module spécifique consacré à l’autisme en clinique psychanalytique, avec théorie, maniement clinique et discussion de cas.", onePrice:"Achat individuel : R$ 299,99 · € 49,90 · accès à vie", orSub:"Ou via l’abonnement mensuel tant qu’il reste actif.", know:"DÉCOUVRIR", rh:"Gestion des Personnes et Ressources Humaines", rhMeta:"600 heures · 100% en ligne · formation libre professionnelle", free:"100% GRATUIT", start:"COMMENCER GRATUITEMENT", mentorship:"Mentorat Professionnel et de Carrière", leadership:"Leadership et Gestion des Personnes", price:"R$ 299,99 · € 49,90 · paiement unique · accès à vie", entrepreneurship:"De la Papaye à l’Entreprise", entrepreneurshipText:"90 leçons · 6 rencontres en direct · positionnement, vente et construction d’activité.", howTitle:"Quelle option vous convient ?", buyTitle:"Je veux une seule formation", buyText:"Choisissez l’achat individuel : paiement unique et accès à vie au contenu acheté.", subTitle:"Je veux plusieurs contenus", subText:"Choisissez l’abonnement mensuel : accès aux contenus payants inclus tant qu’il est actif.", final:"Commencez à votre façon.", finalText:"À vous de choisir : accès à vie à une formation précise ou abonnement mensuel à la Bibliothèque LDR." },
  es: { brand:"Biblioteca LDR", login:"Entrar", eyebrow:"CURSOS · FORMACIONES · CONOCIMIENTO", title:"Elige qué quieres aprender — y cómo quieres acceder.", sub:"Compra una formación una sola vez con acceso vitalicio, o suscríbete mensualmente para acceder a los contenidos digitales de pago incluidos mientras la suscripción esté activa.", see:"VER CURSOS", subscribe:"SUSCRIBIRME", choose:"Elige tu acceso", lifetime:"PAGO ÚNICO · ACCESO VITALICIO", lifetimeText:"Ideal si quieres una formación específica. Pagas una vez y mantienes acceso vitalicio al contenido comprado.", monthly:"SUSCRIPCIÓN MENSUAL", monthlyText:"Ideal si quieres varios contenidos. Accede a los contenidos digitales de pago incluidos mientras esté activa. Cancela cuando quieras.", promo:"⚡ PROMOCIÓN 24H · 50% PRIMER MES", first:"🇧🇷 R$ 19,95  ·  🇪🇺 € 4,95", after:"Desde el segundo mes: R$ 39,90/mes o € 9,90/mes. Cancela cuando quieras.", formations:"Formaciones destacadas", psycho:"Formación Online en Psicoanálisis", psychoMeta:"12 módulos · 1.200 horas · 180 unidades · 6 encuentros en vivo", psychoFocus:"DESTACADO ESPECIAL", psychoAutism:"Autismo en la Clínica Psicoanalítica: Teoría, Manejo y Casos Clínicos", psychoText:"La formación incluye un módulo específico sobre autismo en la clínica psicoanalítica, articulando teoría, manejo clínico y discusión de casos.", onePrice:"Compra individual: R$ 299,99 · € 49,90 · acceso vitalicio", orSub:"O accede mediante la suscripción mensual mientras esté activa.", know:"CONOCER FORMACIÓN", rh:"Gestión de Personas y Recursos Humanos", rhMeta:"600 horas · 100% online · formación libre profesional", free:"100% GRATIS", start:"EMPEZAR GRATIS", mentorship:"Mentoría Profesional y de Carrera", leadership:"Liderazgo y Gestión de Personas", price:"R$ 299,99 · € 49,90 · pago único · acceso vitalicio", entrepreneurship:"Del Mamón al Negocio", entrepreneurshipText:"90 clases · 6 encuentros en vivo · posicionamiento, ventas y construcción de negocio.", howTitle:"¿Qué opción te conviene?", buyTitle:"Quiero una sola formación", buyText:"Elige compra individual: pago único y acceso vitalicio al contenido comprado.", subTitle:"Quiero varios contenidos", subText:"Elige suscripción mensual: acceso a los contenidos de pago incluidos mientras esté activa.", final:"Empieza a tu manera.", finalText:"Tú decides: acceso vitalicio a una formación específica o suscripción mensual a la Biblioteca LDR." }
} as const;

const tone = { violet:"border-violet-200 bg-violet-50", blue:"border-blue-200 bg-blue-50", emerald:"border-emerald-200 bg-emerald-50", gold:"border-[#d6ad63]/40 bg-[#fff9ed]" } as const;

export function LibrarySalesHomeAccessChoice(){
  const {locale:raw}=useI18n();
  const locale=(raw==="pt"||raw==="en"||raw==="fr"||raw==="es"?raw:"pt") as Locale;
  const t=copy[locale];
  const promo=Date.now()<PROMO_END_AT;
  return <main className="min-h-screen bg-[#f7f3e9] text-[#071426]">
    <header className="sticky top-0 z-50 border-b border-[#d6ad63]/25 bg-[#071426]/95 text-white backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6"><a href="#top" className="font-serif text-xl text-[#fff7e7]">{t.brand}</a><div className="flex items-center gap-2"><LanguageSelect/><Link to="/cliente/login" className="rounded-lg border border-white/15 px-3 py-2 text-xs font-black">{t.login}</Link></div></div></header>

    <section id="top" className="bg-gradient-to-br from-[#071426] via-[#0b2341] to-[#12365c] text-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:py-24"><p className="text-xs font-black uppercase tracking-[.24em] text-[#d6ad63]">{t.eyebrow}</p><h1 className="mt-5 max-w-4xl font-serif text-4xl leading-tight text-[#fff7e7] sm:text-6xl">{t.title}</h1><p className="mt-5 max-w-3xl text-base leading-7 text-white/80 sm:text-lg">{t.sub}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#formacoes" className="rounded-xl bg-[#d6ad63] px-5 py-3 text-center text-sm font-black text-[#281605]">{t.see}</a><Link to="/cliente/biblioteca" className="rounded-xl border border-white/20 bg-white/10 px-5 py-3 text-center text-sm font-black">{t.subscribe}</Link></div></div></section>

    <section className="mx-auto max-w-7xl px-4 py-12 sm:px-6"><h2 className="font-serif text-3xl sm:text-4xl">{t.choose}</h2><div className="mt-6 grid gap-5 lg:grid-cols-2"><div className="rounded-[28px] border border-[#d6ad63]/40 bg-white p-7 shadow-sm"><div className="flex items-center gap-3"><BookOpen className="h-6 w-6 text-[#a36d19]"/><p className="text-xs font-black uppercase tracking-[.17em] text-[#8a5d17]">{t.lifetime}</p></div><p className="mt-4 text-base leading-7 text-slate-700">{t.lifetimeText}</p><div className="mt-5 rounded-xl bg-[#f7f3e9] p-4 text-sm font-bold">R$ 299,99 · € 49,90 <span className="font-normal">— nas formações pagas atuais</span></div></div><div className="rounded-[28px] bg-[#071426] p-7 text-white shadow-sm"><div className="flex items-center gap-3"><Library className="h-6 w-6 text-[#d6ad63]"/><p className="text-xs font-black uppercase tracking-[.17em] text-[#d6ad63]">{t.monthly}</p></div><p className="mt-4 text-base leading-7 text-white/80">{t.monthlyText}</p><div className="mt-5 rounded-2xl border border-[#d6ad63]/35 bg-[#d6ad63]/10 p-5"><p className="text-sm font-black text-[#f5cc82]">{promo?t.promo:"ASSINATURA BIBLIOTECA LDR"}</p><p className="mt-2 text-2xl font-black">{promo?t.first:"🇧🇷 R$ 39,90/mês · 🇪🇺 € 9,90/mês"}</p>{promo&&<p className="mt-2 text-sm text-white/80">{t.after}</p>}</div><Link to="/cliente/biblioteca" className="mt-5 block rounded-xl bg-[#d6ad63] px-5 py-3 text-center text-sm font-black text-[#281605]">{promo?"ASSINAR COM 50% OFF":t.subscribe}</Link></div></div></section>

    <section className="mx-auto max-w-7xl px-4 pt-10 sm:px-6"><article className="overflow-hidden rounded-[30px] border-2 border-[#17645e]/35 bg-gradient-to-br from-[#edf8f5] to-white p-7 shadow-sm"><div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><span className="inline-flex rounded-full bg-[#17645e] px-3 py-1 text-[10px] font-black uppercase tracking-[.14em] text-white">NOVA FORMAÇÃO</span><p className="mt-4 text-xs font-black uppercase tracking-[.18em] text-[#17645e]">TERAPIA BREVE PSICANALÍTICA</p><h2 className="mt-2 font-serif text-3xl sm:text-4xl">{locale==='pt'?'Formação em Terapia Breve Psicanalítica':locale==='fr'?'Formation en Thérapie Brève Psychanalytique':locale==='es'?'Formación en Terapia Breve Psicoanalítica':'Brief Psychoanalytic Therapy Training'}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-600">{locale==='pt'?'15 módulos · 300 aulas · 1.200 horas · 6 encontros ao vivo. Do foco à alta, com fundamentos, técnica e prática clínica.':locale==='fr'?'15 modules · 300 leçons · 1 200 heures · 6 rencontres en direct. Des fondements à la pratique clinique.':locale==='es'?'15 módulos · 300 clases · 1.200 horas · 6 encuentros en vivo. Fundamentos, técnica y práctica clínica.':'15 modules · 300 lessons · 1,200 hours · 6 live meetings. Foundations, technique and clinical practice.'}</p><p className="mt-4 font-black text-[#103d3a]">R$ 299,99 · € 49,90 · {locale==='pt'?'pagamento único · acesso vitalício':locale==='fr'?'paiement unique · accès à vie':locale==='es'?'pago único · acceso vitalicio':'one-time payment · lifetime access'}</p></div><Link to="/formacao-terapia-breve-psicanalitica" className="rounded-xl bg-[#17645e] px-6 py-4 text-center text-sm font-black text-white shadow-sm">{locale==='pt'?'CONHECER A FORMAÇÃO':locale==='fr'?'DÉCOUVRIR LA FORMATION':locale==='es'?'CONOCER LA FORMACIÓN':'LEARN MORE'}</Link></div></article></section>

    <section className="mx-auto max-w-7xl px-4 pt-10 sm:px-6"><article className="overflow-hidden rounded-[30px] border-2 border-[#c85a24]/35 bg-gradient-to-br from-[#fff3e8] to-white p-7 shadow-sm"><div className="grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><span className="inline-flex rounded-full bg-[#c85a24] px-3 py-1 text-[10px] font-black uppercase tracking-[.14em] text-white">NOVA FORMAÇÃO · 100% ONLINE</span><p className="mt-4 text-xs font-black uppercase tracking-[.18em] text-[#c85a24]">NEGÓCIO EM 24 HORAS</p><h2 className="mt-2 font-serif text-3xl sm:text-4xl">Formação Negócio em 24 Horas</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-slate-600">9 módulos · 90 aulas · 360 horas · sem encontros ao vivo · projeto final avaliado. Da ideia à primeira oferta pronta para vender.</p><p className="mt-4 font-black text-[#8a3b17]">R$ 299,99 · € 49,90 · pagamento único · acesso vitalício</p></div><Link to="/formacao-negocio-em-24-horas" className="rounded-xl bg-[#c85a24] px-6 py-4 text-center text-sm font-black text-white shadow-sm">CONHECER A FORMAÇÃO</Link></div></article></section>

    <section id="formacoes" className="bg-white py-14"><div className="mx-auto max-w-7xl px-4 sm:px-6"><h2 className="font-serif text-3xl sm:text-4xl">{t.formations}</h2><div className="mt-8 grid gap-6 lg:grid-cols-2">
      <article className="relative overflow-hidden rounded-[30px] border-2 border-violet-300 bg-gradient-to-br from-violet-50 to-white p-7 shadow-sm"><div className="absolute right-0 top-0 rounded-bl-2xl bg-violet-700 px-4 py-2 text-[11px] font-black uppercase tracking-[.14em] text-white">{t.psychoFocus}</div><p className="text-xs font-black uppercase tracking-[.18em] text-violet-700">PSICANÁLISE</p><h3 className="mt-3 font-serif text-3xl">{t.psycho}</h3><p className="mt-3 text-sm text-slate-600">{t.psychoMeta}</p><div className="mt-6 rounded-2xl border border-violet-200 bg-violet-100/70 p-5"><p className="text-xs font-black uppercase tracking-[.14em] text-violet-700">MÓDULO EM EVIDÊNCIA</p><h4 className="mt-2 text-xl font-black text-violet-950">{t.psychoAutism}</h4><p className="mt-3 text-sm leading-6 text-violet-950/80">{t.psychoText}</p></div><div className="mt-5 space-y-2 text-sm"><p className="font-black">{t.onePrice}</p><p className="text-slate-600">{t.orSub}</p></div><Link to="/formacao-psicanalise" className="mt-6 inline-block rounded-xl bg-violet-700 px-5 py-3 text-sm font-black text-white">{t.know}</Link></article>

      <article className={`rounded-[30px] border p-7 ${tone.emerald}`}><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-700">RH · 600H</p><h3 className="mt-3 font-serif text-3xl">{t.rh}</h3><p className="mt-3 text-sm text-slate-600">{t.rhMeta}</p><span className="mt-5 inline-block rounded-full bg-emerald-700 px-3 py-1 text-xs font-black text-white">{t.free}</span><br/><Link to="/cliente/formacoes/gestao-pessoas-rh" className="mt-6 inline-block rounded-xl bg-emerald-700 px-5 py-3 text-sm font-black text-white">{t.start}</Link></article>

      {[{title:t.mentorship,tone:"blue" as const},{title:t.leadership,tone:"gold" as const}].map((x)=><article key={x.title} className={`rounded-[30px] border p-7 ${tone[x.tone]}`}><p className="text-xs font-black uppercase tracking-[.18em] text-[#8a5d17]">FORMAÇÃO PROFISSIONAL</p><h3 className="mt-3 font-serif text-2xl">{x.title}</h3><p className="mt-4 text-sm font-black">{t.price}</p><p className="mt-2 text-sm text-slate-600">{t.orSub}</p><Link to="/cliente/biblioteca" className="mt-6 inline-block rounded-xl bg-[#071426] px-5 py-3 text-sm font-black text-white">{t.know}</Link></article>)}
    </div></div></section>

    <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><div className="rounded-[30px] bg-gradient-to-r from-[#071426] to-[#12365c] p-7 text-white sm:p-10"><p className="text-xs font-black uppercase tracking-[.18em] text-[#d6ad63]">NEGÓCIOS E EMPREENDEDORISMO</p><h2 className="mt-3 font-serif text-3xl text-[#fff7e7]">{t.entrepreneurship}</h2><p className="mt-3 max-w-3xl text-white/75">{t.entrepreneurshipText}</p><div className="mt-5 flex flex-wrap gap-3 text-sm"><span className="rounded-full bg-white/10 px-3 py-2">R$ 299,99 · € 49,90 · acesso vitalício</span><span className="rounded-full bg-white/10 px-3 py-2">Também disponível pela assinatura ativa</span></div><Link to="/treinamento" className="mt-6 inline-block rounded-xl bg-[#d6ad63] px-5 py-3 text-sm font-black text-[#281605]">CONHECER TREINAMENTO</Link></div></section>

    <section className="bg-[#efe7d6] py-14"><div className="mx-auto max-w-7xl px-4 sm:px-6"><h2 className="font-serif text-3xl">{t.howTitle}</h2><div className="mt-6 grid gap-5 md:grid-cols-2"><div className="rounded-2xl bg-white p-6"><GraduationCap className="h-7 w-7 text-[#a36d19]"/><h3 className="mt-3 text-xl font-black">{t.buyTitle}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t.buyText}</p><ul className="mt-4 space-y-2 text-sm"><li><Check className="mr-2 inline h-4 w-4"/>Pagamento único</li><li><Check className="mr-2 inline h-4 w-4"/>Acesso vitalício ao conteúdo comprado</li></ul></div><div className="rounded-2xl bg-[#071426] p-6 text-white"><Sparkles className="h-7 w-7 text-[#d6ad63]"/><h3 className="mt-3 text-xl font-black">{t.subTitle}</h3><p className="mt-2 text-sm leading-6 text-white/70">{t.subText}</p><ul className="mt-4 space-y-2 text-sm"><li><Check className="mr-2 inline h-4 w-4"/>R$ 39,90/mês ou € 9,90/mês</li><li><Check className="mr-2 inline h-4 w-4"/>Cancele quando quiser</li></ul></div></div></div></section>

    <section className="mx-auto max-w-5xl px-4 py-16 text-center sm:px-6"><h2 className="font-serif text-4xl">{t.final}</h2><p className="mx-auto mt-4 max-w-2xl text-slate-600">{t.finalText}</p><div className="mt-7 flex flex-col justify-center gap-3 sm:flex-row"><a href="#formacoes" className="rounded-xl bg-[#071426] px-5 py-3 text-sm font-black text-white">VER FORMAÇÕES</a><Link to="/cliente/biblioteca" className="rounded-xl bg-[#d6ad63] px-5 py-3 text-sm font-black text-[#281605]">{t.subscribe}</Link></div></section>
  </main>;
}
