import { Link } from "@tanstack/react-router";
import { BookOpen, Brain, CheckCircle2, GraduationCap, Sparkles, UsersRound, Video } from "lucide-react";
import { LanguageSelect } from "@/lib/i18n";

const modules=[
["01","O Nascimento da Psicanálise e a Descoberta do Inconsciente","Freud, Breuer, Anna O., Associação Livre e Primeira Tópica."],
["02","A Estrutura da Personalidade — A Segunda Tópica","Id, Ego, Superego e o funcionamento dinâmico do aparelho psíquico."],
["03","O Desenvolvimento Psicossexual e o Complexo de Édipo","Sexualidade infantil, fases do desenvolvimento e estruturação do sujeito."],
["04","As Forças Psíquicas: Pulsões e Narcisismo","Trieb, Eros, pulsão de morte, narcisismo primário e secundário."],
["05","Os Mecanismos de Defesa do Ego","Recalque, projeção, sublimação, racionalização, negação e formação reativa."],
["06","As Manifestações do Inconsciente","Sonhos, atos falhos, esquecimentos, chistes e Psicopatologia da Vida Cotidiana."],
["07","Introdução à Técnica Clínica Psicanalítica","Associação Livre, Atenção Flutuante, enquadre, resistência e ética da escuta."],
["08","Transferência e Contratransferência","Repetição, transferência amorosa e hostil, contratransferência e manejo."],
["09","Os Caminhos Pós-Freudianos","Melanie Klein, Donald Winnicott e Jacques Lacan em perspectiva comparada."],
["10","O Mal-Estar na Atualidade — Psicanálise Aplicada","Sofrimento contemporâneo, burnout, redes sociais, imediatismo e cultura."],
] as const;

export function PsychoanalysisTrainingPage(){
 return <div className="min-h-screen bg-[#fbf8ff] text-[#241238]">
  <header className="border-b border-[#caa85d]/40 bg-[#32155c] text-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4 sm:px-6"><Link to="/" className="font-serif text-xl font-bold">Grupo LDR Essence</Link><LanguageSelect/></div></header>
  <main className="mx-auto max-w-6xl space-y-10 px-4 py-8 sm:px-6 sm:py-12">
   <section className="overflow-hidden rounded-[2rem] border border-[#caa85d] bg-gradient-to-br from-[#2a104e] via-[#4b2077] to-[#27103f] p-6 text-white shadow-2xl sm:p-10">
    <div className="grid gap-8 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div><span className="inline-flex items-center gap-2 rounded-full bg-[#d6b86d] px-3 py-1.5 text-xs font-black uppercase tracking-[.14em] text-[#32155c]"><Sparkles className="h-4 w-4"/>Primeira turma · lançamento</span><h1 className="mt-5 font-serif text-4xl font-bold leading-tight sm:text-6xl">Formação Online em Psicanálise</h1><p className="mt-4 max-w-2xl text-base leading-7 text-white/80 sm:text-lg">Fundamentos, técnica, clínica e formação psicanalítica em um percurso estruturado sobre teoria, análise pessoal e supervisão.</p><div className="mt-6 flex flex-wrap gap-2 text-sm font-bold"><span className="rounded-full bg-white/10 px-3 py-2">10 módulos</span><span className="rounded-full bg-white/10 px-3 py-2">6 encontros ao vivo</span><span className="rounded-full bg-white/10 px-3 py-2">6–12 meses</span><span className="rounded-full bg-white/10 px-3 py-2">Conteúdo digital vitalício</span></div></div>
    <div className="rounded-3xl border border-white/15 bg-white/10 p-6"><p className="text-xs font-black uppercase tracking-[.16em] text-[#efd58d]">Oferta de lançamento · primeiro mês</p><div className="mt-4 text-sm text-white/65"><span className="line-through">R$ 599,99</span><span className="mx-2">·</span><span className="line-through">€ 100,56</span></div><strong className="mt-2 block text-4xl">R$ 299,99</strong><strong className="mt-1 block text-2xl text-[#efd58d]">€ 49,90</strong><p className="mt-3 text-xs leading-5 text-white/75">Pagamento único. Acesso vitalício às aulas, textos, materiais e gravações disponibilizadas. Encontros, atividades e acompanhamento seguem o calendário da turma.</p><a href="/cliente/biblioteca" className="mt-6 inline-flex min-h-12 w-full items-center justify-center rounded-2xl bg-[#d6b86d] px-5 text-center text-sm font-black text-[#32155c]">QUERO COMEÇAR MINHA FORMAÇÃO</a></div></div>
   </section>
   <section><p className="text-xs font-black uppercase tracking-[.18em] text-[#7b4aa3]">O tripé da formação</p><h2 className="mt-2 font-serif text-3xl font-bold">Psicanálise se constrói em percurso</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{[[Brain,"Teoria","Estudo sistemático de Freud, conceitos fundamentais, autores pós-freudianos e aplicações contemporâneas."],[BookOpen,"Análise pessoal","A formação destaca a importância da própria análise como parte do percurso do psicanalista; ela não está incluída automaticamente na compra."],[UsersRound,"Supervisão","Desenvolvimento da escuta, reflexão sobre técnica e discussão orientada conforme a etapa da formação."]].map(([Icon,t,d]:any)=><article key={t} className="rounded-3xl border border-[#ded0eb] bg-white p-5 shadow-sm"><Icon className="h-7 w-7 text-[#5b2b86]"/><h3 className="mt-4 font-serif text-xl font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-[#66576f]">{d}</p></article>)}</div></section>
   <section className="rounded-[2rem] border border-[#ded0eb] bg-white p-6 sm:p-8"><h2 className="font-serif text-3xl font-bold">Como estudar Psicanálise</h2><p className="mt-3 max-w-4xl leading-7 text-[#66576f]">A proposta não é decorar conceitos. O percurso combina leitura dos textos originais, estudo teórico, reflexão clínica, análise pessoal, supervisão e estudo continuado. Cada módulo termina com uma atividade e uma seção “Para ir mais fundo”, com obras originais e referências legais para continuar a leitura.</p></section>
   <section><div className="flex items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#7b4aa3]">Grade da formação</p><h2 className="mt-2 font-serif text-3xl font-bold">10 módulos</h2></div></div><div className="mt-5 grid gap-3">{modules.map(([n,t,d])=><details key={n} className="group rounded-2xl border border-[#ded0eb] bg-white p-5"><summary className="cursor-pointer list-none font-bold"><span className="mr-3 text-[#8b5aae]">Módulo {n}</span>{t}</summary><p className="mt-3 pl-0 text-sm leading-6 text-[#66576f] sm:pl-20">{d} Ao final: atividade + “Para ir mais fundo” com 2 ou 3 leituras originais recomendadas.</p></details>)}</div></section>
   <section className="grid gap-4 md:grid-cols-3">{[[Video,"6 encontros ao vivo","Fundamentos, inconsciente, pulsões, técnica, clínica contemporânea e supervisão/fechamento."],[GraduationCap,"Professores convidados","A estrutura está preparada para participações especiais ao longo da formação, sem inventar nomes antes da confirmação."],[CheckCircle2,"Prática supervisionada","Alunos que cumprirem os requisitos poderão futuramente se candidatar a oportunidades na Rede LDR, conforme disponibilidade, avaliação e requisitos aplicáveis."]].map(([Icon,t,d]:any)=><article key={t} className="rounded-3xl bg-[#32155c] p-6 text-white"><Icon className="h-7 w-7 text-[#e2c372]"/><h3 className="mt-4 font-serif text-xl font-bold">{t}</h3><p className="mt-2 text-sm leading-6 text-white/75">{d}</p></article>)}</section>
   <section className="rounded-[2rem] border border-[#caa85d] bg-[#f5edfb] p-6 sm:p-8"><h2 className="font-serif text-3xl font-bold">Acesso vitalício aos conteúdos digitais</h2><p className="mt-3 leading-7 text-[#66576f]">Após o período formativo, aulas gravadas, textos, materiais e gravações disponibilizadas continuam acessíveis. Encontros ao vivo, atividades acompanhadas, supervisões e participação de professores seguem as condições e o calendário da turma.</p><a href="/cliente/biblioteca" className="mt-6 inline-flex min-h-12 items-center justify-center rounded-2xl bg-[#5b2b86] px-6 text-sm font-black text-white">GARANTIR VALOR DE LANÇAMENTO</a></section>
  </main>
 </div>
}
