import { Link } from "@tanstack/react-router";
import { ArrowRight, BookOpen, CheckCircle2, FileCheck2, GraduationCap, Sparkles, Video } from "lucide-react";
import { LanguageSelect, useI18n } from "@/lib/i18n";

const PANEL="https://painel.ldrrhestrategia.com";

const COPY={
pt:{badge:"OFERTA ESPECIAL DE LANÇAMENTO · PRIMEIROS 100 ALUNOS",title:"Do Mamão ao Negócio",lead:"Uma formação prática de 90 dias para qualquer pessoa transformar uma ideia em um negócio mais claro, testado e documentado.",normal:"Valor normal",launch:"Valor de lançamento",normalBR:"R$ 299,99",normalEU:"€ 49,90",launchBR:"R$ 299,99",launchEU:"€ 49,90",note:"Pagamento único · acesso vitalício · sem assinatura mensal",cta:"QUERO COMEÇAR MINHA FORMAÇÃO",login:"JÁ TENHO ACESSO",headline:"Não é uma biblioteca de aulas para consumir correndo.",sub:"É uma jornada guiada: aprender, pesquisar, testar, aplicar, corrigir e registrar.",features:[["90 aulas em 90 dias","Uma nova aula é liberada por dia. O conteúdo futuro fica bloqueado, mas tudo que já foi liberado pode ser revisto e corrigido."],["Aproximadamente 20 minutos de aula por dia","Cada tema traz leitura aprofundada, aplicação prática, exemplo, quiz e atividade de campo antes das questões."],["10 perguntas por aula","7 perguntas objetivas e 3 respostas escritas para pesquisar, testar, aplicar e corrigir o que está sendo construído."],["Manual do Meu Negócio","As respostas alimentam um dashboard e formam, ao longo dos 90 dias, um manual personalizado para estruturar o próprio negócio."],["6 encontros ao vivo opcionais","São 2 por mês para dúvidas, empreendedorismo, experiências, networking e assuntos complementares. Presença não obrigatória."],["Projeto com avaliação humana","Há 3 avaliações incluídas: uma ao final de cada mês. A aprovação libera o mês seguinte e mantém acompanhamento próximo."],["PDF do Manual e certificado","Ao final, o aluno pode gerar o Manual do Negócio em PDF e o certificado com conteúdo programático, 300 horas e período realizado."],["Acesso vitalício","Depois dos 3 meses, aulas, respostas, materiais e Manual continuam disponíveis sem nova compra."]],monthsTitle:"O que acontece em cada mês",months:[["Mês 1 · Diagnosticar","Propósito, recursos, problema, cliente, mercado, concorrência, posicionamento, preço, custos, vendas, operação, riscos e sustentação emocional."],["Mês 2 · Construir e validar","Transformar hipóteses em testes: oferta, comunicação, preço, canais, prospecção, experiência do cliente, evidências e correções."],["Mês 3 · Executar e corrigir","Criar processos, indicadores, metas, plano de ação, decisões, internacionalização e consolidar o projeto final."],],storyTitle:"Baseado em história real, aplicável a qualquer negócio",story:"O treinamento usa os aprendizados presentes em “A Coragem de Começar” e “O Menino que Vendia Mamão” como ponto de partida para mostrar que começar com o que se tem, observar o mercado e aprender pela execução pode ser transformado em método. O conteúdo não depende de um setor específico: pode ser aplicado a produto, serviço, carreira independente ou negócio digital.",final:"GARANTIR O VALOR DE LANÇAMENTO"},
en:{badge:"SPECIAL LAUNCH OFFER · FIRST 100 STUDENTS",title:"From Papaya to Business",lead:"A practical 90-day training for turning an idea into a clearer, tested and documented business.",normal:"Regular price",launch:"Launch price",normalBR:"R$ 299.99",normalEU:"€49.90",launchBR:"R$ 299.99",launchEU:"€49.90",note:"One-time payment · lifetime access · no monthly subscription",cta:"START MY TRAINING",login:"I ALREADY HAVE ACCESS",headline:"Not a library of lessons to binge.",sub:"A guided journey: learn, research, test, apply, correct and document.",features:[["90 lessons in 90 days","One new lesson unlocks daily. Future content stays locked while released work can be reviewed and improved."],["About 20 minutes of guided lesson each day","Each topic includes in-depth reading, practical application, example, quiz and field activity before the questions."],["10 questions per lesson","7 objective questions and 3 written answers for research, testing, application and correction."],["My Business Manual","Answers feed a dashboard and become a personalized business manual throughout the 90 days."],["6 optional live meetings","Two per month for questions, entrepreneurship, experiences, networking and complementary topics."],["Human-reviewed project","Three reviews are included: one at the end of each month. Approval unlocks the next month for closer follow-up."],["Manual PDF and certificate","At the end, generate the Business Manual PDF and certificate with syllabus, 300 hours and training period."],["Lifetime access","After three months, lessons, answers, materials and Manual remain accessible without repurchase."]],monthsTitle:"What happens each month",months:[["Month 1 · Diagnose","Purpose, resources, problem, customer, market, competition, positioning, price, costs, sales, operations and risks."],["Month 2 · Build and validate","Turn hypotheses into tests: offer, communication, price, channels, prospecting, customer experience and evidence."],["Month 3 · Execute and correct","Create processes, metrics, goals, action plan, decisions, internationalization and consolidate the final project."]],storyTitle:"Built from a real story, applicable to any business",story:"The training uses lessons from The Courage to Begin and The Boy Who Sold Papaya as a lens for starting with available resources, observing the market and learning through execution. It can be applied to products, services, independent careers or digital businesses.",final:"GET THE LAUNCH PRICE"},
fr:{badge:"OFFRE SPÉCIALE DE LANCEMENT · 100 PREMIERS ÉLÈVES",title:"De la Papaye à l’Entreprise",lead:"Une formation pratique de 90 jours pour transformer une idée en activité plus claire, testée et documentée.",normal:"Prix normal",launch:"Prix de lancement",normalBR:"R$ 299,99",normalEU:"49,90 €",launchBR:"R$ 299,99",launchEU:"49,90 €",note:"Paiement unique · accès à vie · sans abonnement mensuel",cta:"COMMENCER MA FORMATION",login:"J’AI DÉJÀ ACCÈS",headline:"Ce n’est pas une bibliothèque de cours à consommer rapidement.",sub:"C’est un parcours guidé : apprendre, rechercher, tester, appliquer, corriger et documenter.",features:[["90 cours en 90 jours","Un nouveau cours est débloqué chaque jour. Le futur reste bloqué, mais le contenu déjà ouvert peut être revu."],["Environ 20 minutes de cours guidé par jour","Lecture approfondie, application pratique, exemple, quiz et activité terrain avant les questions."],["10 questions par cours","7 questions objectives et 3 réponses écrites pour rechercher, tester, appliquer et corriger."],["Mon Manuel d’Entreprise","Les réponses alimentent un tableau de bord et deviennent un manuel personnalisé."],["6 rencontres facultatives","Deux par mois pour questions, entrepreneuriat, expériences, networking et thèmes complémentaires."],["Projet évalué humainement","Trois évaluations sont incluses : une à la fin de chaque mois. L’approbation débloque le mois suivant."],["PDF du Manuel et certificat","À la fin, générez le Manuel en PDF et le certificat avec programme, 300 heures et période réalisée."],["Accès à vie","Après les 3 mois, cours, réponses, supports et Manuel restent disponibles."]],monthsTitle:"Chaque mois",months:[["Mois 1 · Diagnostiquer","But, ressources, problème, client, marché, concurrence, positionnement, prix, coûts, ventes, opérations et risques."],["Mois 2 · Construire et valider","Transformer les hypothèses en tests : offre, communication, prix, canaux, prospection et preuves."],["Mois 3 · Exécuter et corriger","Créer processus, indicateurs, objectifs, plan d’action, décisions, internationalisation et projet final."]],storyTitle:"Fondé sur une histoire réelle, applicable à toute activité",story:"La formation utilise les enseignements de Le Courage de Commencer et Le Garçon qui Vendait des Papayes comme repère pour commencer avec les ressources disponibles, observer le marché et apprendre par l’exécution.",final:"PROFITER DU PRIX DE LANCEMENT"},
es:{badge:"OFERTA ESPECIAL DE LANZAMIENTO · PRIMEROS 100 ALUMNOS",title:"De la Papaya al Negocio",lead:"Una formación práctica de 90 días para convertir una idea en un negocio más claro, probado y documentado.",normal:"Precio normal",launch:"Precio de lanzamiento",normalBR:"R$ 299,99",normalEU:"€ 49,90",launchBR:"R$ 299,99",launchEU:"€ 49,90",note:"Pago único · acceso vitalicio · sin suscripción mensual",cta:"EMPEZAR MI FORMACIÓN",login:"YA TENGO ACCESO",headline:"No es una biblioteca de clases para consumir rápido.",sub:"Es un recorrido guiado: aprender, investigar, probar, aplicar, corregir y documentar.",features:[["90 clases en 90 días","Se libera una clase por día. El futuro queda bloqueado y lo ya liberado puede revisarse."],["Aproximadamente 20 minutos de clase guiada al día","Lectura profunda, aplicación práctica, ejemplo, quiz y actividad de campo antes de las preguntas."],["10 preguntas por clase","7 preguntas objetivas y 3 escritas para investigar, probar, aplicar y corregir."],["Manual de Mi Negocio","Las respuestas alimentan un dashboard y forman un manual personalizado."],["6 encuentros opcionales","Dos por mes para dudas, emprendimiento, experiencias, networking y temas complementarios."],["Proyecto evaluado por una persona","Se incluyen 3 evaluaciones: una al final de cada mes. La aprobación libera el mes siguiente."],["PDF del Manual y certificado","Al final, genera el Manual en PDF y el certificado con programa, 300 horas y período realizado."],["Acceso vitalicio","Después de los 3 meses, clases, respuestas, materiales y Manual siguen disponibles."]],monthsTitle:"Qué ocurre cada mes",months:[["Mes 1 · Diagnosticar","Propósito, recursos, problema, cliente, mercado, competencia, posicionamiento, precio, costes, ventas, operación y riesgos."],["Mes 2 · Construir y validar","Convertir hipótesis en pruebas: oferta, comunicación, precio, canales, prospección, experiencia y evidencia."],["Mes 3 · Ejecutar y corregir","Crear procesos, indicadores, metas, plan de acción, decisiones, internacionalización y proyecto final."]],storyTitle:"Basado en una historia real, aplicable a cualquier negocio",story:"La formación usa los aprendizajes de El Coraje de Empezar y El Niño que Vendía Papayas como referencia para empezar con los recursos disponibles, observar el mercado y aprender mediante la ejecución.",final:"QUIERO EL PRECIO DE LANZAMIENTO"}
} as const;

export function TrainingLaunchPageV2(){
 const {locale}=useI18n();const c=COPY[locale];
 return <div className="min-h-screen bg-[#fffaf2] text-[#32111b]" data-launch-offer-version="2026-09-09-v4">
  <div className="sticky top-0 z-[60] border-b-2 border-[#d7ad54] bg-[#2f0715] px-3 py-3 text-center text-white shadow-xl">
    <div className="mx-auto flex max-w-6xl flex-col items-center justify-center gap-2 sm:flex-row sm:gap-5">
      <strong className="text-xs font-black uppercase tracking-[.16em] text-[#f0ca73]">🔥 {c.badge}</strong>
      <span className="text-sm font-bold"><span className="mr-2 opacity-65 line-through">{c.normalBR}</span><strong className="text-xl text-[#f0ca73]">{c.launchBR}</strong></span>
      <span className="text-sm font-bold"><span className="mr-2 opacity-65 line-through">{c.normalEU}</span><strong className="text-xl text-[#f0ca73]">{c.launchEU}</strong></span>
      <a href={`${PANEL}/cliente/biblioteca`} className="rounded-xl bg-[#d7ad54] px-4 py-2 text-xs font-black text-[#42111d]">{c.final}</a>
    </div>
  </div>
  <header className="border-b border-[#d7ad54]/50 bg-[#5b0824] text-white"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-4 sm:px-6"><Link to="/" className="font-serif text-xl font-bold">Grupo LDR Essence</Link><LanguageSelect/></div></header>
  <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6 sm:py-12">
   <section className="overflow-hidden rounded-[2rem] border border-[#d7ad54] bg-[#5b0824] text-white shadow-2xl shadow-[#5b0824]/20"><div className="grid gap-8 p-6 sm:p-10 lg:grid-cols-[1.2fr_.8fr] lg:items-center"><div><span className="inline-flex items-center gap-2 rounded-full bg-[#d7ad54] px-3 py-1.5 text-xs font-black uppercase tracking-[.14em] text-[#42111d]"><Sparkles className="h-4 w-4"/>{c.badge}</span><h1 className="mt-5 font-serif text-5xl font-bold leading-none sm:text-6xl">{c.title}</h1><p className="mt-4 max-w-2xl text-lg leading-8 text-[#f4e8df]">{c.lead}</p><div className="mt-6 flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-white/10 px-3 py-2">90 dias</span><span className="rounded-full bg-white/10 px-3 py-2">300 horas</span><span className="rounded-full bg-white/10 px-3 py-2">90 aulas</span><span className="rounded-full bg-white/10 px-3 py-2">900 perguntas</span><span className="rounded-full bg-white/10 px-3 py-2">Acesso vitalício</span></div></div><aside className="rounded-3xl border border-white/20 bg-white/10 p-6"><p className="text-xs font-black uppercase tracking-[.15em] text-[#efd18e]">Pagamento único</p><strong className="mt-2 block text-4xl">{c.launchBR}</strong><strong className="block text-2xl text-[#efd18e]">{c.launchEU}</strong><p className="mt-3 text-xs opacity-80">{c.note}</p><a href={`${PANEL}/cliente/biblioteca`} className="mt-6 inline-flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-[#d7ad54] px-5 py-3 text-center text-sm font-black text-[#42111d]">{c.cta}<ArrowRight className="h-4 w-4"/></a><a href={`${PANEL}/cliente/login`} className="mt-3 inline-flex min-h-11 w-full items-center justify-center rounded-2xl border border-white/25 px-5 py-3 text-center text-sm font-black">{c.login}</a></aside></div></section>
   <section className="py-10 text-center"><h2 className="font-serif text-3xl font-bold sm:text-4xl">{c.headline}</h2><p className="mx-auto mt-3 max-w-3xl text-lg text-[#6d5960]">{c.sub}</p></section>
   <section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{c.features.map(([title,text],i)=><article key={title} className="rounded-3xl border border-[#ead3a2] bg-white p-5 shadow-sm"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-[#5b0824] text-[#efd18e]">{i===0?<GraduationCap className="h-5 w-5"/>:i===1?<BookOpen className="h-5 w-5"/>:i===4?<Video className="h-5 w-5"/>:i===5?<FileCheck2 className="h-5 w-5"/>:<CheckCircle2 className="h-5 w-5"/>}</div><h3 className="mt-4 font-serif text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#6d5960]">{text}</p></article>)}</section>
   <section className="mt-10 rounded-[2rem] border border-[#ead3a2] bg-white p-6 sm:p-8"><h2 className="font-serif text-3xl font-bold">{c.monthsTitle}</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{c.months.map(([title,text],i)=><article key={title} className="rounded-3xl bg-[#fff3dd] p-5"><span className="text-xs font-black uppercase tracking-[.14em] text-[#9c7019]">0{i+1}</span><h3 className="mt-2 font-serif text-xl font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#6d5960]">{text}</p></article>)}</div></section>
   <section className="mt-8 rounded-[2rem] bg-[#5b0824] p-6 text-white sm:p-8"><h2 className="font-serif text-3xl font-bold text-[#fff7e9]">{c.storyTitle}</h2><p className="mt-4 max-w-4xl leading-8 text-[#f2e5de]">{c.story}</p></section>
   <section className="mt-8 rounded-[2rem] border border-[#d7ad54] bg-[#fff3dd] p-7 text-center"><p className="text-xs font-black uppercase tracking-[.15em] text-[#9c7019]">{c.badge}</p><div className="mt-3 flex items-end justify-center gap-3"><span className="text-sm line-through opacity-60">{c.normalBR}</span><strong className="text-4xl text-[#5b0824]">{c.launchBR}</strong></div><p className="mt-1 font-bold text-[#8d6416]">{c.launchEU}</p><a href={`${PANEL}/cliente/biblioteca`} className="mt-5 inline-flex min-h-12 items-center justify-center gap-2 rounded-2xl bg-[#5b0824] px-7 py-3 font-black text-white">{c.final}<ArrowRight className="h-4 w-4"/></a></section>
  </main>
 </div>;
}
