export type AILesson={id:string;number:number;title:string;objective:string;introduction:string;development:string;example:string;exercise:string;action:string;summary:string};
export type AIModule={number:number;title:string;brief:string;lessons:AILesson[]};
const DATA:[string,string,string[]][]=[
["Fundamentos da Inteligência Artificial","Compreender IA generativa, modelos de linguagem, limites, verificação, privacidade, autoria e uso responsável.",["O que é Inteligência Artificial","Da automação à IA generativa","Como uma IA generativa funciona","LLMs sem complicação","IA generativa x automação tradicional","Principais categorias de ferramentas","Texto, imagem, áudio, vídeo e código","O que a IA faz bem","Limitações da IA","Alucinações e erros","Como verificar respostas","Privacidade e proteção de dados","Direitos autorais e IA","Ética e uso responsável","Sua estratégia pessoal de IA"]],
["Prompt Engineering e Comunicação com IA","Aprender a transformar intenção em instruções claras, verificáveis, reutilizáveis e orientadas a resultados.",["Anatomia de um bom prompt","Contexto, tarefa e objetivo","Definição de papéis","Restrições e critérios","Exemplos dentro do prompt","Prompts de uma etapa","Prompts estruturados","Trabalhando com documentos","Extração de informações","Análise e classificação","Prompts para pesquisa","Prompts para negócios","Prompts reutilizáveis","Biblioteca de prompts","Avaliação e melhoria de resultados"]],
["Nova Forma de Criar Conteúdo","Construir um sistema editorial com IA sem perder estratégia, autoria, voz de marca e revisão humana.",["IA como parceira criativa","Pesquisa de público","Definição de persona","Posicionamento","Pilares de conteúdo","Ideação em escala","Roteiros para vídeos curtos","Carrosséis que ensinam e vendem","Posts e legendas","Artigos e newsletters","Storytelling","Conteúdo multilíngue","Reaproveitamento de conteúdo","Calendário editorial com IA","Sistema completo de produção"]],
["Marketing Digital + IA","Aplicar IA à jornada do cliente, oferta, copy, SEO, mídia, experimentação e análise de desempenho.",["Fundamentos do marketing digital","Jornada do cliente","Funil de vendas","Oferta e proposta de valor","Copywriting","Headlines e hooks","Landing pages","E-mail marketing","Redes sociais","SEO e IA","Pesquisa de palavras-chave","Anúncios e criativos","Testes A/B","Métricas e análise","Plano de marketing com IA"]],
["Vendas e Atendimento com IA","Criar um processo comercial humano, mensurável e assistido por IA do lead ao pós-venda.",["Processo comercial","Identificação de leads","Qualificação","Scripts de abordagem","WhatsApp comercial","E-mail de prospecção","Follow-up","Tratamento de objeções","Negociação","Fechamento","CRM","Atendimento automatizado","Personalização em escala","Pós-venda","Máquina comercial assistida por IA"]],
["Criação e Gestão de Cursos Digitais","Projetar, produzir, avaliar, comercializar e melhorar cursos online com foco em aprendizagem e transformação real.",["Escolhendo um tema","Definindo a transformação","Pesquisa de demanda","Perfil do aluno","Objetivos de aprendizagem","Construção da grade curricular","Módulos e aulas","Conteúdo textual","Aulas gravadas","Exercícios","Avaliações","Projetos","Plataforma e experiência do aluno","Marketing e venda do curso","Gestão e atualização contínua"]],
["Programação na Era da IA","Aprender pensamento computacional e desenvolvimento assistido por IA, mantendo revisão, testes, segurança e compreensão do código.",["Como mudou a programação","Pensamento computacional","Front-end, back-end e banco de dados","HTML","CSS","JavaScript","APIs","Bancos de dados","Git e controle de versão","GitHub","Programação assistida por IA","Debugging com IA","Vibe coding com responsabilidade","Segurança e validação do código","Construindo sua primeira aplicação"]],
["Sites, Sistemas e Produtos com IA","Transformar requisitos em produtos digitais utilizáveis, responsivos, integrados, testados e publicados.",["Landing pages","Sites institucionais","Formulários","Autenticação","Painéis","Bancos de dados aplicados","Integrações","APIs externas","Pagamentos","Sistemas de assinatura","Aplicações responsivas","UX/UI assistido por IA","Testes","Deploy","Produto em produção"]],
["Automação de Processos","Mapear processos, eliminar trabalho repetitivo e criar workflows confiáveis com tratamento de falhas e supervisão.",["Pensamento de automação","Mapeamento de processos","Gatilhos e ações","Workflows","Formulários e banco de dados","E-mail automatizado","CRM automatizado","Atendimento","Automação de marketing","Automação de vendas","Automação em RH","Relatórios","Integração entre ferramentas","Monitoramento e falhas","Automação completa"]],
["Agentes de IA e Funcionário Digital","Projetar agentes especializados com objetivos, contexto, ferramentas, limites, segurança e supervisão humana.",["O que é um agente","Chatbot x agente","Objetivo e função","Instruções do sistema","Base de conhecimento","Memória e contexto","Ferramentas","Agente de atendimento","Agente comercial","Agente de marketing","Agente administrativo","Agente de RH","Supervisão humana","Segurança e limites","Construindo seu Funcionário Digital"]],
["IA para RH e Gestão de Pessoas","Usar IA para apoiar RH sem automatizar decisões humanas sensíveis de forma irresponsável.",["Transformação do RH","Descrição de cargos","Divulgação de vagas","Triagem assistida","Entrevistas","Onboarding","Treinamentos","Comunicação interna","Pesquisa de clima","Desenvolvimento","Feedback","Indicadores","People Analytics","Ética da IA no RH","Plano de transformação do RH"]],
["Produtividade e Gestão Empresarial","Criar um sistema operacional de trabalho que una planejamento, informação, processos, indicadores e decisão assistida.",["Segundo cérebro digital","Gestão de tarefas","Planejamento","Documentos","Reuniões","Pesquisa","Análise de informações","Procedimentos operacionais","Gestão de projetos","Atendimento e operação","Organização financeira de dados","Dashboards","Indicadores","Decisão assistida por IA","Sistema operacional pessoal e empresarial"]],
["Empreendedorismo e Novos Negócios com IA","Validar problemas, construir ofertas, testar modelos e operar negócios AI-first com foco em valor real.",["Identificando problemas","Pesquisa de mercado","Validação","Análise da concorrência","Modelo de negócio","Produto mínimo viável","Precificação","Marca","Oferta","Aquisição de clientes","Recorrência","Escalabilidade","Operação enxuta","Internacionalização","Negócio AI-first"]],
["Carreira e Geração de Renda com IA","Transformar IA em vantagem profissional, portfólio, serviços, produtos e plano de desenvolvimento sustentável.",["O novo mercado profissional","Competências para a era da IA","Diagnóstico profissional","Currículo","LinkedIn","Portfólio","Marca pessoal","Networking","Pesquisa de oportunidades","Entrevistas","Freelancer com IA","Prestação de serviços","Consultoria","Produtos digitais","Plano profissional de 12 meses"]],
["Projeto Final — Do Problema à Solução","Integrar estratégia, tecnologia, IA, experiência, marketing, ética e validação em uma solução real e documentada.",["Escolha do problema","Pesquisa e evidências","Público-alvo","Proposta de solução","Modelo de negócio","Arquitetura da solução","Identidade e UX","Construção com IA","Conteúdo","Marketing","Automação","Testes","Segurança e revisão humana","Apresentação do projeto","Entrega final e próximos passos"]]
];
function lesson(mi:number,li:number,title:string,brief:string):AILesson{const id=`ai-m${String(mi).padStart(2,"0")}-a${String(li).padStart(2,"0")}`;return{id,number:li,title,objective:`Ao final desta aula, você será capaz de aplicar ${title.toLowerCase()} em uma situação real de trabalho, carreira ou negócio, explicando a decisão tomada e o resultado esperado.`,introduction:`${title} não deve ser tratado como um recurso isolado. Nesta etapa, conectamos o tema ao objetivo do módulo: ${brief} O foco é aprender o raciocínio por trás da ferramenta para que o conhecimento continue útil mesmo quando plataformas e modelos mudarem.`,development:`Trabalhe em quatro camadas: problema, contexto, execução e validação. Primeiro descreva o problema sem citar uma ferramenta. Depois identifique dados, pessoas, riscos e critérios de sucesso. Só então escolha onde a IA pode acelerar pesquisa, criação, análise ou automação. Compare a saída com evidências e critérios definidos antes da execução. Registre versões, decisões e correções: usar IA profissionalmente exige rastreabilidade, revisão humana e capacidade de explicar por que uma solução foi aceita ou rejeitada.`,example:`Imagine uma pequena empresa que precisa melhorar um processo ligado a “${title}”. Em vez de pedir à IA uma solução pronta, a equipe informa objetivo, público, restrições, exemplos e métrica de sucesso. Gera duas alternativas, verifica fatos, testa a opção de menor risco e documenta o aprendizado antes de ampliar o uso.`,exercise:`Escolha um caso real seu. Escreva: (1) problema em uma frase; (2) resultado desejado; (3) informações disponíveis; (4) riscos; (5) como a IA ajudará; (6) como você verificará a qualidade. Produza uma primeira versão, critique-a e faça uma segunda versão melhorada.`,action:`Salve o resultado no seu portfólio da formação. Registre o que foi feito por você, o que foi apoiado por IA, quais verificações realizou e qual seria o próximo teste em ambiente real.`,summary:`A competência central desta aula não é apertar um botão: é formular um problema, usar IA com intenção, validar a saída e transformar o resultado em ação responsável.`};}
export const AI_BUSINESS_CAREER_MODULES:AIModule[]=DATA.map(([title,brief,titles],i)=>({number:i+1,title,brief,lessons:titles.map((t,j)=>lesson(i+1,j+1,t,brief))}));
export const AI_PROJECTS=[
{number:1,afterModule:4,title:"Conteúdo & Marketing com IA",deliverable:"Campanha editorial de 30 dias com público, posicionamento, funil, peças, calendário, métricas e registro do uso de IA."},
{number:2,afterModule:6,title:"Produto Digital",deliverable:"Protótipo completo de curso ou produto digital com transformação, grade, avaliação, oferta, página e plano de lançamento."},
{number:3,afterModule:8,title:"Programação & Produto",deliverable:"Site, aplicação ou MVP funcional com requisitos, UX, código revisado, testes e publicação ou demonstração documentada."},
{number:4,afterModule:10,title:"Automação & Agentes",deliverable:"Workflow ou Funcionário Digital com objetivo, entradas, ações, ferramentas, limites, supervisão e plano de tratamento de falhas."},
{number:5,afterModule:14,title:"IA aplicada à profissão ou negócio",deliverable:"Solução aplicada a RH, gestão, empreendedorismo ou carreira, com diagnóstico, implementação, indicadores e plano de evolução."},
{number:6,afterModule:15,title:"Projeto Final — Solução completa com IA",deliverable:"Solução real integrando problema, público, IA, construção, experiência, marketing, automação, testes, ética, documentação e apresentação final."}
] as const;
export const AI_TOTAL_LESSONS=225;
