export type MassotherapyLesson={id:string;title:string;summary:string;content:string[]};
export type MassotherapyModule={id:number;title:string;focus:string;lessons:MassotherapyLesson[];activity:string};
type Spec={id:number;title:string;focus:string;blocks:string[]};
const specs:Spec[]=[
{id:1,title:"Fundamentos, Ética e Biossegurança",focus:"História, ética, biossegurança, ambiente, ergonomia e acolhimento.",blocks:["História da massagem, evolução das técnicas, perfil profissional, ética, limites de atuação e legislação aplicável","Higiene pessoal, mãos, EPIs quando indicados, desinfecção de macas, ambiente e descarte","Preparação da sala, iluminação, música, cromoterapia como bem-estar, aromaterapia introdutória e óleos","Ergonomia, postura, biomecânica, prevenção de lesões ocupacionais e alongamento","Acolhimento, comunicação, consentimento, privacidade e primeiro contato"]},
{id:2,title:"Anatomia Humana Essencial",focus:"Planos, eixos, ossos, articulações e referências anatômicas.",blocks:["Planos e eixos, posição, direção, divisões do corpo, células e tecidos","Crânio, face e coluna cervical, torácica, lombar e sacro","Tórax, costelas, esterno, cintura escapular, braços e mãos","Pelve, membros inferiores, pernas e pés","Articulações, cartilagens, ligamentos, líquido sinovial e mobilidade"]},
{id:3,title:"Fisiologia e Biomecânica Muscular",focus:"Pele, circulação, linfa, sistema nervoso, músculos e fáscia.",blocks:["Pele, epiderme, derme, circulação, coração, artérias, veias e retorno venoso","Sistema linfático, linfa, linfonodos, sistema nervoso e receptores sensoriais","Fisiologia da contração muscular e resposta ao toque","Músculos da face, pescoço, trapézio, dorsais e peitorais","Deltoide, bíceps, tríceps, glúteos, quadríceps, isquiotibiais, panturrilha e fáscia"]},
{id:4,title:"Massagem Relaxante Clássica / Sueca",focus:"Effleurage, pétrissage, fricção, percussão, vibração e sequência integrada.",blocks:["Benefícios de bem-estar, indicações, contraindicações e deslizamentos","Amassamento, pétrissage, fricção e aquecimento tecidual","Tapotement, vibração, ritmo, intensidade e pressão","Sequência de costas e membros inferiores em decúbito ventral","Membros superiores, decúbito dorsal e sessão integrada de 60 minutos"]},
{id:5,title:"Drenagem Linfática Manual",focus:"Fundamentos, manobras suaves, fluxo e segurança.",blocks:["Diferenças entre drenagem e massagem, Vodder/Leduc, indicações e contraindicações","Pressão, bombeamento, captação e evacuação","Membros inferiores","Abdômen, flancos e membros superiores","Pescoço, face e protocolo corporal com consentimento e limites profissionais"]},
{id:6,title:"Massagem Estética e Modeladora",focus:"Fundamentos estéticos, manobras, acessórios e cosmetologia.",blocks:["Tecido adiposo, fibroedema geloide, flacidez e limites da massagem estética","Ritmo, hiperemia, amassamento, pinçamento e deslizamento","Rolos, pantalas e acessórios","Ventosas estéticas e bambuterapia","Cosmetologia, cafeína, centella asiática, frio/calor e protocolo seguro"]},
{id:7,title:"Medicina Tradicional Chinesa e Shiatsu",focus:"Conceitos tradicionais da MTC e prática de Shiatsu sem equipará-los à biomedicina.",blocks:["Qi, Yin/Yang e Cinco Elementos como conceitos tradicionais","Doze meridianos e leitura energética tradicional","Pressão com polegares, palmas e cotovelos","Postura, respiração e ergonomia","Sequências tradicionais em decúbito ventral e dorsal"]},
{id:8,title:"Reflexologia",focus:"Mapas tradicionais e técnicas voltadas ao relaxamento e bem-estar.",blocks:["História, zonas reflexas e mapas tradicionais dos pés","Caminhada com polegar e prática podal","Mapas palmares e autoaplicação","Noções de auriculoterapia com sementes, sem diagnóstico","Reflexologia facial e protocolos de relaxamento"]},
{id:9,title:"Terapias de Spa e Bem-Estar",focus:"Pedras quentes, bambuterapia, pindas e candle massage com segurança.",blocks:["Pedras quentes, basalto, aquecedores, higienização e segurança","Deslizamentos com pedras e controle de temperatura","Bambuterapia, escolha, assepsia e aplicação","Pindas, preparo, aquecimento e cuidados","Candle massage com cosméticos apropriados e ritual de Spa"]},
{id:10,title:"Massagem Desportiva",focus:"Exercício, preparação, recuperação, mobilidade e limites profissionais.",blocks:["Fibras musculares, fadiga, recuperação e fisiologia do exercício","Pré-atividade, estímulo, aquecimento e segurança","Inter-atividade e adequação individual","Pós-atividade, conforto e recuperação sem alegações de remoção de toxinas","Alongamentos, noções de FNP, mobilidade e sinais de lesão"]},
{id:11,title:"Liberação Miofascial e Pontos-Gatilho",focus:"Fáscia, técnicas manuais, pontos sensíveis e ferramentas básicas.",blocks:["Anatomia da fáscia, tecido conjuntivo e restrições","Liberação superficial, profunda, mãos cruzadas e rolamento","Pontos sensíveis, dor referida e avaliação sem diagnóstico","Pressão sustentada, dosagem, conforto e reavaliação","Ventosas, Gua Sha e noções de IASTM com contraindicações"]},
{id:12,title:"Populações Especiais e Condições de Saúde",focus:"Gestantes, idosos, bebês e red flags.",blocks:["Gestação, posicionamento, conforto, contraindicações e liberação médica quando necessária","Idosos, pele, fragilidade, osteoporose, artrose e pressão adaptada","Shantala, vínculo, conforto, higiene, segurança e responsáveis","Hérnia de disco, ciatalgia e fibromialgia: limites e encaminhamento","Câncer, pós-operatório, trombose, febre, infecção e quando não massagear"]},
{id:13,title:"Avaliação e Anamnese",focus:"Entrevista, observação postural, avaliação palpatória e plano de atendimento.",blocks:["Anamnese, entrevista, histórico, medicamentos e contraindicações","Observação postural de assimetrias sem diagnóstico médico","Avaliação palpatória de tensão, textura, sensibilidade, temperatura e edema aparente","Escolha de técnicas e objetivos de bem-estar","Plano de atendimento, evolução, frequência e encaminhamento"]},
{id:14,title:"Prática Clínica Orientada",focus:"Casos fictícios e fluxo completo sem simular supervisão presencial.",blocks:["Caso fictício de desconforto lombar e limites de atuação","Caso fictício de tensão cervical e estresse","Caso fictício de fadiga e cliente fisicamente ativo","Recepção, acolhimento, anamnese, contraindicações e escolha de técnica","Execução, finalização, registro, autocuidado e retorno"]},
{id:15,title:"Empreendedorismo, Marketing e Gestão",focus:"Formalização, finanças, marketing, vendas e experiência do cliente.",blocks:["Formalização, obrigações locais, requisitos sanitários e regras vigentes","Custos, materiais, lavanderia, energia, precificação e caixa","Instagram, TikTok, Google, conteúdo, fotos e publicidade ética","Pacotes, recorrência, fidelização e parcerias","Pós-venda, satisfação, relacionamento, organização e avaliação final"]},
];
const variants=["Fundamentos e conceitos essenciais","Aplicação profissional e anatomia relacionada","Prática segura passo a passo","Revisão, estudo de caso e tomada de decisão"];
function makeLesson(moduleId:number,index:number,block:string,variant:string):MassotherapyLesson{const n=index+1;return{id:`m${moduleId}-l${n}`,title:`${block} — ${variant}`,summary:`Aula ${n}: estudo aplicado de ${block.toLowerCase()}.`,content:[`INTRODUÇÃO — Esta aula apresenta ${block.toLowerCase()} no escopo da massoterapia, priorizando segurança, consentimento, conforto e limites de atuação.`,`OBJETIVOS — Reconhecer conceitos centrais, explicar aplicação prática, identificar riscos e saber quando interromper ou encaminhar.`,`CONTEÚDO PRINCIPAL — ${block}. Relacione o tema com anatomia, fisiologia, biossegurança e comunicação, sem confundir massoterapia com diagnóstico médico ou fisioterapêutico.`,`APLICAÇÃO PRÁTICA — Organize o ambiente, explique o procedimento, obtenha consentimento e ajuste pressão, ritmo, temperatura e posicionamento ao conforto do cliente.`,`PONTOS DE ATENÇÃO — Dor intensa, alteração súbita de sensibilidade, edema importante, febre, infecção, lesão aguda, mal-estar ou sinais incompatíveis com atendimento seguro exigem interrupção e avaliação adequada.`,`CONTRAINDICAÇÕES E LIMITES — Na dúvida, não execute. Situações pós-operatórias, oncológicas, vasculares, gestacionais ou com suspeita de lesão podem exigir avaliação/liberação de profissional de saúde.`,`BOAS PRÁTICAS — Higienize mãos e materiais, preserve privacidade, registre informações, evite promessas de cura e respeite a legislação local.`,`RESUMO E REVISÃO — Registre três aprendizados, uma contraindicação e uma adaptação. Pergunta: qual sinal faria você interromper a técnica e encaminhar o cliente?`]};}
export const massotherapyModules:MassotherapyModule[]=specs.map(spec=>({...spec,lessons:spec.blocks.flatMap((b,bi)=>variants.map((v,vi)=>makeLesson(spec.id,bi*4+vi,b,v))),activity:`Atividade do módulo ${spec.id}: elabore um protocolo seguro para um caso fictício, descrevendo anamnese, técnica, adaptações, contraindicações, consentimento e encaminhamento.`}));
export const MASSOTHERAPY_TOTAL_LESSONS=massotherapyModules.reduce((s,m)=>s+m.lessons.length,0);
export const MASSOTHERAPY_TOTAL_MODULES=massotherapyModules.length;
