export type MentorshipLesson={id:string;title:string;summary:string;content:string[]};
export type MentorshipModule={id:number;title:string;lessons:MentorshipLesson[];activity:string};

const lesson=(id:string,title:string,summary:string,...content:string[]):MentorshipLesson=>({id,title,summary,content});

export const mentorshipCareerModules:MentorshipModule[]=[
 {id:1,title:"Fundamentos da Mentoria Profissional",activity:"Defina seu papel como mentor, seus limites e o perfil de pessoa que você pretende acompanhar.",lessons:[
  lesson("m1-1","O que é mentoria","Compreenda a finalidade da mentoria e o que caracteriza um processo profissional.","Mentoria é um processo estruturado de desenvolvimento em que experiência, reflexão e direcionamento ajudam o mentorado a avançar em objetivos concretos.","O mentor não substitui profissionais de saúde, não promete resultados e trabalha com objetivos compatíveis com sua competência."),
  lesson("m1-2","Papel e responsabilidades do mentor","Entenda responsabilidades, limites e postura profissional.","O mentor organiza o processo, ajuda o mentorado a ampliar possibilidades, acompanha decisões e favorece responsabilização.","Clareza de escopo, confidencialidade, registro e encaminhamento quando necessário protegem as duas partes."),
  lesson("m1-3","Mentoria, consultoria, terapia e coaching","Diferencie práticas que podem parecer semelhantes.","Consultoria costuma entregar diagnóstico e recomendação especializada. Coaching usa metodologias próprias orientadas a desempenho. Terapias e psicoterapias possuem outros objetivos e referenciais.","Na mentoria profissional, a experiência do mentor e a construção conjunta de estratégia ocupam lugar central."),
  lesson("m1-4","Ética e limites profissionais","Construa uma prática segura e responsável.","Defina contrato, objetivos, confidencialidade, canais de contato, limites de disponibilidade e critérios de encerramento.","Nunca use a mentoria para diagnosticar ou tratar condições de saúde quando isso estiver fora da sua habilitação.") ]},
 {id:2,title:"Diagnóstico e Definição de Objetivos",activity:"Crie um roteiro de primeiro encontro com diagnóstico inicial, objetivo principal e indicadores de avanço.",lessons:[
  lesson("m2-1","Primeiro contato com o mentorado","Estruture uma entrada profissional e acolhedora.","O primeiro contato deve esclarecer objetivo, funcionamento, duração, investimento e limites do processo.","Evite prometer transformação antes de compreender a necessidade real."),
  lesson("m2-2","Anamnese profissional","Mapeie trajetória, momento atual e expectativas.","Uma anamnese profissional pode incluir histórico de carreira, experiências relevantes, competências percebidas, dificuldades, contexto atual, recursos e metas.","Use perguntas abertas e organize as informações sem transformar a conversa em interrogatório."),
  lesson("m2-3","Identificação de necessidades","Separe desejo imediato de necessidade estratégica.","O que a pessoa pede nem sempre é o que precisa priorizar. Investigue contexto, consequências e obstáculos antes de definir o foco.","Transforme queixas genéricas em problemas observáveis e trabalháveis."),
  lesson("m2-4","Definição de objetivos","Converta intenção em direção concreta.","Objetivos úteis são específicos o suficiente para orientar ação e flexíveis o suficiente para serem revisados.","Defina também sinais de progresso para que mentor e mentorado saibam se o processo está avançando."),
  lesson("m2-5","Plano de desenvolvimento","Organize prioridades e próximos passos.","O plano de desenvolvimento conecta objetivo, ações, responsáveis, prazos e critérios de acompanhamento.","Trabalhe com poucas prioridades por vez para aumentar execução.") ]},
 {id:3,title:"Carreira e Desenvolvimento Profissional",activity:"Monte um mapa de carreira com situação atual, direção desejada, competências e três próximos passos.",lessons:[
  lesson("m3-1","Planejamento de carreira","Transforme carreira em projeto gerenciável.","Planejamento de carreira combina autoconhecimento profissional, leitura de mercado e decisões compatíveis com a realidade.","O mentor ajuda a pessoa a comparar caminhos sem decidir por ela."),
  lesson("m3-2","Transição profissional","Conduza mudanças com menor improviso.","Transições podem envolver função, setor, país, modelo de trabalho ou empreendedorismo.","Mapeie riscos, recursos financeiros, lacunas de competência, rede de contatos e uma estratégia de transição gradual quando possível."),
  lesson("m3-3","Competências e potencial","Reconheça recursos já disponíveis e lacunas reais.","Competência envolve conhecimentos, habilidades e comportamentos observáveis.","Evite avaliações vagas; peça exemplos concretos de situações em que a pessoa demonstrou determinada capacidade."),
  lesson("m3-4","Tomada de decisão","Estruture escolhas profissionais complexas.","Compare opções por critérios relevantes: aprendizado, remuneração, mobilidade, estabilidade, alinhamento com objetivos e custo de oportunidade.","Decidir melhor não significa eliminar toda incerteza, mas torná-la consciente."),
  lesson("m3-5","Metas profissionais","Conecte ambição a execução.","Quebre metas maiores em marcos mensais, semanais e ações de curto prazo.","Revise metas quando surgirem dados novos em vez de insistir em um plano que perdeu sentido.") ]},
 {id:4,title:"Comunicação e Condução da Mentoria",activity:"Prepare cinco perguntas estratégicas e um modelo de feedback para utilizar em um encontro real ou simulado.",lessons:[
  lesson("m4-1","Escuta profissional","Escute para compreender, não apenas para responder.","A escuta profissional considera conteúdo, contexto, contradições, prioridades e aquilo que a pessoa evita decidir.","Resuma o que ouviu e confirme sua compreensão antes de orientar."),
  lesson("m4-2","Perguntas estratégicas","Use perguntas que produzam reflexão e decisão.","Perguntas úteis ampliam consciência, testam pressupostos e aproximam o mentorado de uma ação concreta.","Evite perguntas manipulativas que já carregam a resposta desejada pelo mentor."),
  lesson("m4-3","Comunicação assertiva","Seja claro sem ser agressivo.","Comunicação assertiva combina respeito, objetividade, limites e responsabilidade pelo que está sendo dito.","Diferencie fato, interpretação e recomendação ao conversar sobre decisões profissionais."),
  lesson("m4-4","Feedback","Ofereça retorno que possa ser utilizado.","Um feedback de qualidade descreve comportamento ou resultado, explica impacto e sugere possibilidades de melhoria.","Evite rótulos pessoais e generalizações."),
  lesson("m4-5","Condução dos encontros","Dê estrutura sem engessar o processo.","Um encontro pode incluir abertura, revisão de ações, tema principal, decisões, plano de ação e fechamento.","Reserve os minutos finais para sintetizar compromissos e próximos passos."),
  lesson("m4-6","Situações difíceis","Mantenha o processo profissional diante de resistência ou impasse.","Quando houver resistência, volte ao objetivo contratado e explore o que está impedindo a ação.","Se a demanda ultrapassar o escopo da mentoria, sinalize o limite e encaminhe quando necessário.") ]},
 {id:5,title:"Método e Acompanhamento",activity:"Desenhe sua sessão-padrão de mentoria e um modelo simples de registro de progresso.",lessons:[
  lesson("m5-1","Estrutura de uma sessão","Crie consistência na experiência do mentorado.","Ter uma estrutura-base ajuda a manter foco e continuidade entre encontros.","A estrutura pode ser adaptada, mas deve preservar objetivo, decisão e acompanhamento."),
  lesson("m5-2","Plano de ação","Converta conversa em movimento.","Toda ação deve ser clara, realista e atribuída ao responsável correto.","Evite listas enormes; priorize o que realmente muda o processo."),
  lesson("m5-3","Acompanhamento da evolução","Use evidências de avanço.","Acompanhe entregas, decisões, mudanças de comportamento profissional e indicadores definidos no início.","Progresso não precisa ser linear, mas deve ser observável."),
  lesson("m5-4","Registro dos encontros","Documente apenas o necessário.","Registros profissionais podem conter data, objetivo, decisões, ações combinadas e pontos para acompanhamento.","Proteja os dados e evite registrar informações irrelevantes ou excessivamente sensíveis."),
  lesson("m5-5","Indicadores e avaliação","Revise o processo com método.","Use indicadores adequados ao objetivo, como candidaturas realizadas, entrevistas, propostas, decisões tomadas ou entregas concluídas.","Periodicamente, avalie se o processo deve continuar, mudar de foco ou ser encerrado.") ]},
 {id:6,title:"Posicionamento Profissional do Mentor",activity:"Escreva em uma frase quem você ajuda, em qual problema e qual transformação profissional você facilita.",lessons:[
  lesson("m6-1","Definição de público","Escolha com quem sua experiência gera mais valor.","Um público bem definido facilita comunicação, metodologia, conteúdo e indicação.","Comece por problemas que você conhece de forma concreta."),
  lesson("m6-2","Nicho e posicionamento","Diferencie especialização de limitação.","Posicionamento é a associação que você quer construir na mente do mercado.","Ele pode evoluir conforme sua prática produz dados e resultados."),
  lesson("m6-3","Construção da oferta","Transforme conhecimento em serviço compreensível.","Explique para quem é, qual problema aborda, como funciona, duração, entregáveis e limites.","Uma boa oferta reduz dúvidas sem criar promessas irreais."),
  lesson("m6-4","Autoridade e presença digital","Construa confiança com consistência.","Autoridade é consequência de clareza, experiência demonstrável, conteúdo útil, prova social legítima e coerência profissional.","Evite depender apenas de estética ou frases de efeito."),
  lesson("m6-5","Comunicação do serviço","Fale do benefício sem distorcer o processo.","Mostre situações que a mentoria ajuda a organizar e decisões que ela facilita.","Use linguagem concreta e inclua chamadas para ação simples.") ]},
 {id:7,title:"Mentoria de Carreira na Prática",activity:"Escolha um dos casos do módulo e produza diagnóstico, objetivo, plano de ação e forma de acompanhamento.",lessons:[
  lesson("m7-1","Estudo de caso: estagnação","Trabalhe um caso de profissional sem perspectiva de crescimento.","Mapeie o que depende da empresa, o que depende do profissional e quais alternativas externas existem.","Construa ações que gerem informação antes de uma decisão definitiva."),
  lesson("m7-2","Estudo de caso: transição","Organize mudança de área com critérios.","Identifique competências transferíveis, lacunas, experiências de teste e rede necessária.","Planeje uma transição que produza evidências antes de abandonar a trajetória atual quando possível."),
  lesson("m7-3","Simulação de atendimento","Pratique abertura, diagnóstico e fechamento.","Simule um encontro de 30 a 50 minutos com foco em uma decisão profissional realista.","Ao final, avalie clareza, escuta, qualidade das perguntas e objetividade do plano de ação."),
  lesson("m7-4","Construção de estratégias","Escolha estratégias compatíveis com o contexto.","Duas pessoas com o mesmo objetivo podem precisar de caminhos diferentes por recursos, rede, experiência e restrições.","Evite soluções-padrão sem diagnóstico."),
  lesson("m7-5","Análise da evolução","Aprenda a revisar o processo.","Compare o estado atual com o objetivo inicial e registre mudanças concretas.","Use a revisão para decidir continuidade, encerramento ou novo ciclo de mentoria.") ]},
 {id:8,title:"Estruturando seu Serviço de Mentoria",activity:"Monte sua primeira oferta completa de mentoria com público, duração, frequência, entregáveis, preço e jornada do cliente.",lessons:[
  lesson("m8-1","Modelo de atendimento","Escolha formato coerente com sua proposta.","Defina atendimento individual ou grupo, duração dos encontros, frequência, canais e materiais.","Mantenha o modelo simples no início e melhore com base na experiência."),
  lesson("m8-2","Jornada do cliente","Organize a experiência do primeiro contato ao encerramento.","Mapeie descoberta, conversa inicial, contratação, onboarding, encontros, acompanhamento e fechamento.","Uma jornada clara reduz atrito e aumenta confiança."),
  lesson("m8-3","Pacotes e programas","Estruture duração e entregas.","Venda um processo compreensível, não apenas horas soltas, quando isso fizer sentido para sua prática.","Deixe claro o que está e o que não está incluído."),
  lesson("m8-4","Agenda e operação","Crie uma rotina sustentável.","Defina horários, política de reagendamento, intervalos, registros, pagamentos e acompanhamento.","Operação organizada protege a qualidade do serviço."),
  lesson("m8-5","Experiência do mentorado","Cuide dos pontos que geram percepção de valor.","Pontualidade, clareza, continuidade, materiais úteis e acompanhamento consistente importam tanto quanto a conversa em si.","Colete feedback para ajustar o serviço."),
  lesson("m8-6","Apresentação profissional","Prepare materiais essenciais para vender e entregar.","Crie uma apresentação curta, página ou mensagem de oferta, formulário inicial, contrato e roteiro de onboarding.","Mantenha linguagem simples e profissional.") ]},
 {id:9,title:"Prática e Conclusão",activity:"Entregue um caso final completo: diagnóstico, objetivos, plano de mentoria, duas sessões simuladas, acompanhamento e critérios de conclusão.",lessons:[
  lesson("m9-1","Construção do processo completo","Integre tudo que foi estudado.","Escolha um caso real autorizado ou simulado e estruture o processo do primeiro contato ao encerramento.","Demonstre coerência entre diagnóstico, objetivo, metodologia e ações."),
  lesson("m9-2","Aplicação prática","Transforme conhecimento em condução.","Execute ou simule encontros e registre decisões, dificuldades e ajustes.","Observe especialmente sua escuta, clareza de limites e capacidade de manter foco."),
  lesson("m9-3","Avaliação final","Revise sua preparação para atuar.","Avalie seus pontos fortes, lacunas e temas que exigem estudo adicional.","Defina como seguirá desenvolvendo sua prática após a formação."),
  lesson("m9-4","Conclusão","Organize os próximos passos profissionais.","Finalize sua oferta, materiais, rotina e plano de divulgação.","A conclusão da formação representa o início de uma prática que deve continuar sendo revisada e aprimorada.") ]}
];

export const MENTORSHIP_TOTAL_LESSONS=mentorshipCareerModules.reduce((sum,m)=>sum+m.lessons.length,0);
