import type { PsychoanalysisModule } from "@/content/psychoanalysis-curriculum";

type Spec={title:string;summary:string;body:string[];activity:string};

function lesson(index:number,s:Spec){
  return {
    id:`m15-l${index}`,
    title:s.title,
    summary:s.summary,
    content:[
      `Objetivos de aprendizagem — ${s.summary}`,
      ...s.body,
      "Nota ética e regulatória — A atuação profissional varia conforme o país. A Psicanálise não deve ser apresentada como substituta de avaliação médica, psicológica, psiquiátrica, neuropsicológica ou multiprofissional quando estas forem indicadas. Em temas legais, regulatórios, migratórios e de proteção de dados, consulte sempre fontes oficiais e atualizadas do país de atuação.",
      `Atividade prática — ${s.activity}`,
      "Síntese — Construa uma prática internacional responsável combinando escuta clínica, adaptação cultural, limites profissionais, proteção de dados, pesquisa das regras locais e trabalho interdisciplinar quando necessário."
    ]
  };
}

const lessons=[
  lesson(1,{title:"Psicanálise no cenário internacional",summary:"Compreender como a Psicanálise é percebida em diferentes contextos culturais e profissionais.",body:["A Psicanálise tem histórias institucionais distintas entre países. Em alguns contextos está fortemente ligada à universidade, medicina, psicologia ou associações psicanalíticas; em outros circula como prática clínica independente ou complementar.","Atuar internacionalmente exige separar três perguntas: como a Psicanálise é culturalmente percebida, quais atividades são juridicamente reservadas a profissões regulamentadas e qual é o escopo real da sua própria formação."],activity:"Escolha dois países e compare como a Psicanálise aparece em instituições, associações e oferta clínica."}),
  lesson(2,{title:"Psicanálise na Europa: diferenças entre países",summary:"Entender por que não existe uma única regra europeia para exercício profissional.",body:["A União Europeia harmoniza algumas áreas, mas saúde, títulos profissionais e atividades reservadas continuam dependendo fortemente da legislação nacional.","Antes de divulgar serviços, identifique se o país protege títulos como psicólogo, psicoterapeuta ou profissional de saúde, e evite usar denominações reservadas quando não possuir a habilitação exigida."],activity:"Monte uma tabela com país, título profissional, órgão oficial consultado e principais limites encontrados."}),
  lesson(3,{title:"Como pesquisar regras de atuação em outro país",summary:"Aprender um método seguro para verificar exigências locais antes de atender.",body:["Comece por portais governamentais, ministérios da saúde, educação, trabalho, registros profissionais e legislação oficial. Associações privadas podem complementar a pesquisa, mas não substituem a fonte pública.","Registre a data da consulta e diferencie obrigação legal, recomendação profissional e prática de mercado."],activity:"Crie um checklist de pesquisa regulatória para um país de interesse."}),
  lesson(4,{title:"Ética na atuação internacional",summary:"Definir limites de competência, comunicação e responsabilidade profissional.",body:["O cliente precisa entender quem é o profissional, qual sua formação, qual serviço está sendo oferecido e quais são os limites desse serviço.","Evite promessas de cura, garantias de resultado, diagnósticos fora da competência e linguagem que possa confundir Psicanálise com profissão regulamentada quando isso não corresponder à realidade local."],activity:"Escreva uma apresentação profissional internacional clara e sem promessas indevidas."}),
  lesson(5,{title:"GDPR e proteção de dados na prática clínica",summary:"Conhecer princípios essenciais de privacidade aplicáveis ao contexto europeu.",body:["Dados sobre saúde e vida psíquica podem receber proteção reforçada. O profissional precisa pensar em base legal, minimização de dados, segurança, retenção, acesso e descarte.","WhatsApp, formulários, e-mail, agendas e prontuários devem ser avaliados não apenas pela conveniência, mas também pela proteção das informações."],activity:"Mapeie onde os dados de um cliente entram, ficam armazenados e são eliminados na sua rotina."}),
  lesson(6,{title:"Atendimento psicanalítico online internacional",summary:"Organizar enquadre, contrato, fuso horário, pagamentos e emergências à distância.",body:["O atendimento internacional precisa prever localização do cliente, contatos de emergência quando apropriado, forma de pagamento, política de faltas e limites do suporte fora da sessão.","O profissional também deve considerar se a legislação relevante é a do país onde ele está, a do cliente ou ambas, buscando orientação qualificada quando necessário."],activity:"Crie um checklist pré-atendimento internacional com dez itens."}),
  lesson(7,{title:"Construindo uma carreira internacional em Psicanálise",summary:"Transformar experiência clínica em posicionamento profissional compreensível em outros mercados.",body:["Uma carreira internacional começa pela clareza: quem você atende, em quais idiomas, qual problema ajuda a elaborar, qual abordagem utiliza e o que diferencia sua experiência.","Presença digital, consistência de conteúdo, rede de indicação e apresentação profissional precisam estar alinhadas ao público e ao país-alvo."],activity:"Escreva seu posicionamento internacional em até cinco linhas."}),
  lesson(8,{title:"Como conquistar os primeiros clientes internacionais",summary:"Planejar captação ética por conteúdo, comunidades, networking e indicação.",body:["Comunidades de migrantes, redes profissionais, produção de conteúdo e parcerias podem aproximar o profissional do público sem depender de publicidade agressiva.","A confiança tende a crescer quando existe clareza de serviço, prova de experiência sem exposição indevida de pacientes e comunicação adaptada ao idioma e contexto cultural."],activity:"Monte um plano de 30 dias com três canais de captação ética."}),
  lesson(9,{title:"Precificação internacional",summary:"Estruturar valores em diferentes moedas sem perder coerência profissional.",body:["Preço não deve ser simples conversão cambial. Considere custo de vida, tributação, meios de pagamento, posicionamento, público e sustentabilidade da agenda.","Defina previamente moeda, prazo de pagamento, política de cancelamento e eventual reajuste."],activity:"Crie três cenários de preço para Brasil, zona do euro e outro mercado de interesse."}),
  lesson(10,{title:"Migração, identidade e sofrimento psíquico",summary:"Compreender luto migratório, pertencimento, solidão e reconstrução identitária.",body:["Migrar pode envolver ganho e perda simultaneamente: novas possibilidades, ruptura de redes, mudança de idioma, deslocamento de status e transformação da relação com família e origem.","A escuta precisa evitar reduzir todo sofrimento ao fato de migrar, mas também não deve ignorar o peso social e simbólico dessa experiência."],activity:"Construa uma vinheta fictícia de migração destacando perdas, recursos e conflitos de pertencimento."}),
  lesson(11,{title:"Introdução à neurodiversidade",summary:"Conhecer a perspectiva da neurodiversidade e suas implicações para a escuta clínica.",body:["Neurodiversidade descreve variações do funcionamento neurológico humano e também sustenta debates sociais sobre deficiência, diferença, direitos e inclusão.","Na clínica, isso convida a distinguir sofrimento que a pessoa deseja trabalhar de características que não precisam ser normalizadas."],activity:"Liste cinco mudanças de linguagem que tornam sua comunicação clínica menos patologizante."}),
  lesson(12,{title:"Psicanálise e autismo: possibilidades e limites",summary:"Situar a contribuição psicanalítica sem transformar hipóteses em explicações causais do autismo.",body:["A Psicanálise pode oferecer espaço de escuta para história, relações, sofrimento, identidade, corpo e formas singulares de comunicação.","Ela não deve ser usada para responsabilizar famílias, negar conhecimento contemporâneo sobre autismo ou impedir acesso a suportes e tratamentos indicados."],activity:"Escreva três possibilidades e três limites da atuação psicanalítica com pessoas autistas."}),
  lesson(13,{title:"Atendimento de adultos autistas",summary:"Acolher identidade, relações, diagnóstico tardio e demandas da vida adulta.",body:["Adultos autistas podem chegar à clínica com histórias de mascaramento social, exaustão, dificuldades relacionais, ansiedade, experiências de exclusão ou descoberta tardia do diagnóstico.","A escuta deve considerar também trabalho, sexualidade, autonomia, rotina, sensorialidade e recursos já desenvolvidos pela própria pessoa."],activity:"Crie perguntas de primeira entrevista adequadas a um adulto autista sem infantilização."}),
  lesson(14,{title:"Autismo, comunicação e sensibilidade sensorial",summary:"Adaptar setting e comunicação às necessidades individuais.",body:["Luz, ruído, temperatura, duração, câmera, olhar e ritmo de fala podem influenciar profundamente o conforto de uma sessão.","Adaptação não significa abandonar o enquadre, mas torná-lo suficientemente previsível e acessível para que a pessoa possa participar."],activity:"Desenhe duas versões de setting: presencial e online, com adaptações sensoriais possíveis."}),
  lesson(15,{title:"Autismo e trabalho interdisciplinar",summary:"Saber quando e como articular-se com outros profissionais.",body:["Psicologia, psiquiatria, neurologia, terapia ocupacional, fonoaudiologia, educação e assistência social podem ocupar funções distintas conforme a necessidade da pessoa.","Interdisciplinaridade exige consentimento, respeito ao sigilo e clareza sobre o que cada profissional pode ou não oferecer."],activity:"Monte um mapa de encaminhamento para três necessidades clínicas diferentes."}),
  lesson(16,{title:"Autismo, família e cuidadores",summary:"Escutar a família preservando autonomia e subjetividade da pessoa autista.",body:["Famílias podem apresentar exaustão, culpa, medo e dúvidas reais sobre suporte. A clínica não deve transformá-las em causa do autismo nem apagar a voz da pessoa atendida.","Quando a pessoa é adulta, atenção especial deve ser dada à autonomia, consentimento e limites de compartilhamento de informações."],activity:"Escreva uma resposta clínica a um cuidador que pede detalhes confidenciais de uma sessão."}),
  lesson(17,{title:"Autismo e população LGBTQIAP+",summary:"Compreender interseções entre neurodivergência, identidade, sexualidade e pertencimento.",body:["Identidade de gênero e orientação sexual não devem ser tratadas como sintomas do autismo nem como problemas a serem corrigidos.","A escuta precisa considerar estigma, rejeição, experiências de violência, necessidade de pertencimento e possíveis barreiras de comunicação com serviços."],activity:"Analise uma vinheta fictícia evitando patologizar identidade ou orientação sexual."}),
  lesson(18,{title:"Autismo em contexto internacional",summary:"Articular autismo, migração, idioma, cultura e acesso a serviços.",body:["Uma pessoa autista migrante pode enfrentar simultaneamente mudança de rotina, idioma, burocracia, perda de rede de suporte e diferenças nos sistemas de saúde e educação.","O analista deve mapear quais dificuldades pertencem ao sofrimento subjetivo, quais dependem de acessibilidade e quais exigem apoio institucional ou interdisciplinar."],activity:"Crie um mapa de rede de apoio para uma pessoa autista brasileira vivendo na Europa."}),
  lesson(19,{title:"Caso prático internacional",summary:"Integrar migração, trabalho, relações, neurodiversidade e escuta psicanalítica.",body:["Caso fictício: uma pessoa brasileira adulta, vivendo há dois anos na Bélgica, procura atendimento por exaustão, isolamento social e conflitos no trabalho após diagnóstico tardio de autismo.","A construção do caso deve distinguir fatores migratórios, sensoriais, relacionais, laborais e subjetivos, sem atribuir tudo ao diagnóstico ou à migração."],activity:"Produza uma construção de caso com demanda, hipóteses, limites, adaptações e possíveis encaminhamentos."}),
  lesson(20,{title:"Como eu começaria uma carreira internacional hoje",summary:"Transformar experiência internacional em um plano realista de entrada no mercado.",body:["A experiência prática de Luciano Rodrigues Almeida serve aqui como estudo de percurso: adaptação a outro país, construção de presença digital, atendimento de brasileiros no exterior, organização de serviços e aprendizado com tentativas e ajustes.","Essa experiência não é apresentada como regra universal. O objetivo é extrair princípios transferíveis: pesquisar antes de anunciar, comunicar limites, começar com um público claro, criar rede e revisar continuamente a estratégia."],activity:"Projeto final: escolha um país e monte seu Plano de Internacionalização Profissional com público, pesquisa regulatória, posicionamento, oferta, preço, canais, cuidados éticos e plano de ação de 90 dias."})
];

export const psychoanalysisInternationalAutismModule:PsychoanalysisModule={
  id:15,
  title:"Psicanálise Internacional, Neurodiversidade e Autismo",
  description:"Atuação internacional, carreira no exterior, ética, proteção de dados, migração, neurodiversidade e autismo.",
  lessons,
  deeper:[
    {author:"União Europeia",title:"Proteção de dados e GDPR",year:"atual",note:"Consulte sempre o portal oficial da União Europeia e a autoridade de proteção de dados do país de atuação."},
    {author:"Organização Mundial da Saúde",title:"Autismo e saúde",year:"atual",note:"Use referências oficiais e atualizadas sobre autismo e necessidades de suporte."},
    {author:"Autoridades nacionais",title:"Regulamentação profissional",year:"atual",note:"Verifique títulos protegidos, escopo profissional, registros e exigências no país onde pretende atuar."}
  ],
  activity:"Projeto final — Plano de Internacionalização Profissional: país-alvo, público, pesquisa regulatória, posicionamento, proposta de atendimento, preço, canais de divulgação, cuidados éticos e plano de ação de 90 dias."
};
