export type PsychoanalysisLesson={id:string;title:string;summary:string;content:string[]};
export type PsychoanalysisModule={id:number;title:string;focus:string;lessons:PsychoanalysisLesson[];deeper:{title:string;author:string;year:string;note:string}[];activity:string};

const generic=(moduleId:number,titles:string[],focus:string)=>titles.map((title,i)=>({id:`m${moduleId}-l${i+1}`,title,summary:focus,content:[focus,"Esta aula organiza os conceitos centrais do tema, relacionando leitura teórica, reflexão clínica e contexto histórico. O objetivo é compreender o conceito sem reduzi-lo a definições decoradas.","Ao estudar, registre dúvidas, conceitos-chave e relações com os textos originais indicados no final do módulo."]}));

const basePsychoanalysisModules:PsychoanalysisModule[]=[
{ id:1,title:"O Nascimento da Psicanálise e a Descoberta do Inconsciente",focus:"Viena do século XIX, Freud, Breuer, Anna O., Associação Livre e Primeira Tópica.",lessons:[
{id:"m1-l1",title:"Viena e o contexto do nascimento da Psicanálise",summary:"O cenário médico, científico e cultural do final do século XIX.",content:["A Psicanálise nasceu em um momento de forte confiança na medicina positivista e na neurologia. Em Viena, sintomas sem lesão orgânica clara desafiaram os modelos médicos disponíveis e abriram espaço para novas perguntas sobre sofrimento psíquico.","Freud iniciou sua trajetória como médico neurologista. Seu interesse foi se deslocando do sistema nervoso para os fenômenos que não encontravam explicação suficiente apenas na anatomia ou na fisiologia.","Estudar esse contexto ajuda a compreender que a Psicanálise não surgiu pronta: ela foi sendo construída a partir de impasses clínicos, hipóteses, revisões e mudanças técnicas."]},
{id:"m1-l2",title:"Histeria, Breuer e o caso Anna O.",summary:"A escuta de sintomas sem causa orgânica aparente.",content:["Josef Breuer acompanhou a paciente conhecida na literatura como Anna O., pseudônimo de Bertha Pappenheim. O caso tornou-se central na narrativa histórica da Psicanálise porque associou fala, memória e transformação de sintomas.","A chamada talking cure foi descrita como uma forma de verbalização de experiências e afetos. É importante estudar o caso com rigor: relatos posteriores mostram que sua história clínica foi mais complexa do que versões introdutórias simplificadas costumam sugerir.","O valor histórico do caso está menos em uma ideia de cura milagrosa e mais na abertura de uma pergunta: que relação pode existir entre sintomas, lembranças, afetos e aquilo que não é conscientemente elaborado?"]},
{id:"m1-l3",title:"Do método catártico à hipnose",summary:"O uso inicial da hipnose e seus limites.",content:["A hipnose foi utilizada para facilitar o acesso a lembranças e afetos. Freud experimentou esse recurso, mas encontrou limitações clínicas importantes.","Nem todos os pacientes eram hipnotizáveis e os efeitos nem sempre se mantinham. Isso levou Freud a buscar uma técnica que dependesse menos do estado hipnótico e mais da própria fala do paciente."]},
{id:"m1-l4",title:"A invenção da Associação Livre",summary:"A regra fundamental da fala sem seleção prévia.",content:["A Associação Livre solicita que o analisando diga o que lhe vier à mente, inclusive pensamentos considerados banais, embaraçosos ou aparentemente sem importância.","Essa regra desloca o método da sugestão direta para uma escuta das formações, interrupções, repetições e resistências presentes na fala."]},
{id:"m1-l5",title:"A ideia de conflito psíquico",summary:"Desejos, proibições e formações de compromisso.",content:["Freud percebeu que o sofrimento psíquico podia envolver conflitos entre desejos, defesas e exigências conscientes. O sintoma passa a ser pensado como uma formação que carrega uma história e uma função psíquica.","Esse movimento foi decisivo para a construção da noção de inconsciente dinâmico."]},
{id:"m1-l6",title:"A Primeira Tópica",summary:"Consciente, Pré-consciente e Inconsciente.",content:["Na Primeira Tópica, Freud organiza o aparelho psíquico em sistemas: Consciente, Pré-consciente e Inconsciente.","O Consciente corresponde ao que está presente à percepção em determinado momento. O Pré-consciente reúne conteúdos acessíveis à consciência. O Inconsciente envolve representações submetidas a processos próprios e que não se tornam conscientes de modo direto."]},
{id:"m1-l7",title:"O inconsciente não é um depósito",summary:"Dinâmica, censura e retorno do recalcado.",content:["O inconsciente freudiano não deve ser reduzido a um arquivo de lembranças esquecidas. Ele possui funcionamento próprio e aparece de modo indireto em sonhos, atos falhos, sintomas e repetições.","Essa concepção muda a ideia de sujeito: nem toda ação humana é plenamente transparente para quem a realiza."]},
{id:"m1-l8",title:"Como ler Freud neste módulo",summary:"Leitura histórica e conceitual dos textos fundadores.",content:["Leia Freud considerando o momento em que cada texto foi escrito. Conceitos mudam ao longo da obra e não devem ser retirados de seu contexto.","Compare formulações, anote mudanças de vocabulário e observe como as hipóteses clínicas são revisadas ao longo dos anos."]},
{id:"m1-l9",title:"Síntese do Módulo 1",summary:"Do impasse médico ao método psicanalítico.",content:["O primeiro módulo percorre a passagem de uma clínica centrada na hipnose e no método catártico para uma técnica sustentada pela Associação Livre e pela hipótese do inconsciente.","Mais do que memorizar datas, o objetivo é compreender como um problema clínico levou à construção de um novo modo de escutar o sofrimento psíquico."]}
],deeper:[{title:"Estudos sobre a Histeria",author:"Sigmund Freud e Josef Breuer",year:"1895",note:"Leia especialmente os casos clínicos e a discussão sobre o método catártico."},{title:"Cinco Lições de Psicanálise",author:"Sigmund Freud",year:"1910",note:"As duas primeiras lições oferecem uma introdução histórica acessível ao surgimento do método."},{title:"A Interpretação dos Sonhos",author:"Sigmund Freud",year:"1900",note:"Use como ponte para compreender a formulação mais ampla do inconsciente."}],activity:"Explique por que a passagem da hipnose para a Associação Livre representou uma mudança fundamental na construção do método psicanalítico."},
{ id:2,title:"A Estrutura da Personalidade — A Segunda Tópica",focus:"Id, Ego, Superego e o funcionamento dinâmico do aparelho psíquico.",lessons:generic(2,["Da Primeira à Segunda Tópica","O Id","O Ego","O Superego","Princípio do prazer e princípio da realidade","Conflito psíquico","Ideal do Eu e culpa","Aplicações clínicas","Síntese do módulo"],"Compreender a segunda teoria freudiana do aparelho psíquico e a relação dinâmica entre Id, Ego e Superego."),deeper:[{title:"O Ego e o Id",author:"Sigmund Freud",year:"1923",note:"Texto central para a Segunda Tópica."},{title:"Novas Conferências Introdutórias sobre Psicanálise",author:"Sigmund Freud",year:"1933",note:"Revisão didática do modelo estrutural."}],activity:"Descreva um conflito cotidiano hipotético e mostre como Id, Ego e Superego poderiam ser utilizados como modelo para pensá-lo."},
{ id:3,title:"O Desenvolvimento Psicossexual e o Complexo de Édipo",focus:"Sexualidade infantil, fases do desenvolvimento e Complexo de Édipo.",lessons:generic(3,["Sexualidade infantil","Fase oral","Fase anal","Fase fálica","Latência","Fase genital","Complexo de Édipo","Marcas na estruturação do sujeito","Síntese do módulo"],"Estudar a teoria freudiana da sexualidade infantil e seu papel na constituição psíquica."),deeper:[{title:"Três Ensaios sobre a Teoria da Sexualidade",author:"Sigmund Freud",year:"1905",note:"Texto fundamental sobre sexualidade infantil."},{title:"A Dissolução do Complexo de Édipo",author:"Sigmund Freud",year:"1924",note:"Aprofunda a questão edípica."}],activity:"Explique por que a sexualidade infantil em Freud não pode ser reduzida à sexualidade adulta em miniatura."},
{ id:4,title:"As Forças Psíquicas: Pulsões e Narcisismo",focus:"Pulsão, Eros, pulsão de morte e narcisismo.",lessons:generic(4,["Instinto e pulsão","Fonte, pressão, meta e objeto","Pulsões de vida","Pulsão de morte","Narcisismo primário","Narcisismo secundário","Libido e investimento","Autoimagem e relações","Síntese do módulo"],"Distinguir instinto e pulsão e compreender a teoria freudiana do narcisismo."),deeper:[{title:"Os Instintos e seus Destinos",author:"Sigmund Freud",year:"1915",note:"Texto central sobre teoria pulsional."},{title:"Introdução ao Narcisismo",author:"Sigmund Freud",year:"1914",note:"Base conceitual para o estudo do narcisismo."},{title:"Além do Princípio do Prazer",author:"Sigmund Freud",year:"1920",note:"Introduz a reformulação ligada à compulsão à repetição e pulsão de morte."}],activity:"Compare pulsão e instinto e explique por que essa diferença é importante para a teoria psicanalítica."},
{ id:5,title:"Os Mecanismos de Defesa do Ego",focus:"Recalque, projeção, sublimação, racionalização, negação e formação reativa.",lessons:generic(5,["Defesa e angústia","Recalque","Projeção","Sublimação","Racionalização","Negação","Formação reativa","Defesas e clínica","Síntese do módulo"],"Estudar modos de defesa do Ego e contextualizar a contribuição de Freud e a sistematização posterior de Anna Freud."),deeper:[{title:"A Repressão",author:"Sigmund Freud",year:"1915",note:"Texto essencial sobre recalque."},{title:"Inibição, Sintoma e Angústia",author:"Sigmund Freud",year:"1926",note:"Relaciona defesa, sintoma e angústia."},{title:"O Ego e os Mecanismos de Defesa",author:"Anna Freud",year:"1936",note:"Sistematização clássica posterior dos mecanismos de defesa."}],activity:"Escolha dois mecanismos de defesa e compare suas diferenças sem transformá-los em rótulos diagnósticos."},
{ id:6,title:"As Manifestações do Inconsciente",focus:"Sonhos, atos falhos, esquecimentos e chistes.",lessons:generic(6,["Formações do inconsciente","Sonho e desejo","Conteúdo manifesto e latente","Trabalho do sonho","Atos falhos","Esquecimentos","Chistes","Leitura clínica sem adivinhação","Síntese do módulo"],"Compreender como o inconsciente aparece de forma indireta nas formações da vida cotidiana."),deeper:[{title:"A Interpretação dos Sonhos",author:"Sigmund Freud",year:"1900",note:"Obra central sobre sonho e inconsciente."},{title:"Psicopatologia da Vida Cotidiana",author:"Sigmund Freud",year:"1901",note:"Atos falhos e esquecimentos."},{title:"Os Chistes e sua Relação com o Inconsciente",author:"Sigmund Freud",year:"1905",note:"Estudo do humor e processos inconscientes."}],activity:"Diferencie conteúdo manifesto e conteúdo latente e explique por que interpretar um sonho não significa usar um dicionário fixo de símbolos."},
{ id:7,title:"Introdução à Técnica Clínica Psicanalítica",focus:"Associação Livre, Atenção Flutuante, enquadre e resistência.",lessons:generic(7,["A regra fundamental","Atenção flutuante","O enquadre","O silêncio","Resistência","Interpretação","Neutralidade e abstinência","Ética da escuta","Síntese do módulo"],"Introduzir fundamentos da técnica sem transformar a clínica em um manual mecânico."),deeper:[{title:"Recomendações aos Médicos que Exercem a Psicanálise",author:"Sigmund Freud",year:"1912",note:"Formula a atenção flutuante e recomendações técnicas."},{title:"Sobre o Início do Tratamento",author:"Sigmund Freud",year:"1913",note:"Discute enquadre e começo do trabalho analítico."}],activity:"Explique a diferença entre Associação Livre e Atenção Flutuante e por que elas formam um par técnico."},
{ id:8,title:"Transferência e Contratransferência",focus:"Relação analista-analisando, repetição, transferência e contratransferência.",lessons:generic(8,["O que é transferência","Repetição na relação analítica","Transferência amorosa","Transferência hostil","Resistência e transferência","Manejo","Contratransferência","Limites éticos","Síntese do módulo"],"Estudar a transferência como fenômeno central da clínica e a contratransferência como questão técnica a ser elaborada."),deeper:[{title:"A Dinâmica da Transferência",author:"Sigmund Freud",year:"1912",note:"Texto fundamental sobre transferência."},{title:"Observações sobre o Amor Transferencial",author:"Sigmund Freud",year:"1915",note:"Discute manejo e limites."}],activity:"Explique por que a transferência não deve ser confundida simplesmente com gostar ou não gostar do analista."},
{ id:9,title:"Os Caminhos Pós-Freudianos",focus:"Klein, Winnicott e Lacan em perspectiva comparada.",lessons:generic(9,["Depois de Freud","Melanie Klein","Posições kleinianas","Donald Winnicott","Ambiente e holding","Jacques Lacan","Linguagem e sujeito","Comparações e diferenças","Síntese do módulo"],"Apresentar três grandes linhas pós-freudianas sem apagar suas diferenças teóricas."),deeper:[{title:"Notas sobre alguns mecanismos esquizoides",author:"Melanie Klein",year:"1946",note:"Introdução a conceitos kleinianos."},{title:"O Brincar e a Realidade",author:"Donald Winnicott",year:"1971",note:"Obra central sobre ambiente, criatividade e desenvolvimento."},{title:"Escritos",author:"Jacques Lacan",year:"1966",note:"Coletânea fundamental para aprofundar o retorno a Freud e a linguagem."}],activity:"Compare uma contribuição de Klein, Winnicott e Lacan, destacando uma diferença conceitual entre eles."},
{ id:10,title:"O Mal-Estar na Atualidade — Psicanálise Aplicada",focus:"Cultura contemporânea, ansiedade, burnout, redes sociais, imediatismo e vazio.",lessons:generic(10,["Freud e a cultura","Mal-estar e renúncia","Ansiedade contemporânea","Esgotamento e trabalho","Redes sociais","Imediatismo e prazer","Vazio e repetição","Limites da aplicação social","Síntese final"],"Refletir sobre fenômenos contemporâneos à luz da Psicanálise sem reduzir sofrimento a diagnósticos simplistas."),deeper:[{title:"O Mal-Estar na Civilização",author:"Sigmund Freud",year:"1930",note:"Texto central para pensar sujeito e cultura."},{title:"Psicologia das Massas e Análise do Eu",author:"Sigmund Freud",year:"1921",note:"Ajuda a pensar identificação e laço social."},{title:"O Futuro de uma Ilusão",author:"Sigmund Freud",year:"1927",note:"Amplia a reflexão sobre cultura, crença e conflito."}],activity:"Escolha um fenômeno contemporâneo e construa uma reflexão psicanalítica sem tratá-lo automaticamente como diagnóstico clínico."}
];

const addedPsychoanalysisModules:PsychoanalysisModule[]=[
{ id:11,title:"Análise Pessoal e o Lugar do Analista",focus:"A função da análise pessoal na formação, os pontos cegos do analista, transferência, contratransferência, desejo do analista, ética e limites pessoais.",lessons:generic(11,["Por que o analista também se analisa","Autoconhecimento não é análise pessoal","Pontos cegos do analista","Transferência na própria análise","Contratransferência e implicação subjetiva","O desejo do analista","Limites pessoais e limites clínicos","Ética e responsabilidade","Afetos mobilizados pela escuta","Quando a história pessoal invade a clínica","Sustentar perguntas sem responder pelo outro","Análise pessoal e formação contínua","Preparação para a prática","Revisão do módulo","Síntese e integração"],"Compreender a análise pessoal como eixo do tripé formativo e refletir sobre a posição subjetiva de quem ocupa o lugar de analista."),deeper:[{title:"Análise Terminável e Interminável",author:"Sigmund Freud",year:"1937",note:"Texto fundamental para pensar os limites e a continuidade do trabalho analítico."},{title:"Recomendações aos Médicos que Exercem a Psicanálise",author:"Sigmund Freud",year:"1912",note:"Ajuda a refletir sobre a posição e a escuta do analista."},{title:"A Questão da Análise Leiga",author:"Sigmund Freud",year:"1926",note:"Amplia a discussão sobre formação e exercício da Psicanálise."}],activity:"Explique por que a análise pessoal é considerada parte do tripé formativo e descreva dois riscos clínicos de um analista que não reconhece seus próprios pontos cegos."},
{ id:12,title:"Supervisão Clínica e Construção da Escuta",focus:"Supervisão, apresentação de caso, hipótese clínica, manejo, ética, confidencialidade, limites e preparação para a prática.",lessons:generic(12,["O que é supervisão clínica","Como apresentar um caso","Separar fato, hipótese e interpretação","Construção da hipótese clínica","Manejo da transferência","Escuta do discurso e repetição","Silêncio e intervenção","Impasse clínico","Limites do analista","Ética e confidencialidade","Quando encaminhar","Registro e organização do caso","Supervisão como formação contínua","Preparação para início da prática","Síntese e integração"],"Compreender a supervisão como espaço de elaboração técnica, ética e clínica na formação psicanalítica."),deeper:[{title:"Recordar, Repetir e Elaborar",author:"Sigmund Freud",year:"1914",note:"Ajuda a pensar repetição, elaboração e manejo clínico."},{title:"Observações sobre o Amor Transferencial",author:"Sigmund Freud",year:"1915",note:"Texto importante para refletir sobre manejo e limites na transferência."},{title:"Construções em Análise",author:"Sigmund Freud",year:"1937",note:"Aprofunda a reflexão sobre construção, hipótese e trabalho clínico."}],activity:"Construa uma vinheta clínica fictícia curta e diferencie: fatos relatados, hipótese de trabalho, elementos transferenciais e pontos que você levaria para supervisão."}
];

const extensionTitles:Record<number,string[]>={
1:["Leitura orientada: Estudos sobre a Histeria","Mapa conceitual da Primeira Tópica","Exercício: consciente, pré-consciente e inconsciente","Caso histórico: o método catártico","Prática de leitura: Associação Livre","Perguntas de revisão do Módulo 1","Conexões entre sintoma, memória e afeto","Diário de estudo: o nascimento do método","Preparação para a atividade final"],
2:["Leitura orientada: O Ego e o Id","Mapa conceitual: Id, Ego e Superego","Exercício sobre conflito psíquico","Princípio do prazer na vida cotidiana","Princípio da realidade e mediação","Ideal do Eu e exigência moral","Perguntas de revisão da Segunda Tópica","Aplicação teórica em situação hipotética","Preparação para a atividade final"],
3:["Leitura orientada: Três Ensaios","Mapa das fases do desenvolvimento","Exercício: fase oral e dependência","Exercício: fase anal e controle","Exercício: fase fálica e diferença","Latência e reorganização psíquica","Complexo de Édipo em perspectiva histórica","Perguntas de revisão do desenvolvimento","Preparação para a atividade final"],
4:["Leitura orientada: Introdução ao Narcisismo","Mapa conceitual das pulsões","Fonte, pressão, meta e objeto na prática teórica","Eros e ligação psíquica","Compulsão à repetição e pulsão de morte","Narcisismo primário e secundário","Investimento libidinal e relações","Perguntas de revisão das pulsões","Preparação para a atividade final"],
5:["Leitura orientada: A Repressão","Mapa das defesas do Ego","Exercício comparativo: recalque e negação","Projeção sem rótulos diagnósticos","Sublimação e produção cultural","Racionalização e narrativa consciente","Formação reativa em perspectiva teórica","Perguntas de revisão das defesas","Preparação para a atividade final"],
6:["Leitura orientada: A Interpretação dos Sonhos","Mapa do trabalho do sonho","Exercício: manifesto e latente","Condensação e deslocamento","Atos falhos no cotidiano","Esquecimento e conflito","Chistes e economia psíquica","Perguntas de revisão das formações do inconsciente","Preparação para a atividade final"],
7:["Leitura orientada: Recomendações aos Médicos","Mapa da técnica psicanalítica","Associação Livre em profundidade","Atenção Flutuante e escuta","Enquadre e constância","Silêncio, tempo e intervenção","Resistência sem confronto mecânico","Perguntas de revisão da técnica","Preparação para a atividade final"],
8:["Leitura orientada: A Dinâmica da Transferência","Mapa da transferência","Repetição e atualização na relação analítica","Transferência amorosa e manejo","Transferência hostil e resistência","Contratransferência e elaboração","Limites éticos na relação analítica","Perguntas de revisão da transferência","Preparação para a atividade final"],
9:["Leitura orientada: Melanie Klein","Leitura orientada: Donald Winnicott","Leitura orientada: Jacques Lacan","Mapa comparativo pós-freudiano","Klein e fantasia inconsciente","Winnicott e ambiente facilitador","Lacan, linguagem e sujeito","Perguntas de revisão dos autores","Preparação para a atividade final"],
10:["Leitura orientada: O Mal-Estar na Civilização","Mapa do sujeito e da cultura","Ansiedade e contemporaneidade sem diagnóstico automático","Trabalho, produtividade e esgotamento","Redes sociais e reconhecimento","Imediatismo e satisfação","Vazio, repetição e laço social","Perguntas de revisão da Psicanálise aplicada","Síntese final do percurso"]
};
function extensionLesson(module:PsychoanalysisModule,title:string,index:number):PsychoanalysisLesson{return {id:`m${module.id}-l${10+index}`,title,summary:module.focus,content:[`Esta unidade aprofunda ${title.toLowerCase()} dentro do eixo do módulo ${module.id}.`,`O objetivo é transformar a leitura em elaboração: compare conceitos, registre dúvidas e relacione esta unidade aos textos originais recomendados no módulo.`,`Ao final, produza uma síntese curta com o que mudou na sua compreensão do tema e uma pergunta que você levaria para um encontro ao vivo ou para o fórum da formação.`]};}
export const psychoanalysisModules:PsychoanalysisModule[]=[...basePsychoanalysisModules,...addedPsychoanalysisModules].map(module=>module.id<=10?({...module,lessons:[...module.lessons,...((extensionTitles[module.id]??[]).slice(0,6).map((title,index)=>extensionLesson(module,title,index)))]}):module);

export const PSYCHOANALYSIS_TOTAL_LESSONS=psychoanalysisModules.reduce((n,m)=>n+m.lessons.length,0);
