export type PsychoanalystProgramKey="marketing-psicanalistas"|"agenda-clinica"|"psicanalista-10k";
export type PsychoanalystProgram={key:PsychoanalystProgramKey;title:string;shortTitle:string;subtitle:string;hours:number;priceBRL:number;priceEUR:number;level:string;modules:string[];deliverables:string[]};

export const PSYCHOANALYST_PROGRAMS:PsychoanalystProgram[]=[
{key:"marketing-psicanalistas",shortTitle:"Marketing para Psicanalistas",title:"Marketing para Psicanalistas — Do Posicionamento ao Primeiro Paciente",subtitle:"Posicionamento, autoridade, conteúdo e aquisição ética para a prática psicanalítica.",hours:120,priceBRL:197,priceEUR:39,level:"Profissional",modules:["Fundamentos do Marketing de Serviços Profissionais","Posicionamento e Diferenciação","Comportamento de Quem Procura Atendimento","Instagram Profissional","Estratégia de Conteúdo","Aquisição Orgânica","WhatsApp e Primeiro Contato","Jornada de Aquisição","Marketing Pago","Projeto Final — Plano de Aquisição de 90 Dias"],deliverables:["Posicionamento e proposta de valor","Bio e estrutura do Instagram","30 ideias de conteúdo","Calendário editorial de 90 dias","Estratégia de aquisição e WhatsApp","Indicadores e plano de otimização"]},
{key:"agenda-clinica",shortTitle:"Agenda Clínica",title:"Agenda Clínica — Como Atrair, Organizar e Consolidar Pacientes",subtitle:"Planejamento, capacidade, organização e indicadores para uma agenda clínica sustentável.",hours:180,priceBRL:297,priceEUR:59,level:"Profissional",modules:["A Clínica como Prática Profissional","Onde Encontrar Pacientes","Primeiro Contato","Primeira Sessão e Organização Administrativa","Organização Semanal","Planejamento Mensal","Faltas e Cancelamentos","Pagamentos e Inadimplência","Experiência Administrativa do Paciente","Continuidade Clínica e Limites Éticos","Indicadores da Agenda","Projeto Final — Agenda Clínica de 12 Meses"],deliverables:["Agenda semanal e mensal","Política administrativa de faltas e pagamentos","Dashboard de indicadores","Cenários de capacidade e faturamento","Plano de agenda clínica de 12 meses"]},
{key:"psicanalista-10k",shortTitle:"Psicanalista 10K+",title:"Psicanalista 10K+ — Gestão, Marca e Crescimento da Prática Clínica",subtitle:"Estratégia avançada para construir uma prática clínica com potencial de faturamento acima de R$ 10 mil/mês, sem promessa de renda.",hours:360,priceBRL:497,priceEUR:89,level:"Avançado",modules:["Estratégia da Prática Profissional","Modelo de Negócio","Economia da Prática Clínica","Precificação","Capacidade e Ocupação","Receita, Custos e Resultado","Indicadores","Custo de Aquisição","Valor do Relacionamento Profissional","Autoridade e Reputação","Marca Pessoal","Automação Administrativa","Expansão Internacional","Produtos Educacionais Complementares","Plano Estratégico de 12 Meses"],deliverables:["Modelo econômico da prática","Plano de precificação e capacidade","Dashboard estratégico","Plano de autoridade e reputação","Plano de crescimento sustentável","Plano estratégico de 12 meses"]}
];

export const PSYCHOANALYST_TRILOGY={title:"Psicanalista de Alta Performance",subtitle:"Marketing, agenda, gestão e crescimento para construir uma prática clínica profissional, ética e sustentável.",hours:660,priceBRL:797,priceEUR:149,separateBRL:991,separateEUR:187,savingBRL:194,savingEUR:38};

export const CLINICAL_PRACTICE_LAB=[
{title:"Do início à aquisição",case:"Tenho 3 pacientes, 840 seguidores e nenhum orçamento para anúncios.",task:"Diagnosticar posicionamento, canais, conteúdo, cronograma e indicadores para 90 dias."},
{title:"Agenda cheia, baixa sustentabilidade",case:"Tenho 25 pacientes, agenda cheia, estou exausto e minha rentabilidade é baixa.",task:"Analisar capacidade, horários, preço, faltas, despesas, carga semanal e sustentabilidade."},
{title:"Audiência sem contatos",case:"Tenho seguidores, mas quase ninguém entra em contato.",task:"Analisar perfil, bio, conteúdo, CTA, confiança, posicionamento, jornada e WhatsApp."},
{title:"Prática internacional",case:"Quero construir uma prática para brasileiros que vivem na Europa.",task:"Desenvolver posicionamento, idiomas, comunicação, moeda, horários, canais e pontos regulatórios a validar."}
];

export const ACADEMIC_METHOD=["Objetivo de aprendizagem","Fundamento conceitual","Leitura e referências verificáveis","Estudo de caso","Exercício aplicado","Entrega prática","Indicador","Avaliação"];
export const ETHICS_RULES=["Marketing não substitui competência clínica","Paciente não deve ser reduzido a lead","Não criar dependência para aumentar receita","Nunca usar conteúdo clínico confidencial em marketing","Preservar autonomia e sigilo","Evitar pressão comercial","Separar comunicação comercial da relação analítica"];
