import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { CheckCircle2, ChevronLeft, ChevronRight, GraduationCap, LockKeyhole } from "lucide-react";
import { useEffect, useState } from "react";
import { mentorshipCareerModules, MENTORSHIP_TOTAL_LESSONS } from "@/content/mentorship-career-curriculum";
import { clientCreateMentorshipCheckout, clientMentorshipOffer } from "@/lib/mentorship-commerce.functions";
import { clientSaveProgress } from "@/lib/learning.functions";

export const Route=createFileRoute("/_clientarea/cliente/treinamentos/mentoria-carreira")({component:MentorshipCareerTraining});

type Saved={completed:string[];module:number;lesson:number;answers:Record<string,string>};
const EMPTY:Saved={completed:[],module:0,lesson:0,answers:{}};
const KEY="ldr-mentorship-career-v1";
function loadState():Saved{if(typeof window==="undefined")return EMPTY;try{const p=JSON.parse(localStorage.getItem(KEY)||"");return {...EMPTY,...p,answers:p.answers??{},completed:Array.isArray(p.completed)?p.completed:[]};}catch{return EMPTY;}}

function MentorshipCareerTraining(){
 const offerFn=useServerFn(clientMentorshipOffer);const checkoutFn=useServerFn(clientCreateMentorshipCheckout);const saveProgressFn=useServerFn(clientSaveProgress);
 const {data:offer,isLoading}=useQuery({queryKey:["mentorship-career-offer"],queryFn:()=>offerFn({})});
 const checkout=useMutation({mutationFn:(market:"BR"|"INTL")=>checkoutFn({data:{market}}),onSuccess:r=>{window.location.href=r.url;}});
 const [state,setState]=useState<Saved>(EMPTY);const [answer,setAnswer]=useState("");
 useEffect(()=>setState(loadState()),[]);
 const mod=mentorshipCareerModules[Math.min(state.module,mentorshipCareerModules.length-1)];const current=mod.lessons[Math.min(state.lesson,mod.lessons.length-1)];
 useEffect(()=>setAnswer(state.answers[`m${mod.id}`]??""),[mod.id,state.answers]);
 const progress=Math.round((state.completed.length/MENTORSHIP_TOTAL_LESSONS)*100);
 const maxUnlockedLesson=Math.max(1,Math.min(MENTORSHIP_TOTAL_LESSONS,Number(offer?.elapsedDays??0)+1));
 const currentGlobalIndex=mentorshipCareerModules.slice(0,state.module).reduce((sum,m)=>sum+m.lessons.length,0)+state.lesson;
 const nextLocked=currentGlobalIndex+1>=maxUnlockedLesson;
 const persist=(next:Saved)=>{setState(next);try{localStorage.setItem(KEY,JSON.stringify(next));}catch{}const pct=Math.round((next.completed.length/MENTORSHIP_TOTAL_LESSONS)*100);const m=mentorshipCareerModules[Math.min(next.module,mentorshipCareerModules.length-1)];const l=m.lessons[Math.min(next.lesson,m.lessons.length-1)];saveProgressFn({data:{productKey:"formacao_mentoria_profissional_carreira",progressPercent:pct,currentLocation:`Módulo ${m.id} · ${l.title}`}}).catch(()=>undefined);};
 const markDone=()=>{const completed=state.completed.includes(current.id)?state.completed:[...state.completed,current.id];persist({...state,completed});};
 const next=()=>{if(nextLocked)return;const completed=state.completed.includes(current.id)?state.completed:[...state.completed,current.id];if(state.lesson<mod.lessons.length-1){persist({...state,completed,lesson:state.lesson+1});return;}if(state.module<mentorshipCareerModules.length-1)persist({...state,completed,module:state.module+1,lesson:0});else persist({...state,completed});};
 const previous=()=>{if(state.lesson>0)return persist({...state,lesson:state.lesson-1});if(state.module>0){const prev=mentorshipCareerModules[state.module-1];persist({...state,module:state.module-1,lesson:prev.lessons.length-1});}};
 const saveAnswer=()=>persist({...state,answers:{...state.answers,[`m${mod.id}`]:answer}});
 const doneThis=state.completed.includes(current.id);
 if(isLoading)return <section className="s8-card">Carregando formação…</section>;
 if(!offer?.entitled)return <section className="overflow-hidden rounded-[28px] border border-[#3b82f6]/35 bg-gradient-to-br from-[#071a33] via-[#0b3b78] to-[#0d5cab] p-6 text-white shadow-xl"><LockKeyhole className="h-8 w-8 text-[#93c5fd]"/><p className="mt-4 text-xs font-black uppercase tracking-[.16em] text-[#bfdbfe]">Formação protegida</p><h1 className="mt-2 font-serif text-3xl font-bold">Formação em Mentoria Profissional e de Carreira</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/80">Percurso estruturado de 3 meses · 90 aulas · 1 aula por dia · cerca de 40 minutos de estudo guiado diário · acesso vitalício aos conteúdos digitais.</p><div className="mt-5 flex flex-wrap gap-3"><button disabled={checkout.isPending} onClick={()=>checkout.mutate("BR")} className="rounded-2xl bg-white px-5 py-3 text-sm font-black text-[#0b3b78]">Brasil · R$ 299,99 · pagamento único</button><button disabled={checkout.isPending} onClick={()=>checkout.mutate("INTL")} className="rounded-2xl border border-white/25 px-5 py-3 text-sm font-black">Europa · € 49,90</button><Link to="/cliente/biblioteca" className="rounded-2xl border border-white/25 px-5 py-3 text-sm font-black">Voltar à biblioteca</Link></div></section>;
 return <div className="min-w-0 space-y-5 pb-10">
  <section className="overflow-hidden rounded-[28px] border border-[#60a5fa]/35 bg-gradient-to-br from-[#071a33] via-[#0b3b78] to-[#0d5cab] p-5 text-white shadow-xl sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><span className="inline-flex items-center gap-2 rounded-full bg-white px-3 py-1.5 text-[11px] font-black uppercase tracking-[.15em] text-[#0b3b78]"><GraduationCap className="h-3.5 w-3.5"/>Acesso liberado</span><h1 className="mt-4 font-serif text-3xl font-bold sm:text-4xl">Formação em Mentoria Profissional e de Carreira</h1><p className="mt-2 text-sm text-white/80">3 meses · 90 aulas · 1 aula por dia · 40 min/dia · pagamento único · acesso vitalício aos conteúdos digitais</p></div><div className="min-w-[210px] rounded-2xl bg-white/10 p-4"><div className="flex items-center justify-between text-xs font-bold"><span>Seu progresso</span><span>{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-white" style={{width:`${progress}%`}}/></div><p className="mt-2 text-[11px] text-white/70">{state.completed.length} de {MENTORSHIP_TOTAL_LESSONS} aulas concluídas</p><p className="mt-1 text-[11px] text-white/60">{maxUnlockedLesson} aulas liberadas pelo percurso diário</p></div></div></section>

  <section className="grid gap-4 lg:grid-cols-[280px_minmax(0,1fr)]">
   <aside className="rounded-[24px] border border-[#bfdbfe] bg-white p-3 shadow-sm lg:sticky lg:top-20 lg:self-start"><div className="mb-3 px-2"><p className="text-xs font-black uppercase tracking-[.14em] text-[#0b5cab]">Módulos</p><p className="mt-1 text-xs text-[#64748b]">90 dias de percurso estruturado · 1 aula por dia · acesso digital vitalício.</p></div><div className="grid gap-2 lg:max-h-[72vh] lg:overflow-y-auto">{mentorshipCareerModules.map((m,mi)=>{const completedCount=m.lessons.filter(l=>state.completed.includes(l.id)).length;const firstIndex=mentorshipCareerModules.slice(0,mi).reduce((sum,x)=>sum+x.lessons.length,0);const locked=firstIndex>=maxUnlockedLesson;return <button key={m.id} disabled={locked} onClick={()=>persist({...state,module:mi,lesson:0})} className={`w-full rounded-xl px-3 py-3 text-left disabled:cursor-not-allowed disabled:opacity-40 ${state.module===mi?"bg-[#0b5cab] text-white":"hover:bg-[#eff6ff]"}`}><span className="block text-[10px] font-black uppercase tracking-[.12em] opacity-70">Módulo {String(m.id).padStart(2,"0")} · {completedCount}/{m.lessons.length}{locked?" · libera ao longo do percurso":""}</span><span className="mt-1 block text-sm font-bold leading-5">{m.title}</span></button>})}</div></aside>
   <main className="min-w-0 space-y-4">
    <section className="rounded-[24px] border border-[#bfdbfe] bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#dbeafe] px-3 py-1 text-[10px] font-black uppercase tracking-[.12em] text-[#0b5cab]">Módulo {mod.id}</span><span className="rounded-full bg-[#eff6ff] px-3 py-1 text-[10px] font-black uppercase tracking-[.12em] text-[#1d4ed8]">Aula {state.lesson+1}/{mod.lessons.length}</span><span className="rounded-full bg-[#eff6ff] px-3 py-1 text-[10px] font-black uppercase tracking-[.12em] text-[#1d4ed8]">{current.studyMinutes} min</span>{doneThis?<span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black uppercase tracking-[.12em] text-emerald-700"><CheckCircle2 className="h-3 w-3"/>Concluída</span>:null}</div><h2 className="mt-4 font-serif text-3xl font-bold text-[#0f2f57]">{current.title}</h2><p className="mt-2 text-sm font-semibold text-[#2563a7]">{current.summary}</p><div className="mt-6 space-y-4 text-[15px] leading-7 text-[#475569]">{current.content.map((p,i)=><p key={i}>{p}</p>)}</div><div className="mt-8 flex flex-wrap justify-between gap-3 border-t border-[#dbeafe] pt-5"><button onClick={previous} disabled={state.module===0&&state.lesson===0} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-[#bfdbfe] px-4 py-2 text-sm font-bold disabled:opacity-30"><ChevronLeft className="h-4 w-4"/>Anterior</button><div className="flex gap-2"><button onClick={markDone} className="rounded-xl border border-[#93c5fd] px-4 py-2 text-sm font-bold text-[#0b5cab]">Marcar concluída</button><button onClick={next} disabled={nextLocked} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#0b5cab] px-4 py-2 text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-40">{nextLocked?"Próxima aula libera no próximo dia":"Próxima"}<ChevronRight className="h-4 w-4"/></button></div></div></section>
    {state.lesson===mod.lessons.length-1?<section className="rounded-[24px] border border-[#bfdbfe] bg-[#eff6ff] p-5 sm:p-6"><h3 className="font-serif text-2xl font-bold text-[#0f2f57]">Atividade do módulo</h3><p className="mt-2 text-sm leading-6 text-[#475569]">{mod.activity}</p><textarea value={answer} onChange={e=>setAnswer(e.target.value)} rows={6} placeholder="Escreva sua resposta…" className="mt-4 w-full rounded-2xl border border-[#bfdbfe] bg-white p-4 text-sm outline-none focus:border-[#3b82f6]"/><button onClick={saveAnswer} className="mt-3 rounded-xl bg-[#0b5cab] px-4 py-2 text-sm font-black text-white">Salvar atividade</button></section>:null}
   </main>
  </section>
 </div>;
}