import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Award, CalendarDays, Trophy } from "lucide-react";
import { academicChallenges } from "@/lib/academic-challenges-v2.functions";
import { useI18n } from "@/lib/i18n";

export const Route=createFileRoute("/_clientarea/cliente/rede-academica/desafios")({component:AcademicChallengesPage});
type L="pt"|"en"|"fr"|"es";
const COPY={
 pt:{back:"REDE ACADÊMICA",title:"Desafio Acadêmico LDR",desc:"Participe com artigo ou reflexão. A avaliação combina comunidade e júri editorial; Acolher sozinho não define o resultado.",loading:"Carregando desafios…",error:"Não foi possível carregar os desafios.",open:"ABERTO",closed:"ENCERRADO",community:"comunidade",jury:"júri",entry:"Participação registrada",article:"CRIAR ARTIGO",reflection:"CRIAR REFLEXÃO",rules:"VER REGRAS",empty:"Nenhum desafio publicado neste momento."},
 en:{back:"ACADEMIC NETWORK",title:"LDR Academic Challenge",desc:"Participate with an article or reflection. Evaluation combines community input and an editorial jury; support alone does not determine the result.",loading:"Loading challenges…",error:"Challenges could not be loaded.",open:"OPEN",closed:"CLOSED",community:"community",jury:"jury",entry:"Entry registered",article:"CREATE ARTICLE",reflection:"CREATE REFLECTION",rules:"VIEW RULES",empty:"No challenge is published right now."},
 fr:{back:"RÉSEAU ACADÉMIQUE",title:"Défi Académique LDR",desc:"Participez avec un article ou une réflexion. L’évaluation combine la communauté et un jury éditorial ; le soutien seul ne détermine pas le résultat.",loading:"Chargement des défis…",error:"Impossible de charger les défis.",open:"OUVERT",closed:"TERMINÉ",community:"communauté",jury:"jury",entry:"Participation enregistrée",article:"CRÉER UN ARTICLE",reflection:"CRÉER UNE RÉFLEXION",rules:"VOIR LES RÈGLES",empty:"Aucun défi publié pour le moment."},
 es:{back:"RED ACADÉMICA",title:"Desafío Académico LDR",desc:"Participa con un artículo o una reflexión. La evaluación combina comunidad y jurado editorial; el apoyo por sí solo no define el resultado.",loading:"Cargando desafíos…",error:"No se pudieron cargar los desafíos.",open:"ABIERTO",closed:"CERRADO",community:"comunidad",jury:"jurado",entry:"Participación registrada",article:"CREAR ARTÍCULO",reflection:"CREAR REFLEXIÓN",rules:"VER REGLAS",empty:"No hay desafíos publicados en este momento."}
} as const;
function AcademicChallengesPage(){
  const {locale:raw}=useI18n();const locale=(raw==="en"||raw==="fr"||raw==="es"?raw:"pt") as L,t=COPY[locale];
  const list=useServerFn(academicChallenges);const {data=[],isLoading,error}=useQuery({queryKey:["academic-challenges"],queryFn:()=>list()});
  return <div className="mx-auto max-w-5xl space-y-5 px-3 pb-28 pt-4 sm:px-6 sm:pt-6"><div className="flex items-start justify-between gap-4"><div><Link to="/cliente/rede-academica" className="text-xs font-black text-[#07315a] dark:text-[#efc56d]">← {t.back}</Link><p className="mt-4 text-[10px] font-black tracking-[.18em] text-[#9a772c]">LDR ESSENCE ACADEMY</p><h1 className="mt-1 font-serif text-3xl sm:text-4xl">{t.title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{t.desc}</p></div><span className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-[#071426] text-[#efc56d]"><Trophy className="h-7 w-7"/></span></div>{isLoading?<div className="rounded-2xl border p-6">{t.loading}</div>:error?<div className="rounded-2xl border p-6">{t.error}</div>:data.length?<div className="grid gap-4 lg:grid-cols-2">{data.map((c:any)=><article key={c.id} className="rounded-[26px] border bg-card p-5 shadow-sm"><div className="flex flex-wrap gap-2 text-[10px] font-black"><span className="rounded-full bg-[#f6efde] px-3 py-1 text-[#7b5a1d]">{c.status==="published"?t.open:t.closed}</span>{c.category&&<span className="rounded-full bg-muted px-3 py-1">{c.category}</span>}</div><h2 className="mt-3 font-serif text-2xl">{c.title}</h2><p className="mt-1 font-bold text-[#07315a] dark:text-[#efc56d]">{c.theme}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{c.description}</p><div className="mt-4 flex flex-wrap items-center gap-3 text-[10px] text-muted-foreground"><span className="flex items-center gap-1"><CalendarDays className="h-3 w-3"/>{new Date(c.starts_at).toLocaleDateString(locale)} — {new Date(c.ends_at).toLocaleDateString(locale)}</span><span>{c.community_weight}% {t.community} · {c.jury_weight}% {t.jury}</span></div>{c.myEntry?<div className="mt-4 rounded-xl border bg-muted/40 p-3 text-xs font-bold"><Award className="mr-2 inline h-4 w-4 text-[#c99b38]"/>{t.entry} · {c.myEntry.status}{c.myEntry.badge?` · ${String(c.myEntry.badge).replaceAll("_"," ")}`:""}</div>:c.status==="published"?<div className="mt-4 grid gap-2 sm:grid-cols-2"><Link to="/cliente/rede-academica/criar-artigo" className="flex min-h-11 items-center justify-center rounded-xl bg-[#07315a] px-3 text-xs font-black text-white">{t.article}</Link><Link to="/cliente/rede-academica/criar" className="flex min-h-11 items-center justify-center rounded-xl border px-3 text-xs font-black">{t.reflection}</Link></div>:null}{c.rules&&<details className="mt-4 rounded-xl border p-3"><summary className="cursor-pointer text-xs font-black">{t.rules}</summary><p className="mt-3 whitespace-pre-wrap text-xs leading-5 text-muted-foreground">{c.rules}</p></details>}</article>)}</div>:<div className="rounded-2xl border border-dashed p-10 text-center text-sm text-muted-foreground">{t.empty}</div>}</div>
}
