import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Bell, Check, ChevronRight } from "lucide-react";
import { useState } from "react";
import { academicMarkNotificationRead, academicNotifications } from "@/lib/academic-social-v2.functions";

export const Route=createFileRoute("/_clientarea/cliente/rede-academica/notificacoes")({component:AcademicNotificationsPage});
function AcademicNotificationsPage(){
  const qc=useQueryClient();const listFn=useServerFn(academicNotifications),readFn=useServerFn(academicMarkNotificationRead);const [mode,setMode]=useState<"all"|"unread">("all");
  const {data=[],isLoading,error}=useQuery({queryKey:["academic-notifications"],queryFn:()=>listFn()});
  const mark=useMutation({mutationFn:(id:string)=>readFn({data:{id}}),onSuccess:()=>qc.invalidateQueries({queryKey:["academic-notifications"]})});
  if(isLoading)return <div className="mx-auto max-w-4xl p-6 text-sm text-muted-foreground">Carregando notificações…</div>;
  const items=mode==="unread"?data.filter((x:any)=>!x.isRead):data;
  return <div className="mx-auto max-w-4xl space-y-5 px-3 pb-28 pt-4 sm:px-6 sm:pt-6"><div className="flex items-center justify-between gap-3"><div><Link to="/cliente/rede-academica" className="text-xs font-black text-[#07315a] dark:text-[#efc56d]">← REDE ACADÊMICA</Link><h1 className="mt-2 font-serif text-3xl">Notificações</h1></div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#edf4fb] text-[#07315a] dark:bg-slate-800"><Bell className="h-6 w-6"/></span></div><div className="grid grid-cols-2 overflow-hidden rounded-2xl border bg-card"><button onClick={()=>setMode("all")} className={`min-h-11 text-xs font-black ${mode==="all"?"bg-[#07315a] text-white":""}`}>TODAS</button><button onClick={()=>setMode("unread")} className={`min-h-11 text-xs font-black ${mode==="unread"?"bg-[#07315a] text-white":""}`}>NÃO LIDAS · {data.filter((x:any)=>!x.isRead).length}</button></div>{error?<div className="rounded-2xl border p-5 text-sm">Não foi possível carregar as notificações.</div>:items.length?<div className="space-y-3">{items.map((n:any)=><article key={n.id} className={`rounded-2xl border bg-card p-4 shadow-sm ${n.isRead?"opacity-70":"border-[#d8cba9]"}`}><div className="flex items-start gap-3"><span className={`mt-0.5 h-2.5 w-2.5 shrink-0 rounded-full ${n.isRead?"bg-muted":"bg-[#c99b38]"}`}/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-3"><div><b className="text-sm">{n.subject||"Rede Acadêmica LDR"}</b><p className="mt-1 text-sm leading-6 text-muted-foreground">{n.body}</p></div><ChevronRight className="h-4 w-4 shrink-0 text-muted-foreground"/></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2"><span className="text-[10px] text-muted-foreground">{new Date(n.created_at).toLocaleString()}</span>{!n.isRead&&<button disabled={mark.isPending} onClick={()=>mark.mutate(n.id)} className="min-h-10 rounded-xl border px-3 text-[10px] font-black"><Check className="mr-1 inline h-4 w-4"/>MARCAR COMO LIDA</button>}</div></div></div></article>)}</div>:<div className="rounded-2xl border border-dashed p-10 text-center text-sm text-muted-foreground">Nenhuma notificação nesta área.</div>}</div>
}
