import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Bookmark, BookOpen } from "lucide-react";
import { academicSavedContent } from "@/lib/academic-saved-v2.functions";
import { useI18n } from "@/lib/i18n";

export const Route=createFileRoute("/_clientarea/cliente/rede-academica/salvos")({component:AcademicSavedPage});
type L="pt"|"en"|"fr"|"es";
const COPY={
 pt:{back:"REDE ACADÊMICA",title:"Salvos",private:"Somente você vê esta área.",loading:"Carregando…",error:"Não foi possível carregar os itens salvos.",posts:"Publicações",articles:"Artigos",empty:"Nada salvo nesta categoria."},
 en:{back:"ACADEMIC NETWORK",title:"Saved",private:"Only you can see this area.",loading:"Loading…",error:"Saved items could not be loaded.",posts:"Posts",articles:"Articles",empty:"Nothing saved in this category."},
 fr:{back:"RÉSEAU ACADÉMIQUE",title:"Enregistrés",private:"Vous seul pouvez voir cet espace.",loading:"Chargement…",error:"Impossible de charger les éléments enregistrés.",posts:"Publications",articles:"Articles",empty:"Aucun élément enregistré dans cette catégorie."},
 es:{back:"RED ACADÉMICA",title:"Guardados",private:"Solo tú puedes ver esta área.",loading:"Cargando…",error:"No se pudieron cargar los elementos guardados.",posts:"Publicaciones",articles:"Artículos",empty:"No hay elementos guardados en esta categoría."}
} as const;
function AcademicSavedPage(){const {locale:raw}=useI18n();const locale=(raw==="en"||raw==="fr"||raw==="es"?raw:"pt") as L,t=COPY[locale];const list=useServerFn(academicSavedContent);const {data,isLoading,error}=useQuery({queryKey:["academic-saved-content"],queryFn:()=>list()});return <div className="mx-auto max-w-5xl space-y-5 px-3 pb-28 pt-4 sm:px-6 sm:pt-6"><Link to="/cliente/rede-academica" className="text-xs font-black text-[#07315a] dark:text-[#efc56d]">← {t.back}</Link><header><div className="flex items-center gap-2"><Bookmark className="h-6 w-6 text-[#c99b38]"/><h1 className="font-serif text-3xl">{t.title}</h1></div><p className="mt-1 text-sm text-muted-foreground">{t.private}</p></header>{isLoading?<p className="text-sm text-muted-foreground">{t.loading}</p>:error||!data?<div className="rounded-2xl border p-5">{t.error}</div>:<div className="grid gap-6 lg:grid-cols-2"><section><h2 className="mb-3 font-serif text-xl">{t.posts}</h2><div className="space-y-3">{data.posts.length?data.posts.map((p:any)=><Link key={p.id} to="/cliente/rede-academica/post/$id" params={{id:p.id}} className="block rounded-2xl border bg-card p-4 shadow-sm"><span className="text-[10px] font-black text-[#9a772c]">{String(p.post_type).toUpperCase()}</span><p className="mt-2 line-clamp-4 whitespace-pre-wrap text-sm leading-6">{p.body}</p></Link>):<Empty text={t.empty}/>}</div></section><section><h2 className="mb-3 font-serif text-xl">{t.articles}</h2><div className="space-y-3">{data.articles.length?data.articles.map((a:any)=><Link key={a.id} to="/cliente/rede-academica/artigo/$slug" params={{slug:a.slug}} className="block rounded-2xl border bg-card p-4 shadow-sm"><BookOpen className="h-4 w-4 text-[#c99b38]"/><b className="mt-2 block font-serif text-lg">{a.title}</b><p className="mt-1 line-clamp-3 text-sm text-muted-foreground">{a.summary}</p></Link>):<Empty text={t.empty}/>}</div></section></div>}</div>}
function Empty({text}:{text:string}){return <div className="rounded-2xl border border-dashed p-6 text-center text-sm text-muted-foreground">{text}</div>}
