import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useState } from "react";
import { GraduationCap, Radio, School, Sparkles } from "lucide-react";
import { undergraduateCourse } from "@/lib/undergraduate.catalog";
import { clientSubmitUndergraduateInterest } from "@/lib/undergraduate-interest.functions";

export const Route=createFileRoute("/_clientarea/cliente/graduacao/$courseKey")({component:UndergraduatePage});

function UndergraduatePage(){
 const {courseKey}=Route.useParams();
 const course=undergraduateCourse(courseKey);
 const submitFn=useServerFn(clientSubmitUndergraduateInterest);
 const [form,setForm]=useState({fullName:"",email:"",phone:"",country:""});
 const submit=useMutation({mutationFn:()=>submitFn({data:{courseKey, ...form}})});
 if(!course)return <div className="rounded-3xl border bg-card p-6"><h1 className="text-2xl font-bold">Graduação não encontrada</h1><Link to="/cliente/biblioteca" className="mt-4 inline-block font-bold text-primary">Voltar à Biblioteca</Link></div>;
 return <div className="mx-auto max-w-5xl space-y-6 pb-10">
  <section className="overflow-hidden rounded-[30px] bg-gradient-to-br from-[#071426] via-[#0b2341] to-[#163b67] p-6 text-white shadow-xl sm:p-9">
   <div className="flex flex-wrap gap-2"><span className="rounded-full bg-[#d6ad63] px-3 py-1 text-[10px] font-black uppercase tracking-[.15em] text-[#281605]">🎓 Graduação · Em breve</span><span className="rounded-full bg-white/10 px-3 py-1 text-[10px] font-black uppercase">Proposta acadêmica preliminar</span></div>
   <div className="mt-5 flex items-start gap-4"><div className="text-4xl">{course.icon}</div><div><h1 className="font-serif text-3xl font-bold text-[#fff7e7] sm:text-4xl">{course.title}</h1><p className="mt-3 max-w-3xl text-sm leading-7 text-white/78">{course.intro}</p></div></div>
   <div className="mt-6 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-white/60">Duração prevista</p><strong>{course.years} anos · {course.semesters} semestres</strong></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-white/60">Modalidade prevista</p><strong>🔴 Live + 🏫 Semipresencial</strong></div><div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-white/60">Valor ilustrativo</p><strong>A partir de R$ 99,90/mês*</strong></div></div>
  </section>

  <section className="grid gap-4 md:grid-cols-2"><article className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="font-serif text-2xl text-[#0b2341]">Para quem é</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{course.profile}</p></article><article className="rounded-3xl border bg-white p-6 shadow-sm"><h2 className="font-serif text-2xl text-[#0b2341]">Possibilidades profissionais</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{course.opportunities}</p></article></section>

  <section className="rounded-[28px] border bg-white p-5 shadow-sm sm:p-7"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#a77b2e]">Grade curricular preliminar</p><h2 className="mt-2 font-serif text-3xl text-[#0b2341]">{course.semesters} semestres de formação prevista</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">A matriz abaixo é uma proposta inicial e poderá ser ajustada pela futura instituição de ensino superior responsável pela oferta.</p><div className="mt-6 grid gap-4 md:grid-cols-2">{course.curriculum.map((subjects,i)=><article key={i} className="rounded-2xl border border-[#d6ad63]/30 bg-[#fffaf0] p-5"><h3 className="font-bold text-[#0b2341]">{i+1}º semestre</h3><ul className="mt-3 space-y-2 text-sm text-[#4d5965]">{subjects.map(s=><li key={s}>• {s}</li>)}</ul></article>)}</div></section>

  <section className="rounded-[28px] bg-[#071426] p-6 text-white sm:p-8"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#d6ad63]">Como funcionará</p><h2 className="mt-2 font-serif text-3xl text-[#fff7e7]">Live Semipresencial</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["💻","Conteúdo digital","Materiais acadêmicos e atividades previstos para a plataforma."],["🔴","Aulas Live","Encontros acadêmicos ao vivo conforme a futura organização acadêmica."],["🏫","Experiências presenciais","Atividades presenciais poderão integrar o curso conforme o projeto pedagógico."],["📚","Biblioteca digital","Materiais acadêmicos e conteúdos complementares previstos."],["📝","Atividades e avaliações","Avaliações e atividades conforme o futuro projeto pedagógico."],["🤝","Experiências práticas","Projetos, estudos de caso e práticas quando aplicáveis."]].map(([icon,title,text])=><article key={title} className="rounded-2xl bg-white/10 p-4"><div className="text-2xl">{icon}</div><h3 className="mt-2 font-bold">{title}</h3><p className="mt-1 text-xs leading-5 text-white/70">{text}</p></article>)}</div></section>

  <section className="rounded-[28px] border border-amber-300 bg-amber-50 p-6"><div className="flex items-center gap-2 font-black text-amber-900"><Sparkles className="h-5 w-5"/>CURSO EM DESENVOLVIMENTO — EM BREVE</div><p className="mt-3 text-sm leading-7 text-amber-950/80">Esta página apresenta uma proposta acadêmica preliminar. A eventual oferta como curso de graduação dependerá de parceria com instituição de ensino superior devidamente credenciada, das aprovações acadêmicas necessárias e do atendimento às exigências regulatórias aplicáveis. Grade curricular, duração, modalidade, atividades presenciais, valores e demais características poderão sofrer alterações antes da abertura oficial de matrículas.</p><p className="mt-3 text-xs font-semibold text-amber-900">Modalidade e duração previstas, sujeitas à regulamentação e ao projeto pedagógico definitivo da futura instituição ofertante.</p><p className="mt-2 text-xs text-amber-900">*R$ 99,90/mês é valor meramente ilustrativo de lançamento; mensalidades, bolsas e condições serão definidas antes de eventual abertura de matrículas.</p></section>

  <section className="rounded-[28px] border bg-white p-6 shadow-sm sm:p-8"><h2 className="font-serif text-3xl text-[#0b2341]">Quero ser avisado no lançamento</h2><p className="mt-2 text-sm text-muted-foreground">Cadastre seu interesse. Isso não é matrícula e não gera cobrança.</p>{submit.isSuccess?<div className="mt-5 rounded-2xl bg-emerald-50 p-5 font-bold text-emerald-800">Interesse registrado. Avisaremos você quando houver novidades sobre esta futura graduação.</div>:<div className="mt-5 grid gap-3 sm:grid-cols-2"><input className="rounded-xl border px-4 py-3" placeholder="Nome completo" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/><input className="rounded-xl border px-4 py-3" type="email" placeholder="E-mail" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input className="rounded-xl border px-4 py-3" placeholder="WhatsApp" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><input className="rounded-xl border px-4 py-3" placeholder="País" value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/><label className="sm:col-span-2 flex items-start gap-2 text-xs leading-5 text-muted-foreground"><input type="checkbox" required className="mt-1"/> Autorizo o contato da LDR sobre novidades deste futuro curso.</label><button disabled={submit.isPending} onClick={()=>submit.mutate()} className="sm:col-span-2 rounded-xl bg-[#0b2341] px-5 py-3 font-black text-white disabled:opacity-60">{submit.isPending?"Enviando…":"QUERO SER AVISADO NO LANÇAMENTO"}</button>{submit.isError?<p className="sm:col-span-2 text-sm text-red-600">Não foi possível registrar agora. Verifique os dados e tente novamente.</p>:null}</div>}</section>
  <Link to="/cliente/biblioteca" className="inline-flex font-bold text-[#0b2341]">← Voltar à Biblioteca LDR</Link>
 </div>;
}
