import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useMutation } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { BookOpen, MapPin, Send } from "lucide-react";
import { useState } from "react";
import { academicCreateArticle } from "@/lib/academic-articles-v2.functions";

export const Route=createFileRoute("/_clientarea/cliente/rede-academica/criar-artigo")({component:CreateAcademicArticle});
function CreateAcademicArticle(){
  const navigate=useNavigate();const createFn=useServerFn(academicCreateArticle);const [title,setTitle]=useState("");const [summary,setSummary]=useState("");const [body,setBody]=useState("");const [category,setCategory]=useState("");const [keywords,setKeywords]=useState("");const [references,setReferences]=useState("");const [locationLabel,setLocationLabel]=useState("");
  const create=useMutation({mutationFn:()=>createFn({data:{title,summary,body,category,keywords:keywords.split(",").map(x=>x.trim()).filter(Boolean),references,locationLabel}}),onSuccess:(x)=>navigate({to:"/cliente/rede-academica/artigo/$slug",params:{slug:x.slug}})});
  return <div className="mx-auto max-w-4xl space-y-5 px-3 pb-24 pt-4 sm:px-6 sm:pt-6"><Link to="/cliente/rede-academica" className="text-xs font-black text-[#07315a] dark:text-[#efc56d]">← REDE ACADÊMICA</Link><section className="rounded-[30px] border bg-card p-5 shadow-sm sm:p-8"><div className="flex items-center gap-3"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#edf4fb] text-[#07315a]"><BookOpen className="h-6 w-6"/></span><div><p className="text-[10px] font-black tracking-[.16em] text-[#9a772c]">ARTIGO ACADÊMICO</p><h1 className="font-serif text-3xl">Escrever artigo</h1></div></div><p className="mt-3 text-sm leading-6 text-muted-foreground">Estruture seu texto com títulos, subtítulos, listas, citações e referências usando linhas e parágrafos claros. O conteúdo é armazenado de forma segura sem scripts ou HTML executável.</p><div className="mt-6 grid gap-4"><Field label="Título" value={title} setValue={setTitle} maxLength={180}/><Field label="Resumo" value={summary} setValue={setSummary} maxLength={800}/><div className="grid gap-4 sm:grid-cols-2"><Field label="Categoria" value={category} setValue={setCategory} maxLength={100}/><Field label="Palavras-chave, separadas por vírgula" value={keywords} setValue={setKeywords} maxLength={600}/></div><label className="text-xs font-black">Texto completo<textarea value={body} onChange={e=>setBody(e.target.value)} rows={18} maxLength={100000} className="mt-2 w-full rounded-2xl border bg-background p-4 text-sm leading-7 outline-none focus:border-[#c8a657]" placeholder="Introdução\n\nSubtítulo\n\nDesenvolva seu argumento…"/></label><label className="text-xs font-black">Referências<textarea value={references} onChange={e=>setReferences(e.target.value)} rows={6} maxLength={12000} className="mt-2 w-full rounded-2xl border bg-background p-4 text-sm leading-6"/></label><label className="text-xs font-black">Localização opcional<div className="relative mt-2"><MapPin className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground"/><input value={locationLabel} onChange={e=>setLocationLabel(e.target.value)} maxLength={160} placeholder="Bruxelas, Bélgica" className="min-h-11 w-full rounded-xl border bg-background pl-10 pr-3 text-sm"/></div></label></div>{create.error&&<p className="mt-4 rounded-xl border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{String((create.error as Error).message||"Não foi possível publicar.")}</p>}<button disabled={create.isPending||title.trim().length<3||!body.trim()} onClick={()=>create.mutate()} className="mt-6 flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-[#07315a] px-5 text-sm font-black text-white disabled:opacity-40"><Send className="h-4 w-4"/>{create.isPending?"PUBLICANDO…":"PUBLICAR ARTIGO"}</button></section></div>
}
function Field({label,value,setValue,maxLength}:{label:string;value:string;setValue:(v:string)=>void;maxLength:number}){return <label className="text-xs font-black">{label}<input value={value} onChange={e=>setValue(e.target.value)} maxLength={maxLength} className="mt-2 min-h-11 w-full rounded-xl border bg-background px-3 text-sm"/></label>}
