import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { BookOpen, Globe2, MapPin, ShieldCheck } from "lucide-react";
import { useI18n } from "@/lib/i18n";
import { academicEditorialArticle } from "@/lib/academic-editorial-v3-detail.functions";

export const Route=createFileRoute("/_clientarea/cliente/rede-academica/artigo-editorial/$slug")({component:EditorialArticlePage});
const COPY={pt:{back:"← REDE ACADÊMICA",badge:"Conteúdo editorial LDR",original:"Idioma original",notice:"Este artigo é conteúdo editorial identificado da LDR, criado para estimular estudo e debate. Não representa produção espontânea de um usuário real da plataforma.",author:"Perfil editorial"},en:{back:"← ACADEMIC NETWORK",badge:"LDR editorial content",original:"Original language",notice:"This article is identified LDR editorial content created to encourage study and discussion. It does not represent spontaneous content from a real platform user.",author:"Editorial profile"},fr:{back:"← RÉSEAU ACADÉMIQUE",badge:"Contenu éditorial LDR",original:"Langue originale",notice:"Cet article est un contenu éditorial LDR clairement identifié, créé pour encourager l’étude et le débat. Il ne représente pas la publication spontanée d’un utilisateur réel.",author:"Profil éditorial"},es:{back:"← RED ACADÉMICA",badge:"Contenido editorial LDR",original:"Idioma original",notice:"Este artículo es contenido editorial LDR identificado, creado para fomentar el estudio y el debate. No representa contenido espontáneo de un usuario real de la plataforma.",author:"Perfil editorial"}} as const;
function EditorialArticlePage(){const {slug}=Route.useParams();const {locale:raw}=useI18n();const locale=(raw==="en"||raw==="fr"||raw==="es"?raw:"pt") as keyof typeof COPY,t=COPY[locale];const get=useServerFn(academicEditorialArticle);const {data,isLoading,error}=useQuery({queryKey:["academic-editorial-article",slug],queryFn:()=>get({data:{slug}})});if(isLoading)return <div className="mx-auto max-w-3xl p-6 text-sm text-muted-foreground">…</div>;if(error||!data)return <div className="mx-auto max-w-3xl p-6">Artigo editorial indisponível.</div>;const p=data.profile;return <div className="mx-auto max-w-3xl space-y-5 px-3 pb-28 pt-4 sm:px-6 sm:pt-6"><Link to="/cliente/rede-academica" className="text-xs font-black text-[#07315a] dark:text-[#efc56d]">{t.back}</Link><article className="rounded-[28px] border bg-card p-5 shadow-sm sm:p-8"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#f8efd8] px-3 py-1 text-[9px] font-black text-[#745717]"><ShieldCheck className="mr-1 inline h-3.5 w-3.5"/>{t.badge}</span><span className="text-[10px] text-muted-foreground"><Globe2 className="mr-1 inline h-3.5 w-3.5"/>{t.original}: {String(data.language).toUpperCase()}</span></div><h1 className="mt-5 font-serif text-3xl leading-tight sm:text-4xl">{data.title}</h1><p className="mt-3 text-base leading-7 text-muted-foreground">{data.summary}</p><div className="mt-5 flex flex-wrap items-center gap-3 border-y py-4"><Link to="/cliente/rede-academica/perfil-editorial/$username" params={{username:p.username}} className="grid h-11 w-11 place-items-center rounded-full bg-[#07315a] text-xs font-black text-white">{String(p.display_name).split(" ").map((x:string)=>x[0]).join("").slice(0,2)}</Link><div><Link to="/cliente/rede-academica/perfil-editorial/$username" params={{username:p.username}} className="text-sm font-black hover:underline">{p.display_name}</Link><p className="mt-1 text-[10px] text-muted-foreground">{t.author} · {p.profession} · <MapPin className="mr-0.5 inline h-3 w-3"/>{p.city}, {p.country}</p></div></div><div className="mt-6 whitespace-pre-wrap text-[15px] leading-8">{data.body}</div>{data.keywords?.length>0&&<div className="mt-6 flex flex-wrap gap-2">{data.keywords.map((x:string)=><Link key={x} to="/cliente/rede-academica/buscar" search={{q:x} as any} className="rounded-full border px-3 py-1 text-[10px] font-bold">#{x.replace(/\s+/g,"")}</Link>)}</div>}<div className="mt-7 rounded-2xl border border-[#d8b65b]/40 bg-[#fffaf0] p-4 text-[11px] leading-5 text-[#604816] dark:bg-[#2a2416] dark:text-[#f0d58c]"><BookOpen className="mr-1 inline h-4 w-4"/>{t.notice}</div></article></div>}
