import { Link, createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { BookOpen, CheckCircle2, ShieldCheck } from "lucide-react";
import { clientCreateEditorialCheckout, clientEditorialSubscription, clientSetEditorialCancellation } from "@/lib/editorial-subscription.functions";
import { findEditorialBySlug } from "@/lib/editorial-catalog";
import { localizeEditorial } from "@/lib/editorial-i18n";
import { useI18n } from "@/lib/i18n";

export const Route=createFileRoute("/_clientarea/cliente/biblioteca/publicacoes/$slug")({component:PublicationPage});

type Locale="pt"|"en"|"fr"|"es";
const COPY={
  pt:{publications:"← Publicações",notFound:"Publicação não encontrada.",loading:"Carregando publicação…",all:"← Todas as publicações",library:"Minha Biblioteca",weekly:"Assinatura semanal",brand:"Grupo LDR Essence",billing:"Cobrança recorrente semanal",week:"semana",europe:"Europa",brazil:"Brasil",opening:"ABRINDO CHECKOUT…",subscribe:"ASSINAR AGORA",separate:"Assinatura independente da Biblioteca LDR. Você pode cancelar para o fim do período semanal.",active:"ASSINATURA ATIVA",keep:"MANTER ASSINATURA",cancel:"CANCELAR AO FIM DO PERÍODO",edition:"EDIÇÃO #01 · SETEMBRO 2026",inEdition:"Nesta edição",editionTitle:"Uma leitura semanal para entender, aprender e acompanhar mudanças.",block:"Bloco",blockText:"Conteúdo editorial preparado para contextualizar o tema, destacar pontos principais e indicar fontes quando a pauta exigir verificação oficial ou científica.",next:"Próxima edição",nextText:"Novas edições são publicadas semanalmente e permanecem no histórico da publicação para assinantes enquanto a assinatura estiver ativa."},
  en:{publications:"← Publications",notFound:"Publication not found.",loading:"Loading publication…",all:"← All publications",library:"My Library",weekly:"Weekly subscription",brand:"Grupo LDR Essence",billing:"Recurring weekly billing",week:"week",europe:"Europe",brazil:"Brazil",opening:"OPENING CHECKOUT…",subscribe:"SUBSCRIBE NOW",separate:"Independent from the LDR Library subscription. You can cancel at the end of the weekly period.",active:"ACTIVE SUBSCRIPTION",keep:"KEEP SUBSCRIPTION",cancel:"CANCEL AT PERIOD END",edition:"EDITION #01 · SEPTEMBER 2026",inEdition:"In this edition",editionTitle:"A weekly read to understand, learn and follow changes.",block:"Section",blockText:"Editorial content prepared to provide context, highlight key points and indicate sources when a topic requires official or scientific verification.",next:"Next edition",nextText:"New editions are published weekly and remain in the publication history for subscribers while the subscription is active."},
  fr:{publications:"← Publications",notFound:"Publication introuvable.",loading:"Chargement de la publication…",all:"← Toutes les publications",library:"Ma Bibliothèque",weekly:"Abonnement hebdomadaire",brand:"Grupo LDR Essence",billing:"Facturation récurrente hebdomadaire",week:"semaine",europe:"Europe",brazil:"Brésil",opening:"OUVERTURE DU PAIEMENT…",subscribe:"S'ABONNER",separate:"Abonnement indépendant de la Bibliothèque LDR. Vous pouvez annuler à la fin de la période hebdomadaire.",active:"ABONNEMENT ACTIF",keep:"MAINTENIR L'ABONNEMENT",cancel:"ANNULER À LA FIN DE LA PÉRIODE",edition:"ÉDITION #01 · SEPTEMBRE 2026",inEdition:"Dans cette édition",editionTitle:"Une lecture hebdomadaire pour comprendre, apprendre et suivre les changements.",block:"Rubrique",blockText:"Contenu éditorial préparé pour contextualiser le thème, mettre en avant les points principaux et indiquer les sources lorsqu'une vérification officielle ou scientifique est nécessaire.",next:"Prochaine édition",nextText:"De nouvelles éditions sont publiées chaque semaine et restent dans l'historique pour les abonnés tant que l'abonnement est actif."},
  es:{publications:"← Publicaciones",notFound:"Publicación no encontrada.",loading:"Cargando publicación…",all:"← Todas las publicaciones",library:"Mi Biblioteca",weekly:"Suscripción semanal",brand:"Grupo LDR Essence",billing:"Cobro recurrente semanal",week:"semana",europe:"Europa",brazil:"Brasil",opening:"ABRIENDO PAGO…",subscribe:"SUSCRIBIRME AHORA",separate:"Suscripción independiente de la Biblioteca LDR. Puedes cancelar al final del período semanal.",active:"SUSCRIPCIÓN ACTIVA",keep:"MANTENER SUSCRIPCIÓN",cancel:"CANCELAR AL FINAL DEL PERÍODO",edition:"EDICIÓN #01 · SEPTIEMBRE 2026",inEdition:"En esta edición",editionTitle:"Una lectura semanal para entender, aprender y seguir los cambios.",block:"Bloque",blockText:"Contenido editorial preparado para contextualizar el tema, destacar los puntos principales e indicar fuentes cuando el asunto requiera verificación oficial o científica.",next:"Próxima edición",nextText:"Las nuevas ediciones se publican semanalmente y permanecen en el historial para suscriptores mientras la suscripción esté activa."},
} as const;

function money(c:number,cur:"BRL"|"EUR",locale:Locale){return new Intl.NumberFormat(locale==="pt"?(cur==="BRL"?"pt-BR":"pt-PT"):locale==="fr"?"fr-FR":locale==="es"?"es-ES":"en-US",{style:"currency",currency:cur}).format(c/100)}

function PublicationPage(){
  const {locale:raw}=useI18n();
  const locale=(raw==="pt"||raw==="en"||raw==="fr"||raw==="es"?raw:"pt") as Locale;
  const t=COPY[locale];
  const {slug}=Route.useParams();
  const baseItem=findEditorialBySlug(slug);
  const item=baseItem?localizeEditorial(baseItem,locale):null;
  const ctxFn=useServerFn(clientEditorialSubscription),checkoutFn=useServerFn(clientCreateEditorialCheckout),cancelFn=useServerFn(clientSetEditorialCancellation);
  const {data,refetch,isLoading}=useQuery({queryKey:["editorial",item?.productKey],enabled:!!item,queryFn:()=>ctxFn({data:{productKey:item!.productKey}})});
  const checkout=useMutation({mutationFn:()=>checkoutFn({data:{productKey:item!.productKey,market:data?.market==="BR"?"BR":"INTL"}}),onSuccess:r=>location.href=r.url});
  const cancel=useMutation({mutationFn:(v:boolean)=>cancelFn({data:{productKey:item!.productKey,cancelAtPeriodEnd:v}}),onSuccess:()=>refetch()});
  if(!item)return <div className="space-y-4"><Link to="/cliente/biblioteca/publicacoes" className="font-black text-[#0b2341]">{t.publications}</Link><p>{t.notFound}</p></div>;
  if(isLoading||!data)return <p>{t.loading}</p>;
  const price=data.market==="BR"?money(data.priceBrlCents,"BRL",locale):money(data.priceEurCents,"EUR",locale);

  if(!data.active)return <div className="space-y-5 pb-10"><div className="flex flex-wrap gap-4"><Link to="/cliente/biblioteca/publicacoes" className="text-sm font-black text-[#0b2341]">{t.all}</Link><Link to="/cliente/biblioteca" className="text-sm font-bold text-slate-500">{t.library}</Link></div><section className="overflow-hidden rounded-[30px] p-7 text-white shadow-xl sm:p-10" style={{background:`linear-gradient(135deg,${item.color},#071426)`}}><div className="flex items-start justify-between gap-4"><span className="text-5xl">{item.icon}</span><span className="rounded-full bg-white/15 px-3 py-1 text-[10px] font-black uppercase tracking-wider">{t.weekly}</span></div><p className="mt-8 text-[10px] font-black uppercase tracking-[.25em] text-[#f0c775]">{t.brand}</p><h1 className="mt-3 max-w-4xl font-serif text-4xl leading-tight !text-white sm:text-6xl">{item.title}</h1><p className="mt-4 max-w-3xl text-base leading-7 !text-white/80">{item.description}</p><div className="mt-6 flex flex-wrap gap-2">{item.topics.map(topic=><span key={topic} className="rounded-full bg-white/10 px-3 py-2 text-[10px] font-bold">{topic}</span>)}</div><div className="mt-8 rounded-2xl bg-white/10 p-5"><p className="text-xs font-bold uppercase tracking-wider text-white/60">{t.billing}</p><p className="mt-2 text-4xl font-black">{price}<span className="text-sm font-medium text-white/60"> / {t.week}</span></p><p className="mt-2 text-xs text-white/60">{t.europe} {money(item.priceEurCents,"EUR",locale)} · {t.brazil} {money(item.priceBrlCents,"BRL",locale)}</p></div>{item.notice&&<div className="mt-5 flex gap-3 rounded-2xl bg-white/10 p-4 text-sm leading-6 text-white/75"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#f0c775]"/><p>{item.notice}</p></div>}<button disabled={checkout.isPending} onClick={()=>checkout.mutate()} className="mt-7 rounded-xl bg-[#f0c775] px-6 py-3 font-black text-[#35101e] disabled:opacity-60">{checkout.isPending?t.opening:t.subscribe}</button><p className="mt-3 text-xs text-white/55">{t.separate}</p></section></div>;

  return <div className="space-y-6 pb-10"><div className="flex flex-wrap items-center justify-between gap-3"><Link to="/cliente/biblioteca/publicacoes" className="text-sm font-black text-[#0b2341]">{t.all}</Link><div className="flex flex-wrap gap-2"><span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black text-emerald-700"><CheckCircle2 className="mr-1 inline h-3 w-3"/>{t.active}</span><button onClick={()=>cancel.mutate(!data.subscription?.cancel_at_period_end)} className="rounded-full border px-3 py-1 text-[10px] font-black">{data.subscription?.cancel_at_period_end?t.keep:t.cancel}</button></div></div><article className="overflow-hidden rounded-[30px] border bg-white shadow-xl"><section className="p-8 text-white sm:p-12" style={{background:`linear-gradient(135deg,${item.color},#071426)`}}><p className="text-xs font-black uppercase tracking-[.25em] text-[#f0c775]">{t.edition}</p><div className="mt-5 flex items-center gap-4"><span className="text-5xl">{item.icon}</span><h1 className="font-serif text-4xl !text-white sm:text-6xl">{item.title}</h1></div><p className="mt-5 max-w-3xl text-lg leading-8 !text-white/80">{item.subtitle}</p></section><section className="p-7 sm:p-10"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#a77b2e]">{t.inEdition}</p><h2 className="mt-2 font-serif text-3xl text-[#0b2341]">{t.editionTitle}</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{item.topics.map((topic,i)=><div key={topic} className="rounded-2xl border bg-slate-50 p-5"><p className="text-[10px] font-black uppercase tracking-wider text-[#a77b2e]">{t.block} {i+1}</p><h3 className="mt-2 font-serif text-2xl text-[#0b2341]">{topic}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{t.blockText}</p></div>)}</div>{item.notice&&<div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900">{item.notice}</div>}</section><section className="bg-[#f7f3e9] p-7 sm:p-10"><BookOpen className="h-6 w-6 text-[#a77b2e]"/><h2 className="mt-3 font-serif text-3xl text-[#0b2341]">{t.next}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t.nextText}</p></section></article></div>;
}
