import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useMutation, useQuery } from "@tanstack/react-query";
import { aiReadyAccess, aiReadyCheckout } from "@/lib/ai-ready.functions";\nimport { clientSaveProgress } from "@/lib/learning.functions";\nimport { useEffect, useState } from "react";
import { CheckCircle2, ShieldCheck } from "lucide-react";\nimport { AiNarrator } from "@/components/ai-ready/ai-narrator";

export const Route=createFileRoute("/_clientarea/cliente/ai-ready")({component:AiReadyClient});

const lessons=[
 {title:"1. IA generativa sem mitos",body:"IA generativa prevê e produz conteúdo a partir de padrões. Ela pode acelerar rascunhos, sínteses, pesquisa inicial e organização, mas não “sabe” se uma resposta é verdadeira. Na empresa, trate cada saída como material a validar.",example:"Exemplo: usar IA para rascunhar uma resposta comercial é aceitável; enviar preços, prazos ou condições sem conferência humana cria risco desnecessário.",action:"Ação: liste 3 tarefas repetitivas em que IA pode apoiar sem tomar a decisão final."},
 {title:"2. Mapa de usos permitidos e proibidos",body:"Cada equipe deve saber onde a IA pode ser usada, onde exige aprovação e onde não deve ser usada. Separe usos de baixo risco — ideias, revisão de tom, estrutura — de usos que afetam clientes, candidatos, colaboradores ou decisões relevantes.",example:"Exemplo: criar perguntas para uma entrevista é diferente de pedir à IA que decida automaticamente qual candidato contratar.",action:"Ação: classifique os usos atuais da sua empresa em Permitido, Revisão obrigatória ou Não permitido."},
 {title:"3. Dados, privacidade e confidencialidade",body:"Antes de inserir informação em uma ferramenta, verifique se há dados pessoais, dados sensíveis, contratos, credenciais, informação financeira, estratégia ou segredo comercial. Use apenas o mínimo necessário e siga as regras internas e do fornecedor.",example:"Exemplo: em vez de colar o prontuário, currículo completo ou contrato de um cliente, remova identificadores e trabalhe apenas com os elementos indispensáveis quando isso for apropriado.",action:"Ação: identifique quais categorias de dados da empresa nunca devem ser copiadas para uma IA pública sem autorização e controles adequados."},
 {title:"4. Alucinações, fontes e propriedade intelectual",body:"Modelos podem inventar números, leis, referências, citações e funcionalidades. Conteúdo plausível não é sinônimo de conteúdo correto. Também é preciso avaliar direitos de terceiros antes de publicar textos, imagens, código ou materiais gerados.",example:"Exemplo: se a IA citar uma norma, artigo ou estatística, abra a fonte original e confirme o trecho, a data e o contexto antes de usar.",action:"Ação: aplique a regra 2F — Fato e Fonte — a toda informação externa relevante gerada por IA."},
 {title:"5. Revisão humana e responsabilidade",body:"Defina quem responde pelo resultado. Quanto maior o impacto sobre uma pessoa ou sobre o negócio, maior deve ser a revisão humana. A ferramenta apoia; o responsável humano verifica contexto, precisão, consequências e autorização.",example:"Exemplo: comunicação interna simples pode ter revisão leve; decisão de RH, crédito, saúde, segurança ou avaliação de pessoas exige controles muito mais fortes e análise das regras aplicáveis.",action:"Ação: nomeie um responsável humano para cada uso de IA que possa afetar clientes, trabalhadores ou decisões importantes."},
 {title:"6. Prompt profissional e registro mínimo",body:"Um bom pedido informa objetivo, contexto permitido, formato esperado, limites e necessidade de citar incertezas. Para usos recorrentes, documente ferramenta, finalidade, responsável e tipo de dado utilizado.",example:"Exemplo de instrução: “Resuma este texto em 5 pontos. Não invente fatos. Marque qualquer informação que precise de confirmação humana.”",action:"Ação: crie um prompt-padrão para uma tarefa frequente e registre qual ferramenta a equipe utiliza para executá-la."},
 {title:"7. Incidentes e checklist antes de publicar",body:"Se alguém inserir dados indevidos, receber conteúdo perigoso ou identificar uma decisão inadequada baseada em IA, interrompa o uso, preserve as informações necessárias para apuração e comunique o responsável interno. Antes de publicar, faça a checagem final.",example:"Checklist: tenho autorização para usar estes dados? confirmei fatos e fontes? revisei vieses/impacto sobre pessoas? há informação confidencial? um humano responsável aprovou a saída?",action:"Conclusão: se qualquer resposta crítica for “não sei”, não publique nem execute a decisão até obter revisão adequada."},
];

const references=[
 ["Stanford AI Index 2026","Panorama global de pesquisa, desempenho técnico, IA responsável, economia, ciência, medicina, educação e governança.","https://hai.stanford.edu/ai-index/2026-ai-index-report"],
 ["NIST — Generative AI Profile","Framework técnico para identificar e gerenciar riscos específicos de IA generativa.","https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence"],
 ["Comissão Europeia — AI Literacy","Orientações e práticas de alfabetização em IA para organizações e trabalhadores.","https://digital-strategy.ec.europa.eu/en/policies/ai-talent-skills-and-literacy"],
 ["UNESCO — Ética da Inteligência Artificial","Referência global sobre direitos humanos, transparência, supervisão humana, educação e ética.","https://www.unesco.org/en/artificial-intelligence/recommendation-ethics"],
 ["Nature — Artificial Intelligence","Pesquisa e debates científicos recentes sobre IA, aplicações, riscos e impactos.","https://www.nature.com/subjects/artificial-intelligence"],
 ["OMS — IA responsável em saúde","Casos de governança, ética, equidade, supervisão e riscos em um setor de alto impacto.","https://www.who.int/teams/health-ethics-governance/emerging-technologies/big-data-and-artificial-intelligence"],
];

const worldAudio="Panorama IA no mundo. A inteligência artificial deixou de ser apenas uma ferramenta experimental e passou a influenciar trabalho, ciência, educação, saúde e decisões empresariais. O Stanford AI Index acompanha essa evolução em pesquisa, desempenho, economia, educação e governança. Instituições como NIST, UNESCO, Comissão Europeia e Organização Mundial da Saúde convergem em um ponto importante: capacidade técnica precisa caminhar junto com pensamento crítico, supervisão humana, transparência, proteção de dados e responsabilidade. Ao acompanhar as notícias sobre inteligência artificial, não observe apenas qual modelo ficou mais poderoso. Pergunte também: quem responde pelo resultado, quais dados foram usados, como o sistema foi avaliado, quem pode ser afetado e quais controles existem. Essa é a diferença entre simplesmente usar inteligência artificial e desenvolver maturidade em inteligência artificial.";

const kit=[
 ["Política Interna de Uso de IA","Defina ferramentas autorizadas, usos permitidos, usos restritos, dados proibidos, revisão humana e fluxo de incidentes."],
 ["Inventário de IA","Registre ferramenta, fornecedor, finalidade, equipe, responsável, dados utilizados e criticidade do uso."],
 ["Checklist do colaborador","Perguntas objetivas antes de inserir dados, confiar em uma resposta ou publicar conteúdo produzido com IA."],
 ["Guia para RH e liderança","Oriente onboarding, comunicação interna, responsabilidades, treinamento e revisão periódica das práticas."],
 ["Registro de capacitação","Mantenha nome, função, data, conteúdo realizado e confirmação de conclusão de cada participante."],
];

function AiReadyClient(){
 const accessFn=useServerFn(aiReadyAccess),checkoutFn=useServerFn(aiReadyCheckout),saveProgressFn=useServerFn(clientSaveProgress);\n const [completed,setCompleted]=useState<number[]>([]);\n useEffect(()=>{try{setCompleted(JSON.parse(localStorage.getItem("ai-ready-2026-completed")||"[]"))}catch{}},[]);\n const markLesson=async(index:number)=>{const next=Array.from(new Set([...completed,index])).sort();setCompleted(next);localStorage.setItem("ai-ready-2026-completed",JSON.stringify(next));await saveProgressFn({data:{productKey:"ai_ready_2026",progressPercent:Math.round((next.length/7)*80),currentLocation:`module-${index+1}`}})};
 const q=useQuery({queryKey:["ai-ready-access"],queryFn:()=>accessFn({})});
 const checkout=useMutation({mutationFn:(market:"BR"|"INTL")=>checkoutFn({data:{market}}),onSuccess:r=>{location.href=r.url}});
 if(q.isLoading)return <div className="p-8">Carregando AI READY 2026…</div>;
 if(!q.data?.entitled)return <div className="mx-auto max-w-3xl space-y-6 py-8"><section className="rounded-[28px] bg-[#071426] p-7 text-white"><p className="text-xs font-black uppercase tracking-[.2em] text-[#d6ad63]">AI READY 2026</p><h1 className="mt-3 font-serif text-4xl font-bold">Prepare sua empresa para o uso responsável de IA.</h1><p className="mt-4 text-sm leading-6 text-white/75">Treinamento + kit empresarial + certificados de conclusão para até 10 colaboradores.</p></section><section className="rounded-2xl border bg-white p-6"><h2 className="font-serif text-2xl font-bold text-[#0b2341]">Oferta de lançamento</h2><div className="mt-5 grid gap-3 sm:grid-cols-2"><button disabled={checkout.isPending} onClick={()=>checkout.mutate("INTL")} className="min-h-12 rounded-xl bg-[#0b2341] px-5 font-black text-white">Comprar por €49</button><button disabled={checkout.isPending} onClick={()=>checkout.mutate("BR")} className="min-h-12 rounded-xl border border-[#0b2341] px-5 font-black text-[#0b2341]">Comprar por R$297</button></div>{checkout.error&&<p className="mt-3 text-sm text-red-700">{String(checkout.error.message)}</p>}<p className="mt-4 text-xs leading-5 text-slate-500">Pagamento único. Programa educacional; não constitui certificação governamental, parecer jurídico ou garantia de conformidade.</p></section></div>;
 return <div className="mx-auto max-w-4xl space-y-6 py-8"><section className="rounded-[28px] bg-[#071426] p-7 text-white"><div className="flex items-center gap-3"><CheckCircle2 className="h-7 w-7 text-[#d6ad63]"/><p className="text-xs font-black uppercase tracking-[.2em] text-[#d6ad63]">Acesso liberado</p></div><h1 className="mt-4 font-serif text-4xl font-bold">AI READY 2026</h1><p className="mt-3 text-sm text-white/75">Treinamento empresarial prático de alfabetização e uso responsável de Inteligência Artificial.</p><div className="mt-5"><div className="flex justify-between text-xs font-bold"><span>Progresso dos módulos</span><span>{completed.length}/7</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full bg-[#d6ad63] transition-all" style={{width:`${(completed.length/7)*100}%`}}/></div><p className="mt-2 text-xs text-white/60">Sem prazo ou tempo mínimo: avance no seu ritmo.</p></div></section><section className="rounded-2xl border bg-white p-6"><h2 className="font-serif text-2xl font-bold text-[#0b2341]">Treinamento aplicado</h2><p className="mt-2 text-sm text-slate-600">Leia os 7 módulos e execute a ação proposta em cada etapa usando a realidade da sua empresa.</p><div className="mt-5 space-y-4">{lessons.map(x=><article key={x.title} className="rounded-xl border bg-slate-50 p-5"><h3 className="font-black text-[#0b2341]">{x.title}</h3><p className="mt-3 text-sm leading-6 text-slate-700">{x.body}</p><p className="mt-3 rounded-lg bg-white p-3 text-sm leading-6 text-slate-600"><b>Na prática:</b> {x.example}</p><p className="mt-3 text-sm font-semibold leading-6 text-[#0b2341]">{x.action}</p><AiNarrator label="Ouvir este módulo" text={`${x.title}. ${x.body} Na prática: ${x.example} ${x.action}`} /><button type="button" onClick={()=>markLesson(lessons.indexOf(x))} disabled={completed.includes(lessons.indexOf(x))} className="mt-3 min-h-10 rounded-lg border border-[#0b2341] px-4 text-sm font-black text-[#0b2341] disabled:border-emerald-300 disabled:bg-emerald-50 disabled:text-emerald-700">{completed.includes(lessons.indexOf(x))?"✓ Módulo concluído":"Marcar módulo como concluído"}</button></article>)}</div></section><section className="grid gap-4 md:grid-cols-2">
 <article className="rounded-2xl border border-emerald-200 bg-emerald-50 p-5"><p className="text-xs font-black uppercase tracking-[.16em] text-emerald-700">Laboratório de Prompt</p><h3 className="mt-2 font-serif text-xl font-bold text-[#0b2341]">Do pedido vago ao briefing profissional</h3><p className="mt-2 text-sm leading-6 text-slate-700">Transforme uma tarefa real usando: objetivo, contexto permitido, dados, restrições, formato, critérios de qualidade e revisão humana.</p></article>
 <article className="rounded-2xl border border-rose-200 bg-rose-50 p-5"><p className="text-xs font-black uppercase tracking-[.16em] text-rose-700">Detecte o erro da IA</p><h3 className="mt-2 font-serif text-xl font-bold text-[#0b2341]">Não confunda confiança com verdade</h3><p className="mt-2 text-sm leading-6 text-slate-700">Analise uma resposta plausível, procure fatos não verificados, fontes frágeis, omissões, vieses e conclusões que exigem validação.</p></article>
 <article className="rounded-2xl border border-amber-200 bg-amber-50 p-5"><p className="text-xs font-black uppercase tracking-[.16em] text-amber-700">Dilema ético</p><h3 className="mt-2 font-serif text-xl font-bold text-[#0b2341]">Quando eficiência não basta</h3><p className="mt-2 text-sm leading-6 text-slate-700">Avalie cenários de RH, atendimento, educação e serviços considerando impacto, equidade, transparência, privacidade e responsabilidade.</p></article>
 <article className="rounded-2xl border border-sky-200 bg-sky-50 p-5"><p className="text-xs font-black uppercase tracking-[.16em] text-sky-700">Caso empresarial</p><h3 className="mt-2 font-serif text-xl font-bold text-[#0b2341]">Decida como uma organização</h3><p className="mt-2 text-sm leading-6 text-slate-700">Receba um caso com objetivo, pessoas afetadas e riscos. Defina controles, responsável humano e critérios para aprovar, ajustar ou interromper o uso.</p></article>
 <article className="rounded-2xl border border-cyan-200 bg-cyan-50 p-5"><p className="text-xs font-black uppercase tracking-[.16em] text-cyan-700">Missão no trabalho</p><h3 className="mt-2 font-serif text-xl font-bold text-[#0b2341]">Leve a aula para uma tarefa real</h3><p className="mt-2 text-sm leading-6 text-slate-700">Escolha um processo do seu trabalho, identifique onde a IA ajuda, quais dados pode usar, quais riscos existem e onde a revisão humana é obrigatória.</p></article>
 <article className="rounded-2xl border border-indigo-200 bg-indigo-50 p-5"><p className="text-xs font-black uppercase tracking-[.16em] text-indigo-700">Projeto final AI READY</p><h3 className="mt-2 font-serif text-xl font-bold text-[#0b2341]">Mapa de uso responsável da empresa</h3><p className="mt-2 text-sm leading-6 text-slate-700">Ao final, consolide ferramentas utilizadas, finalidades, responsáveis, dados envolvidos, riscos, controles e próximos passos em um plano aplicável à organização.</p></article>
</section><section className="overflow-hidden rounded-2xl border border-violet-300 bg-gradient-to-br from-[#24124d] via-[#35206b] to-[#17112f] p-6 text-white shadow-lg">
 <p className="text-xs font-black uppercase tracking-[.2em] text-violet-200">Laboratório de decisão</p>
 <h2 className="mt-2 font-serif text-2xl font-bold">🤖 Conversa com a IA</h2>
 <p className="mt-3 text-sm leading-6 text-violet-50/90">Pare a aula e pense como se estivesse diante de uma decisão real. A IA apresenta perguntas, contrapontos e riscos para ajudar você a estruturar o raciocínio — sem substituir sua decisão.</p>
 <div className="mt-4 rounded-xl border border-white/15 bg-white/10 p-4">
  <p className="text-sm font-bold text-violet-100">Desafio de decisão</p>
  <p className="mt-2 text-sm leading-6">Sua equipe quer automatizar uma tarefa com IA. Antes de decidir, responda: qual é o objetivo? Que dados entram no sistema? Quem pode ser afetado? O que acontece se a resposta estiver errada? Quem será responsável pela revisão final?</p>
 </div>
 <p className="mt-4 text-xs leading-5 text-violet-200">Princípio do laboratório: a IA amplia a análise; a responsabilidade pela decisão continua humana.</p>
</section><section className="rounded-2xl border bg-[#eef5fb] p-6"><h2 className="font-serif text-2xl font-bold text-[#0b2341]">🌍 IA no mundo — áudio complementar</h2><p className="mt-2 text-sm leading-6 text-slate-600">Este áudio não repete a aula: conecta o treinamento a pesquisa, governança e acontecimentos globais.</p><AiNarrator label="Ouvir panorama mundial" text={worldAudio}/><div className="mt-6"><h3 className="font-black text-[#0b2341]">Biblioteca de pesquisa & atualidades</h3><div className="mt-3 grid gap-3">{references.map(([t,d,url])=><a key={t} href={url} target="_blank" rel="noreferrer" className="rounded-xl border bg-white p-4 transition hover:border-[#9a6c20]"><b className="text-[#0b2341]">{t}</b><p className="mt-1 text-sm leading-6 text-slate-600">{d}</p><span className="mt-2 inline-block text-xs font-black text-[#9a6c20]">ABRIR FONTE ↗</span></a>)}</div></div></section><section className="rounded-2xl border bg-[#fffaf0] p-6"><div className="flex items-center gap-3"><ShieldCheck className="h-6 w-6 text-[#9a6c20]"/><h2 className="font-serif text-2xl font-bold text-[#0b2341]">Kit de implementação empresarial</h2></div><p className="mt-3 text-sm leading-6 text-slate-600">Use estes cinco documentos como estrutura interna e adapte-os à realidade, às ferramentas e às obrigações aplicáveis à sua organização.</p><div className="mt-5 grid gap-3">{kit.map(([t,d])=><div key={t} className="rounded-xl border border-[#e3d7bd] bg-white p-4"><h3 className="font-black text-[#0b2341]">{t}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{d}</p></div>)}</div><p className="mt-5 text-xs leading-5 text-slate-500">Material educacional e organizacional. Não substitui avaliação jurídica, de proteção de dados, segurança da informação ou análise regulatória específica.</p></section></div>
}
