import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { BookOpen, Hash, Search, Users } from "lucide-react";
import { useState } from "react";
import { academicUnifiedSearch } from "@/lib/academic-search-v2.functions";

export const Route=createFileRoute("/_clientarea/cliente/rede-academica/buscar")({component:AcademicSearchPage});
function AcademicSearchPage(){const [term,setTerm]=useState("");const [submitted,setSubmitted]=useState("");const search=useServerFn(academicUnifiedSearch);const {data,isFetching}=useQuery({queryKey:["academic-search",submitted],queryFn:()=>search({data:{q:submitted}}),enabled:submitted.trim().length>=2});return <div className="mx-auto max-w-5xl space-y-5 px-3 pb-28 pt-4 sm:px-6 sm:pt-6"><Link to="/cliente/rede-academica" className="text-xs font-black text-[#07315a] dark:text-[#efc56d]">← REDE ACADÊMICA</Link><header><h1 className="font-serif text-3xl">Buscar na Rede Acadêmica</h1><p className="mt-1 text-sm text-muted-foreground">Publicações, artigos, perfis, comunidades e tópicos. Diário, e-mail e telefone nunca entram na busca.</p></header><form onSubmit={e=>{e.preventDefault();setSubmitted(term.trim())}} className="flex gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3.5 h-4 w-4 text-muted-foreground"/><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="Pesquisar…" className="min-h-11 w-full rounded-xl border bg-card pl-10 pr-3 text-sm"/></div><button className="min-h-11 rounded-xl bg-[#07315a] px-4 text-xs font-black text-white">BUSCAR</button></form>{isFetching&&<p className="text-sm text-muted-foreground">Buscando…</p>}{data&&<div className="space-y-6"><Section title="Publicações" icon={BookOpen}>{data.posts.map((p:any)=><Link key={p.id} to="/cliente/rede-academica/post/$id" params={{id:p.id}} className="block rounded-2xl border bg-card p-4"><span className="text-[10px] font-black text-[#9a772c]">{String(p.post_type).toUpperCase()}</span><p className="mt-2 line-clamp-3 text-sm leading-6">{p.body}</p></Link>)}</Section><Section title="Artigos" icon={BookOpen}>{data.articles.map((a:any)=><Link key={a.id} to="/cliente/rede-academica/artigo/$slug" params={{slug:a.slug}} className="block rounded-2xl border bg-card p-4"><b className="font-serif text-lg">{a.title}</b><p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{a.summary}</p></Link>)}</Section><Section title="Perfis" icon={Users}>{data.profiles.map((p:any)=><Link key={p.id} to="/cliente/rede-academica/perfil/$username" params={{username:p.username}} className="block rounded-2xl border bg-card p-4"><b>@{p.username}</b><p className="mt-1 text-xs text-muted-foreground">{p.profession||String(p.role).toUpperCase()}</p></Link>)}</Section><Section title="Comunidades" icon={Users}>{data.communities.map((c:any)=><div key={c.id} className="rounded-2xl border bg-card p-4"><b>{c.name}</b><p className="mt-1 text-xs text-muted-foreground">{c.description}</p></div>)}</Section><Section title="Tópicos" icon={Hash}>{data.topics.map((t:any)=><Link key={t.id} to="/cliente/rede-academica" search={{} as any} className="inline-flex min-h-11 items-center rounded-full border bg-card px-4 text-xs font-black">#{t.label}</Link>)}</Section></div>}</div>}
function Section({title,icon:Icon,children}:{title:string;icon:any;children:any}){const items=Array.isArray(children)?children.filter(Boolean):children;return <section><div className="mb-3 flex items-center gap-2"><Icon className="h-4 w-4 text-[#c99b38]"/><h2 className="font-serif text-xl">{title}</h2></div><div className="grid gap-3 md:grid-cols-2">{Array.isArray(items)&&items.length?items:<p className="text-sm text-muted-foreground">Nenhum resultado.</p>}</div></section>}
