import { createFileRoute, Link } from "@tanstack/react-router";
import { BookOpen, Languages, ShieldPlus } from "lucide-react";
import { useI18n } from "@/lib/i18n";

export const Route=createFileRoute("/_clientarea/cliente/biblioteca/cursos-gratuitos")({component:FreeCoursesShelf});

const COPY={
pt:{back:"← Minha Biblioteca",eyebrow:"LDR Plataforma",title:"Cursos gratuitos",intro:"Conteúdos digitais para estudar no seu ritmo. Os cursos desta área são 100% em formato de leitura e não incluem aulas ao vivo.",free:"Gratuito",career:"Como Organizar sua Carreira e Dar o Próximo Passo Profissional",careerMeta:"7 aulas · 7 dias · 100% leitura · sem aulas ao vivo.",view:"Ver curso",french:"Francês Básico para Negócios — Nível A1",frenchMeta:"30 aulas · 30 dias · 10 horas · 100% leitura · sem aulas ao vivo.",start:"Começar gratuitamente",aid:"Primeiros Socorros — Noções Básicas",aidMeta:"30 aulas · 30 dias · 10 horas · 100% leitura · sem aulas ao vivo.",aidNote:"Curso educativo e introdutório · não habilita como socorrista profissional."},
en:{back:"← My Library",eyebrow:"LDR Platform",title:"Free courses",intro:"Digital content to study at your own pace. Courses in this area are 100% reading-based and do not include live classes.",free:"Free",career:"Organize Your Career and Take the Next Professional Step",careerMeta:"7 lessons · 7 days · 100% reading · no live classes.",view:"View course",french:"Basic French for Business — Level A1",frenchMeta:"30 lessons · 30 days · 10 hours · 100% reading · no live classes.",start:"Start for free",aid:"First Aid — Basic Concepts",aidMeta:"30 lessons · 30 days · 10 hours · 100% reading · no live classes.",aidNote:"Educational introductory course · does not qualify you as a professional first responder."},
fr:{back:"← Ma Bibliothèque",eyebrow:"Plateforme LDR",title:"Cours gratuits",intro:"Des contenus numériques à étudier à votre rythme. Les cours de cet espace sont 100 % en lecture et ne comprennent pas de cours en direct.",free:"Gratuit",career:"Organiser sa carrière et franchir la prochaine étape professionnelle",careerMeta:"7 leçons · 7 jours · 100 % lecture · sans cours en direct.",view:"Voir le cours",french:"Français de base pour les affaires — Niveau A1",frenchMeta:"30 leçons · 30 jours · 10 heures · 100 % lecture · sans cours en direct.",start:"Commencer gratuitement",aid:"Premiers secours — Notions de base",aidMeta:"30 leçons · 30 jours · 10 heures · 100 % lecture · sans cours en direct.",aidNote:"Cours éducatif et introductif · ne qualifie pas comme secouriste professionnel."},
es:{back:"← Mi Biblioteca",eyebrow:"Plataforma LDR",title:"Cursos gratuitos",intro:"Contenidos digitales para estudiar a tu ritmo. Los cursos de esta área son 100% de lectura y no incluyen clases en vivo.",free:"Gratis",career:"Cómo organizar tu carrera y dar el siguiente paso profesional",careerMeta:"7 clases · 7 días · 100% lectura · sin clases en vivo.",view:"Ver curso",french:"Francés básico para negocios — Nivel A1",frenchMeta:"30 clases · 30 días · 10 horas · 100% lectura · sin clases en vivo.",start:"Empezar gratis",aid:"Primeros auxilios — Nociones básicas",aidMeta:"30 clases · 30 días · 10 horas · 100% lectura · sin clases en vivo.",aidNote:"Curso educativo e introductorio · no habilita como socorrista profesional."}
} as const;

function FreeCoursesShelf(){const {locale}=useI18n();const c=COPY[locale];return <div className="space-y-5"><Link to="/cliente/biblioteca" className="text-sm font-bold text-[#9a4828]">{c.back}</Link><section className="rounded-[28px] border bg-[#fffaf7] p-5 sm:p-7"><p className="text-xs font-black uppercase tracking-[.16em] text-[#b85c2e]">{c.eyebrow}</p><h1 className="mt-2 font-serif text-3xl font-bold text-[#5d2917]">{c.title}</h1><p className="mt-2 text-sm text-[#64748b]">{c.intro}</p><div className="mt-6 grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Link to="/cliente/biblioteca/curso-gratuito-carreira" className="block rounded-[24px] border border-[#d88a62] bg-gradient-to-br from-[#7b351f] to-[#b85c2e] p-5 text-white shadow-lg"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-black uppercase tracking-[.14em] text-[#9a4828]">{c.free}</span><BookOpen className="mt-4 h-7 w-7"/><h2 className="mt-3 font-serif text-2xl font-bold">{c.career}</h2><p className="mt-2 text-sm text-white/85">{c.careerMeta}</p><span className="mt-4 inline-block text-sm font-black underline underline-offset-4">{c.view}</span></Link><Link to="/cliente/cursos/frances-negocios-a1" className="block rounded-[24px] border border-[#496e98] bg-gradient-to-br from-[#071426] via-[#123f73] to-[#8b1723] p-5 text-white shadow-lg"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-black uppercase tracking-[.14em] text-[#123f73]">🇫🇷 {c.free} · A1</span><Languages className="mt-4 h-7 w-7"/><h2 className="mt-3 font-serif text-2xl font-bold">{c.french}</h2><p className="mt-2 text-sm text-white/85">{c.frenchMeta}</p><span className="mt-4 inline-block text-sm font-black underline underline-offset-4">{c.start}</span></Link><Link to="/cliente/cursos/primeiros-socorros" className="block rounded-[24px] border border-[#d44a55] bg-gradient-to-br from-[#5b0b12] via-[#b51f2e] to-[#071426] p-5 text-white shadow-lg"><span className="inline-flex rounded-full bg-white px-3 py-1 text-[10px] font-black uppercase tracking-[.14em] text-[#a71927]">⛑️ {c.free}</span><ShieldPlus className="mt-4 h-7 w-7"/><h2 className="mt-3 font-serif text-2xl font-bold">{c.aid}</h2><p className="mt-2 text-sm text-white/85">{c.aidMeta}</p><p className="mt-2 text-xs text-white/70">{c.aidNote}</p><span className="mt-4 inline-block text-sm font-black underline underline-offset-4">{c.start}</span></Link></div></section></div>}
