import { Outlet, createFileRoute, useLocation } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { BookOpen, Film, GraduationCap, LockKeyhole, MessageCircle, ReceiptText, ShoppingCart } from "lucide-react";
import { useState } from "react";

import { clientCreateDigitalCheckout, clientCreateEntrepreneurComboCheckout, clientDigitalLibrary } from "@/lib/client-portal.functions";
import { clientAddLibraryComment, clientLearningHub } from "@/lib/learning.functions";
import { clientCreateDoMamaoTrainingCheckout, clientDoMamaoTrainingOffer } from "@/lib/training-commerce.functions";
import { useI18n } from "@/lib/i18n";

export const Route = createFileRoute("/_clientarea/cliente/biblioteca")({ component: ClientLibraryRoute });

function ClientLibraryRoute() {
  const location = useLocation();
  const pathname = location.pathname.replace(/\/+$/, "") || "/";
  if (pathname !== "/cliente/biblioteca") return <Outlet />;
  return <ClientLibrary />;
}

type Locale = "pt" | "en" | "fr" | "es";

const COPY = {
  pt: { eyebrow:"A Coragem de Começar", title:"Minha Biblioteca", intro:"Seu espaço exclusivo para leitura, formação e conteúdos.", orders:"Ver pedidos e pagamentos", paid:"Pagamento recebido.", paidBody:"Estamos confirmando sua compra e liberando o acesso automaticamente.", refresh:"Atualizar acesso", cancelled:"Pagamento cancelado. Nenhum conteúdo foi liberado.", buyState:"Disponível para compra", accessState:"Acesso liberado", value:"Valor", locked:"A leitura permanece bloqueada até a confirmação do pagamento.", buy:"Comprar", trainingMeta:"Formação · 3 meses · 300 horas", trainingDesc:"Jornada guiada para empreendedores, atividades práticas, 6 encontros ao vivo opcionais, projeto de negócio e 3 avaliações mensais incluídas.", trainingLocked:"A formação completa é liberada após a confirmação do pagamento.", buyTraining:"Quero começar minha formação", accessTraining:"Acessar treinamento", progress:"Progresso", cohort:"Turma", film:"Filme", filmTitle:"O Menino que Vendia Mamão", filmState:"Em produção", filmText:"Adaptação cinematográfica em desenvolvimento. Ainda não há compra nem conteúdo liberado na Biblioteca.", comments:"Comentários", commentsHelp:"Envie dúvidas ou comentários sobre seus conteúdos. A equipe responde por aqui.", none:"Nenhum comentário ainda.", write:"Escreva seu comentário…", publish:"Publicar comentário", team:"Equipe LDR Essence", client:"Cliente", readerEbook:"Acessar eBook", readerBook:"Acessar livro", launch:"OFERTA DE LANÇAMENTO", half:"PREÇO ESPECIAL", first100:"Preço especial para os primeiros 100 alunos", lifetime:"Acesso vitalício", optional:"6 encontros ao vivo opcionais", project:"3 avaliações · 1 por mês" },
  en: { eyebrow:"The Courage to Begin", title:"My Library", intro:"Your private space for reading, training and content.", orders:"View orders and payments", paid:"Payment received.", paidBody:"We are confirming your purchase and unlocking access automatically.", refresh:"Refresh access", cancelled:"Payment cancelled. No content was unlocked.", buyState:"Available to buy", accessState:"Access granted", value:"Price", locked:"Reading remains locked until payment is confirmed.", buy:"Buy", trainingMeta:"Training · 3 months · 300 hours", trainingDesc:"Guided entrepreneurial journey, practical activities, 6 optional live sessions, business project and 3 monthly reviews included.", trainingLocked:"The full training unlocks after payment confirmation.", buyTraining:"Start my training", accessTraining:"Open training", progress:"Progress", cohort:"Cohort", film:"Film", filmTitle:"The Boy Who Sold Papaya", filmState:"In production", filmText:"Film adaptation in development. There is no purchase or content available yet.", comments:"Comments", commentsHelp:"Send questions or comments. The team replies here.", none:"No comments yet.", write:"Write your comment…", publish:"Publish comment", team:"LDR Essence Team", client:"Client", readerEbook:"Open eBook", readerBook:"Open book", launch:"LAUNCH OFFER", half:"PREÇO ESPECIAL", first100:"Special price for the first 100 students", lifetime:"Lifetime access", optional:"6 optional live sessions", project:"3 reviews · 1 per month" },
  fr: { eyebrow:"Le Courage de Commencer", title:"Ma Bibliothèque", intro:"Votre espace privé de lecture, formation et contenus.", orders:"Voir les commandes et paiements", paid:"Paiement reçu.", paidBody:"Nous confirmons votre achat et débloquons automatiquement l’accès.", refresh:"Actualiser l’accès", cancelled:"Paiement annulé. Aucun contenu n’a été débloqué.", buyState:"Disponible à l’achat", accessState:"Accès autorisé", value:"Prix", locked:"La lecture reste verrouillée jusqu’à confirmation du paiement.", buy:"Acheter", trainingMeta:"Formation · 3 mois · 300 heures", trainingDesc:"Parcours guidé, activités pratiques, 6 rencontres en direct facultatives, projet d’entreprise et 3 évaluations mensuelles incluses.", trainingLocked:"La formation complète est débloquée après confirmation du paiement.", buyTraining:"Commencer ma formation", accessTraining:"Ouvrir la formation", progress:"Progression", cohort:"Groupe", film:"Film", filmTitle:"Le Garçon qui Vendait des Papayes", filmState:"En production", filmText:"Adaptation cinématographique en développement. Aucun achat ni contenu n’est encore disponible.", comments:"Commentaires", commentsHelp:"Envoyez vos questions ou commentaires. L’équipe répond ici.", none:"Aucun commentaire pour le moment.", write:"Écrivez votre commentaire…", publish:"Publier", team:"Équipe LDR Essence", client:"Client", readerEbook:"Ouvrir l’eBook", readerBook:"Ouvrir le livre", launch:"OFFRE DE LANCEMENT", half:"PRIX SPÉCIAL", first100:"Prix spécial pour les 100 premiers élèves", lifetime:"Accès à vie", optional:"6 rencontres en direct facultatives", project:"3 évaluations · 1 par mois" },
  es: { eyebrow:"El Valor de Empezar", title:"Mi Biblioteca", intro:"Tu espacio privado de lectura, formación y contenidos.", orders:"Ver pedidos y pagos", paid:"Pago recibido.", paidBody:"Estamos confirmando tu compra y liberando el acceso automáticamente.", refresh:"Actualizar acceso", cancelled:"Pago cancelado. No se liberó ningún contenido.", buyState:"Disponible para comprar", accessState:"Acceso liberado", value:"Precio", locked:"La lectura permanece bloqueada hasta confirmar el pago.", buy:"Comprar", trainingMeta:"Formación · 3 meses · 300 horas", trainingDesc:"Recorrido guiado, actividades prácticas, 6 encuentros en vivo opcionales, proyecto de negocio y 3 evaluaciones mensuales incluidas.", trainingLocked:"La formación completa se libera después de confirmar el pago.", buyTraining:"Comenzar mi formación", accessTraining:"Abrir formación", progress:"Progreso", cohort:"Grupo", film:"Película", filmTitle:"El Niño que Vendía Papaya", filmState:"En producción", filmText:"Adaptación cinematográfica en desarrollo. Todavía no hay compra ni contenido disponible.", comments:"Comentarios", commentsHelp:"Envía dudas o comentarios. El equipo responde aquí.", none:"Aún no hay comentarios.", write:"Escribe tu comentario…", publish:"Publicar", team:"Equipo LDR Essence", client:"Cliente", readerEbook:"Abrir eBook", readerBook:"Abrir libro", launch:"OFERTA DE LANZAMIENTO", half:"PREÇO ESPECIAL", first100:"Precio especial para los primeros 100 alumnos", lifetime:"Acceso de por vida", optional:"6 encuentros en vivo opcionales", project:"3 evaluaciones · 1 por mes" },
} as const;

const PRODUCT_COPY = {
  ebook_coragem_comecar: { pt:{title:"A Coragem de Começar",desc:"eBook de empreendedorismo, coragem e recomeços."}, en:{title:"The Courage to Begin",desc:"An eBook about entrepreneurship, courage and new beginnings."}, fr:{title:"Le Courage de Commencer",desc:"Un eBook sur l’entrepreneuriat, le courage et les nouveaux départs."}, es:{title:"El Valor de Empezar",desc:"Un eBook sobre emprendimiento, valentía y nuevos comienzos."} },
  livro_menino_mamao: { pt:{title:"O Menino que Vendia Mamão",desc:"Livro autobiográfico sobre trabalho, recomeços, estratégia e a coragem de continuar construindo."}, en:{title:"The Boy Who Sold Papaya",desc:"An autobiographical book about work, new beginnings, strategy and the courage to keep building."}, fr:{title:"Le Garçon qui Vendait des Papayes",desc:"Un livre autobiographique sur le travail, les nouveaux départs, la stratégie et le courage de continuer à construire."}, es:{title:"El Niño que Vendía Papaya",desc:"Un libro autobiográfico sobre trabajo, nuevos comienzos, estrategia y el valor de seguir construyendo."} },
} as const;

function money(cents:number,currency:"BRL"|"EUR",locale:Locale){const code=locale==="pt"?(currency==="BRL"?"pt-BR":"pt-PT"):locale==="fr"?"fr-FR":locale==="es"?"es-ES":"en-US";return new Intl.NumberFormat(code,{style:"currency",currency}).format(cents/100);}

function ClientLibrary(){
  const {locale:currentLocale}=useI18n(); const locale=(currentLocale==="pt"||currentLocale==="en"||currentLocale==="fr"||currentLocale==="es"?currentLocale:"pt") as Locale; const copy=COPY[locale];
  const fn=useServerFn(clientDigitalLibrary); const checkoutFn=useServerFn(clientCreateDigitalCheckout); const comboCheckoutFn=useServerFn(clientCreateEntrepreneurComboCheckout); const trainingOfferFn=useServerFn(clientDoMamaoTrainingOffer); const trainingCheckoutFn=useServerFn(clientCreateDoMamaoTrainingCheckout); const learningFn=useServerFn(clientLearningHub); const commentFn=useServerFn(clientAddLibraryComment); const queryClient=useQueryClient();
  const [comment,setComment]=useState(""); const [productKey,setProductKey]=useState<string>("ebook_coragem_comecar");
  const checkout=useMutation({mutationFn:(input:{productKey:"ebook_coragem_comecar"|"livro_menino_mamao";market:"BR"|"INTL"})=>checkoutFn({data:input}),onSuccess:(r)=>{window.location.href=r.url;}});
  const trainingCheckout=useMutation({mutationFn:(market:"BR"|"INTL")=>trainingCheckoutFn({data:{market}}),onSuccess:(r)=>{window.location.href=r.url;}}); const comboCheckout=useMutation({mutationFn:(market:"BR"|"INTL")=>comboCheckoutFn({data:{market}}),onSuccess:(r)=>{window.location.href=r.url;}});
  const addComment=useMutation({mutationFn:()=>commentFn({data:{body:comment,productKey}}),onSuccess:async()=>{setComment("");await queryClient.invalidateQueries({queryKey:["client-learning-hub"]});}});
  const params=typeof window!=="undefined"?new URLSearchParams(window.location.search):null; const paymentState=params?.get("payment");
  const {data,isLoading,error}=useQuery({queryKey:["client-digital-library"],queryFn:()=>fn({})}); const {data:trainingOffer}=useQuery({queryKey:["client-do-mamao-training-offer",paymentState],queryFn:()=>trainingOfferFn({})}); const {data:learning}=useQuery({queryKey:["client-learning-hub"],queryFn:()=>learningFn({})});
  if(isLoading)return <p className="text-sm text-muted-foreground">Carregando biblioteca…</p>; if(error||!data)return <section className="s8-card"><h1 className="font-serif text-2xl">{copy.title}</h1></section>;
  const comments=learning?.comments?.filter((c:any)=>c.product_key)??[]; const progress=learning?.progress??[]; const market:"BR"|"INTL"=data.market==="BR"?"BR":"INTL";
  const trainingPrice=trainingOffer?(market==="BR"?money(trainingOffer.priceBrlCents,"BRL",locale):money(trainingOffer.priceEurCents,"EUR",locale)):market==="BR"?"R$ 299,99":"€ 49,90";
  const regularTrainingPrice=trainingOffer?(market==="BR"?money(trainingOffer.regularPriceBrlCents,"BRL",locale):money(trainingOffer.regularPriceEurCents,"EUR",locale)):market==="BR"?"R$ 599,99":"€ 100,56";

  return <div className="min-w-0 space-y-5">
    <section className="s8-card" style={{background:"linear-gradient(145deg,#0b2341,#071426)",color:"#fff",borderColor:"#c9a63a"}}><p className="text-xs font-bold uppercase tracking-[.18em]" style={{color:"#d6ad63"}}>{copy.eyebrow}</p><h1 className="mt-1 !text-[#f7ead8] font-serif text-3xl sm:text-4xl">{copy.title}</h1><p className="mt-2 max-w-3xl text-sm leading-6 opacity-85">{copy.intro}</p><a href="/cliente/pedidos" className="mt-4 inline-flex min-h-11 items-center gap-2 text-sm font-bold underline"><ReceiptText className="h-4 w-4"/>{copy.orders}</a></section>
    {paymentState==="success"?<section className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900"><strong>{copy.paid}</strong> {copy.paidBody}</section>:paymentState==="cancel"?<section className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900">{copy.cancelled}</section>:null}

    {trainingOffer?.launchPromotionActive&&!trainingOffer.entitled?<section className="overflow-hidden rounded-3xl border border-[#d5aa45] bg-[#5b0824] p-5 text-white shadow-lg sm:p-7"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#d9aa3f] px-3 py-1 text-xs font-black text-[#3d0818]">🔥 {copy.launch}</span><span className="rounded-full bg-white px-3 py-1 text-xs font-black text-[#6d0d2e]">{copy.half}</span></div><h2 className="mt-4 font-serif text-3xl font-bold text-[#fff5df]">Do Mamão ao Negócio</h2><p className="mt-2 text-sm text-[#f5dfac]">{copy.first100}{typeof trainingOffer.launchRemaining==="number"?` · ${trainingOffer.launchRemaining} vagas promocionais restantes`:""}</p><div className="mt-5 flex flex-wrap items-end gap-3"><span className="text-base text-white/65 line-through">{regularTrainingPrice}</span><strong className="text-4xl text-[#f1c45d]">{trainingPrice}</strong></div><div className="mt-5 grid gap-2 text-sm sm:grid-cols-3"><div className="rounded-xl bg-white/10 p-3">✓ {copy.lifetime}</div><div className="rounded-xl bg-white/10 p-3">✓ {copy.optional}</div><div className="rounded-xl bg-white/10 p-3">✓ {copy.project}</div></div><button type="button" disabled={trainingCheckout.isPending} onClick={()=>trainingCheckout.mutate(market)} className="mt-5 min-h-12 w-full rounded-2xl bg-[#d9aa3f] px-5 font-black text-[#3d0818] disabled:opacity-50">{copy.buyTraining}</button><p className="mt-3 text-center text-xs text-white/70">Pagamento único · {copy.lifetime}</p></section>:null}

    <section className="overflow-hidden rounded-3xl border-2 border-[#d5aa45] bg-gradient-to-br from-[#35101e] to-[#5b0824] p-5 text-white shadow-xl sm:p-7"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-[#d9aa3f] px-3 py-1 text-xs font-black text-[#3d0818]">COMBO DE LANÇAMENTO</span><span className="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">3 PRODUTOS PELO PREÇO PROMOCIONAL DA FORMAÇÃO</span></div><h2 className="mt-4 font-serif text-3xl font-bold text-[#fff5df]">Combo Empreendedor — Formação Completa</h2><p className="mt-2 text-sm leading-6 text-[#f5dfac]">eBook A Coragem de Começar + Livro O Menino que Vendia Mamão + Formação Do Mamão ao Negócio.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white/10 p-4"><strong>📘 eBook</strong><p className="mt-1 text-xs opacity-80">A Coragem de Começar</p></div><div className="rounded-2xl bg-white/10 p-4"><strong>📕 Livro</strong><p className="mt-1 text-xs opacity-80">O Menino que Vendia Mamão</p></div><div className="rounded-2xl bg-white/10 p-4"><strong>🎓 Formação</strong><p className="mt-1 text-xs opacity-80">90 dias · 300 horas</p></div></div><div className="mt-5"><p className="text-sm text-white/70 line-through">{market==="BR"?"Separadamente: R$ 359,79":"Separadamente: € 74,80"}</p><strong className="mt-1 block text-4xl text-[#f1c45d]">{market==="BR"?"R$ 299,99":"€ 49,90"}</strong><p className="mt-1 text-sm font-bold text-emerald-300">{market==="BR"?"Economia: R$ 59,80":"Economia: € 24,90"}</p></div><button type="button" disabled={comboCheckout.isPending} onClick={()=>comboCheckout.mutate(market)} className="mt-5 min-h-12 w-full rounded-2xl bg-[#d9aa3f] px-5 font-black text-[#3d0818] disabled:opacity-50">QUERO O COMBO COMPLETO</button><p className="mt-3 text-center text-xs text-white/70">Pagamento único · acesso vitalício aos conteúdos digitais</p></section>

    <section className="grid min-w-0 gap-4 sm:grid-cols-2 xl:grid-cols-4" aria-label={copy.title}>
      {data.products.map((product)=>{const p=progress.find((x:any)=>x.product_key===product.key);const regionalPrice=market==="BR"?money(product.priceBrlCents,"BRL",locale):money(product.priceEurCents,"EUR",locale);const pc=PRODUCT_COPY[product.key][locale];const readerLabel=product.key==="ebook_coragem_comecar"?copy.readerEbook:copy.readerBook;return <article key={product.key} className="s8-card flex min-h-[360px] min-w-0 flex-col overflow-hidden"><div className="flex items-start justify-between gap-3"><div className="rounded-xl border border-border bg-accent/50 p-3 text-primary"><BookOpen className="h-6 w-6"/></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${product.entitled?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-900"}`}>{product.entitled?copy.accessState:copy.buyState}</span></div><h2 className="mt-5 font-serif text-2xl">{pc.title}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{pc.desc}</p>{p&&product.entitled?<div className="mt-4 rounded-xl bg-accent/50 p-4"><p className="text-xs font-bold uppercase text-primary">{copy.progress}</p><p className="mt-1 text-sm">{p.progress_percent}%</p></div>:null}<div className="mt-4 rounded-xl border border-border bg-background/70 p-4"><p className="text-xs uppercase text-muted-foreground">{copy.value}</p><p className="mt-1 font-bold text-primary">{regionalPrice}</p></div><div className="mt-auto pt-5">{product.entitled?<a href={`/cliente/biblioteca/${product.key}`} className="inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground">{readerLabel}</a>:<><div className="mb-3 flex gap-2 text-xs text-muted-foreground"><LockKeyhole className="h-4 w-4 shrink-0"/>{copy.locked}</div><button disabled={checkout.isPending} onClick={()=>checkout.mutate({productKey:product.key,market})} className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground"><ShoppingCart className="h-4 w-4"/>{copy.buy}</button></>}</div></article>;})}

      <article className="s8-card flex min-h-[360px] min-w-0 flex-col overflow-hidden" style={{borderColor:"#c9a63a"}}><div className="flex items-start justify-between gap-3"><div className="rounded-xl border p-3" style={{borderColor:"#c9a63a",background:"#0b2341",color:"#f0cf78"}}><GraduationCap className="h-6 w-6"/></div><span className={`rounded-full px-3 py-1 text-xs font-bold ${trainingOffer?.entitled?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-900"}`}>{trainingOffer?.entitled?copy.accessState:copy.buyState}</span></div><p className="mt-5 text-xs font-bold uppercase tracking-[.14em]" style={{color:"#8a6816"}}>{copy.trainingMeta}</p><h2 className="mt-1 font-serif text-2xl">Do Mamão ao Negócio</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy.trainingDesc}</p>{trainingOffer?.entitled?<div className="mt-4 rounded-xl bg-accent/50 p-4"><p className="text-xs font-bold uppercase text-primary">{copy.progress}</p><p className="mt-1 text-sm">{trainingOffer.progressPercent}%{trainingOffer.cohortNumber?` · ${copy.cohort} ${trainingOffer.cohortNumber}`:""}</p></div>:null}<div className="mt-4 rounded-xl border border-border bg-background/70 p-4">{trainingOffer?.launchPromotionActive&&!trainingOffer.entitled?<p className="mb-1 text-xs font-black text-[#9a6d12]">{copy.launch} · {copy.half}</p>:null}{trainingOffer?.launchPromotionActive&&!trainingOffer.entitled?<p className="text-xs text-muted-foreground line-through">{regularTrainingPrice}</p>:null}<p className="mt-1 text-xl font-black text-primary">{trainingPrice}</p></div><div className="mt-auto pt-5">{trainingOffer?.entitled?<a href="/cliente/treinamentos/do-mamao-ao-negocio" className="inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground">{copy.accessTraining}</a>:<><div className="mb-3 flex gap-2 text-xs text-muted-foreground"><LockKeyhole className="h-4 w-4 shrink-0"/>{copy.trainingLocked}</div><button disabled={trainingCheckout.isPending||!trainingOffer} onClick={()=>trainingCheckout.mutate(market)} className="inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground"><ShoppingCart className="h-4 w-4"/>{copy.buyTraining}</button></>}</div></article>

      <article className="s8-card flex min-h-[360px] min-w-0 flex-col overflow-hidden"><div className="flex items-start justify-between gap-3"><div className="rounded-xl border border-border bg-accent/50 p-3 text-primary"><Film className="h-6 w-6"/></div><span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-900">{copy.filmState}</span></div><p className="mt-5 text-xs font-bold uppercase text-primary">{copy.film}</p><h2 className="mt-1 font-serif text-2xl">{copy.filmTitle}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{copy.filmText}</p></article>
    </section>

    <section className="s8-card min-w-0"><h2 className="flex items-center gap-2 font-serif text-2xl"><MessageCircle className="h-5 w-5"/>{copy.comments}</h2><p className="mt-1 text-sm text-muted-foreground">{copy.commentsHelp}</p><div className="mt-4 grid gap-2">{comments.length?comments.map((c:any)=><div key={c.id} className={`rounded-xl border p-3 text-sm ${c.author_kind==="professional"?"bg-accent/70":"bg-background"}`}><p className="text-xs font-bold text-primary">{c.author_label||(c.author_kind==="professional"?copy.team:copy.client)}</p><p className="mt-1 whitespace-pre-wrap">{c.body}</p></div>):<p className="text-sm text-muted-foreground">{copy.none}</p>}</div><div className="mt-4 grid gap-2"><select value={productKey} onChange={(e)=>setProductKey(e.target.value)} className="min-h-11 rounded-lg border border-border bg-background p-3 text-sm">{data.products.map((p)=><option key={p.key} value={p.key}>{PRODUCT_COPY[p.key][locale].title}</option>)}<option value="do-mamao-ao-negocio">Do Mamão ao Negócio</option></select><textarea value={comment} onChange={(e)=>setComment(e.target.value)} className="min-h-24 rounded-lg border border-border bg-background p-3 text-sm" placeholder={copy.write}/><button disabled={!comment.trim()||addComment.isPending} onClick={()=>addComment.mutate()} className="min-h-11 justify-self-start rounded-lg bg-primary px-4 py-2 text-sm font-bold text-primary-foreground">{copy.publish}</button></div></section>
  </div>;
}
