import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useMemo, useState } from "react";
import { MessageCircle, ShieldCheck, Clock3, ShoppingCart } from "lucide-react";
import { useI18n } from "@/lib/i18n";
import { clientActivateProfessionalOrientationCheckout, clientCreateProfessionalOrientationCheckout, clientProfessionalOrientationOffer } from "@/lib/professional-orientation.functions";

export const Route=createFileRoute("/_clientarea/cliente/orientacao-profissional")({component:Page});

const SUPPORT_CHANNEL="Falar com o Ecossistema";
const SUPPORT_MESSAGE="Olá! Meu pagamento da Orientação Profissional foi confirmado pela LDR Essence Academy. Gostaria de continuar meu atendimento pelo Falar com o Ecossistema.";
const supportUrl=()=>`https://suporte.ldrrhestrategia.com/falar-com-ecossistema?assunto=${encodeURIComponent(SUPPORT_MESSAGE)}`;

const COPY={
pt:{new:"NOVO SERVIÇO",title:"Orientação Profissional Escrita",intro:"Orientação prática para carreira, currículo, entrevistas, transição profissional, posicionamento e próximos passos.",private:"Atendimento pelo Falar com o Ecossistema",minutes:"10, 30 ou 60 minutos",human:"Resposta humana",choose:"Escolha seu pacote",promo:"Promoção de lançamento ativa por 30 dias a partir da primeira compra confirmada.",regular:"Preço regular: €0,90 a cada 2 minutos, com pacotes prontos.",until:"PROMO ATÉ",pack:"PACOTE",min:"minutos",promoValue:"valor promocional",buy:"COMPRAR PACOTE",important:"Importante:",notice:"este é um serviço breve de orientação profissional. Não garante contratação, promoção, visto, reconhecimento de diploma ou resultado profissional. Decisões finais são do cliente e podem exigir profissionais ou órgãos especializados.",mine:"Minhas orientações",continue:"CONTINUAR NO SUPPORT",confirming:"Confirmando seu pagamento…",confirmed:"Pagamento confirmado com sucesso.",redirect:"Seu atendimento foi registrado. Agora você continuará pelo Falar com o Ecossistema.",retry:"Ainda estamos confirmando seu pagamento. Tente novamente em alguns segundos."},
en:{new:"NEW SERVICE",title:"Written Career Guidance",intro:"Practical guidance for career, CV, interviews, career transition, positioning and next steps.",private:"Service via Falar com o Ecossistema",minutes:"10, 30 or 60 minutes",human:"Human response",choose:"Choose your package",promo:"Launch promotion active for 30 days from the first confirmed purchase.",regular:"Regular price: €0.90 every 2 minutes, with ready-made packages.",until:"PROMO UNTIL",pack:"PACKAGE",min:"minutes",promoValue:"promotional price",buy:"BUY PACKAGE",important:"Important:",notice:"this is a brief professional guidance service. It does not guarantee hiring, promotion, visa, diploma recognition or professional results.",mine:"My guidance sessions",continue:"CONTINUE ON SUPPORT",confirming:"Confirming your payment…",confirmed:"Payment confirmed successfully.",redirect:"Your service was registered. You will now continue on Falar com o Ecossistema.",retry:"We are still confirming your payment. Please try again in a few seconds."},
fr:{new:"NOUVEAU SERVICE",title:"Orientation professionnelle écrite",intro:"Orientation pratique pour la carrière, le CV, les entretiens, la transition professionnelle, le positionnement et les prochaines étapes.",private:"Service via Falar com o Ecossistema",minutes:"10, 30 ou 60 minutes",human:"Réponse humaine",choose:"Choisissez votre forfait",promo:"Promotion de lancement active pendant 30 jours à compter du premier achat confirmé.",regular:"Tarif normal : 0,90 € toutes les 2 minutes, avec forfaits disponibles.",until:"PROMO JUSQU'AU",pack:"FORFAIT",min:"minutes",promoValue:"tarif promotionnel",buy:"ACHETER LE FORFAIT",important:"Important :",notice:"il s'agit d'un service bref d'orientation professionnelle. Il ne garantit ni embauche, ni promotion, ni visa, ni reconnaissance de diplôme, ni résultat professionnel.",mine:"Mes orientations",continue:"CONTINUER SUR SUPPORT",confirming:"Confirmation de votre paiement…",confirmed:"Paiement confirmé avec succès.",redirect:"Votre service a été enregistré. Vous allez maintenant continuer sur Falar com o Ecossistema.",retry:"Nous confirmons encore votre paiement. Réessayez dans quelques secondes."},
es:{new:"NUEVO SERVICIO",title:"Orientación Profesional Escrita",intro:"Orientación práctica para carrera, currículum, entrevistas, transición profesional, posicionamiento y próximos pasos.",private:"Atención por Falar com o Ecossistema",minutes:"10, 30 o 60 minutos",human:"Respuesta humana",choose:"Elige tu paquete",promo:"Promoción de lanzamiento activa durante 30 días desde la primera compra confirmada.",regular:"Precio regular: €0,90 cada 2 minutos, con paquetes disponibles.",until:"PROMO HASTA",pack:"PAQUETE",min:"minutos",promoValue:"valor promocional",buy:"COMPRAR PAQUETE",important:"Importante:",notice:"este es un servicio breve de orientación profesional. No garantiza contratación, promoción, visado, reconocimiento de diploma o resultado profesional.",mine:"Mis orientaciones",continue:"CONTINUAR EN SUPPORT",confirming:"Confirmando tu pago…",confirmed:"Pago confirmado correctamente.",redirect:"Tu servicio ha sido registrado. Ahora continuarás por Falar com o Ecossistema.",retry:"Todavía estamos confirmando tu pago. Inténtalo de nuevo en unos segundos."}
} as const;

const LOCALE_TAG={pt:"pt-BR",en:"en-US",fr:"fr-FR",es:"es-ES"} as const;

function Page(){
  const {locale}=useI18n(); const c=COPY[locale]; const tag=LOCALE_TAG[locale];
  const money=(cents:number,currency:string)=>new Intl.NumberFormat(tag,{style:"currency",currency}).format(cents/100);
  const offerFn=useServerFn(clientProfessionalOrientationOffer),checkoutFn=useServerFn(clientCreateProfessionalOrientationCheckout),activateFn=useServerFn(clientActivateProfessionalOrientationCheckout);
  const [paymentState,setPaymentState]=useState<"idle"|"confirming"|"confirmed"|"error">("idle");
  const [paymentError,setPaymentError]=useState("");
  const {data:offer,refetch:refetchOffer}=useQuery({queryKey:["professional-orientation-offer"],queryFn:()=>offerFn({})});

  useEffect(()=>{
    const params=new URLSearchParams(location.search);const id=params.get("session_id");const ok=params.get("payment")==="success";
    if(!id||!ok)return;
    let cancelled=false;let tries=0;setPaymentState("confirming");
    const confirm=async()=>{tries+=1;try{await activateFn({data:{checkoutSessionId:id}});if(cancelled)return;await refetchOffer();history.replaceState({},"",location.pathname);setPaymentState("confirmed");setTimeout(()=>{location.href=supportUrl();},700);}catch(error:any){if(cancelled)return;if(tries<8){setTimeout(confirm,1500);return;}setPaymentError(error?.message||c.retry);setPaymentState("error");}};
    confirm();return()=>{cancelled=true;};
  },[]);

  const checkout=useMutation({mutationFn:(x:{market:"BR"|"INTL";packageMinutes:10|30|60})=>checkoutFn({data:x}),onSuccess:r=>location.href=r.url});
  const sessions=offer?.sessions??[];
  const confirmedSessions=useMemo(()=>sessions.filter((s:any)=>s.status!=="pending"),[sessions]);

  if(paymentState!=="idle")return <main className="mx-auto max-w-3xl pb-16"><section className="rounded-[28px] border bg-white p-8 text-center shadow-sm"><MessageCircle className="mx-auto h-10 w-10 text-[#0b5cab]"/><h1 className="mt-4 font-serif text-3xl text-[#071426]">{paymentState==="confirmed"?c.confirmed:c.confirming}</h1><p className="mt-3 text-sm leading-6 text-slate-600">{paymentState==="error"?(paymentError||c.retry):c.redirect}</p>{paymentState==="confirmed"?<a href={supportUrl()} className="mt-6 inline-flex rounded-xl bg-[#25D366] px-6 py-3 font-black text-white">{c.continue}</a>:null}{paymentState==="error"?<button onClick={()=>location.reload()} className="mt-6 rounded-xl bg-[#0b5cab] px-6 py-3 font-black text-white">{c.retry}</button>:null}</section></main>;

  return <main className="mx-auto max-w-6xl space-y-8 pb-16"><section className="overflow-hidden rounded-[30px] bg-gradient-to-br from-[#071426] via-[#0b5cab] to-[#2d7bc2] p-7 text-white shadow-xl sm:p-10"><span className="inline-flex rounded-full bg-white/10 px-3 py-1 text-xs font-black uppercase tracking-[.14em]">{c.new}</span><h1 className="mt-4 font-serif text-4xl sm:text-5xl">{c.title}</h1><p className="mt-4 max-w-3xl text-white/80">{c.intro}</p><div className="mt-6 flex flex-wrap gap-2 text-xs font-black"><span className="rounded-xl bg-white/10 px-3 py-2"><MessageCircle className="mr-1 inline h-4 w-4"/>{c.private}</span><span className="rounded-xl bg-white/10 px-3 py-2"><Clock3 className="mr-1 inline h-4 w-4"/>{c.minutes}</span><span className="rounded-xl bg-white/10 px-3 py-2"><ShieldCheck className="mr-1 inline h-4 w-4"/>{c.human}</span></div></section><section className="rounded-[28px] border bg-white p-6 shadow-sm"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-serif text-3xl">{c.choose}</h2><p className="mt-2 text-sm text-slate-600">{offer?.promo?.active?c.promo:c.regular}</p></div>{offer?.promo?.promoExpiresAt&&offer?.promo?.active?<span className="rounded-full bg-emerald-100 px-3 py-2 text-xs font-black text-emerald-800">{c.until} {new Date(offer.promo.promoExpiresAt).toLocaleDateString(tag)}</span>:null}</div><div className="mt-6 grid gap-4 md:grid-cols-3">{offer?.packages?.map((p:any)=><article key={p.minutes} className="rounded-2xl border border-[#0b5cab]/25 bg-slate-50 p-5"><p className="text-xs font-black uppercase tracking-[.14em] text-[#0b5cab]">{c.pack}</p><h3 className="mt-2 text-2xl font-black">{p.minutes} {c.min}</h3><p className="mt-3 text-3xl font-black text-[#0b5cab]">{money(p.amountCents,p.currency)}</p>{offer?.promo?.active?<p className="mt-1 text-xs text-emerald-700">{c.promoValue}</p>:null}<button disabled={checkout.isPending} onClick={()=>checkout.mutate({market:offer.market,packageMinutes:p.minutes})} className="mt-5 w-full rounded-xl bg-[#0b5cab] px-4 py-3 text-sm font-black text-white disabled:opacity-50"><ShoppingCart className="mr-2 inline h-4 w-4"/>{c.buy}</button></article>)}</div></section><section className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><b>{c.important}</b> {c.notice}</section>{confirmedSessions.length?<section><h2 className="font-serif text-2xl">{c.mine}</h2><div className="mt-4 space-y-3">{confirmedSessions.map((s:any)=><a key={s.id} href={supportUrl()} className="flex w-full items-center justify-between rounded-2xl border bg-white p-4 text-left"><div><b>{s.package_minutes} {c.min}</b><p className="text-xs text-slate-500">{new Date(s.created_at).toLocaleString(tag)}</p></div><span className="rounded-full bg-[#25D366]/10 px-3 py-2 text-xs font-black text-[#128C7E]">{c.continue}</span></a>)}</div></section>:null}</main>;
}
