import { createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import {
  ArrowLeft, BookOpen, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight,
  FileCheck2, GraduationCap, HelpCircle, MessageCircle, Moon, Settings2, Sun, Video,
} from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import {
  clientCreateDoMamaoProjectReviewCheckout,
  clientDoMamaoTrainingExperience,
  clientSaveDoMamaoTrainingState,
  clientSubmitDoMamaoProject,
} from "@/lib/training-commerce.functions";
import { clientAddLibraryComment, clientLearningHub } from "@/lib/learning.functions";
import { useI18n } from "@/lib/i18n";

export const Route = createFileRoute("/_clientarea/cliente/treinamentos/do-mamao-ao-negocio")({ component: DoMamaoTraining });

type Locale = "pt" | "en" | "fr" | "es";
type Area = "inicio" | "trilha" | "projeto" | "encontros" | "ajuda";
type Step = { month:1|2|3; title:string; lesson:string; mentor:string; question:string; example:string; placeholder?:string; options?:string[] };

const COPY: Record<Locale, Record<string,string>> = {
  pt:{back:"Treinamentos",meta:"Formação de 3 meses · 300 horas",lifetime:"Acesso vitalício",minimum:"Conclusão oficial após 90 dias",progress:"Progresso",continue:"Continuar treinamento",start:"Início",path:"Trilha",project:"Projeto",live:"Encontros",help:"Ajuda",appearance:"Aparência",light:"Claro",dark:"Escuro",month1:"Mês 1 · Fundamentos",month2:"Mês 2 · Construção",month3:"Mês 3 · Execução",locked:"Esta etapa será liberada automaticamente no momento certo da sua jornada.",lesson:"Conteúdo desta etapa",mentor:"Luciano · Mentor",answer:"Sua resposta",save:"Salvar e continuar",previous:"Anterior",next:"Próxima",synced:"Sincronizado",saving:"Salvando…",failed:"Falha ao salvar",projectLocked:"Sua primeira entrega oficial será liberada ao completar os 90 dias.",projectReady:"Seu projeto já pode ser enviado para avaliação.",credits:"Créditos disponíveis",projectName:"Nome do projeto",projectLink:"Link do projeto (opcional)",projectText:"Cole ou descreva seu projeto aqui",submit:"Enviar para avaliação",extra:"Nova avaliação",extraHelp:"A primeira avaliação está incluída. Avaliações adicionais não exigem recompra do curso.",buyBR:"R$ 179,90",buyEU:"€ 29,90",sent:"Projetos enviados",noSent:"Nenhum projeto enviado ainda.",optional:"Encontros ao vivo extras e opcionais · 2 por mês · 6 no total",noLive:"Nenhum encontro publicado no momento.",join:"Participar",notices:"Avisos",noNotice:"Nenhum aviso novo.",questions:"Perguntas e respostas",ask:"Escreva sua dúvida…",send:"Enviar",days:"dias de jornada",stage:"Etapa atual",nextAction:"Próximo passo"},
  en:{back:"Training",meta:"3-month training · 300 hours",lifetime:"Lifetime access",minimum:"Official completion after 90 days",progress:"Progress",continue:"Continue training",start:"Home",path:"Path",project:"Project",live:"Sessions",help:"Help",appearance:"Appearance",light:"Light",dark:"Dark",month1:"Month 1 · Foundations",month2:"Month 2 · Build",month3:"Month 3 · Execution",locked:"This stage will unlock automatically at the right time in your journey.",lesson:"Step content",mentor:"Luciano · Mentor",answer:"Your answer",save:"Save and continue",previous:"Previous",next:"Next",synced:"Synced",saving:"Saving…",failed:"Save failed",projectLocked:"Your first official submission unlocks after 90 days.",projectReady:"Your project can now be submitted for review.",credits:"Available credits",projectName:"Project name",projectLink:"Project link (optional)",projectText:"Paste or describe your project here",submit:"Submit for review",extra:"New review",extraHelp:"The first review is included. Extra reviews do not require repurchasing the course.",buyBR:"R$ 179.90",buyEU:"€ 29.90",sent:"Submitted projects",noSent:"No project submitted yet.",optional:"Extra optional live sessions · 2 per month · 6 total",noLive:"No session published right now.",join:"Join",notices:"Announcements",noNotice:"No new announcement.",questions:"Questions and answers",ask:"Write your question…",send:"Send",days:"days in journey",stage:"Current stage",nextAction:"Next step"},
  fr:{back:"Formations",meta:"Formation de 3 mois · 300 heures",lifetime:"Accès à vie",minimum:"Validation officielle après 90 jours",progress:"Progression",continue:"Continuer",start:"Accueil",path:"Parcours",project:"Projet",live:"Rencontres",help:"Aide",appearance:"Apparence",light:"Clair",dark:"Sombre",month1:"Mois 1 · Fondamentaux",month2:"Mois 2 · Construction",month3:"Mois 3 · Exécution",locked:"Cette étape sera débloquée automatiquement au bon moment.",lesson:"Contenu de cette étape",mentor:"Luciano · Mentor",answer:"Votre réponse",save:"Enregistrer et continuer",previous:"Précédent",next:"Suivant",synced:"Synchronisé",saving:"Enregistrement…",failed:"Échec",projectLocked:"Le premier dépôt officiel est débloqué après 90 jours.",projectReady:"Votre projet peut être envoyé pour évaluation.",credits:"Crédits disponibles",projectName:"Nom du projet",projectLink:"Lien du projet (optionnel)",projectText:"Collez ou décrivez votre projet ici",submit:"Envoyer pour évaluation",extra:"Nouvelle évaluation",extraHelp:"La première évaluation est incluse. Les suivantes ne nécessitent pas de racheter la formation.",buyBR:"R$ 179,90",buyEU:"29,90 €",sent:"Projets envoyés",noSent:"Aucun projet envoyé.",optional:"Rencontres en direct facultatives · 2 par mois · 6 au total",noLive:"Aucune rencontre publiée.",join:"Participer",notices:"Annonces",noNotice:"Aucune nouvelle annonce.",questions:"Questions et réponses",ask:"Écrivez votre question…",send:"Envoyer",days:"jours de parcours",stage:"Étape actuelle",nextAction:"Prochaine étape"},
  es:{back:"Entrenamientos",meta:"Formación de 3 meses · 300 horas",lifetime:"Acceso de por vida",minimum:"Finalización oficial después de 90 días",progress:"Progreso",continue:"Continuar",start:"Inicio",path:"Ruta",project:"Proyecto",live:"Encuentros",help:"Ayuda",appearance:"Apariencia",light:"Claro",dark:"Oscuro",month1:"Mes 1 · Fundamentos",month2:"Mes 2 · Construcción",month3:"Mes 3 · Ejecución",locked:"Esta etapa se habilitará automáticamente en el momento adecuado.",lesson:"Contenido de esta etapa",mentor:"Luciano · Mentor",answer:"Tu respuesta",save:"Guardar y continuar",previous:"Anterior",next:"Siguiente",synced:"Sincronizado",saving:"Guardando…",failed:"Error al guardar",projectLocked:"La primera entrega oficial se habilita después de 90 días.",projectReady:"Tu proyecto ya puede enviarse para evaluación.",credits:"Créditos disponibles",projectName:"Nombre del proyecto",projectLink:"Enlace del proyecto (opcional)",projectText:"Pega o describe tu proyecto aquí",submit:"Enviar para evaluación",extra:"Nueva evaluación",extraHelp:"La primera evaluación está incluida. Las adicionales no requieren volver a comprar el curso.",buyBR:"R$ 179,90",buyEU:"€ 29,90",sent:"Proyectos enviados",noSent:"Aún no hay proyectos enviados.",optional:"Encuentros en vivo opcionales · 2 por mes · 6 en total",noLive:"No hay encuentros publicados.",join:"Participar",notices:"Avisos",noNotice:"No hay avisos nuevos.",questions:"Preguntas y respuestas",ask:"Escribe tu duda…",send:"Enviar",days:"días de recorrido",stage:"Etapa actual",nextAction:"Próximo paso"},
};

const STEPS: Record<Locale, Step[]> = {
  pt:[
    {month:1,title:"Começar do ponto real",lesson:"Antes de criar um negócio, entenda sua situação atual: experiência, recursos, tempo, conhecimento e o que já existe de concreto. Clareza evita decisões impulsivas e ajuda a construir algo possível.",mentor:"Vamos começar entendendo onde você está hoje.",question:"Você já tem uma ideia de negócio?",example:"Exemplo: quero vender refeições saudáveis para pessoas que trabalham perto de mim.",options:["Sim, já tenho","Tenho uma ideia, mas ainda está confusa","Ainda não tenho"]},
    {month:1,title:"Problema antes da solução",lesson:"Negócios ganham força quando resolvem uma necessidade percebida. Observe dificuldades, desejos, custos, atrasos ou oportunidades reais antes de pensar no produto.",mentor:"Um negócio forte começa por um problema real.",question:"Qual problema você gostaria de resolver?",example:"Exemplo: profissionais não têm tempo para preparar almoço saudável durante a semana.",placeholder:"Descreva o problema em poucas linhas."},
    {month:1,title:"Quem é o cliente",lesson:"Seu cliente não é todo mundo. Definir para quem você quer vender ajuda a escolher linguagem, preço, canal, oferta e forma de atendimento.",mentor:"Agora vamos aproximar sua ideia de uma pessoa real.",question:"Quem você imagina que compraria essa solução?",example:"Exemplo: pessoas de 25 a 45 anos que trabalham em escritórios e compram almoço durante a semana.",placeholder:"Descreva seu cliente de forma simples."},
    {month:2,title:"Transformar ideia em oferta",lesson:"Oferta é a forma concreta como o cliente compra sua solução. Ela precisa deixar claro o que recebe, como funciona e qual resultado prático busca.",mentor:"Chegou a hora de transformar a ideia em algo que possa ser comprado.",question:"O que exatamente você pretende oferecer?",example:"Exemplo: plano semanal com 5 refeições prontas e entrega na segunda-feira.",placeholder:"Produto, serviço, experiência ou combinação."},
    {month:2,title:"Preço e modelo de cobrança",lesson:"O preço precisa sustentar custos, tempo, margem e percepção de valor. Nesta etapa, crie uma hipótese que poderá ser testada e ajustada.",mentor:"Preço não nasce só do custo. Ele precisa fazer sentido para o cliente e para o negócio.",question:"Como você imagina cobrar por essa oferta?",example:"Exemplo: €45 por pacote semanal ou €10 por refeição avulsa.",placeholder:"Valor, faixa de preço ou modelo de cobrança."},
    {month:2,title:"Validar antes de investir demais",lesson:"Validar é testar se alguém demonstra interesse, pede informação, reserva ou paga. Um teste pequeno pode evitar meses de investimento sem mercado.",mentor:"Antes de crescer, vamos testar.",question:"Qual é a menor forma de testar essa ideia com uma pessoa real?",example:"Exemplo: oferecer 10 vagas de teste e medir quantas pessoas realmente compram.",placeholder:"Escreva um teste simples que você pode fazer."},
    {month:3,title:"Plano de execução",lesson:"Uma ideia só vira negócio quando se transforma em ações. Priorize poucas tarefas que aproximem você de um cliente ou de uma venda.",mentor:"Agora saímos da ideia e entramos em execução.",question:"Quais são as três ações mais importantes para colocar isso em prática?",example:"Exemplo: definir cardápio, calcular preço e fazer a primeira oferta para 10 pessoas.",placeholder:"1. ...  2. ...  3. ..."},
    {month:3,title:"Chegar aos primeiros clientes",lesson:"Canal é onde a relação comercial começa: indicação, WhatsApp, Instagram, rua, empresa, marketplace, parceria ou prospecção direta.",mentor:"Todo projeto precisa de uma forma de chegar ao cliente.",question:"Onde você pretende encontrar seus primeiros clientes?",example:"Exemplo: grupos locais de WhatsApp e contato direto com pequenos escritórios.",placeholder:"Canais, lugares, redes ou contatos."},
    {month:3,title:"Síntese do projeto",lesson:"Seu projeto final deve unir problema, cliente, oferta, preço, validação, canais e ações. Ele precisa demonstrar que você consegue explicar e executar a lógica do negócio.",mentor:"Estamos chegando ao seu projeto final.",question:"Em uma frase, qual negócio você quer construir e por quê?",example:"Exemplo: quero criar um serviço semanal de refeições práticas para profissionais com pouco tempo.",placeholder:"Escreva a versão mais clara da sua proposta."},
  ],
  en:[], fr:[], es:[],
};
STEPS.en = STEPS.pt.map((s,i)=>({...s,title:["Start from reality","Problem before solution","Define the customer","Turn the idea into an offer","Price and payment","Validate before investing","Execution plan","Reach first customers","Project summary"][i]}));
STEPS.fr = STEPS.pt.map((s,i)=>({...s,title:["Commencer à partir de la réalité","Le problème avant la solution","Définir le client","Transformer l’idée en offre","Prix et paiement","Valider avant d’investir","Plan d’exécution","Trouver les premiers clients","Synthèse du projet"][i]}));
STEPS.es = STEPS.pt.map((s,i)=>({...s,title:["Empezar desde la realidad","El problema antes de la solución","Definir al cliente","Convertir la idea en oferta","Precio y cobro","Validar antes de invertir","Plan de ejecución","Llegar a los primeros clientes","Síntesis del proyecto"][i]}));

function DoMamaoTraining(){
  const {locale:appLocale}=useI18n();
  const [locale,setLocale]=useState<Locale>((["pt","en","fr","es"].includes(appLocale)?appLocale:"pt") as Locale);
  const [area,setArea]=useState<Area>("inicio"); const [theme,setTheme]=useState<"light"|"dark">("light"); const [scale,setScale]=useState(1);
  const [stepIndex,setStepIndex]=useState(0); const [answer,setAnswer]=useState(""); const [guidedAnswers,setGuidedAnswers]=useState<Record<string,string>>({}); const [cloudState,setCloudState]=useState<Record<string,unknown>>({});
  const [syncLabel,setSyncLabel]=useState(COPY.pt.synced); const [question,setQuestion]=useState(""); const [projectTitle,setProjectTitle]=useState(""); const [projectUrl,setProjectUrl]=useState(""); const [projectText,setProjectText]=useState("");
  const c=COPY[locale]; const steps=STEPS[locale]; const experienceFn=useServerFn(clientDoMamaoTrainingExperience); const saveFn=useServerFn(clientSaveDoMamaoTrainingState); const learningFn=useServerFn(clientLearningHub); const commentFn=useServerFn(clientAddLibraryComment); const submitProjectFn=useServerFn(clientSubmitDoMamaoProject); const checkoutFn=useServerFn(clientCreateDoMamaoProjectReviewCheckout); const qc=useQueryClient();
  const {data,isLoading,error}=useQuery({queryKey:["do-mamao-training-experience"],queryFn:()=>experienceFn({})}); const {data:learning}=useQuery({queryKey:["client-learning-hub"],queryFn:()=>learningFn({})});
  const save=useMutation({mutationFn:(state:Record<string,unknown>)=>saveFn({data:{state}}),onMutate:()=>setSyncLabel(c.saving),onSuccess:()=>setSyncLabel(c.synced),onError:()=>setSyncLabel(c.failed)});
  const ask=useMutation({mutationFn:()=>commentFn({data:{body:question,trainingId:data!.trainingId}}),onSuccess:async()=>{setQuestion("");await qc.invalidateQueries({queryKey:["client-learning-hub"]});}});
  const submitProject=useMutation({mutationFn:()=>submitProjectFn({data:{title:projectTitle,projectUrl,projectText}}),onSuccess:async()=>{setProjectTitle("");setProjectUrl("");setProjectText("");await qc.invalidateQueries({queryKey:["do-mamao-training-experience"]});}});
  const buyReview=useMutation({mutationFn:(market:"BR"|"INTL")=>checkoutFn({data:{market}}),onSuccess:(r)=>{if(r.url)window.location.assign(r.url);}});

  useEffect(()=>{if(!data)return;const state=(data.trainingState&&typeof data.trainingState==="object"?data.trainingState:{}) as Record<string,unknown>;setCloudState(state);const ga=(state.guidedAnswers&&typeof state.guidedAnswers==="object"?state.guidedAnswers:{}) as Record<string,string>;setGuidedAnswers(ga);const idx=typeof state.guidedStep==="number"?state.guidedStep:0;setStepIndex(Math.max(0,Math.min(8,idx)));},[data]);
  useEffect(()=>{setSyncLabel(c.synced);setAnswer(guidedAnswers[`guided_${locale}_${stepIndex}`]??"");},[c.synced,guidedAnswers,locale,stepIndex]);

  if(isLoading)return <div className="s8-card">Carregando seu treinamento…</div>; if(error||!data)return <div className="s8-card">Não foi possível abrir o treinamento.</div>;
  const startDate=new Date(data.enrolledAt); const days=Math.max(0,Math.floor((Date.now()-startDate.getTime())/86400000)); const maxStep=days<30?2:days<60?5:8; const current=steps[stepIndex]; const isLocked=stepIndex>maxStep;
  const stage=days<30?c.month1:days<60?c.month2:c.month3; const progress=Number(data.progressPercent??0); const dark=theme==="dark"; const page=dark?"bg-[#120b0f] text-[#f9f1ec]":"bg-[#fffaf4] text-[#301018]"; const card=dark?"border-[#5f4539] bg-[#21161b]":"border-[#ead6ad] bg-white"; const soft=dark?"bg-[#2b1c22]":"bg-[#fff2d9]"; const input=dark?"border-[#6b5144] bg-[#160f13] text-white":"border-[#dfcca5] bg-white text-[#301018]";
  const saveGuided=()=>{if(!answer.trim()||isLocked)return;const key=`guided_${locale}_${stepIndex}`;const nextAnswers={...guidedAnswers,[key]:answer.trim()};const answers={...((cloudState.answers&&typeof cloudState.answers==="object"?cloudState.answers:{}) as Record<string,unknown>)};const quiz={...((cloudState.quiz&&typeof cloudState.quiz==="object"?cloudState.quiz:{}) as Record<string,unknown>)};const reflections={...((cloudState.reflections&&typeof cloudState.reflections==="object"?cloudState.reflections:{}) as Record<string,unknown>)};for(let i=0;i<7;i++)answers[`guided_${stepIndex}_a_${i}`]=answer.trim();for(let i=0;i<4;i++)quiz[`guided_${stepIndex}_q_${i}`]="completed";for(let i=0;i<4;i++)reflections[`guided_${stepIndex}_r_${i}`]=`Etapa ${stepIndex+1} concluída pelo aluno com resposta registrada e salva na jornada guiada.`;const nextIndex=Math.min(8,stepIndex+1);const merged={...cloudState,answers,quiz,reflections,guidedAnswers:nextAnswers,guidedStep:nextIndex,lastPanel:`guided-${stepIndex+1}`};setCloudState(merged);setGuidedAnswers(nextAnswers);save.mutate(merged);if(stepIndex<maxStep)setStepIndex(nextIndex);};
  const sessions=learning?.sessions?.filter((x:any)=>x.training_id===data.trainingId)??[]; const announcements=(learning?.announcements?.filter((x:any)=>x.training_id===data.trainingId)??[]).slice(0,3); const comments=useMemo(()=>(learning?.comments?.filter((x:any)=>x.training_id===data.trainingId)??[]).slice(-8),[learning?.comments,data.trainingId]);
  const nav:[[Area,string,any],[Area,string,any],[Area,string,any],[Area,string,any],[Area,string,any]]=[["inicio",c.start,BookOpen],["trilha",c.path,GraduationCap],["projeto",c.project,FileCheck2],["encontros",c.live,Video],["ajuda",c.help,HelpCircle]];

  return <div className={`min-h-screen overflow-x-hidden rounded-3xl pb-24 transition-colors ${page}`} style={{fontSize:`${scale}rem`}}>
    <header className="sticky top-0 z-20 border-b border-[#c89b3a]/40 bg-[#5b0824] text-white shadow-sm">
      <div className="mx-auto max-w-5xl px-4 py-3"><div className="flex items-center justify-between gap-3"><a href="/cliente/treinamentos" className="inline-flex min-h-10 items-center gap-2 text-sm font-semibold text-[#f5dfac]"><ArrowLeft className="h-4 w-4"/>{c.back}</a><details className="relative"><summary className="flex h-10 w-10 cursor-pointer list-none items-center justify-center rounded-xl border border-white/20 bg-white/10" aria-label={c.appearance}><Settings2 className="h-5 w-5"/></summary><div className="absolute right-0 mt-2 w-64 rounded-2xl border border-[#cda34a] bg-[#5b0824] p-3 shadow-xl"><select value={locale} onChange={e=>setLocale(e.target.value as Locale)} className="mb-2 min-h-11 w-full rounded-xl bg-white px-3 text-[#5b0824]"><option value="pt">Português</option><option value="en">English</option><option value="fr">Français</option><option value="es">Español</option></select><div className="grid grid-cols-4 gap-2"><button onClick={()=>setTheme("light")} className={`h-10 rounded-xl ${theme==="light"?"bg-[#d9aa3d] text-[#3d0818]":"bg-white text-[#5b0824]"}`}><Sun className="mx-auto h-4 w-4"/></button><button onClick={()=>setTheme("dark")} className={`h-10 rounded-xl ${theme==="dark"?"bg-[#d9aa3d] text-[#3d0818]":"bg-white text-[#5b0824]"}`}><Moon className="mx-auto h-4 w-4"/></button><button onClick={()=>setScale(v=>Math.max(.9,v-.05))} className="h-10 rounded-xl bg-white font-bold text-[#5b0824]">A−</button><button onClick={()=>setScale(v=>Math.min(1.2,v+.05))} className="h-10 rounded-xl bg-white font-bold text-[#5b0824]">A+</button></div></div></details></div><div className="mt-2"><p className="text-[11px] font-bold uppercase tracking-[.14em] text-[#dcb45c]">{c.meta}</p><div className="mt-1 flex items-end justify-between gap-3"><h1 className="font-serif text-2xl font-bold leading-tight">Do Mamão ao Negócio</h1><span className="shrink-0 text-xs font-bold">{progress}%</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-[#ddb044]" style={{width:`${Math.max(2,progress)}%`}}/></div></div></div>
    </header>

    <main className="mx-auto max-w-5xl space-y-4 px-3 py-4 sm:px-4">
      {area==="inicio"&&<><section className={`rounded-3xl border p-5 ${card}`}><p className="text-xs font-bold uppercase tracking-[.14em] text-[#b78324]">{c.stage}</p><h2 className="mt-1 font-serif text-2xl font-bold">{stage}</h2><div className="mt-4 grid grid-cols-2 gap-3"><div className={`rounded-2xl p-3 ${soft}`}><span className="text-xs opacity-70">{c.days}</span><strong className="mt-1 block text-xl">{days}</strong></div><div className={`rounded-2xl p-3 ${soft}`}><span className="text-xs opacity-70">{c.nextAction}</span><strong className="mt-1 block text-sm">{steps[Math.min(maxStep,stepIndex)].title}</strong></div></div><button onClick={()=>{setStepIndex(Math.min(stepIndex,maxStep));setArea("trilha")}} className="mt-4 min-h-12 w-full rounded-2xl bg-[#6d0d2e] px-5 font-bold text-white">{c.continue}</button></section><section className={`rounded-3xl border p-4 ${card}`}><div className="flex flex-wrap gap-2 text-xs font-bold"><span className={`rounded-full px-3 py-2 ${soft}`}>{c.lifetime}</span><span className={`rounded-full px-3 py-2 ${soft}`}>{c.minimum}</span></div></section></>}

      {area==="trilha"&&<section className={`rounded-3xl border p-4 sm:p-6 ${card}`}><div className="flex items-center justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#b78324]">{current.month===1?c.month1:current.month===2?c.month2:c.month3}</p><h2 className="mt-1 font-serif text-2xl font-bold">{current.title}</h2></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${soft}`}>{stepIndex+1}/9</span></div>{isLocked?<div className={`mt-5 rounded-2xl p-5 ${soft}`}><p className="font-bold">🔒 {c.locked}</p></div>:<><div className={`mt-5 rounded-2xl p-4 ${soft}`}><p className="text-xs font-bold uppercase tracking-[.13em] text-[#b78324]">{c.lesson}</p><p className="mt-2 leading-7">{current.lesson}</p><p className="mt-3 text-sm italic opacity-75">{current.example}</p></div><div className="mt-4 rounded-3xl rounded-tl-md bg-[#6d0d2e] p-4 text-white"><p className="text-xs font-bold uppercase tracking-[.13em] text-[#f1d18a]">{c.mentor}</p><p className="mt-2 leading-7">{current.mentor}</p></div><div className={`mt-4 rounded-3xl rounded-tr-md border p-4 ${card}`}><p className="font-bold">{current.question}</p>{current.options?<div className="mt-3 grid gap-2">{current.options.map(o=><button key={o} onClick={()=>setAnswer(o)} className={`min-h-12 rounded-2xl border px-4 text-left text-sm font-semibold ${answer===o?"border-[#c79631] bg-[#fff0c9] text-[#5b0824]":input}`}>{o}</button>)}</div>:<textarea value={answer} onChange={e=>setAnswer(e.target.value)} placeholder={current.placeholder||c.answer} className={`mt-3 min-h-32 w-full rounded-2xl border p-4 ${input}`}/>}</div><div className="mt-5 grid grid-cols-3 gap-2"><button disabled={stepIndex===0} onClick={()=>setStepIndex(v=>Math.max(0,v-1))} className={`min-h-11 rounded-xl border font-semibold disabled:opacity-40 ${card}`}><ChevronLeft className="mx-auto h-4 w-4"/></button><button disabled={!answer.trim()||save.isPending} onClick={saveGuided} className="min-h-11 rounded-xl bg-[#6d0d2e] px-3 text-sm font-bold text-white disabled:opacity-40"><CheckCircle2 className="mx-auto mb-1 h-4 w-4"/>{c.save}</button><button disabled={stepIndex>=maxStep} onClick={()=>setStepIndex(v=>Math.min(maxStep,v+1))} className={`min-h-11 rounded-xl border font-semibold disabled:opacity-40 ${card}`}><ChevronRight className="mx-auto h-4 w-4"/></button></div><p className="mt-3 text-center text-xs opacity-60">{syncLabel}</p></>}</section>}

      {area==="projeto"&&<section className="grid gap-4 lg:grid-cols-2"><div className={`rounded-3xl border p-5 ${card}`}><div className="flex items-center justify-between gap-3"><h2 className="font-serif text-2xl font-bold">{c.project}</h2><span className={`rounded-full px-3 py-1 text-xs font-bold ${soft}`}>{c.credits}: {data.availableProjectCredits??0}</span></div><p className="mt-3 text-sm leading-6">{data.projectSubmissionEligible?c.projectReady:c.projectLocked}</p>{data.projectSubmissionEligible&&Number(data.availableProjectCredits??0)>0&&<div className="mt-4 space-y-3"><input value={projectTitle} onChange={e=>setProjectTitle(e.target.value)} placeholder={c.projectName} className={`min-h-12 w-full rounded-2xl border px-4 ${input}`}/><input value={projectUrl} onChange={e=>setProjectUrl(e.target.value)} placeholder={c.projectLink} className={`min-h-12 w-full rounded-2xl border px-4 ${input}`}/><textarea value={projectText} onChange={e=>setProjectText(e.target.value)} placeholder={c.projectText} className={`min-h-40 w-full rounded-2xl border p-4 ${input}`}/><button disabled={!projectTitle.trim()||(!projectText.trim()&&!projectUrl.trim())||submitProject.isPending} onClick={()=>submitProject.mutate()} className="min-h-12 w-full rounded-2xl bg-[#6d0d2e] font-bold text-white disabled:opacity-40">{c.submit}</button></div>}</div><div className={`rounded-3xl border p-5 ${card}`}><h3 className="font-serif text-xl font-bold">{c.extra}</h3><p className="mt-2 text-sm leading-6 opacity-75">{c.extraHelp}</p><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={()=>buyReview.mutate("BR")} className={`min-h-12 rounded-2xl border font-bold ${card}`}>{c.buyBR}</button><button onClick={()=>buyReview.mutate("INTL")} className={`min-h-12 rounded-2xl border font-bold ${card}`}>{c.buyEU}</button></div><h4 className="mt-6 font-bold">{c.sent}</h4><div className="mt-2 space-y-2">{(data.projectSubmissions??[]).length?(data.projectSubmissions??[]).map((p:any)=><div key={p.id} className={`rounded-2xl p-3 text-sm ${soft}`}><strong>{p.title}</strong><span className="ml-2 text-xs opacity-60">{p.status}</span>{p.feedback&&<p className="mt-2 whitespace-pre-wrap text-sm">{p.feedback}</p>}</div>):<p className="text-sm opacity-60">{c.noSent}</p>}</div></div></section>}

      {area==="encontros"&&<section className={`rounded-3xl border p-5 ${card}`}><div className="flex items-start gap-3"><CalendarDays className="mt-1 h-5 w-5 text-[#b78324]"/><div><h2 className="font-serif text-2xl font-bold">{c.live}</h2><p className="mt-1 text-sm opacity-70">{c.optional}</p></div></div><div className="mt-4 space-y-3">{sessions.length?sessions.map((s:any)=><div key={s.id} className={`rounded-2xl p-4 ${soft}`}><strong>{s.title}</strong><p className="mt-1 text-sm opacity-70">{new Date(s.starts_at).toLocaleString()}</p>{s.description&&<p className="mt-2 text-sm">{s.description}</p>}{s.meeting_url&&<a href={s.meeting_url} target="_blank" rel="noreferrer" className="mt-3 inline-flex min-h-10 items-center rounded-xl bg-[#6d0d2e] px-4 text-sm font-bold text-white">{c.join}</a>}</div>):<p className="text-sm opacity-60">{c.noLive}</p>}</div></section>}

      {area==="ajuda"&&<section className="grid gap-4 lg:grid-cols-2"><div className={`rounded-3xl border p-5 ${card}`}><h2 className="font-serif text-xl font-bold">{c.notices}</h2><div className="mt-3 space-y-2">{announcements.length?announcements.map((a:any)=><div key={a.id} className={`rounded-2xl p-3 ${soft}`}><strong>{a.title}</strong><p className="mt-1 text-sm">{a.body}</p></div>):<p className="text-sm opacity-60">{c.noNotice}</p>}</div></div><div className={`rounded-3xl border p-5 ${card}`}><h2 className="font-serif text-xl font-bold">{c.questions}</h2><div className="mt-3 max-h-72 space-y-2 overflow-y-auto">{comments.map((m:any)=><div key={m.id} className={`rounded-2xl p-3 text-sm ${m.author_kind==="professional"?soft:"border border-current/10"}`}><strong>{m.author_kind==="professional"?"Equipe LDR":m.author_label}</strong><p className="mt-1">{m.body}</p></div>)}</div><textarea value={question} onChange={e=>setQuestion(e.target.value)} placeholder={c.ask} className={`mt-3 min-h-24 w-full rounded-2xl border p-3 ${input}`}/><button disabled={!question.trim()||ask.isPending} onClick={()=>ask.mutate()} className="mt-2 inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#6d0d2e] px-4 text-sm font-bold text-white disabled:opacity-40"><MessageCircle className="h-4 w-4"/>{c.send}</button></div></section>}
    </main>

    <nav className="fixed bottom-0 left-0 right-0 z-30 border-t border-[#c89b3a]/30 bg-[#5b0824]/95 px-2 pb-[max(env(safe-area-inset-bottom),8px)] pt-2 backdrop-blur"><div className="mx-auto grid max-w-xl grid-cols-5 gap-1">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>setArea(id)} className={`min-h-14 rounded-xl px-1 py-2 text-[11px] font-bold ${area===id?"bg-[#d9aa3d] text-[#3d0818]":"text-white"}`}><Icon className="mx-auto mb-1 h-4 w-4"/><span className="block truncate">{label}</span></button>)}</div></nav>
  </div>;
}