import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { Award, LockKeyhole, Printer } from "lucide-react";
import { psychoanalysisModules } from "@/content/psychoanalysis-curriculum-active";
import { clientPsychoanalysisOffer } from "@/lib/psychoanalysis-commerce.functions";
import { useI18n } from "@/lib/i18n";

export const Route=createFileRoute("/_clientarea/cliente/treinamentos/psicanalise/certificado")({component:PsychoanalysisCertificate});

const C={
pt:{checking:"Verificando certificado…",unavailable:"Certificado indisponível",need:"É necessário possuir acesso à Formação Online em Psicanálise.",locked:"Seu certificado ainda está bloqueado",days:"Dias de percurso",progress:"Progresso",cohort:"Turma",organizing:"Em organização",back:"Voltar à formação",print:"Gerar / imprimir certificado",certificate:"Certificado de Conclusão",certify:"Certificamos que",course:"Formação Online em Psicanálise",hours:"Carga horária",enrolled:"Data de matrícula",registered:"Registrada na plataforma",completed:"Data de conclusão",curriculum:"Matriz curricular",module:"Módulo",units:"unidades de aprendizagem",responsible:"Responsável pela formação",studentSignature:"Assinatura do aluno"},
en:{checking:"Checking certificate…",unavailable:"Certificate unavailable",need:"Access to the Online Psychoanalysis Training is required.",locked:"Your certificate is still locked",days:"Days in program",progress:"Progress",cohort:"Cohort",organizing:"Being organized",back:"Back to training",print:"Generate / print certificate",certificate:"Certificate of Completion",certify:"This certifies that",course:"Online Psychoanalysis Training",hours:"Course hours",enrolled:"Enrollment date",registered:"Registered on the platform",completed:"Completion date",curriculum:"Curriculum",module:"Module",units:"learning units",responsible:"Training coordinator",studentSignature:"Student signature"},
fr:{checking:"Vérification du certificat…",unavailable:"Certificat indisponible",need:"L’accès à la Formation en ligne en psychanalyse est requis.",locked:"Votre certificat est encore verrouillé",days:"Jours de parcours",progress:"Progression",cohort:"Groupe",organizing:"En cours d’organisation",back:"Retour à la formation",print:"Générer / imprimer le certificat",certificate:"Certificat de réussite",certify:"Nous certifions que",course:"Formation en ligne en psychanalyse",hours:"Volume horaire",enrolled:"Date d’inscription",registered:"Enregistrée sur la plateforme",completed:"Date de fin",curriculum:"Programme",module:"Module",units:"unités d’apprentissage",responsible:"Responsable de la formation",studentSignature:"Signature de l’étudiant"},
es:{checking:"Verificando certificado…",unavailable:"Certificado no disponible",need:"Es necesario tener acceso a la Formación Online en Psicoanálisis.",locked:"Tu certificado todavía está bloqueado",days:"Días de recorrido",progress:"Progreso",cohort:"Grupo",organizing:"En organización",back:"Volver a la formación",print:"Generar / imprimir certificado",certificate:"Certificado de Finalización",certify:"Certificamos que",course:"Formación Online en Psicoanálisis",hours:"Carga horaria",enrolled:"Fecha de matrícula",registered:"Registrada en la plataforma",completed:"Fecha de finalización",curriculum:"Plan de estudios",module:"Módulo",units:"unidades de aprendizaje",responsible:"Responsable de la formación",studentSignature:"Firma del alumno"}
} as const;
function PsychoanalysisCertificate(){
 const {locale}=useI18n(); const t=C[locale]??C.pt;
 const offerFn=useServerFn(clientPsychoanalysisOffer);
 const {data:offer,isLoading}=useQuery({queryKey:["psychoanalysis-certificate-status"],queryFn:()=>offerFn({})});
 if(isLoading)return <section className="s8-card">{t.checking}</section>;
 if(!offer?.entitled)return <section className="s8-card"><LockKeyhole className="h-7 w-7"/><h1 className="mt-3 font-serif text-2xl font-bold">{t.unavailable}</h1><p className="mt-2 text-sm text-muted-foreground">{t.need}</p></section>;
 if(!offer.certificateEligible)return <section className="mx-auto max-w-3xl rounded-[28px] border border-[#ded0eb] bg-white p-6 shadow-sm"><LockKeyhole className="h-8 w-8 text-[#5b2b86]"/><h1 className="mt-4 font-serif text-3xl font-bold text-[#2f1457]">{t.locked}</h1><p className="mt-3 text-sm leading-6 text-[#66576f]">A liberação acadêmica considera o período mínimo de 180 dias e 100% do percurso obrigatório. A conclusão formativa também exige no mínimo 12 sessões de análise pessoal e a etapa de prática clínica supervisionada da Clínica Social LDR, sujeitas à validação da equipe.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-[#f8f3fb] p-4"><p className="text-xs font-black uppercase text-[#7b4aa3]">{t.days}</p><p className="mt-1 text-2xl font-black text-[#2f1457]">{offer.elapsedDays}/180</p></div><div className="rounded-2xl bg-[#f8f3fb] p-4"><p className="text-xs font-black uppercase text-[#7b4aa3]">{t.progress}</p><p className="mt-1 text-2xl font-black text-[#2f1457]">{offer.progressPercent}%</p></div><div className="rounded-2xl bg-[#f8f3fb] p-4"><p className="text-xs font-black uppercase text-[#7b4aa3]">{t.cohort}</p><p className="mt-1 text-2xl font-black text-[#2f1457]">{offer.cohortNumber?`PSICA-${String(offer.cohortNumber).padStart(3,"0")}`:t.organizing}</p></div></div><Link to="/cliente/treinamentos/psicanalise" className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-[#5b2b86] px-4 text-sm font-black text-white">{t.back}</Link></section>;
 const dateLocale=locale==="fr"?"fr-FR":locale==="es"?"es-ES":locale==="en"?"en-GB":"pt-BR";
 const completionDate=new Date().toLocaleDateString(dateLocale);
 return <div className="mx-auto max-w-5xl space-y-4 pb-10">
   <div className="flex flex-wrap items-center justify-between gap-3 print:hidden"><Link to="/cliente/treinamentos/psicanalise" className="text-sm font-bold text-[#5b2b86] underline">{t.back}</Link><button onClick={()=>window.print()} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#5b2b86] px-4 text-sm font-black text-white"><Printer className="h-4 w-4"/>{t.print}</button></div>
   <section className="border-[10px] border-double border-[#5b2b86] bg-[#fffdf9] p-7 text-center shadow-xl print:shadow-none sm:p-12">
     <Award className="mx-auto h-12 w-12 text-[#c9a54a]"/>
     <p className="mt-4 text-xs font-black uppercase tracking-[.28em] text-[#7b4aa3]">Grupo LDR Essence · LDR RH & Estratégia</p>
     <h1 className="mt-5 font-serif text-4xl font-bold text-[#2f1457] sm:text-5xl">{t.certificate}</h1>
     <p className="mx-auto mt-6 max-w-3xl text-base leading-8 text-[#51445a]">{t.certify} <strong className="text-[#2f1457]">{offer.customerName}</strong> concluiu a <strong>{t.course}</strong>, com carga horária formativa total de <strong>1.200 horas</strong>, após cumprir o período mínimo formativo de 220 dias e os requisitos obrigatórios previstos no percurso.</p>
     <p className="mx-auto mt-4 max-w-3xl text-sm leading-7 text-[#66576f]">Formação livre em Psicanálise, com carga horária declarada de 1.200 horas. O percurso inclui formação teórica, atividades, análise pessoal e prática clínica supervisionada. Este certificado comprova a conclusão do percurso formativo; não equivale a graduação universitária, licença estatal ou autorização automática para exercer atividade regulada. O exercício profissional deve observar as regras aplicáveis no local de atuação.</p>
     <div className="mt-8 grid gap-4 text-left sm:grid-cols-3"><div className="rounded-2xl border border-[#dfd3e8] p-4"><p className="text-xs font-black uppercase text-[#7b4aa3]">{t.hours}</p><p className="mt-1 font-bold text-[#2f1457]">1.200 horas</p></div><div className="rounded-2xl border border-[#dfd3e8] p-4"><p className="text-xs font-black uppercase text-[#7b4aa3]">{t.enrolled}</p><p className="mt-1 font-bold text-[#2f1457]">{offer.enrolledAt?new Date(offer.enrolledAt).toLocaleDateString(dateLocale):t.registered}</p></div><div className="rounded-2xl border border-[#dfd3e8] p-4"><p className="text-xs font-black uppercase text-[#7b4aa3]">{t.completed}</p><p className="mt-1 font-bold text-[#2f1457]">{completionDate}</p></div></div>
     <div className="mt-8 text-left"><h2 className="font-serif text-2xl font-bold text-[#2f1457]">{t.curriculum}</h2><div className="mt-4 grid gap-2 sm:grid-cols-2">{psychoanalysisModules.map(m=><div key={m.id} className="rounded-xl border border-[#eadff0] p-3"><strong className="text-sm text-[#5b2b86]">{t.module} {m.id}</strong><p className="mt-1 text-xs leading-5 text-[#66576f]">{m.title} · {m.lessons.length} {t.units}</p></div>)}</div></div>
     <div className="mt-12 grid gap-10 sm:grid-cols-2"><div><div className="mx-auto h-px max-w-xs bg-[#2f1457]"/><p className="mt-2 font-serif text-lg font-bold text-[#2f1457]">Luciano Rodrigues Almeida</p><p className="text-xs text-[#66576f]">{t.responsible}</p></div><div><div className="mx-auto h-px max-w-xs bg-[#2f1457]"/><p className="mt-2 font-serif text-lg font-bold text-[#2f1457]">{t.studentSignature}</p><p className="text-xs text-[#66576f]">{offer.customerName}</p></div></div>
     <p className="mt-10 text-[11px] leading-5 text-[#85788c]">Certificado emitido digitalmente pela Plataforma LDR. Validação vinculada à conta e ao histórico de conclusão do aluno.</p>
   </section>
 </div>;
}
