import { createFileRoute, Link } from "@tanstack/react-router";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { BookOpen, CheckCircle2, ChevronLeft, ChevronRight, GraduationCap, LockKeyhole, Sparkles, UsersRound, Video } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { psychoanalysisModules, PSYCHOANALYSIS_TOTAL_LESSONS } from "@/content/psychoanalysis-curriculum";
import { clientCreatePsychoanalysisCheckout, clientPsychoanalysisOffer } from "@/lib/psychoanalysis-commerce.functions";
import { clientSaveProgress } from "@/lib/learning.functions";

export const Route=createFileRoute("/_clientarea/cliente/treinamentos/psicanalise")({component:PsychoanalysisTrainingExperience});

type Saved={completed:string[];module:number;lesson:number;answers:Record<string,string>};
const EMPTY:Saved={completed:[],module:0,lesson:0,answers:{}};
const KEY="ldr-psychoanalysis-training-v1";
function loadState():Saved{if(typeof window==="undefined")return EMPTY;try{const p=JSON.parse(localStorage.getItem(KEY)||"");return {...EMPTY,...p,answers:p.answers??{},completed:Array.isArray(p.completed)?p.completed:[]};}catch{return EMPTY;}}

function PsychoanalysisTrainingExperience(){
 const offerFn=useServerFn(clientPsychoanalysisOffer);const checkoutFn=useServerFn(clientCreatePsychoanalysisCheckout);const saveProgressFn=useServerFn(clientSaveProgress);
 const {data:offer,isLoading}=useQuery({queryKey:["psychoanalysis-offer"],queryFn:()=>offerFn({})});
 const checkout=useMutation({mutationFn:(market:"BR"|"INTL")=>checkoutFn({data:{market}}),onSuccess:r=>{window.location.href=r.url;}});
 const [state,setState]=useState<Saved>(EMPTY);const [answer,setAnswer]=useState("");
 useEffect(()=>setState(loadState()),[]);
 const mod=psychoanalysisModules[Math.min(state.module,psychoanalysisModules.length-1)];const lesson=mod.lessons[Math.min(state.lesson,mod.lessons.length-1)];
 const maxUnlockedLesson=Math.max(1,Math.min(PSYCHOANALYSIS_TOTAL_LESSONS,Number(offer?.maxUnlockedLesson??1)));
 const currentGlobalIndex=psychoanalysisModules.slice(0,state.module).reduce((sum,m)=>sum+m.lessons.length,0)+state.lesson;
 const nextLocked=currentGlobalIndex+1>=maxUnlockedLesson;
 useEffect(()=>setAnswer(state.answers[`m${mod.id}`]??""),[mod.id,state.answers]);
 const progress=Math.round((state.completed.length/PSYCHOANALYSIS_TOTAL_LESSONS)*100);
 const persist=(next:Saved)=>{setState(next);try{localStorage.setItem(KEY,JSON.stringify(next));}catch{}const pct=Math.round((next.completed.length/PSYCHOANALYSIS_TOTAL_LESSONS)*100);const m=psychoanalysisModules[Math.min(next.module,psychoanalysisModules.length-1)];const l=m.lessons[Math.min(next.lesson,m.lessons.length-1)];saveProgressFn({data:{productKey:"formacao_psicanalise",progressPercent:pct,currentLocation:`Módulo ${m.id} · ${l.title}`}}).catch(()=>undefined);};
 const markDone=()=>{const completed=state.completed.includes(lesson.id)?state.completed:[...state.completed,lesson.id];persist({...state,completed});};
 const next=()=>{markDone();if(state.lesson<mod.lessons.length-1){persist({...state,completed:state.completed.includes(lesson.id)?state.completed:[...state.completed,lesson.id],lesson:state.lesson+1});return;}if(state.module<psychoanalysisModules.length-1)persist({...state,completed:state.completed.includes(lesson.id)?state.completed:[...state.completed,lesson.id],module:state.module+1,lesson:0});};
 const previous=()=>{if(state.lesson>0)return persist({...state,lesson:state.lesson-1});if(state.module>0){const prev=psychoanalysisModules[state.module-1];persist({...state,module:state.module-1,lesson:prev.lessons.length-1});}};
 const saveAnswer=()=>persist({...state,answers:{...state.answers,[`m${mod.id}`]:answer}});
 const doneThis=state.completed.includes(lesson.id);const moduleDone=mod.lessons.every(l=>state.completed.includes(l.id));
 if(isLoading)return <section className="s8-card">Carregando formação…</section>;
 if(!offer?.entitled)return <section className="overflow-hidden rounded-[28px] border border-[#caa85d] bg-[#2f1457] p-6 text-white shadow-xl"><LockKeyhole className="h-8 w-8 text-[#e0c16f]"/><p className="mt-4 text-xs font-black uppercase tracking-[.16em] text-[#e0c16f]">Formação protegida</p><h1 className="mt-2 font-serif text-3xl font-bold">Formação Online em Psicanálise</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-white/75">12 módulos, 180 unidades de aprendizagem, 6 encontros ao vivo e acesso vitalício aos conteúdos digitais. A formação é liberada após a confirmação do pagamento.</p><div className="mt-5 flex flex-wrap gap-3"><button disabled={checkout.isPending} onClick={()=>checkout.mutate("BR")} className="rounded-2xl bg-[#d6b86d] px-5 py-3 text-sm font-black text-[#2f1457]">Brasil · R$ 299,99 · pagamento único</button><button disabled={checkout.isPending} onClick={()=>checkout.mutate("INTL")} className="rounded-2xl border border-white/25 px-5 py-3 text-sm font-black">Europa · € 49,90</button><Link to="/formacao-psicanalise" className="rounded-2xl border border-white/25 px-5 py-3 text-sm font-black">Ver página da formação</Link></div></section>;
 return <div className="min-w-0 space-y-5 pb-10">
  <section className="overflow-hidden rounded-[28px] border border-[#caa85d]/70 bg-gradient-to-br from-[#24103f] via-[#4b2077] to-[#2a104e] p-5 text-white shadow-xl sm:p-7"><div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><span className="inline-flex items-center gap-2 rounded-full bg-[#d6b86d] px-3 py-1.5 text-[11px] font-black uppercase tracking-[.15em] text-[#32155c]"><Sparkles className="h-3.5 w-3.5"/>Acesso liberado</span><h1 className="mt-4 font-serif text-3xl font-bold sm:text-4xl">Formação Online em Psicanálise</h1><p className="mt-2 text-sm text-white/75">Teoria · Análise pessoal · Supervisão · 12 módulos · 180 unidades · 1.200 horas · 6 encontros ao vivo</p><div className="mt-4 flex flex-wrap gap-2"><Link to="/cliente/treinamentos/psicanalise/forum" className="rounded-xl border border-white/20 bg-white/10 px-4 py-2 text-xs font-black text-white">Fórum da formação</Link><span className="rounded-xl bg-[#d6b86d] px-4 py-2 text-xs font-black text-[#32155c]">1 nova aula por dia</span><span className="rounded-xl bg-white/10 px-4 py-2 text-xs font-black text-white">Conclusão mínima: 180 dias</span>{offer.cohortNumber?<span className="rounded-xl bg-white/10 px-4 py-2 text-xs font-black text-white">Sua turma: PSICA-{String(offer.cohortNumber).padStart(3,"0")}</span>:null}</div></div><div className="min-w-[210px] rounded-2xl bg-white/10 p-4"><div className="flex items-center justify-between text-xs font-bold"><span>Seu progresso</span><span>{progress}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-[#d6b86d]" style={{width:`${progress}%`}}/></div><p className="mt-2 text-[11px] text-white/65">{state.completed.length} de {PSYCHOANALYSIS_TOTAL_LESSONS} aulas concluídas</p></div></div></section>

  <details className="rounded-[24px] border border-[#d9c77f] bg-[#fffaf0] p-5 shadow-sm sm:p-6"><summary className="cursor-pointer font-serif text-xl font-bold text-[#2f1457]">Requisitos para conclusão</summary><div className="mt-4 grid gap-3 text-sm leading-6 text-[#64596b]"><p>✓ Completar 100% do material teórico e das atividades obrigatórias.</p><p>✓ Cumprir o período mínimo de 180 dias dentro do percurso de 6 a 12 meses.</p><p>✓ Realizar no mínimo 12 sessões de análise pessoal.</p><p>✓ Cumprir a etapa de prática clínica supervisionada vinculada à Clínica Social LDR.</p><p className="rounded-xl bg-white p-3"><strong>Clínica Social LDR:</strong> na fase clínica, alunos elegíveis serão direcionados para atendimentos online de pacientes da clínica social, conforme disponibilidade, critérios, confidencialidade e supervisão.</p><p className="text-xs text-[#85788c]">Carga horária formativa total: 1.200 horas. A conclusão e a certificação permanecem sujeitas à validação dos requisitos formativos pela equipe.</p></div></details>
  <section className="grid gap-4 lg:grid-cols-[280px_minmax(0,1fr)]">
   <aside className="rounded-[24px] border border-[#dfd3e8] bg-white p-3 shadow-sm lg:sticky lg:top-20 lg:self-start"><div className="mb-3 px-2"><p className="text-xs font-black uppercase tracking-[.14em] text-[#7b4aa3]">Módulos</p><p className="mt-1 text-xs text-[#75677e]">180 dias de percurso estruturado · até 12 meses para concluir.</p></div><div className="grid gap-2 lg:max-h-[72vh] lg:overflow-y-auto">{psychoanalysisModules.map((m,mi)=>{const completedCount=m.lessons.filter(l=>state.completed.includes(l.id)).length;const firstIndex=psychoanalysisModules.slice(0,mi).reduce((sum,x)=>sum+x.lessons.length,0);const locked=firstIndex>=maxUnlockedLesson;return <button key={m.id} disabled={locked} onClick={()=>persist({...state,module:mi,lesson:0})} className={`w-full rounded-xl px-3 py-3 text-left disabled:cursor-not-allowed disabled:opacity-40 ${state.module===mi?"bg-[#4b2077] text-white":"hover:bg-[#f4eef9]"}`}><span className="block text-[10px] font-black uppercase tracking-[.12em] opacity-70">Módulo {String(m.id).padStart(2,"0")} · {completedCount}/{m.lessons.length}{locked?" · libera ao longo do percurso":""}</span><span className="mt-1 block text-sm font-bold leading-5">{m.title}</span></button>})}</div></aside>
   <main className="min-w-0 space-y-4">
    <section className="rounded-[24px] border border-[#dfd3e8] bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#efe5f7] px-3 py-1 text-[10px] font-black uppercase tracking-[.12em] text-[#5b2b86]">Módulo {mod.id}</span><span className="rounded-full bg-[#f5efe0] px-3 py-1 text-[10px] font-black uppercase tracking-[.12em] text-[#8a6816]">Aula {state.lesson+1}/{mod.lessons.length}</span>{doneThis?<span className="inline-flex items-center gap-1 rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black uppercase tracking-[.12em] text-emerald-700"><CheckCircle2 className="h-3 w-3"/>Concluída</span>:null}</div><h2 className="mt-4 font-serif text-3xl font-bold text-[#2f1457]">{lesson.title}</h2><p className="mt-2 text-sm font-semibold text-[#7b4aa3]">{lesson.summary}</p><div className="mt-6 space-y-4 text-[15px] leading-7 text-[#53495a]">{lesson.content.map((p,i)=><p key={i}>{p}</p>)}</div><div className="mt-8 flex flex-wrap justify-between gap-3 border-t border-[#eee5f3] pt-5"><button onClick={previous} disabled={state.module===0&&state.lesson===0} className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-[#d8c9e3] px-4 py-2 text-sm font-bold disabled:opacity-30"><ChevronLeft className="h-4 w-4"/>Anterior</button><div className="flex gap-2"><button onClick={markDone} className="rounded-xl border border-[#c8b3d8] px-4 py-2 text-sm font-bold text-[#5b2b86]">Marcar concluída</button><button onClick={next} disabled={nextLocked} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-[#5b2b86] px-4 py-2 text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-40">{nextLocked?"Próxima aula libera no próximo dia":"Próxima"}<ChevronRight className="h-4 w-4"/></button></div></div></section>
    {state.lesson===mod.lessons.length-1?<><section className="rounded-[24px] border border-[#d9c77f] bg-[#fffaf0] p-5 sm:p-6"><div className="flex items-center gap-2 text-[#7a5c12]"><BookOpen className="h-5 w-5"/><h3 className="font-serif text-2xl font-bold">Para ir mais fundo</h3></div><div className="mt-4 grid gap-3">{mod.deeper.map(r=><article key={r.title} className="rounded-2xl border border-[#eadba9] bg-white p-4"><p className="font-bold text-[#3b254d]">{r.title} ({r.year})</p><p className="text-xs font-semibold text-[#7b4aa3]">{r.author}</p><p className="mt-2 text-sm leading-6 text-[#64596b]">{r.note} Procure em edição oficial, biblioteca, Google Books ou acervo legal disponível em sua região.</p></article>)}</div></section><section className="rounded-[24px] border border-[#dfd3e8] bg-white p-5 sm:p-6"><h3 className="font-serif text-2xl font-bold text-[#2f1457]">Atividade do módulo</h3><p className="mt-2 text-sm leading-6 text-[#64596b]">{mod.activity}</p><textarea value={answer} onChange={e=>setAnswer(e.target.value)} rows={6} placeholder="Escreva sua resposta…" className="mt-4 w-full rounded-2xl border border-[#d8c9e3] bg-[#fcfaff] p-4 text-sm outline-none focus:border-[#7b4aa3]"/><div className="mt-3 flex items-center justify-between gap-3"><p className="text-xs text-[#85788c]">Sua resposta fica salva nesta experiência. A devolutiva docente será integrada ao fluxo de atividades.</p><button onClick={saveAnswer} className="shrink-0 rounded-xl bg-[#5b2b86] px-4 py-2 text-sm font-black text-white">Salvar atividade</button></div></section></>:null}
    <section className="grid gap-3 sm:grid-cols-3"><article className="rounded-2xl bg-[#2f1457] p-4 text-white"><GraduationCap className="h-5 w-5 text-[#e0c16f]"/><p className="mt-2 text-sm font-bold">Tripé formativo</p><p className="mt-1 text-xs text-white/65">Teoria, análise pessoal e supervisão.</p></article><article className="rounded-2xl bg-[#2f1457] p-4 text-white"><Video className="h-5 w-5 text-[#e0c16f]"/><p className="mt-2 text-sm font-bold">6 encontros ao vivo</p><p className="mt-1 text-xs text-white/65">Agenda e links dos encontros ao vivo serão exibidos aqui conforme o calendário.</p></article><article className="rounded-2xl bg-[#2f1457] p-4 text-white"><UsersRound className="h-5 w-5 text-[#e0c16f]"/><p className="mt-2 text-sm font-bold">Professores convidados</p><p className="mt-1 text-xs text-white/65">Participações serão adicionadas após confirmação.</p></article></section>
   <section className="grid gap-3 sm:grid-cols-3"><article className="rounded-2xl border border-[#dfd3e8] bg-white p-4"><p className="text-xs font-black uppercase tracking-[.12em] text-[#7b4aa3]">Ritmo recomendado</p><p className="mt-2 text-sm font-bold text-[#2f1457]">1 nova aula por dia</p><p className="mt-1 text-xs leading-5 text-[#75677e]">As aulas anteriores permanecem disponíveis para revisão.</p></article><article className="rounded-2xl border border-[#dfd3e8] bg-white p-4"><p className="text-xs font-black uppercase tracking-[.12em] text-[#7b4aa3]">Prazo</p><p className="mt-2 text-sm font-bold text-[#2f1457]">6 a 12 meses</p><p className="mt-1 text-xs leading-5 text-[#75677e]">O percurso acadêmico pode ser concluído a partir de 180 dias e permanece aberto por até 12 meses.</p></article><article className="rounded-2xl border border-[#dfd3e8] bg-white p-4"><p className="text-xs font-black uppercase tracking-[.12em] text-[#7b4aa3]">Certificado</p><p className="mt-2 text-sm font-bold text-[#2f1457]">Liberado após os requisitos</p><p className="mt-1 text-xs leading-5 text-[#75677e]">Somente após 180 dias de matrícula e conclusão das atividades obrigatórias. Formação livre em Psicanálise · CBO 2515-50.</p><Link to="/cliente/treinamentos/psicanalise/certificado" className="mt-3 inline-flex min-h-10 items-center rounded-xl bg-[#5b2b86] px-3 text-xs font-black text-white">{offer.certificateEligible?"Gerar certificado":"Ver requisitos"}</Link></article></section>
</main>
  </section>
 </div>;
}
