import { Link, createFileRoute } from "@tanstack/react-router";
import { BookOpen, FlaskConical, Newspaper, Search } from "lucide-react";
import { useMemo, useState } from "react";
import { EDITORIAL_CATALOG } from "@/lib/editorial-catalog";
import { localizeEditorial } from "@/lib/editorial-i18n";
import { useI18n } from "@/lib/i18n";

export const Route=createFileRoute("/_clientarea/cliente/biblioteca/publicacoes")({component:PublicacoesHub});

type Locale="pt"|"en"|"fr"|"es";
const COPY={
  pt:{back:"← Minha Biblioteca",articles:"ARTIGOS CIENTÍFICOS",eyebrow:"Central editorial LDR",title:"Jornais, revistas & conhecimento",intro:"Publicações semanais independentes sobre economia, política, migração, tecnologia, saúde, negócios, viagem, carreira internacional e outros temas. Cada assinatura é separada da assinatura principal da Biblioteca.",all:"TODOS",newspapers:"JORNAIS",magazines:"REVISTAS",search:"Buscar por tema, publicação ou assunto",weeklyPublications:"Publicações semanais",weekly:"Semanal",independent:"Assinatura independente",week:"semana",brazil:"Brasil",academic:"Pesquisa acadêmica",science:"Artigos Científicos & Pesquisa",scienceDesc:"Atalhos por área, fontes de acesso aberto e orientação para localizar DOI, autores, periódico e referências para trabalhos acadêmicos.",premium:"Edição especial premium",life:"A Vida de Luciano",lifeDesc:"Uma história real em novos capítulos toda semana. Assinatura de €5,00 ou R$29,90 por semana.",know:"CONHECER A REVISTA"},
  en:{back:"← My Library",articles:"SCIENTIFIC ARTICLES",eyebrow:"LDR editorial hub",title:"Newspapers, magazines & knowledge",intro:"Independent weekly publications on economy, politics, migration, technology, health, business, travel, international careers and more. Each subscription is separate from the main Library subscription.",all:"ALL",newspapers:"NEWSPAPERS",magazines:"MAGAZINES",search:"Search by topic, publication or subject",weeklyPublications:"Weekly publications",weekly:"Weekly",independent:"Independent subscription",week:"week",brazil:"Brazil",academic:"Academic research",science:"Scientific Articles & Research",scienceDesc:"Shortcuts by field, open-access sources and guidance to find DOI, authors, journals and references for academic work.",premium:"Premium special edition",life:"The Life of Luciano",lifeDesc:"A true story with new chapters every week. Subscription €5.00 or R$29.90 per week.",know:"DISCOVER THE MAGAZINE"},
  fr:{back:"← Ma Bibliothèque",articles:"ARTICLES SCIENTIFIQUES",eyebrow:"Centre éditorial LDR",title:"Journaux, magazines & connaissance",intro:"Publications hebdomadaires indépendantes sur l'économie, la politique, la migration, la technologie, la santé, les affaires, le voyage, la carrière internationale et d'autres thèmes. Chaque abonnement est séparé de l'abonnement principal de la Bibliothèque.",all:"TOUS",newspapers:"JOURNAUX",magazines:"MAGAZINES",search:"Rechercher par thème, publication ou sujet",weeklyPublications:"Publications hebdomadaires",weekly:"Hebdomadaire",independent:"Abonnement indépendant",week:"semaine",brazil:"Brésil",academic:"Recherche académique",science:"Articles Scientifiques & Recherche",scienceDesc:"Accès par domaine, sources en libre accès et orientation pour trouver DOI, auteurs, revues et références pour les travaux académiques.",premium:"Édition spéciale premium",life:"La Vie de Luciano",lifeDesc:"Une histoire vraie avec de nouveaux chapitres chaque semaine. Abonnement de 5,00 € ou R$29,90 par semaine.",know:"DÉCOUVRIR LE MAGAZINE"},
  es:{back:"← Mi Biblioteca",articles:"ARTÍCULOS CIENTÍFICOS",eyebrow:"Central editorial LDR",title:"Periódicos, revistas & conocimiento",intro:"Publicaciones semanales independientes sobre economía, política, migración, tecnología, salud, negocios, viajes, carrera internacional y otros temas. Cada suscripción es independiente de la suscripción principal de la Biblioteca.",all:"TODOS",newspapers:"PERIÓDICOS",magazines:"REVISTAS",search:"Buscar por tema, publicación o asunto",weeklyPublications:"Publicaciones semanales",weekly:"Semanal",independent:"Suscripción independiente",week:"semana",brazil:"Brasil",academic:"Investigación académica",science:"Artículos Científicos & Investigación",scienceDesc:"Accesos por área, fuentes de acceso abierto y orientación para localizar DOI, autores, revistas y referencias para trabajos académicos.",premium:"Edición especial premium",life:"La Vida de Luciano",lifeDesc:"Una historia real con nuevos capítulos cada semana. Suscripción de 5,00 € o R$29,90 por semana.",know:"CONOCER LA REVISTA"},
} as const;

function money(c:number,cur:"BRL"|"EUR",locale:Locale){return new Intl.NumberFormat(locale==="pt"?(cur==="BRL"?"pt-BR":"pt-PT"):locale==="fr"?"fr-FR":locale==="es"?"es-ES":"en-US",{style:"currency",currency:cur}).format(c/100)}

function PublicacoesHub(){
  const {locale:raw}=useI18n();
  const locale=(raw==="pt"||raw==="en"||raw==="fr"||raw==="es"?raw:"pt") as Locale;
  const t=COPY[locale];
  const [q,setQ]=useState("");
  const [tab,setTab]=useState<"todos"|"jornal"|"revista">("todos");
  const catalog=useMemo(()=>EDITORIAL_CATALOG.map(x=>localizeEditorial(x,locale)),[locale]);
  const items=useMemo(()=>catalog.filter(x=>(tab==="todos"||x.kind===tab)&&(`${x.title} ${x.description} ${x.topics.join(" ")}`).toLowerCase().includes(q.toLowerCase())),[q,tab,catalog]);
  return <div className="space-y-7 pb-10">
    <div className="flex flex-wrap items-center justify-between gap-3"><Link to="/cliente/biblioteca" className="text-sm font-black text-[#0b2341]">{t.back}</Link><Link to="/cliente/biblioteca/artigos-cientificos" className="rounded-full border border-[#d6ad63] px-4 py-2 text-xs font-black text-[#0b2341]">{t.articles}</Link></div>
    <section className="overflow-hidden rounded-[30px] bg-gradient-to-br from-[#071426] via-[#0b2341] to-[#163b67] p-7 text-white shadow-xl sm:p-10">
      <p className="text-xs font-black uppercase tracking-[.25em] text-[#d6ad63]">{t.eyebrow}</p>
      <h1 className="mt-3 font-serif text-4xl sm:text-6xl">{t.title}</h1>
      <p className="mt-4 max-w-3xl text-sm leading-7 text-white/75 sm:text-base">{t.intro}</p>
      <div className="mt-6 flex flex-wrap gap-2"><button onClick={()=>setTab("todos")} className={`rounded-full px-4 py-2 text-xs font-black ${tab==="todos"?"bg-[#d6ad63] text-[#281605]":"bg-white/10"}`}>{t.all}</button><button onClick={()=>setTab("jornal")} className={`rounded-full px-4 py-2 text-xs font-black ${tab==="jornal"?"bg-[#d6ad63] text-[#281605]":"bg-white/10"}`}>{t.newspapers}</button><button onClick={()=>setTab("revista")} className={`rounded-full px-4 py-2 text-xs font-black ${tab==="revista"?"bg-[#d6ad63] text-[#281605]":"bg-white/10"}`}>{t.magazines}</button></div>
    </section>
    <div className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search} className="w-full rounded-2xl border bg-white py-3 pl-11 pr-4 text-sm outline-none focus:ring-2 focus:ring-[#d6ad63]"/></div>
    <section><div className="mb-4 flex items-center gap-2"><Newspaper className="h-5 w-5 text-[#a77b2e]"/><h2 className="font-serif text-3xl text-[#0b2341]">{t.weeklyPublications}</h2></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
<Link to="/cliente/biblioteca/jornal-ldr" className="group overflow-hidden rounded-[26px] border bg-white !text-slate-900 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="bg-gradient-to-br from-[#071426] via-[#0b2341] to-[#163b67] p-5 !text-white"><div className="flex items-start justify-between gap-3"><span className="text-3xl">📰</span><span className="rounded-full bg-white/15 px-3 py-1 text-[9px] font-black uppercase tracking-wider !text-white">{t.weekly}</span></div><h3 className="mt-5 font-serif text-2xl leading-tight !text-white">Jornal LDR</h3><p className="mt-2 text-xs leading-5 !text-white/80">LDR Editorial</p></div><div className="p-5"><p className="text-sm font-bold text-slate-700">{t.independent}</p><p className="mt-1 font-black text-[#0b2341]">{money(90,"EUR",locale)} / {t.week} <span className="font-medium text-slate-500">· {t.brazil} {money(90,"BRL",locale)}</span></p></div></Link>
<Link to="/cliente/biblioteca/revista-ldr" className="group overflow-hidden rounded-[26px] border bg-white !text-slate-900 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="bg-gradient-to-br from-[#4c071d] via-[#6b0d2b] to-[#8f2448] p-5 !text-white"><div className="flex items-start justify-between gap-3"><span className="text-3xl">📖</span><span className="rounded-full bg-white/15 px-3 py-1 text-[9px] font-black uppercase tracking-wider !text-white">{t.weekly}</span></div><h3 className="mt-5 font-serif text-2xl leading-tight !text-white">Revista LDR</h3><p className="mt-2 text-xs leading-5 !text-white/80">LDR Editorial</p></div><div className="p-5"><p className="text-sm font-bold text-slate-700">{t.independent}</p><p className="mt-1 font-black text-[#0b2341]">{money(90,"EUR",locale)} / {t.week} <span className="font-medium text-slate-500">· {t.brazil} {money(90,"BRL",locale)}</span></p></div></Link>
{items.map(item=><Link key={item.productKey} to="/cliente/biblioteca/publicacoes/$slug" params={{slug:item.slug}} className="group overflow-hidden rounded-[26px] border bg-white shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><div className="p-5 text-white" style={{background:`linear-gradient(135deg,${item.color},#071426)`}}><div className="flex items-start justify-between gap-3"><span className="text-3xl">{item.icon}</span><span className="rounded-full bg-white/15 px-3 py-1 text-[9px] font-black uppercase tracking-wider">{t.weekly}</span></div><h3 className="mt-5 font-serif text-2xl leading-tight !text-white">{item.title}</h3><p className="mt-2 text-xs leading-5 !text-white/80">{item.subtitle}</p></div><div className="p-5"><p className="text-sm leading-6 text-slate-600">{item.description}</p><div className="mt-4 flex flex-wrap gap-1.5">{item.topics.slice(0,4).map(topic=><span key={topic} className="rounded-full bg-slate-100 px-2.5 py-1 text-[9px] font-bold text-slate-600">{topic}</span>)}</div><div className="mt-5 border-t pt-4"><p className="text-xs font-bold text-slate-500">{t.independent}</p><p className="mt-1 font-black text-[#0b2341]">{money(item.priceEurCents,"EUR",locale)} / {t.week} <span className="font-medium text-slate-400">· {t.brazil} {money(item.priceBrlCents,"BRL",locale)}</span></p></div></div></Link>)}</div></section>
    <section className="grid gap-4 lg:grid-cols-2"><Link to="/cliente/biblioteca/artigos-cientificos" className="rounded-[26px] border border-[#d6ad63]/40 bg-[#fffaf0] p-6 shadow-sm"><FlaskConical className="h-7 w-7 text-[#a77b2e]"/><p className="mt-4 text-[10px] font-black uppercase tracking-[.2em] text-[#a77b2e]">{t.academic}</p><h2 className="mt-2 font-serif text-3xl text-[#0b2341]">{t.science}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{t.scienceDesc}</p></Link><div className="rounded-[26px] bg-[#5b0824] p-6 text-white"><BookOpen className="h-7 w-7 text-[#f0c775]"/><p className="mt-4 text-[10px] font-black uppercase tracking-[.2em] text-[#f0c775]">{t.premium}</p><h2 className="mt-2 font-serif text-3xl">{t.life}</h2><p className="mt-3 text-sm leading-6 text-white/75">{t.lifeDesc}</p><Link to="/cliente/biblioteca/publicacoes/$slug" params={{slug:"a-vida-de-luciano"}} className="mt-5 inline-block rounded-xl bg-[#f0c775] px-4 py-3 text-xs font-black text-[#35101e]">{t.know}</Link></div></section>
  </div>
}
