import { Link, createFileRoute } from "@tanstack/react-router";
import { BookOpenCheck, ExternalLink, FlaskConical, Search, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";
import { useI18n } from "@/lib/i18n";

export const Route=createFileRoute("/_clientarea/cliente/biblioteca/artigos-cientificos")({component:ScientificArticles});

type Locale="pt"|"en"|"fr"|"es";
const COPY={
  pt:{publications:"← Publicações",library:"Minha Biblioteca",eyebrow:"Biblioteca acadêmica",title:"Artigos Científicos & Pesquisa",intro:"Área de apoio para localizar fontes confiáveis para faculdade, TCC, projetos de pesquisa e estudo pessoal. A LDR direciona para a fonte original e não reproduz integralmente artigos protegidos.",search:"Buscar área de pesquisa",areas:"Áreas de pesquisa",areaHelp:"Pesquise por assunto, autor, palavra-chave, ano, idioma e acesso aberto nas bases abaixo.",recommended:"Bases recomendadas",recommendedHelp:"Sempre confira autores, ano, periódico, DOI e versão original antes de citar.",checklist:"Checklist para trabalho acadêmico",checks:["Verifique se o artigo está realmente publicado em periódico.","Confirme autores, ano, título, volume, número e páginas.","Use o DOI quando houver.","Prefira o texto original e fontes de acesso aberto.","Não use referência inventada ou não verificada."],refs:"Referências ABNT e APA",refsText:"A estrutura desta área fica preparada para uma próxima etapa: selecionar um artigo verificado e gerar a referência em ABNT ou APA com base nos metadados reais da publicação.",warning:"Nunca gerar DOI, autor ou periódico por suposição.",topics:["Psicanálise e Comportamento","Recursos Humanos","Administração e Negócios","Inteligência Artificial","Saúde","Saúde Mental","Estética","Ciências Rurais","Migração","Turismo","Educação","Psicopedagogia","Economia","Política","Ciências Sociais"],sources:["Periódicos científicos, com forte presença de conteúdo em português e acesso aberto.","Base internacional para saúde, medicina, comportamento e áreas relacionadas.","Diretório de periódicos científicos de acesso aberto.","Pesquisa por título, autor e DOI para conferência bibliográfica.","Busca acadêmica ampla para localizar artigos, citações e versões disponíveis."]},
  en:{publications:"← Publications",library:"My Library",eyebrow:"Academic library",title:"Scientific Articles & Research",intro:"A support area for finding reliable sources for university work, dissertations, research projects and personal study. LDR directs users to the original source and does not reproduce protected articles in full.",search:"Search research field",areas:"Research fields",areaHelp:"Search by subject, author, keyword, year, language and open access in the databases below.",recommended:"Recommended databases",recommendedHelp:"Always verify authors, year, journal, DOI and the original version before citing.",checklist:"Academic work checklist",checks:["Check that the article is actually published in a journal.","Confirm authors, year, title, volume, issue and pages.","Use the DOI when available.","Prefer the original text and open-access sources.","Do not use invented or unverified references."],refs:"ABNT and APA references",refsText:"This area is prepared for a next step: selecting a verified article and generating an ABNT or APA reference from the publication's real metadata.",warning:"Never generate DOI, author or journal by assumption.",topics:["Psychoanalysis & Behaviour","Human Resources","Management & Business","Artificial Intelligence","Health","Mental Health","Aesthetics","Rural Sciences","Migration","Tourism","Education","Psychopedagogy","Economics","Politics","Social Sciences"],sources:["Scientific journals, with a strong presence of Portuguese-language and open-access content.","International database for health, medicine, behaviour and related fields.","Directory of open-access scientific journals.","Search by title, author and DOI for bibliographic verification.","Broad academic search to locate articles, citations and available versions."]},
  fr:{publications:"← Publications",library:"Ma Bibliothèque",eyebrow:"Bibliothèque académique",title:"Articles Scientifiques & Recherche",intro:"Espace d'appui pour trouver des sources fiables pour l'université, les mémoires, les projets de recherche et l'étude personnelle. LDR renvoie vers la source originale et ne reproduit pas intégralement les articles protégés.",search:"Rechercher un domaine",areas:"Domaines de recherche",areaHelp:"Recherchez par sujet, auteur, mot-clé, année, langue et accès ouvert dans les bases ci-dessous.",recommended:"Bases recommandées",recommendedHelp:"Vérifiez toujours les auteurs, l'année, la revue, le DOI et la version originale avant de citer.",checklist:"Checklist pour travail académique",checks:["Vérifiez que l'article est réellement publié dans une revue.","Confirmez les auteurs, l'année, le titre, le volume, le numéro et les pages.","Utilisez le DOI lorsqu'il existe.","Privilégiez le texte original et les sources en libre accès.","N'utilisez pas de référence inventée ou non vérifiée."],refs:"Références ABNT et APA",refsText:"Cette zone est prête pour une prochaine étape : sélectionner un article vérifié et générer la référence ABNT ou APA à partir des métadonnées réelles de la publication.",warning:"Ne jamais générer un DOI, un auteur ou une revue par supposition.",topics:["Psychanalyse & Comportement","Ressources Humaines","Gestion & Affaires","Intelligence Artificielle","Santé","Santé Mentale","Esthétique","Sciences Rurales","Migration","Tourisme","Éducation","Psychopédagogie","Économie","Politique","Sciences Sociales"],sources:["Revues scientifiques avec une forte présence de contenu en portugais et en libre accès.","Base internationale pour la santé, la médecine, le comportement et les domaines associés.","Répertoire de revues scientifiques en libre accès.","Recherche par titre, auteur et DOI pour vérification bibliographique.","Recherche académique large pour trouver des articles, citations et versions disponibles."]},
  es:{publications:"← Publicaciones",library:"Mi Biblioteca",eyebrow:"Biblioteca académica",title:"Artículos Científicos & Investigación",intro:"Área de apoyo para localizar fuentes fiables para universidad, TFG/TCC, proyectos de investigación y estudio personal. LDR dirige a la fuente original y no reproduce íntegramente artículos protegidos.",search:"Buscar área de investigación",areas:"Áreas de investigación",areaHelp:"Busca por tema, autor, palabra clave, año, idioma y acceso abierto en las bases de abajo.",recommended:"Bases recomendadas",recommendedHelp:"Comprueba siempre autores, año, revista, DOI y versión original antes de citar.",checklist:"Checklist para trabajo académico",checks:["Verifica que el artículo esté realmente publicado en una revista.","Confirma autores, año, título, volumen, número y páginas.","Usa el DOI cuando exista.","Prefiere el texto original y fuentes de acceso abierto.","No uses referencias inventadas o no verificadas."],refs:"Referencias ABNT y APA",refsText:"Esta área queda preparada para una siguiente etapa: seleccionar un artículo verificado y generar la referencia en ABNT o APA con base en los metadatos reales de la publicación.",warning:"Nunca generar DOI, autor o revista por suposición.",topics:["Psicoanálisis y Comportamiento","Recursos Humanos","Administración y Negocios","Inteligencia Artificial","Salud","Salud Mental","Estética","Ciencias Rurales","Migración","Turismo","Educación","Psicopedagogía","Economía","Política","Ciencias Sociales"],sources:["Revistas científicas, con fuerte presencia de contenido en portugués y acceso abierto.","Base internacional para salud, medicina, comportamiento y áreas relacionadas.","Directorio de revistas científicas de acceso abierto.","Búsqueda por título, autor y DOI para verificación bibliográfica.","Búsqueda académica amplia para localizar artículos, citas y versiones disponibles."]},
} as const;
const SOURCE_NAMES=["SciELO","PubMed","DOAJ","Crossref","Google Scholar"] as const;
const SOURCE_URLS=["https://www.scielo.org/","https://pubmed.ncbi.nlm.nih.gov/","https://doaj.org/","https://search.crossref.org/","https://scholar.google.com/"] as const;

function ScientificArticles(){
  const {locale:raw}=useI18n();
  const locale=(raw==="pt"||raw==="en"||raw==="fr"||raw==="es"?raw:"pt") as Locale;
  const t=COPY[locale];
  const [q,setQ]=useState("");
  const filtered=useMemo(()=>t.topics.filter(topic=>topic.toLowerCase().includes(q.toLowerCase())),[q,t]);
  return <div className="space-y-7 pb-10">
    <div className="flex flex-wrap items-center justify-between gap-3"><Link to="/cliente/biblioteca/publicacoes" className="text-sm font-black text-[#0b2341]">{t.publications}</Link><Link to="/cliente/biblioteca" className="text-sm font-bold text-slate-500">{t.library}</Link></div>
    <section className="rounded-[30px] bg-gradient-to-br from-[#2c2148] via-[#403566] to-[#17233d] p-7 text-white shadow-xl sm:p-10"><FlaskConical className="h-9 w-9 text-[#d6ad63]"/><p className="mt-5 text-xs font-black uppercase tracking-[.25em] text-[#d6ad63]">{t.eyebrow}</p><h1 className="mt-3 font-serif text-4xl sm:text-6xl">{t.title}</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-white/75 sm:text-base">{t.intro}</p></section>
    <div className="relative"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={t.search} className="w-full rounded-2xl border bg-white py-3 pl-11 pr-4 text-sm outline-none focus:ring-2 focus:ring-[#d6ad63]"/></div>
    <section><h2 className="font-serif text-3xl text-[#0b2341]">{t.areas}</h2><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(topic=><div key={topic} className="rounded-2xl border bg-white p-5"><BookOpenCheck className="h-5 w-5 text-[#a77b2e]"/><h3 className="mt-3 font-bold text-[#0b2341]">{topic}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{t.areaHelp}</p></div>)}</div></section>
    <section className="rounded-[26px] border bg-white p-6"><h2 className="font-serif text-3xl text-[#0b2341]">{t.recommended}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{t.recommendedHelp}</p><div className="mt-5 grid gap-3 md:grid-cols-2">{SOURCE_NAMES.map((name,i)=><a key={name} href={SOURCE_URLS[i]} target="_blank" rel="noreferrer" className="rounded-2xl border p-5 transition hover:border-[#d6ad63] hover:shadow-sm"><div className="flex items-center justify-between gap-3"><h3 className="font-black text-[#0b2341]">{name}</h3><ExternalLink className="h-4 w-4 text-[#a77b2e]"/></div><p className="mt-2 text-xs leading-5 text-slate-500">{t.sources[i]}</p></a>)}</div></section>
    <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-[26px] bg-[#fffaf0] p-6"><ShieldCheck className="h-6 w-6 text-[#a77b2e]"/><h2 className="mt-3 font-serif text-2xl text-[#0b2341]">{t.checklist}</h2><ul className="mt-4 space-y-2 text-sm leading-6 text-slate-600">{t.checks.map(x=><li key={x}>• {x}</li>)}</ul></div><div className="rounded-[26px] bg-[#0b2341] p-6 text-white"><h2 className="font-serif text-2xl">{t.refs}</h2><p className="mt-3 text-sm leading-6 text-white/70">{t.refsText}</p><p className="mt-4 text-xs font-bold text-[#d6ad63]">{t.warning}</p></div></section>
  </div>
}
