import { Link, createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { BookOpen, CheckCircle2, ShieldCheck } from "lucide-react";
import { clientCreateEditorialCheckout, clientEditorialSubscription, clientSetEditorialCancellation } from "@/lib/editorial-subscription.functions";
import { findEditorialBySlug } from "@/lib/editorial-catalog";

export const Route=createFileRoute("/_clientarea/cliente/biblioteca/publicacoes/$slug")({component:PublicationPage});

function money(c:number,cur:"BRL"|"EUR"){return new Intl.NumberFormat(cur==="BRL"?"pt-BR":"pt-PT",{style:"currency",currency:cur}).format(c/100)}

function PublicationPage(){
  const {slug}=Route.useParams();
  const item=findEditorialBySlug(slug);
  const ctxFn=useServerFn(clientEditorialSubscription),checkoutFn=useServerFn(clientCreateEditorialCheckout),cancelFn=useServerFn(clientSetEditorialCancellation);
  const {data,refetch,isLoading}=useQuery({queryKey:["editorial",item?.productKey],enabled:!!item,queryFn:()=>ctxFn({data:{productKey:item!.productKey}})});
  const checkout=useMutation({mutationFn:()=>checkoutFn({data:{productKey:item!.productKey,market:data?.market==="BR"?"BR":"INTL"}}),onSuccess:r=>location.href=r.url});
  const cancel=useMutation({mutationFn:(v:boolean)=>cancelFn({data:{productKey:item!.productKey,cancelAtPeriodEnd:v}}),onSuccess:()=>refetch()});
  if(!item)return <div className="space-y-4"><Link to="/cliente/biblioteca/publicacoes" className="font-black text-[#0b2341]">← Publicações</Link><p>Publicação não encontrada.</p></div>;
  if(isLoading||!data)return <p>Carregando publicação…</p>;
  const price=data.market==="BR"?money(data.priceBrlCents,"BRL"):money(data.priceEurCents,"EUR");

  if(!data.active)return <div className="space-y-5 pb-10"><div className="flex flex-wrap gap-4"><Link to="/cliente/biblioteca/publicacoes" className="text-sm font-black text-[#0b2341]">← Todas as publicações</Link><Link to="/cliente/biblioteca" className="text-sm font-bold text-slate-500">Minha Biblioteca</Link></div><section className="overflow-hidden rounded-[30px] p-7 text-white shadow-xl sm:p-10" style={{background:`linear-gradient(135deg,${item.color},#071426)`}}><div className="flex items-start justify-between gap-4"><span className="text-5xl">{item.icon}</span><span className="rounded-full bg-white/15 px-3 py-1 text-[10px] font-black uppercase tracking-wider">Assinatura semanal</span></div><p className="mt-8 text-[10px] font-black uppercase tracking-[.25em] text-[#f0c775]">Grupo LDR Essence</p><h1 className="mt-3 max-w-4xl font-serif text-4xl leading-tight sm:text-6xl">{item.title}</h1><p className="mt-4 max-w-3xl text-base leading-7 text-white/75">{item.description}</p><div className="mt-6 flex flex-wrap gap-2">{item.topics.map(t=><span key={t} className="rounded-full bg-white/10 px-3 py-2 text-[10px] font-bold">{t}</span>)}</div><div className="mt-8 rounded-2xl bg-white/10 p-5"><p className="text-xs font-bold uppercase tracking-wider text-white/60">Cobrança recorrente semanal</p><p className="mt-2 text-4xl font-black">{price}<span className="text-sm font-medium text-white/60"> / semana</span></p><p className="mt-2 text-xs text-white/60">Europa {money(item.priceEurCents,"EUR")} · Brasil {money(item.priceBrlCents,"BRL")}</p></div>{item.notice&&<div className="mt-5 flex gap-3 rounded-2xl bg-white/10 p-4 text-sm leading-6 text-white/75"><ShieldCheck className="mt-0.5 h-5 w-5 shrink-0 text-[#f0c775]"/><p>{item.notice}</p></div>}<button disabled={checkout.isPending} onClick={()=>checkout.mutate()} className="mt-7 rounded-xl bg-[#f0c775] px-6 py-3 font-black text-[#35101e] disabled:opacity-60">{checkout.isPending?"ABRINDO CHECKOUT…":"ASSINAR AGORA"}</button><p className="mt-3 text-xs text-white/55">Assinatura independente da Biblioteca LDR. Você pode cancelar para o fim do período semanal.</p></section></div>;

  return <div className="space-y-6 pb-10"><div className="flex flex-wrap items-center justify-between gap-3"><Link to="/cliente/biblioteca/publicacoes" className="text-sm font-black text-[#0b2341]">← Todas as publicações</Link><div className="flex flex-wrap gap-2"><span className="rounded-full bg-emerald-50 px-3 py-1 text-[10px] font-black text-emerald-700"><CheckCircle2 className="mr-1 inline h-3 w-3"/>ASSINATURA ATIVA</span><button onClick={()=>cancel.mutate(!data.subscription?.cancel_at_period_end)} className="rounded-full border px-3 py-1 text-[10px] font-black">{data.subscription?.cancel_at_period_end?"MANTER ASSINATURA":"CANCELAR AO FIM DO PERÍODO"}</button></div></div><article className="overflow-hidden rounded-[30px] border bg-white shadow-xl"><section className="p-8 text-white sm:p-12" style={{background:`linear-gradient(135deg,${item.color},#071426)`}}><p className="text-xs font-black uppercase tracking-[.25em] text-[#f0c775]">EDIÇÃO #01 · SETEMBRO 2026</p><div className="mt-5 flex items-center gap-4"><span className="text-5xl">{item.icon}</span><h1 className="font-serif text-4xl sm:text-6xl">{item.title}</h1></div><p className="mt-5 max-w-3xl text-lg leading-8 text-white/75">{item.subtitle}</p></section><section className="p-7 sm:p-10"><p className="text-[10px] font-black uppercase tracking-[.2em] text-[#a77b2e]">Nesta edição</p><h2 className="mt-2 font-serif text-3xl text-[#0b2341]">Uma leitura semanal para entender, aprender e acompanhar mudanças.</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{item.topics.map((topic,i)=><div key={topic} className="rounded-2xl border bg-slate-50 p-5"><p className="text-[10px] font-black uppercase tracking-wider text-[#a77b2e]">Bloco {i+1}</p><h3 className="mt-2 font-serif text-2xl text-[#0b2341]">{topic}</h3><p className="mt-2 text-sm leading-6 text-slate-600">Conteúdo editorial preparado para contextualizar o tema, destacar pontos principais e indicar fontes quando a pauta exigir verificação oficial ou científica.</p></div>)}</div>{item.notice&&<div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900">{item.notice}</div>}</section><section className="bg-[#f7f3e9] p-7 sm:p-10"><BookOpen className="h-6 w-6 text-[#a77b2e]"/><h2 className="mt-3 font-serif text-3xl text-[#0b2341]">Próxima edição</h2><p className="mt-2 text-sm leading-6 text-slate-600">Novas edições são publicadas semanalmente e permanecem no histórico da publicação para assinantes enquanto a assinatura estiver ativa.</p></section></article></div>;
}
