import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useState } from "react";
import { Bell, BookOpen, Building2, CalendarDays, ExternalLink, Gift, LogOut, MessageCircle } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { LanguageSelect, useI18n } from "@/lib/i18n";
import { employeeContext, employeeRequestBenefit } from "@/lib/organization-portal.functions";
import { portalNotifications } from "@/lib/notification-center.functions";

export const Route = createFileRoute("/_portal/funcionario")({ component: EmployeePortal });
type AnyRow = Record<string, any>;
type Locale = "pt"|"en"|"fr"|"es";

const COPY = {
  pt:{title:"Área do Funcionário",signOut:"Sair",loading:"Carregando benefícios…",loadError:"Não foi possível carregar seus benefícios.",unlinkedTitle:"Acesso ainda não vinculado",unlinkedText:"Não localizamos seu e-mail na lista de funcionários de uma empresa. Peça ao responsável da empresa para cadastrar exatamente o e-mail desta conta Google.",blockedTitle:"Benefício temporariamente inativo",blockedText:"Seu cadastro existe, mas a empresa desativou o acesso aos benefícios. Fale com o responsável da sua empresa.",eyebrow:"Seus benefícios",hello:"Olá",intro:"Aqui aparecem somente os serviços que sua empresa comprou e atribuiu a você.",noneTitle:"Nenhum benefício liberado ainda",noneText:"Quando sua empresa concluir uma compra e selecionar você como beneficiário, o serviço aparecerá aqui automaticamente.",available:"Disponível",requested:"Solicitado",used:"Utilizado",benefit:"Benefício",credits:"crédito(s) disponível(is)",requestSuccess:"Solicitação enviada. A equipe poderá seguir com o agendamento.",requestError:"Não foi possível solicitar.",sending:"Enviando…",use:"Usar / solicitar benefício",requestedText:"Sua solicitação já foi registrada e está aguardando organização do atendimento.",noCredit:"Este benefício não possui crédito disponível para nova solicitação.",commitment:"Você tem um compromisso com o seu benefício",commitmentText:"Quando houver crédito disponível, use o serviço e acompanhe sua agenda. Cuidar do seu benefício também faz parte do compromisso assumido com você.",quick:"Acessos rápidos",hire:"Contratar e agendar",hireText:"Use um benefício da empresa ou conheça serviços individuais.",agenda:"Minha agenda",agendaText:"Veja atendimentos já marcados.",ebook:"E-book e biblioteca",ebookText:"Conheça A Coragem de Começar e os conteúdos para empreendedores.",ecosystem:"Ecossistema LDR",ecosystemText:"Acesse serviços, soluções e outras páginas do Grupo LDR Essence.",notifications:"Notificações",noNotifications:"Nenhuma notificação nova.",noAgenda:"Nenhum atendimento agendado no momento.",individual:"Ver serviços individuais"},
  en:{title:"Employee Area",signOut:"Sign out",loading:"Loading benefits…",loadError:"Could not load your benefits.",unlinkedTitle:"Access not linked yet",unlinkedText:"We could not find your email in a company's employee list. Ask the company administrator to register the exact email used by this Google account.",blockedTitle:"Benefit temporarily inactive",blockedText:"Your registration exists, but the company has disabled access to benefits. Contact your company administrator.",eyebrow:"Your benefits",hello:"Hello",intro:"Only services purchased by your company and assigned to you appear here.",noneTitle:"No benefits available yet",noneText:"When your company completes a purchase and selects you as a beneficiary, the service will appear here automatically.",available:"Available",requested:"Requested",used:"Used",benefit:"Benefit",credits:"credit(s) available",requestSuccess:"Request sent. The team can now organize the appointment.",requestError:"Could not send the request.",sending:"Sending…",use:"Use / request benefit",requestedText:"Your request has already been registered and is waiting for the service to be organized.",noCredit:"This benefit has no credit available for a new request.",commitment:"You have a commitment to use your benefit",commitmentText:"When credit is available, use the service and follow your schedule. Making use of your benefit is part of the commitment made for your wellbeing.",quick:"Quick access",hire:"Buy and schedule",hireText:"Use a company benefit or explore individual services.",agenda:"My schedule",agendaText:"See services already scheduled.",ebook:"E-book and library",ebookText:"Discover A Coragem de Começar and entrepreneur content.",ecosystem:"LDR Ecosystem",ecosystemText:"Access Grupo LDR Essence services, solutions and other pages.",notifications:"Notifications",noNotifications:"No new notifications.",noAgenda:"No service scheduled right now.",individual:"View individual services"},
  fr:{title:"Espace Collaborateur",signOut:"Se déconnecter",loading:"Chargement des avantages…",loadError:"Impossible de charger vos avantages.",unlinkedTitle:"Accès pas encore associé",unlinkedText:"Votre e-mail n’a pas été trouvé dans la liste des collaborateurs d’une entreprise. Demandez au responsable d’enregistrer exactement l’adresse e-mail de ce compte Google.",blockedTitle:"Avantage temporairement inactif",blockedText:"Votre inscription existe, mais l’entreprise a désactivé l’accès aux avantages. Contactez le responsable de votre entreprise.",eyebrow:"Vos avantages",hello:"Bonjour",intro:"Seuls les services achetés par votre entreprise et qui vous sont attribués apparaissent ici.",noneTitle:"Aucun avantage disponible pour le moment",noneText:"Lorsque votre entreprise finalise un achat et vous sélectionne comme bénéficiaire, le service apparaît automatiquement ici.",available:"Disponible",requested:"Demandé",used:"Utilisé",benefit:"Avantage",credits:"crédit(s) disponible(s)",requestSuccess:"Demande envoyée. L’équipe peut maintenant organiser le rendez-vous.",requestError:"Impossible d’envoyer la demande.",sending:"Envoi…",use:"Utiliser / demander l’avantage",requestedText:"Votre demande est déjà enregistrée et attend l’organisation du service.",noCredit:"Cet avantage ne dispose plus de crédit pour une nouvelle demande.",commitment:"Vous avez un engagement envers votre avantage",commitmentText:"Lorsqu’un crédit est disponible, utilisez le service et consultez votre agenda. Profiter de l’avantage fait partie de l’engagement pris pour vous.",quick:"Accès rapides",hire:"Souscrire et planifier",hireText:"Utilisez un avantage de l’entreprise ou découvrez les services individuels.",agenda:"Mon agenda",agendaText:"Consultez les prestations déjà planifiées.",ebook:"E-book et bibliothèque",ebookText:"Découvrez A Coragem de Começar et les contenus pour entrepreneurs.",ecosystem:"Écosystème LDR",ecosystemText:"Accédez aux services, solutions et autres pages du Grupo LDR Essence.",notifications:"Notifications",noNotifications:"Aucune nouvelle notification.",noAgenda:"Aucune prestation planifiée pour le moment.",individual:"Voir les services individuels"},
  es:{title:"Área del Empleado",signOut:"Salir",loading:"Cargando beneficios…",loadError:"No fue posible cargar tus beneficios.",unlinkedTitle:"Acceso aún no vinculado",unlinkedText:"No encontramos tu correo en la lista de empleados de una empresa. Pide al responsable que registre exactamente el correo de esta cuenta de Google.",blockedTitle:"Beneficio temporalmente inactivo",blockedText:"Tu registro existe, pero la empresa desactivó el acceso a los beneficios. Habla con el responsable de tu empresa.",eyebrow:"Tus beneficios",hello:"Hola",intro:"Aquí aparecen únicamente los servicios que tu empresa compró y te asignó.",noneTitle:"Aún no hay beneficios disponibles",noneText:"Cuando tu empresa complete una compra y te seleccione como beneficiario, el servicio aparecerá aquí automáticamente.",available:"Disponible",requested:"Solicitado",used:"Utilizado",benefit:"Beneficio",credits:"crédito(s) disponible(s)",requestSuccess:"Solicitud enviada. El equipo podrá organizar la cita.",requestError:"No fue posible enviar la solicitud.",sending:"Enviando…",use:"Usar / solicitar beneficio",requestedText:"Tu solicitud ya fue registrada y está esperando la organización del servicio.",noCredit:"Este beneficio no tiene crédito disponible para una nueva solicitud.",commitment:"Tienes un compromiso con tu beneficio",commitmentText:"Cuando tengas crédito disponible, usa el servicio y revisa tu agenda. Aprovechar el beneficio forma parte del compromiso asumido contigo.",quick:"Accesos rápidos",hire:"Contratar y agendar",hireText:"Usa un beneficio de la empresa o conoce servicios individuales.",agenda:"Mi agenda",agendaText:"Consulta los servicios ya programados.",ebook:"E-book y biblioteca",ebookText:"Conoce A Coragem de Começar y los contenidos para emprendedores.",ecosystem:"Ecosistema LDR",ecosystemText:"Accede a servicios, soluciones y otras páginas de Grupo LDR Essence.",notifications:"Notificaciones",noNotifications:"No hay notificaciones nuevas.",noAgenda:"No hay servicios programados en este momento.",individual:"Ver servicios individuales"}
} as const;

const SERVICE_NAMES: Record<string, Record<string,string>> = {
  massagem_laboral_10_eu:{pt:"Massagem Laboral — 10 min",en:"Workplace Massage — 10 min",fr:"Massage en entreprise — 10 min",es:"Masaje Laboral — 10 min"},massagem_laboral_15_eu:{pt:"Massagem Laboral — 15 min",en:"Workplace Massage — 15 min",fr:"Massage en entreprise — 15 min",es:"Masaje Laboral — 15 min"},massagem_laboral_20_eu:{pt:"Massagem Laboral — 20 min",en:"Workplace Massage — 20 min",fr:"Massage en entreprise — 20 min",es:"Masaje Laboral — 20 min"},massagem_laboral_30_eu:{pt:"Massagem Laboral — 30 min",en:"Workplace Massage — 30 min",fr:"Massage en entreprise — 30 min",es:"Masaje Laboral — 30 min"},massagem_laboral_40_eu:{pt:"Massagem Laboral — até 40 min",en:"Workplace Massage — up to 40 min",fr:"Massage en entreprise — jusqu’à 40 min",es:"Masaje Laboral — hasta 40 min"},orientacao_profissional_eu:{pt:"Orientação profissional",en:"Career guidance",fr:"Orientation professionnelle",es:"Orientación profesional"},orientacao_profissional_br:{pt:"Orientação profissional",en:"Career guidance",fr:"Orientation professionnelle",es:"Orientación profesional"},plano_carreira_eu:{pt:"Diagnóstico de Carreira + Plano Profissional",en:"Career Assessment + Professional Plan",fr:"Diagnostic de carrière + Plan professionnel",es:"Diagnóstico de carrera + Plan profesional"},plano_carreira_br:{pt:"Diagnóstico de Carreira + Plano Profissional",en:"Career Assessment + Professional Plan",fr:"Diagnostic de carrière + Plan professionnel",es:"Diagnóstico de carrera + Plan profesional"},transicao_carreira_eu:{pt:"Transição de carreira",en:"Career transition",fr:"Transition de carrière",es:"Transición de carrera"},transicao_carreira_br:{pt:"Transição de carreira",en:"Career transition",fr:"Transition de carrière",es:"Transición de carrera"},carreira_internacional_eu:{pt:"Carreira Internacional",en:"International Career",fr:"Carrière internationale",es:"Carrera internacional"},carreira_internacional_br:{pt:"Carreira Internacional",en:"International Career",fr:"Carrière internationale",es:"Carrera internacional"},mentoria_sessao:{pt:"Sessão Individual de Mentoria",en:"Individual Mentorship Session",fr:"Séance individuelle de mentorat",es:"Sesión individual de mentoría"},mentoria_4:{pt:"Mentoria — 4 sessões",en:"Mentorship — 4 sessions",fr:"Mentorat — 4 séances",es:"Mentoría — 4 sesiones"},mentoria_8:{pt:"Mentoria — 8 sessões",en:"Mentorship — 8 sessions",fr:"Mentorat — 8 séances",es:"Mentoría — 8 sesiones"},psicanalise_clinica_eu:{pt:"Psicanálise Clínica — Sessão Online",en:"Clinical Psychoanalysis — Online Session",fr:"Psychanalyse clinique — Séance en ligne",es:"Psicoanálisis clínico — Sesión online"},psicanalise_clinica_br:{pt:"Psicanálise Clínica — Sessão Online",en:"Clinical Psychoanalysis — Online Session",fr:"Psychanalyse clinique — Séance en ligne",es:"Psicoanálisis clínico — Sesión online"}
};
const INTL:Record<Locale,string>={pt:"pt-PT",en:"en-GB",fr:"fr-FR",es:"es-ES"};

function EmployeePortal(){
  const {locale}=useI18n(); const copy=COPY[locale]; const navigate=useNavigate();
  const getContext=useServerFn(employeeContext); const requestBenefit=useServerFn(employeeRequestBenefit); const getNotifications=useServerFn(portalNotifications);
  const [data,setData]=useState<any>(null); const [notifications,setNotifications]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [busyId,setBusyId]=useState<string|null>(null);
  async function load(){setLoading(true);try{const [ctx,notes]=await Promise.all([getContext(),getNotifications()]);setData(ctx);setNotifications(notes as any[]);}catch{toast.error(copy.loadError);}finally{setLoading(false);}}
  useEffect(()=>{void load();},[]);
  async function signOut(){await supabase.auth.signOut();navigate({to:"/funcionario/login",replace:true});}
  const serviceName=(b:AnyRow)=>SERVICE_NAMES[b.catalog_key]?.[locale]??b.service?.name??copy.benefit;
  if(loading)return <div className="min-h-screen p-6"><div className="s8-card mx-auto max-w-md text-center">{copy.loading}</div></div>;
  const scheduled=(data?.benefits??[]).filter((b:AnyRow)=>b.scheduled_at).sort((a:AnyRow,b:AnyRow)=>new Date(a.scheduled_at).getTime()-new Date(b.scheduled_at).getTime());
  return <div className="min-h-screen" style={{background:"var(--cream)"}}>
    <header className="sticky top-0 z-30 text-primary-foreground shadow-sm" style={{background:"linear-gradient(135deg, var(--wine-deep), var(--wine))"}}><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-4 py-4 sm:px-6"><div className="min-w-0"><p className="break-words font-serif text-xl sm:text-2xl">Grupo LDR Essence</p><p className="text-xs opacity-80">{copy.title}</p></div><div className="flex flex-wrap items-center gap-3"><LanguageSelect/><button type="button" onClick={signOut} className="flex items-center gap-2 rounded-lg border border-white/30 px-3 py-2 text-sm font-bold"><LogOut className="h-4 w-4"/>{copy.signOut}</button></div></div></header>
    <main className="mx-auto max-w-6xl px-4 py-7 sm:px-6">
      {data?.status==="unlinked"?<Message title={copy.unlinkedTitle} text={copy.unlinkedText}/>:data?.status==="blocked"?<Message title={copy.blockedTitle} text={copy.blockedText}/>:<>
        <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.18em] text-muted-foreground">{copy.eyebrow}</p><h1 className="mt-1 font-serif text-3xl sm:text-4xl">{copy.hello}, {data?.member?.full_name}</h1><p className="mt-2 text-sm text-muted-foreground">{copy.intro}</p></div>{data?.organization?.name&&<span className="flex items-center gap-2 rounded-full bg-primary/10 px-3 py-2 text-xs font-bold text-primary"><Building2 className="h-4 w-4"/>{data.organization.name}</span>}</div>
        <section className="mt-6 rounded-2xl border border-primary/20 bg-primary/5 p-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-primary">{copy.commitment}</p><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{copy.commitmentText}</p></section>
        <section className="mt-6"><h2 className="mb-3 font-serif text-xl">{copy.quick}</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Quick icon={MessageCircle} href="#beneficios" title={copy.hire} text={copy.hireText}/><Quick icon={CalendarDays} href="#agenda" title={copy.agenda} text={copy.agendaText}/><Quick icon={BookOpen} href="https://www.lucianoempreendendor.com/" title={copy.ebook} text={copy.ebookText} external/><Quick icon={ExternalLink} href="https://ldrrhestrategia.com/" title={copy.ecosystem} text={copy.ecosystemText} external/></div></section>
        <section id="beneficios" className="mt-7 grid gap-4 sm:grid-cols-2">{(data?.benefits??[]).length===0?<div className="s8-card sm:col-span-2"><Gift className="h-6 w-6 text-primary"/><h2 className="mt-3 font-serif text-2xl">{copy.noneTitle}</h2><p className="mt-2 text-sm text-muted-foreground">{copy.noneText}</p><a href={`https://ldrrhestrategia.com/solucoes?lang=${locale}`} target="_blank" rel="noreferrer" className="mt-4 inline-block rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground">{copy.individual}</a></div>:(data.benefits as AnyRow[]).map(b=>{const remaining=Math.max(Number(b.credits_granted)-Number(b.credits_used),0);const assigned=b.status==="assigned";const status=b.status==="assigned"?copy.available:b.status==="requested"?copy.requested:b.status==="used"?copy.used:b.status;return <article key={b.id} className="s8-card min-w-0"><div className="flex items-start justify-between gap-3"><span className="rounded-2xl bg-primary/10 p-3 text-primary"><Gift className="h-5 w-5"/></span><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-bold">{status}</span></div><h2 className="mt-4 break-words font-serif text-2xl">{serviceName(b)}</h2><div className="mt-3 rounded-xl bg-primary/5 p-3"><p className="text-sm"><strong>{remaining}</strong> / {b.credits_granted} {copy.credits}</p></div>{b.scheduled_at&&<p className="mt-3 rounded-lg border p-3 text-sm"><strong>{copy.agenda}:</strong> {new Date(b.scheduled_at).toLocaleString(INTL[locale])}</p>}{assigned&&remaining>0?<button type="button" disabled={busyId===b.id} onClick={async()=>{setBusyId(b.id);try{await requestBenefit({data:{benefitId:b.id}});toast.success(copy.requestSuccess);await load();}catch{toast.error(copy.requestError);}finally{setBusyId(null);}}} className="mt-4 w-full rounded-xl bg-primary px-4 py-3 text-sm font-bold text-primary-foreground disabled:opacity-60">{busyId===b.id?copy.sending:copy.use}</button>:<p className="mt-4 text-xs text-muted-foreground">{b.status==="requested"?copy.requestedText:copy.noCredit}</p>}</article>})}</section>
        <section id="agenda" className="s8-card mt-7"><div className="flex items-center gap-3"><CalendarDays className="h-5 w-5 text-primary"/><h2 className="font-serif text-2xl">{copy.agenda}</h2></div><div className="mt-4 space-y-2">{scheduled.length===0?<p className="text-sm text-muted-foreground">{copy.noAgenda}</p>:scheduled.map((b:AnyRow)=><div key={b.id} className="rounded-xl border bg-card p-4"><p className="font-bold">{serviceName(b)}</p><p className="mt-1 text-sm text-muted-foreground">{new Date(b.scheduled_at).toLocaleString(INTL[locale])}</p>{b.scheduled_note&&<p className="mt-2 text-xs text-muted-foreground">{b.scheduled_note}</p>}</div>)}</div></section>
        <section className="s8-card mt-7"><div className="flex items-center gap-3"><Bell className="h-5 w-5 text-primary"/><h2 className="font-serif text-2xl">{copy.notifications}</h2></div><div className="mt-4 space-y-2">{notifications.length===0?<p className="text-sm text-muted-foreground">{copy.noNotifications}</p>:notifications.slice(0,8).map(n=><div key={n.id} className="rounded-xl border bg-card p-4"><p className="text-sm font-bold">{n.subject||n.event_type}</p><p className="mt-1 text-sm text-muted-foreground">{n.body}</p></div>)}</div></section>
      </>}
    </main>
  </div>;
}
function Quick({icon:Icon,href,title,text,external}:{icon:any;href:string;title:string;text:string;external?:boolean}){return <a href={href} target={external?"_blank":undefined} rel={external?"noreferrer":undefined} className="s8-card block min-w-0 transition hover:-translate-y-0.5 hover:shadow-md"><Icon className="h-6 w-6 text-primary"/><h3 className="mt-3 break-words font-bold">{title}</h3><p className="mt-1 break-words text-sm text-muted-foreground">{text}</p></a>}
function Message({title,text}:{title:string;text:string}){return <section className="s8-card mx-auto max-w-2xl text-center"><h1 className="font-serif text-3xl">{title}</h1><p className="mx-auto mt-3 max-w-xl text-sm leading-6 text-muted-foreground">{text}</p></section>}
