import { useEffect,useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { addEcosystemAdminReply,getEcosystemAttachmentUrl,getEcosystemContactThread,listEcosystemContacts,updateEcosystemContact } from "@/lib/ecosystem-support.functions";

export const Route=createFileRoute("/admin/contatos")({component:Contacts});
function Contacts(){
 const list=useServerFn(listEcosystemContacts),threadFn=useServerFn(getEcosystemContactThread),urlFn=useServerFn(getEcosystemAttachmentUrl),replyFn=useServerFn(addEcosystemAdminReply),updateFn=useServerFn(updateEcosystemContact);
 const [items,setItems]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[reply,setReply]=useState(""),[notice,setNotice]=useState("");
 async function load(){setItems(await list())} useEffect(()=>{void load()},[]);
 async function open(id:string){setNotice("");setSelected(await threadFn({data:{id}}))}
 async function attachment(id:string){const url=await urlFn({data:{id}});window.open(url,"_blank","noopener,noreferrer")}
 async function send(){if(!selected||!reply.trim())return;const r=await replyFn({data:{contactId:selected.contact.id,body:reply}});setReply("");setNotice(r.emailSent?"Resposta enviada e registrada.":`Resposta registrada para ${r.email}. O envio externo por e-mail ainda não está conectado; nenhum e-mail foi falsamente marcado como enviado.`);await open(selected.contact.id);await load()}
 async function status(next:string){if(!selected)return;await updateFn({data:{id:selected.contact.id,status:next,priority:selected.contact.priority||"normal"}});await open(selected.contact.id);await load()}
 return <main className="min-h-screen bg-slate-50 p-5"><div className="mx-auto max-w-7xl"><h1 className="text-3xl font-bold text-[#07345b]">Atendimento do Ecossistema</h1><p className="mt-2 text-slate-600">Protocolos, histórico e documentos privados.</p><div className="mt-6 grid gap-5 lg:grid-cols-[360px_1fr]"><aside className="space-y-3">{items.map(x=><button key={x.id} onClick={()=>void open(x.id)} className="w-full rounded-2xl bg-white p-4 text-left shadow-sm"><strong>{x.protocol}</strong><div className="mt-1 truncate text-sm">{x.subject}</div><div className="text-xs text-slate-500">{x.email} · {x.status}</div></button>)}</aside><section className="rounded-2xl bg-white p-5 shadow-sm">{!selected?<p>Selecione um protocolo.</p>:<><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">{selected.contact.protocol} · {selected.contact.subject}</h2><p className="text-sm text-slate-600">{selected.contact.name} · {selected.contact.email}</p></div><select value={selected.contact.status} onChange={e=>void status(e.target.value)} className="rounded-xl border p-2"><option value="novo">Novo</option><option value="em_atendimento">Em atendimento</option><option value="aguardando_cliente">Aguardando cliente</option><option value="respondido">Respondido</option><option value="resolvido">Resolvido</option></select></div><div className="mt-5 rounded-xl bg-slate-50 p-4 whitespace-pre-wrap">{selected.contact.message}</div>{selected.attachments.length>0&&<div className="mt-5"><h3 className="font-bold">Documentos</h3><div className="mt-2 flex flex-wrap gap-2">{selected.attachments.map((a:any)=><button key={a.id} onClick={()=>void attachment(a.id)} className="rounded-xl border px-3 py-2 text-sm">{a.original_name}</button>)}</div></div>}<div className="mt-6 space-y-3">{selected.messages.map((m:any)=><div key={m.id} className={`rounded-xl p-3 ${m.direction==="outbound"?"bg-blue-50":"bg-slate-50"}`}><div className="text-xs font-bold uppercase">{m.direction==="outbound"?"LDR":"Entrada"}</div><div className="mt-1 whitespace-pre-wrap">{m.body}</div></div>)}</div><div className="mt-6"><textarea value={reply} onChange={e=>setReply(e.target.value)} rows={5} maxLength={10000} placeholder="Escreva a resposta..." className="w-full rounded-xl border p-3"/><button onClick={()=>void send()} className="mt-3 rounded-xl bg-[#07345b] px-5 py-3 font-bold text-white">Registrar resposta</button>{notice&&<p role="status" className="mt-3 rounded-xl bg-amber-50 p-3 text-sm">{notice}</p>}</div></>}</section></div></div></main>
}