import { useEffect,useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { MapPin,ShieldCheck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { LanguageSelect,useI18n } from "@/lib/i18n";
export const Route=createFileRoute("/carreira/vagas/$jobId")({component:Job});
const C={pt:{about:"Sobre a vaga",resp:"Responsabilidades",req:"Requisitos mínimos",apply:"Candidatar-me",closed:"Vaga indisponível ou não publicada.",safe:"Esta vaga passou pela etapa de publicação da plataforma."},en:{about:"About the job",resp:"Responsibilities",req:"Minimum requirements",apply:"Apply",closed:"Job unavailable or not published.",safe:"This job passed the platform publication stage."},fr:{about:"À propos du poste",resp:"Responsabilités",req:"Exigences minimales",apply:"Postuler",closed:"Offre indisponible ou non publiée.",safe:"Cette offre a passé l’étape de publication de la plateforme."},es:{about:"Sobre la vacante",resp:"Responsabilidades",req:"Requisitos mínimos",apply:"Postularme",closed:"Vacante no disponible o no publicada.",safe:"Esta vacante pasó por la etapa de publicación de la plataforma."}} as const;
function Job(){const{jobId}=Route.useParams();const{locale}=useI18n();const t=C[locale];const[j,setJ]=useState<any>();useEffect(()=>{void(async()=>{const{data}=await(supabase.from("career_jobs" as never)as any).select("id,title,description,responsibilities,requirements,country,city,work_mode,contract_type,publication_language,required_languages,salary_currency,salary_min,salary_max,salary_period,career_companies(name,website)").eq("id",jobId).eq("status","published").maybeSingle();setJ(data??null)})()},[jobId]);if(j===null)return <main className="min-h-screen bg-slate-50 p-8"><div className="mx-auto max-w-3xl rounded-2xl bg-white p-6">{t.closed}</div></main>;if(!j)return null;return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-4xl px-5 py-10"><div className="flex justify-end"><LanguageSelect/></div><article className="mt-5 rounded-3xl bg-white p-6 shadow-sm md:p-9"><p className="font-semibold text-[#c28d19]">{j.career_companies?.name}</p><h1 className="mt-2 text-3xl font-bold text-[#07345b] md:text-4xl">{j.title}</h1><p className="mt-4 flex flex-wrap items-center gap-2 text-slate-600"><MapPin size={18}/>{[j.city,j.country].filter(Boolean).join(", ")} · {j.work_mode} · {j.contract_type}</p><div className="mt-6 flex gap-2 rounded-xl bg-slate-50 p-4 text-sm text-slate-600"><ShieldCheck size={19}/>{t.safe}</div><S title={t.about}>{j.description}</S>{j.responsibilities&&<S title={t.resp}>{j.responsibilities}</S>}<S title={t.req}>{j.requirements}</S><a href={"/carreira/candidatar/"+j.id} className="mt-8 inline-flex min-h-12 items-center justify-center rounded-xl bg-[#07345b] px-6 font-semibold text-white">{t.apply}</a></article></div></main>}
function S({title,children}:{title:string;children:React.ReactNode}){return <section className="mt-8"><h2 className="text-xl font-bold text-[#07345b]">{title}</h2><p className="mt-3 whitespace-pre-line leading-7 text-slate-700">{children}</p></section>}
