import {createFileRoute,Link} from "@tanstack/react-router";
import {useEffect,useState} from "react";
import {BriefcaseBusiness,Users,GraduationCap,Store,ShieldCheck} from "lucide-react";
import {supabase} from "@/integrations/supabase/client";
import {LanguageSelect} from "@/lib/i18n";
export const Route=createFileRoute("/carreira/work")({component:Work});
function Work(){const[user,setUser]=useState<any>();const[prefs,setPrefs]=useState<any>(null);const[saving,setSaving]=useState(false);useEffect(()=>{void(async()=>{const{data}=await supabase.auth.getUser();setUser(data.user??null);if(data.user){const{data:p}=await(supabase.from("ldr_work_preferences" as never)as any).select("*").maybeSingle();setPrefs(p??{active:false,opportunity_types:[],modalities:[],country_codes:[],competency_keys:[]})}})()},[]);
const save=async()=>{if(!user)return;setSaving(true);await(supabase.from("ldr_work_preferences" as never)as any).upsert({user_id:user.id,active:!!prefs?.active,opportunity_types:prefs?.opportunity_types??[],modalities:prefs?.modalities??[],country_codes:prefs?.country_codes??[],competency_keys:prefs?.competency_keys??[],updated_at:new Date().toISOString()});setSaving(false)};
if(user===undefined)return null;return <main className="min-h-screen bg-slate-50 text-slate-900"><div className="mx-auto max-w-5xl px-5 py-10"><div className="flex justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#c99b2d]">LDR Work</p><h1 className="mt-2 text-4xl font-black text-[#07345b]">Quero ganhar dinheiro</h1><p className="mt-2 max-w-2xl text-slate-600">Encontre caminhos de trabalho, projetos e serviços dentro do ecossistema LDR.</p></div><LanguageSelect/></div><div className="mt-6 flex gap-3 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm text-[#07345b]"><ShieldCheck size={20}/><p>A LDR organiza oportunidades, mas não garante contratação nem renda. Projetos produtivos pagos devem seguir as condições informadas em cada oportunidade.</p></div>{!user?<div className="mt-8 rounded-3xl bg-white p-8 shadow-sm"><p>Entre na sua conta para personalizar seus caminhos.</p><a href="/cliente/login?next=%2Fcarreira%2Fwork" className="mt-4 inline-flex rounded-xl bg-[#07345b] px-5 py-3 font-bold text-white">Entrar</a></div>:<><section className="mt-8 rounded-3xl bg-white p-6 shadow-sm"><h2 className="text-xl font-black text-[#07345b]">Preferências de oportunidades</h2><label className="mt-4 flex items-center gap-3 text-sm font-bold"><input type="checkbox" checked={!!prefs?.active} onChange={e=>setPrefs({...prefs,active:e.target.checked})}/> Quero receber caminhos compatíveis com minhas preferências</label><label className="mt-4 block text-sm font-bold">Competências de interesse</label><input value={(prefs?.competency_keys??[]).join(", ")} onChange={e=>setPrefs({...prefs,competency_keys:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)})} placeholder="ex.: liderança, atendimento, dados" className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3"/><button onClick={save} disabled={saving} className="mt-4 rounded-xl bg-[#07345b] px-5 py-3 font-bold text-white disabled:opacity-50">{saving?"Salvando…":"Salvar preferências"}</button></section><div className="mt-8 grid gap-4 sm:grid-cols-2"><Card icon={<BriefcaseBusiness/>} title="Vagas" text="Explore vagas abertas e candidaturas." to="/carreira/oportunidades-para-mim"/><Card icon={<Users/>} title="Projetos e Squads" text="Participe de projetos e equipes multidisciplinares." to="/carreira/squads"/><Card icon={<Store/>} title="Oferecer serviços" text="Use sua atuação profissional dentro da rede LDR." to="/profissionais"/><Card icon={<GraduationCap/>} title="Preparar meu perfil" text="Fortaleça evidências e competências antes de se candidatar." to="/carreira/passaporte"/></div></>}<Link to="/carreira" className="mt-8 inline-flex font-bold text-[#07345b]">← LDR Carreira</Link></div></main>}
function Card({icon,title,text,to}:{icon:any,title:string,text:string,to:string}){return <Link to={to} className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200 transition hover:ring-[#d4b050]"><div className="text-[#c99b2d]">{icon}</div><h2 className="mt-4 text-xl font-black text-[#07345b]">{title}</h2><p className="mt-2 text-sm text-slate-600">{text}</p></Link>}