import { type ReactNode } from "react";
import { createFileRoute, Link, Outlet, useLocation } from "@tanstack/react-router";
import { BriefcaseBusiness, Building2, ClipboardCheck, FileText, Globe2, Search, ShieldCheck, UserRound } from "lucide-react";
import { LanguageSelect, useI18n } from "@/lib/i18n";

export const Route = createFileRoute("/carreira")({
  head: () => ({
    meta: [
      { title: "LDR Carreira | Oportunidades e Talentos" },
      { name: "description", content: "Conectando profissionais e empresas em uma plataforma internacional, inclusiva e gratuita de oportunidades profissionais." },
      { name: "robots", content: "index,follow" },
    ],
  }),
  component: CareerRouterGuard,
});

const copy = {
  pt: {
    brand: "LDR Carreira", badge: "100% gratuito para profissionais e empresas", heroTitle: "Oportunidades encontram talentos, onde quer que estejam.", heroSub: "Conectamos pessoas que procuram oportunidades a empresas que querem encontrar talentos — com uma experiência simples, humana, segura e inclusiva.", free: "Sem mensalidade", privacy: "Dados protegidos", global: "Preparado para oportunidades internacionais", companyTitle: "Área da empresa", companySub: "Publique vagas gratuitamente, organize o processo seletivo e informe condições reais de acessibilidade e inclusão.", jobsTitle: "Vagas abertas", jobsSub: "Consulte oportunidades publicadas na LDR Carreira e prepare sua candidatura com mais segurança.", applicationsTitle: "Candidaturas e triagem", applicationsSub: "Acompanhe candidaturas, organize etapas e use critérios responsáveis para reduzir erros no processo seletivo.", guideTitle: "Guia de triagem responsável", guideSub: "Orientações para uma seleção ética, inclusiva e baseada em critérios claros.", verified: "Ambiente LDR Carreira", candidate: "Sou profissional", company: "Sou empresa", publish: "Publicar vaga", seeJobs: "Ver vagas abertas", seeApplications: "Acessar candidaturas", openGuide: "Abrir guia", companyPanel: "Entrar no painel da empresa", back: "Voltar para LDR Carreira", proof: "Escolha uma ação abaixo para continuar.", loginNeeded: "Entre com Google para publicar uma vaga.", login: "Entrar para publicar", saved: "Vaga salva. A publicação pública depende de validação da LDR.", error: "Não foi possível salvar agora. Confira os campos obrigatórios.", companyName: "Empresa", email: "E-mail profissional", country: "País", city: "Cidade", jobTitle: "Título da vaga", category: "Categoria", description: "Descrição da vaga", saveDraft: "Salvar rascunho", sendReview: "Enviar para análise"
  },
  en: {
    brand: "LDR Career", badge: "100% free for professionals and companies", heroTitle: "Opportunities meet talent, wherever they are.", heroSub: "We connect people looking for opportunities with companies looking for talent — through a simple, human, secure and inclusive experience.", free: "No subscription", privacy: "Protected data", global: "Ready for international opportunities", companyTitle: "Company area", companySub: "Post jobs for free, organize the selection process and state real accessibility and inclusion conditions.", jobsTitle: "Open jobs", jobsSub: "Browse opportunities published on LDR Career and prepare your application more safely.", applicationsTitle: "Applications and screening", applicationsSub: "Track applications, organize steps and use responsible criteria to reduce selection-process errors.", guideTitle: "Responsible screening guide", guideSub: "Guidelines for ethical, inclusive selection based on clear criteria.", verified: "LDR Career environment", candidate: "I'm a professional", company: "I'm a company", publish: "Post a job", seeJobs: "See open jobs", seeApplications: "Access applications", openGuide: "Open guide", companyPanel: "Enter company panel", back: "Back to LDR Career", proof: "Choose an action below to continue.", loginNeeded: "Sign in with Google to post a job.", login: "Sign in to post", saved: "Job saved. Public publication requires LDR validation.", error: "Unable to save now. Check the required fields.", companyName: "Company", email: "Professional email", country: "Country", city: "City", jobTitle: "Job title", category: "Category", description: "Job description", saveDraft: "Save draft", sendReview: "Submit for review"
  },
  fr: {
    brand: "LDR Carrière", badge: "100 % gratuit pour les professionnels et les entreprises", heroTitle: "Les opportunités rencontrent les talents, où qu’ils soient.", heroSub: "Nous mettons en relation les personnes à la recherche d’opportunités et les entreprises à la recherche de talents, dans une expérience simple, humaine, sécurisée et inclusive.", free: "Sans abonnement", privacy: "Données protégées", global: "Prêt pour les opportunités internationales", companyTitle: "Espace entreprise", companySub: "Publiez gratuitement des offres, organisez le processus de sélection et indiquez les conditions réelles d’accessibilité et d’inclusion.", jobsTitle: "Offres ouvertes", jobsSub: "Consultez les opportunités publiées sur LDR Carrière et préparez votre candidature avec plus de sécurité.", applicationsTitle: "Candidatures et triage", applicationsSub: "Suivez les candidatures, organisez les étapes et utilisez des critères responsables.", guideTitle: "Guide de triage responsable", guideSub: "Orientations pour une sélection éthique, inclusive et fondée sur des critères clairs.", verified: "Environnement LDR Carrière", candidate: "Je suis professionnel", company: "Je suis une entreprise", publish: "Publier une offre", seeJobs: "Voir les offres", seeApplications: "Accéder aux candidatures", openGuide: "Ouvrir le guide", companyPanel: "Entrer dans le panneau entreprise", back: "Retour à LDR Carrière", proof: "Choisissez une action ci-dessous pour continuer.", loginNeeded: "Connectez-vous avec Google pour publier une offre.", login: "Se connecter pour publier", saved: "Offre enregistrée. La publication publique nécessite une validation LDR.", error: "Impossible d’enregistrer maintenant. Vérifiez les champs obligatoires.", companyName: "Entreprise", email: "E-mail professionnel", country: "Pays", city: "Ville", jobTitle: "Titre du poste", category: "Catégorie", description: "Description de l’offre", saveDraft: "Enregistrer le brouillon", sendReview: "Envoyer pour validation"
  },
  es: {
    brand: "LDR Carrera", badge: "100% gratuito para profesionales y empresas", heroTitle: "Las oportunidades encuentran talento, dondequiera que esté.", heroSub: "Conectamos personas que buscan oportunidades con empresas que buscan talento, mediante una experiencia sencilla, humana, segura e inclusiva.", free: "Sin mensualidad", privacy: "Datos protegidos", global: "Preparado para oportunidades internacionales", companyTitle: "Área de empresa", companySub: "Publica vacantes gratis, organiza el proceso de selección e informa condiciones reales de accesibilidad e inclusión.", jobsTitle: "Vacantes abiertas", jobsSub: "Consulta oportunidades publicadas en LDR Carrera y prepara tu candidatura con más seguridad.", applicationsTitle: "Candidaturas y selección", applicationsSub: "Acompaña candidaturas, organiza etapas y usa criterios responsables.", guideTitle: "Guía de selección responsable", guideSub: "Orientaciones para una selección ética, inclusiva y basada en criterios claros.", verified: "Ambiente LDR Carrera", candidate: "Soy profesional", company: "Soy empresa", publish: "Publicar vacante", seeJobs: "Ver vacantes", seeApplications: "Acceder a candidaturas", openGuide: "Abrir guía", companyPanel: "Entrar al panel de empresa", back: "Volver a LDR Carrera", proof: "Elige una acción abajo para continuar.", loginNeeded: "Inicia sesión con Google para publicar una vacante.", login: "Entrar para publicar", saved: "Vacante guardada. La publicación pública requiere validación LDR.", error: "No fue posible guardar ahora. Revisa los campos obligatorios.", companyName: "Empresa", email: "Correo profesional", country: "País", city: "Ciudad", jobTitle: "Título", category: "Categoría", description: "Descripción de la vacante", saveDraft: "Guardar borrador", sendReview: "Enviar a revisión"
  },
} as const;

const professionalModules = {
  pt: [["Passaporte profissional","/carreira/passaporte"],["Minha Jornada","/carreira/minha-jornada"],["Oportunidades para mim","/carreira/oportunidades-para-mim"],["Meu desenvolvimento","/carreira/meu-desenvolvimento"],["Meu Futuro","/carreira/meu-futuro"]],
  en: [["Professional Passport","/carreira/passaporte"],["My Journey","/carreira/minha-jornada"],["Opportunities for me","/carreira/oportunidades-para-mim"],["My development","/carreira/meu-desenvolvimento"],["My Future","/carreira/meu-futuro"]],
  fr: [["Passeport professionnel","/carreira/passaporte"],["Mon parcours","/carreira/minha-jornada"],["Opportunités pour moi","/carreira/oportunidades-para-mim"],["Mon développement","/carreira/meu-desenvolvimento"],["Mon avenir","/carreira/meu-futuro"]],
  es: [["Pasaporte profesional","/carreira/passaporte"],["Mi Jornada","/carreira/minha-jornada"],["Oportunidades para mí","/carreira/oportunidades-para-mim"],["Mi desarrollo","/carreira/meu-desenvolvimento"],["Mi futuro","/carreira/meu-futuro"]],
} as const;

type Locale = keyof typeof copy;

function CareerRouterGuard() {
  const { pathname } = useLocation();
  const { locale } = useI18n();
  const t = copy[locale as Locale] ?? copy.pt;
  return <div data-career-page>{pathname.replace(/\/+$/, "") === "/carreira" ? <Landing t={t} locale={locale as Locale} /> : <Outlet />}</div>;
}

function Header({ t }: { t: (typeof copy)[Locale] }) {
  return <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4"><Link reloadDocument to="/carreira" className="flex items-center gap-3 font-semibold text-[#07345b]"><BriefcaseBusiness aria-hidden="true" /> {t.brand}</Link><LanguageSelect /></div></header>;
}

function Landing({ t, locale }: { t: (typeof copy)[Locale]; locale: Locale }) {
  return <main className="min-h-screen bg-[#f8fafc] pb-28 text-slate-900"><Header t={t} /><section className="bg-gradient-to-br from-[#031d34] via-[#07345b] to-[#0b477a] text-white"><div className="mx-auto max-w-6xl px-5 py-16 md:py-24"><span className="inline-flex rounded-full bg-white px-4 py-2 text-sm font-bold text-[#07345b] shadow-sm">{t.badge}</span><h1 className="mt-6 max-w-4xl text-4xl font-black tracking-tight text-white md:text-6xl">{t.heroTitle}</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-white/90">{t.heroSub}</p><div className="mt-8 flex flex-wrap gap-3 text-sm">{[t.free, t.privacy, t.global].map((item) => <span key={item} className="rounded-full bg-white/14 px-4 py-2 text-white">✓ {item}</span>)}</div></div></section><section className="mx-auto grid max-w-6xl gap-5 px-5 py-12 md:grid-cols-3"><ActionCard icon={<UserRound />} title={t.candidate} to="/carreira/vagas" /><ActionCard icon={<Building2 />} title={t.company} to="/carreira/empresa" /><ActionCard icon={<Search />} title={t.jobsTitle} to="/carreira/vagas" /></section><section className="mx-auto max-w-6xl px-5 pb-12"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{professionalModules[locale].map(([title,to])=><Link key={to} to={to} className="flex min-h-16 items-center justify-center rounded-2xl border border-slate-200 bg-white px-4 text-center text-sm font-bold text-[#07345b] shadow-sm transition hover:border-[#d4b050]">{title}</Link>)}</div></section></main>;
}

function ActionCard({ icon, title, to }: { icon: ReactNode; title: string; to: string }) { return <Link reloadDocument to={to} className="rounded-3xl border border-slate-200 bg-white p-6 text-[#07345b] shadow-sm transition hover:-translate-y-0.5 hover:border-[#d4b050]"><div className="mb-4 text-[#07345b]">{icon}</div><strong className="text-xl">{title}</strong></Link>; }
