import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { BriefcaseBusiness, CheckCircle2, Info, MapPin, ShieldCheck } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { LanguageSelect, useI18n } from "@/lib/i18n";

export const Route=createFileRoute("/carreira/oportunidades-para-mim")({component:SmartOpportunities});
const C={
pt:{title:"Oportunidades para mim",sub:"Vagas organizadas pelas evidências do seu Passaporte Profissional.",login:"Entre na sua conta para ver oportunidades relacionadas ao seu perfil.",empty:"Ainda não há oportunidades publicadas para comparar.",why:"Por que aparece para você",shown:"evidências relacionadas",none:"Nenhuma evidência relacionada ainda — você pode conhecer a vaga mesmo assim.",rule:"Esta organização é apenas informativa. Ela não aprova, rejeita nem envia candidaturas automaticamente.",view:"Ver vaga",apply:"Candidatar",passport:"Meu passaporte"},
en:{title:"Opportunities for me",sub:"Jobs organized using evidence from your Professional Passport.",login:"Sign in to see opportunities related to your profile.",empty:"There are no published opportunities to compare yet.",why:"Why you see this",shown:"related evidence",none:"No related evidence yet — you can still explore this job.",rule:"This organization is informational only. It does not approve, reject or submit applications automatically.",view:"View job",apply:"Apply",passport:"My passport"},
fr:{title:"Opportunités pour moi",sub:"Offres organisées à partir des preuves de votre Passeport Professionnel.",login:"Connectez-vous pour voir les opportunités liées à votre profil.",empty:"Aucune opportunité publiée à comparer pour le moment.",why:"Pourquoi cette offre apparaît",shown:"preuves associées",none:"Aucune preuve associée pour l’instant — vous pouvez tout de même découvrir l’offre.",rule:"Ce classement est uniquement informatif. Il n’approuve, ne refuse et n’envoie aucune candidature automatiquement.",view:"Voir l’offre",apply:"Postuler",passport:"Mon passeport"},
es:{title:"Oportunidades para mí",sub:"Vacantes organizadas según las evidencias de tu Pasaporte Profesional.",login:"Inicia sesión para ver oportunidades relacionadas con tu perfil.",empty:"Aún no hay oportunidades publicadas para comparar.",why:"Por qué aparece para ti",shown:"evidencias relacionadas",none:"Aún no hay evidencias relacionadas — puedes conocer la vacante igualmente.",rule:"Esta organización es solo informativa. No aprueba, rechaza ni envía candidaturas automáticamente.",view:"Ver vacante",apply:"Postular",passport:"Mi pasaporte"}} as const;

function SmartOpportunities(){
 const{locale}=useI18n();const t=C[locale as keyof typeof C]??C.pt;
 const[user,setUser]=useState<any>();const[jobs,setJobs]=useState<any[]>([]);const[evidence,setEvidence]=useState<any[]>([]);
 useEffect(()=>{void(async()=>{const{data}=await supabase.auth.getUser();setUser(data.user??null);if(!data.user)return;
 const{data:apps}=await(supabase.from("career_applications" as never)as any).select("id,career_selection_journeys(id)").eq("candidate_user_id",data.user.id);
 const journeys=(apps??[]).flatMap((x:any)=>x.career_selection_journeys??[]);
 if(journeys.length){const{data:e}=await(supabase.from("career_candidate_evidence" as never)as any).select("competency_key,validity_status").in("journey_id",journeys.map((x:any)=>x.id)).eq("validity_status","current");setEvidence(e??[])}
 const{data:j}=await(supabase.from("career_jobs" as never)as any).select("id,title,city,country,work_mode,contract_type,career_companies(name),career_job_competencies(competency_key,label,requirement_type)").eq("status","published").order("published_at",{ascending:false}).limit(50);setJobs(j??[])})()},[]);
 const keys=useMemo(()=>new Set(evidence.map((e:any)=>e.competency_key)),[evidence]);
 const ranked=useMemo(()=>jobs.map(j=>{const comps=j.career_job_competencies??[];const matched=comps.filter((c:any)=>keys.has(c.competency_key));return{...j,matched}}).sort((a,b)=>b.matched.length-a.matched.length),[jobs,keys]);
 if(user===undefined)return null;
 return <main className="min-h-screen bg-slate-50 text-slate-900"><div className="mx-auto max-w-5xl px-5 py-10"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#c99b2d]">LDR Carreira</p><h1 className="mt-2 text-4xl font-black text-[#07345b]">{t.title}</h1><p className="mt-2 text-slate-600">{t.sub}</p></div><LanguageSelect/></div>
 <div className="mt-6 flex gap-3 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm text-[#07345b]"><ShieldCheck className="shrink-0" size={20}/><p>{t.rule}</p></div>
 {!user?<div className="mt-8 rounded-3xl bg-white p-8 shadow-sm"><p>{t.login}</p><Link to="/cliente/login" className="mt-4 inline-flex rounded-xl bg-[#07345b] px-5 py-3 font-bold text-white">Login</Link></div>:<><div className="mt-6 flex justify-end"><Link to="/carreira/passaporte" className="rounded-xl border border-[#07345b] px-4 py-2 text-sm font-bold text-[#07345b]">{t.passport}</Link></div>
 <div className="mt-5 grid gap-5">{ranked.length===0?<p className="rounded-3xl bg-white p-8">{t.empty}</p>:ranked.map(j=><article key={j.id} className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><h2 className="text-xl font-black text-[#07345b]">{j.title}</h2><p className="mt-1 text-sm text-slate-600">{j.career_companies?.name??"LDR Carreira"}</p><p className="mt-2 flex items-center gap-1 text-sm text-slate-500"><MapPin size={15}/>{[j.city,j.country,j.work_mode].filter(Boolean).join(" · ")}</p></div><BriefcaseBusiness className="text-[#c99b2d]"/></div><div className="mt-5 rounded-2xl bg-slate-50 p-4"><p className="flex items-center gap-2 text-sm font-black"><Info size={17}/>{t.why}</p>{j.matched.length?<div className="mt-3 flex flex-wrap gap-2">{j.matched.map((c:any)=><span key={c.competency_key} className="inline-flex items-center gap-1 rounded-full bg-white px-3 py-2 text-xs font-bold ring-1 ring-slate-200"><CheckCircle2 size={14}/>{c.label}</span>)}</div>:<p className="mt-2 text-sm text-slate-600">{t.none}</p>}</div><div className="mt-5 grid gap-2 sm:grid-cols-2"><Link to="/carreira/vagas/$jobId" params={{jobId:j.id}} className="min-h-12 rounded-xl border border-[#07345b] px-4 py-3 text-center text-sm font-black text-[#07345b]">{t.view}</Link><Link to="/carreira/candidatar/$jobId" params={{jobId:j.id}} className="min-h-12 rounded-xl bg-[#07345b] px-4 py-3 text-center text-sm font-black text-white">{t.apply}</Link></div></article>)}</div></>}
 </div></main>
}