import {useEffect,useState} from "react";
import {createFileRoute} from "@tanstack/react-router";
import {supabase} from "@/integrations/supabase/client";
import {LanguageSelect,useI18n} from "@/lib/i18n";
import {ShieldCheck,ClipboardCheck} from "lucide-react";
export const Route=createFileRoute("/carreira/empresa/entrevista")({component:InterviewPage});
const C={
pt:{title:"Entrevista estruturada LDR",sub:"Registre evidências relacionadas à vaga. A decisão final permanece humana.",login:"Entre como empresa para continuar.",job:"Vaga",candidate:"Candidato",experience:"Experiência relevante",knowledge:"Conhecimento e requisitos",situations:"Situações profissionais",evidence:"Evidências observadas",placeholder:"Registre fatos observáveis relacionados aos requisitos da vaga. Não registre informações clínicas ou discriminatórias.",rule:"Use somente critérios relacionados ao trabalho. Necessidades de acessibilidade não são critério negativo de seleção."},
en:{title:"LDR structured interview",sub:"Record job-related evidence. The final decision remains human.",login:"Sign in as a company to continue.",job:"Job",candidate:"Candidate",experience:"Relevant experience",knowledge:"Knowledge and requirements",situations:"Work situations",evidence:"Observed evidence",placeholder:"Record observable facts related to job requirements. Do not record clinical or discriminatory information.",rule:"Use only job-related criteria. Accessibility needs are not a negative selection criterion."},
fr:{title:"Entretien structuré LDR",sub:"Enregistrez des preuves liées au poste. La décision finale reste humaine.",login:"Connectez-vous comme entreprise pour continuer.",job:"Offre",candidate:"Candidat",experience:"Expérience pertinente",knowledge:"Connaissances et exigences",situations:"Situations professionnelles",evidence:"Preuves observées",placeholder:"Consignez des faits observables liés aux exigences du poste. Ne consignez aucune information clinique ou discriminatoire.",rule:"Utilisez uniquement des critères liés au travail. Les besoins d’accessibilité ne constituent pas un critère négatif."},
es:{title:"Entrevista estructurada LDR",sub:"Registra evidencias relacionadas con la vacante. La decisión final sigue siendo humana.",login:"Inicia sesión como empresa para continuar.",job:"Vacante",candidate:"Candidato",experience:"Experiencia relevante",knowledge:"Conocimientos y requisitos",situations:"Situaciones profesionales",evidence:"Evidencias observadas",placeholder:"Registra hechos observables relacionados con los requisitos. No registres información clínica ni discriminatoria.",rule:"Usa solo criterios relacionados con el trabajo. Las necesidades de accesibilidad no son un criterio negativo."}
} as const;
function InterviewPage(){const{locale}=useI18n();const t=C[locale];const[user,setUser]=useState<any>();useEffect(()=>{void supabase.auth.getUser().then(({data})=>setUser(data.user??null))},[]);if(user===undefined)return null;if(!user)return <main className="min-h-screen bg-slate-50 p-8">{t.login}</main>;return <main className="min-h-screen bg-slate-50 text-slate-900"><div className="mx-auto max-w-4xl px-5 py-10"><div className="flex justify-between gap-4"><div><h1 className="text-4xl font-black text-[#07345b]">{t.title}</h1><p className="mt-2 text-slate-600">{t.sub}</p></div><LanguageSelect/></div><div className="mt-6 flex gap-3 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm text-[#07345b]"><ShieldCheck size={20}/><p>{t.rule}</p></div><section className="mt-8 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><div className="flex items-center gap-2"><ClipboardCheck className="text-[#07345b]"/><h2 className="text-xl font-black">{t.evidence}</h2></div><div className="mt-5 grid gap-5">{[t.experience,t.knowledge,t.situations].map(x=><label key={x} className="grid gap-2 font-bold">{x}<textarea className="min-h-28 rounded-xl border border-slate-300 p-3 font-normal" placeholder={t.placeholder}/></label>)}</div><p className="mt-5 text-sm text-slate-500">{t.sub}</p></section></div></main>}
