import {useEffect,useMemo,useState} from "react";
import {createFileRoute,Link} from "@tanstack/react-router";
import {CheckCircle2,Circle,Clock3,ShieldCheck} from "lucide-react";
import {supabase} from "@/integrations/supabase/client";
import {LanguageSelect,useI18n} from "@/lib/i18n";
export const Route=createFileRoute("/carreira/minha-jornada")({component:Journey});
const copy={pt:{back:"← LDR Carreira",development:"Meu desenvolvimento",title:"Minha Jornada",sub:"Acompanhe sua preparação, evidências, desenvolvimento e próximos passos.",empty:"Nenhuma jornada encontrada.",login:"Entre na sua conta para acessar sua jornada.",next:"Próxima etapa",evidence:"Evidências registradas",rule:"Sua jornada apoia o desenvolvimento. Nenhuma etapa online decide sozinha sua contratação."},en:{back:"← LDR Career",development:"My development",title:"My Journey",sub:"Track preparation, evidence, development and next steps.",empty:"No journey found.",login:"Sign in to access your journey.",next:"Next stage",evidence:"Recorded evidence",rule:"Your journey supports development. No online stage alone decides hiring."},fr:{back:"← LDR Carrière",development:"Mon développement",title:"Mon parcours",sub:"Suivez votre préparation, vos preuves, votre développement et les prochaines étapes.",empty:"Aucun parcours trouvé.",login:"Connectez-vous pour accéder à votre parcours.",next:"Prochaine étape",evidence:"Preuves enregistrées",rule:"Le parcours soutient votre développement. Aucune étape en ligne ne décide seule d’un recrutement."},es:{back:"← LDR Carrera",development:"Mi desarrollo",title:"Mi Jornada",sub:"Sigue tu preparación, evidencias, desarrollo y próximos pasos.",empty:"No se encontró ninguna jornada.",login:"Inicia sesión para acceder a tu jornada.",next:"Próxima etapa",evidence:"Evidencias registradas",rule:"La jornada apoya tu desarrollo. Ninguna etapa en línea decide por sí sola una contratación."}} as const;
function Journey(){const{locale}=useI18n();const t=copy[locale];const[user,setUser]=useState<any>();const[data,setData]=useState<any[]>([]);const[evidence,setEvidence]=useState<any[]>([]);
useEffect(()=>{void(async()=>{const{data:a}=await supabase.auth.getUser();setUser(a.user??null);if(!a.user)return;const{data:apps}=await(supabase.from("career_applications" as never)as any).select("id,job_id,status,created_at,career_jobs(title,company_id),career_selection_journeys(id,status,started_at,career_journey_stages(id,title,stage_type,position,status,required))").eq("candidate_user_id",a.user.id).order("created_at",{ascending:false});setData(apps??[]);const journeys=(apps??[]).flatMap((x:any)=>x.career_selection_journeys??[]).map((x:any)=>x.id);if(journeys.length){const{data:e}=await(supabase.from("career_candidate_evidence" as never)as any).select("id,journey_id,competency_key,evidence_type,validity_status,verified_at").in("journey_id",journeys);setEvidence(e??[])}})()},[]);
const all=useMemo(()=>data.flatMap((a:any)=>(a.career_selection_journeys??[]).map((j:any)=>({...j,application:a}))),[data]);
if(user===undefined)return null;if(user===null)return <main className="min-h-screen bg-slate-50 p-8">{t.login}</main>;
return <main className="min-h-screen bg-slate-50 text-slate-900"><div className="mx-auto max-w-5xl px-5 py-10"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><Link to="/carreira" className="text-sm font-bold text-[#07345b]">{t.back}</Link><Link to="/carreira/meu-desenvolvimento" className="rounded-xl border border-[#07345b] px-3 py-2 text-sm font-bold text-[#07345b]">{t.development}</Link></div><div className="flex flex-col items-start justify-between gap-4 sm:flex-row"><div><h1 className="text-4xl font-black text-[#07345b]">{t.title}</h1><p className="mt-2 text-slate-600">{t.sub}</p></div><LanguageSelect/></div><div className="mt-6 flex gap-2 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm text-[#07345b]"><ShieldCheck size={20}/>{t.rule}</div>{!all.length?<div className="mt-8 rounded-3xl bg-white p-8 shadow-sm">{t.empty}</div>:<div className="mt-8 grid gap-6">{all.map((j:any)=>{const stages=[...(j.career_journey_stages??[])].sort((a:any,b:any)=>a.position-b.position);const next=stages.find((s:any)=>s.status!=="completed"&&s.status!=="skipped");const ev=evidence.filter((x:any)=>x.journey_id===j.id);return <article key={j.id} className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200"><h2 className="text-2xl font-black text-[#07345b]">{j.application?.career_jobs?.title??"LDR Carreira"}</h2>{next&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm"><strong>{t.next}:</strong> {next.title}</p>}<ol className="mt-5 grid gap-3">{stages.map((s:any)=><li key={s.id} className="flex items-center gap-3 rounded-2xl border border-slate-100 p-4">{s.status==="completed"?<CheckCircle2 className="text-emerald-600"/>:s.status==="in_progress"||s.status==="available"?<Clock3 className="text-[#c28d19]"/>:<Circle className="text-slate-400"/>}<div><p className="font-bold">{s.title}</p><p className="text-xs uppercase tracking-wide text-slate-500">{s.status.replaceAll("_"," ")}</p></div></li>)}</ol><div className="mt-5 border-t pt-4"><h3 className="font-bold">{t.evidence}</h3><p className="mt-1 text-sm text-slate-600">{ev.length?ev.map((x:any)=>x.competency_key).join(" · "):"—"}</p></div></article>})}</div>}</div></main>}
