import { useEffect, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { FileText, ShieldCheck, Upload } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";
import { LanguageSelect, useI18n } from "@/lib/i18n";

export const Route=createFileRoute("/carreira/profissional")({component:CandidateProfilePage});

const copy={
pt:{title:"Meu perfil profissional",sub:"Complete seu perfil e mantenha seu currículo privado para reutilizar nas candidaturas.",name:"Nome profissional",role:"Título profissional",summary:"Sobre você",country:"País",city:"Cidade",skills:"Competências (separadas por vírgula)",languages:"Idiomas (separados por vírgula)",resume:"Currículo privado",save:"Salvar perfil",saved:"Perfil salvo com sucesso.",login:"Entre na sua conta para acessar seu perfil profissional.",privacy:"Seu currículo não é público. O acesso depende de autorização.",upload:"Enviar currículo",error:"Não foi possível concluir a operação."},
en:{title:"My professional profile",sub:"Complete your profile and keep your resume private for reuse in applications.",name:"Professional name",role:"Professional title",summary:"About you",country:"Country",city:"City",skills:"Skills (comma separated)",languages:"Languages (comma separated)",resume:"Private resume",save:"Save profile",saved:"Profile saved successfully.",login:"Sign in to access your professional profile.",privacy:"Your resume is not public. Access requires authorization.",upload:"Upload resume",error:"Unable to complete the operation."},
fr:{title:"Mon profil professionnel",sub:"Complétez votre profil et gardez votre CV privé pour le réutiliser dans vos candidatures.",name:"Nom professionnel",role:"Titre professionnel",summary:"À propos de vous",country:"Pays",city:"Ville",skills:"Compétences (séparées par des virgules)",languages:"Langues (séparées par des virgules)",resume:"CV privé",save:"Enregistrer le profil",saved:"Profil enregistré.",login:"Connectez-vous pour accéder à votre profil professionnel.",privacy:"Votre CV n’est pas public. Son accès nécessite une autorisation.",upload:"Envoyer le CV",error:"Impossible de terminer l’opération."},
es:{title:"Mi perfil profesional",sub:"Completa tu perfil y mantén tu currículum privado para reutilizarlo en candidaturas.",name:"Nombre profesional",role:"Título profesional",summary:"Sobre ti",country:"País",city:"Ciudad",skills:"Competencias (separadas por comas)",languages:"Idiomas (separados por comas)",resume:"Currículum privado",save:"Guardar perfil",saved:"Perfil guardado.",login:"Inicia sesión para acceder a tu perfil profesional.",privacy:"Tu currículum no es público. El acceso requiere autorización.",upload:"Subir currículum",error:"No fue posible completar la operación."}
} as const;

function CandidateProfilePage(){
 const {locale}=useI18n(); const t=copy[locale]; const [userId,setUserId]=useState<string|null>(null); const [status,setStatus]=useState("");
 const [form,setForm]=useState({display_name:"",professional_title:"",professional_summary:"",country:"",city:"",skills:"",languages:""});
 useEffect(()=>{void (async()=>{const {data}=await supabase.auth.getUser(); const id=data.user?.id??null; setUserId(id); if(!id)return; const {data:p}=await supabase.from("career_candidate_profiles" as never).select("*").eq("user_id",id).maybeSingle() as any; if(p)setForm({display_name:p.display_name??"",professional_title:p.professional_title??"",professional_summary:p.professional_summary??"",country:p.country??"",city:p.city??"",skills:(p.skills??[]).join(", "),languages:(p.languages??[]).join(", ")});})()},[]);
 const input="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 outline-none focus:border-[#c99b2d] focus:ring-2 focus:ring-[#c99b2d]/20";
 async function save(){if(!userId)return; setStatus(""); const payload={user_id:userId,display_name:form.display_name.trim(),professional_title:form.professional_title.trim()||null,professional_summary:form.professional_summary.trim()||null,country:form.country.trim(),city:form.city.trim()||null,skills:form.skills.split(",").map(x=>x.trim()).filter(Boolean).slice(0,30),languages:form.languages.split(",").map(x=>x.trim()).filter(Boolean).slice(0,20)}; const {error}=await (supabase.from("career_candidate_profiles" as never) as any).upsert(payload,{onConflict:"user_id"}); setStatus(error?t.error:t.saved)}
 async function upload(file:File){if(!userId)return;if(file.size>5242880||!["application/pdf","application/vnd.openxmlformats-officedocument.wordprocessingml.document"].includes(file.type)){setStatus(t.error);return} const ext=file.type==="application/pdf"?"pdf":"docx"; const path=userId+"/resume."+ext; const {error}=await supabase.storage.from("career-resumes").upload(path,file,{upsert:true,contentType:file.type}); if(error){setStatus(t.error);return} await (supabase.from("career_candidate_profiles" as never) as any).update({resume_path:path}).eq("user_id",userId); setStatus(t.saved)}
 if(userId===null)return <main className="min-h-screen bg-slate-50"><div className="mx-auto max-w-3xl px-5 py-12"><div className="flex justify-end"><LanguageSelect/></div><p className="mt-10 rounded-2xl bg-white p-6 shadow-sm">{t.login}</p></div></main>;
 return <main className="min-h-screen bg-slate-50 text-slate-900"><div className="mx-auto max-w-3xl px-5 py-10"><div className="flex items-center justify-between"><h1 className="text-3xl font-bold text-[#07345b]">{t.title}</h1><LanguageSelect/></div><p className="mt-3 text-slate-600">{t.sub}</p><div className="mt-8 grid gap-4 rounded-3xl bg-white p-6 shadow-sm md:p-8"><Field label={t.name}><input required maxLength={120} className={input} value={form.display_name} onChange={e=>setForm({...form,display_name:e.target.value})}/></Field><Field label={t.role}><input maxLength={160} className={input} value={form.professional_title} onChange={e=>setForm({...form,professional_title:e.target.value})}/></Field><Field label={t.summary}><textarea maxLength={3000} rows={5} className={input} value={form.professional_summary} onChange={e=>setForm({...form,professional_summary:e.target.value})}/></Field><div className="grid gap-4 sm:grid-cols-2"><Field label={t.country}><input required maxLength={100} className={input} value={form.country} onChange={e=>setForm({...form,country:e.target.value})}/></Field><Field label={t.city}><input maxLength={120} className={input} value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></Field></div><Field label={t.skills}><input className={input} value={form.skills} onChange={e=>setForm({...form,skills:e.target.value})}/></Field><Field label={t.languages}><input className={input} value={form.languages} onChange={e=>setForm({...form,languages:e.target.value})}/></Field><button type="button" onClick={save} className="min-h-12 rounded-xl bg-[#07345b] px-5 py-3 font-semibold text-white">{t.save}</button><div className="border-t border-slate-200 pt-5"><div className="flex gap-3"><ShieldCheck className="text-[#07345b]"/><div><strong>{t.resume}</strong><p className="mt-1 text-sm text-slate-600">{t.privacy}</p></div></div><label className="mt-4 inline-flex min-h-12 cursor-pointer items-center gap-2 rounded-xl border border-[#07345b] px-4 py-3 font-semibold text-[#07345b]"><Upload size={18}/>{t.upload}<input type="file" accept=".pdf,.docx,application/pdf,application/vnd.openxmlformats-officedocument.wordprocessingml.document" className="sr-only" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/></label></div>{status&&<p role="status" className="rounded-xl bg-slate-50 p-3 text-sm">{status}</p>}</div></div></main>
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block text-sm font-medium text-slate-700"><span className="mb-2 block">{label}</span>{children}</label>}
