import { Link, createFileRoute } from "@tanstack/react-router";
import { ArrowRight, BadgeCheck, CalendarDays, HeartHandshake, ShieldCheck, UsersRound } from "lucide-react";
import { LanguageSelect, useI18n } from "@/lib/i18n";
import { socialClinicLanding } from "@/lib/social-clinic.functions";
import { ProfessionalNetworkMap } from "@/components/professional-network-map";

export const Route = createFileRoute("/clinica-social")({
  loader: () => socialClinicLanding(),
  head: () => ({ meta: [
    { title: "Clínica Social LDR de Psicanálise" },
    { name: "description", content: "Atendimento psicanalítico com valor social: R$ 80 no Brasil e € 30 na Europa, mediante cadastro e disponibilidade." },
    { name: "robots", content: "index,follow" },
    { property: "og:title", content: "Clínica Social LDR de Psicanálise" },
    { property: "og:description", content: "Atendimento psicanalítico com valor social: R$ 80 no Brasil e € 30 na Europa, mediante cadastro e disponibilidade." },
    { property: "og:type", content: "website" },
    { property: "og:url", content: "https://ldrrhestrategia.com/clinica-social" },
  ], links: [{ rel: "canonical", href: "https://ldrrhestrategia.com/clinica-social" }] }),
  component: SocialClinicPage,
});

const WINE="#5b0824", NAVY="#0b1428", GOLD="#c9a63a", CREAM="#fbf8f1";
const copy:any = {
  pt:{eyebrow:"CLÍNICA SOCIAL LDR DE PSICANÁLISE",title:"Um espaço de escuta com valor social",sub:"A Clínica Social LDR amplia o acesso à Psicanálise com atendimentos individuais, organização profissional e confidencialidade.",apply:"SOU CLIENTE — QUERO ATENDIMENTO",provider:"SOU PROFISSIONAL — QUERO ATENDER",company:"SOU EMPRESA — QUERO CONTRATAR",approval:"O cadastro profissional é gratuito. Ao completar 100% dos dados e publicar, o perfil fica online automaticamente. Serviços sujeitos a requisitos profissionais podem exigir validação específica.",area:"ENTRAR NA MINHA ÁREA",what:"O que é a Clínica Social?",whatText:"Uma iniciativa do ecossistema LDR para adultos que desejam iniciar ou continuar um processo de análise com um valor social. O cadastro é uma solicitação e o atendimento depende da disponibilidade de agenda.",how:"Como funciona",professional:"Quem realiza os atendimentos",form:"Solicitar atendimento",formation:"Conheça também a Formação em Psicanálise LDR",formationText:"A Clínica Social integra o ecossistema de Psicanálise da LDR. Conheça a formação estruturada em estudo teórico, atividades, análise pessoal e desenvolvimento progressivo da prática clínica.",formationCta:"CONHECER A FORMAÇÃO",emergency:"A Clínica Social LDR não é um serviço de emergência. Em situações de risco imediato, emergência médica ou psiquiátrica, procure os serviços de emergência da sua região.",submit:"ENVIAR SOLICITAÇÃO"},
  en:{eyebrow:"LDR SOCIAL PSYCHOANALYSIS CLINIC",title:"A listening space at a social rate",sub:"The LDR Social Clinic expands access to psychoanalysis with individual sessions, professional organization and confidentiality.",apply:"I'M A CLIENT — I WANT CARE",provider:"I'M A PROFESSIONAL — I WANT TO PROVIDE CARE",company:"I'M A COMPANY — I WANT TO HIRE",approval:"Professional registration is free. Once the profile is 100% complete and published, it goes online automatically. Services subject to professional requirements may require specific validation.",area:"MY AREA",what:"What is the Social Clinic?",whatText:"An LDR initiative for adults who want to begin or continue psychoanalysis at a social rate. Registration is a request and care depends on availability.",how:"How it works",professional:"Who provides care",form:"Request care",formation:"Discover the LDR Psychoanalysis Training",formationText:"The Social Clinic is part of LDR's psychoanalysis ecosystem, alongside a structured training pathway.",formationCta:"VIEW TRAINING",emergency:"The LDR Social Clinic is not an emergency service. In immediate risk or a medical/psychiatric emergency, contact your local emergency services.",submit:"SEND REQUEST"},
  fr:{eyebrow:"CLINIQUE SOCIALE LDR DE PSYCHANALYSE",title:"Un espace d'écoute à tarif social",sub:"La Clinique Sociale LDR élargit l'accès à la psychanalyse avec des séances individuelles, une organisation professionnelle et la confidentialité.",apply:"JE SUIS CLIENT — JE CHERCHE UN ACCOMPAGNEMENT",provider:"JE SUIS PROFESSIONNEL — JE VEUX EXERCER",company:"JE SUIS UNE ENTREPRISE — JE VEUX RECRUTER",approval:"L'inscription professionnelle est gratuite. Une fois le profil complété à 100 % et publié, il est mis en ligne automatiquement. Certains services soumis à des exigences professionnelles peuvent nécessiter une validation spécifique.",area:"MON ESPACE",what:"Qu'est-ce que la Clinique Sociale ?",whatText:"Une initiative LDR pour les adultes qui souhaitent commencer ou poursuivre une analyse à tarif social. L'inscription est une demande et dépend des disponibilités.",how:"Comment ça marche",professional:"Qui assure les séances",form:"Demander un accompagnement",formation:"Découvrez aussi la Formation en Psychanalyse LDR",formationText:"La Clinique Sociale fait partie de l'écosystème de psychanalyse LDR, avec une formation structurée.",formationCta:"DÉCOUVRIR LA FORMATION",emergency:"La Clinique Sociale LDR n'est pas un service d'urgence. En cas de risque immédiat ou d'urgence médicale/psychiatrique, contactez les services d'urgence de votre région.",submit:"ENVOYER LA DEMANDE"},
  es:{eyebrow:"CLÍNICA SOCIAL LDR DE PSICOANÁLISIS",title:"Un espacio de escucha con valor social",sub:"La Clínica Social LDR amplía el acceso al psicoanálisis con sesiones individuales, organización profesional y confidencialidad.",apply:"SOY CLIENTE — QUIERO ATENCIÓN",provider:"SOY PROFESIONAL — QUIERO ATENDER",company:"SOY EMPRESA — QUIERO CONTRATAR",approval:"El registro profesional es gratuito. Al completar el 100 % de los datos y publicar, el perfil queda online automáticamente. Algunos servicios sujetos a requisitos profesionales pueden requerir una validación específica.",area:"MI ÁREA",what:"¿Qué es la Clínica Social?",whatText:"Una iniciativa LDR para adultos que desean iniciar o continuar un proceso de análisis con valor social. El registro es una solicitud y depende de disponibilidad.",how:"Cómo funciona",professional:"Quién realiza las sesiones",form:"Solicitar atención",formation:"Conoce también la Formación en Psicoanálisis LDR",formationText:"La Clínica Social forma parte del ecosistema de psicoanálisis LDR, junto con una formación estructurada.",formationCta:"CONOCER LA FORMACIÓN",emergency:"La Clínica Social LDR no es un servicio de emergencia. Ante un riesgo inmediato o emergencia médica/psiquiátrica, busca los servicios de emergencia de tu región.",submit:"ENVIAR SOLICITUD"}
};
function money(cents:number,currency:"BRL"|"EUR"){return new Intl.NumberFormat(currency==="BRL"?"pt-BR":"pt-PT",{style:"currency",currency}).format(cents/100)}

function SocialClinicPage(){
  const {locale}=useI18n(); const c=copy[locale]||copy.pt; const data:any=Route.useLoaderData();
  const profile=data?.profile; const profiles=Array.isArray(data?.profiles)?data.profiles:(profile?[profile]:[]);
  return <div className="min-h-screen" style={{background:CREAM,color:NAVY}}>
    <header className="border-b bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4"><Link to="/" className="font-serif text-xl font-bold">Grupo LDR Essence</Link><LanguageSelect/></div></header>
    <main>
      <section className="relative overflow-hidden" style={{background:`linear-gradient(135deg,${NAVY},${WINE})`,color:"white"}}><div className="mx-auto max-w-6xl px-4 py-16 sm:py-24"><p className="text-xs font-black tracking-[.22em]" style={{color:GOLD}}>{c.eyebrow}</p><h1 className="mt-4 max-w-4xl font-serif text-4xl leading-tight sm:text-6xl">{c.title}</h1><p className="mt-5 max-w-3xl text-lg text-white/80">{c.sub}</p><div className="mt-8 grid gap-3 md:grid-cols-3"><a href="#profissionais" className="rounded-2xl px-6 py-4 text-center text-sm font-black" style={{background:GOLD,color:NAVY}}>{c.apply}</a><Link to="/profissional/login" className="rounded-2xl bg-white px-6 py-4 text-center text-sm font-black" style={{color:WINE}}>{c.provider}</Link><Link to="/empresa/login" className="rounded-2xl border border-white/50 px-6 py-4 text-center text-sm font-black">{c.company}</Link></div><p className="mt-4 max-w-3xl text-sm font-semibold text-white/75">{c.approval}</p></div></section>
      <section className="mx-auto grid max-w-6xl gap-5 px-4 py-10 sm:grid-cols-2"><div className="rounded-3xl bg-white p-7 shadow-sm"><HeartHandshake style={{color:WINE}}/><h2 className="mt-4 font-serif text-2xl">{c.what}</h2><p className="mt-3 leading-7 text-slate-600">{c.whatText}</p></div><div className="rounded-3xl p-7 text-white" style={{background:NAVY}}><h2 className="font-serif text-2xl">Valor social por sessão</h2><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/10 p-4"><div className="text-sm">🇧🇷 Brasil</div><div className="mt-1 text-2xl font-black">{money(data.pricing.brlCents,"BRL")}</div></div><div className="rounded-2xl bg-white/10 p-4"><div className="text-sm">🇪🇺 Europa</div><div className="mt-1 text-2xl font-black">{money(data.pricing.eurCents,"EUR")}</div></div></div><p className="mt-4 text-sm text-white/70">Escolha o profissional → escolha o serviço → selecione o horário → pague → agendamento confirmado.</p></div></section>
      <section className="mx-auto max-w-6xl px-4 py-8"><h2 className="font-serif text-3xl">{c.how}</h2><div className="mt-6 grid gap-4 sm:grid-cols-4">{[["1","Escolha o profissional"],["2","Escolha o serviço"],["3","Selecione o horário"],["4","Pague e confirme"]].map(([n,t])=><div key={n} className="rounded-2xl border bg-white p-5"><div className="font-black" style={{color:GOLD}}>{n}</div><div className="mt-2 font-bold">{t}</div></div>)}</div></section>
      <section className="mx-auto max-w-6xl px-4 py-6">
        <ProfessionalNetworkMap
          profiles={profiles}
          title="Mapa da Rede LDR"
          text="Veja onde estão os profissionais públicos e aprovados da rede. Use os filtros por país e cidade para encontrar atendimento online ou presencial."
          labels={{oneProfessional:"profissional",manyProfessionals:"profissionais",oneActiveProfile:"perfil ativo",manyActiveProfiles:"perfis ativos",empty:"Nenhum profissional disponível para este filtro.",filterByCountry:"Filtrar por país",clearFilter:"Limpar filtro",allCountries:"Todos os países",allCities:"Todas as cidades",allAreas:"Todas as áreas",city:"Cidade",area:"Área",languages:"Idiomas",viewProfile:"Ver perfil"}}
        />
      </section>
      <section id="profissionais" className="mx-auto max-w-6xl scroll-mt-6 px-4 py-10">
        <div className="rounded-[2rem] border bg-white p-7 sm:p-9">
          <p className="text-xs font-black tracking-[.18em]" style={{color:WINE}}>{c.professional}</p>
          <h2 className="mt-2 font-serif text-3xl">Profissionais aprovados pela LDR</h2>
          <p className="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Perfis ativos e aprovados administrativamente. Serviços e horários aparecem conforme o cadastro de cada profissional.</p>
          <div className="mt-6 grid gap-5 md:grid-cols-2 xl:grid-cols-3">
            {profiles.map((p:any)=><article key={p.id||p.slug} className="flex min-w-0 flex-col rounded-3xl border bg-[#fbf8f1] p-5">
              <div className="flex items-start gap-4">
                {p.photo_url?<img src={p.photo_url} alt={p.display_name} className="h-20 w-20 shrink-0 rounded-2xl object-cover"/>:<div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-2xl bg-white"><UsersRound className="h-9 w-9"/></div>}
                <div className="min-w-0"><div className="flex items-center gap-2"><h3 className="break-words font-serif text-2xl">{p.display_name}</h3>{p.profile_verified&&<BadgeCheck className="h-5 w-5 shrink-0" style={{color:GOLD}}/>}</div><p className="mt-1 text-sm font-black" style={{color:WINE}}>{p.professional_title}</p><p className="mt-2 text-xs text-slate-500">{p.public_region||[p.city,p.country_code].filter(Boolean).join(" · ")}{p.online_enabled?" · Online":""}{p.in_person_enabled?" · Presencial":""}</p></div>
              </div>
              <p className="mt-4 line-clamp-4 text-sm leading-6 text-slate-600">{p.about||p.experience_summary||"Perfil profissional aprovado pela LDR."}</p>
              {Array.isArray(p.specialties)&&p.specialties.length>0?<div className="mt-4 flex flex-wrap gap-2">{p.specialties.slice(0,4).map((s:string)=><span key={s} className="rounded-full bg-white px-3 py-1 text-xs font-bold">{s}</span>)}</div>:null}
              <div className="mt-auto pt-5">
                <p className="mb-3 text-xs font-semibold text-slate-500">{p.active_service_count>0?(p.active_service_count+" serviço(s) ativo(s)"):p.availability_count>0?(p.availability_count+" período(s) de disponibilidade cadastrado(s)"):"Atendimento social ainda não disponível. Consulte o perfil profissional."}</p>
                <div className="space-y-3">{Array.isArray(p.services)&&p.services.length>0?<div className="grid gap-2">{p.services.map((s:any)=><Link key={s.id} to="/profissional/$slug" params={{slug:p.slug}} search={{source:"social_clinic",service:s.id}} hash="agendar" className="rounded-2xl border bg-white p-3 text-left"><div className="flex flex-wrap items-center justify-between gap-2"><span className="font-black">{s.name}</span><span className="font-black" style={{color:WINE}}>{money(String(s.currency)==="BRL"?data.pricing.brlCents:data.pricing.eurCents,String(s.currency)==="BRL"?"BRL":"EUR")}</span></div><p className="mt-1 text-xs text-slate-500">{s.duration_minutes} min · {s.modality==="online"?"Online":s.modality==="in_person"?"Presencial":"Online / Presencial"}</p><p className="mt-2 text-xs font-black" style={{color:WINE}}>VER HORÁRIOS E PAGAR →</p></Link>)}</div>:<p className="text-sm text-slate-500">Nenhum serviço disponível para agendamento neste momento.</p>}<Link to="/profissional/$slug" params={{slug:p.slug}} search={{source:"social_clinic"}} className="inline-flex rounded-full border px-5 py-2.5 text-sm font-black">VER PERFIL COMPLETO</Link></div>
              </div>
            </article>)}
          </div>
          {profiles.length===0?<div className="mt-6 rounded-2xl border border-dashed p-6 text-sm text-slate-600">Nenhum profissional aprovado está disponível neste momento.</div>:null}
        </div>
      </section>
      <section className="mx-auto max-w-6xl px-4 py-10"><div className="rounded-[2rem] border p-7 sm:flex sm:items-center sm:justify-between" style={{borderColor:GOLD}}><div><h2 className="font-serif text-2xl">{c.formation}</h2><p className="mt-2 max-w-3xl text-slate-600">{c.formationText}</p></div><Link to="/formacao-psicanalise" className="mt-5 inline-flex shrink-0 items-center gap-2 rounded-full px-5 py-3 text-sm font-black sm:mt-0" style={{background:GOLD,color:NAVY}}>{c.formationCta}<ArrowRight className="h-4 w-4"/></Link></div></section>
      <section className="mx-auto max-w-6xl px-4 pb-12"><div className="rounded-2xl bg-amber-50 p-5 text-sm leading-6 text-amber-950"><ShieldCheck className="mb-2"/>{c.emergency}</div><div className="mt-5 grid gap-3 sm:grid-cols-3"><a href="#profissionais" className="rounded-full border px-5 py-2.5 text-center text-sm font-black">{c.apply}</a><Link to="/profissional/login" className="rounded-full px-5 py-2.5 text-center text-sm font-black text-white" style={{background:WINE}}>{c.provider}</Link><Link to="/empresa/login" className="rounded-full border px-5 py-2.5 text-center text-sm font-black">{c.company}</Link></div></section>
    </main></div>
}
