import { createFileRoute,Link } from "@tanstack/react-router";
import { CheckCircle2 } from "lucide-react";
import { useI18n } from "@/lib/i18n";
import { getProfessionalFormation,pfText,type PFLocale } from "@/lib/academy-professional-formations.catalog";

export const Route=createFileRoute("/formacoes/$slug")({component:Page});
const COLORS:Record<string,string>={navy:"#0b3764",wine:"#7a1835",green:"#047857",petrol:"#0F5E7A",purple:"#6D3FA0",gold:"#a06f1c"};
const UI={pt:{badge:"FORMAÇÃO LIVRE · COMPRA AVULSA",online:"100% online",hours:"horas",lessons:"aulas",modules:"módulos",project:"Projeto final obrigatório",one:"Pagamento único",outside:"Não incluída na assinatura da LDR Academy",learn:"O que você vai estudar",cta:"ACESSAR / COMPRAR",safe:"Pagamento seguro via Stripe",final:"Projeto aplicado e avaliação",finalText:"A conclusão exige progresso integral e entrega do projeto final pela plataforma."},en:{badge:"NON-DEGREE TRAINING · STANDALONE PURCHASE",online:"100% online",hours:"hours",lessons:"lessons",modules:"modules",project:"Mandatory final project",one:"One-time payment",outside:"Not included in the LDR Academy subscription",learn:"What you will study",cta:"ACCESS / BUY",safe:"Secure Stripe payment",final:"Applied project and assessment",finalText:"Completion requires full progress and submission of the final project through the platform."},fr:{badge:"FORMATION LIBRE · ACHAT SÉPARÉ",online:"100% en ligne",hours:"heures",lessons:"leçons",modules:"modules",project:"Projet final obligatoire",one:"Paiement unique",outside:"Non incluse dans l’abonnement LDR Academy",learn:"Ce que vous étudierez",cta:"ACCÉDER / ACHETER",safe:"Paiement sécurisé Stripe",final:"Projet appliqué et évaluation",finalText:"La validation exige une progression complète et l’envoi du projet final sur la plateforme."},es:{badge:"FORMACIÓN LIBRE · COMPRA INDIVIDUAL",online:"100% online",hours:"horas",lessons:"clases",modules:"módulos",project:"Proyecto final obligatorio",one:"Pago único",outside:"No incluida en la suscripción de LDR Academy",learn:"Lo que estudiarás",cta:"ACCEDER / COMPRAR",safe:"Pago seguro con Stripe",final:"Proyecto aplicado y evaluación",finalText:"La finalización exige progreso completo y entrega del proyecto final en la plataforma."}} as const;
function money(cents:number,currency:"BRL"|"EUR",locale:PFLocale){return new Intl.NumberFormat(locale==="pt"?"pt-BR":locale==="fr"?"fr-FR":locale==="es"?"es-ES":"en-US",{style:"currency",currency}).format(cents/100)}
function Page(){const {slug}=Route.useParams(),{locale:raw}=useI18n(),locale=(raw==="en"||raw==="fr"||raw==="es"?raw:"pt") as PFLocale,u=UI[locale],f=getProfessionalFormation(slug);if(!f)return <main className="p-8">Formação não encontrada.</main>;const t=pfText(f,locale);return <main className="min-h-screen bg-[#f7f3e9] text-[#071426]"><section className="px-4 py-16 text-white" style={{background:`linear-gradient(135deg,${COLORS[f.theme]??"#071426"},#071426)`}}><div className="mx-auto max-w-6xl"><div className="text-5xl">{f.icon}</div><p className="mt-5 text-xs font-black tracking-[.18em] text-[#d6ad63]">{u.badge}</p><h1 className="mt-3 max-w-5xl font-serif text-4xl text-[#fff7e7] sm:text-6xl">{t.name}</h1><p className="mt-5 max-w-3xl text-white/80">{t.description}</p><div className="mt-7 flex flex-wrap gap-2">{[u.online,`${f.hours} ${u.hours}`,`${f.lessons} ${u.lessons}`,`${f.modulesCount} ${u.modules}`,u.project].map(x=><span key={x} className="rounded-full bg-white/10 px-4 py-2 text-xs font-black">{x}</span>)}</div><div className="mt-8 flex flex-wrap items-center gap-3"><Link to={f.learnerPath as any} className="rounded-xl bg-[#d6ad63] px-6 py-4 text-sm font-black text-[#281605]">{u.cta}</Link><span className="rounded-xl border border-white/20 px-5 py-3 text-sm font-black">🇧🇷 {money(f.priceBrlCents,"BRL",locale)} · 🇪🇺 {money(f.priceEurCents,"EUR",locale)}</span></div><p className="mt-3 text-sm font-semibold text-white/80">{u.one} · {u.outside}</p><p className="mt-1 text-xs text-white/60">{u.safe}</p></div></section><section className="mx-auto max-w-6xl px-4 py-14"><p className="text-xs font-black uppercase tracking-[.16em] text-[#a06f1c]">{t.category??"LDR ACADEMY"}</p><h2 className="mt-2 font-serif text-3xl">{u.learn}</h2><div className="mt-7 grid gap-4 md:grid-cols-2">{t.modules.map((m,i)=><article key={m} className="rounded-2xl border bg-white p-5"><p className="text-xs font-black text-[#a06f1c]">{String(i+1).padStart(2,"0")}</p><h3 className="mt-2 text-lg font-black">{m}</h3></article>)}</div><section className="mt-10 rounded-3xl bg-[#071426] p-7 text-white"><CheckCircle2 className="h-8 w-8 text-[#d6ad63]"/><h2 className="mt-4 font-serif text-3xl text-[#fff7e7]">{u.final}</h2><p className="mt-3 text-white/75">{t.project}. {u.finalText}</p></section>{t.disclaimer?<p className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">{t.disclaimer}</p>:null}</section></main>}
