import {createFileRoute,Outlet,useRouterState} from "@tanstack/react-router";import{useEffect,useState}from"react";import{humanRoomClient}from"@/lib/human-room-browser";
export const Route=createFileRoute("/human-room/salas")({component:Page});
const editorial=[
{slug:"editorial-educacao-futuro",title:"O que uma universidade precisa ensinar para continuar relevante?",objective:"build",is_demo:true,perspectives:4},
{slug:"editorial-carreira-ia",title:"A inteligência artificial vai substituir empregos ou transformar carreiras?",objective:"explore",is_demo:true,perspectives:4},
{slug:"editorial-saude-mental-trabalho",title:"Como trabalhar sem transformar produtividade em esgotamento?",objective:"question",is_demo:true,perspectives:4},
{slug:"editorial-cidades-pertencimento",title:"O que faz alguém realmente se sentir parte de uma cidade nova?",objective:"build",is_demo:true,perspectives:4},
{slug:"editorial-relacoes-digitais",title:"Estamos mais conectados e menos próximos uns dos outros?",objective:"explore",is_demo:true,perspectives:4},
{slug:"editorial-empreender-2026",title:"Ainda faz sentido começar um negócio pequeno em 2026?",objective:"act",is_demo:true,perspectives:4}
];
function Page(){const pathname=useRouterState({select:s=>s.location.pathname});return pathname==="/human-room/salas"||pathname==="/human-room/salas/"?<Rooms/>:<Outlet/>}function Rooms(){const[r,setR]=useState<any[]>(editorial);useEffect(()=>{humanRoomClient().rpc("list_public_human_rooms").then(({data}:any)=>{if(data?.length){const extra=data.filter((x:any)=>!editorial.some(e=>e.slug===x.slug));setR([...editorial,...extra])}}).catch(()=>{})},[]);return <main className="min-h-screen bg-[#f7f5ef] p-5"><div className="mx-auto max-w-5xl"><a href="/human-room" className="font-black">← HUMAN ROOM</a><h1 className="my-10 font-serif text-5xl font-bold">Salas abertas</h1><div className="grid gap-4">{r.map(x=><a className="rounded-3xl border bg-white p-6" href={"/human-room/salas/"+x.slug} key={x.slug}><small className="font-black text-[#315b4c]">{x.is_demo?"EDITORIAL · ":""}{x.objective?.toUpperCase()} · {x.perspectives||0} PERSPECTIVAS</small><h2 className="mt-2 text-2xl font-bold">{x.title}</h2></a>)}</div></div></main>}