import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, BriefcaseBusiness, Building2, GraduationCap, HeartHandshake, Sparkles, UserRound, UsersRound } from "lucide-react";
import { LanguageSelect, useI18n } from "@/lib/i18n";
import { childhoodImage } from "@/lib/story-childhood";
import { atomiumImage } from "@/lib/story-atomium";
import { hospitalImage } from "@/lib/story-hospital";
import { SocialProofSection } from "@/components/social-proof-section";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "Do Porta em Porta ao Negócio — Formação para Empreendedores | Grupo LDR Essence" },
    { name: "description", content: "Da venda de banana e mamão na Bahia à construção de negócios na Europa. Conheça a história de Luciano Rodrigues Almeida e a formação Do Porta em Porta ao Negócio." },
    { property: "og:title", content: "Do Porta em Porta ao Negócio — Formação para Empreendedores" },
    { property: "og:description", content: "Uma história real de trabalho, mudanças e recomeços transformada em formação prática para empreendedores." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary_large_image" },
  ]}),
  component: Home,
});

const COPY = {
  pt: {
    brand:"Grupo LDR Essence", tagline:"Conhecimento que transforma realidades", enter:"ENTRAR", panels:"ACESSAR PAINÉIS",
    heroEyebrow:"UMA HISTÓRIA REAL. UM MÉTODO CONSTRUÍDO NA PRÁTICA.",
    heroTitle:"EU COMECEI VENDENDO BANANA E MAMÃO DE PORTA EM PORTA.",
    heroSecond:"HOJE, CONTINUO VENDENDO — MAS DE UM JEITO DIFERENTE: TAMBÉM ENSINO O QUE APRENDI NO CAMINHO.",
    heroText:"Da Bahia à Europa, entre trabalho, mudanças, quedas e recomeços, descobri que ninguém precisa começar grande — mas precisa começar com direção.",
    storyCta:"CONHEÇA MINHA HISTÓRIA ↓", formationCta:"JÁ CONHEÇO — QUERO VER A FORMAÇÃO",
    originKicker:"CAPÍTULO 1 · BAHIA", originTitle:"Antes de existir um negócio, existia um menino aprendendo a fazer acontecer.",
    originText1:"Foi ali que tudo começou. Muito antes de existir empresa, plataforma ou formação, banana e mamão fizeram parte dos meus primeiros contatos com venda, trabalho e responsabilidade.",
    originText2:"Naquele momento eu não chamava aquilo de empreendedorismo. Eu só sabia que precisava me movimentar com aquilo que tinha nas mãos.",
    quote1:"“Eu não comecei com estrutura. Comecei com necessidade, vontade e movimento.”",
    lineKicker:"A VIDA NÃO FOI UMA LINHA RETA", lineTitle:"Durante muito tempo eu achei que estava mudando de caminho. Hoje entendo que estava construindo repertório.",
    lineText:"Cabeleireiro → Psicanálise → Massagem e bem-estar → RH → Gestão de Projetos → Empreendedorismo → Grupo LDR Essence.",
    europeKicker:"CAPÍTULO 2 · EUROPA", europeTitle:"Mudar de país me obrigou a começar de novo.",
    europeText:"Portugal e depois Bélgica trouxeram novos mercados, outras culturas, novos contatos e a necessidade de reaprender a vender, atender, comunicar e construir. Você pode mudar de país, mas leva consigo tudo aquilo que aprendeu para sobreviver, trabalhar e avançar.",
    pauseKicker:"CAPÍTULO 3 · A PAUSA", pauseTitle:"E então a vida me obrigou a parar.",
    pauseText:"Na Bélgica, uma fratura no pé interrompeu minha rotina. Para quem vive criando, trabalhando e tentando fazer acontecer, parar mexe com muito mais do que o corpo. A pergunta passou a ser: o que eu faria com tudo aquilo que tinha aprendido até ali?",
    quote2:"“Nem toda pausa é o fim. Algumas viram ponto de reorganização.”",
    turnKicker:"A VIRADA", turnTitle:"Eu parei de olhar para minha história como fases soltas.",
    turnText:"Cada etapa me ensinou algo sobre pessoas, comportamento, atendimento, vendas, serviço, gestão e negócios. Nenhuma fase foi perdida. Tudo virou repertório.",
    doorKicker:"DO PORTA EM PORTA AO NEGÓCIO", doorTitle:"Eu comecei vendendo de porta em porta. De certa forma, continuo vendendo até hoje.",
    doorText:"Antes eu levava banana e mamão até as pessoas. Hoje eu levo conhecimento, serviços, soluções e negócios — e ensino o que aprendi fazendo isso na prática.",
    bridge:"O que antes era experiência virou repertório. O repertório virou método. E o método virou formação.",
    originName:"“Do Mamão ao Negócio” continua sendo a origem dessa história. “Do Porta em Porta ao Negócio” é a evolução dela.",
    offerKicker:"FORMAÇÃO PARA EMPREENDEDORES", offerTitle:"DO PORTA EM PORTA AO NEGÓCIO", offerSub:"Da venda de banana e mamão à construção de negócios na Europa.",
    offerText:"Uma formação prática para ajudar você a sair da ideia, organizar sua oferta, posicionamento e vendas e avançar com mais direção.",
    includes:"Formação vendida individualmente · pagamento único", lessons:"90 aulas", live:"6 encontros ao vivo", lifetime:"Acesso vitalício", practical:"Aplicação prática", positioning:"Posicionamento e vendas", project:"Projeto e construção do negócio",
    priceBr:"🇧🇷 R$ 299,99", priceEu:"🇪🇺 € 49,90", buy:"QUERO COMEÇAR MINHA FORMAÇÃO", hotmart:"Pagamento único e seguro pelo Stripe",
    forKicker:"PARA QUEM É", forTitle:"Você não precisa ter tudo pronto para começar.",
    forText:"A formação foi pensada para quem tem uma ideia e não sabe por onde começar; já começou, mas está sem direção; precisa organizar oferta, posicionamento e vendas; quer transformar conhecimento em negócio; ou pensa em crescer e atuar em outros mercados.",
    trustTitle:"Eu não posso prometer que empreender será fácil.",
    trustText:"Também não posso prometer resultado rápido. O que posso fazer é colocar à sua disposição aquilo que aprendi trabalhando, estudando, errando, recomeçando e construindo.",
    finalQuote:"Talvez você não precise começar grande. Talvez precise apenas começar com direção.",
    client:"Área do Cliente", company:"Área da Empresa", employee:"Área do Funcionário", professional:"Área do Profissional", find:"Encontrar profissionais", network:"Entrar para a Rede LDR",
  },
  en: {
    brand:"Grupo LDR Essence", tagline:"Knowledge that transforms realities", enter:"SIGN IN", panels:"ACCESS PORTALS",
    heroEyebrow:"A REAL STORY. A METHOD BUILT IN PRACTICE.", heroTitle:"I STARTED SELLING BANANAS AND PAPAYAS DOOR TO DOOR.", heroSecond:"TODAY I STILL SELL — IN A DIFFERENT WAY: I ALSO TEACH WHAT I LEARNED ALONG THE WAY.", heroText:"From Bahia to Europe, through work, change, setbacks and new beginnings, I learned that you do not have to start big — but you do need direction.", storyCta:"DISCOVER MY STORY ↓", formationCta:"I KNOW THE STORY — SHOW ME THE TRAINING",
    originKicker:"CHAPTER 1 · BAHIA", originTitle:"Before there was a business, there was a boy learning how to make things happen.", originText1:"That is where everything started. Long before a company, platform or training program existed, bananas and papayas were part of my first experiences with sales, work and responsibility.", originText2:"I did not call it entrepreneurship then. I only knew I had to move with what I had in my hands.", quote1:"“I did not start with structure. I started with need, will and movement.”",
    lineKicker:"LIFE WAS NOT A STRAIGHT LINE", lineTitle:"For years I thought I was changing paths. Today I understand I was building repertoire.", lineText:"Hairdresser → Psychoanalysis → Massage & well-being → HR → Project Management → Entrepreneurship → Grupo LDR Essence.",
    europeKicker:"CHAPTER 2 · EUROPE", europeTitle:"Changing countries forced me to start again.", europeText:"Portugal and then Belgium brought new markets, cultures, contacts and the need to relearn how to sell, serve, communicate and build. You can change countries, but you carry everything you learned to survive, work and move forward.",
    pauseKicker:"CHAPTER 3 · THE PAUSE", pauseTitle:"Then life forced me to stop.", pauseText:"In Belgium, a foot fracture interrupted my routine. When you are used to creating and working, stopping affects more than the body. The question became: what would I do with everything I had learned so far?", quote2:"“Not every pause is the end. Some become a point of reorganization.”",
    turnKicker:"THE TURN", turnTitle:"I stopped seeing my story as disconnected phases.", turnText:"Every stage taught me something about people, behavior, service, sales, management and business. No phase was wasted. Everything became repertoire.",
    doorKicker:"FROM DOOR TO DOOR TO BUSINESS", doorTitle:"I started selling door to door. In a way, I still sell today.", doorText:"Before, I took bananas and papayas to people. Today I take knowledge, services, solutions and businesses — and I teach what I learned by doing it in practice.", bridge:"Experience became repertoire. Repertoire became a method. And the method became a training program.", originName:"“From Papaya to Business” remains the origin of this story. “From Door to Door to Business” is its evolution.",
    offerKicker:"ENTREPRENEUR TRAINING", offerTitle:"FROM DOOR TO DOOR TO BUSINESS", offerSub:"From selling bananas and papayas to building businesses in Europe.", offerText:"Practical training to help you move from idea to offer, positioning, sales and clearer next steps.", includes:"Training sold separately · one-time payment", lessons:"90 lessons", live:"6 live sessions", lifetime:"Lifetime access", practical:"Practical application", positioning:"Positioning & sales", project:"Business project & structure", priceBr:"🇧🇷 R$ 299.99", priceEu:"🇪🇺 €49.90", buy:"START MY TRAINING", hotmart:"Secure one-time payment via Stripe",
    forKicker:"WHO IT IS FOR", forTitle:"You do not need to have everything ready to start.", forText:"For people with an idea and no clear starting point; those who started but feel lost; need to organize offer, positioning and sales; want to turn knowledge into a business; or plan to grow into new markets.", trustTitle:"I cannot promise entrepreneurship will be easy.", trustText:"I also cannot promise quick results. What I can do is share what I learned by working, studying, making mistakes, starting again and building.", finalQuote:"Maybe you do not need to start big. Maybe you just need to start with direction.", client:"Client Area", company:"Company Area", employee:"Employee Area", professional:"Professional Area", find:"Find professionals", network:"Join the LDR Network",
  },
  fr: {
    brand:"Grupo LDR Essence", tagline:"Un savoir qui transforme les réalités", enter:"ENTRER", panels:"ACCÉDER AUX ESPACES",
    heroEyebrow:"UNE HISTOIRE RÉELLE. UNE MÉTHODE CONSTRUITE DANS LA PRATIQUE.", heroTitle:"J’AI COMMENCÉ À VENDRE DES BANANES ET DES PAPAYES DE PORTE À PORTE.", heroSecond:"AUJOURD’HUI, JE CONTINUE À VENDRE — AUTREMENT : J’ENSEIGNE AUSSI CE QUE J’AI APPRIS EN CHEMIN.", heroText:"De Bahia à l’Europe, entre travail, changements, chutes et nouveaux départs, j’ai appris qu’il n’est pas nécessaire de commencer grand — mais qu’il faut une direction.", storyCta:"DÉCOUVRIR MON HISTOIRE ↓", formationCta:"JE CONNAIS — VOIR LA FORMATION",
    originKicker:"CHAPITRE 1 · BAHIA", originTitle:"Avant l’entreprise, il y avait un garçon qui apprenait à faire avec ce qu’il avait.", originText1:"C’est là que tout a commencé. Bien avant l’entreprise, la plateforme ou la formation, les bananes et les papayes faisaient partie de mes premières expériences de vente, de travail et de responsabilité.", originText2:"Je n’appelais pas cela de l’entrepreneuriat. Je savais seulement qu’il fallait avancer avec ce que j’avais entre les mains.", quote1:"« Je n’ai pas commencé avec une structure. J’ai commencé avec le besoin, la volonté et le mouvement. »",
    lineKicker:"LA VIE N’A PAS ÉTÉ UNE LIGNE DROITE", lineTitle:"Pendant longtemps, je pensais changer de voie. Aujourd’hui, je comprends que je construisais mon expérience.", lineText:"Coiffeur → Psychanalyse → Massage & bien-être → RH → Gestion de projets → Entrepreneuriat → Grupo LDR Essence.",
    europeKicker:"CHAPITRE 2 · EUROPE", europeTitle:"Changer de pays m’a obligé à recommencer.", europeText:"Le Portugal puis la Belgique ont apporté de nouveaux marchés, cultures, contacts et la nécessité de réapprendre à vendre, servir, communiquer et construire.",
    pauseKicker:"CHAPITRE 3 · LA PAUSE", pauseTitle:"Puis la vie m’a obligé à m’arrêter.", pauseText:"En Belgique, une fracture du pied a interrompu ma routine. Quand on vit en créant et en travaillant, s’arrêter touche bien plus que le corps. La question est devenue : que faire de tout ce que j’avais appris ?", quote2:"« Toutes les pauses ne sont pas une fin. Certaines deviennent un point de réorganisation. »",
    turnKicker:"LE TOURNANT", turnTitle:"J’ai cessé de voir mon histoire comme des phases séparées.", turnText:"Chaque étape m’a appris quelque chose sur les personnes, le comportement, le service, la vente, la gestion et l’entreprise. Rien n’a été perdu. Tout est devenu expérience.",
    doorKicker:"DU PORTE-À-PORTE À L’ENTREPRISE", doorTitle:"J’ai commencé à vendre de porte à porte. D’une certaine façon, je vends encore aujourd’hui.", doorText:"Avant, j’apportais bananes et papayes aux gens. Aujourd’hui, j’apporte connaissances, services, solutions et affaires — et j’enseigne ce que j’ai appris dans la pratique.", bridge:"L’expérience est devenue un répertoire. Le répertoire est devenu une méthode. Et la méthode est devenue une formation.", originName:"« De la Papaye à l’Entreprise » reste l’origine de cette histoire. « Du Porte-à-Porte à l’Entreprise » en est l’évolution.",
    offerKicker:"FORMATION POUR ENTREPRENEURS", offerTitle:"DU PORTE-À-PORTE À L’ENTREPRISE", offerSub:"De la vente de bananes et papayes à la construction d’activités en Europe.", offerText:"Une formation pratique pour passer de l’idée à l’offre, au positionnement, à la vente et à des prochaines étapes plus claires.", includes:"Inclut eBook + Livre + Formation complète", lessons:"90 leçons", live:"6 rencontres en direct", lifetime:"Accès à vie", practical:"Application pratique", positioning:"Positionnement et ventes", project:"Projet et structure d’entreprise", priceBr:"🇧🇷 R$ 299,99", priceEu:"🇪🇺 49,90 €", buy:"COMMENCER MA FORMATION", hotmart:"Paiement unique et sécurisé via Stripe",
    forKicker:"POUR QUI", forTitle:"Vous n’avez pas besoin que tout soit prêt pour commencer.", forText:"Pour ceux qui ont une idée mais ne savent pas par où commencer, qui ont commencé sans direction claire, qui doivent organiser leur offre, leur positionnement et leurs ventes, ou qui veulent grandir sur de nouveaux marchés.", trustTitle:"Je ne peux pas promettre que l’entrepreneuriat sera facile.", trustText:"Je ne peux pas non plus promettre des résultats rapides. Je peux partager ce que j’ai appris en travaillant, étudiant, me trompant, recommençant et construisant.", finalQuote:"Peut-être que vous n’avez pas besoin de commencer grand. Peut-être avez-vous simplement besoin de commencer avec une direction.", client:"Espace Client", company:"Espace Entreprise", employee:"Espace Collaborateur", professional:"Espace Professionnel", find:"Trouver des professionnels", network:"Rejoindre le Réseau LDR",
  },
  es: {
    brand:"Grupo LDR Essence", tagline:"Conocimiento que transforma realidades", enter:"ENTRAR", panels:"ACCEDER A LOS PANELES",
    heroEyebrow:"UNA HISTORIA REAL. UN MÉTODO CONSTRUIDO EN LA PRÁCTICA.", heroTitle:"EMPECÉ VENDIENDO BANANAS Y PAPAYAS PUERTA A PUERTA.", heroSecond:"HOY SIGO VENDIENDO — DE OTRA MANERA: TAMBIÉN ENSEÑO LO QUE APRENDÍ EN EL CAMINO.", heroText:"De Bahia a Europa, entre trabajo, cambios, caídas y nuevos comienzos, aprendí que no necesitas empezar en grande — pero sí necesitas dirección.", storyCta:"CONOCE MI HISTORIA ↓", formationCta:"YA LA CONOZCO — VER LA FORMACIÓN",
    originKicker:"CAPÍTULO 1 · BAHIA", originTitle:"Antes de existir un negocio, había un niño aprendiendo a hacer que las cosas sucedieran.", originText1:"Ahí empezó todo. Mucho antes de una empresa, plataforma o formación, las bananas y las papayas fueron parte de mis primeras experiencias con ventas, trabajo y responsabilidad.", originText2:"En ese momento no lo llamaba emprendimiento. Solo sabía que tenía que moverme con lo que tenía en las manos.", quote1:"“No empecé con estructura. Empecé con necesidad, voluntad y movimiento.”",
    lineKicker:"LA VIDA NO FUE UNA LÍNEA RECTA", lineTitle:"Durante mucho tiempo pensé que estaba cambiando de camino. Hoy entiendo que estaba construyendo repertorio.", lineText:"Peluquero → Psicoanálisis → Masaje y bienestar → RR. HH. → Gestión de Proyectos → Emprendimiento → Grupo LDR Essence.",
    europeKicker:"CAPÍTULO 2 · EUROPA", europeTitle:"Cambiar de país me obligó a empezar de nuevo.", europeText:"Portugal y después Bélgica trajeron nuevos mercados, culturas, contactos y la necesidad de reaprender a vender, atender, comunicar y construir.",
    pauseKicker:"CAPÍTULO 3 · LA PAUSA", pauseTitle:"Entonces la vida me obligó a parar.", pauseText:"En Bélgica, una fractura en el pie interrumpió mi rutina. Cuando estás acostumbrado a crear y trabajar, parar afecta mucho más que el cuerpo. La pregunta pasó a ser: ¿qué haría con todo lo aprendido hasta ese momento?", quote2:"“No toda pausa es el final. Algunas se convierten en un punto de reorganización.”",
    turnKicker:"EL GIRO", turnTitle:"Dejé de mirar mi historia como fases desconectadas.", turnText:"Cada etapa me enseñó algo sobre personas, comportamiento, atención, ventas, servicio, gestión y negocios. Ninguna fase se perdió. Todo se convirtió en repertorio.",
    doorKicker:"DE PUERTA EN PUERTA AL NEGOCIO", doorTitle:"Empecé vendiendo puerta a puerta. De alguna manera, sigo vendiendo hoy.", doorText:"Antes llevaba bananas y papayas a las personas. Hoy llevo conocimiento, servicios, soluciones y negocios — y enseño lo que aprendí haciéndolo en la práctica.", bridge:"La experiencia se convirtió en repertorio. El repertorio se convirtió en método. Y el método se convirtió en formación.", originName:"“De la Papaya al Negocio” sigue siendo el origen de esta historia. “De Puerta en Puerta al Negocio” es su evolución.",
    offerKicker:"FORMACIÓN PARA EMPRENDEDORES", offerTitle:"DE PUERTA EN PUERTA AL NEGOCIO", offerSub:"De vender bananas y papayas a construir negocios en Europa.", offerText:"Una formación práctica para ayudarte a pasar de la idea a la oferta, el posicionamiento, las ventas y próximos pasos más claros.", includes:"Incluye eBook + Libro + Formación completa", lessons:"90 clases", live:"6 encuentros en vivo", lifetime:"Acceso de por vida", practical:"Aplicación práctica", positioning:"Posicionamiento y ventas", project:"Proyecto y estructura del negocio", priceBr:"🇧🇷 R$ 299,99", priceEu:"🇪🇺 € 49,90", buy:"QUIERO EMPEZAR MI FORMACIÓN", hotmart:"Pago único y seguro mediante Stripe",
    forKicker:"PARA QUIÉN ES", forTitle:"No necesitas tenerlo todo listo para empezar.", forText:"Para quien tiene una idea y no sabe por dónde comenzar, ya empezó pero está sin dirección, necesita organizar oferta, posicionamiento y ventas, quiere transformar conocimiento en negocio o crecer hacia nuevos mercados.", trustTitle:"No puedo prometer que emprender será fácil.", trustText:"Tampoco puedo prometer resultados rápidos. Lo que sí puedo hacer es compartir lo que aprendí trabajando, estudiando, equivocándome, empezando de nuevo y construyendo.", finalQuote:"Tal vez no necesites empezar en grande. Tal vez solo necesites empezar con dirección.", client:"Área del Cliente", company:"Área de Empresa", employee:"Área del Empleado", professional:"Área del Profesional", find:"Encontrar profesionales", network:"Entrar a la Red LDR",
  },
} as const;

function Home() {
  const { locale } = useI18n();
  const c = COPY[locale];
  const access = [
    { to:"/cliente/login", title:c.client, icon:UserRound },
    { to:"/empresa/login", title:c.company, icon:Building2 },
    { to:"/funcionario/login", title:c.employee, icon:UsersRound },
    { to:"/profissional/login", title:c.professional, icon:BriefcaseBusiness },
  ] as const;

  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b border-white/10 text-white shadow-sm" style={{background:"linear-gradient(135deg, var(--wine-deep), var(--wine))"}}>
      <div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-3 sm:px-6">
        <div className="min-w-0"><p className="truncate font-serif text-lg sm:text-xl">{c.brand}</p><p className="hidden text-xs opacity-75 sm:block">{c.tagline}</p></div>
        <div className="flex items-center gap-2"><LanguageSelect/><details className="relative"><summary className="cursor-pointer list-none rounded-xl bg-[#d9aa3f] px-3 py-2 text-xs font-black text-[#3d0818] sm:px-4">{c.enter}</summary><div className="absolute right-0 mt-2 w-72 rounded-2xl border bg-card p-3 text-foreground shadow-2xl">{access.map(({to,title,icon:Icon})=><Link key={to} to={to} className="flex items-center gap-3 rounded-xl p-3 text-sm font-bold hover:bg-primary/10"><Icon className="h-5 w-5 text-primary"/>{title}<ArrowUpRight className="ml-auto h-4 w-4"/></Link>)}<Link to="/profissionais" className="flex items-center gap-3 rounded-xl p-3 text-sm font-bold hover:bg-primary/10"><UsersRound className="h-5 w-5 text-primary"/>{c.find}<ArrowUpRight className="ml-auto h-4 w-4"/></Link><Link to="/para-profissionais" className="flex items-center gap-3 rounded-xl p-3 text-sm font-bold hover:bg-primary/10"><HeartHandshake className="h-5 w-5 text-primary"/>{c.network}<ArrowUpRight className="ml-auto h-4 w-4"/></Link></div></details></div>
      </div>
    </header>

    <main>
      <section className="relative overflow-hidden bg-[#071a33] text-white">
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(217,170,63,.22),transparent_38%)]"/>
        <div className="relative mx-auto grid max-w-6xl gap-10 px-4 py-16 sm:px-6 sm:py-20 lg:grid-cols-[1.15fr_.85fr] lg:items-center lg:py-24">
          <div><p className="text-xs font-black uppercase tracking-[.18em] text-[#e2b64e]">{c.heroEyebrow}</p><h1 className="mt-5 max-w-4xl font-serif text-4xl font-bold leading-[1.05] sm:text-5xl lg:text-6xl">{c.heroTitle}</h1><p className="mt-5 max-w-3xl text-lg font-black leading-7 text-[#f1c45d] sm:text-xl">{c.heroSecond}</p><p className="mt-5 max-w-2xl text-sm leading-7 text-white/80 sm:text-base">{c.heroText}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><a href="#historia" className="inline-flex min-h-12 items-center justify-center rounded-2xl bg-[#d9aa3f] px-6 py-4 text-sm font-black text-[#3d0818] shadow-lg">{c.storyCta}</a><a href="#formacao" className="inline-flex min-h-12 items-center justify-center rounded-2xl border border-white/30 px-6 py-4 text-sm font-black text-white hover:bg-white/10">{c.formationCta}</a></div></div>
          <div className="relative mx-auto w-full max-w-md"><div className="absolute -inset-4 rounded-[2.5rem] bg-[#d9aa3f]/15 blur-2xl"/><img src={childhoodImage} alt="Infância na Bahia — onde a história começou" className="relative aspect-[4/5] w-full rounded-[2rem] border border-[#d9aa3f]/40 object-cover shadow-2xl"/><div className="absolute bottom-4 left-4 right-4 rounded-2xl bg-black/60 p-4 backdrop-blur"><p className="text-xs font-black uppercase tracking-[.16em] text-[#f1c45d]">BAHIA · ONDE TUDO COMEÇOU</p></div></div>
        </div>
      </section>

      <div id="historia" className="mx-auto max-w-6xl space-y-6 px-4 py-10 sm:px-6 sm:py-14">
        <section className="grid overflow-hidden rounded-[2rem] border bg-card shadow-xl lg:grid-cols-[.85fr_1.15fr]"><img src={childhoodImage} alt="Foto de infância na Bahia" className="h-full min-h-[320px] w-full object-cover"/><div className="p-7 sm:p-10"><p className="text-xs font-black uppercase tracking-[.18em] text-primary">{c.originKicker}</p><h2 className="mt-3 font-serif text-3xl leading-tight sm:text-4xl">{c.originTitle}</h2><p className="mt-5 text-sm leading-7 text-muted-foreground sm:text-base">{c.originText1}</p><p className="mt-3 text-sm leading-7 text-muted-foreground sm:text-base">{c.originText2}</p><blockquote className="mt-6 border-l-4 border-[#d9aa3f] pl-5 font-serif text-xl italic leading-8">{c.quote1}</blockquote></div></section>

        <section className="rounded-[2rem] border bg-card p-7 shadow-lg sm:p-10"><p className="text-xs font-black uppercase tracking-[.18em] text-primary">{c.lineKicker}</p><h2 className="mt-3 max-w-4xl font-serif text-3xl leading-tight sm:text-4xl">{c.lineTitle}</h2><p className="mt-6 rounded-2xl bg-primary/8 p-5 text-sm font-black leading-7 text-primary sm:text-base">{c.lineText}</p></section>

        <section className="grid overflow-hidden rounded-[2rem] border bg-[#071a33] text-white shadow-xl lg:grid-cols-[1.05fr_.95fr]"><div className="p-7 sm:p-10"><p className="text-xs font-black uppercase tracking-[.18em] text-[#e2b64e]">{c.europeKicker}</p><h2 className="mt-3 font-serif text-3xl leading-tight sm:text-4xl">{c.europeTitle}</h2><p className="mt-5 text-sm leading-7 text-white/80 sm:text-base">{c.europeText}</p></div><img src={atomiumImage} alt="Bruxelas — nova fase na Europa" loading="lazy" className="h-full min-h-[360px] w-full object-cover"/></section>

        <section className="grid overflow-hidden rounded-[2rem] border bg-card shadow-xl lg:grid-cols-[.9fr_1.1fr]"><img src={hospitalImage} alt="Período de recuperação na Bélgica" loading="lazy" className="h-full min-h-[360px] w-full object-cover"/><div className="p-7 sm:p-10"><p className="text-xs font-black uppercase tracking-[.18em] text-primary">{c.pauseKicker}</p><h2 className="mt-3 font-serif text-3xl leading-tight sm:text-4xl">{c.pauseTitle}</h2><p className="mt-5 text-sm leading-7 text-muted-foreground sm:text-base">{c.pauseText}</p><blockquote className="mt-6 border-l-4 border-[#d9aa3f] pl-5 font-serif text-xl italic leading-8">{c.quote2}</blockquote></div></section>

        <section className="rounded-[2rem] border bg-card p-7 shadow-xl sm:p-10"><p className="text-xs font-black uppercase tracking-[.18em] text-primary">{c.turnKicker}</p><h2 className="mt-3 max-w-4xl font-serif text-3xl leading-tight sm:text-4xl">{c.turnTitle}</h2><p className="mt-5 max-w-4xl text-sm leading-7 text-muted-foreground sm:text-base">{c.turnText}</p></section>

        <section className="relative overflow-hidden rounded-[2rem] border border-[#d5aa45] bg-[#5b0824] p-7 text-white shadow-2xl sm:p-10"><div className="absolute -right-20 -top-20 h-64 w-64 rounded-full bg-[#d5aa45]/20 blur-3xl"/><div className="relative"><p className="text-xs font-black uppercase tracking-[.18em] text-[#e2b64e]">{c.doorKicker}</p><h2 className="mt-4 max-w-4xl font-serif text-3xl leading-tight text-[#fff5df] sm:text-5xl">{c.doorTitle}</h2><p className="mt-5 max-w-4xl text-sm leading-7 text-[#f5dfac] sm:text-base">{c.doorText}</p><p className="mt-7 max-w-4xl font-serif text-2xl font-bold leading-9 text-white">{c.bridge}</p><p className="mt-4 max-w-3xl text-sm italic leading-7 text-white/75">{c.originName}</p><a href="#formacao" className="mt-7 inline-flex min-h-12 items-center gap-2 rounded-2xl bg-[#d9aa3f] px-6 py-4 text-sm font-black text-[#3d0818]">{c.formationCta}<ArrowUpRight className="h-4 w-4"/></a></div></section>

        <section className="overflow-hidden rounded-[2rem] border-2 border-[#d5aa45] bg-gradient-to-br from-[#35101e] to-[#5b0824] p-7 text-white shadow-2xl sm:p-10"><div className="flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div className="max-w-3xl"><span className="inline-flex rounded-full bg-[#d9aa3f] px-3 py-1.5 text-xs font-black text-[#3d0818]">{locale==="pt"?"AMOSTRA GRÁTIS":locale==="fr"?"EXTRAIT GRATUIT":locale==="es"?"MUESTRA GRATIS":"FREE PREVIEW"}</span><h2 className="mt-4 font-serif text-3xl leading-tight text-[#fff5df] sm:text-4xl">{locale==="pt"?"Leia o início da minha história antes de decidir":locale==="fr"?"Lisez le début de mon histoire avant de décider":locale==="es"?"Lee el inicio de mi historia antes de decidir":"Read the beginning of my story before you decide"}</h2><p className="mt-4 text-sm leading-7 text-[#f5dfac] sm:text-base">{locale==="pt"?"Entre na experiência de leitura e conheça gratuitamente uma parte da história que deu origem ao livro, ao eBook e à formação — Bahia, porta em porta, recomeços e a transformação da experiência em método.":locale==="fr"?"Entrez dans l’expérience de lecture et découvrez gratuitement une partie de l’histoire à l’origine du livre, de l’eBook et de la formation — Bahia, porte-à-porte, nouveaux départs et transformation de l’expérience en méthode.":locale==="es"?"Entra en la experiencia de lectura y conoce gratis una parte de la historia que dio origen al libro, al eBook y a la formación — Bahia, puerta a puerta, nuevos comienzos y la transformación de la experiencia en método.":"Enter the reading experience and discover a free part of the story behind the book, eBook and training — Bahia, door to door, new beginnings and turning experience into method."}</p><p className="mt-4 font-serif text-xl font-bold text-[#f1c45d]">{locale==="pt"?"Leia primeiro. Depois decida se quer continuar.":locale==="fr"?"Lisez d’abord. Décidez ensuite si vous voulez continuer.":locale==="es"?"Lee primero. Después decide si quieres continuar.":"Read first. Then decide if you want to continue."}</p></div><a href="/amostra-gratis" className="inline-flex min-h-14 shrink-0 items-center justify-center rounded-2xl bg-[#d9aa3f] px-6 py-4 text-sm font-black text-[#3d0818] shadow-lg">{locale==="pt"?"LER AMOSTRA GRÁTIS →":locale==="fr"?"LIRE L’EXTRAIT GRATUIT →":locale==="es"?"LEER MUESTRA GRATIS →":"READ FREE PREVIEW →"}</a></div></section>

        <section className="rounded-[2rem] border border-[#c9a85d] bg-gradient-to-br from-[#2a104e] via-[#4b2077] to-[#27103f] p-6 text-white shadow-xl sm:p-8">
          <div className="grid gap-6 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#e2c372]">NOVA FORMAÇÃO · PSICANÁLISE</p><h2 className="mt-2 font-serif text-3xl font-bold sm:text-4xl">Formação Online em Psicanálise</h2><p className="mt-3 max-w-3xl leading-7 text-white/80">12 módulos · 6 encontros ao vivo · teoria, análise pessoal e supervisão · leituras orientadas · atividades · acesso vitalício aos conteúdos digitais.</p><div className="mt-4 flex flex-wrap gap-3 text-sm"><strong className="text-[#f0d58e]">PAGAMENTO ÚNICO · R$ 299,99 / € 49,90</strong></div></div><a href="/formacao-psicanalise" className="inline-flex min-h-12 items-center justify-center rounded-2xl bg-[#d6b86d] px-6 text-center text-sm font-black text-[#32155c]">CONHECER A FORMAÇÃO</a></div>
        </section>

        <section className="overflow-hidden rounded-[2rem] border border-[#1d4f91]/25 bg-gradient-to-br from-[#061a34] via-[#0a376b] to-[#0b5cab] p-7 text-white shadow-2xl sm:p-10">
          <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#7ed7ff]">{locale==="pt"?"BIBLIOTECA LDR · FORMAÇÕES E CURSOS":locale==="fr"?"BIBLIOTECA LDR · FORMATIONS ET COURS":locale==="es"?"BIBLIOTECA LDR · FORMACIONES Y CURSOS":"BIBLIOTECA LDR · COURSES & TRAINING"}</p><h2 className="mt-3 max-w-4xl font-serif text-3xl leading-tight sm:text-4xl">{locale==="pt"?"Conheça todos os cursos e formações disponíveis":locale==="fr"?"Découvrez tous les cours et formations disponibles":locale==="es"?"Conoce todos los cursos y formaciones disponibles":"Explore all available courses and training"}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-white/75 sm:text-base">{locale==="pt"?"Você pode comprar cada formação separadamente com acesso vitalício ou acessar os conteúdos pagos pela assinatura da Biblioteca LDR.":locale==="fr"?"Achetez chaque formation séparément avec accès à vie ou accédez aux contenus payants via l’abonnement Biblioteca LDR.":locale==="es"?"Compra cada formación por separado con acceso de por vida o accede al contenido de pago con la suscripción Biblioteca LDR.":"Buy each course separately with lifetime access or access paid content through the Biblioteca LDR subscription."}</p></div><Link to="/cliente/biblioteca" className="inline-flex min-h-12 shrink-0 items-center justify-center rounded-2xl bg-[#ffd84d] px-6 text-sm font-black text-[#08264b]">{locale==="pt"?"VER BIBLIOTECA →":locale==="fr"?"VOIR LA BIBLIOTHÈQUE →":locale==="es"?"VER BIBLIOTECA →":"VIEW LIBRARY →"}</Link></div>
          <div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {[
              {title:"Do Mamão ao Negócio",tag:locale==="pt"?"Empreendedorismo · 90 aulas":"Entrepreneurship · 90 lessons",href:"/treinamento",tone:"bg-[#6b0929]"},
              {title:"Formação Online em Psicanálise",tag:locale==="pt"?"12 módulos · percurso completo":"12 modules · full path",href:"/formacao-psicanalise",tone:"bg-[#562a82]"},
              {title:"Formação em Mentoria Profissional e de Carreira",tag:locale==="pt"?"Carreira · posicionamento · prática":"Career · positioning · practice",href:"/cliente/biblioteca",tone:"bg-[#0b5cab]"},
              {title:"Formação em Liderança e Gestão de Pessoas",tag:locale==="pt"?"Liderança · equipes · gestão":"Leadership · teams · management",href:"/cliente/biblioteca",tone:"bg-[#0f5132]"},
              {title:"Planejamento de Carreira",tag:locale==="pt"?"CURSO GRATUITO":"FREE COURSE",href:"/cliente/biblioteca",tone:"bg-[#b85c2e]"},
              {title:"Francês A1",tag:locale==="pt"?"CURSO GRATUITO":"FREE COURSE",href:"/cliente/biblioteca",tone:"bg-[#8b5a2b]"}
            ].map((course)=><Link key={course.title} to={course.href} className={`rounded-2xl border border-white/15 ${course.tone} p-5 transition hover:-translate-y-1 hover:shadow-xl`}><GraduationCap className="h-6 w-6 text-white/90"/><h3 className="mt-3 font-serif text-xl font-bold leading-tight">{course.title}</h3><p className="mt-2 text-xs font-black uppercase tracking-[.12em] text-white/70">{course.tag}</p><span className="mt-4 inline-flex items-center gap-1 text-sm font-black">{locale==="pt"?"CONHECER":locale==="fr"?"DÉCOUVRIR":locale==="es"?"CONOCER":"EXPLORE"}<ArrowUpRight className="h-4 w-4"/></span></Link>)}
          </div>
          <div className="mt-7 rounded-[1.5rem] border border-[#ffd84d]/55 bg-black/20 p-5 sm:p-6"><div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><p className="text-xs font-black uppercase tracking-[.16em] text-[#ffd84d]">⚡ {locale==="pt"?"PROMOÇÃO DE 24 HORAS · 50% NO PRIMEIRO MÊS":locale==="fr"?"PROMO 24H · -50% LE PREMIER MOIS":locale==="es"?"PROMO 24H · 50% EL PRIMER MES":"24H PROMO · 50% OFF FIRST MONTH"}</p><div className="mt-2 flex flex-wrap gap-x-6 gap-y-1"><strong className="text-2xl text-[#ffd84d]">🇧🇷 R$ 19,95</strong><strong className="text-2xl text-[#7ed7ff]">🇪🇺 € 4,95</strong></div><p className="mt-2 text-xs text-white/70">{locale==="pt"?"A partir do segundo mês: R$ 39,90/mês ou € 9,90/mês. Cancele quando quiser.":locale==="fr"?"À partir du deuxième mois : 39,90 R$/mois ou 9,90 €/mois. Annulez quand vous voulez.":locale==="es"?"Desde el segundo mes: R$ 39,90/mes o € 9,90/mes. Cancela cuando quieras.":"From month two: R$39.90/month or €9.90/month. Cancel anytime."}</p></div><Link to="/cliente/biblioteca" className="inline-flex min-h-12 items-center justify-center rounded-2xl bg-[#ffd84d] px-6 text-sm font-black text-[#08264b]">{locale==="pt"?"APROVEITAR 50% →":locale==="fr"?"PROFITER DE -50% →":locale==="es"?"APROVECHAR 50% →":"GET 50% OFF →"}</Link></div></div>
        </section>

        <SocialProofSection locale={locale}/>

        <section id="formacao" className="scroll-mt-24 overflow-hidden rounded-[2rem] border border-[#d5aa45] bg-[#5b0824] text-white shadow-2xl"><div className="p-7 sm:p-10"><div className="inline-flex items-center gap-2 rounded-full bg-[#d9aa3f] px-3 py-1.5 text-xs font-black text-[#3d0818]"><GraduationCap className="h-4 w-4"/>{c.offerKicker}</div><h2 className="mt-5 font-serif text-4xl leading-tight text-[#fff5df] sm:text-5xl">{c.offerTitle}</h2><p className="mt-3 text-lg font-bold text-[#f1c45d]">{c.offerSub}</p><p className="mt-5 max-w-3xl text-sm leading-7 text-[#f5dfac] sm:text-base">{c.offerText}</p><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[c.lessons,c.live,c.lifetime,c.practical,c.positioning,c.project].map((item)=><div key={item} className="rounded-2xl border border-white/15 bg-white/8 p-4 text-sm font-bold">✓ {item}</div>)}</div><div className="mt-8 rounded-[1.5rem] border border-[#d9aa3f]/50 bg-black/15 p-6"><p className="text-xs font-black uppercase tracking-[.15em] text-[#e2b64e]">{c.includes}</p><div className="mt-4 flex flex-col gap-1 sm:flex-row sm:items-end sm:gap-6"><strong className="text-3xl text-[#f1c45d] sm:text-4xl">{c.priceBr}</strong><strong className="text-2xl text-[#f1c45d] sm:text-3xl">{c.priceEu}</strong></div><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Link to="/cliente/biblioteca" className="inline-flex min-h-12 flex-1 items-center justify-center gap-2 rounded-2xl bg-[#d9aa3f] px-6 py-4 text-sm font-black text-[#3d0818] shadow-lg"><GraduationCap className="h-5 w-5"/>{c.buy}<ArrowUpRight className="h-4 w-4"/></Link></div><p className="mt-3 text-xs text-white/65">{c.hotmart}</p></div></div></section>

        <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-[2rem] border bg-card p-7 shadow-lg sm:p-9"><p className="text-xs font-black uppercase tracking-[.18em] text-primary">{c.forKicker}</p><h2 className="mt-3 font-serif text-3xl leading-tight">{c.forTitle}</h2><p className="mt-5 text-sm leading-7 text-muted-foreground sm:text-base">{c.forText}</p></div><div className="rounded-[2rem] border bg-[#071a33] p-7 text-white shadow-lg sm:p-9"><Sparkles className="h-7 w-7 text-[#e2b64e]"/><h2 className="mt-4 font-serif text-3xl leading-tight">{c.trustTitle}</h2><p className="mt-5 text-sm leading-7 text-white/75 sm:text-base">{c.trustText}</p><p className="mt-6 font-serif text-xl font-bold leading-8 text-[#f1c45d]">{c.finalQuote}</p></div></section>

        <section className="rounded-[2rem] border bg-card p-7 shadow-lg sm:p-9"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-primary">{c.panels}</p><h2 className="mt-2 font-serif text-3xl">{c.enter}</h2></div><Link to="/profissionais" className="inline-flex items-center gap-2 rounded-xl border px-4 py-3 text-sm font-black text-primary">{c.find}<ArrowUpRight className="h-4 w-4"/></Link></div><div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{access.map(({to,title,icon:Icon})=><Link key={to} to={to} className="rounded-2xl border bg-background p-5 transition hover:-translate-y-1 hover:border-primary/30 hover:shadow-lg"><Icon className="h-6 w-6 text-primary"/><h3 className="mt-3 font-serif text-xl">{title}</h3><span className="mt-4 inline-flex items-center gap-1 text-sm font-black text-primary">{c.enter}<ArrowUpRight className="h-4 w-4"/></span></Link>)}</div></section>
      </div>
    </main>
  </div>;
}
