import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowUpRight, BriefcaseBusiness, Building2, HeartHandshake, Sparkles, UserRound, UsersRound } from "lucide-react";
import { LanguageSelect, useI18n } from "@/lib/i18n";

export const Route = createFileRoute("/")({
  head: () => ({
    meta: [
      { title: "Grupo LDR Essence — Acessos e Sistema S8" },
      { name: "description", content: "Acesse sua área no ecossistema Grupo LDR Essence: cliente individual, empresa, funcionário ou profissional." },
      { property: "og:title", content: "Grupo LDR Essence — Acessos" },
      { property: "og:description", content: "Áreas organizadas para clientes, empresas, funcionários e profissionais." },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: Home,
});

const HOME_COPY = {
  pt: { tagline:"Serviços, benefícios, desenvolvimento e bem-estar", choose:"Escolha sua área", chooseText:"Cada perfil encontra apenas o que precisa. Cliente individual, empresa, funcionário e profissional têm acessos organizados a serviços, agenda, conteúdos e benefícios.", find:"Encontrar profissionais", enter:"Entrar", client:"Área do Cliente", clientText:"Compras, agenda, serviços, biblioteca, e-book, treinamentos e acompanhamento.", company:"Área da Empresa", companyText:"Gerencie funcionários, benefícios, contratação, pagamentos e agenda corporativa.", employee:"Área do Funcionário", employeeText:"Consulte benefícios, créditos, agenda, notificações e conteúdos disponibilizados.", professional:"Área do Profissional", professionalText:"Perfil, agenda, serviços, atendimentos, financeiro, treinamentos e recursos da Rede LDR.", companyEyebrow:"Benefícios para empresas", companyTitle:"Transforme cuidado e desenvolvimento em benefício para sua equipe.", companyDescription:"Planos empresariais de 1 a 10 funcionários, 11 a 50 e configuração personalizada a partir de 51 funcionários. A empresa cadastra a equipe, libera benefícios e acompanha somente as informações administrativas necessárias.", companyItem1:"Psicanálise e atendimento individual", companyItem2:"Carreira, orientação e mentoria", companyItem3:"Bem-estar e ações corporativas", plans:"Ver planos para empresas", benefits:"Configurar benefícios", network:"Rede de Profissionais LDR", networkTitle:"Você é profissional? Faça parte de uma rede criada para organizar e fortalecer sua presença.", networkText:"Conheça os planos, recursos, comunidade, treinamentos e ferramentas da Rede LDR antes de criar seu perfil.", discover:"Conhecer a Rede", already:"Já sou profissional" },
  en: { tagline:"Services, benefits, development and well-being", choose:"Choose your area", chooseText:"Each profile finds only what it needs. Individual clients, companies, employees and professionals have organized access to services, schedules, content and benefits.", find:"Find professionals", enter:"Sign in", client:"Client Area", clientText:"Purchases, schedule, services, library, e-book, training and follow-up.", company:"Company Area", companyText:"Manage employees, benefits, purchases, payments and corporate scheduling.", employee:"Employee Area", employeeText:"View benefits, credits, schedule, notifications and available content.", professional:"Professional Area", professionalText:"Profile, schedule, services, appointments, finances, training and LDR Network resources.", companyEyebrow:"Benefits for companies", companyTitle:"Turn care and development into a benefit for your team.", companyDescription:"Company plans for 1 to 10 employees, 11 to 50, and custom configuration from 51 employees. The company registers its team, releases benefits and sees only the necessary administrative information.", companyItem1:"Psychoanalysis and individual care", companyItem2:"Career guidance and mentorship", companyItem3:"Well-being and corporate actions", plans:"View company plans", benefits:"Configure benefits", network:"LDR Professional Network", networkTitle:"Are you a professional? Join a network created to organize and strengthen your presence.", networkText:"Explore plans, resources, community, training and LDR Network tools before creating your profile.", discover:"Discover the Network", already:"I am a professional" },
  fr: { tagline:"Services, avantages, développement et bien-être", choose:"Choisissez votre espace", chooseText:"Chaque profil trouve uniquement ce dont il a besoin. Clients individuels, entreprises, collaborateurs et professionnels disposent d’accès organisés aux services, agendas, contenus et avantages.", find:"Trouver des professionnels", enter:"Entrer", client:"Espace Client", clientText:"Achats, agenda, services, bibliothèque, e-book, formations et accompagnement.", company:"Espace Entreprise", companyText:"Gérez collaborateurs, avantages, achats, paiements et agenda de l’entreprise.", employee:"Espace Collaborateur", employeeText:"Consultez avantages, crédits, agenda, notifications et contenus disponibles.", professional:"Espace Professionnel", professionalText:"Profil, agenda, services, rendez-vous, finances, formations et ressources du Réseau LDR.", companyEyebrow:"Avantages pour les entreprises", companyTitle:"Transformez le soin et le développement en avantage pour votre équipe.", companyDescription:"Forfaits entreprise de 1 à 10 collaborateurs, de 11 à 50 et configuration personnalisée à partir de 51. L’entreprise inscrit son équipe, attribue les avantages et ne consulte que les informations administratives nécessaires.", companyItem1:"Psychanalyse et accompagnement individuel", companyItem2:"Carrière, orientation et mentorat", companyItem3:"Bien-être et actions en entreprise", plans:"Voir les forfaits entreprise", benefits:"Configurer les avantages", network:"Réseau de Professionnels LDR", networkTitle:"Vous êtes professionnel ? Rejoignez un réseau conçu pour organiser et renforcer votre présence.", networkText:"Découvrez les forfaits, ressources, communauté, formations et outils du Réseau LDR avant de créer votre profil.", discover:"Découvrir le Réseau", already:"Je suis professionnel" },
  es: { tagline:"Servicios, beneficios, desarrollo y bienestar", choose:"Elige tu área", chooseText:"Cada perfil encuentra solo lo que necesita. Clientes individuales, empresas, empleados y profesionales tienen accesos organizados a servicios, agenda, contenidos y beneficios.", find:"Encontrar profesionales", enter:"Entrar", client:"Área del Cliente", clientText:"Compras, agenda, servicios, biblioteca, e-book, formaciones y seguimiento.", company:"Área de Empresa", companyText:"Gestiona empleados, beneficios, contrataciones, pagos y agenda corporativa.", employee:"Área del Empleado", employeeText:"Consulta beneficios, créditos, agenda, notificaciones y contenidos disponibles.", professional:"Área del Profesional", professionalText:"Perfil, agenda, servicios, citas, finanzas, formaciones y recursos de la Red LDR.", companyEyebrow:"Beneficios para empresas", companyTitle:"Convierte el cuidado y el desarrollo en un beneficio para tu equipo.", companyDescription:"Planes empresariales de 1 a 10 empleados, de 11 a 50 y configuración personalizada desde 51. La empresa registra a su equipo, libera beneficios y consulta solo la información administrativa necesaria.", companyItem1:"Psicoanálisis y atención individual", companyItem2:"Carrera, orientación y mentoría", companyItem3:"Bienestar y acciones corporativas", plans:"Ver planes para empresas", benefits:"Configurar beneficios", network:"Red de Profesionales LDR", networkTitle:"¿Eres profesional? Forma parte de una red creada para organizar y fortalecer tu presencia.", networkText:"Conoce los planes, recursos, comunidad, formaciones y herramientas de la Red LDR antes de crear tu perfil.", discover:"Conocer la Red", already:"Ya soy profesional" },
} as const;

function Home() {
  const { locale } = useI18n();
  const c = HOME_COPY[locale];
  const access = [
    { to:"/cliente/login", title:c.client, text:c.clientText, icon:UserRound, featured:true },
    { to:"/empresa/login", title:c.company, text:c.companyText, icon:Building2 },
    { to:"/funcionario/login", title:c.employee, text:c.employeeText, icon:UsersRound },
    { to:"/profissional/login", title:c.professional, text:c.professionalText, icon:BriefcaseBusiness },
  ] as const;
  return <div className="min-h-screen bg-background text-foreground">
    <header className="text-primary-foreground shadow-sm" style={{background:"linear-gradient(135deg, var(--wine-deep), var(--wine))"}}><div className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 px-4 py-5 sm:px-6"><div className="min-w-0"><p className="break-words font-serif text-2xl">Grupo LDR Essence</p><p className="mt-1 text-sm opacity-85">{c.tagline}</p></div><LanguageSelect/></div></header>
    <main className="mx-auto max-w-6xl px-4 py-8 sm:px-6">
      <section className="s8-card min-w-0 overflow-hidden">
        <div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">Grupo LDR Essence</p><h1 className="mt-2 break-words font-serif text-3xl sm:text-4xl">{c.choose}</h1><p className="mt-3 max-w-3xl text-[0.98rem] leading-7 text-muted-foreground">{c.chooseText}</p></div><Link to="/profissionais" className="inline-flex min-h-11 items-center gap-2 rounded-xl border px-4 py-3 text-sm font-black text-primary transition hover:bg-primary hover:text-primary-foreground">{c.find} <ArrowUpRight className="h-4 w-4"/></Link></div>
        <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{access.map(({to,title,text,icon:Icon,featured})=><Link key={to} to={to} className={`group min-w-0 rounded-2xl border p-5 transition duration-300 hover:-translate-y-1 hover:shadow-xl focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 ${featured?"border-primary bg-primary text-primary-foreground":"bg-card hover:border-primary/25"}`}><div className={`grid h-11 w-11 place-items-center rounded-2xl ${featured?"bg-white/15":"bg-primary/10 text-primary"}`}><Icon className="h-6 w-6"/></div><h2 className="mt-4 break-words font-serif text-2xl">{title}</h2><p className={`mt-2 break-words text-sm leading-6 ${featured?"opacity-85":"text-muted-foreground"}`}>{text}</p><span className="mt-5 inline-flex items-center gap-1 text-sm font-black">{c.enter} <ArrowUpRight className="h-4 w-4 transition group-hover:translate-x-0.5 group-hover:-translate-y-0.5"/></span></Link>)}</div>
      </section>

      <section className="relative mt-4 overflow-hidden rounded-[2rem] border bg-card p-7 shadow-xl shadow-primary/5 sm:p-9"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-secondary/15 blur-3xl"/><div className="relative grid gap-7 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1.5 text-xs font-black uppercase tracking-[.16em] text-primary"><HeartHandshake className="h-4 w-4"/>{c.companyEyebrow}</div><h2 className="mt-4 max-w-3xl font-serif text-3xl leading-tight sm:text-4xl">{c.companyTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-muted-foreground sm:text-base">{c.companyDescription}</p><div className="mt-5 grid gap-2 text-sm sm:grid-cols-3"><span className="rounded-xl border bg-background px-4 py-3 font-bold">{c.companyItem1}</span><span className="rounded-xl border bg-background px-4 py-3 font-bold">{c.companyItem2}</span><span className="rounded-xl border bg-background px-4 py-3 font-bold">{c.companyItem3}</span></div></div><div className="flex flex-col gap-3 sm:flex-row lg:flex-col"><Link to="/planos-empresas" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-2xl bg-primary px-6 py-4 text-sm font-black text-primary-foreground shadow-lg transition hover:-translate-y-0.5">{c.plans} <ArrowUpRight className="h-4 w-4"/></Link><Link to="/empresa/login" className="inline-flex min-h-11 items-center justify-center rounded-2xl border px-6 py-4 text-sm font-black text-primary transition hover:bg-primary/5">{c.benefits}</Link></div></div></section>

      <section className="relative mt-4 overflow-hidden rounded-[2rem] bg-primary p-7 text-primary-foreground shadow-xl shadow-primary/10 sm:p-9"><div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-secondary/20 blur-3xl"/><div className="relative grid gap-6 lg:grid-cols-[1fr_auto] lg:items-center"><div><div className="inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-black uppercase tracking-[.16em]"><Sparkles className="h-4 w-4 text-secondary"/>{c.network}</div><h2 className="mt-4 max-w-3xl font-serif text-3xl leading-tight sm:text-4xl">{c.networkTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-7 opacity-85 sm:text-base">{c.networkText}</p></div><div className="flex flex-col gap-3 sm:flex-row lg:flex-col"><Link to="/para-profissionais" className="inline-flex min-h-11 items-center justify-center gap-2 rounded-2xl bg-secondary px-6 py-4 text-sm font-black text-secondary-foreground shadow-lg transition hover:-translate-y-0.5">{c.discover} <ArrowUpRight className="h-4 w-4"/></Link><Link to="/profissional/login" className="inline-flex min-h-11 items-center justify-center rounded-2xl border border-white/30 px-6 py-4 text-sm font-black transition hover:bg-white/10">{c.already}</Link></div></div></section>

      <a data-card="ebook-home-ldr" href="https://www.lucianoempreendendor.com/" target="_blank" rel="noreferrer" className="mt-4 block rounded-2xl border p-5 transition hover:-translate-y-0.5 hover:shadow-lg"><p className="text-xs font-black uppercase tracking-[.16em]">PLATAFORMA PARA EMPREENDEDORES</p><h2 className="mt-2 font-serif text-2xl">E-book e biblioteca — A Coragem de Começar</h2><p className="mt-2 text-sm">Acesse o e-book, conteúdos e recursos da plataforma.</p></a>
      <section className="mt-4 grid gap-4 lg:grid-cols-[1.1fr_.9fr]">
        <div className="s8-card"><h2 className="font-serif text-2xl">Sistema S8 / Mentoria</h2><p className="mt-3 text-sm leading-6">Um percurso de oito encontros individuais de 50 minutos, conduzido pela LDR RH &amp; Estratégia, que estrutura o projeto de negócio do participante e conclui com um Plano de Desenvolvimento (PDE) personalizado.</p><Link to="/formulario" className="mt-5 inline-block rounded-lg bg-primary px-5 py-3 font-bold text-primary-foreground">Quero participar</Link></div>
        <div className="s8-card"><h2 className="font-serif text-2xl">Outras páginas do ecossistema</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">Conheça serviços, soluções corporativas e conteúdos para empreendedores.</p><div className="mt-4 grid gap-2"><a href="https://ldrrhestrategia.com/" target="_blank" rel="noreferrer" className="rounded-xl border px-4 py-3 text-sm font-bold text-primary">Grupo LDR Essence</a><a href="https://www.lucianoempreendendor.com/" target="_blank" rel="noreferrer" className="rounded-xl border px-4 py-3 text-sm font-bold text-primary">Luciano Empreendedor</a></div></div>
      </section>
    </main>
  </div>;
}
