import { Link, createFileRoute, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { clientCreateLdrPassCheckout } from "@/lib/ldr-pass.functions";

export const Route = createFileRoute("/ldr-pass")({head:()=>({meta:[{title:"LDR ONE | Assinatura única do Ecossistema LDR"},{name:"description",content:"Uma assinatura para todos os conteúdos digitais do Ecossistema LDR. Os serviços gratuitos continuam gratuitos."}]}),component:LdrOnePage});
const offers=[
 {name:"LDR FREE",description:"O que já é gratuito continua gratuito.",monthly:"Grátis",annual:"Grátis",items:["Cadastro e perfil gratuitos","Rede Acadêmica e recursos gratuitos","Vagas e candidaturas gratuitas","Cursos e conteúdos abertos"]},
 {name:"LDR ONE Individual",description:"Uma assinatura para o catálogo digital completo.",monthly:"€ 39,90 / mês",annual:"€ 399 / ano",items:["Todos os cursos e formações digitais disponíveis","Todos os eBooks e publicações digitais","Ferramentas e benefícios do ecossistema","Acesso aos serviços profissionais conforme créditos contratados"]},
 {name:"LDR ONE Business",description:"Uma assinatura por colaborador, com recursos empresariais.",monthly:"€ 19,90 / colaborador / mês",annual:"€ 199 / colaborador / ano",items:["Todo o catálogo digital para colaboradores elegíveis","Painel e ferramentas empresariais","Recursos de carreira e desenvolvimento","Serviços humanos conforme créditos e contrato"]}
];
function checkoutErrorMessage(err:unknown){\n const raw=err instanceof Error?err.message:String(err??"");\n if(/Unauthorized|authenticated session/i.test(raw))return "Entre na sua conta para contratar o LDR ONE.";\n if(/Acesso do cliente não disponível/i.test(raw))return "Seu cadastro de cliente precisa ser concluído antes da assinatura.";\n if(/já possui um LDR ONE/i.test(raw))return "Você já possui uma assinatura LDR ONE em andamento.";\n if(/Pagamento LIVE indisponível|Preço LDR ONE indisponível/i.test(raw))return "Pagamento temporariamente indisponível. Tente novamente em instantes.";\n return raw&&raw!=="Error"?raw:"Não foi possível abrir o pagamento. Tente novamente.";\n}\nfunction LdrOnePage(){
 const [billing,setBilling]=useState<"monthly"|"annual">("monthly"),[seats,setSeats]=useState(5),[busy,setBusy]=useState<number|null>(null),[error,setError]=useState("");const navigate=useNavigate();
 async function buy(i:number){setError("");setBusy(i);try{const r=await clientCreateLdrPassCheckout({data:{plan:i===1?"individual":"business",market:"EU",billing,seats:i===1?1:seats,source:"ecossistema"}});if(!r?.url)throw Error("O checkout não retornou um endereço de pagamento.");window.location.href=r.url}catch(err){console.error("LDR ONE checkout failed",err);setError(checkoutErrorMessage(err));setBusy(null)}}
 return <main className="min-h-screen bg-[#070b17] text-white"><section className="mx-auto max-w-6xl px-5 py-14 sm:py-20"><Link to="/ecossistema" className="text-sm font-bold text-[#f4c76b]">← Ecossistema LDR</Link><p className="mt-10 text-xs font-black uppercase tracking-[.22em] text-[#f4c76b]">Assinatura única</p><h1 className="mt-4 max-w-4xl font-serif text-4xl font-bold leading-tight sm:text-6xl">LDR ONE. Todo o ecossistema, uma assinatura.</h1><p className="mt-5 max-w-3xl text-lg text-white/75">Todos os cursos e formações digitais disponíveis, eBooks e publicações em uma única assinatura. Os recursos gratuitos permanecem gratuitos.</p><div className="mt-8 flex flex-wrap gap-3"><button type="button" aria-pressed={billing==="monthly"} onClick={()=>setBilling("monthly")} className={`rounded-full px-6 py-3 font-bold ${billing==="monthly"?"bg-[#f4c76b] text-[#1f1303]":"border border-white/30"}`}>Mensal</button><button type="button" aria-pressed={billing==="annual"} onClick={()=>setBilling("annual")} className={`rounded-full px-6 py-3 font-bold ${billing==="annual"?"bg-[#f4c76b] text-[#1f1303]":"border border-white/30"}`}>Anual</button></div>{error&&<p className="mt-4 text-sm text-red-200">{error}</p>}</section>
 <section className="mx-auto grid max-w-6xl gap-5 px-5 pb-16 lg:grid-cols-3">{offers.map((o,i)=><article key={o.name} className={`flex flex-col rounded-[28px] border p-7 ${i===1?"border-[#f4c76b] bg-[#f4c76b]/[.08]":"border-white/20 bg-white/[.05]"}`}><p className="text-xs font-bold uppercase tracking-widest text-[#f4c76b]">{i===0?"Acesso aberto":i===1?"Pessoas":"Empresas"}</p><h2 className="mt-3 font-serif text-3xl font-bold">{o.name}</h2><p className="mt-3 min-h-14 text-white/70">{o.description}</p><p className="mt-6 text-2xl font-black">{billing==="monthly"?o.monthly:o.annual}</p>{i===2&&<div className="mt-4 rounded-xl border border-white/20 p-4"><label htmlFor="ldr-one-seats" className="block text-sm font-semibold">Quantidade de colaboradores (mínimo 5)</label><input id="ldr-one-seats" type="number" min={5} max={10000} value={seats} onChange={e=>setSeats(Math.max(5,Math.min(10000,Number(e.target.value)||5)))} className="mt-2 w-full rounded-lg bg-white px-3 py-2 text-[#081326]"/><p className="mt-3 text-sm text-white/80">Total: {(seats*(billing==="monthly"?19.9:199)).toLocaleString("pt-PT",{style:"currency",currency:"EUR"})}</p></div>}<ul className="mt-7 flex-1 space-y-4">{o.items.map(x=><li key={x} className="text-sm leading-6 text-white/80">✓ {x}</li>)}</ul>{i===0?<Link to="/ecossistema" className="mt-8 rounded-xl bg-[#f4c76b] px-5 py-3 text-center font-black text-[#1f1303]">Explorar gratuitamente</Link>:<button type="button" disabled={busy!==null} onClick={()=>buy(i)} className="mt-8 rounded-xl bg-[#f4c76b] px-5 py-3 text-center font-black text-[#1f1303] disabled:opacity-60">{busy===i?"Abrindo pagamento…":"Assinar agora"}</button>}</article>)}</section></main>
}
