import { Link, createFileRoute } from "@tanstack/react-router";
import { useEffect, useRef, useState } from "react";
import { clientCreateLdrPassCheckout } from "@/lib/ldr-pass.functions";

export const Route = createFileRoute("/ldr-pass")({validateSearch:(search:Record<string,unknown>)=>({plan:search.plan==="business"?"business" as const:"individual" as const,checkout:search.checkout==="resume"?"resume" as const:undefined,billing:search.billing==="annual"?"annual" as const:"monthly" as const,seats:Math.max(2,Math.min(10000,Number(search.seats)||2)),market:search.market==="BR"?"BR" as const:"EU" as const}),head:()=>({meta:[{title:"LDR ONE | Assinatura única do Ecossistema LDR"},{name:"description",content:"Uma assinatura para todos os conteúdos digitais do Ecossistema LDR. Os serviços gratuitos continuam gratuitos."}]}),component:LdrOnePage});
const offers=[
 {name:"LDR FREE",description:"O que já é gratuito continua gratuito.",monthly:"Grátis",annual:"Grátis",items:["Cadastro e perfil gratuitos","Rede Acadêmica e recursos gratuitos","Vagas e candidaturas gratuitas","Cursos e conteúdos abertos"]},
 {name:"LDR ONE Individual",description:"Uma assinatura para o catálogo digital completo.",monthly:"€ 39,90 / mês",annual:"€ 399 / ano",monthlyBR:"R$ 236,15 / mês",annualBR:"R$ 2.361,52 / ano",items:["Todos os cursos e formações digitais disponíveis","Todos os eBooks e publicações digitais","Ferramentas e benefícios do ecossistema","Acesso aos serviços profissionais conforme créditos contratados"]},
 {name:"LDR ONE Business",description:"Uma assinatura por colaborador, com recursos empresariais.",monthly:"€ 19,90 / colaborador / mês",annual:"€ 199 / colaborador / ano",monthlyBR:"R$ 117,78 / colaborador / mês",annualBR:"R$ 1.177,80 / colaborador / ano",items:["Todo o catálogo digital para colaboradores elegíveis","Painel e ferramentas empresariais","Recursos de carreira e desenvolvimento","Serviços humanos conforme créditos e contrato"]}
];
function checkoutErrorMessage(err:unknown){
 const raw=err instanceof Error?err.message:String(err??"");
 if(/Unauthorized|authenticated session/i.test(raw))return "Entre na sua conta para contratar o LDR ONE.";
 if(/Acesso do cliente não disponível/i.test(raw))return "Seu cadastro de cliente precisa ser concluído antes da assinatura.";
 if(/já possui um LDR ONE/i.test(raw))return "Você já possui uma assinatura LDR ONE em andamento.";
 if(/Pagamento LIVE indisponível|Preço LDR ONE indisponível/i.test(raw))return "Pagamento temporariamente indisponível. Tente novamente em instantes.";
 return raw&&raw!=="Error"?raw:"Não foi possível abrir o pagamento. Tente novamente.";
}
function LdrOnePage(){
 const search=Route.useSearch();
 const [billing,setBilling]=useState<"monthly"|"annual">(search.billing),[market,setMarket]=useState<"EU"|"BR">(search.market),[seatsInput,setSeatsInput]=useState(String(search.seats)),[busy,setBusy]=useState<number|null>(null),[error,setError]=useState("");
 const seats=Math.max(2,Math.min(10000,Number.parseInt(seatsInput,10)||2));
 async function buy(i:number,resuming=false){setError("");setBusy(i);try{const r=await clientCreateLdrPassCheckout({data:{plan:i===1?"individual":"business",market,billing,seats:i===1?1:seats,source:"ecossistema"}});if(!r?.url)throw Error("O checkout não retornou um endereço de pagamento.");window.location.href=r.url}catch(err){if(/Unauthorized|authenticated session/i.test(err instanceof Error?err.message:String(err))){if(resuming){setError("Sua sessão não foi confirmada. Entre novamente e toque em Assinar agora.");setBusy(null);return;}window.location.assign(`/cliente/login?next=${encodeURIComponent(`/ldr-pass?plan=${i===1?"individual":"business"}&billing=${billing}&seats=${seats}&market=${market}&checkout=resume`)}`);return;}console.error("LDR ONE checkout failed",err);setError(checkoutErrorMessage(err));setBusy(null)}}
 const resumed=useRef(false);
 useEffect(()=>{
  if(search.checkout!=="resume"||resumed.current)return;
  resumed.current=true;
  // Consume the navigation intent before requesting a session: a reload must not repeat it.
  const url=new URL(window.location.href);url.searchParams.delete("checkout");
  window.history.replaceState(window.history.state,"",`${url.pathname}${url.search}${url.hash}`);
  void buy(search.plan==="business"?2:1,true);
 },[search.checkout,search.plan]);
 return <main className="min-h-screen bg-[#070b17] text-white"><section className="mx-auto max-w-6xl px-5 py-14 sm:py-20"><Link to="/ecossistema" className="text-sm font-bold text-[#f4c76b]">← Ecossistema LDR</Link><p className="mt-10 text-xs font-black uppercase tracking-[.22em] text-[#f4c76b]">Assinatura única</p><h1 className="mt-4 max-w-4xl font-serif text-4xl font-bold leading-tight sm:text-6xl">LDR ONE. Todo o ecossistema, uma assinatura.</h1><p className="mt-5 max-w-3xl text-lg text-white/75">O Ecossistema LDR é online e você pode começar gratuitamente. Crie seu acesso LDR FREE e descubra conteúdos, oportunidades e recursos para aprender, desenvolver sua carreira e cuidar do seu bem-estar.</p><div className="mt-8 flex flex-wrap gap-3"><button type="button" aria-pressed={market==="EU"} onClick={()=>setMarket("EU")} className={`rounded-full px-6 py-3 font-bold ${market==="EU"?"bg-white text-[#081326]":"border border-white/30"}`}>Europa · EUR</button><button type="button" aria-pressed={market==="BR"} onClick={()=>setMarket("BR")} className={`rounded-full px-6 py-3 font-bold ${market==="BR"?"bg-white text-[#081326]":"border border-white/30"}`}>Brasil · BRL</button></div><div className="mt-3 flex flex-wrap gap-3"><button type="button" aria-pressed={billing==="monthly"} onClick={()=>setBilling("monthly")} className={`rounded-full px-6 py-3 font-bold ${billing==="monthly"?"bg-[#f4c76b] text-[#1f1303]":"border border-white/30"}`}>Mensal</button><button type="button" aria-pressed={billing==="annual"} onClick={()=>setBilling("annual")} className={`rounded-full px-6 py-3 font-bold ${billing==="annual"?"bg-[#f4c76b] text-[#1f1303]":"border border-white/30"}`}>Anual</button></div>{error&&<p className="mt-4 text-sm text-red-200">{error}</p>}</section>
 <section className="mx-auto grid max-w-6xl gap-5 px-5 pb-16 lg:grid-cols-3">{offers.map((o,i)=><article key={o.name} className={`flex flex-col rounded-[28px] border p-7 ${i===1?"border-[#f4c76b] bg-[#f4c76b]/[.08]":"border-white/20 bg-white/[.05]"}`}><p className="text-xs font-bold uppercase tracking-widest text-[#f4c76b]">{i===0?"Acesso aberto":i===1?"Pessoas":"Empresas"}</p><h2 className="mt-3 font-serif text-3xl font-bold">{o.name}</h2><p className="mt-3 min-h-14 text-white/70">{o.description}</p><p className="mt-6 text-2xl font-black">{market==="EU"?(billing==="monthly"?o.monthly:o.annual):(i===0?"Grátis":billing==="monthly"?o.monthlyBR:o.annualBR)}</p>{i===2&&<div className="mt-4 rounded-xl border border-white/20 p-4"><label htmlFor="ldr-one-seats" className="block text-sm font-semibold">Quantidade de colaboradores (mínimo 2)</label><div className="mt-2 flex items-stretch gap-2"><button type="button" aria-label="Diminuir colaboradores" onClick={()=>setSeatsInput(String(Math.max(2,seats-1)))} className="min-h-12 min-w-12 rounded-lg border border-white/30 bg-white/10 text-xl font-black text-white">−</button><input id="ldr-one-seats" type="number" inputMode="numeric" min={2} max={10000} step={1} value={seatsInput} onChange={e=>{const v=e.target.value;if(v===""||/^\d{0,5}$/.test(v))setSeatsInput(v)}} onBlur={()=>setSeatsInput(String(seats))} className="min-h-12 min-w-0 flex-1 rounded-lg bg-white px-4 py-3 text-lg font-bold text-[#081326]" /><button type="button" aria-label="Adicionar colaborador" onClick={()=>setSeatsInput(String(Math.min(10000,seats+1)))} className="min-h-12 min-w-12 rounded-lg border border-white/30 bg-white/10 text-xl font-black text-white">+</button></div><p className="mt-3 text-sm text-white/80">{market==="EU"?<>Total: {(seats*(billing==="monthly"?19.9:199)).toLocaleString("pt-PT",{style:"currency",currency:"EUR"})}</>:<>Total: {(seats*(billing==="monthly"?117.78:1177.80)).toLocaleString("pt-BR",{style:"currency",currency:"BRL"})}</>}</p></div>}<ul className="mt-7 flex-1 space-y-4">{o.items.map(x=><li key={x} className="text-sm leading-6 text-white/80">✓ {x}</li>)}</ul>{i===0?<Link to="/ecossistema" className="mt-8 rounded-xl bg-[#f4c76b] px-5 py-3 text-center font-black text-[#1f1303]">Começar grátis</Link>:<button type="button" disabled={busy!==null} onClick={()=>buy(i)} className="mt-8 rounded-xl bg-[#f4c76b] px-5 py-3 text-center font-black text-[#1f1303] disabled:opacity-60">{busy===i?"Abrindo pagamento…":"Assinar agora"}</button>}</article>)}</section></main>
}
