import { Link, createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useState } from "react";
import { BadgeCheck, BookOpen, CalendarDays, ChartNoAxesCombined, CircleDollarSign, Globe2, GraduationCap, HeartHandshake, ShieldCheck, Sparkles, UsersRound } from "lucide-react";
import { LanguageSelect, useI18n } from "@/lib/i18n";
import { networkLanding } from "@/lib/professional-network.functions";

export const Route = createFileRoute("/para-profissionais")({
  head: () => ({ meta: [{ title: "Rede de Profissionais LDR — Faça parte" }, { name: "description", content: "Perfil profissional, agenda, checkout, treinamentos ao vivo, comunidade e ferramentas em um único ambiente." }] }),
  component: ProfessionalsSales,
});

type AnyRow = Record<string, any>;
const COPY = {
pt:{hero:"FAÇA PARTE DA REDE DE PROFISSIONAIS LDR",sub:"Uma estrutura criada para profissionais que desejam fortalecer sua presença, organizar seus serviços e desenvolver sua atuação dentro de uma comunidade profissional.",join:"QUERO FAZER PARTE",plans:"CONHECER OS PLANOS",concept:"Você não entra apenas em uma plataforma. Você entra em um ecossistema profissional.",more:"MAIS DO QUE UM PERFIL PROFISSIONAL",how:"COMO FUNCIONA",training:"TREINAMENTOS AO VIVO LDR",payments:"ATENDIMENTOS E PAGAMENTOS",plansTitle:"PLANOS",faq:"PERGUNTAS FREQUENTES",transparency:"TRANSPARÊNCIA",final:"CRIE SUA PRESENÇA PROFISSIONAL NA REDE LDR",noGuarantee:"A participação na Rede de Profissionais LDR não representa garantia de clientes, atendimentos ou faturamento.",commission:"Comissão inicial da plataforma: 10% sobre atendimentos efetivamente pagos pela plataforma, além da assinatura mensal.",monthly:"Repasses são organizados uma vez por mês, conforme calendário, documentação aplicável e condições dos termos.",directory:"Encontrar profissionais"},
en:{hero:"JOIN THE LDR PROFESSIONAL NETWORK",sub:"A structure for professionals who want to strengthen their presence, organize services and grow within a professional community.",join:"JOIN THE NETWORK",plans:"VIEW PLANS",concept:"You are not just joining a platform. You are joining a professional ecosystem.",more:"MORE THAN A PROFESSIONAL PROFILE",how:"HOW IT WORKS",training:"LDR LIVE TRAINING",payments:"BOOKINGS AND PAYMENTS",plansTitle:"PLANS",faq:"FAQ",transparency:"TRANSPARENCY",final:"BUILD YOUR PROFESSIONAL PRESENCE WITH LDR",noGuarantee:"Participation in the LDR Professional Network does not guarantee clients, appointments or revenue.",commission:"Initial platform commission: 10% on appointments effectively paid through the platform, in addition to the monthly subscription.",monthly:"Payouts are organized monthly according to the platform calendar, applicable documents and terms.",directory:"Find professionals"},
fr:{hero:"REJOIGNEZ LE RÉSEAU DE PROFESSIONNELS LDR",sub:"Une structure pour renforcer votre présence, organiser vos services et développer votre activité au sein d’une communauté professionnelle.",join:"JE VEUX PARTICIPER",plans:"VOIR LES PLANS",concept:"Vous ne rejoignez pas seulement une plateforme. Vous rejoignez un écosystème professionnel.",more:"PLUS QU’UN PROFIL PROFESSIONNEL",how:"COMMENT ÇA MARCHE",training:"FORMATIONS LDR EN DIRECT",payments:"RENDEZ-VOUS ET PAIEMENTS",plansTitle:"PLANS",faq:"QUESTIONS FRÉQUENTES",transparency:"TRANSPARENCE",final:"DÉVELOPPEZ VOTRE PRÉSENCE PROFESSIONNELLE AVEC LDR",noGuarantee:"La participation au Réseau de Professionnels LDR ne garantit pas de clients, rendez-vous ou chiffre d’affaires.",commission:"Commission initiale de la plateforme : 10 % sur les prestations effectivement payées via la plateforme, en plus de l’abonnement mensuel.",monthly:"Les versements sont organisés mensuellement selon le calendrier, les documents applicables et les conditions.",directory:"Trouver un professionnel"},
es:{hero:"FORMA PARTE DE LA RED DE PROFESIONALES LDR",sub:"Una estructura para fortalecer tu presencia, organizar servicios y desarrollar tu actividad dentro de una comunidad profesional.",join:"QUIERO PARTICIPAR",plans:"VER PLANES",concept:"No entras solo en una plataforma. Entras en un ecosistema profesional.",more:"MÁS QUE UN PERFIL PROFESIONAL",how:"CÓMO FUNCIONA",training:"FORMACIONES LDR EN VIVO",payments:"CITAS Y PAGOS",plansTitle:"PLANES",faq:"PREGUNTAS FRECUENTES",transparency:"TRANSPARENCIA",final:"DESARROLLA TU PRESENCIA PROFESIONAL CON LDR",noGuarantee:"Participar en la Red de Profesionales LDR no garantiza clientes, citas ni facturación.",commission:"Comisión inicial de la plataforma: 10% sobre las citas efectivamente pagadas mediante la plataforma, además de la suscripción mensual.",monthly:"Los pagos a profesionales se organizan mensualmente según calendario, documentación aplicable y condiciones.",directory:"Encontrar profesionales"}
} as const;

const BENEFITS=["Perfil profissional público","Página própria dentro da plataforma","Agenda integrada","Checkout de atendimentos","Painel profissional e financeiro","Histórico de atendimentos","Gestão de disponibilidade","Treinamentos ao vivo","Palestras e benefícios","Comunidade profissional","Serviços de marketing opcionais","Consultoria e desenvolvimento profissional"];
const TRAINING=["Marketing profissional","Atendimento e experiência do cliente","Organização financeira","Carreira e posicionamento","Comunicação","Empreendedorismo","IA aplicada ao trabalho","Gestão"];
const STEPS=["CRIE SEU PERFIL","ESCOLHA SEU PLANO","ENVIE SUAS INFORMAÇÕES","AGUARDE A ANÁLISE","PUBLIQUE SEUS SERVIÇOS","GERENCIE TUDO PELO PAINEL"];
const FAQ=[
["A plataforma garante clientes?","Não. A Rede LDR oferece estrutura, visibilidade, tecnologia, comunidade e ferramentas para o desenvolvimento profissional, mas não garante quantidade de clientes, atendimentos ou faturamento."],
["Existe comissão?","Sim. Inicialmente a comissão é de 10% sobre atendimentos pagos através da plataforma, além da assinatura mensal."],
["Quando recebo?","Os repasses são organizados mensalmente, conforme calendário da plataforma, documentação exigida e condições previstas nos termos."],
["Tenho treinamento?","Sim. Os membros terão acesso aos treinamentos ao vivo incluídos conforme o plano e calendário da comunidade."],
["Posso atender online?","Depende da natureza do serviço, da qualificação e das regras profissionais e legais aplicáveis ao país do profissional e do cliente."]
];

function money(cents:number,currency:string,locale:string){return new Intl.NumberFormat(locale==="pt"?"pt-BR":locale,{style:"currency",currency}).format(cents/100)}
function ProfessionalsSales(){
 const {locale}=useI18n(); const copy=COPY[locale]; const load=useServerFn(networkLanding); const [data,setData]=useState<any>(null);
 useEffect(()=>{void load().then(setData)},[load]);
 const plans=(data?.plans??[]) as AnyRow[]; const luciano=(data?.profiles??[]).find((p:AnyRow)=>p.slug==="luciano-rodrigues-almeida");
 return <div className="min-h-screen bg-background text-foreground">
  <header className="sticky top-0 z-40 border-b bg-background/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-4 sm:px-6"><Link to="/" className="font-serif text-xl font-bold">Grupo LDR Essence</Link><div className="flex items-center gap-2"><Link to="/profissionais" className="hidden rounded-lg px-3 py-2 text-sm font-bold sm:inline-flex">{copy.directory}</Link><LanguageSelect/></div></div></header>
  <main>
   <section className="overflow-hidden border-b bg-gradient-to-br from-primary via-primary to-primary/80 text-primary-foreground"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-16 sm:px-6 lg:grid-cols-[1.15fr_.85fr] lg:py-24"><div><p className="text-xs font-black uppercase tracking-[.2em] text-secondary">Rede de Profissionais LDR</p><h1 className="mt-4 max-w-4xl font-serif text-4xl leading-tight sm:text-5xl lg:text-6xl">{copy.hero}</h1><p className="mt-5 max-w-3xl text-lg leading-8 opacity-90">{copy.sub}</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/profissional/login" className="rounded-xl bg-secondary px-6 py-3 font-black text-secondary-foreground">{copy.join}</Link><a href="#planos" className="rounded-xl border border-white/40 px-6 py-3 font-bold">{copy.plans}</a></div></div><div className="rounded-3xl border border-white/20 bg-white/10 p-7 backdrop-blur"><Sparkles className="h-9 w-9 text-secondary"/><p className="mt-5 font-serif text-3xl leading-tight">{copy.concept}</p><p className="mt-5 text-sm leading-6 opacity-85">Perfil profissional, estrutura digital, treinamentos ao vivo, comunidade e ferramentas reunidas em um único ambiente.</p></div></div></section>
   <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><p className="text-xs font-black uppercase tracking-[.18em] text-primary">Rede LDR</p><h2 className="mt-2 font-serif text-3xl">{copy.more}</h2><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{BENEFITS.map((b,i)=>{const I=[BadgeCheck,Globe2,CalendarDays,CircleDollarSign,ChartNoAxesCombined,UsersRound,GraduationCap,HeartHandshake,BookOpen,ShieldCheck,Sparkles,UsersRound][i];return <div key={b} className="rounded-2xl border bg-card p-5"><I className="h-6 w-6 text-primary"/><p className="mt-3 font-bold">{b}</p></div>})}</div></section>
   <section className="border-y bg-muted/35"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><h2 className="font-serif text-3xl">{copy.how}</h2><div className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{STEPS.map((s,i)=><div key={s} className="rounded-2xl border bg-card p-5"><span className="text-3xl font-black text-primary/30">{i+1}</span><p className="mt-3 font-black">{s}</p></div>)}</div></div></section>
   {luciano?<section className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><p className="text-xs font-black uppercase tracking-[.18em] text-primary">Perfil profissional real</p><div className="mt-4 grid gap-5 rounded-3xl border bg-card p-6 lg:grid-cols-[1fr_auto]"><div><h2 className="font-serif text-3xl">{luciano.display_name}</h2><p className="mt-2 font-bold text-primary">{luciano.professional_title}</p><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">{luciano.about}</p><div className="mt-4 flex flex-wrap gap-2">{(luciano.specialties??[]).slice(0,7).map((s:string)=><span key={s} className="rounded-full bg-primary/8 px-3 py-1 text-xs font-bold">{s}</span>)}</div></div><Link to="/profissional/$slug" params={{slug:luciano.slug}} className="self-end rounded-xl bg-primary px-5 py-3 text-center font-bold text-primary-foreground">VER PERFIL</Link></div></section>:null}
   <section className="border-y bg-primary/5"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><h2 className="font-serif text-3xl">{copy.training}</h2><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Encontros AO VIVO, com data e horário publicados no painel e exibição automática conforme o fuso local do participante.</p><div className="mt-6 flex flex-wrap gap-2">{TRAINING.map(t=><span key={t} className="rounded-full border bg-card px-4 py-2 text-sm font-bold">{t}</span>)}</div></div></section>
   <section className="mx-auto grid max-w-7xl gap-5 px-4 py-14 sm:px-6 lg:grid-cols-2"><div className="rounded-3xl border bg-card p-7"><h2 className="font-serif text-3xl">{copy.payments}</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">Perfil → serviço → modalidade → data → horário → checkout → pagamento → confirmação → atendimento. Quando o serviço estiver no marketplace, o pagamento acontece pelo site.</p><p className="mt-4 text-sm font-semibold">{copy.commission}</p></div><div className="rounded-3xl border bg-card p-7"><h2 className="font-serif text-3xl">Repasse mensal</h2><p className="mt-4 text-sm leading-6 text-muted-foreground">Valor do serviço, comissão LDR, taxas, reembolsos, ajustes e líquido previsto aparecem separadamente no painel.</p><p className="mt-4 text-sm font-semibold">{copy.monthly}</p></div></section>
   <section id="planos" className="border-y bg-muted/35"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><h2 className="font-serif text-3xl">{copy.plansTitle}</h2><div className="mt-7 grid gap-4 lg:grid-cols-2">{plans.map((p:AnyRow)=><article key={p.id} className={`rounded-3xl border bg-card p-7 ${p.plan_code==="pro"?"border-primary shadow-lg":""}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.16em] text-primary">{p.market==="BR"?"Brasil":"Europa"}</p><h3 className="mt-2 font-serif text-2xl">{p.name}</h3></div>{p.plan_code==="pro"?<span className="rounded-full bg-primary px-3 py-1 text-xs font-black text-primary-foreground">MAIS RECURSOS</span>:null}</div><p className="mt-5 text-3xl font-black">{money(p.amount_cents,p.currency,locale)} <span className="text-sm font-semibold text-muted-foreground">/ mês</span></p><ul className="mt-5 space-y-2 text-sm">{(p.benefits??[]).map((b:string)=><li key={b} className="flex gap-2"><span className="font-black text-primary">✓</span>{b}</li>)}</ul><Link to="/profissional/login" className="mt-6 block rounded-xl bg-primary px-5 py-3 text-center font-black text-primary-foreground">CRIAR MEU PERFIL</Link></article>)}</div></div></section>
   <section className="mx-auto max-w-5xl px-4 py-14 sm:px-6"><h2 className="font-serif text-3xl">{copy.faq}</h2><div className="mt-6 space-y-3">{FAQ.map(([q,a])=><details key={q} className="rounded-2xl border bg-card p-5"><summary className="cursor-pointer font-bold">{q}</summary><p className="mt-3 text-sm leading-6 text-muted-foreground">{a}</p></details>)}</div></section>
   <section className="border-y bg-primary/5"><div className="mx-auto max-w-5xl px-4 py-12 text-sm leading-6 sm:px-6"><h2 className="font-serif text-2xl">{copy.transparency}</h2><p className="mt-4">{copy.noGuarantee}</p><p className="mt-2">A ativação do perfil depende da categoria, país, documentação aplicável, assinatura e aprovação da LDR. Títulos profissionais regulamentados ficam em revisão administrativa até validação dos requisitos configurados.</p><p className="mt-2">Serviços de saúde mental não substituem serviços de emergência.</p><Link to="/rede-profissionais/termos" className="mt-4 inline-block font-bold text-primary underline">Ler termos, privacidade, cancelamento, reembolso e repasse</Link></div></section>
   <section className="bg-primary text-primary-foreground"><div className="mx-auto max-w-5xl px-4 py-16 text-center sm:px-6"><h2 className="font-serif text-4xl">{copy.final}</h2><div className="mt-7 flex flex-wrap justify-center gap-3"><Link to="/profissional/login" className="rounded-xl bg-secondary px-6 py-3 font-black text-secondary-foreground">{copy.join}</Link><Link to="/profissionais" className="rounded-xl border border-white/40 px-6 py-3 font-bold">{copy.directory}</Link></div></div></section>
  </main>
 </div>
}
