import { Link, createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useMemo, useState } from "react";
import { BadgeCheck, CalendarDays, Clock3, Globe2, Languages, MapPin, Monitor, ShieldCheck, UserRound } from "lucide-react";
import { toast } from "sonner";
import { LanguageSelect, useI18n } from "@/lib/i18n";
import { marketplaceBookingCheckout, publicProfessional } from "@/lib/professional-network.functions";

export const Route = createFileRoute("/profissional/$slug")({
  loader: ({ params }) => publicProfessional({ data: { slug: params.slug } }),
  head: ({ loaderData, params }) => {
    const profile = (loaderData as any)?.profile;
    const name = profile?.display_name || params.slug.replace(/-/g, " ");
    const title = profile?.professional_title ? `${name} — ${profile.professional_title} | Rede LDR` : `${name} | Rede de Profissionais LDR`;
    const description = profile?.about ? String(profile.about).slice(0, 155) : "Perfil profissional na Rede de Profissionais LDR.";
    return { meta: [{ title }, { name: "description", content: description }, { name: "robots", content: "index,follow" }] };
  },
  component: PublicProfessionalPage,
});
type AnyRow=Record<string,any>;
const COPY={
pt:{back:"Voltar ao diretório",about:"Sobre",experience:"Experiência",education:"Formação",specialties:"Áreas e especialidades",services:"Serviços",online:"Online",present:"Presencial",duration:"Duração",availability:"Disponibilidade",noAvailability:"Sem horários publicados neste momento.",view:"VER HORÁRIOS",book:"AGENDAR",choose:"Escolha o serviço e informe um horário disponível",name:"Seu nome",email:"Seu e-mail",date:"Data e horário",mode:"Modalidade",pay:"CONTINUAR PARA PAGAMENTO",opening:"Abrindo checkout…",support:"O agendamento e o pagamento deste serviço são feitos pelo site. WhatsApp fica disponível apenas para suporte quando apropriado.",provider:"Serviço prestado por profissional da Rede LDR",emergency:"Este serviço não substitui serviços de emergência.",verified:"Perfil verificado",docs:"Documentos profissionais verificados",identity:"Identidade verificada"},
en:{back:"Back to directory",about:"About",experience:"Experience",education:"Education",specialties:"Areas and specialties",services:"Services",online:"Online",present:"In person",duration:"Duration",availability:"Availability",noAvailability:"No times published right now.",view:"VIEW TIMES",book:"BOOK",choose:"Choose a service and enter an available time",name:"Your name",email:"Your email",date:"Date and time",mode:"Modality",pay:"CONTINUE TO PAYMENT",opening:"Opening checkout…",support:"Booking and payment are completed on the website. WhatsApp is only for support when appropriate.",provider:"Service provided by an LDR Network professional",emergency:"This service does not replace emergency services.",verified:"Verified profile",docs:"Professional documents verified",identity:"Identity verified"},
fr:{back:"Retour au répertoire",about:"À propos",experience:"Expérience",education:"Formation",specialties:"Domaines et spécialités",services:"Services",online:"En ligne",present:"Présentiel",duration:"Durée",availability:"Disponibilité",noAvailability:"Aucun horaire publié pour le moment.",view:"VOIR LES HORAIRES",book:"RÉSERVER",choose:"Choisissez un service et indiquez un horaire disponible",name:"Votre nom",email:"Votre e-mail",date:"Date et heure",mode:"Modalité",pay:"CONTINUER VERS LE PAIEMENT",opening:"Ouverture du paiement…",support:"La réservation et le paiement se font sur le site. WhatsApp est réservé au support lorsque cela est approprié.",provider:"Service fourni par un professionnel du Réseau LDR",emergency:"Ce service ne remplace pas les services d’urgence.",verified:"Profil verificado",docs:"Documents professionnels vérifiés",identity:"Identité vérifiée"},
es:{back:"Volver al directorio",about:"Sobre mí",experience:"Experiencia",education:"Formación",specialties:"Áreas y especialidades",services:"Servicios",online:"Online",present:"Presencial",duration:"Duración",availability:"Disponibilidad",noAvailability:"No hay horarios publicados en este momento.",view:"VER HORARIOS",book:"AGENDAR",choose:"Elige un servicio e indica un horario disponible",name:"Tu nombre",email:"Tu correo",date:"Fecha y hora",mode:"Modalidad",pay:"CONTINUAR AL PAGO",opening:"Abriendo pago…",support:"La reserva y el pago se realizan en el sitio. WhatsApp queda para soporte cuando sea apropiado.",provider:"Servicio prestado por un profesional de la Red LDR",emergency:"Este servicio no sustituye los servicios de emergencia.",verified:"Perfil verificado",docs:"Documentos profesionales verificados",identity:"Identidad verificada"}
} as const;
function money(cents:number|null,currency:string|null,locale:string){if(cents==null||!currency)return "—";return new Intl.NumberFormat(locale==="pt"?"pt-BR":locale,{style:"currency",currency}).format(cents/100)}
function PublicProfessionalPage(){
 const {slug}=Route.useParams(); const initialData=Route.useLoaderData(); const {locale}=useI18n(); const c=COPY[locale]; const checkout=useServerFn(marketplaceBookingCheckout); const data=initialData as any; const [selected,setSelected]=useState(""); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [date,setDate]=useState(""); const [mode,setMode]=useState<"online"|"in_person">("online"); const [busy,setBusy]=useState(false);
 const services=(data?.services??[]) as AnyRow[]; const service=services.find(s=>s.id===selected); const rules=((data?.availability??[]) as AnyRow[]).filter(r=>!selected||!r.professional_service_id||r.professional_service_id===selected);
 const days=useMemo(()=>{const map=["Dom","Seg","Ter","Qua","Qui","Sex","Sáb"];return [...new Set(rules.map(r=>`${map[Number(r.weekday)]??r.weekday} ${String(r.start_time).slice(0,5)}–${String(r.end_time).slice(0,5)} (${r.timezone})`))]},[rules]);
 useEffect(()=>{if(service){setMode(service.modality==="in_person"?"in_person":"online")}},[service]);
 if(!data)return <div className="min-h-screen grid place-items-center p-6 text-center"><div><h1 className="font-serif text-3xl">Perfil não disponível</h1><Link to="/profissionais" className="mt-4 inline-block underline">{c.back}</Link></div></div>;
 const p=data.profile;
 async function pay(){if(!service||!date){toast.error(c.choose);return;}setBusy(true);try{const local=new Date(date);const r=await checkout({data:{profileSlug:slug,serviceId:service.id,startAt:local.toISOString(),customerName:name,customerEmail:email,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||"Europe/Brussels",modality:mode}});window.location.assign(r.url);}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível abrir o checkout.");setBusy(false)}}
 return <div className="min-h-screen bg-background"><header className="sticky top-0 z-30 border-b bg-background/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-4 sm:px-6"><Link to="/profissionais" className="text-sm font-bold">← {c.back}</Link><LanguageSelect/></div></header><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><section className="rounded-3xl border bg-card p-6 sm:p-8"><div className="grid gap-7 lg:grid-cols-[auto_1fr_auto]"><div className="grid h-28 w-28 place-items-center overflow-hidden rounded-3xl bg-primary/10">{p.photo_url?<img src={p.photo_url} alt={p.display_name} className="h-full w-full object-cover"/>:<UserRound className="h-12 w-12 text-primary"/>}</div><div className="min-w-0"><h1 className="break-words font-serif text-4xl">{p.display_name}</h1><p className="mt-2 text-lg font-bold text-primary">{p.professional_title}</p><div className="mt-4 flex flex-wrap gap-2">{p.identity_verified?<span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary"><BadgeCheck className="mr-1 inline h-3 w-3"/>{c.identity}</span>:null}{p.documents_verified?<span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-bold text-primary"><ShieldCheck className="mr-1 inline h-3 w-3"/>{c.docs}</span>:null}{p.profile_verified?<span className="rounded-full bg-primary px-3 py-1 text-xs font-bold text-primary-foreground">{c.verified}</span>:null}</div><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-sm text-muted-foreground"><span><MapPin className="mr-1 inline h-4 w-4"/>{p.public_region||`${p.city??""} ${p.country_code}`}</span><span><Languages className="mr-1 inline h-4 w-4"/>{(p.languages??[]).map((x:string)=>x.toUpperCase()).join(" · ")}</span>{p.online_enabled?<span><Monitor className="mr-1 inline h-4 w-4"/>{c.online}</span>:null}{p.in_person_enabled?<span><Globe2 className="mr-1 inline h-4 w-4"/>{c.present}</span>:null}</div></div><a href="#agendar" className="self-end rounded-xl bg-primary px-5 py-3 text-center font-black text-primary-foreground">{c.book}</a></div></section>
 <div className="mt-6 grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div className="space-y-6"><section className="rounded-3xl border bg-card p-6"><h2 className="font-serif text-2xl">{c.about}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{p.about}</p></section><section className="grid gap-4 sm:grid-cols-2"><div className="rounded-3xl border bg-card p-6"><h2 className="font-serif text-2xl">{c.experience}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{p.experience_summary||"—"}</p></div><div className="rounded-3xl border bg-card p-6"><h2 className="font-serif text-2xl">{c.education}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{p.education_summary||"—"}</p></div></section><section className="rounded-3xl border bg-card p-6"><h2 className="font-serif text-2xl">{c.specialties}</h2><div className="mt-4 flex flex-wrap gap-2">{(p.specialties??[]).map((s:string)=><span key={s} className="rounded-full bg-primary/8 px-3 py-1.5 text-sm font-bold">{s}</span>)}</div></section><section className="rounded-3xl border bg-card p-6"><h2 className="font-serif text-2xl">{c.services}</h2><div className="mt-4 space-y-3">{services.map(s=><button key={s.id} onClick={()=>setSelected(s.id)} className={`w-full rounded-2xl border p-4 text-left transition ${selected===s.id?"border-primary bg-primary/5":"bg-background"}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-bold">{s.name}</p><p className="mt-1 text-sm text-muted-foreground">{s.description}</p><p className="mt-2 text-xs"><Clock3 className="mr-1 inline h-3 w-3"/>{s.duration_minutes} min · {s.modality==="online"?c.online:s.modality==="in_person"?c.present:`${c.online} / ${c.present}`}</p></div><strong>{money(s.price_cents,s.currency,locale)}</strong></div>{!s.booking_enabled?<p className="mt-2 text-xs font-semibold text-muted-foreground">Checkout ainda não publicado para este serviço.</p>:null}</button>)}</div></section></div>
 <aside id="agendar" className="h-fit rounded-3xl border bg-card p-6 lg:sticky lg:top-24"><h2 className="font-serif text-2xl">{c.book}</h2><p className="mt-2 text-sm text-muted-foreground">{c.choose}</p>{service?<><div className="mt-4 rounded-xl bg-primary/5 p-4 text-sm"><p className="font-bold">{service.name}</p><p className="mt-1">{money(service.price_cents,service.currency,locale)} · {service.duration_minutes} min</p></div><div className="mt-4"><p className="text-xs font-black uppercase tracking-wide text-muted-foreground">{c.availability}</p>{days.length?<div className="mt-2 flex flex-wrap gap-2">{days.map(x=><span key={x} className="rounded-lg border px-2.5 py-1 text-xs">{x}</span>)}</div>:<p className="mt-2 text-sm text-muted-foreground">{c.noAvailability}</p>}</div>{service.booking_enabled&&days.length?<div className="mt-5 grid gap-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder={c.name} className="rounded-xl border bg-background px-3 py-3 text-sm"/><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder={c.email} className="rounded-xl border bg-background px-3 py-3 text-sm"/><input value={date} onChange={e=>setDate(e.target.value)} type="datetime-local" className="rounded-xl border bg-background px-3 py-3 text-sm"/>{service.modality==="both"?<select value={mode} onChange={e=>setMode(e.target.value as any)} className="rounded-xl border bg-background px-3 py-3 text-sm"><option value="online">{c.online}</option><option value="in_person">{c.present}</option></select>:null}<button onClick={pay} disabled={busy} className="rounded-xl bg-primary px-4 py-3 font-black text-primary-foreground disabled:opacity-50">{busy?c.opening:c.pay}</button></div>:null}</>:<p className="mt-4 text-sm text-muted-foreground">{c.choose}</p>}<div className="mt-5 border-t pt-4 text-xs leading-5 text-muted-foreground"><p className="font-bold text-foreground">{c.provider}</p><p className="mt-2">{c.support}</p>{p.professional_title.toLowerCase().includes("psican")?<p className="mt-2">{c.emergency}</p>:null}</div></aside></div>
 </main></div>
}