import { Link, createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { ArrowUpRight, BadgeCheck, Globe2, Languages, MapPin, Monitor, Search, Sparkles, UserRound, UsersRound, X } from "lucide-react";
import { LanguageSelect, useI18n } from "@/lib/i18n";
import { networkLanding } from "@/lib/professional-network.functions";

export const Route = createFileRoute("/profissionais")({
  loader: () => networkLanding(),
  head: () => ({ meta: [
    { title: "Encontre um Profissional — Rede LDR" },
    { name: "description", content: "Encontre profissionais da Rede de Profissionais LDR por área, país, cidade, idioma e modalidade." },
    { property: "og:title", content: "Rede de Profissionais LDR" },
    { property: "og:description", content: "Profissionais com presença organizada, serviços e modalidades de atendimento em um único ecossistema." },
  ] }),
  component: Directory,
});

type AnyRow=Record<string,any>;
const COPY={
pt:{title:"ENCONTRE O PROFISSIONAL CERTO PARA O SEU MOMENTO",sub:"Explore profissionais com perfil ativo na Rede LDR e filtre por área, localização, idioma e modalidade de atendimento.",search:"Buscar por nome, área ou especialidade",area:"Área profissional",country:"País",language:"Idioma",all:"Todos",online:"Online",present:"Presencial",profile:"VER PERFIL",empty:"Nenhum profissional encontrado com estes filtros.",back:"Para profissionais",eyebrow:"Rede de Profissionais LDR",ctaTitle:"Você é profissional?",ctaText:"Apresente seus serviços, organize sua presença profissional e faça parte de um ecossistema com tecnologia, comunidade e desenvolvimento.",cta:"CONHECER A REDE LDR",results:"profissionais encontrados",oneResult:"profissional encontrado",clear:"Limpar filtros",active:"Perfil ativo",premium:"Uma rede criada para aproximar pessoas e profissionais",premiumText:"Perfis organizados, busca inteligente e uma experiência simples para encontrar o atendimento adequado."},
en:{title:"FIND THE RIGHT PROFESSIONAL FOR YOUR MOMENT",sub:"Explore active LDR Network professionals and filter by area, location, language and service modality.",search:"Search by name, area or specialty",area:"Professional area",country:"Country",language:"Language",all:"All",online:"Online",present:"In person",profile:"VIEW PROFILE",empty:"No professionals match these filters.",back:"For professionals",eyebrow:"LDR Professional Network",ctaTitle:"Are you a professional?",ctaText:"Showcase your services, organize your professional presence and join an ecosystem with technology, community and development.",cta:"DISCOVER THE LDR NETWORK",results:"professionals found",oneResult:"professional found",clear:"Clear filters",active:"Active profile",premium:"A network designed to connect people and professionals",premiumText:"Organized profiles, smart search and a simple experience to find the right service."},
fr:{title:"TROUVEZ LE PROFESSIONNEL ADAPTÉ À VOTRE MOMENT",sub:"Explorez les professionnels actifs du Réseau LDR et filtrez par domaine, lieu, langue et modalité.",search:"Rechercher par nom, domaine ou spécialité",area:"Domaine professionnel",country:"Pays",language:"Langue",all:"Tous",online:"En ligne",present:"Présentiel",profile:"VOIR LE PROFIL",empty:"Aucun professionnel ne correspond à ces filtres.",back:"Pour les professionnels",eyebrow:"Réseau de Professionnels LDR",ctaTitle:"Vous êtes professionnel ?",ctaText:"Présentez vos services, organisez votre présence professionnelle et rejoignez un écosystème de technologie, communauté et développement.",cta:"DÉCOUVRIR LE RÉSEAU LDR",results:"professionnels trouvés",oneResult:"professionnel trouvé",clear:"Effacer les filtres",active:"Profil actif",premium:"Un réseau conçu pour rapprocher les personnes et les professionnels",premiumText:"Profils organisés, recherche intelligente et expérience simple pour trouver le service adapté."},
es:{title:"ENCUENTRA AL PROFESIONAL ADECUADO PARA TU MOMENTO",sub:"Explora profesionales activos de la Red LDR y filtra por área, ubicación, idioma y modalidad.",search:"Buscar por nombre, área o especialidad",area:"Área profesional",country:"País",language:"Idioma",all:"Todos",online:"Online",present:"Presencial",profile:"VER PERFIL",empty:"No hay profesionales con estos filtros.",back:"Para profesionales",eyebrow:"Red de Profesionales LDR",ctaTitle:"¿Eres profesional?",ctaText:"Presenta tus servicios, organiza tu presencia profesional y forma parte de un ecosistema con tecnología, comunidad y desarrollo.",cta:"CONOCER LA RED LDR",results:"profesionales encontrados",oneResult:"profesional encontrado",clear:"Limpiar filtros",active:"Perfil activo",premium:"Una red creada para conectar personas y profesionales",premiumText:"Perfiles organizados, búsqueda inteligente y una experiencia simple para encontrar el servicio adecuado."}
} as const;

function Directory(){
 const {locale}=useI18n(); const c=COPY[locale]; const data=Route.useLoaderData() as any; const [q,setQ]=useState(""); const [cat,setCat]=useState(""); const [country,setCountry]=useState(""); const [lang,setLang]=useState(""); const [mode,setMode]=useState("");
 const categories=(data?.categories??[]) as AnyRow[]; const profiles=(data?.profiles??[]) as AnyRow[];
 const catMap=useMemo(()=>new Map(categories.map(x=>[x.id,x])),[categories]);
 const countries=[...new Set(profiles.map(p=>p.country_code).filter(Boolean))].sort(); const languages=[...new Set(profiles.flatMap(p=>p.languages??[]))].sort();
 const filtered=profiles.filter(p=>{const hay=`${p.display_name} ${p.professional_title} ${(p.specialties??[]).join(" ")} ${p.city??""}`.toLowerCase(); return (!q||hay.includes(q.toLowerCase()))&&(!cat||p.category_id===cat)&&(!country||p.country_code===country)&&(!lang||(p.languages??[]).includes(lang))&&(!mode||(mode==="online"?p.online_enabled:p.in_person_enabled));});
 const hasFilters=Boolean(q||cat||country||lang||mode); const clear=()=>{setQ("");setCat("");setCountry("");setLang("");setMode("")};
 return <div className="min-h-screen bg-background text-foreground">
  <header className="sticky top-0 z-40 border-b bg-background/90 backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-4 sm:px-6"><Link to="/" className="font-serif text-xl font-bold tracking-tight">Grupo LDR Essence</Link><div className="flex items-center gap-2"><Link to="/para-profissionais" className="hidden rounded-xl border border-primary/20 bg-primary/5 px-4 py-2 text-sm font-black text-primary transition hover:bg-primary hover:text-primary-foreground sm:inline-flex">{c.back}</Link><LanguageSelect/></div></div></header>
  <main>
   <section className="relative overflow-hidden border-b"><div className="absolute inset-0 bg-gradient-to-br from-primary/[.10] via-background to-secondary/[.16]"/><div className="absolute -right-28 -top-28 h-80 w-80 rounded-full bg-primary/10 blur-3xl"/><div className="relative mx-auto grid max-w-7xl gap-10 px-4 py-14 sm:px-6 lg:grid-cols-[1.15fr_.85fr] lg:items-end lg:py-20"><div className="max-w-4xl"><div className="inline-flex items-center gap-2 rounded-full border bg-background/75 px-4 py-2 text-xs font-black uppercase tracking-[.16em] text-primary shadow-sm backdrop-blur"><Sparkles className="h-4 w-4"/>{c.eyebrow}</div><h1 className="mt-5 max-w-4xl font-serif text-4xl leading-[1.05] sm:text-5xl lg:text-6xl">{c.title}</h1><p className="mt-5 max-w-3xl text-base leading-7 text-muted-foreground sm:text-lg sm:leading-8">{c.sub}</p></div><div className="rounded-[2rem] border bg-card/90 p-6 shadow-xl shadow-primary/5 backdrop-blur sm:p-7"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-primary text-primary-foreground"><UsersRound className="h-5 w-5"/></div><p className="font-serif text-xl">{c.premium}</p></div><p className="mt-4 text-sm leading-6 text-muted-foreground">{c.premiumText}</p></div></div></section>

   <section className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="rounded-[2rem] border bg-card p-4 shadow-xl shadow-primary/5 sm:p-6"><div className="grid gap-3 lg:grid-cols-5"><label className="relative lg:col-span-2"><Search className="absolute left-4 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder={c.search} aria-label={c.search} className="w-full rounded-2xl border bg-background py-3.5 pl-11 pr-4 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/10"/></label><select aria-label={c.area} value={cat} onChange={e=>setCat(e.target.value)} className="rounded-2xl border bg-background px-4 py-3.5 text-sm outline-none transition focus:border-primary"><option value="">{c.area}: {c.all}</option>{categories.map(x=><option key={x.id} value={x.id}>{x[`name_${locale}`]||x.name_pt}</option>)}</select><select aria-label={c.country} value={country} onChange={e=>setCountry(e.target.value)} className="rounded-2xl border bg-background px-4 py-3.5 text-sm outline-none transition focus:border-primary"><option value="">{c.country}: {c.all}</option>{countries.map(x=><option key={x} value={x}>{x}</option>)}</select><select aria-label={c.language} value={lang} onChange={e=>setLang(e.target.value)} className="rounded-2xl border bg-background px-4 py-3.5 text-sm outline-none transition focus:border-primary"><option value="">{c.language}: {c.all}</option>{languages.map(x=><option key={x} value={x}>{x.toUpperCase()}</option>)}</select></div><div className="mt-4 flex flex-col gap-3 border-t pt-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex flex-wrap gap-2"><button onClick={()=>setMode("")} className={`rounded-full border px-4 py-2 text-sm font-bold transition ${!mode?"border-primary bg-primary text-primary-foreground shadow-sm":"bg-background hover:border-primary/40"}`}>{c.all}</button><button onClick={()=>setMode("online")} className={`rounded-full border px-4 py-2 text-sm font-bold transition ${mode==="online"?"border-primary bg-primary text-primary-foreground shadow-sm":"bg-background hover:border-primary/40"}`}>{c.online}</button><button onClick={()=>setMode("present")} className={`rounded-full border px-4 py-2 text-sm font-bold transition ${mode==="present"?"border-primary bg-primary text-primary-foreground shadow-sm":"bg-background hover:border-primary/40"}`}>{c.present}</button></div>{hasFilters?<button onClick={clear} className="inline-flex items-center gap-2 self-start text-sm font-bold text-muted-foreground transition hover:text-primary"><X className="h-4 w-4"/>{c.clear}</button>:null}</div></div>

   <div className="mt-8 flex items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.15em] text-primary">{c.eyebrow}</p><p className="mt-1 text-sm text-muted-foreground"><strong className="text-foreground">{filtered.length}</strong> {filtered.length===1?c.oneResult:c.results}</p></div></div>
   <section className="mt-5 grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map(p=>{const category=catMap.get(p.category_id);return <article key={p.id} className="group relative overflow-hidden rounded-[2rem] border bg-card p-6 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-primary/25 hover:shadow-2xl hover:shadow-primary/10"><div className="absolute inset-x-0 top-0 h-1 bg-gradient-to-r from-primary via-secondary to-primary opacity-70"/><div className="flex items-start gap-4"><div className="relative grid h-20 w-20 shrink-0 place-items-center overflow-hidden rounded-3xl bg-primary/10 ring-1 ring-primary/10">{p.photo_url?<img src={p.photo_url} alt={p.display_name||"Profissional"} className="h-full w-full object-cover"/>:<UserRound className="h-9 w-9 text-primary"/>}<span className="absolute bottom-1 right-1 h-3 w-3 rounded-full border-2 border-card bg-emerald-500"/></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><h2 className="break-words font-serif text-2xl leading-tight">{p.display_name}</h2><p className="mt-1 text-sm font-black text-primary">{p.professional_title}</p></div><BadgeCheck className="mt-1 h-5 w-5 shrink-0 text-primary"/></div><p className="mt-2 text-xs font-bold uppercase tracking-wide text-muted-foreground">{c.active}</p></div></div><div className="mt-5 rounded-2xl bg-muted/40 p-4"><p className="text-sm font-semibold">{category?.[`name_${locale}`]||category?.name_pt||p.professional_title}</p><div className="mt-3 grid gap-2 text-sm text-muted-foreground"><p className="flex items-center gap-2"><MapPin className="h-4 w-4 shrink-0 text-primary"/>{p.city?`${p.city} · `:""}{p.country_code}</p>{(p.languages??[]).length?<p className="flex items-center gap-2"><Languages className="h-4 w-4 shrink-0 text-primary"/>{(p.languages??[]).map((x:string)=>x.toUpperCase()).join(" · ")}</p>:null}</div></div><div className="mt-4 flex flex-wrap gap-2">{p.online_enabled?<span className="inline-flex items-center rounded-full border border-primary/10 bg-primary/10 px-3 py-1.5 text-xs font-black text-primary"><Monitor className="mr-1.5 h-3.5 w-3.5"/>{c.online.toUpperCase()}</span>:null}{p.in_person_enabled?<span className="inline-flex items-center rounded-full border bg-secondary/15 px-3 py-1.5 text-xs font-black"><Globe2 className="mr-1.5 h-3.5 w-3.5"/>{c.present.toUpperCase()}</span>:null}</div>{p.about?<p className="mt-4 line-clamp-3 text-sm leading-6 text-muted-foreground">{p.about}</p>:null}<Link to="/profissional/$slug" params={{slug:p.slug}} className="mt-6 flex items-center justify-between rounded-2xl bg-primary px-5 py-3.5 text-sm font-black text-primary-foreground transition group-hover:shadow-lg"><span>{c.profile}</span><ArrowUpRight className="h-4 w-4"/></Link></article>})}</section>
   {filtered.length===0?<div className="mt-8 rounded-[2rem] border border-dashed bg-muted/20 p-10 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-primary/10"><Search className="h-5 w-5 text-primary"/></div><p className="mt-4 text-sm text-muted-foreground">{c.empty}</p>{hasFilters?<button onClick={clear} className="mt-4 rounded-xl border px-4 py-2 text-sm font-black text-primary">{c.clear}</button>:null}</div>:null}

   <section className="relative mt-12 overflow-hidden rounded-[2.25rem] bg-primary p-7 text-primary-foreground shadow-2xl shadow-primary/15 sm:p-10 lg:p-12"><div className="absolute -right-16 -top-20 h-72 w-72 rounded-full bg-secondary/20 blur-3xl"/><div className="relative grid gap-7 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-black uppercase tracking-[.18em] text-secondary">{c.eyebrow}</p><h2 className="mt-3 font-serif text-3xl sm:text-4xl">{c.ctaTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-7 opacity-85 sm:text-base">{c.ctaText}</p></div><Link to="/para-profissionais" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-secondary px-6 py-4 text-sm font-black text-secondary-foreground shadow-lg transition hover:-translate-y-0.5"><span>{c.cta}</span><ArrowUpRight className="h-4 w-4"/></Link></div></section>
  </section>
  </main>
 </div>
}
