import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { professionalDashboard, professionalSaveOnboarding } from "@/lib/professional-network.functions";

export const Route=createFileRoute("/profissional-onboarding")({head:()=>({meta:[{title:"Cadastro Profissional — Rede LDR"},{name:"robots",content:"noindex,nofollow"}]}),component:Onboarding});
type AnyRow=Record<string,any>;
function Onboarding(){const load=useServerFn(professionalDashboard);const save=useServerFn(professionalSaveOnboarding);const [data,setData]=useState<any>(null);const [step,setStep]=useState(1);const [busy,setBusy]=useState(false);const [f,setF]=useState<any>({countryCode:"BE",currency:"EUR",displayName:"",professionalTitle:"",categoryId:"",city:"",languages:"pt",onlineEnabled:true,inPersonEnabled:false,about:"",experienceSummary:"",educationSummary:"",specialties:""});useEffect(()=>{void supabase.auth.getSession().then(async({data:s})=>{if(!s.session){window.location.replace("/profissional/login");return}const r=await load();const activeApproved=r.profile?.profile_status==="active"&&r.profile?.compliance_status==="approved";if(activeApproved){window.location.replace("/profissional-painel");return}setData(r);setStep(Math.min(Number(r.account?.onboarding_step||1),6));if(r.profile)setF((x:any)=>({...x,countryCode:r.profile.country_code||r.account.country_code||"BE",currency:r.account.preferred_currency||"EUR",displayName:r.profile.display_name||"",professionalTitle:r.profile.professional_title||"",categoryId:r.profile.category_id||"",city:r.profile.city||"",languages:(r.profile.languages||[]).join(", "),onlineEnabled:r.profile.online_enabled,inPersonEnabled:r.profile.in_person_enabled,about:r.profile.about||"",experienceSummary:r.profile.experience_summary||"",educationSummary:r.profile.education_summary||"",specialties:(r.profile.specialties||[]).join(", ")}))})},[]);async function persist(next:number){setBusy(true);try{await save({data:{step:next,countryCode:f.countryCode,currency:f.currency,displayName:f.displayName||undefined,professionalTitle:f.professionalTitle||undefined,categoryId:f.categoryId||undefined,city:f.city||undefined,languages:f.languages.split(",").map((x:string)=>x.trim().toLowerCase()).filter(Boolean),onlineEnabled:f.onlineEnabled,inPersonEnabled:f.inPersonEnabled,about:f.about||undefined,experienceSummary:f.experienceSummary||undefined,educationSummary:f.educationSummary||undefined,specialties:f.specialties.split(",").map((x:string)=>x.trim()).filter(Boolean)}});setStep(Math.min(next,6));toast.success("Progresso salvo.")}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível salvar.")}finally{setBusy(false)}}
async function submitForReview(){setBusy(true);try{await save({data:{step:7,countryCode:f.countryCode,currency:f.currency,displayName:f.displayName,professionalTitle:f.professionalTitle,categoryId:f.categoryId,city:f.city,languages:f.languages.split(",").map((x:string)=>x.trim()).filter(Boolean),onlineEnabled:f.onlineEnabled,inPersonEnabled:f.inPersonEnabled,about:f.about,experienceSummary:f.experienceSummary,educationSummary:f.educationSummary,specialties:f.specialties.split(",").map((x:string)=>x.trim()).filter(Boolean)}});toast.success("Perfil enviado para análise da LDR.");window.location.replace("/profissional-painel")}catch(e){toast.error(e instanceof Error?e.message:"Não foi possível enviar o perfil.");setBusy(false)}}
if(!data)return <div className="min-h-screen grid place-items-center text-sm text-muted-foreground">Preparando seu cadastro…</div>;return <div className="min-h-screen bg-background"><header className="border-b bg-primary text-primary-foreground"><div className="mx-auto max-w-4xl px-4 py-5 sm:px-6"><p className="font-serif text-2xl">Rede de Profissionais LDR</p><p className="mt-1 text-xs opacity-80">Cadastro profissional · salvar e continuar depois</p></div></header><main className="mx-auto max-w-4xl px-4 py-8 sm:px-6"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.18em] text-primary">Etapa {step} de 6</p><h1 className="mt-1 font-serif text-3xl">Crie seu perfil profissional</h1></div><div className="hidden gap-1 sm:flex">{Array.from({length:6},(_,i)=><span key={i} className={`h-2 w-8 rounded-full ${i<step?"bg-primary":"bg-muted"}`}/>)}</div></div><section className="mt-7 rounded-3xl border bg-card p-6 sm:p-8">{step===1?<><Title t="1. País e mercado" d="Os preços, moedas e requisitos profissionais dependem do mercado apropriado; não fazemos conversão cambial automática."/><div className="mt-5 grid gap-3 sm:grid-cols-2"><Field l="País"><select value={f.countryCode} onChange={e=>setF({...f,countryCode:e.target.value,currency:e.target.value==="BR"?"BRL":"EUR"})}><option value="BE">Bélgica</option><option value="PT">Portugal</option><option value="BR">Brasil</option><option value="DE">Alemanha</option></select></Field><Field l="Moeda"><input value={f.currency} readOnly/></Field></div><Next busy={busy} onClick={()=>persist(2)}/></>:null}
{step===2?<><Title t="2. Categoria e identificação profissional" d="Títulos regulamentados ficam sujeitos à validação específica do país e da profissão."/><div className="mt-5 grid gap-3 sm:grid-cols-2"><Field l="Nome público"><input value={f.displayName} onChange={e=>setF({...f,displayName:e.target.value})}/></Field><Field l="Título profissional"><input value={f.professionalTitle} onChange={e=>setF({...f,professionalTitle:e.target.value})}/></Field><Field l="Categoria"><select value={f.categoryId} onChange={e=>setF({...f,categoryId:e.target.value})}><option value="">Selecione</option>{(data.categories??[]).map((c:AnyRow)=><option key={c.id} value={c.id}>{c.name_pt}</option>)}</select></Field></div><Nav busy={busy} prev={()=>setStep(1)} next={()=>{if(!f.displayName||!f.professionalTitle||!f.categoryId){toast.error("Preencha nome, título e categoria.");return}void persist(3)}}/></>:null}
{step===3?<><Title t="3. Atuação e modalidades" d="Informe apenas localização pública. Endereço residencial não precisa ser publicado."/><div className="mt-5 grid gap-3 sm:grid-cols-2"><Field l="Cidade"><input value={f.city} onChange={e=>setF({...f,city:e.target.value})}/></Field><Field l="Idiomas"><input value={f.languages} onChange={e=>setF({...f,languages:e.target.value})} placeholder="pt, fr, en, es"/></Field></div><div className="mt-5 flex flex-wrap gap-5 text-sm"><label><input type="checkbox" checked={f.onlineEnabled} onChange={e=>setF({...f,onlineEnabled:e.target.checked})}/> Atendimento online</label><label><input type="checkbox" checked={f.inPersonEnabled} onChange={e=>setF({...f,inPersonEnabled:e.target.checked})}/> Atendimento presencial</label></div><Nav busy={busy} prev={()=>setStep(2)} next={()=>persist(4)}/></>:null}
{step===4?<><Title t="4. Apresentação" d="Descreva sua atuação de forma clara, sem promessas de cura, resultado garantido ou qualificações que não possam ser comprovadas."/><Field l="Sobre"><textarea rows={6} value={f.about} onChange={e=>setF({...f,about:e.target.value})}/></Field><Nav busy={busy} prev={()=>setStep(3)} next={()=>persist(5)}/></>:null}
{step===5?<><Title t="5. Formação, experiência e áreas" d="Não invente registros, anos, certificações ou resultados. Documentos exigidos serão tratados em ambiente privado."/><div className="grid gap-4"><Field l="Experiência"><textarea rows={4} value={f.experienceSummary} onChange={e=>setF({...f,experienceSummary:e.target.value})}/></Field><Field l="Formação"><textarea rows={4} value={f.educationSummary} onChange={e=>setF({...f,educationSummary:e.target.value})}/></Field><Field l="Áreas / especialidades"><input value={f.specialties} onChange={e=>setF({...f,specialties:e.target.value})} placeholder="separadas por vírgula"/></Field></div><Nav busy={busy} prev={()=>setStep(4)} next={()=>persist(6)}/></>:null}
{step===6?<><Title t="6. Revisão e envio" d="Revise seus dados. O cadastro profissional é gratuito e não possui mensalidade. Seu perfil só ficará público depois da análise e liberação pelo administrador LDR."/><div className="mt-5 rounded-xl bg-muted/50 p-4 text-sm leading-6"><strong>Antes de enviar:</strong> confirme sua formação, experiência, especialidades e modalidades de atendimento. Após o envio, o perfil ficará em análise e não aparecerá no diretório público até ser aprovado.</div><div className="mt-6 flex flex-wrap justify-between gap-3"><button onClick={()=>setStep(5)} className="rounded-xl border px-4 py-3 text-sm font-bold">VOLTAR</button><button disabled={busy} onClick={()=>void submitForReview()} className="rounded-xl bg-primary px-5 py-3 text-sm font-black text-primary-foreground disabled:opacity-50">{busy?"ENVIANDO…":"ENVIAR PERFIL PARA APROVAÇÃO"}</button></div></>:null}</section><p className="mt-5 text-center text-xs text-muted-foreground">Você pode sair e continuar depois com a mesma conta Google.</p></main></div>}
function Title({t,d}:{t:string;d:string}){return <div><h2 className="font-serif text-2xl">{t}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{d}</p></div>}
function Field({l,children}:{l:string;children:any}){return <label className="mt-4 grid gap-1 text-sm font-bold"><span>{l}</span><div className="[&>input]:w-full [&>input]:rounded-xl [&>input]:border [&>input]:bg-background [&>input]:px-3 [&>input]:py-3 [&>select]:w-full [&>select]:rounded-xl [&>select]:border [&>select]:bg-background [&>select]:px-3 [&>select]:py-3 [&>textarea]:w-full [&>textarea]:rounded-xl [&>textarea]:border [&>textarea]:bg-background [&>textarea]:px-3 [&>textarea]:py-3">{children}</div></label>}
function Next({busy,onClick}:{busy:boolean;onClick:()=>void}){return <button disabled={busy} onClick={onClick} className="mt-6 rounded-xl bg-primary px-5 py-3 font-black text-primary-foreground disabled:opacity-50">SALVAR E CONTINUAR</button>}
function Nav({busy,prev,next}:{busy:boolean;prev:()=>void;next:()=>void}){return <div className="mt-6 flex flex-wrap justify-between gap-3"><button onClick={prev} className="rounded-xl border px-4 py-3 text-sm font-bold">VOLTAR</button><button disabled={busy} onClick={next} className="rounded-xl bg-primary px-5 py-3 text-sm font-black text-primary-foreground disabled:opacity-50">SALVAR E CONTINUAR</button></div>}
