import { Link, createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useEffect, useState } from "react";
import { Languages, MapPin, Monitor, UserRound } from "lucide-react";
import { LanguageSelect, useI18n } from "@/lib/i18n";
import { networkLanding } from "@/lib/professional-network.functions";

export const Route=createFileRoute("/profissionais/$category")({component:CategoryDirectory});
type AnyRow=Record<string,any>;
const ALIAS:Record<string,string>={rh:"recursos-humanos",psicanalise:"psicanalise",massagem:"massagistas",terapeutas:"terapeutas",mentoria:"mentoria",consultores:"consultores",carreira:"consultoria-carreira","bem-estar":"bem-estar"};
function CategoryDirectory(){const {category}=Route.useParams();const {locale}=useI18n();const load=useServerFn(networkLanding);const [data,setData]=useState<any>(null);useEffect(()=>{void load().then(setData)},[load]);if(!data)return <div className="min-h-screen grid place-items-center text-sm text-muted-foreground">Carregando…</div>;const slug=ALIAS[category]||category;const cat=(data.categories??[]).find((x:AnyRow)=>x.slug===slug);const profiles=(data.profiles??[]).filter((p:AnyRow)=>p.category_id===cat?.id);const name=cat?.[`name_${locale}`]||cat?.name_pt||category;return <div className="min-h-screen bg-background"><header className="border-b"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 sm:px-6"><Link to="/profissionais" className="font-bold">← Diretório</Link><LanguageSelect/></div></header><main className="mx-auto max-w-7xl px-4 py-10 sm:px-6"><p className="text-xs font-black uppercase tracking-[.18em] text-primary">Rede de Profissionais LDR</p><h1 className="mt-2 font-serif text-4xl">Profissionais de {name}</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">Perfis públicos ativos e aprovados. A publicação de títulos regulamentados depende das regras e validações aplicáveis ao país e à profissão.</p><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{profiles.map((p:AnyRow)=><article key={p.id} className="rounded-3xl border bg-card p-6"><div className="flex gap-4"><div className="grid h-14 w-14 place-items-center rounded-2xl bg-primary/10">{p.photo_url?<img src={p.photo_url} alt="" className="h-full w-full rounded-2xl object-cover"/>:<UserRound className="h-7 w-7 text-primary"/>}</div><div><h2 className="font-serif text-2xl">{p.display_name}</h2><p className="text-sm font-bold text-primary">{p.professional_title}</p></div></div><p className="mt-4 text-sm"><MapPin className="mr-1 inline h-4 w-4 text-primary"/>{p.city?`${p.city} · `:""}{p.country_code}</p><p className="mt-2 text-sm"><Languages className="mr-1 inline h-4 w-4 text-primary"/>{(p.languages??[]).map((x:string)=>x.toUpperCase()).join(" · ")}</p>{p.online_enabled?<p className="mt-2 text-sm"><Monitor className="mr-1 inline h-4 w-4 text-primary"/>Online</p>:null}<p className="mt-4 line-clamp-3 text-sm leading-6 text-muted-foreground">{p.about}</p><Link to="/profissional/$slug" params={{slug:p.slug}} className="mt-5 block rounded-xl bg-primary px-4 py-3 text-center text-sm font-black text-primary-foreground">VER PERFIL</Link></article>)}</div>{profiles.length===0?<div className="mt-8 rounded-2xl border border-dashed p-8 text-center text-sm text-muted-foreground">Ainda não há perfis públicos ativos nesta categoria.</div>:null}</main></div>}
