import { Link, createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { LanguageSelect, useI18n } from "@/lib/i18n";

export const Route=createFileRoute("/profissional/login")({head:()=>({meta:[{title:"Área do Profissional — Rede LDR"},{name:"robots",content:"noindex"}]}),component:ProfessionalLogin});
const COPY={pt:{title:"Área do Profissional",sub:"Crie seu perfil, escolha o plano e gerencie sua atuação na Rede LDR.",google:"Entrar com Google",opening:"Abrindo…",back:"Conhecer a Rede LDR",error:"Não foi possível entrar."},en:{title:"Professional Area",sub:"Create your profile, choose a plan and manage your work in the LDR Network.",google:"Continue with Google",opening:"Opening…",back:"Explore the LDR Network",error:"Could not sign in."},fr:{title:"Espace Professionnel",sub:"Créez votre profil, choisissez votre plan et gérez votre activité dans le Réseau LDR.",google:"Continuer avec Google",opening:"Ouverture…",back:"Découvrir le Réseau LDR",error:"Connexion impossible."},es:{title:"Área Profesional",sub:"Crea tu perfil, elige tu plan y gestiona tu actividad en la Red LDR.",google:"Continuar con Google",opening:"Abriendo…",back:"Conocer la Red LDR",error:"No fue posible entrar."}} as const;
function ProfessionalLogin(){const {locale}=useI18n();const c=COPY[locale];const [busy,setBusy]=useState(false);useEffect(()=>{let active=true;void supabase.auth.getSession().then(({data})=>{if(active&&data.session)window.location.replace("/profissional-painel")});const {data}=supabase.auth.onAuthStateChange((_e,s)=>{if(active&&s)window.location.replace("/profissional-painel")});return()=>{active=false;data.subscription.unsubscribe()}},[]);async function signIn(){setBusy(true);const {data,error}=await supabase.auth.signInWithOAuth({provider:"google",options:{redirectTo:`${window.location.origin}/profissional/login`,skipBrowserRedirect:true}});if(error||!data.url){setBusy(false);toast.error(c.error);return}window.location.assign(data.url)}return <div className="min-h-screen bg-background"><header className="bg-primary text-primary-foreground"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-5 sm:px-6"><div><p className="font-serif text-2xl">Grupo LDR Essence</p><p className="text-xs opacity-80">Rede de Profissionais LDR</p></div><LanguageSelect/></div></header><main className="mx-auto max-w-md px-4 py-12 sm:px-6"><section className="rounded-3xl border bg-card p-7 shadow-sm"><h1 className="font-serif text-3xl">{c.title}</h1><p className="mt-3 text-sm leading-6 text-muted-foreground">{c.sub}</p><button onClick={signIn} disabled={busy} className="mt-6 w-full rounded-xl border bg-background px-4 py-3 font-black text-primary">{busy?c.opening:c.google}</button><Link to="/para-profissionais" className="mt-4 block text-center text-sm font-bold underline">{c.back}</Link></section></main></div>}
