import { useEffect, useState } from "react";
import { LanguageSelect, useI18n } from "@/lib/i18n";
import { supabase } from "@/integrations/supabase/client";
import { createFileRoute, Link } from "@tanstack/react-router";
import { BookHeart, HeartHandshake, MessageCircle, Network, ShieldCheck, Users } from "lucide-react";

export const Route=createFileRoute("/rede-academica")({component:AcademicNetworkLanding,head:()=>({meta:[{title:"Rede Acadêmica LDR | LDR Essence Academy"},{name:"description",content:"Rede social acadêmica gratuita com diário privado, comunidades, debates e networking."}]})});

const CONTENT={
 pt:{title:"REDE ACADÊMICA GRATUITA",desc:"Crie sua conta gratuitamente e participe.",create:"CRIAR CONTA GRÁTIS",enter:"ENTRAR NA REDE",free:"CONTA GRÁTIS",noCard:"SEM CARTÃO",join:"PARTICIPE GRATUITAMENTE",joinTitle:"A Rede Acadêmica é gratuita.",joinText:"Crie sua conta gratuitamente e participe. Publique, compartilhe conhecimento, participe de discussões e conecte-se com a comunidade acadêmica.",features:[["Meu Diário","Um espaço privado e gratuito para registrar pensamentos, aprendizados e reflexões."],["Feed Acadêmico","Compartilhe reflexões, perguntas, debates, estudos e indicações."],["Comunidades","Participe de grupos por área: Psicanálise, RH, IA, Carreira, Educação e muito mais."],["Networking acadêmico","Conecte-se com pessoas que compartilham interesses de estudo e atuação."],["Acolher","Uma reação simples para valorizar a troca sem transformar a rede em competição."],["Privacidade e anonimato","Publique com seu nome ou anonimamente. Seu Diário continua privado."]]},
 en:{title:"FREE ACADEMIC NETWORK",desc:"Create your free account and join the community.",create:"CREATE FREE ACCOUNT",enter:"ENTER THE NETWORK",free:"FREE ACCOUNT",noCard:"NO CARD",join:"JOIN FOR FREE",joinTitle:"The Academic Network is free.",joinText:"Create your free account and take part. Publish, share knowledge, join discussions and connect with the academic community.",features:[["My Journal","A private, free space to record thoughts, learning and reflections."],["Academic Feed","Share reflections, questions, debates, studies and recommendations."],["Communities","Join groups in Psychoanalysis, HR, AI, Careers, Education and more."],["Academic networking","Connect with people who share your study and professional interests."],["Support","A simple reaction to value exchange without turning the network into a competition."],["Privacy and anonymity","Publish with your name or anonymously. Your Journal remains private."]]},
 fr:{title:"RÉSEAU ACADÉMIQUE GRATUIT",desc:"Créez votre compte gratuitement et rejoignez la communauté.",create:"CRÉER UN COMPTE GRATUIT",enter:"ENTRER DANS LE RÉSEAU",free:"COMPTE GRATUIT",noCard:"SANS CARTE",join:"PARTICIPEZ GRATUITEMENT",joinTitle:"Le Réseau Académique est gratuit.",joinText:"Créez votre compte gratuitement. Publiez, partagez des connaissances, participez aux discussions et échangez avec la communauté académique.",features:[["Mon journal","Un espace privé et gratuit pour noter pensées, apprentissages et réflexions."],["Fil académique","Partagez réflexions, questions, débats, études et recommandations."],["Communautés","Rejoignez des groupes en psychanalyse, RH, IA, carrière, éducation et plus encore."],["Réseautage académique","Échangez avec des personnes qui partagent vos intérêts d'étude et professionnels."],["Soutenir","Une réaction simple pour valoriser les échanges sans transformer le réseau en compétition."],["Confidentialité et anonymat","Publiez sous votre nom ou anonymement. Votre journal reste privé."]]},
 es:{title:"RED ACADÉMICA GRATUITA",desc:"Crea tu cuenta gratis y participa en la comunidad.",create:"CREAR CUENTA GRATIS",enter:"ENTRAR EN LA RED",free:"CUENTA GRATIS",noCard:"SIN TARJETA",join:"PARTICIPA GRATIS",joinTitle:"La Red Académica es gratuita.",joinText:"Crea tu cuenta gratis y participa. Publica, comparte conocimiento, participa en debates y conecta con la comunidad académica.",features:[["Mi Diario","Un espacio privado y gratuito para registrar pensamientos, aprendizajes y reflexiones."],["Feed Académico","Comparte reflexiones, preguntas, debates, estudios y recomendaciones."],["Comunidades","Participa en grupos de Psicoanálisis, RR. HH., IA, Carrera, Educación y mucho más."],["Networking académico","Conecta con personas que comparten tus intereses de estudio y profesionales."],["Acoger","Una reacción sencilla para valorar el intercambio sin convertir la red en una competición."],["Privacidad y anonimato","Publica con tu nombre o de forma anónima. Tu Diario sigue siendo privado."]]}
} as const;
const ICONS=[BookHeart,MessageCircle,Users,Network,HeartHandshake,ShieldCheck] as const;
function AcademicNetworkLanding(){const {locale}=useI18n();const copy=CONTENT[locale]??CONTENT.pt;const [authenticated,setAuthenticated]=useState(false);useEffect(()=>{const {data}=supabase.auth.onAuthStateChange((_event,session)=>setAuthenticated(Boolean(session)));return()=>data.subscription.unsubscribe()},[]);return <main className="min-h-screen bg-[#f7f4ed] text-[#071426] dark:bg-background dark:text-foreground">
  <div className="mx-auto flex max-w-7xl justify-end px-4 pt-4 sm:px-6"><div className="w-36"><LanguageSelect /></div></div>\n  <section className="border-b border-[#d8cba9] bg-gradient-to-br from-[#071426] via-[#102a4a] to-[#193b62] text-white"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 sm:py-24"><p className="text-xs font-black tracking-[.25em] text-[#e7c979]">LDR ESSENCE ACADEMY</p><h1 className="mt-4 max-w-4xl font-serif text-4xl leading-tight sm:text-6xl">{copy.title}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-200">{copy.desc}</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/cliente/rede-academica" className="rounded-xl bg-[#e6c873] px-5 py-3 text-sm font-black text-[#071426]">{authenticated?copy.enter:copy.create}</Link></div><div className="mt-5 flex flex-wrap gap-2 text-[10px] font-black tracking-[.08em]"><span className="rounded-full bg-white/10 px-3 py-1.5">{copy.title}</span><span className="rounded-full bg-white/10 px-3 py-1.5">{copy.free}</span><span className="rounded-full bg-white/10 px-3 py-1.5">{copy.noCard}</span></div></div></section>
  <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{copy.features.map(([title,desc],i)=>{const Icon=ICONS[i];return <article key={title} className="rounded-[24px] border border-[#d8cba9] bg-white p-6 shadow-sm dark:bg-card"><Icon className="h-7 w-7"/><h2 className="mt-4 font-serif text-2xl">{title}</h2><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-muted-foreground">{desc}</p></article>})}</div></section>
  <section className="mx-auto max-w-5xl px-4 pb-16 sm:px-6"><div className="rounded-[30px] border border-[#d8cba9] bg-white p-7 text-center shadow-sm dark:bg-card sm:p-10"><p className="text-xs font-black tracking-[.18em] text-[#9a772c]">{copy.join}</p><h2 className="mt-3 font-serif text-3xl">{copy.joinTitle}</h2><p className="mx-auto mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">{copy.joinText}</p><Link to="/cliente/rede-academica" className="mt-6 inline-flex rounded-xl bg-[#071426] px-5 py-3 text-sm font-black text-white">{authenticated?copy.enter:copy.create}</Link></div></section>
</main>}
