from pathlib import Path
p=Path('apps/painel-ldr/src/components/psychoanalysis-training-page.tsx')
s=p.read_text(encoding='utf-8')
anchor='''   <section className="rounded-[2rem] border border-[#caa85d] bg-[#f5edfb] p-6 sm:p-8"><h2 className="font-serif text-3xl font-bold">Acesso vitalício aos conteúdos digitais</h2>'''
insert='''   <section className="rounded-[2rem] border border-[#ded0eb] bg-white p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-[#7b4aa3]">O que você recebe</p><h2 className="mt-2 font-serif text-3xl font-bold">Uma formação completa, não apenas videoaulas</h2><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["90 aulas organizadas em 10 módulos","6 encontros ao vivo durante o percurso","Atividade ao final de cada módulo","Leituras ‘Para ir mais fundo’","Professores convidados ao longo da formação","Possibilidade futura de candidatura à prática supervisionada","Acesso vitalício às aulas, textos e gravações disponibilizadas","Percurso recomendado de 6 a 12 meses","Ambiente exclusivo dentro da Biblioteca LDR"].map(item=><div key={item} className="flex gap-3 rounded-2xl bg-[#f8f3fb] p-4"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-[#5b2b86]"/><p className="text-sm font-semibold leading-6 text-[#51445a]">{item}</p></div>)}</div></section>
   <section className="rounded-[2rem] border border-[#ded0eb] bg-white p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-[#7b4aa3]">Encontros ao vivo</p><h2 className="mt-2 font-serif text-3xl font-bold">6 momentos de aprofundamento</h2><div className="mt-5 grid gap-3 sm:grid-cols-2">{["1. Fundamentos e método psicanalítico","2. Inconsciente e estrutura psíquica","3. Sexualidade, pulsões e mecanismos de defesa","4. Técnica, resistência e transferência","5. Psicanálise e clínica contemporânea","6. Supervisão, percurso e fechamento"].map(item=><div key={item} className="rounded-2xl border border-[#e5d9ed] p-4 text-sm font-bold text-[#3d2851]">{item}</div>)}</div><p className="mt-4 text-xs leading-5 text-[#74657d]">Datas, professores, links e gravações serão disponibilizados na área do aluno conforme o calendário da turma.</p></section>
   <section className="rounded-[2rem] border border-[#ded0eb] bg-white p-6 sm:p-8"><p className="text-xs font-black uppercase tracking-[.18em] text-[#7b4aa3]">Perguntas frequentes</p><h2 className="mt-2 font-serif text-3xl font-bold">Antes de começar</h2><div className="mt-5 grid gap-3">{[["O acesso é vitalício?","Sim. O acesso vitalício refere-se às aulas gravadas, textos, materiais e gravações disponibilizadas. Encontros ao vivo, acompanhamento e supervisões seguem o calendário da turma."],["Em quanto tempo posso concluir?","O percurso é planejado para no mínimo 6 meses e pode ser realizado em até 12 meses dentro do ciclo formativo."],["A análise pessoal está incluída?","Não automaticamente. A formação explica a importância da análise pessoal como parte do tripé psicanalítico, mas ela deve ser contratada ou realizada separadamente."],["Existe estágio garantido?","Não. Alunos que cumprirem critérios poderão se candidatar a futuras oportunidades de prática supervisionada na Rede LDR, conforme disponibilidade, avaliação e requisitos aplicáveis."],["Recebo certificado?","A plataforma está preparada para certificação, mas os critérios e a comunicação final de certificado serão definidos antes da emissão. Não há promessa de diploma ou habilitação profissional automática."],["Onde encontro as leituras indicadas?","As referências orientam o aluno a buscar editoras, bibliotecas, Google Books e acervos legais disponíveis em sua região. A formação não distribui cópias não autorizadas."]].map(([q,a])=><details key={q} className="rounded-2xl border border-[#e5d9ed] p-4"><summary className="cursor-pointer font-bold text-[#3d2851]">{q}</summary><p className="mt-3 text-sm leading-6 text-[#66576f]">{a}</p></details>)}</div></section>
'''
if anchor not in s: raise SystemExit('anchor not found')
s=s.replace(anchor,insert+anchor,1)
p.write_text(s,encoding='utf-8')
