from pathlib import Path
import json,re

ROOT=Path('apps/painel-ldr/src')
cat=ROOT/'lib/professional-formations.catalog.ts'
s=cat.read_text()

new_slugs=[
 'jornalismo-digital','estetica-beleza','terapias-contemporaneas','copywriting-vendas','educacao-financeira','mediacao-conflitos'
]
# Extend the shared professional-formation catalog types without disturbing existing products.
m=re.search(r'export type PFSlug=([^;]+);',s)
if not m: raise SystemExit('PFSlug anchor not found')
current=m.group(1)
for slug in new_slugs:
    token=f'"{slug}"'
    if token not in current: current += f'|{token}'
s=s[:m.start()]+f'export type PFSlug={current};'+s[m.end():]

old='type T={name:string;short:string;description:string;project:string;modules:string[]};'
new='type T={name:string;short:string;description:string;project:string;modules:string[];category?:string;disclaimer?:string;portfolio?:string[]};'
if old in s: s=s.replace(old,new,1)
oldpf='export type PF={slug:PFSlug;productKey:string;publicPath:string;learnerPath:string;icon:string;theme:string;priceBrlCents:number;priceEurCents:number;hours:number;lessons:number;modulesCount:number;minimumDays:number;i18n:Record<PFLocale,T>};'
newpf='export type PF={slug:PFSlug;productKey:string;publicPath:string;learnerPath:string;icon:string;theme:string;priceBrlCents:number;priceEurCents:number;hours:number;lessons:number;modulesCount:number;minimumDays:number;includedInSubscription?:boolean;i18n:Record<PFLocale,T>};'
if oldpf in s: s=s.replace(oldpf,newpf,1)
if 'const advanced=' not in s:
    anchor='const common={priceBrlCents:29999,priceEurCents:4990,hours:600,lessons:150,modulesCount:10,minimumDays:75};'
    if anchor not in s: raise SystemExit('common anchor not found')
    s=s.replace(anchor,anchor+'\nconst advanced={priceBrlCents:29999,priceEurCents:4990,hours:600,lessons:150,modulesCount:15,minimumDays:75,includedInSubscription:false};',1)

formations=[
 dict(slug='jornalismo-digital',productKey='formacao_jornalismo_digital_comunicacao_comunidade',publicPath='/formacao-jornalismo-digital',icon='📰',theme='navy',
  pt=dict(name='Formação em Jornalismo Digital, Comunicação e Serviços à Comunidade',short='Jornalismo Digital',category='Comunicação e Jornalismo',description='Formação livre profissional em jornalismo digital, apuração, redação, dados, vídeo, podcast, utilidade pública, audiência, ética e sustentabilidade de mídia.',project='Meu Veículo Digital — Plano Editorial e Financeiro de 12 Meses',disclaimer='Formação livre profissional. Não equivale a graduação em Jornalismo nem substitui requisitos legais ou profissionais aplicáveis em cada país.',portfolio=['Notícia','Entrevista','Reportagem','Conteúdo de utilidade pública','Defesa do consumidor','Reportagem de dados','Investigação documental','Podcast ou vídeo','Newsletter','Projeto multimídia'],modules=['Fundamentos do Jornalismo','Redação Jornalística','Apuração e Fontes','Entrevista','Fact-checking e Verificação','Jornalismo Investigativo','Jornalismo de Dados','Redes Sociais e Distribuição','Vídeo e Jornalismo Audiovisual','Podcast e Áudio','Jornalismo Local e Serviços à Comunidade','Ética, Privacidade e Direito de Resposta','Empreendedorismo em Mídia e Modelos de Receita','SEO, Audiência e IA Aplicada ao Jornalismo','Laboratório de Jornalismo LDR e Projeto Final']),
  en=dict(name='Digital Journalism, Communication and Community Services Training',short='Digital Journalism',category='Communication & Journalism',description='Professional non-degree training in digital journalism, reporting, writing, data, video, podcasts, public-service content, audience, ethics and media sustainability.',project='My Digital Media Outlet — 12-Month Editorial and Financial Plan',disclaimer='Professional non-degree training. It is not a journalism degree and does not replace legal or professional requirements applicable in each country.',modules=['Journalism Foundations','Journalistic Writing','Reporting and Sources','Interviewing','Fact-checking and Verification','Investigative Journalism','Data Journalism','Social Media and Distribution','Video and Audiovisual Journalism','Podcast and Audio','Local Journalism and Community Services','Ethics, Privacy and Right of Reply','Media Entrepreneurship and Revenue Models','SEO, Audience and AI for Journalism','LDR Journalism Lab and Final Project']),
  fr=dict(name='Formation en Journalisme Numérique, Communication et Services à la Communauté',short='Journalisme Numérique',category='Communication et Journalisme',description='Formation professionnelle libre en journalisme numérique, enquête, rédaction, données, vidéo, podcast, service public, audience, éthique et économie des médias.',project='Mon Média Numérique — Plan Éditorial et Financier sur 12 Mois',disclaimer='Formation professionnelle libre. Elle ne constitue pas un diplôme universitaire de journalisme et ne remplace pas les exigences légales ou professionnelles applicables selon le pays.',modules=['Fondamentaux du Journalisme','Écriture Journalistique','Enquête et Sources','Interview','Fact-checking et Vérification','Journalisme d’Investigation','Journalisme de Données','Réseaux Sociaux et Distribution','Vidéo et Journalisme Audiovisuel','Podcast et Audio','Journalisme Local et Services à la Communauté','Éthique, Vie Privée et Droit de Réponse','Entrepreneuriat Média et Modèles de Revenus','SEO, Audience et IA appliquée au Journalisme','Laboratoire de Journalisme LDR et Projet Final']),
  es=dict(name='Formación en Periodismo Digital, Comunicación y Servicios a la Comunidad',short='Periodismo Digital',category='Comunicación y Periodismo',description='Formación profesional libre en periodismo digital, investigación, redacción, datos, vídeo, podcast, servicio público, audiencia, ética y sostenibilidad de medios.',project='Mi Medio Digital — Plan Editorial y Financiero de 12 Meses',disclaimer='Formación profesional libre. No equivale a un grado universitario en Periodismo ni sustituye requisitos legales o profesionales aplicables en cada país.',modules=['Fundamentos del Periodismo','Redacción Periodística','Investigación y Fuentes','Entrevista','Fact-checking y Verificación','Periodismo de Investigación','Periodismo de Datos','Redes Sociales y Distribución','Vídeo y Periodismo Audiovisual','Podcast y Audio','Periodismo Local y Servicios a la Comunidad','Ética, Privacidad y Derecho de Respuesta','Emprendimiento en Medios y Modelos de Ingresos','SEO, Audiencia e IA aplicada al Periodismo','Laboratorio de Periodismo LDR y Proyecto Final'])),
 dict(slug='estetica-beleza',productKey='formacao_estetica_beleza_gestao_servicos',publicPath='/formacao-estetica-beleza',icon='✨',theme='rose',
  pt=dict(name='Formação em Estética, Beleza e Gestão de Serviços',short='Estética & Beleza',category='Estética & Beleza',description='Formação livre profissional em fundamentos da estética, biossegurança, cuidados não invasivos, experiência do cliente, marketing, gestão e precificação.',project='Meu Negócio de Estética e Beleza — Estrutura, Atendimento e Plano Financeiro',disclaimer='Conteúdo educacional voltado a práticas não invasivas. Não habilita para atos reservados a profissões regulamentadas nem substitui formação legalmente exigida.',modules=['Fundamentos da Estética e Beleza','Anatomia e Fisiologia Aplicadas','Pele e Anexos Cutâneos','Biossegurança','Higiene e Segurança','Cosméticos e Princípios Ativos','Estética Facial Não Invasiva','Estética Corporal Não Invasiva','Cuidados Básicos e Protocolos Não Invasivos','Beleza, Imagem e Experiência do Cliente','Atendimento e Anamnese','Ética e Limites Profissionais','Marketing para Profissionais de Beleza','Gestão de Salão, Clínica ou Espaço de Atendimento','Precificação, Vendas, Crescimento e Projeto Final']),
  en=dict(name='Aesthetics, Beauty and Service Management Training',short='Aesthetics & Beauty',category='Aesthetics & Beauty',description='Professional non-degree training in aesthetics foundations, biosafety, non-invasive care, customer experience, marketing, management and pricing.',project='My Aesthetics and Beauty Business — Structure, Service and Financial Plan',disclaimer='Educational content focused on non-invasive practices. It does not qualify learners for regulated acts or replace legally required professional training.',modules=['Aesthetics and Beauty Foundations','Applied Anatomy and Physiology','Skin and Cutaneous Appendages','Biosafety','Hygiene and Safety','Cosmetics and Active Ingredients','Non-invasive Facial Aesthetics','Non-invasive Body Aesthetics','Basic Care and Non-invasive Protocols','Beauty, Image and Customer Experience','Client Service and Intake','Ethics and Professional Boundaries','Marketing for Beauty Professionals','Salon, Clinic or Studio Management','Pricing, Sales, Growth and Final Project']),
  fr=dict(name='Formation en Esthétique, Beauté et Gestion des Services',short='Esthétique & Beauté',category='Esthétique & Beauté',description='Formation professionnelle libre en fondamentaux de l’esthétique, biosécurité, soins non invasifs, expérience client, marketing, gestion et tarification.',project='Mon Entreprise d’Esthétique et Beauté — Structure, Service et Plan Financier',disclaimer='Contenu éducatif centré sur des pratiques non invasives. Il ne qualifie pas pour les actes réservés aux professions réglementées et ne remplace pas les formations légalement requises.',modules=['Fondamentaux de l’Esthétique et de la Beauté','Anatomie et Physiologie Appliquées','Peau et Annexes Cutanées','Biosécurité','Hygiène et Sécurité','Cosmétiques et Principes Actifs','Esthétique Faciale Non Invasive','Esthétique Corporelle Non Invasive','Soins de Base et Protocoles Non Invasifs','Beauté, Image et Expérience Client','Accueil et Anamnèse','Éthique et Limites Professionnelles','Marketing pour Professionnels de la Beauté','Gestion de Salon, Clinique ou Espace','Tarification, Ventes, Croissance et Projet Final']),
  es=dict(name='Formación en Estética, Belleza y Gestión de Servicios',short='Estética & Belleza',category='Estética & Belleza',description='Formación profesional libre en fundamentos de estética, bioseguridad, cuidados no invasivos, experiencia del cliente, marketing, gestión y precios.',project='Mi Negocio de Estética y Belleza — Estructura, Atención y Plan Financiero',disclaimer='Contenido educativo centrado en prácticas no invasivas. No habilita para actos reservados a profesiones reguladas ni sustituye formación legalmente exigida.',modules=['Fundamentos de Estética y Belleza','Anatomía y Fisiología Aplicadas','Piel y Anexos Cutáneos','Bioseguridad','Higiene y Seguridad','Cosméticos y Principios Activos','Estética Facial No Invasiva','Estética Corporal No Invasiva','Cuidados Básicos y Protocolos No Invasivos','Belleza, Imagen y Experiencia del Cliente','Atención y Anamnesis','Ética y Límites Profesionales','Marketing para Profesionales de Belleza','Gestión de Salón, Clínica o Espacio','Precios, Ventas, Crecimiento y Proyecto Final'])),
 dict(slug='terapias-contemporaneas',productKey='formacao_terapias_contemporaneas_desenvolvimento_humano',publicPath='/formacao-terapias-contemporaneas',icon='🌿',theme='green',
  pt=dict(name='Formação em Terapias Contemporâneas e Práticas de Desenvolvimento Humano',short='Desenvolvimento Humano',category='Desenvolvimento Humano',description='Formação livre profissional em escuta, acolhimento, comunicação, desenvolvimento humano, ética, encaminhamento e construção responsável de prática profissional.',project='Programa de Atendimento e Desenvolvimento Humano',disclaimer='Não substitui atendimento médico, psicológico ou de outros profissionais de saúde. A formação enfatiza limites de atuação, consentimento, proteção de dados, situações de risco e encaminhamento adequado.',modules=['História das Práticas Terapêuticas Contemporâneas','Escuta e Acolhimento','Comunicação Terapêutica','Relação de Ajuda','Desenvolvimento Humano','Emoções e Comportamento','Estresse e Autorregulação','Luto e Mudanças','Relacionamentos','Sexualidade e Diversidade','Trabalho e Burnout','Ética e Limites de Atuação','Risco, Encaminhamento e Rede de Saúde Mental','Construção de Prática Profissional','Gestão, Posicionamento e Projeto Final']),
  en=dict(name='Contemporary Therapies and Human Development Practices Training',short='Human Development',category='Human Development',description='Professional non-degree training in listening, support, communication, human development, ethics, referral and responsible practice building.',project='Human Development and Support Program',disclaimer='Does not replace medical, psychological or other health care. The training emphasizes scope limits, consent, data protection, risk situations and appropriate referral.',modules=['History of Contemporary Therapeutic Practices','Listening and Support','Therapeutic Communication','Helping Relationship','Human Development','Emotions and Behavior','Stress and Self-regulation','Grief and Change','Relationships','Sexuality and Diversity','Work and Burnout','Ethics and Scope Limits','Risk, Referral and Mental Health Network','Building a Professional Practice','Management, Positioning and Final Project']),
  fr=dict(name='Formation en Thérapies Contemporaines et Pratiques de Développement Humain',short='Développement Humain',category='Développement Humain',description='Formation professionnelle libre en écoute, accueil, communication, développement humain, éthique, orientation et construction responsable de la pratique.',project='Programme d’Accompagnement et de Développement Humain',disclaimer='Ne remplace pas un suivi médical, psychologique ou autre soin de santé. La formation insiste sur les limites d’exercice, le consentement, la protection des données, les situations à risque et l’orientation appropriée.',modules=['Histoire des Pratiques Thérapeutiques Contemporaines','Écoute et Accueil','Communication Thérapeutique','Relation d’Aide','Développement Humain','Émotions et Comportement','Stress et Autorégulation','Deuil et Changements','Relations','Sexualité et Diversité','Travail et Burnout','Éthique et Limites d’Exercice','Risque, Orientation et Réseau de Santé Mentale','Construction d’une Pratique Professionnelle','Gestion, Positionnement et Projet Final']),
  es=dict(name='Formación en Terapias Contemporáneas y Prácticas de Desarrollo Humano',short='Desarrollo Humano',category='Desarrollo Humano',description='Formación profesional libre en escucha, acogida, comunicación, desarrollo humano, ética, derivación y construcción responsable de práctica profesional.',project='Programa de Atención y Desarrollo Humano',disclaimer='No sustituye atención médica, psicológica ni otros servicios de salud. La formación enfatiza límites de actuación, consentimiento, protección de datos, situaciones de riesgo y derivación adecuada.',modules=['Historia de las Prácticas Terapéuticas Contemporáneas','Escucha y Acogida','Comunicación Terapéutica','Relación de Ayuda','Desarrollo Humano','Emociones y Comportamiento','Estrés y Autorregulación','Duelo y Cambios','Relaciones','Sexualidad y Diversidad','Trabajo y Burnout','Ética y Límites de Actuación','Riesgo, Derivación y Red de Salud Mental','Construcción de Práctica Profesional','Gestión, Posicionamiento y Proyecto Final'])),
 dict(slug='copywriting-vendas',productKey='formacao_copywriting_vendas_consultivas',publicPath='/formacao-copywriting-vendas',icon='✍️',theme='gold',
  pt=dict(name='Formação em Copywriting e Vendas Consultivas',short='Copywriting & Vendas',category='Vendas & Marketing',description='Formação livre profissional em pesquisa de público, copywriting, ofertas, funis, prospecção, vendas consultivas, negociação, CRM e métricas comerciais.',project='Máquina Comercial — Estratégia de Aquisição, Copy e Vendas para 90 Dias',disclaimer='Persuasão deve ser utilizada com transparência, respeito ao consumidor e sem práticas enganosas ou coercitivas.',modules=['Psicologia da Comunicação','Fundamentos de Marketing','Comportamento do Consumidor e Voz do Cliente','Copywriting','Headlines e Promessas Responsáveis','Storytelling','Oferta e Proposta de Valor','Landing Pages','E-mail, WhatsApp e Conteúdo para Redes Sociais','Funis e Jornada do Cliente','Prospecção e Social Selling','Vendas Consultivas e Reuniões Comerciais','Negociação, Objeções e Follow-up','CRM, CAC, LTV, Conversão, Ticket e Retenção','Gestão Comercial, Ética e Projeto Final']),
  en=dict(name='Copywriting and Consultative Sales Training',short='Copywriting & Sales',category='Sales & Marketing',description='Professional non-degree training in audience research, copywriting, offers, funnels, prospecting, consultative sales, negotiation, CRM and sales metrics.',project='Sales Engine — 90-Day Acquisition, Copy and Sales Strategy',disclaimer='Persuasion must be used transparently, respectfully and without deceptive or coercive practices.',modules=['Communication Psychology','Marketing Foundations','Consumer Behavior and Voice of Customer','Copywriting','Headlines and Responsible Promises','Storytelling','Offer and Value Proposition','Landing Pages','Email, WhatsApp and Social Content','Funnels and Customer Journey','Prospecting and Social Selling','Consultative Sales and Sales Meetings','Negotiation, Objections and Follow-up','CRM, CAC, LTV, Conversion, Ticket and Retention','Sales Management, Ethics and Final Project']),
  fr=dict(name='Formation en Copywriting et Vente Consultative',short='Copywriting & Vente',category='Vente & Marketing',description='Formation professionnelle libre en étude du public, copywriting, offres, tunnels, prospection, vente consultative, négociation, CRM et métriques commerciales.',project='Machine Commerciale — Stratégie d’Acquisition, Copy et Vente sur 90 Jours',disclaimer='La persuasion doit être utilisée avec transparence, respect du consommateur et sans pratiques trompeuses ou coercitives.',modules=['Psychologie de la Communication','Fondamentaux du Marketing','Comportement du Consommateur et Voix du Client','Copywriting','Titres et Promesses Responsables','Storytelling','Offre et Proposition de Valeur','Landing Pages','E-mail, WhatsApp et Contenu Social','Tunnels et Parcours Client','Prospection et Social Selling','Vente Consultative et Réunions Commerciales','Négociation, Objections et Follow-up','CRM, CAC, LTV, Conversion, Ticket et Rétention','Gestion Commerciale, Éthique et Projet Final']),
  es=dict(name='Formación en Copywriting y Ventas Consultivas',short='Copywriting & Ventas',category='Ventas & Marketing',description='Formación profesional libre en investigación de público, copywriting, ofertas, embudos, prospección, ventas consultivas, negociación, CRM y métricas comerciales.',project='Máquina Comercial — Estrategia de Adquisición, Copy y Ventas para 90 Días',disclaimer='La persuasión debe utilizarse con transparencia, respeto al consumidor y sin prácticas engañosas o coercitivas.',modules=['Psicología de la Comunicación','Fundamentos de Marketing','Comportamiento del Consumidor y Voz del Cliente','Copywriting','Titulares y Promesas Responsables','Storytelling','Oferta y Propuesta de Valor','Landing Pages','Email, WhatsApp y Contenido Social','Embudos y Recorrido del Cliente','Prospección y Social Selling','Ventas Consultivas y Reuniones Comerciales','Negociación, Objeciones y Follow-up','CRM, CAC, LTV, Conversión, Ticket y Retención','Gestión Comercial, Ética y Proyecto Final'])),
 dict(slug='educacao-financeira',productKey='formacao_gestao_financeira_educacao_investimentos',publicPath='/formacao-educacao-financeira',icon='💶',theme='petrol',
  pt=dict(name='Formação em Gestão Financeira, Educação Financeira e Investimentos',short='Finanças & Investimentos',category='Finanças & Negócios',description='Formação livre profissional com trilhas de Pessoa Física e Pequenos Negócios/MEI, cobrindo matemática financeira, orçamento, investimentos, fluxo de caixa, custos, margem e planejamento.',project='Plano Financeiro Pessoal e Empresarial de 12 Meses',disclaimer='Conteúdo de educação financeira. Não constitui recomendação individual de investimento, consultoria financeira, jurídica, fiscal ou tributária.',modules=['Fundamentos de Finanças','Matemática Financeira: Juros, Inflação e Valor do Dinheiro','Organização Financeira Pessoal e Orçamento','Crédito, Dívida e Reserva de Emergência','Sistema Financeiro e Produtos Financeiros','Renda Fixa','Renda Variável','Fundos, ETFs, Risco, Retorno e Diversificação','Trilha Pessoa Física: Planejamento e Investimentos','Finanças para MEI e Pequenos Negócios','Fluxo de Caixa e Capital de Giro','Custos, Preço, Margem, Markup e Ponto de Equilíbrio','DRE Simplificada, Pró-labore e Separação PF/PJ','Tributação Introdutória, Reserva Empresarial e Decisões Financeiras','Planejamento Financeiro Integrado e Projeto Final']),
  en=dict(name='Financial Management, Financial Education and Investments Training',short='Finance & Investments',category='Finance & Business',description='Professional non-degree training with Personal Finance and Small Business tracks covering financial math, budgeting, investments, cash flow, costs, margin and planning.',project='12-Month Personal and Business Financial Plan',disclaimer='Financial education content only. It is not individualized investment advice or financial, legal, tax or accounting consulting.',modules=['Finance Foundations','Financial Math: Interest, Inflation and Time Value','Personal Financial Organization and Budgeting','Credit, Debt and Emergency Fund','Financial System and Products','Fixed Income','Equities','Funds, ETFs, Risk, Return and Diversification','Personal Finance Track: Planning and Investments','Finance for Small Business and Self-employed','Cash Flow and Working Capital','Costs, Pricing, Margin, Markup and Break-even','Simplified Income Statement, Owner Pay and PF/PJ Separation','Introductory Taxation, Business Reserve and Financial Decisions','Integrated Financial Planning and Final Project']),
  fr=dict(name='Formation en Gestion Financière, Éducation Financière et Investissements',short='Finance & Investissements',category='Finance & Entreprise',description='Formation professionnelle libre avec parcours Finances Personnelles et Petites Entreprises couvrant mathématiques financières, budget, investissements, trésorerie, coûts, marge et planification.',project='Plan Financier Personnel et Professionnel sur 12 Mois',disclaimer='Contenu d’éducation financière uniquement. Il ne constitue pas un conseil individualisé en investissement ni une consultation financière, juridique ou fiscale.',modules=['Fondamentaux de la Finance','Mathématiques Financières : Intérêts, Inflation et Valeur Temps','Organisation Financière Personnelle et Budget','Crédit, Dette et Fonds d’Urgence','Système Financier et Produits','Revenu Fixe','Actions','Fonds, ETF, Risque, Rendement et Diversification','Parcours Particulier : Planification et Investissements','Finances pour Petites Entreprises et Indépendants','Trésorerie et Fonds de Roulement','Coûts, Prix, Marge, Markup et Seuil de Rentabilité','Compte de Résultat Simplifié, Rémunération et Séparation Privé/Pro','Fiscalité Introductive, Réserve d’Entreprise et Décisions Financières','Planification Financière Intégrée et Projet Final']),
  es=dict(name='Formación en Gestión Financiera, Educación Financiera e Inversiones',short='Finanzas & Inversiones',category='Finanzas & Negocios',description='Formación profesional libre con itinerarios de Persona Física y Pequeños Negocios, cubriendo matemáticas financieras, presupuesto, inversiones, flujo de caja, costes, margen y planificación.',project='Plan Financiero Personal y Empresarial de 12 Meses',disclaimer='Contenido de educación financiera. No constituye recomendación individual de inversión ni asesoría financiera, jurídica, fiscal o tributaria.',modules=['Fundamentos de Finanzas','Matemática Financiera: Intereses, Inflación y Valor del Dinero','Organización Financiera Personal y Presupuesto','Crédito, Deuda y Fondo de Emergencia','Sistema Financiero y Productos','Renta Fija','Renta Variable','Fondos, ETF, Riesgo, Retorno y Diversificación','Itinerario Persona Física: Planificación e Inversiones','Finanzas para Autónomos y Pequeños Negocios','Flujo de Caja y Capital de Trabajo','Costes, Precio, Margen, Markup y Punto de Equilibrio','Estado de Resultados Simplificado, Remuneración y Separación PF/PJ','Fiscalidad Introductoria, Reserva Empresarial y Decisiones Financieras','Planificación Financiera Integrada y Proyecto Final'])),
 dict(slug='mediacao-conflitos',productKey='formacao_mediacao_negociacao_resolucao_conflitos',publicPath='/formacao-mediacao-conflitos',icon='⚖️',theme='purple',
  pt=dict(name='Formação em Mediação, Negociação e Resolução de Conflitos',short='Mediação & Conflitos',category='Mediação & Conflitos',description='Formação livre profissional em teoria do conflito, comunicação, negociação, técnicas de mediação, ética, confidencialidade, construção de acordos e estudos de caso.',project='Caso Completo de Mediação — Diagnóstico, Sessões e Construção de Acordo',disclaimer='Formação livre profissional. O certificado não habilita automaticamente para atuação como mediador judicial; requisitos legais variam por país e jurisdição.',modules=['Teoria do Conflito','Comunicação Interpessoal','Comunicação Não Violenta','Escuta Ativa','Negociação: Posições, Interesses e BATNA','Técnicas de Mediação','Gestão de Emoções','Conflitos Familiares','Conflitos Empresariais','Conflitos Comunitários','Conflitos de Consumo','Mediação Online','Ética, Imparcialidade, Neutralidade e Confidencialidade','Construção de Alternativas, Caucus e Termos de Acordo','Prática com Estudos de Caso e Projeto Final']),
  en=dict(name='Mediation, Negotiation and Conflict Resolution Training',short='Mediation & Conflict',category='Mediation & Conflict',description='Professional non-degree training in conflict theory, communication, negotiation, mediation techniques, ethics, confidentiality, agreement building and case studies.',project='Complete Mediation Case — Diagnosis, Sessions and Agreement Building',disclaimer='Professional non-degree training. The certificate does not automatically qualify the learner to act as a court mediator; legal requirements vary by country and jurisdiction.',modules=['Conflict Theory','Interpersonal Communication','Nonviolent Communication','Active Listening','Negotiation: Positions, Interests and BATNA','Mediation Techniques','Emotion Management','Family Conflicts','Business Conflicts','Community Conflicts','Consumer Conflicts','Online Mediation','Ethics, Impartiality, Neutrality and Confidentiality','Alternatives, Caucus and Agreement Terms','Case Practice and Final Project']),
  fr=dict(name='Formation en Médiation, Négociation et Résolution des Conflits',short='Médiation & Conflits',category='Médiation & Conflits',description='Formation professionnelle libre en théorie du conflit, communication, négociation, techniques de médiation, éthique, confidentialité, accords et études de cas.',project='Cas Complet de Médiation — Diagnostic, Séances et Construction d’Accord',disclaimer='Formation professionnelle libre. Le certificat ne qualifie pas automatiquement pour exercer comme médiateur judiciaire ; les exigences légales varient selon le pays et la juridiction.',modules=['Théorie du Conflit','Communication Interpersonnelle','Communication Non Violente','Écoute Active','Négociation : Positions, Intérêts et BATNA','Techniques de Médiation','Gestion des Émotions','Conflits Familiaux','Conflits d’Entreprise','Conflits Communautaires','Conflits de Consommation','Médiation en Ligne','Éthique, Impartialité, Neutralité et Confidentialité','Alternatives, Caucus et Termes d’Accord','Pratique par Études de Cas et Projet Final']),
  es=dict(name='Formación en Mediación, Negociación y Resolución de Conflictos',short='Mediación & Conflictos',category='Mediación & Conflictos',description='Formación profesional libre en teoría del conflicto, comunicación, negociación, técnicas de mediación, ética, confidencialidad, construcción de acuerdos y casos.',project='Caso Completo de Mediación — Diagnóstico, Sesiones y Construcción de Acuerdo',disclaimer='Formación profesional libre. El certificado no habilita automáticamente para actuar como mediador judicial; los requisitos legales varían por país y jurisdicción.',modules=['Teoría del Conflicto','Comunicación Interpersonal','Comunicación No Violenta','Escucha Activa','Negociación: Posiciones, Intereses y BATNA','Técnicas de Mediación','Gestión de Emociones','Conflictos Familiares','Conflictos Empresariales','Conflictos Comunitarios','Conflictos de Consumo','Mediación Online','Ética, Imparcialidad, Neutralidad y Confidencialidad','Construcción de Alternativas, Caucus y Términos de Acuerdo','Práctica con Casos y Proyecto Final']))
]

def ts(v):
    return json.dumps(v,ensure_ascii=False,separators=(',',':'))

def entry(f):
    loc=[]
    for code in ['pt','en','fr','es']:
        d=f[code].copy()
        loc.append(f'{code}:'+ts(d))
    return '{slug:'+ts(f['slug'])+',productKey:'+ts(f['productKey'])+',publicPath:'+ts(f['publicPath'])+',learnerPath:'+ts('/cliente/treinamentos/formacao-profissional/'+f['slug'])+',icon:'+ts(f['icon'])+',theme:'+ts(f['theme'])+',...advanced,i18n:{'+','.join(loc)+'}}'

if 'formacao_jornalismo_digital_comunicacao_comunidade' not in s:
    marker='\n];\nexport function getProfessionalFormation'
    if marker not in s: raise SystemExit('catalog end marker not found')
    block=',\n'+',\n'.join(entry(f) for f in formations)
    s=s.replace(marker,block+marker,1)

# Replace the old generic lesson filler with a richer course/module/topic-specific academic scaffold.
start=s.find('export function buildLessons(')
if start<0: raise SystemExit('buildLessons not found')
new_builder=r'''export function buildLessons(f:PF,locale:PFLocale){
 const t=pfText(f,locale),perModule=Math.max(1,Math.floor(f.lessons/f.modulesCount));
 const L={
  pt:{lesson:"Aula",objective:"Objetivo de aprendizagem",question:"Pergunta central",concepts:"Conceitos fundamentais",context:"Contexto e desenvolvimento",caseLabel:"Estudo de caso",critical:"Análise crítica",practice:"Atividade prática",errors:"Erros e riscos",synthesis:"Síntese",refs:"Referências para aprofundamento"},
  en:{lesson:"Lesson",objective:"Learning objective",question:"Central question",concepts:"Core concepts",context:"Context and development",caseLabel:"Case study",critical:"Critical analysis",practice:"Practical activity",errors:"Errors and risks",synthesis:"Synthesis",refs:"Further reading"},
  fr:{lesson:"Leçon",objective:"Objectif d’apprentissage",question:"Question centrale",concepts:"Concepts fondamentaux",context:"Contexte et développement",caseLabel:"Étude de cas",critical:"Analyse critique",practice:"Activité pratique",errors:"Erreurs et risques",synthesis:"Synthèse",refs:"Pour approfondir"},
  es:{lesson:"Clase",objective:"Objetivo de aprendizaje",question:"Pregunta central",concepts:"Conceptos fundamentales",context:"Contexto y desarrollo",caseLabel:"Estudio de caso",critical:"Análisis crítico",practice:"Actividad práctica",errors:"Errores y riesgos",synthesis:"Síntesis",refs:"Referencias para profundizar"}
 }[locale];
 const angles={
  pt:["fundamentos e linguagem técnica","história, contexto e evolução","autores, modelos e conceitos centrais","diagnóstico do problema e critérios de análise","métodos, ferramentas e tomada de decisão","estudo de caso aplicado","laboratório e aplicação profissional","ética, limites, riscos e proteção de pessoas","avaliação de evidências, resultados e melhoria","integração ao projeto profissional"],
  en:["foundations and technical language","history, context and evolution","authors, models and central concepts","problem diagnosis and analysis criteria","methods, tools and decision-making","applied case study","lab and professional application","ethics, limits, risks and protection","evaluation of evidence, outcomes and improvement","integration into the professional project"],
  fr:["fondements et langage technique","histoire, contexte et évolution","auteurs, modèles et concepts centraux","diagnostic du problème et critères d’analyse","méthodes, outils et prise de décision","étude de cas appliquée","laboratoire et application professionnelle","éthique, limites, risques et protection","évaluation des preuves, résultats et amélioration","intégration au projet professionnel"],
  es:["fundamentos y lenguaje técnico","historia, contexto y evolución","autores, modelos y conceptos centrales","diagnóstico del problema y criterios de análisis","métodos, herramientas y toma de decisiones","caso aplicado","laboratorio y aplicación profesional","ética, límites, riesgos y protección","evaluación de evidencias, resultados y mejora","integración en el proyecto profesional"]
 }[locale];
 const safe=(x:string)=>x.toLowerCase();
 return t.modules.map((moduleTitle,mi)=>({id:mi+1,title:moduleTitle,lessons:Array.from({length:perModule},(_,li)=>{
  const n=mi*perModule+li+1,angle=angles[li%angles.length],subject=safe(moduleTitle);
  const title=`${L.lesson} ${n} · ${moduleTitle} — ${angle}`;
  const content=[
   `${L.objective}: dominar ${angle} no eixo ${subject}, relacionando teoria, contexto profissional e o projeto final “${t.project}”.`,
   `${L.question}: quais decisões, critérios e limites tornam ${subject} tecnicamente consistente, verificável e adequado ao contexto real de atuação?`,
   `${L.concepts}: identifique a terminologia própria de ${subject}, diferencie conceitos próximos e registre relações de causa, evidência, contexto e consequência. A leitura deve evitar simplificações e separar afirmações factuais, interpretações e hipóteses.`,
   `${L.context}: analise como ${subject} se desenvolve dentro de ${t.name}. Compare abordagens possíveis, observe mudanças históricas e tecnológicas quando pertinentes e conecte o conteúdo às demandas atuais do campo.`,
   `${L.caseLabel}: construa ou examine uma situação profissional plausível envolvendo ${subject}. Delimite o problema, os atores envolvidos, as informações disponíveis, o que ainda precisa ser verificado e duas alternativas de ação.`,
   `${L.critical}: compare as alternativas do caso, explicite vantagens, limites, riscos e possíveis efeitos não intencionais. Quando houver regra legal, clínica, financeira ou profissional, trate o conteúdo como educação e indique a necessidade de verificar fontes oficiais atuais.`,
   `${L.practice}: produza uma entrega específica sobre ${subject} — diagnóstico, roteiro, protocolo não invasivo, análise, texto, planilha, mapa de decisão, peça de comunicação ou plano — escolhendo o formato coerente com esta formação. Registre critérios usados e como o resultado será avaliado.`,
   `${L.errors}: evite copiar modelos sem adaptação, afirmar dados sem fonte, confundir opinião com evidência, prometer resultados e ultrapassar limites éticos ou profissionais. Revise a entrega considerando público, contexto, privacidade, segurança e clareza.`,
   `${L.synthesis}: resuma em cinco pontos o que muda na sua prática após estudar ${subject} e conecte essa síntese ao módulo anterior e ao próximo passo do projeto.`,
   `${L.refs}: priorize livros acadêmicos, artigos revisados por pares, documentos técnicos, normas e fontes oficiais pertinentes ao tema. Não use referências inventadas; registre autor, instituição, título e data quando consultar uma fonte.`
  ];
  return{id:`${f.slug}-m${mi+1}-l${li+1}`,title,summary:`${L.objective}: ${moduleTitle} — ${angle}.`,content};
 })}));
}'''
s=s[:start]+new_builder+'\n'
cat.write_text(s)

# Public page: dynamic module/lesson counts, independent-product notice, Stripe messaging, category/disclaimer/portfolio.
p=ROOT/'components/professional-formation-public-page.tsx'; x=p.read_text()
x=x.replace('modules:"10 MÓDULOS",project:', 'modules:"MÓDULOS",project:')
x=x.replace('modules:"10 MODULES",project:', 'modules:"MODULES",project:')
x=x.replace('modules:"10 MODULES",project:', 'modules:"MODULES",project:')
x=x.replace('modules:"10 MÓDULOS",project:', 'modules:"MÓDULOS",project:')
for old,new in [
 ('library:"Também disponível pela assinatura ativa da Biblioteca LDR.",notice:', 'library:"Também disponível pela assinatura ativa da Biblioteca LDR.",independent:"Produto independente · não incluído automaticamente na assinatura mensal.",stripe:"Pagamento seguro via Stripe.",altPay:"Precisa de outra forma de pagamento? Entre em contato.",notice:'),
 ('library:"Also available through an active LDR Library subscription.",notice:', 'library:"Also available through an active LDR Library subscription.",independent:"Independent product · not automatically included in the monthly subscription.",stripe:"Secure payment via Stripe.",altPay:"Need another payment method? Contact us.",notice:'),
 ('library:"Également disponible avec l’abonnement actif à la Bibliothèque LDR.",notice:', 'library:"Également disponible avec l’abonnement actif à la Bibliothèque LDR.",independent:"Produit indépendant · non inclus automatiquement dans l’abonnement mensuel.",stripe:"Paiement sécurisé via Stripe.",altPay:"Besoin d’un autre mode de paiement ? Contactez-nous.",notice:'),
 ('library:"También disponible con la suscripción activa de la Biblioteca LDR.",notice:', 'library:"También disponible con la suscripción activa de la Biblioteca LDR.",independent:"Producto independiente · no incluido automáticamente en la suscripción mensual.",stripe:"Pago seguro mediante Stripe.",altPay:"¿Necesitas otra forma de pago? Contáctanos.",notice:')]:
    x=x.replace(old,new)
x=x.replace('{[u.online,u.hours,u.lessons,u.modules,u.project].map(x=>', '{[u.online,`${f.hours} ${locale==="en"?"HOURS":locale==="fr"?"HEURES":locale==="es"?"HORAS":"HORAS"}`,`${f.lessons} ${locale==="en"?"LESSONS":locale==="fr"?"LEÇONS":locale==="es"?"CLASES":"AULAS"}`,`${f.modulesCount} ${u.modules}`,u.project].map(x=>')
x=x.replace('{u.price} · {u.library}', '{u.price} · {f.includedInSubscription===false?u.independent:u.library}')
x=x.replace('</p></div></section><section className="mx-auto max-w-6xl px-4 py-14">', '</p><p className="mt-2 text-xs text-white/65">{u.stripe} {u.altPay}</p></div></section><section className="mx-auto max-w-6xl px-4 py-14">')
x=x.replace('<h2 className="font-serif text-3xl">{u.learn}</h2>', '<p className="text-xs font-black uppercase tracking-[.16em] text-[#a06f1c]">{t.category??"FORMAÇÃO PROFISSIONAL"}</p><h2 className="mt-2 font-serif text-3xl">{u.learn}</h2>')
x=x.replace('15 {locale==="fr"?"leçons":locale==="es"?"clases":locale==="en"?"lessons":"aulas"}', '{Math.max(1,Math.floor(f.lessons/f.modulesCount))} {locale==="fr"?"leçons":locale==="es"?"clases":locale==="en"?"lessons":"aulas"}')
x=x.replace('<p className="mt-6 text-xs text-slate-500">{u.notice}</p>', '{t.portfolio?.length?<section className="mt-8 rounded-3xl border bg-white p-6"><h3 className="font-serif text-2xl">Portfólio obrigatório</h3><div className="mt-4 flex flex-wrap gap-2">{t.portfolio.map(item=><span key={item} className="rounded-full bg-[#f7f3e9] px-3 py-2 text-xs font-bold">{item}</span>)}</div></section>:null}<p className="mt-6 text-xs text-slate-500">{t.disclaimer??u.notice}</p>')
p.write_text(x)

# Cards used in the authenticated library: dynamic counts and category; preserve existing products.
p=ROOT/'components/five-professional-formation-cards.tsx'; x=p.read_text()
x=x.replace('<div className="text-3xl">{f.icon}</div><span', '<div className="flex items-start justify-between gap-3"><div className="text-3xl">{f.icon}</div>{t.category?<span className="rounded-full bg-[#f7f3e9] px-2 py-1 text-[9px] font-black text-[#7a5a22]">{t.category}</span>:null}</div><span')
x=x.replace('150 {u.lessons}', '{f.lessons} {u.lessons}').replace('10 {u.modules}', '{f.modulesCount} {u.modules}')
x=x.replace('<p className="mt-4 font-black">R$ 299,99 · € 49,90</p></a>', '<p className="mt-4 font-black">R$ 299,99 · € 49,90</p><p className="mt-1 text-[10px] text-slate-500">Pagamento seguro via Stripe · outra forma de pagamento: entre em contato.</p></a>')
p.write_text(x)

# Learner page: make module/lesson math data-driven so 15x10 formations work without affecting existing 10x15 courses.
p=ROOT/'routes/_clientarea.cliente.treinamentos.formacao-profissional.$slug.tsx'; x=p.read_text()
x=x.replace('const mod=modules[Math.min(state.module,modules.length-1)],lesson=mod.lessons[Math.min(state.lesson,14)],global=state.module*15+state.lesson,max=Number(offer.maxUnlockedLesson??2),nextLocked=global+1>=max,progress=Math.round(state.completed.length/150*100);', 'const perModule=Math.max(1,Math.floor(f.lessons/f.modulesCount)),mod=modules[Math.min(state.module,modules.length-1)],lesson=mod.lessons[Math.min(state.lesson,perModule-1)],global=state.module*perModule+state.lesson,max=Number(offer.maxUnlockedLesson??2),nextLocked=global+1>=max,progress=Math.round(state.completed.length/f.lessons*100);')
x=x.replace('Math.round(n.completed.length/150*100)', 'Math.round(n.completed.length/f.lessons*100)')
x=x.replace('if(state.lesson<14)', 'if(state.lesson<perModule-1)').replace('else if(state.module<9)', 'else if(state.module<f.modulesCount-1)').replace('lesson:14', 'lesson:perModule-1')
x=x.replace('i*15>=max', 'i*perModule>=max')
x=x.replace('{global+1}/150', '{global+1}/{f.lessons}')
x=x.replace('100% online · 600h · 150 aulas · 10 módulos · projeto final obrigatório', '100% online · {f.hours}h · {f.lessons} aulas · {f.modulesCount} módulos · projetos e avaliação · projeto final obrigatório')
x=x.replace('100% online · 600h · 150 {locale==="fr"?"leçons":locale==="es"?"clases":locale==="en"?"lessons":"aulas"} · 10 módulos · {t.project}', '100% online · {f.hours}h · {f.lessons} {locale==="fr"?"leçons":locale==="es"?"clases":locale==="en"?"lessons":"aulas"} · {f.modulesCount} módulos · {t.project}')
p.write_text(x)

# Create one public route per advanced formation; generic learner route remains shared, preventing duplicate products.
routes={
 'formacao-jornalismo-digital.tsx':'jornalismo-digital',
 'formacao-estetica-beleza.tsx':'estetica-beleza',
 'formacao-terapias-contemporaneas.tsx':'terapias-contemporaneas',
 'formacao-copywriting-vendas.tsx':'copywriting-vendas',
 'formacao-educacao-financeira.tsx':'educacao-financeira',
 'formacao-mediacao-conflitos.tsx':'mediacao-conflitos',
}
for filename,slug in routes.items():
    p=ROOT/'routes'/filename
    route='/'+filename[:-4]
    p.write_text(f'import {{ createFileRoute }} from "@tanstack/react-router";import {{ ProfessionalFormationPublicPage }} from "@/components/professional-formation-public-page";export const Route=createFileRoute("{route}")({{component:()=> <ProfessionalFormationPublicPage slug="{slug}"/>}});\n')

# Only the main psychoanalysis formation may publicly advertise its six live meetings.
p=ROOT/'components/library-sales-home-access-choice.tsx'; x=p.read_text()
repls={
 '90 aulas · 6 encontros ao vivo · aplicação prática em posicionamento, vendas e construção do negócio.':'90 aulas · 100% online · projetos práticos e avaliação aplicada em posicionamento, vendas e construção do negócio.',
 '90 lessons · 6 live meetings · practical positioning, sales and business building.':'90 lessons · 100% online · practical projects and assessment in positioning, sales and business building.',
 '90 leçons · 6 rencontres en direct · positionnement, vente et construction d’activité.':'90 leçons · 100% en ligne · projets pratiques et évaluation en positionnement, vente et construction d’activité.',
 '90 clases · 6 encuentros en vivo · posicionamiento, ventas y construcción de negocio.':'90 clases · 100% online · proyectos prácticos y evaluación en posicionamiento, ventas y construcción de negocio.'
}
for a,b in repls.items(): x=x.replace(a,b)
p.write_text(x)

# Remove live-meeting marketing from Brief Therapy public metadata; content/access remain untouched.
p=ROOT/'routes/formacao-terapia-breve-psicanalitica.tsx'; x=p.read_text().replace('Formação em Terapia Breve Psicanalítica: 15 módulos, 300 aulas, 1.200 horas e 6 encontros ao vivo.','Formação em Terapia Breve Psicanalítica: 15 módulos, 300 aulas, 1.200 horas, 100% online, projetos práticos e avaliação de projetos.')
p.write_text(x)

# Remove the same Brief Therapy promise from the shared sales-card translations while preserving Psychoanalysis live meetings.
p=ROOT/'lib/library-sales-card-i18n.ts'; x=p.read_text()
for a,b in [
 ('15 módulos · 300 aulas · 1.200 horas · 6 encontros ao vivo','15 módulos · 300 aulas · 1.200 horas · 100% online · projetos e avaliação'),
 ('15 modules · 300 lessons · 1,200 hours · 6 live meetings','15 modules · 300 lessons · 1,200 hours · 100% online · projects and assessment'),
 ('15 modules · 300 leçons · 1 200 heures · 6 rencontres en direct','15 modules · 300 leçons · 1 200 heures · 100% en ligne · projets et évaluation'),
 ('15 módulos · 300 clases · 1.200 horas · 6 encuentros en vivo','15 módulos · 300 clases · 1.200 horas · 100% online · proyectos y evaluación')]: x=x.replace(a,b)
p.write_text(x)

print('Integrated LDR Academy expansion prepared safely.')
