from pathlib import Path

p=Path('apps/painel-ldr/src/routes/_clientarea.cliente.rede-academica.tsx')
s=p.read_text()
old='''    <div className="hidden flex-wrap items-center gap-2 sm:flex">\n      <button type="button" onClick={()=>{setTab("feed");setTimeout(()=>{const el=document.getElementById("academic-composer");el?.scrollIntoView({behavior:"smooth",block:"center"});el?.querySelector<HTMLTextAreaElement>("textarea")?.focus()},0)}} className="min-h-11 rounded-xl bg-[#07315a] px-4 py-3 text-[10px] font-black text-white"><Plus className="mr-1 inline h-4 w-4"/>{locale==="pt"?"CRIAR":locale==="en"?"CREATE":locale==="fr"?"CRÉER":"CREAR"}</button>\n      <Link to="/cliente/rede-academica/buscar" className="min-h-11 rounded-xl border bg-card px-4 py-3 text-[10px] font-black"><Search className="mr-1 inline h-4 w-4"/>{locale==="pt"?"BUSCAR":locale==="en"?"SEARCH":locale==="fr"?"RECHERCHER":"BUSCAR"}</Link>\n      <Link to="/cliente/rede-academica/notificacoes" className="min-h-11 rounded-xl border bg-card px-4 py-3 text-[10px] font-black"><Bell className="mr-1 inline h-4 w-4"/>{locale==="pt"?"NOTIFICAÇÕES":locale==="en"?"NOTIFICATIONS":locale==="fr"?"NOTIFICATIONS":"NOTIFICACIONES"}</Link>\n      <Link to="/cliente/rede-academica/desafios" className="min-h-11 rounded-xl border bg-card px-4 py-3 text-[10px] font-black">{locale==="pt"?"DESAFIOS":locale==="en"?"CHALLENGES":locale==="fr"?"DÉFIS":"DESAFÍOS"}</Link>\n      <Link to="/cliente/rede-academica/salvos" className="min-h-11 rounded-xl border bg-card px-4 py-3 text-[10px] font-black">{t.saved}</Link>\n    </div>\n'''
if old not in s: raise SystemExit('secondary desktop navigation block not found; stop safely')
s=s.replace(old,'',1)
old_labels='''const labels={pt:{library:"Biblioteca",accessibility:"Acessibilidade",chat:"Chat"},en:{library:"Library",accessibility:"Accessibility",chat:"Chat"},fr:{library:"Bibliothèque",accessibility:"Accessibilité",chat:"Chat"},es:{library:"Biblioteca",accessibility:"Accesibilidad",chat:"Chat"}}[locale];'''
new_labels='''const labels={pt:{library:"Biblioteca",accessibility:"Acessibilidade",chat:"Chat",search:"Buscar",notifications:"Notificações",challenges:"Desafios"},en:{library:"Library",accessibility:"Accessibility",chat:"Chat",search:"Search",notifications:"Notifications",challenges:"Challenges"},fr:{library:"Bibliothèque",accessibility:"Accessibilité",chat:"Chat",search:"Rechercher",notifications:"Notifications",challenges:"Défis"},es:{library:"Biblioteca",accessibility:"Accesibilidad",chat:"Chat",search:"Buscar",notifications:"Notificaciones",challenges:"Desafíos"}}[locale];'''
if old_labels not in s: raise SystemExit('utility labels block not found; stop safely')
s=s.replace(old_labels,new_labels,1)
old_chat='''    <Link to="/cliente/rede-academica/chat" className={item}><MessageCircle className="h-4 w-4 shrink-0 text-[#b78927]"/><span>{labels.chat}</span></Link>\n'''
new_chat='''    <Link to="/cliente/rede-academica/chat" className={item}><MessageCircle className="h-4 w-4 shrink-0 text-[#b78927]"/><span>{labels.chat}</span></Link>\n    <Link to="/cliente/rede-academica/buscar" className={item}><Search className="h-4 w-4 shrink-0 text-[#b78927]"/><span>{labels.search}</span></Link>\n    <Link to="/cliente/rede-academica/notificacoes" className={item}><Bell className="h-4 w-4 shrink-0 text-[#b78927]"/><span>{labels.notifications}</span></Link>\n    <Link to="/cliente/rede-academica/desafios" className={item}><Network className="h-4 w-4 shrink-0 text-[#b78927]"/><span>{labels.challenges}</span></Link>\n'''
if old_chat not in s: raise SystemExit('utility chat link not found; stop safely')
s=s.replace(old_chat,new_chat,1)
p.write_text(s)
