from pathlib import Path

ROOT=Path('apps/painel-ldr/src')
feed=ROOT/'components/academic-social-v3-feed.tsx'
server=ROOT/'lib/academic-network.server.ts'

def once(text, old, new, label):
    n=text.count(old)
    if n!=1: raise SystemExit(f'{label}: expected 1 match, found {n}')
    return text.replace(old,new,1)

s=feed.read_text()
s=once(s,'import { useMemo, useRef, useState } from "react";','import { useEffect, useMemo, useRef, useState } from "react";','react useEffect')
old=''' const [text,setText]=useState(""),[commentOpen,setCommentOpen]=useState(false),[shareOpen,setShareOpen]=useState(false),[shareMessage,setShareMessage]=useState("");const roleLabel:Record<string,string>={member:t.member,student:t.student,professor:t.professor,mentor:t.mentor};const postUrl=()=>`${window.location.origin}/cliente/rede-academica/post/${p.id}`;'''
new=''' const [text,setText]=useState(""),[commentOpen,setCommentOpen]=useState(false),[shareOpen,setShareOpen]=useState(false),[shareMessage,setShareMessage]=useState(""),[supported,setSupported]=useState(Boolean(p.supported)),[saved,setSaved]=useState(Boolean(p.saved)),[supportCount,setSupportCount]=useState(Math.max(0,Number(p.supportCount||0))),[actionError,setActionError]=useState("");const supportBase=useRef(Boolean(p.supported)),saveBase=useRef(Boolean(p.saved)),supportTimer=useRef<number|undefined>(undefined),saveTimer=useRef<number|undefined>(undefined);const roleLabel:Record<string,string>={member:t.member,student:t.student,professor:t.professor,mentor:t.mentor};const postUrl=()=>`${window.location.origin}/cliente/rede-academica/post/${p.id}`;
 useEffect(()=>{supportBase.current=Boolean(p.supported);saveBase.current=Boolean(p.saved);setSupported(Boolean(p.supported));setSaved(Boolean(p.saved));setSupportCount(Math.max(0,Number(p.supportCount||0)))},[p.id,p.supported,p.saved,p.supportCount]);
 const toggleSupport=()=>{if(!premium)return;setActionError("");setSupported(current=>{const next=!current;setSupportCount(count=>Math.max(0,count+(next?1:-1)));if(supportTimer.current)window.clearTimeout(supportTimer.current);supportTimer.current=window.setTimeout(async()=>{if(next===supportBase.current)return;try{const result=await support.mutateAsync(p.id);supportBase.current=Boolean(result?.supported);setSupported(supportBase.current);if(typeof result?.supportCount==='number')setSupportCount(Math.max(0,result.supportCount))}catch(err:any){setSupported(supportBase.current);setSupportCount(Math.max(0,Number(p.supportCount||0)));setActionError(String(err?.message||err))}},220);return next})};
 const toggleSave=()=>{if(!premium)return;setActionError("");setSaved(current=>{const next=!current;if(saveTimer.current)window.clearTimeout(saveTimer.current);saveTimer.current=window.setTimeout(async()=>{if(next===saveBase.current)return;try{const result=await save.mutateAsync(p.id);saveBase.current=Boolean(result?.saved);setSaved(saveBase.current)}catch(err:any){setSaved(saveBase.current);setActionError(String(err?.message||err))}},220);return next})};'''
s=once(s,old,new,'real card local action state')
old='''<div className="academic-v4-post-actions mt-3 grid grid-cols-4 border-t pt-2"><Mini active={Boolean(p.supported)} tone="support" onClick={()=>support.mutate(p.id)} disabled={!premium||support.isPending} icon={HeartHandshake} label={`${p.supported?t.supported:t.support} ${p.supportCount||""}`}/><Mini onClick={()=>setCommentOpen(v=>!v)} disabled={!premium} icon={MessageCircle} label={c.comment}/><Mini active={Boolean(p.saved)} tone="save" onClick={()=>save.mutate(p.id)} disabled={!premium||save.isPending} icon={Bookmark} label={p.saved?t.savedAction:t.save}/><Mini onClick={()=>{setShareOpen(v=>!v);setShareMessage("")}} icon={Share2} label={c.share}/></div>'''
new='''<div className="academic-v4-post-actions mt-3 grid grid-cols-4 border-t pt-2"><Mini active={supported} tone="support" onClick={toggleSupport} disabled={!premium} icon={HeartHandshake} label={`${supported?t.supported:t.support} ${supportCount>0?supportCount:""}`}/><Mini onClick={()=>setCommentOpen(v=>!v)} disabled={!premium} icon={MessageCircle} label={c.comment}/><Mini active={saved} tone="save" onClick={toggleSave} disabled={!premium} icon={Bookmark} label={saved?t.savedAction:t.save}/><Mini onClick={()=>{setShareOpen(v=>!v);setShareMessage("")}} icon={Share2} label={c.share}/></div>{actionError&&<p className="mt-2 text-xs text-destructive">{actionError}</p>}'''
s=once(s,old,new,'real card action controls')
feed.write_text(s)

s=server.read_text()
old='''export async function toggleAcademicSave(userId:string,postId:string){ await requirePremium(userId); const {data}=await db.from("academic_saved_posts").select("post_id").eq("user_id",userId).eq("post_id",postId).maybeSingle(); if(data)await db.from("academic_saved_posts").delete().eq("user_id",userId).eq("post_id",postId); else await db.from("academic_saved_posts").insert({user_id:userId,post_id:postId}); return {saved:!data}; }'''
new='''export async function toggleAcademicSave(userId:string,postId:string){ await requirePremium(userId); const current=await db.from("academic_saved_posts").select("post_id").eq("user_id",userId).eq("post_id",postId).maybeSingle(); if(current.error)fail("Não foi possível verificar a publicação salva."); if(current.data){const removed=await db.from("academic_saved_posts").delete().eq("user_id",userId).eq("post_id",postId);if(removed.error)fail("Não foi possível remover a publicação dos salvos.")}else{const added=await db.from("academic_saved_posts").insert({user_id:userId,post_id:postId});if(added.error)fail("Não foi possível salvar a publicação.")} const canonical=await db.from("academic_saved_posts").select("post_id").eq("user_id",userId).eq("post_id",postId).maybeSingle();if(canonical.error)fail("Não foi possível confirmar a publicação salva.");return {saved:Boolean(canonical.data)}; }'''
s=once(s,old,new,'save server toggle')
old='''export async function toggleAcademicSupport(userId:string,postId:string){ await requirePremium(userId); const {data}=await db.from("academic_reactions").select("post_id").eq("user_id",userId).eq("post_id",postId).eq("reaction_type","support").maybeSingle(); if(data)await db.from("academic_reactions").delete().eq("user_id",userId).eq("post_id",postId).eq("reaction_type","support"); else {await db.from("academic_reactions").insert({user_id:userId,post_id:postId,reaction_type:"support"}); const {data:post}=await db.from("academic_posts").select("user_id").eq("id",postId).maybeSingle(); if(post?.user_id)await queueInAppNotification(post.user_id,userId,"Publicação acolhida","Sua publicação recebeu um Acolher.",{kind:"support",postId});} return {supported:!data}; }'''
new='''export async function toggleAcademicSupport(userId:string,postId:string){ await requirePremium(userId); const current=await db.from("academic_reactions").select("post_id").eq("user_id",userId).eq("post_id",postId).eq("reaction_type","support").maybeSingle();if(current.error)fail("Não foi possível verificar o acolhimento.");if(current.data){const removed=await db.from("academic_reactions").delete().eq("user_id",userId).eq("post_id",postId).eq("reaction_type","support");if(removed.error)fail("Não foi possível remover o acolhimento.")}else{const added=await db.from("academic_reactions").insert({user_id:userId,post_id:postId,reaction_type:"support"});if(added.error)fail("Não foi possível acolher a publicação.");const {data:post}=await db.from("academic_posts").select("user_id").eq("id",postId).maybeSingle();if(post?.user_id)await queueInAppNotification(post.user_id,userId,"Publicação acolhida","Sua publicação recebeu um Acolher.",{kind:"support",postId})}const canonical=await db.from("academic_reactions").select("post_id").eq("user_id",userId).eq("post_id",postId).eq("reaction_type","support").maybeSingle();if(canonical.error)fail("Não foi possível confirmar o acolhimento.");const counted=await db.from("academic_reactions").select("post_id",{count:"exact",head:true}).eq("post_id",postId).eq("reaction_type","support");if(counted.error)fail("Não foi possível atualizar a contagem de acolhimentos.");return {supported:Boolean(canonical.data),supportCount:Math.max(0,counted.count??0)}; }'''
s=once(s,old,new,'support server toggle')
server.write_text(s)
print('academic actions patch applied')
