from pathlib import Path
import re
p=Path('apps/painel-ldr/src/routes/_clientarea.cliente.biblioteca.tsx')
s=p.read_text(encoding='utf-8')
imp='import { clientCreatePsychoanalysisCheckout, clientPsychoanalysisOffer } from "@/lib/psychoanalysis-commerce.functions";\n'
if imp not in s:
    s=s.replace('import { clientCreateDoMamaoTrainingCheckout, clientDoMamaoTrainingOffer } from "@/lib/training-commerce.functions";\n', 'import { clientCreateDoMamaoTrainingCheckout, clientDoMamaoTrainingOffer } from "@/lib/training-commerce.functions";\n'+imp)
s=s.replace('const fn=useServerFn(clientDigitalLibrary); const checkoutFn=useServerFn(clientCreateDigitalCheckout); const comboCheckoutFn=useServerFn(clientCreateEntrepreneurComboCheckout); const trainingOfferFn=useServerFn(clientDoMamaoTrainingOffer); const trainingCheckoutFn=useServerFn(clientCreateDoMamaoTrainingCheckout); const learningFn=useServerFn(clientLearningHub); const commentFn=useServerFn(clientAddLibraryComment); const queryClient=useQueryClient();', 'const fn=useServerFn(clientDigitalLibrary); const checkoutFn=useServerFn(clientCreateDigitalCheckout); const comboCheckoutFn=useServerFn(clientCreateEntrepreneurComboCheckout); const trainingOfferFn=useServerFn(clientDoMamaoTrainingOffer); const trainingCheckoutFn=useServerFn(clientCreateDoMamaoTrainingCheckout); const psychoOfferFn=useServerFn(clientPsychoanalysisOffer); const psychoCheckoutFn=useServerFn(clientCreatePsychoanalysisCheckout); const learningFn=useServerFn(clientLearningHub); const commentFn=useServerFn(clientAddLibraryComment); const queryClient=useQueryClient();')
s=s.replace('const trainingCheckout=useMutation({mutationFn:(market:"BR"|"INTL")=>trainingCheckoutFn({data:{market}}),onSuccess:(r)=>{window.location.href=r.url;}}); const comboCheckout=useMutation({mutationFn:(market:"BR"|"INTL")=>comboCheckoutFn({data:{market}}),onSuccess:(r)=>{window.location.href=r.url;}});', 'const trainingCheckout=useMutation({mutationFn:(market:"BR"|"INTL")=>trainingCheckoutFn({data:{market}}),onSuccess:(r)=>{window.location.href=r.url;}}); const psychoCheckout=useMutation({mutationFn:(market:"BR"|"INTL")=>psychoCheckoutFn({data:{market}}),onSuccess:(r)=>{window.location.href=r.url;}}); const comboCheckout=useMutation({mutationFn:(market:"BR"|"INTL")=>comboCheckoutFn({data:{market}}),onSuccess:(r)=>{window.location.href=r.url;}});')
s=s.replace('const {data,isLoading,error}=useQuery({queryKey:["client-digital-library"],queryFn:()=>fn({})}); const {data:trainingOffer}=useQuery({queryKey:["client-do-mamao-training-offer",paymentState],queryFn:()=>trainingOfferFn({})}); const {data:learning}=useQuery({queryKey:["client-learning-hub"],queryFn:()=>learningFn({})});', 'const {data,isLoading,error}=useQuery({queryKey:["client-digital-library"],queryFn:()=>fn({})}); const {data:trainingOffer}=useQuery({queryKey:["client-do-mamao-training-offer",paymentState],queryFn:()=>trainingOfferFn({})}); const {data:psychoOffer}=useQuery({queryKey:["client-psychoanalysis-offer",paymentState],queryFn:()=>psychoOfferFn({})}); const {data:learning}=useQuery({queryKey:["client-learning-hub"],queryFn:()=>learningFn({})});')
s=s.replace('const trainingEntitled=ownerFullAccess||Boolean(trainingOffer?.entitled);', 'const trainingEntitled=ownerFullAccess||Boolean(trainingOffer?.entitled);\n  const psychoEntitled=ownerFullAccess||Boolean(psychoOffer?.entitled);')
start=s.index('      <div className="grid grid-cols-4 gap-2 sm:gap-3">')
end=s.index('\n\n      {activeLibraryCategory? <div', start)
new_grid='''      <div className="grid grid-cols-5 gap-1.5 sm:gap-3">
        <button type="button" onClick={()=>setActiveLibraryCategory(activeLibraryCategory==="ebook"?null:"ebook")} className={`min-w-0 rounded-2xl bg-[#5b0824] px-1 py-4 text-center text-white shadow-sm transition ${activeLibraryCategory==="ebook"?"ring-2 ring-[#d6ad63]":""}`}><BookOpen className="mx-auto h-5 w-5 sm:h-6 sm:w-6"/><p className="mt-2 truncate text-[9px] font-black sm:text-xs">eBooks</p></button>
        <button type="button" onClick={()=>setActiveLibraryCategory(activeLibraryCategory==="book"?null:"book")} className={`min-w-0 rounded-2xl bg-[#5b0824] px-1 py-4 text-center text-white shadow-sm transition ${activeLibraryCategory==="book"?"ring-2 ring-[#d6ad63]":""}`}><BookOpen className="mx-auto h-5 w-5 sm:h-6 sm:w-6"/><p className="mt-2 truncate text-[9px] font-black sm:text-xs">Livros</p></button>
        <button type="button" onClick={()=>setActiveLibraryCategory(activeLibraryCategory==="training"?null:"training")} className={`min-w-0 rounded-2xl bg-[#d6ad63] px-1 py-4 text-center text-[#281605] shadow-sm transition ${activeLibraryCategory==="training"?"ring-2 ring-[#0b2341]":""}`}><GraduationCap className="mx-auto h-5 w-5 sm:h-6 sm:w-6"/><p className="mt-2 truncate text-[8px] font-black sm:text-[11px]">Negócios</p></button>
        <button type="button" onClick={()=>setActiveLibraryCategory(activeLibraryCategory==="psychoanalysis"?null:"psychoanalysis")} className={`min-w-0 rounded-2xl bg-[#5b2b86] px-1 py-4 text-center text-white shadow-sm transition ${activeLibraryCategory==="psychoanalysis"?"ring-2 ring-[#d6ad63]":""}`}><GraduationCap className="mx-auto h-5 w-5 sm:h-6 sm:w-6"/><p className="mt-2 truncate text-[8px] font-black sm:text-[11px]">Psicanálise</p></button>
        <button type="button" onClick={()=>setActiveLibraryCategory(activeLibraryCategory==="film"?null:"film")} className={`min-w-0 rounded-2xl bg-[#35101e] px-1 py-4 text-center text-white shadow-sm transition ${activeLibraryCategory==="film"?"ring-2 ring-[#d6ad63]":""}`}><Film className="mx-auto h-5 w-5 sm:h-6 sm:w-6"/><p className="mt-2 truncate text-[9px] font-black sm:text-xs">{copy.film}</p></button>
      </div>'''
s=s[:start]+new_grid+s[end:]
anchor='''        {activeLibraryCategory==="film" ? <div><div className="flex items-start gap-3"><div className="rounded-xl bg-[#35101e] p-3 text-white"><Film className="h-5 w-5"/></div>'''
psy='''        {activeLibraryCategory==="psychoanalysis" ? <div><div className="flex items-start gap-3"><div className="rounded-xl bg-[#5b2b86] p-3 text-white"><GraduationCap className="h-5 w-5"/></div><div className="min-w-0 flex-1"><p className="text-xs font-bold uppercase tracking-wide text-[#7b4aa3]">Formação · 10 módulos · 90 aulas</p><h3 className="mt-1 font-serif text-xl text-[#32155c]">Formação Online em Psicanálise</h3>{psychoEntitled?<p className="mt-1 text-xs font-bold text-emerald-700">{copy.accessState}</p>:<p className="mt-1 text-xs font-bold text-[#8a6816]">{copy.buyState}</p>}</div></div><p className="mt-4 text-sm leading-6 text-muted-foreground">Teoria, análise pessoal e supervisão · 6 encontros ao vivo · atividades · leituras orientadas · acesso vitalício aos conteúdos digitais.</p>{psychoEntitled?<a href="/cliente/treinamentos/psicanalise" className="mt-4 inline-flex min-h-11 w-full items-center justify-center rounded-xl bg-[#5b2b86] px-4 text-sm font-black text-white">Acessar formação</a>:<><div className="mt-4 rounded-xl bg-[#f7f0fb] p-3"><p className="text-xs text-muted-foreground"><span className="line-through">{market==="BR"?"R$ 599,99":"€ 100,56"}</span></p><p className="mt-1 text-lg font-black text-[#5b2b86]">{psychoOffer?(market==="BR"?money(psychoOffer.priceBrlCents,"BRL",locale):money(psychoOffer.priceEurCents,"EUR",locale)):(market==="BR"?"R$ 299,99":"€ 49,90")}</p><p className="mt-1 text-[11px] text-muted-foreground">Pagamento único · acesso vitalício aos conteúdos digitais.</p></div><button disabled={psychoCheckout.isPending||!psychoOffer} onClick={()=>psychoCheckout.mutate(market)} className="mt-3 inline-flex min-h-11 w-full items-center justify-center gap-2 rounded-xl bg-[#5b2b86] px-4 text-sm font-black text-white"><ShoppingCart className="h-4 w-4"/>Quero começar minha formação</button><a href="/formacao-psicanalise" className="mt-2 inline-flex min-h-11 w-full items-center justify-center rounded-xl border border-[#cbb7dc] px-4 text-sm font-bold text-[#5b2b86]">Ver grade completa</a></>}</div>:null}
'''
if anchor not in s: raise SystemExit('film anchor not found')
s=s.replace(anchor,psy+anchor,1)
p.write_text(s,encoding='utf-8')
